### ISSUE TITLE
[YOSHINO] [ALL] APDS-9940 ALS: Wrong sensor gain applied

### ISSUE THREAD

**Issue by kholk** [sonyxperiadev/bug_tracker#1]
**Platform:** SoMC Yoshino
**Device:** ALL
**Kernel version:** 4.4.xx
**Android version:** 8.0 (/ALL)

**Description**
The sensor configuration for the APDS-9940 ALS has wrong gain: the lux value is abnormously low

**Symptoms**
Automatic brightness on Android does not work correctly.

**How to reproduce**
Issue is always present. Check with any app that can read the sensor values, such as CPU-Z.

**Comment by jerpelea** [comment]
Fixed in vendor v4 release 

Needs the following commit 
https://github.com/sonyxperiadev/device-sony-yoshino/commit/6ef5b23dcb1cd2b79014a3ca3e0d184f14592603
