### ISSUE TITLE
[maple] Setting up fingerprint triggers crash

### ISSUE THREAD

**Issue by AnnaFangGraphite** [sonyxperiadev/bug_tracker#10]
Steps to reproduce
Tap on Settings->Security->Fingerprint. 
Select fingerprint with PIN.
After entering PIN, tap on NEXT button on "Find the sensor" screen. 
At "Keep going" screen, touch the power button gently and it will prompt the message in red "Lift finger, then touch sensor again".
Keep on touching power button, nothing happens. And wait for a minute or two, crash will happen. The adb log is shown below,

06-04 09:08:40.259  1577  1577 E AndroidRuntime: FATAL EXCEPTION: main
06-04 09:08:40.259  1577  1577 E AndroidRuntime: Process: com.android.settings, PID: 1577
06-04 09:08:40.259  1577  1577 E AndroidRuntime: java.lang.NullPointerException: Attempt to write to field 'int android.app.Fragment.mNextAnim' on a null object reference
06-04 09:08:40.259  1577  1577 E AndroidRuntime:    at android.app.BackStackRecord.run(BackStackRecord.java:780)
06-04 09:08:40.259  1577  1577 E AndroidRuntime:    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
06-04 09:08:40.259  1577  1577 E AndroidRuntime:    at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
06-04 09:08:40.259  1577  1577 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:751)
06-04 09:08:40.259  1577  1577 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:95)
06-04 09:08:40.259  1577  1577 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:154)
06-04 09:08:40.259  1577  1577 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6119)
06-04 09:08:40.259  1577  1577 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
06-04 09:08:40.259  1577  1577 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
06-04 09:08:40.259  1577  1577 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
06-04 09:08:40.259  1061  1792 I am_crash: [1577,0,com.android.settings,952647237,java.lang.NullPointerException,Attempt to write to field 'int android.app.Fragment.mNextAnim' on a null object reference,B

**Comment by jerpelea** [comment]
please add the needed information according to readme

**Comment by AnnaFangGraphite** [comment]
Sorry, here's the info
Device - Sony Xperia XZ premium
Kernel version - 4.4 (from branch n-mr1_4.4)
Android version - android-7.1.1_r55

**Comment by AnnaFangGraphite** [comment]
The oem image used was SW_binaries_for_Xperia_AOSP_N_MR1_4.4_v04_yoshino.img
system.img, userdata.img and boot.img were built by following the instructions on https://developer.sonymobile.com/open-devices/aosp-build-instructions/how-to-build-aosp-nougat-for-unlocked-xperia-devices/ Section "Build AOSP nougat 7.1"

**Comment by jamuir** [comment]
We have been able to enroll fingerprints when the PIN is added beforehand (so the fingerprint reader is functional on the XZP).  The crash described above happens when Settings prompts you to add authentication data before enrolling the fingerprint.

**Comment by jerpelea** [comment]
since the fingerprint HAL is common between android 7.1 and 8 i would suspect a bug in the Android settings that prevents the curent user to becomes authenticated if the PIN ia added before fingerprint

Please check the Android 7.1.2 and Android 8 code and cherry-pick the patch
