### ISSUE TITLE
Xperia XA2, XA2 Ultra - no incall sound over BT

### ISSUE THREAD

**Issue by jerpelea** [sonyxperiadev/bug_tracker#100]
**Platform:** nile 
**Device:** XA2, XA2 Ultra 
**Kernel version:** 4.4
**Android version:**  8.x

**Description**
Bo incall sound over BT

**Symptoms**
Bo incall sound over BT

**How to reproduce**
Dial a phone call and check if there is sound

**Comment by oshmoun** [comment]
any errors in dmesg or logcat?

**Comment by dimitar10** [comment]
**Platform:** Nile
**Device:** Pioneer H4113
**Kernel version:** 4.4.128-gf121410
**Android version:** 8.1.0r20
**Firmware version:** 8.1.6.4_r1_v11_nile

Issue still persists on XA2. The call is made circa 14:11, the headset is connected a bit earlier. Headset device name is HM1350. Attached to this message are the logcat and dmesg. For the logcat, the prunning is disabled, so hopefully it will provide some useful info.

**Discussion**
There appear to be `E/vendor.qti.bluetooth` errors in the logcat, and (by the looks of it) some dsp-related errors in the dmesg, but I can't tell for sure what is happening exactly.

[bluetooth-gsm-call-voice-routing-issue-20180427.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/1955061/bluetooth-gsm-call-voice-routing-issue-20180427.tar.gz)

**Comment by jerpelea** [comment]
@BuzzBumbleBee

**Comment by richardtullberg** [comment]
Same issue as in https://github.com/sonyxperiadev/bug_tracker/issues/96 Xperia XA2, XA2 Ultra - No incall sound

05-08 12:35:04.802     0     0 E qdsp_cvp_callback: cmd = 0x13198 returned error = 0x1
05-08 12:35:04.802     0     0 E voice_send_cvp_topology_commit_cmd: DSP returned error[ADSP_EFAILED]
05-08 12:35:04.802     0     0 E voice_setup_vocproc: Set topology commit failed err:-131
05-08 12:35:04.802     0     0 E         : setup voice failed

**Comment by jerpelea** [comment]
the fix is merged and the DSP is initialized
https://github.com/sonyxperiadev/device-sony-common/commit/11833ba1d081dfb2a8175150ea7144f6b69d9a5d

next step is routing

**Comment by jerpelea** [comment]
FIX merged 
tested and confirmed

**Comment by dimitar10** [comment]
Double checked the issue, and I can also confirm that it is fixed.
