### ISSUE TITLE
SD card only FAT32

### ISSUE THREAD

**Issue by Gaijin1** [sonyxperiadev/bug_tracker#102]
**Platform: Xperia XZ Premium** 
**Device: G8141** 
**Kernel version: 4.4.21-g4f82092-dirty** 
**Android version: 7.1.1 AOSP** 

**Description**
Device forces formatting of any SD card to be used.
Only formats in FAT32 so that files larger than 4GB can't be put on the card. (like 4K movies)

**Comment by jerpelea** [comment]
this is not a bug!
exFat is not OSS
