### ISSUE TITLE
[loire] [all] AOSP 8.1 build error

### ISSUE THREAD

**Issue by mehakimz** [sonyxperiadev/bug_tracker#103]
**Platform:** 
**Device:** 
**Kernel version:** 4.4
**Android version:** 8.1

**Description**
Android.mk in device/sony/common [has been changed](https://github.com/sonyxperiadev/device-sony-common/commit/5a20088b70290f4f17dd33902a0bf9d562119b59#diff-3ae6be565f1e33e90e0b11f768de1f6c), but the "platform/hardware/qcom/msm8998" project is still on untracked.xml (android-8.1.0_r15 branch)

**Symptoms**
error: platform/hardware/qcom/msm8998/Android.mk: No such file or directory.

**Comment by Myself5** [comment]
Please use this manifest commit from master to fix your issue https://github.com/sonyxperiadev/local_manifests/commit/7575f636bc0e8daf052c831fa78a1f7d2936324f

I didn't notice all the other branches, I'll send a PR for those ASAP.
