### ISSUE TITLE
Xperia XA2, XA2 Ultra - Bluetooth address is mirrored

### ISSUE THREAD

**Issue by luk1337** [sonyxperiadev/bug_tracker#105]
**Platform:** Nile 
**Device:** XA2, XA2 Ultra
**Kernel version:** 4.4 
**Android version:**  8.x

**Description**
Bluetooth address is mirrored.

**Symptoms**
Bluetooth address is mirrored.

**How to reproduce**
Enable Bluetooth, compare your WLAN and BT addresses only the last byte should be different.

**Comment by luk1337** [comment]
This can be fixed by disabling BTNV support in Bluetooth QTI HAL.

**Comment by luk1337** [comment]
Fixed.

**Comment by jerpelea** [comment]
please always add the commit that fixes a patch
