### ISSUE TITLE
Xperia X - SIP call Echo 

### ISSUE THREAD

**Issue by jerpelea** [sonyxperiadev/bug_tracker#106]
**Platform:*loire* 
**Device:*x, X compact* 
**Kernel version:*4.4* 
**Android version:*8.x* 

**Description**
dial a SIP phone call and check dmesg 

**Symptoms**
dial a SIP phone call and check dmesg 

**How to reproduce**
03-21 09:44:33.142     0     0 E adm_callback: cmd = 0x10328 returned error = 0x2
03-21 09:44:33.142     0     0 E send_adm_cal_block: DSP returned error[ADSP_EBADPARAM]
03-21 09:44:33.142     0     0 E         : send_afe_cal_type cal_block not found!

**Comment by jerpelea** [comment]
@kholk

**Comment by oshmoun** [comment]
that doesn't look like a kernel issue, more like acdb, maybe the id should be different. Especially since the dmic change that was done a while ago.

**Comment by jerpelea** [comment]
can you take a look?

**Comment by kholk** [comment]
YaY less stuff for me! :p

**Comment by oshmoun** [comment]
after some testing, this doesn't seem related to acdb.

**Comment by oshmoun** [comment]
Tested keyaki, seems to be affected as well!

**Comment by jerpelea** [comment]
fix
https://github.com/sonyxperiadev/device-sony-suzu/pull/49

**Comment by jerpelea** [comment]
with the fix things are improved
