### ISSUE TITLE
Proximity sensor during calls

### ISSUE THREAD

**Issue by mircoparello** [sonyxperiadev/bug_tracker#107]
**Platform:** Nile
**Device:** XA2
**Kernel version:** 4.4
**Android version:** 8.0

**Description**
Proximity sensor turns on the phone's screen during a call or while listening to an audio through earpiece. This results in accidentally muting the microphone or activating loudspeaker with your face.

**Symptoms**
As above.

**How to reproduce**
Make a call and start talking like you would do normally. In about 20-30 seconds you should notice the problem described

**Comment by jerpelea** [comment]
I am sorry but i can not replicate the bug 
Which software are you using ?
