### ISSUE TITLE
Camera focus issue

### ISSUE THREAD

**Issue by mircoparello** [sonyxperiadev/bug_tracker#108]
**Platform:** Nile
**Device:** XA2
**Kernel version:** 4.4
**Android version:** 8.0

**Description**
Camera changes focus automatically if you use manual focus
**Symptoms**
As above

**How to reproduce**
Open camera, select manual mode and manually change focus to a point close to you, take a picture: the camera will shift focus to a farther point before actually taking the picture.

**Comment by jerpelea** [comment]
The camera is not enabled in the kernel on Xperia XA2.
If you fixed the kernel please push the patches!

**Comment by jerpelea** [comment]
What software are you using ?
