### ISSUE TITLE
Gboard settings screen showing up at boot

### ISSUE THREAD

**Issue by mircoparello** [sonyxperiadev/bug_tracker#109]
**Platform:** Nile
**Device:** XA2
**Kernel version:** 4.4
**Android version:** 8.0

**Description**
When rebooting the phone a Gboard settings screen is loading up.
**Symptoms**
As above.

**How to reproduce**
Install Gboard, set it up and use it as default keyboard, reboot your phone: when the phone boots up again it should show a screen of Gboard's configuration prompt.

**Comment by Myself5** [comment]
Do you use plain AOSP or any custom ROM? Did you try a fully clean install? Do you use any third party themes for GBoard?

This shouldn't be a Device related issues as I had that happening even on the Pixel 2 XL, therefore doesn't really match the scope of this bug tracker.

**Comment by jerpelea** [comment]
Gboard issues look more like an ROM issue since the Open Devices does not touch the AOSP code
