### ISSUE TITLE
Xperia Z Ultra  Lmk bug

### ISSUE THREAD

**Issue by hzj5158888** [sonyxperiadev/bug_tracker#110]
Platform: rhine
Device:  togari 
Kernel version: 3.10
Android version: 8.1.0

**Description**
When CONFIG_MEMCG is unenable,LMK doesn't work
log like this : lowmemorykill := Error open /dev/memcg/apps/xxxxxxxx
When CONFIG_MEMCG is enable
log like this : 
03-24 12:24:57.186   400   400 E lowmemorykiller: /dev/memcg/memory.memsw.usage_in_bytes open: errno=2
03-24 12:24:57.186   400   400 I lowmemorykiller: Killing 'com.android.documentsui' (4563), uid 10010, adj 906
03-24 12:24:57.186   400   400 I lowmemorykiller:    to free 39444kB because system is under medium memory pressure oom_adj 800
03-24 12:24:57.250  1059  2973 I ActivityManager: Process com.android.documentsui (pid 4563) has died: cch+6CEM 
03-24 12:24:57.287  1059  1085 W system_server: kill(-4563, 9) failed: No such process
03-24 12:24:57.287  1059  1085 I system_server: Successfully killed process cgroup uid 10010 pid 4563 in 0ms
03-24 12:24:57.407   400   400 E lowmemorykiller: /dev/memcg/memory.memsw.usage_in_bytes open: errno=2
03-24 12:24:57.408   400   400 I lowmemorykiller: Killing 'com.android.keychain' (4577), uid 1000, adj 904
03-24 12:24:57.408   400   400 I lowmemorykiller:    to free 32948kB because system is under medium memory pressure oom_adj 800
03-24 12:24:57.488  1059  2602 I ActivityManager: Process com.android.keychain (pid 4577) has died: cch+4CEM 
03-24 12:24:57.489  1059  1085 W system_server: kill(-4577, 9) failed: No such process
03-24 12:24:57.489  1059  1085 I system_server: Successfully killed process cgroup uid 1000 pid 4577 in 0ms
03-24 12:24:57.530   400   400 E lowmemorykiller: /dev/memcg/memory.memsw.usage_in_bytes open: errno=2
03-24 12:24:57.530   400   400 I lowmemorykiller: Killing 'com.android.externalstorage' (4619), uid 10013, adj 906
03-24 12:24:57.530   400   400 I lowmemorykiller:    to free 32856kB because system is under medium memory pressure oom_adj 800
03-24 12:24:57.646  1059  2601 I ActivityManager: Process com.android.externalstorage (pid 4619) has died: cch+6CEM 
03-24 12:24:57.646  1059  1085 W system_server: kill(-4619, 9) failed: No such process
03-24 12:24:57.646  1059  1085 I system_server: Successfully killed process cgroup uid 10013 pid 4619 in 0ms
03-24 12:24:58.707   400   400 E lowmemorykiller: /dev/memcg/memory.memsw.usage_in_bytes open: errno=2
03-24 12:24:58.707   400   400 I lowmemorykiller: Killing 'android.process.media' (4603), uid 10011, adj 906
03-24 12:24:58.707   400   400 I lowmemorykiller:    to free 36132kB because system is under medium memory pressure oom_adj 800

**How to reproduce**
logcat

**Comment by hzj5158888** [comment]
of cause The bug will be fix When CONFIG_MEMCG enabled

**Comment by jerpelea** [comment]
please send a PR for all devices

**Comment by jerpelea** [comment]
your device is a legacy device and we do not provide Android 8.x support
