### ISSUE TITLE
Xperia X - Hands-free speaker/microphone volume low during SIP call

### ISSUE THREAD

**Issue by cryptes** [sonyxperiadev/bug_tracker#111]
**Platform:*loire* 
**Device:*suzu* 
**Kernel version:*3.10* 
**Android version:*6.0.1* 

**Description**
I installed CSipSimple with my SIP account and called a friend. When doing the call and switching to loudspeaker the output volume is very low (I can hear it in a quiet room only) and also the input volume is very low (I have to hold the phone right next to my mouth instead of simply in front of me. Typically I would call people with my arm nearly stretched out, in this case currently my voice is not recorded by the microphone as the input volume is too low.).

**How to reproduce**
- Install CSipSimple (latest version)
- Make a call
- Switch to loudspeaker mode

**Comment by jerpelea** [comment]
initial fix without final calibration
https://github.com/sonyxperiadev/device-sony-suzu/pull/49

**Comment by jerpelea** [comment]
any feedback after the patch is applied?

**Comment by jerpelea** [comment]
since there is no feedback after the proposed patch I will consider the issue fixed
