### ISSUE TITLE
[ALL but Ganges] Camera records dark videos

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#112]
**Platform:** all
**Device:** all
**Kernel version:** 6.4
**Android version:** 8.1

**Description**
When recording video, shutter speed is set to 1/60s, while the actual recorded video is in the range of 25fps

**Symptoms**
Recorded video is dark.

**How to reproduce**
Start opencamera app and record video in automatic mode, then in manual mode with shutter speed set to a value around 1/30. The latter video will be brighter, and closer to the actual lighting conditions.

**Comment by jerpelea** [comment]
what device are you using?

**Comment by oshmoun** [comment]
tested on kugo, with the back camera

**Comment by oshmoun** [comment]
also tested on keyaki with back camera, same observation

**Comment by jerpelea** [comment]
it has the same imx258 sensor as XZ1

**Comment by oshmoun** [comment]
An update on this (by now ancient) issue.
Ganges does not suffer from this issue. Shutter speed does change according to scene brightness.
Also, the maximum automatic ISO for ganges does not seem to be locked to 935 anymore, but actually goes up to the maximum advertised ISO value (1920)
It would be absolutely AWESOME if these changes can be somehow be made available to older devices

**Comment by jerpelea** [comment]
Ganges uses different sensor HW and can not be compared with the old devices

**Comment by jerpelea** [comment]
Ganges uses different sensor HW and can not be compared with the old devices

**Comment by oshmoun** [comment]
yes it's isocell and not imx, that much is clear.
this issue should be absolutely unrelated to that though.
the camera hardware on older devices obviously supports 1/30s shutter time. it's just that automatic exposure never chooses to go with that when recording video.
As mentioned in the original description, manually setting shutter speed works wonders.
this just can't be related to differences on camera hardware. it can only be some sort of software bug. a bug that's seemingly resolved in ganges.
please note I'm not saying this is necessarily a bug that can be ever fixed. just pointing out why i think blaming the hardware for it is plain wrong.
