### ISSUE TITLE
GPS patches are not applied

### ISSUE THREAD

**Issue by abioteau** [sonyxperiadev/bug_tracker#113]
**Platform:** ALL
**Device:** ALL
**Kernel version:** 4.4
**Android version:** 7.1.1_r55

**Description**
Execute repo_update.sh script failed for applying GPS patches with android-7.1.1_r55.

**Symptoms**
GPS patches are not applied.

**How to reproduce**
Execute repo_update.sh script.

**Comment by abioteau** [comment]
Solved with this PR https://github.com/sonyxperiadev/repo_update/pull/32

**Comment by jerpelea** [comment]
vaild for 4.4 kernel
