### ISSUE TITLE
Wifi activation is lost after a reboot

### ISSUE THREAD

**Issue by abioteau** [sonyxperiadev/bug_tracker#114]
**Platform:** Yoshino
**Device:** ALL
**Kernel version:** 4.4 (LA.UM.5.7.r1)
**Android version:** 7.1.1

**Description**
Wifi activation is lost after a reboot/power on.

**Symptoms**
After a reboot or a power off, Wifi is disabled. User needs to re-enable it at each device start-up.

**How to reproduce**
1) Enable Wifi in Settings or Quick Settings menu
2) Power off or Reboot device
3) Go to Wifi menu. Wifi is disabled even if there is a scrolling.

**Comment by jerpelea** [comment]
fix 
https://github.com/sonyxperiadev/device-sony-yoshino/commit/31082f0add7029f97bc70b5345783aeb827207ab#diff-681c32cf2f78ad235f4e202b048c728c

**Comment by abioteau** [comment]
@jerpelea You are right but fix has not been ported to n-mr1 branch. I push a PR to do that in n-mr1 branch https://github.com/sonyxperiadev/device-sony-yoshino/pull/90

**Comment by abioteau** [comment]
@jerpelea Please accept this PR before closing the issue.

**Comment by abioteau** [comment]
@jerpelea Thanks

**Comment by jerpelea** [comment]
anytime

**Comment by abioteau** [comment]
Isssue solved by https://github.com/sonyxperiadev/device-sony-yoshino/pull/90/commits/1ee48e1d47e191290424e7d9cd799b9793f92b1f
