### ISSUE TITLE
Xperia XA2 - Speaker noise after going silent

### ISSUE THREAD

**Issue by frantisheq** [sonyxperiadev/bug_tracker#116]
**Platform:** Nile
**Device:** XA2
**Kernel version:** 4.4
**Android version:** 8.1

**Description**
You can hear the speaker turning off after it get's silent.

**Symptoms**
There is a noise when the speaker should be quiet.

**How to reproduce**
Turn on touch sound in settings and touch some controls. A moment later after the touch sound finishes playing you can hear noise from the speaker before the amplifier turns off. Put the phone to your ear to hear it better. It's not very loud  but it's annoying hearing it every time you touch something or stop playing video or music.

**Comment by jerpelea** [comment]
from my the issue is resolved
please retest

**Comment by frantisheq** [comment]
confirmed, it's fixed
