### ISSUE TITLE
xperia x oreo stay on the bootlogo

### ISSUE THREAD

**Issue by pmrk74** [sonyxperiadev/bug_tracker#117]
hi

when I extract the oreo system.sin and put it in a zipper and install it via twrp, it will stay on sony logo.

please help me

**Comment by jamuir** [comment]
you can use the "Emma" flash tool to restore your device:

https://developer.sony.com/develop/open-devices/get-started/flash-tool/download-flash-tool/

This isn't the right forum for questions related to flashing via twrp.  Issues opened here should be related to Sony's open devices aosp tree.

**Comment by jerpelea** [comment]
this is not an Open Devices bug !
