### ISSUE TITLE
NFC won't read MiFare Classic cards on AOSP\LOS rom

### ISSUE THREAD

**Issue by VictorRyabov** [sonyxperiadev/bug_tracker#118]
**Platform:**  MSM8998 devices (yoshino board)
**Device:** Xperia XZ1 Compact ............... Lilac
**Kernel version:** AOSP\LineageOS latest
**Android version:** 8.1

**Description**
Hello, thanks for all the work for AOSP community!
I would like to report that after switching to AOSP on my XZ1 Compact(lilac) I have issues reading MiFare card. I will attach a logcat from stock rom where the card was read successfully and AOSP rom where it failed. This issue was confirmed by other AOSP users. 
[nfc stock 8.0.0_SUCCESS.txt](https://github.com/sonyxperiadev/bug_tracker/files/1915218/nfc.stock.8.0.0_SUCCESS.txt)
[nfc_fail_AOSP.txt](https://github.com/sonyxperiadev/bug_tracker/files/1915220/nfc_fail_AOSP.txt)

Please. help to resolve this problem. Thank you very much!

**Symptoms**
Device not reacting to MiFare Classic cards 

**How to reproduce**
Put MiFare classic card to NFC chip

**Comment by Myself5** [comment]
Works fine on both, Poplar and Maple running the latest trees on Carbon Noct here. Lilac uses the same configs and NFC hardware as those two, so I highly doubt its broken there.

![screenshot_kitcard_reader_20180416-170954](https://user-images.githubusercontent.com/6061713/38825222-1280c0ac-41ac-11e8-9868-fb8bc5560bb0.png)

**Comment by VictorRyabov** [comment]
I've tested on pure AOSP https://forum.xda-developers.com/xperia-xz1-compact/development/oreo-8-1-x-android-source-project-t3768679
And LOS https://forum.xda-developers.com/xperia-xz1-compact/development/lineageoslilac-t3745215
All clean flashed. Still not work

**Comment by Myself5** [comment]
the latter you linked isn't even based on the Sony Open Devices Project, it uses a stock based standalone bringup...

**Comment by jerpelea** [comment]
the patches are merged in AOSP now
