### ISSUE TITLE
Switch to android-7.1.2_r36

### ISSUE THREAD

**Issue by abioteau** [sonyxperiadev/bug_tracker#119]
**Platform:** ALL
**Device:** ALL
**Kernel version:** 4.4
**Android version:** 7.1.x

**Description**
Open Devices program has switched from android-7.1.2_r29 (Security Patch 2017-08-05) to android-7.1.1_r55 (Security Patch 2017-10-05) because Google had only released this latest Security Patch on Android 7.1.1 in October. They released it on Android 7.1.2 in December with android-7.1.2_r36.

Open Devices program should switch to android-7.1.2_r36 because Android 7.1.2 offers more stability than Android 7.1.1.

**Comment by jerpelea** [comment]
in the Google page  https://source.android.com/setup/start/build-numbers
there is no device attached to N2G48H | android-7.1.2_r36 | Nougat| -- | --

and there is no official image with N2G48H build number
https://developers.google.com/android/images

**Comment by jerpelea** [comment]
I will create android-7.1.2_r36 branch in repo_update if you want to submit your changes

**Comment by abioteau** [comment]
@jerpelea thanks

**Comment by jerpelea** [comment]
here is the reference
https://groups.google.com/forum/#!topic/android-building/lSlWVBBEjO8

**Comment by abioteau** [comment]
@jerpelea I see that you have created branch android-7.1.2_r36 on local_manifests repository but not already on repo_update. Could you also create branch android-7.1.2_r36 (from n-mr1) on repo_update repository. I will create PRs to submit my changes.
