### ISSUE TITLE
[MAPLE] SIM card is not recognised on Sony Xperia XZ premium

### ISSUE THREAD

**Issue by AnnaFangGraphite** [sonyxperiadev/bug_tracker#12]
After inserting the SIM card, XZ premium still reports "No SIM card - No service". Phone rebooting doesn't help.

 Device - Sony Xperia XZ premium
Kernel version - 4.4 (from branch n-mr1_4.4)
Android version - android-7.1.1_r55
The oem image used was SW_binaries_for_Xperia_AOSP_N_MR1_4.4_v04_yoshino.img
system.img, userdata.img and boot.img were built by following the instructions on https://developer.sonymobile.com/open-devices/aosp-build-instructions/how-to-build-aosp-nougat-for-unlocked-xperia-devices/ Section "Build AOSP nougat 7.1"

**Comment by jerpelea** [comment]
dmesg 
and 
logcat -b radio 
please

**Comment by AnnaFangGraphite** [comment]
Here you go, 
[sonyxzp_radio.log](https://github.com/sonyxperiadev/bug_tracker/files/1418966/sonyxzp_radio.log)
[sonyxzp_dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/1418968/sonyxzp_dmesg.log)

**Comment by jerpelea** [comment]
back to my previous request  ( i edited it)

**Comment by jamuir** [comment]
@jerpelea:  could you explain what was wrong with the previous logs there were posted?

**Comment by jamuir** [comment]
ah... a classic mistake :-)  sorry about that.

note that the radio log suggests it may just be a missing library:
```
06-06 09:48:52.801   681   681 E RILD    : dlopen failed: dlopen failed: library "libpdmapper.so" not found
```

**Comment by jerpelea** [comment]
i discovered the issue and will be fixed in the shortest possible time

**Comment by jerpelea** [comment]
the fix will come in vendor v5 
i am sorry for the inconvenince

**Comment by jamuir** [comment]
no worries.  thanks!

**Comment by jerpelea** [comment]
thanks for reporting the issue

**Comment by abioteau** [comment]
Only available for Oreo version. When will you deliver vendor v5 for Nougat MR1 Kernel 4.4?

**Comment by jerpelea** [comment]
As soon as it is ready

**Comment by abioteau** [comment]
Nice ;-)
