### ISSUE TITLE
Xperia XA2 - USB Tethering dysfunctional on several Linux distros

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#120]
**Platform:** Nile
**Device:** Pioneer H4113
**Kernel version:** 4.4.124 - (prebuilt @ ffba6bd -dirty, branch: aosp/LA.UM.6.4.r1)
**Android version:** 8.1.0r20
**FW version:** 8.1.6.4_r1_v11_nile

**Description**
USB tethering appears to be dysfunctional when the device is connected to a PC running a Linux distro. It did not work on Ubuntu 14.04, 16.04 and Mint 17.3. Tethering on Windows 7 works just fine.

**Symptoms**
When tethering is enabled the switch shows that USB tethering is engaged, but the PC never receives the connection, i.e. ``$ifconfig`` on the PC does not show the usb0 interface. Additionally, running ``$lsusb``, shows different product values between running in adb mode and in tethered mode. I've added the output from ``$lsusb -d 18d1:81f3 -v`` in the attached logs as well.

**How to reproduce**
Connect the device to a PC running one of the aforementioned Linux distros and enable USB tethering ``Settings -> Network & Internet -> Hotspot & Tethering --> USB Tethering``

**Discussion**
If it's of any help, from what I could see in the dmesg, basically the following extra lines are present when tethering is successful (in comparison to when tethering is not successful):
```
[   41.535596] RNDIS_IPA NetDev pipes were connected
[   41.535703] IPv6: ADDRCONF(NETDEV_CHANGE): rndis0: link becomes ready
```
When tethering is successful, the former is printed when ``rndis_ipa_pipe_connect_notify`` in ``drivers/net/ethernet/msm/rndis_ipa.c``, which in turn is (probably) called by ``ipa3_usb_connect_teth_prot`` in  ``drivers/platform/msm/ipa/ipa_clients/ipa_usb.c``

The latter is probably not shown when tethering is not successful because ``netdev_state_change`` from ``net/core/dev.c`` is never called.

Also, when ``$ifconfig`` is issued from the device, the ``rmnet_data0`` interface is missing.

**Logs**

Attached to this message are the compressed logs including the dmesg and logcat from both functional and dysfunctional tethered devices.

[xa2-tethering-logs.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/1932435/xa2-tethering-logs.tar.gz)

**Comment by dimitar10** [comment]
Additional testing revealed that **USB tethering works correctly** on Arch Linux running **kernel  4.16.3**. The newest kernel version of the distros mentioned above is 4.13.

**Comment by jerpelea** [comment]
This is not an Android bug since it appears to be distro specific

**Comment by jerpelea** [comment]
you can check  a7d7acbb1251462076069cea8d8f46f36ad8eaa1

**Comment by dimitar10** [comment]
Thank you very much for the suggestion, Alin.

**Comment by jerpelea** [comment]
this does not appear to be a AOSP bug
