### ISSUE TITLE
Xperia XA2 - In-call audio unavailable after routing to speaker

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#122]
**Platform:** Nile
**Device:** Pioneer H4113
**Kernel version:** 4.4.124 - (prebuilt @ ffba6bd -dirty, branch: aosp/LA.UM.6.4.r1)
**Android version:** 8.1.0r20
**Firmware version:** 8.1.6.4_r1_v11_nile

**Description**
In-call audio becomes unavailable when the user tries to route the call on speaker, by clicking the 'speaker' button in the in-call screen and there is silence at both ends of the call. 

**Symptoms**
All following calls until reboot are muted, but the end call sound signal is clearly audible on the speaker when the user tries to end the call. The same issue happens even when the user is using earphones.

**How to reproduce**
Establish a GSM call, it does not matter if it's incoming or outgoing. After the call is established click the speaker icon to route the audio to the speaker.

**Logs**
Attached to this message you can find the logcat and dmesg.

[incall-audio-unavailable-speaker-20180424.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/1943609/incall-audio-unavailable-speaker-20180424.tar.gz)

**Comment by jerpelea** [comment]
[  132.478433] voice_get_cal: No cal data for cal 8!
[  132.478916] voice_send_cvs_register_cal_cmd: Voice_get_cal failed for cal 7!
[  132.480150] qdsp_cvp_callback: cmd = 0x11371 returned error = 0x2
[  132.480469] voice_send_cvp_register_dev_cfg_cmd: DSP returned error[ADSP_EBADPARAM]
[  132.482555] voice_get_cal: No cal data for cal 5!
[  132.482708] voice_send_cvp_register_cal_cmd: Voice_get_cal failed for cal 2!
[  132.483666] voice_get_cal: No cal data for cal 6!
[  132.483822] voice_send_cvp_register_vol_cal_cmd: Voice_get_cal failed for cal 3!
[  132.485649] qdsp_cvp_callback: cmd = 0x112c2 returned error = 0x1
[  132.485773] voice_send_vol_step_cmd: DSP returned error[ADSP_EFAILED]
[  132.485994] voice volume failed

**Comment by jerpelea** [comment]
@BuzzBumbleBee

**Comment by dimitar10** [comment]
Issue still present on:

**Platform:** Nile
**Device:** Pioneer H4113
**Kernel version:** 4.4.130-ge9dcd44 -dirty
**Android version:** 8.1.0r26
**Firmware version:** 8.1.6.4_r1_v12_nile

**Logs**

The call is made circa 13:26, speaker pressed after 25 seconds. The archive contains both the logcat and the dmesg.

[incall-audio-unavailable-speaker-20180510.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/1994571/incall-audio-unavailable-speaker-20180510.tar.gz)

**Comment by jerpelea** [comment]
the fix is merged and the DSP is initialized
https://github.com/sonyxperiadev/device-sony-common/commit/11833ba1d081dfb2a8175150ea7144f6b69d9a5d

next step is routing

**Comment by jerpelea** [comment]
please check the status

**Comment by dimitar10** [comment]
The issue is no longer present on devices running the latest kernel (4.4.130-67827af3), as well as the update from above.
