### ISSUE TITLE
Xperia XA2 - UI glitch before loading recovery, factory reset or offline charge

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#124]
**Platform:** Nile
**Device:** Pioneer H4113
**Kernel version:** 4.4.128-gf121410
**Android version:** 8.1.0r20
**Firmware version:** 8.1.6.4_r1_v11_nile

**Description**
A scrambled image is displayed for a moment during booting to recovery, booting to the offline charging screen and before a factory reset begins.

**Symptoms**
Before showing the recovery menu, the battery charging animation or the Erasing... animation on factory reset, a scrambled image is displayed for a short moment.

**How to reproduce**
1. Boot the device to recovery by holding the Power + Volume DOWN button combination `OR` 
 power off the device and connect it to a PC via USB `OR` 
 perform a Factory reset from Settings`OR` 
 issue `$ adb reboot recovery` command
2. Observe the display

**Logs**
Attached to this message there is snapshot of the glitch.

![dsc_0024_burst20180427151318637](https://user-images.githubusercontent.com/33422321/39364509-b8f0b1ee-4a1d-11e8-8a0a-602a1fc51248.JPG)

**Comment by jerpelea** [comment]
I can not replicate the bug with the latest build on any of my XA2 devices 
please post the dmesg from boot so that we can check with panel you have 

Thanks
Alin

**Comment by jerpelea** [comment]
please check the status

**Comment by dimitar10** [comment]
The issue is still present. You can find the dmesg below.

[dmesg-ui-glitch-20180521.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2022589/dmesg-ui-glitch-20180521.tar.gz)

**Comment by jerpelea** [comment]
@kholk do you have this issue?

**Comment by kholk** [comment]
This can either be an IOMMU related issue (but since it is not reproducible on at least one other device we can exclude that) or a panel timings one.

Will check as soon as my fiber comes back up, as my pioneer is seriously outdated.

**Comment by jerpelea** [comment]
the issue is confirmed on the mdss_mdp.panel=1:dsi:0:qcom,mdss_dsi_td4322_truly_fhd_cmd:config0:1:none:cfg:single_dsi 
panel

**Comment by jerpelea** [comment]
fix 
https://github.com/sonyxperiadev/kernel/commit/5d0e06c3c4713425611a832b64fedc30bdf7e1ed

**Comment by jerpelea** [comment]
Fix:
sonyxperiadev/kernel@20d73fe
sonyxperiadev/kernel@56bae35
https://github.com/sonyxperiadev/device-sony-nile/commit/746947a675289e250ad90bc7c7ac14f5c165bd5f

**Comment by dimitar10** [comment]
I can confirm that the issue was fixed with the latest commits, and I will mark it as closed.
