### ISSUE TITLE
[TONE/Kagura] External microsd is mounted as a portable storage

### ISSUE THREAD

**Issue by djselbeck** [sonyxperiadev/bug_tracker#125]
**Platform:** 
Tone
**Device:** 
Kagura
**Kernel version:** 
4.4.128-gf12141096c08-dirty
**Android version:** 
8.1.0
**Description**
An external microsd card is mounted as a portable storage.

**Symptoms**
Music/media files residing on the card are not picked up my mediascanner. Storage is only accessible through StorageFramework

**How to reproduce**
Insert an microsd

**Comment by jerpelea** [comment]
https://source.android.com/devices/storage/adoptable

**Comment by djselbeck** [comment]
The behavior is still different from e.g. Stock Sony Rom where applications can access files through normal File-API and MediaFiles are scanned as Library items. Which was the case for AOSP before the migration to FBE

**Comment by jerpelea** [comment]
stock used FDE 
AOSP uses FBE

**Comment by djselbeck** [comment]
I don't want to argue, that FBE can not be used with an µSD used as an adoptable storage. But I would like to get my music (on my µSD) back in my library. Otherwise the whole microSD is kind of useless ;).

And every stock rom scans media files on microsd cards to its Android system library.

**Comment by jerpelea** [comment]
FBE is default on all new devices even on Sony SW

**Comment by jerpelea** [comment]
to get nack to FDE you have to revert locally this commit
https://github.com/sonyxperiadev/device-sony-tone/commit/1a2bb287682b214bad1521ccd4738fec85dc8bdb#diff-a0b9c2a4bf60ebe771d72c2c2beabac4

**Comment by djselbeck** [comment]
Setting the property "persist.sys.adoptable_fbe" to true helps as a workaround to have media scaned from the µsd.

**Comment by jerpelea** [comment]
please pr in common

**Comment by djselbeck** [comment]
I'm not sure if it is a good thing to enable by default.

It basically enables to use an external SD as an adoptable storage which is, like you said, unsupported. I've no idea what can happen if a user does it. 

The main problem basically is that the system only scans "stable" storage devices and only adoptable devices are considered "stable" and visible to applications directly (normal file interface).

There was a code review request for android to separate the "visible" property but it was rejected:

https://android-review.googlesource.com/q/topic:%2522add_visible_flag%2522

Rejection:
https://android-review.googlesource.com/c/platform/system/core/+/538376

**Comment by jerpelea** [comment]
good point
lets see how xz2 is configured
