### ISSUE TITLE
[Yoshino][Lilac] Front camera lacks auto focus

### ISSUE THREAD

**Issue by djselbeck** [sonyxperiadev/bug_tracker#126]
**Platform:** 
Yoshino
**Device:** 
Lilac
**Kernel version:** 
4.4.128-g33dca7663665-dirty
**Android version:** 
8.1.0
**Description**
The front camera of the device does not use or present focus controls.

Sadly I'm not sure if it is an issue or intended because I can not check with stock rom. But it looks like it should use a focus (kagura for example has autofocus both for front & rear camera)

**Symptoms**
Pictures are unsharp from time to time (depending on the distance)

**How to reproduce**
Use camera and try to tap to focus, Open Camera does not present focus controls for front camera

**Comment by jerpelea** [comment]
imx219 is a wide sensor and it has a fixed focus
https://github.com/sonyxperiadev/device-sony-lilac/blob/master/rootdir/vendor/etc/camera/camera_config.xml#L29

**Comment by djselbeck** [comment]
Ok sorry, my mistake.

I was unsure because pictures in not so bright environments are really unsharp. I think it is a very aggressive noise reduction because RAW pictures (taken with OpenCamera) present much more details (and of course noise).

Would be nice if noise reduction could be a bit less aggressive in low light situations for the front camera.

Btw. is there another way of communicating with you guys? Like an IRC for example?

**Comment by jerpelea** [comment]
we have a slack channel for revelopers but for bugs please use github
