### ISSUE TITLE
[Pioneer] - Android 8.1 - Camcorder preview sometimes flickers

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#129]
**Platform:** Nile
**Device:** Pioneer H4113
**Kernel version:** 4.4.130-ge9dcd44 -dirty
**Android version:** 8.1.0r26
**Firmware version:** 8.1.6.4_r1_v12_nile

**Description**
After changing front/rear camera, taking some photos and recording some videos, the camcorder will start to flicker (see attached video).

**Symptoms**
 The camcorder preview flickers - blikns green (see attached video).

**How to reproduce**
1. Open Camera app
2. Take some photos and record some videos switching between front and rare camera

Outcome: Eventually, the camcorder preview will start to flicker.

**Logs**

Important timestamp: 13:01

The archive contains a sample video, the logcat and the dmesg.

[xa2-camera-flicker.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/1994678/xa2-camera-flicker.tar.gz)

**Comment by kholk** [comment]
Definitely cool.

Does it happen when you are using the front camera or the rear camera, or whenever you do the crazy switch does it happen on any?

Thanks!

**Comment by dimitar10** [comment]
As far as I can tell, the issue happens very randomly after taking a few videos, regardless of which camera you are using. It is not even necessary to switch between cameras in order to trigger the flicker.

**Comment by kholk** [comment]
Okay now this is a good description.

We'll look into it!

**Comment by dimitar10** [comment]
Re-tested with:

**Platform:** nile
**Device:** pioneer (H4113)
**Kernel version:** 4.4.140-gdc5bc38
**Android version:** 8.1.0-r35
**Firmware version:** 8.1.6.4_r1_v14_nile

Outcome is the same.

**Comment by dimitar10** [comment]
Re-tested with:

**Platform**: nile
**Device**: pioneer (H4113)
**Kernel version**: 4.4.162-gc9835ae
**Android version**: 8.1.0-r51
**Firmware version**: 8.1.6.4_r1_v16_nile

Outcome is the same.

**Comment by jerpelea** [comment]
In corner cases light conditions the camera will flicker 
We can not solve the issue for Android 8
