### ISSUE TITLE
[loire] mtp is broken for large files

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#13]
**Platform:** loire
**Device:** kugo
**Kernel version:** 4.4 
**Android version:** 8.0

**Description**
MTP seems broken on loire devices.

**Symptoms**
Copying a large file to the device using MTP causes MTP to hang right at the end of the copying process.

**How to reproduce**
Try to copy a file larger than 400mb to the device using mtp.

**Comment by jerpelea** [comment]
bug reproduced on both suzu and kugo

**Comment by humberos** [comment]
yes, confirmed.
All loire devices are affected.

**Comment by dimitar10** [comment]
In addition to the previous comments, this issue is valid for **files of any size**, and not just for large files.

**Comment by oshmoun** [comment]
If one waits long enough, the file transfer reports an error, but the file does get written to the device.
Compared with md5sum, and the transfered file seems intact.

**Comment by kholk** [comment]
Please change the title tag to Loire.

**Comment by jerpelea** [comment]
fixed
