### ISSUE TITLE
[Tone][Yoshino] - Offline charger doesn't work properly

### ISSUE THREAD

**Issue by Paulbouchara** [sonyxperiadev/bug_tracker#130]
Platform: Tone (all chargers), Yoshino (Fast charger)
Device: all
Kernel version: 4.4.132 
Android version: 8.1

Description
The device doesn't charge properly, it goes in a bootloop.

Symptoms
For Tone : Sony logo and instant reboot
In custom ROM Tone : Sony logo, enters offline charge and reboots after 10 secs.
Yoshino : TBD

How to reproduce
Plug a regular charger for Tone devices.
Plug a fast charger for Yoshino devices.

**Comment by jerpelea** [comment]
https://pastebin.com/URLmwTgZ

UART log on dora

**Comment by jerpelea** [comment]
an interesting commit 
https://android.googlesource.com/kernel/msm/+/1e352b291031d023d2677fa59842542deb8a3a46

**Comment by jamuir** [comment]
I tried adapting https://android.googlesource.com/kernel/msm/+/1e352b291031d023d2677fa59842542deb8a3a46
and ended up with a kernel that does not detect usb connections.

Even worse, I turned off my device and now it seems to be bricked :-(

It does not respond to the power button and does not respond to usb.

**Comment by jerpelea** [comment]
@jamuir 
fastboot mode :
 - disconect USB 
 - keep volume up and power for 45 seconds
 - release power and insert usb 

we are looking on the USB issue

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/device-sony-common/pull/487

**Comment by jerpelea** [comment]
@Paulbouchara please test the latest fixes

**Comment by jerpelea** [comment]
the bug seems to be fixed

**Comment by abioteau** [comment]
@jerpelea should fix be backported to 8.0?

**Comment by jerpelea** [comment]
if you can please do it

**Comment by abioteau** [comment]
I do not know which commits fixes it?

**Comment by jerpelea** [comment]
in common 4ac93ddeb596845b68adcfc8bd60794c3f076cde
and the healthd updates

**Comment by abioteau** [comment]
@jerpelea Do you means this PR https://github.com/sonyxperiadev/kernel/pull/1586 for healthd updates or more stuff?

**Comment by abioteau** [comment]
Also this PR https://github.com/sonyxperiadev/device-sony-common/pull/487?

**Comment by jerpelea** [comment]
it has to be tested on 8.0
