### ISSUE TITLE
Xperia XZ1 - reboots entering recovery and charger

### ISSUE THREAD

**Issue by icefalcon2225** [sonyxperiadev/bug_tracker#132]
**Platform:**  yoshino
**Device:** Xperia XZ1 G8342 (poplar)
**Kernel version:**  4.4.124-g02e86eaeedd4-594686-g90dd1746067a-dirty
**Android version:**  8.1.0_r20 OPM2.171019.029

**Description**
Often (maybe 35%-50% of the time), when the device is trying to draw on the screen outside of Android (e.g., using the minui library), the device reboots right around the time it would be initializing the graphics or doing the first draw attempt.  The easiest way to reproduce this is with the recovery image, but it also happens with the battery image that the phone displays when it is turned off but charging.

**Symptoms**
The phone often reboots when entering recovery or starting to charge when powered off.

**How to reproduce**

Here are the steps that reproduce the issue:

   1) From powered off, go into recovery with the  VOLUME_DOWN + POWER button combo.  This always seems to work properly.

   2) While in recovery, issue an "adb reboot recovery" command to the phone from the host computer.  The phone will reboot, and one of two things happen:

       a) Sometimes (maybe 1/2 to 2/3 of the time) the device successfully gets back into recovery on the first attempt.  

        b) Sometimes (about 1/3 to 1/2 of the time) the device reboots near the time when it would enter recovery.  Instead of showing recovery, the LED in the top left flashes blue a few times, then some red and some blue, then the phone reboots.  At this point, either 2a or 2b can happen.  It seems like it is a little bit streaky; that is, if 2b happens then it is more likely to happen again a few times in a row.  Note that once recovery successfully comes up, there are no issues --- it only seems to have a problem with initializing the graphics (and/or the first draw), and once it makes it past that point everything is okay.

There are other ways to make this issue (or something similar) happen.  While step 2 used an "adb reboot recovery" from recovery, you see the same problem happen if you do an "adb reboot recovery" from Android (after the phone has successfully booted into system).  You also see it occur if you try to charge the device while it is off --- sometimes the battery image appears, but sometimes the phone reboots and then boots into Android instead.

This problem is occurring with an image built using the Oreo 8.1 AOSP instructions on the Sony developer web site.  The image contains the pre-built kernel (the one that comes with the AOSP distribution) for the Xperia XZ1.  There are no modifications to the code.

**Comment by oshmoun** [comment]
can you please check if you get any oogs in pstore on the subsequent boot after this kind of crash?
also, were you testing recovery while connected through usb or did you also while device's usb port was free?

**Comment by icefalcon2225** [comment]
Here is the **console-ramoops** after the phone rebooted when trying to enter recovery.  I was in recovery, did an "adb reboot recovery", it failed once to enter (e.g., it rebooted right as recovery would normally appear), then it successfully entered recovery on the next try.  

I was hooked up to the computer via a USB cable the whole time.

[console-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2036424/console-ramoops-0.txt)

**Comment by jerpelea** [comment]
Thanks for the detailed description 
I managed to reproduce it and we are investigating the issue

**Comment by icefalcon2225** [comment]
Thank you for the update.  Hopefully the issue is straightforward to resolve since you can reproduce it.

Also, I moved to the current upstream referenced by the Sony developer build instructions (android-8.1.0_r26  OPM2.171019.029.B1) and confirmed that the issue still exists in that code base.

**Comment by jerpelea** [comment]
The issue is caused by the cont splash handover and the code can be found in the following git 
https://github.com/sonyxperiadev/kernel/tree/aosp/LA.UM.6.4.r1/drivers/video/fbdev/msm

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/kernel/commit/68cfce172010af2695d45c2eda97433079b36d28

**Comment by icefalcon2225** [comment]
I confirmed that these fixes correct the issues that I was seeing.  The device is working properly now.  Thank you for resolving this so quickly.
