### ISSUE TITLE
[Maple] Device does not boot

### ISSUE THREAD

**Issue by abioteau** [sonyxperiadev/bug_tracker#134]
**Platform:** Yoshino
**Device:** Maple
**Kernel version:** LA.UM.5.7.r1 (prebuilt or build on 1cd6d7b)  
**Android version:** 8.0.0_r30
**Vendor image:** 8.0.5.7_r1_v10

**Description**
Device is blocked at Android boot logo.

**Symptoms**
Device is blocked at Android boot logo.

**How to reproduce**
Boot device

**Logs**
[log.txt](https://github.com/sonyxperiadev/bug_tracker/files/2057435/log.txt)

**Comment by jerpelea** [comment]
when did the issue happen (after which sync date)?
Thanks
Alin



On Thu, May 31, 2018 at 10:44 AM +0200, "Adrien Bioteau" <notifications@github.com<mailto:notifications@github.com>> wrote:


Platform: Yoshino
Device: Maple
Kernel version: LA.UM.5.7.r1 (build 1cd6d7b)
Android version: 8.0.0_r30
Vendor image: 8.0.5.7_r1_v10

Description
Device is blocked at Android boot logo.

Symptoms
Device is blocked at Android boot logo.

How to reproduce
Boot device

Logs
log.txt<https://github.com/sonyxperiadev/bug_tracker/files/2057435/log.txt>

**Comment by abioteau** [comment]
@jerpelea I synchronize my source yesterday

**Comment by jerpelea** [comment]
@abioteau 
when was last time you syncronized before yesterday?

**Comment by abioteau** [comment]
@jerpelea When i execute repo_update.sh, it fails to apply patch https://github.com/sonyxperiadev/repo_update/blob/android-8.0.0_r30/repo_update.sh#L39. Due to that following patches https://github.com/sonyxperiadev/repo_update/blob/android-8.0.0_r30/repo_update.sh#L39-L41 are not applied on my environment, perhaps it should explain my issue.

**Comment by jerpelea** [comment]
please test
I will build a test 8.0 ASAP

**Comment by abioteau** [comment]
The following patch has been merged on AOSP
* https://android-review.googlesource.com/c/platform/build/soong/+/266354 => Patchset 28 as on repo_update.sh
* https://android-review.googlesource.com/c/platform/build/soong/+/266393 => Patchset 16 as on repo_update.sh
* https://android-review.googlesource.com/c/platform/build/soong/+/365413 => Patchset 3 instead of Patchset 2 used on repo_update.sh
* https://android-review.googlesource.com/c/platform/build/soong/+/367312 => Patchset 5 instead of Patchset 3 used on repo_update.sh
* https://android-review.googlesource.com/c/platform/build/soong/+/367332=> Patchset 10 instead of Patchset 2 used on repo_update.sh

and this one has been abandoned
* https://android-review.googlesource.com/c/platform/build/soong/+/367392 => Patchset 7 instead of Patchset 2 used on repo_update.sh

**Comment by abioteau** [comment]
@jerpelea I have found with some difficulty a way to apply all platform/build/soong patches only from existing AOSP commits.

https://github.com/abioteau/repo_update/commit/3f98afd9f98d0ec13375e119d7817bc11ef036bc

But after rebuild, it does not solve the issue.

**Comment by jerpelea** [comment]
Fix
https://github.com/sonyxperiadev/repo_update/commit/f935bda2610ab0a9cbc1c83cd662dc95f1dfb00a

missing sepolicy backports
https://github.com/sonyxperiadev/device-sony-sepolicy/commit/5f41853b08699804a2be3be4f474eb8ef97a48c5
https://github.com/sonyxperiadev/device-sony-sepolicy/commit/f5761f0dc15a27d1b5b745d26c8134b9a2bc3083
https://github.com/sonyxperiadev/device-sony-sepolicy/commit/99050f2fb73f122f061d2236977e8def0a0e62cd
https://github.com/sonyxperiadev/device-sony-sepolicy/commit/7bc5256edc59640ac0d57b2a5cc136094dd8773c


Tested 
suzu - ok 
maple - ok

**Comment by abioteau** [comment]
@jerpelea Thanks
