### ISSUE TITLE
[Docs] libncurses5 required during build process

### ISSUE THREAD

**Issue by onitake** [sonyxperiadev/bug_tracker#135]
**Platform:** Debian buster amd64
**Device:** kugo
**Kernel version:** 4.4
**Android version:** 8.0

**Description**
The AOSP documentation should mention that libncurses5 is required during the build process.

**Symptoms**
After following the instructions on https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-oreo-8-0-kernel-4-4#tutorial-step-5, I get the following error:
```
[  0% 149/83246] host C++: validatekeymaps <= frameworks/base/tools/validatekeymaps/Main.cpp
...
/home/build/android/prebuilts/clang/host/linux-x86/clang-3859424/bin/clang++.real: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
```
The documentation should mention that `libncurses5` must be installed - step 2 would be an appropriate place for this.

Debian buster only comes with `libncurses6` preinstalled, but `libncurses5` is still provided as a compatibility package. Other Linux distributions (i.e. Ubuntu) will likely move soon as well.

**Comment by jerpelea** [comment]
The build guide recommands Ubuntu

If you use another distribution there may be missing dependencies

**Comment by onitake** [comment]
Maybe.
But Ubuntu will update their default libncurses in the future too, and it's better to be clear about that requirement.

**Comment by jerpelea** [comment]
I will consider it

**Comment by onitake** [comment]
In addition to `libncurses5`, the build scripts also require `rsync`, which may not be installed on the build system by default. This is particularly true for minimal build environments, and I'm pretty sure it's not distribution specific.
May I suggest adding this requirement as well?
Thanks!

**Comment by jerpelea** [comment]
fixed
