### ISSUE TITLE
[tone][kagura] Focus dmesg spam

### ISSUE THREAD

**Issue by erikcas** [sonyxperiadev/bug_tracker#137]
tone
kagura
LA.UM.6.4.r1 
android-8.1

**Description**
Upon using focussing on camera usage, dmesg is spammed with gpio47 references
See https://git.choose-a.name/snippets/50

**Symptoms**
Dmesg spam

**How to reproduce**
Open cam, focus, zoom, focus again

===========================
This has to be an issue using cash and tmvl53l0. As the dmesg repeatedly fires "i2c-msm-v2 7577000.i2c" issues with gpio47

see https://github.com/sonyxperiadev/kernel/blob/aosp/LA.UM.6.4.r1/arch/arm/boot/dts/qcom/msm8996-tone-kagura-common.dtsi#L32

**Comment by erikcas** [comment]
I was able to silence it by applying this:
https://github.com/choose-a/android_kernel_sony_msm/commit/84fe1b7b1eb7c871be6188b329f7ba9926228e75

**Comment by jerpelea** [comment]
please add commit message

**Comment by jerpelea** [comment]
@erikcas please PR

**Comment by erikcas** [comment]
pr done
