### ISSUE TITLE
Emma flashtool no longer starts up

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/bug_tracker#140]
**Platform:** 
**Device:** 
**Kernel version:** 
**Android version:** 

**Description**
Today (2018-06-19), when I try to run the Emma flashtool (on a Windows 10 machine), it reports that it needs a re-install and directs me to the url: https://developer.sonymobile.com/flashtool

That url is redirected to https://developer.sonymobile.com

After navigating to the Sony Open Devices page from there, I am eventually able to download the "November 9, 2017" version of Emma.

After I re-install and run the newly downloaded version, I get the same message: "Emma needs a reinstallation".

**Symptoms**
Emma keeps requesting a re-install.

**Comment by jerpelea** [comment]
Flashtool has been updated 

Please download the new version 
https://developer.sony.com/develop/open-devices/get-started/flash-tool/download-flash-tool/

**Comment by jamuir** [comment]
thanks for updating the webpage.  I can see the "June 20, 2018" version now, which was not there yesterday.  I will give that a try.

**Comment by jamuir** [comment]
I was able to install the new version of Emma and flash a device.
