### ISSUE TITLE
[Pioneer] Unable to stream music with google play music

### ISSUE THREAD

**Issue by opendata26** [sonyxperiadev/bug_tracker#142]
**Platform:**  Nile
**Device:**  Pioneer
**Kernel version:**  4.4
**Android version:**  8.1

**Description**
When streaming audio from google play music ACDB fails to get device lookup information for something and then seems to stop the mixer configuration. This could also be the total opposite where kernel silently fails to initialize a DAI causing ACDB to fail. Seems to go on forever until phone is restarted or audio stopped.
 
**Symptoms**
Tons of logspam and  systemui crash.

**How to reproduce**
Stream audio with google play music.

logcat:  https://ptpb.pw/qjP2
dmesg: https://ptpb.pw/rVXW - basically that repeating for ever

**Comment by oshmoun** [comment]
here's something you can try, assuming you have root:
remount /odm in rw mode
remove libacdbloader.so
reboot
retry music streaming

**Comment by richardtullberg** [comment]
Do you have a USB headset connected? It is so strange that it tries to set ACDB id to 45... Which is either USB or Voice Tx.

**Comment by opendata26** [comment]
Sorry, missed reply, will try in a bit and no, I have no headset

**Comment by opendata26** [comment]
@oshmoun okay, same stuff in dmesg, and same issue, just this time the speakers go kinda crazy then systemui crash due to logspam from the audio hal being unable to find pcm device

**Comment by richardtullberg** [comment]
Could you tell me exactly how to reproduce this issue and how often it is reproducible when following the steps.
What I think I understand:
1. Get a subscription to Google Play Music 
2. "Stream" a song through internal speakers

How long until the issue should occur?

**Comment by opendata26** [comment]
To reproduce it's:
Buy any song at all feom play music, doesn't need to be subscription
Just try to play it like a local song in the app with either headphones or speakers
About 5-10 seconds later music will stop

**Comment by richardtullberg** [comment]
I have been trying to reproduce this for 2 days now.
I have gotten it only once, and that was the absolute first time i tried it.

1. I bought a song on Google Play Music and played it.
2. After ca 10sec It "crashes", the music stops and the app closes down.
3. I check the log that I took and find that it seems similiar to your log.
4. I can't get it to happen again, I buy a new song and tries with that, I try different settings (Only streaming, no chaching, downloaded content, with/without equalizer, I remove my account and delete app data Music/Play, both speakers and headphones and switching as music plays) but I can't get it to ever reproduce again.

Is there something I might be doing wrong?

**Comment by opendata26** [comment]
You are doing the right thing... I get it every time though.

**Comment by richardtullberg** [comment]
I see allot of GMS errors, so maybe we need to just double check we have the same version of the apps.

My versions of the apps are:
Google Play Music: 8.13.7350-1.G
Google Play Store: 10.8.33-all [0] [PR] 205773289

**Comment by jerpelea** [comment]
@richardtullberg @opendata26  updates on this one

**Comment by richardtullberg** [comment]
@jerpelea @opendata26  I can't reproduce it, tried this morning again and can't get it to happen.

**Comment by opendata26** [comment]
Seems to be fixed, not sure whether  it's new blobs, gapps update or tree updates that fixed it though
