### ISSUE TITLE
kernel makefile uses ANDROID_PRODUCT_OUT before it is defined

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/bug_tracker#144]
**Platform:** all
**Device:** all
**Kernel version:** 
**Android version:** oreo

**Description**
https://github.com/sonyxperiadev/vendor-sony-kernel/commit/0b6166c96b1e110d56e4c92a61e4a29f2a399a62

in the commit above, `ANDROID_PRODUCT_OUT` is used before it is defined:

```bash
~/ggit/sony$ source build/envsetup.sh 
including device/google/dragon/vendorsetup.sh
including device/google/marlin/vendorsetup.sh
including device/google/muskie/vendorsetup.sh
including device/google/taimen/vendorsetup.sh
including device/graphite/generic/vendorsetup.sh
including device/sony/akari/vendorsetup.sh
including device/sony/apollo/vendorsetup.sh
including device/sony/blanc/vendorsetup.sh
including device/sony/discovery/vendorsetup.sh
including device/sony/dora/vendorsetup.sh
including device/sony/kagura/vendorsetup.sh
including device/sony/keyaki/vendorsetup.sh
including device/sony/kugo/vendorsetup.sh
including device/sony/lilac/vendorsetup.sh
including device/sony/maple/vendorsetup.sh
including device/sony/pioneer/vendorsetup.sh
including device/sony/poplar/vendorsetup.sh
including device/sony/suzu/vendorsetup.sh
including vendor/graphite/vendorsetup.sh
including sdk/bash_completion/adb.bash
~/ggit/sony$ lunch aosp_g8142-userdebug
mkdir: cannot create directory ‘/obj’: Permission denied
mkdir: cannot create directory ‘/obj’: Permission denied
cp: cannot create regular file '/obj/KERNEL_OBJ/usr/include/linux/': No such file or directory
cp: cannot create regular file '/obj/KERNEL_OBJ/usr/include/linux/': No such file or directory

<snip>
```

**How to reproduce**
sync your tree, source `build/envsetup.sh` and run `lunch`.

**Comment by jamuir** [comment]
if you run `lunch` a second time, then those shell commands will be executed successfully.

**Comment by jerpelea** [comment]
I tested the build on local machine and there was no error
(I will retest outside our build env)

**Comment by jamuir** [comment]
`ANDROID_PRODUCT_OUT` might have already been defined when you did your test, which would explain why you didn't see the mkdir and cp errors.

**Comment by jamuir** [comment]
@jerpelea The error is only present for people using pre-built kernels.

If you build the kernel from source, then you would have deleted the makefiles that cause the `mkdir` and `cp` errors:
```
kernel/sony/msm-4.4/common-kernel/KernelConfig.mk
kernel/sony/msm-4.9/common-kernel/KernelConfig.mk
```
That may explain why you did not see the error.

**Comment by jerpelea** [comment]
I tested on a clean repo initialized according to the build guide.
Pleade push a solution that implements the patch and works for you and I will review it

**Comment by jamuir** [comment]
sure, I can push a fix.

it would help me if you could post the output of the following commands from your clean repo:

```
$ unset ANDROID_PRODUCT_OUT
$ source build/envsetup.sh  
$ lunch aosp_h8266-eng
```

**Comment by tomgus1** [comment]
Sadly I've not been able to reproduce this error at all on my build environment. Tried on different devices and all okay.

**Comment by Paulbouchara** [comment]
Tested on a 14.04 Google cloud machine
Couldn't reproduce the issue

**Comment by alviteri** [comment]
Can't reproduce this one....

**Comment by jerpelea** [comment]
@jamuir please check your local env

**Comment by alviteri** [comment]
I ever do rm -rf out before build @jamuir

**Comment by bartcubbins** [comment]
Can't reproduce on Gentoo and Ubuntu 18.04

**Comment by alviteri** [comment]
my steps are

for clean build
rm -rf out
lunch aosp_$DEVICE-userdebug
make -jx dist or make -jx bootimage or make -jx recoveryimage

for dirty build
rm -rf out/dist
rm -rf out/target/product
lunch aosp_$DEVICE-userdebug
make -jx dist or make -jx bootimage or make -jx recoveryimage

**Comment by jerpelea** [comment]
The offending commit has been reverted since it is not needed anymore 
Thanks for reporting the issue
