### ISSUE TITLE
missing device config for H8296

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/bug_tracker#145]
**Platform:** tama
**Device:** akari
**Kernel version:** 
**Android version:** 

**Description**
in the project device-sony-akari, there is no configuration for H8296 (this is an XZ2 variant with 6GB of RAM).

**Symptoms**

**How to reproduce**
run "lunch" and notice there is no lunch configuration for h8296.

**Comment by jamuir** [comment]
@jerpelea :  there is a config file for the h8266, which I guess is the dual-sim XZ2 variant with 4GB of RAM.
  
Is it ok to build for h8266 and flash that image on the h8296?

**Comment by jamuir** [comment]
sigh... the h8266 build fails due to missing dependencies under `hardware/qcom`.

Is support for the XZ2 not yet available in open-devices?

**Comment by jerpelea** [comment]
@jamuir the support has been included and the patches are merged on the master branch
The kernel will pe pushed soon

**Comment by jerpelea** [comment]
Unfortunately the H8296 is not a Global device and, for now, you have to add the configuration in your local git

**Comment by jamuir** [comment]
mirh, jerpelea:  thanks for your replies.

@jerpelea: is it anticipated that an image built using the h8266 config should (mostly) work on the h8296?

**Comment by jerpelea** [comment]
yes it should work
