### ISSUE TITLE
Xperia XZ1 - external SDCard not visible over USB

### ISSUE THREAD

**Issue by icefalcon2225** [sonyxperiadev/bug_tracker#146]
Platform: yoshino
Device: Xperia XZ1 G8342 (poplar)
Kernel version: 4.4.139-g880676b-dirty
Android version: 8.1.0_r36 OPM2.171026.006.G1

**Description**
The external SDCard does not appear in the computer's file browser when connecting the phone to a computer with USB and the "Transfer files" options selected.  Therefore, there is not an easy way for a user to put files on the SDCard while the SDCard is in the phone.  Note that the "Internal shared storage" shows properly --- only the SDCard is missing.  This happens with both Windows 10 and Ubuntu 16.04.

The factory image works properly.  With the factory image, both the "Internal shared storage" and the "SDCard" appear in the file browser on the computer.  It is only with the AOSP build the SDCard does not appear.

**Symptions**
The external SDCard does not appear in the file browser when connecting the phone to a computer with USB and the "Transer files" options selected.

**How to reproduce**
Here are the steps to reproduce the problem:
   - Power on the device with a formatted SDCard in it
   - When the device boots, it has a notification indicating that there is an SDCard available
   - Hook the device up to a computer via USB
   - In the notification panel, select "USB charging this device", then "Tap for more options".  A "Use USB to" dialog appears.  
   - Select "Transfer files"
   - Open the device with a file browser on the computer --- it shows "Internal shared storage", but not "SDCard".  The factory image properly shows both.

**Attached files**
I've attached five files
   - *kmsg_aosp.txt* --- the kmsg from an AOSP boot, captured after I hooked the device up to a computer with USB and opened the file browser on the computer (it shows the internal storage but not the SDCard)
   - *logcat_aosp.txt* --- the logcat from an AOSP boot, captured after I hooked the device up to a computer with USB and opened the file browser on the computer (it shows the internal storage but not the SDCard)
   - *logcat_factory.txt* --- the logcat from a factory boot, captured after I hooked the device up to a computer with USB and opened the file browser on the computer (it correctly shows both the internal storage and the SDCard)
   - *screenshot_aosp.png* --- a screen shot of computer file browser when connected to the device running the AOSP image
   - *screenshot_factory.png* --- a screen shot of computer file browser when connected to the device running the factory image

[aosp_kmsg.txt](https://github.com/sonyxperiadev/bug_tracker/files/2224837/aosp_kmsg.txt)
[aosp_logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/2224838/aosp_logcat.txt)
[logcat_factory.txt](https://github.com/sonyxperiadev/bug_tracker/files/2224840/logcat_factory.txt)
![screenshot_aosp](https://user-images.githubusercontent.com/39575563/43157790-00548308-8f4c-11e8-991f-958d5428b570.png)
![screenshot_factory](https://user-images.githubusercontent.com/39575563/43157792-00646b42-8f4c-11e8-8f8f-2306601c72d1.png)

**Comment by kholk** [comment]
Cannot reproduce on SoMC Yoshino Maple
4.4.140 (25/07/18)
OPM2-171026.006.H1

**Comment by jerpelea** [comment]
I can reproduce it on SOMC Lilac

**Comment by kholk** [comment]
What's your SDCard filesystem?

**Comment by oshmoun** [comment]
can you please check what filesystem the sdcard has? if it's exfat, then can you please format to ntfs and test again?

**Comment by jerpelea** [comment]
32 Gb FAT32

**Comment by kholk** [comment]
A possible solution for the issue was found.
We are testing it to evaluate.

Thanks for reporting the bug!

**Comment by icefalcon2225** [comment]
The two SD Cards that I had originally tested with were 8Gb FAT32 and 128Gb FAT32.

**Comment by jerpelea** [comment]
please try this patch
https://review.lineageos.org/#/c/LineageOS/android_frameworks_base/+/208465/

The 128Gb SDcard is not supported without ExFAT implementation

**Comment by icefalcon2225** [comment]
I can confirm that the patch fixes the issue that I was seeing.  With the patch applied, the SD Card appears in the file browser on the computer when the phone is connected USB.  I also tested reading and writing files to the SD Card from the computer.  It all appears to be working.

Thank you for your help!

**Comment by jerpelea** [comment]
the patch has been integrated in repo_update
