### ISSUE TITLE
Xperia XA2 - Wifi sporadic reconnects

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#148]
**Platform:** nile
**Device:** pioneer (H4113)
**Kernel version:** 4.4.140-gdc5bc38
**Android version:** 8.1.0-r35
**Firmware version:** v14

**Description**
The wifi appears to lose connection and then reconnect. 

**Symptoms:**
The device loses wifi connectivity. This affects, for instance, Skype calls, as I've tried several times with an ongoing Skype call, and every once in a while the call was interrupted by the wifi losing connectivity.

**How to reproduce:**
There are no steps to reproduce the issue, apart from turning on wifi.

**Discussion:**
What I have noticed is that the issue varies from happening very rarely to happening very often, and perhaps it's dependent on the state of the device after booting up (if that makes sense at all...). When it occurred more often, I'd reboot the device and it would not happen at all after the next reboot of the device etc. 

**Logs:** logcat and dmesg included

[aosp-8.1-wifi-lost-20180726.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2234909/aosp-8.1-wifi-lost-20180726.tar.gz)

**Comment by jerpelea** [comment]
The same behavior can be observed in all SW.
