### ISSUE TITLE
[2.3.2.r1.4] Xperia XZ2 H8266 Bootloader Patch for TWRP

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#149]
**Platform:*Linux Ubuntu 18.04 x64 / Linux Mint 19 x64* 
**Device:*Xperia XZ2 / H8266* 
**Android version:*8.0.0* 

**Description**
Dear Sony developer team,

I saw on your developer site:

> 2018-08-03: Beta release for 4.9 Kernel:
> - Xperia XZ2 and Xperia XZ2 Compact (Tama)

So I compiled the Kernel for TWRP, but if a friend with the stock 51.1.A.4.265 and an unlocked bootloader tried
`fastboot boot twrp.img`
the following problem happens:

> 1. Screen turns on with Blue LED on, displaying "Your device software cant' be checked for corruption, please lock the bootloader".
> 2. After 5 seconds the screen turns off, but the blue LED is still on.
> 3. After around 20 seconds the screen turns on again with "SONY" logo, blue LED is still on.
> 4.About 5 seconds later, Blue LED turns off.
> 5.Again about 10 seconds later, screen turns off.
> 6.The red LED blinked a few times, with two times of vibration.
> 7.Screen turns on with "SONY" logo, then it's totally an ordinary boot into Android.

If he flash it via fastboot into the boot partition, the device is showing the Sony logo, but then restarts into a bootloop.

This also happens if I use the Sony aosp sources and the Sony aosp 4.9 kernel to create a Bootimage  and boot this.

**So my question is, is the kernel still not stable enough?
Or is the precompiled AOSP Sony 4.9 kernel in the bootimage (compiled with omni 8.0 and omni 8.1 sources to compile TWRP and compiled with sony aosp 8.1 sources) not compatible with the stock firmware?**

I also can only compile a bootimage with your AOSP sources.
A `make -j8` will result in a
`ninja: error: 'out/target/product/akari/obj/KERNEL_OBJ/usr', needed by 'out/target/product/akari/obj_arm/SHARED_LIBRARIES/libdrmutils_intermediates/drm_master.o', missing and no known rule to make it`

_________________________________________________________________________________
_________________________________________________________________________________
_________________________________________________________________________________

I also compiled the kernel from your developer website for the stock version 51.1.A.4.265.
But the twrp bootimage now shows a yellow triangle with a wrench before restarting.
The twrp recovery image results in a black bootloop.
Also using the precompiled stock kernel with the Sony aosp to create a Bootimage result in a not booting device.

**Would the TWRP image (compiled with Omni 8.0 or 8.1 sources) boot with the precompiled 51.1.A.4.265 kernel?
Is the precompiled stock kernel compatible with the AOSP Sony sources?**

Many thanks
Martin

**Comment by jamuir** [comment]
This is probably not the right place to ask for support porting twrp :-)

In any case, one thing you should note is that the XZ2 uses a vbmeta image to verify the integrity of boot, system, vendor and some other partitions (this is part of the enhanced android-verified-boot process).

It could be that if you update the boot image without changing the vbmeta image, the XZ2 will not boot because of the failed integrity check (this can happen even with the bootloader unlocked).

You can build a "no-op" vbmeta image using AOSP and flash it.  After that you should have better luck trying to boot an updated boot image.

**Comment by MartinX3** [comment]
But I need support booting the kernel on the XZ2 and debugging the cause of not booting, even with an aosp bootimage with soap/stock kernel :D

Thank you for this information !
I thought unlocking the bootloader would deactivate every security function :)

So I need to know how to create a book vbmeta image .
I hope it is part of the bootimage.

**Comment by jerpelea** [comment]
please wait for the next bootloader release 
XZ2 is "work in progress" supported

**Comment by jamuir** [comment]
fyi: I built and flashed an updatepackage-zip for the XZ2 earlier today (6 August) but it does not boot on my XZ2.

It just shows the sony splash screen (white text on a black background) and does not progress any further than that.  This is the behaviour even with the vbmeta integrity checks disabled.

**Comment by jerpelea** [comment]
the XZ2 is not able to boot without a bootloader update 
please wait for the official anouncemene

**Comment by MartinX3** [comment]
The bootloader update is ready? :)

**Comment by jerpelea** [comment]
Please wait for the official announcement

**Comment by MartinX3** [comment]
Do you have, after all the month waiting, an ETA for us?
So we can stop disturbing you. :)

**Comment by jerpelea** [comment]
It should be soon.
I am sorry but I can't say a precise date.

**Comment by jamuir** [comment]
It might be better to leave this issue open until the updated bootloader has been released.

**Comment by oshmoun** [comment]
can the title of this issue at least be adjusted so it isn't an eyesore when going through the list? :)

**Comment by MartinX3** [comment]
@oshmoun 
Better now? :)

**Comment by jerpelea** [comment]
I will close this bug since it is out of scope and the new bootloader will come soon

**Comment by MartinX3** [comment]
Are you sure that it will come with the September update?

**Comment by MartinX3** [comment]
Dear @jerpelea ,
is the new 51.1.A.11.51 update the one with the bootloader patch?

**Comment by MartinX3** [comment]
It updated the bootloader to v60.
AOSP is booting fine.
TWRP will come.
Thank you!
