### ISSUE TITLE
Build error with SOMC_KERNEL 4.9

### ISSUE THREAD

**Issue by russel5** [sonyxperiadev/bug_tracker#151]
**Platform:** yosino
**Device:** lilac
**Kernel version:** 4.9
**Android version:** 8.1

**Description**
As you give binaries for kernel 4.9 - youshino platforms, i'm try to build firmware with new kernel version. but this build always get errors after start.
Error log a here --> http://pasted.co/44e65b10
Am i do something wrong?
**Symptoms**
Errors when try to build with new kernel version.

**How to reproduce**
Change kernel path to msm-4.9
Change somc version to 4.9
Change build kernel to true
Try to make.

**Comment by russel5** [comment]
Yes, I'm build aosp since z3 compact and I'm known what and how

**Comment by jerpelea** [comment]
please build the kernel separate and check that your compiler works fine

**Comment by russel5** [comment]
But this error shows when I'm build only kernel - make bootimage, shows when I'm build all firmwares - make
When I'm revert back to 4.4 all works fine

**Comment by russel5** [comment]
Ok, i'm find a solution. All thing is that branch 'android_8.1_r35' don't have this commit 53634d4cd3bc3acfdca29c9e4792e3d7b0996e4c and we have this error when trying build with kernel 4.9
@jerpelea can you merge this commit to 8.1 branch. Thanks.
This bug can be closed.

**Comment by jerpelea** [comment]
please open a push request?

**Comment by russel5** [comment]
i'm not full understand how to make it, english not my home language, sorry

**Comment by MartinX3** [comment]
https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-nougat-8-1-oreo-4-4#tutorial-step-4

Did you step 4.2?
