### ISSUE TITLE
[2.3.2.r1.4] "ok google" makes device lag

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#152]
**Platform:** loire
**Device:** kugo, suzu
**Kernel version:** 4.9
**Android version:** 8.1

**Description**
If the google app has voice detection enabled, device will lag a lot while waiting on the trigger "ok google"

**Symptoms**
Device lags severely when in the app google and the app is listening through the mic.

**How to reproduce**
Install the google app, and enable voice detection, then try to scroll through the app while it's waiting on the trigger.

**Comment by tomgus1** [comment]
I can confirm this issue
