### ISSUE TITLE
Xperia AOSP Android 8.1 -> make mkdtimg build error

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#153]
Xperia AOSP
branch 8.1.0_r35
I executed
repo sync && ./repo_update.sh
and
source build/envsetup.sh && lunch
(I did choose H8266)

while executing make mkdtimg, I get this error

```bash
$ make mkdtimg
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=8.1.0
TARGET_PRODUCT=aosp_arm
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a
TARGET_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.15.0-32-generic-x86_64-with-LinuxMint-19-tara
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=OPM2.171026.006.G1
OUT_DIR=out
============================================
ninja: no work to do.
ninja: no work to do.
out/build-aosp_arm.ninja is missing, regenerating...
[675/1006] including ./system/sepolicy/Android.mk ...
./system/sepolicy/Android.mk:111: warning: BOARD_SEPOLICY_VERS not specified, assuming current platform version
[1006/1006] including ./vendor/qcom/opensource/wlan/wcnss-service/Android.mk ...
vendor/oss/cash/Android.mk: error: cashsvr (EXECUTABLES android-arm) missing libpolyreg (SHARED_LIBRARIES android-arm) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/oss/projection/ucommsvr/Android.mk: error: ucommsvr (EXECUTABLES android-arm) missing libpolyreg (SHARED_LIBRARIES android-arm) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/core/main.mk:728: error: exiting from previous errors.
23:52:54 ckati failed with: exit status 1
build/core/main.mk:21: recipe for target 'run_soong_ui' failed
make: *** [run_soong_ui] Error 1
```
I also tried the new "build-kernels.sh" with the same result multiple times.

I don't know if setting "ALLOW_MISSING_DEPENDENCIES=true" is a good thing.
Sounds more like a dirty workaround.

The missing "libpolyreg" is at device/sony/common/misc/libpolyreg

**Comment by MartinX3** [comment]
My fault.
I don't know why, but it did not set TARGET_PRODUCT to H8266
Only at the second try it set it correctly.
The make mkdtimg is working now.

I don't understand why the build-kernels.sh can't build the mkdtimg.
I shouldn't set a TARGET_PRODUCT by myself to build every kernel.
But that's fine. I made my mkdtimg.

**Comment by jerpelea** [comment]
fix 
https://github.com/sonyxperiadev/vendor-sony-kernel/commit/b5d384c773cc0ad33beb8854d0051ec4f50f0785
thanks for reporting it

**Comment by MartinX3** [comment]
Thank you!

Wouldn't ALLOW_MISSING_DEPENDENCIES=true break something, while building the kernels?
If it build mkdtimg, the variable would stay true.

**Comment by jerpelea** [comment]
it should not
