### ISSUE TITLE
[Lilac] Broken MMC on 4.9/Pie

### ISSUE THREAD

**Issue by invalidsudo** [sonyxperiadev/bug_tracker#154]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.103
**Android version:** 9.0 (built on the date of issue submission)

**Description**
External storage is not available in built-in file manager and /storage/emulated/
MMC appears to be enabled in the defconfig.
Unknown what causes this issue.

**Symptoms**
Unable to access MMC device.

**How to reproduce**
Flash system, vendor, userdata, and boot over fastboot, in addition to SW_binaries_for_Xperia_Android_8.1.6.3_r1_v15_yoshino_beta, then boot the device.

**Comment by jerpelea** [comment]
I found the missing config and it will be fixed soon 
thanks for pointing it out
