### ISSUE TITLE
[akari] build errors

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/bug_tracker#156]
**Platform:** tama
**Device:** akari
**Kernel version:** 
**Android version:** android-8.1.0_r43

**Description**
```bash
$ ./repo_update.sh
$ source build/envsetup.sh
$ lunch aosp_h8266_eng
$ make -j6

<snip>

[ 99% 1441/1446] glob vendor/qcom/opensource/interfaces/camera/device/1.0/Android.bp
[ 99% 1442/1446] glob vendor/qcom/opensource/interfaces/wifi/*/Android.bp
[ 99% 1443/1446] glob vendor/qcom/opensource/interfaces/display/config/1.1/Android.bp
[ 99% 1444/1446] glob vendor/qcom/opensource/interfaces/wifi/supplicant/1.0/Android.bp
[ 99% 1445/1446] glob vendor/qcom/opensource/interfaces/wifi/supplicant/1.1/Android.bp
ninja: error: 'kernel/sony/msm-4.9/common-kernel/kernel-dtb-akari', needed by 'out/target/product/akari/kernel', missing and no known rule to make it
14:36:25 ninja failed with: exit status 1
```

**Symptoms**
cannot build for akari.

**How to reproduce**
see above.

**Comment by MartinX3** [comment]
Aren't the Tama builds useless because of the needed bootloader update, which will come someday in the future?

**Comment by jamuir** [comment]
yes, but I anticipate that the bootloader update will be made available soon.

and the build errors still need to be fixed.

**Comment by jamuir** [comment]
I guess that the project `device-sony-common-kernel` has been dropped.

Note that the kernel-build instructions below need to be updated:

https://developer.sony.com/develop/open-devices/guides/kernel-compilation-guides/how-to-build-and-flash-a-linux-kernel-for-aosp-supported-devices#AutoLinuxKernel

After I do

```bash
$ rm -rf kernel/sony/msm-4.4/common-kernel
$ rm -rf kernel/sony/msm-4.9/common-kernel
```

I hit a new error:

```bash
[ 99% 1441/1446] glob vendor/qcom/opensource/interfaces/display/config/1.0/Android.bp
[ 99% 1442/1446] glob vendor/qcom/opensource/interfaces/display/config/1.1/Android.bp
[ 99% 1443/1446] glob vendor/qcom/opensource/interfaces/wifi/*/Android.bp
[ 99% 1444/1446] glob vendor/qcom/opensource/interfaces/wifi/supplicant/1.0/Android.bp
[ 99% 1445/1446] glob vendor/qcom/opensource/interfaces/wifi/supplicant/1.1/Android.bp
ninja: error: 'kernel/sony/msm-4.9/common-kernel/dtbo-akari.img', needed by 'out/target/product/akari/dtbo.img', missing and no known rule to make it
14:51:49 ninja failed with: exit status 1
```
This must be related to https://github.com/sonyxperiadev/device-sony-akari/commit/67cf0386540470a376e63dda2a7a427465e6d2ec

**Comment by MartinX3** [comment]
Oh, now I know, what you are mean.

Until the Tama Devices are part of the open source project, no kernels will be provided by sony.
So you need to remove the directory.
Removing the folder resolves the problem in the past.
But I did not build it now to test it.

Mentioned here
https://developer.sony.com/develop/open-devices/guides/kernel-compilation-guides/how-to-build-and-flash-a-linux-kernel-for-aosp-supported-devices#AutoLinuxKernel
Step "Prepare the repository for kernel rebuild"

**Comment by jamuir** [comment]
yeah, the kernel-build instructions on the Sony web page need to be updated.

there also seems to be a problem with https://github.com/sonyxperiadev/device-sony-akari/commit/67cf0386540470a376e63dda2a7a427465e6d2ec

**Comment by jerpelea** [comment]
please use the provided script .sh to build the kernel images

**Comment by jerpelea** [comment]
please manually build the kernel before building Android 
cd kernel/sony/msm-4.9/common-kernel
./build-kernels.sh

**Comment by jamuir** [comment]
thanks.

will someone on your side will update the kernel build instructions?

after using the "build-kernels.sh" script, I have been able to create an akari image that boots, which is encouraging.  Unfortunately, the touch screen and buttons do not work, and the image reboots a minute or so after the ui comes up.

Are these known issues?  Should I open new github issues for them?

**Comment by jerpelea** [comment]
We will upload the new kernel images after the bootloader will be released

**Comment by jamuir** [comment]
why did you delete my comment?

**Comment by jerpelea** [comment]
the new bootloader is not public and we do not advise people to start hacking around it
