### ISSUE TITLE
[All] - Android 9 - AOSP camera app is crashing

### ISSUE THREAD

**Issue by jerpelea** [sonyxperiadev/bug_tracker#158]
**Platform:*all* 
**Device:*all* 
**Kernel version:*4.9* 
**Android version:*9* 

**Description**
AOSP camera app is crashing

**Symptoms**
AOSP camera app is crashing

**How to reproduce**
start the camera app and it will crash 

NOTE:
Tested with Open Camera and camera works

**Comment by LLJY** [comment]
AOSP camera works ok on Kagura

**Comment by jerpelea** [comment]
we fixed preview and snapshotbsince the work bug was added but the video recording does not work yet
