### ISSUE TITLE
[Tone] recovery not working properly 

### ISSUE THREAD

**Issue by jerpelea** [sonyxperiadev/bug_tracker#16]
Platform: Tone
Device: Kagura, Keyaki
Kernel version: 4.4
Android version: 8.0

Description
Recovery will crash early without logs

Symptoms
There is just a reboot when an user tryes to enter recovery

How to reproduce
Flash the recovery on the boot partition and reboot. There will be multimple reboot loops

**Comment by oshmoun** [comment]
on keyaki, rebooting to recovery causes the device to get stuck in some unknown mode (neither flash mode nor fastboot mode).

**Comment by jerpelea** [comment]
recovery has been fixed and now it behaves normally 

volume down  + power = recovery from Cold boot
adb reboot recovery = recovery from Android
