### ISSUE TITLE
[Yoshino] - Android 9 - Power off reboots device

### ISSUE THREAD

**Issue by invalidsudo** [sonyxperiadev/bug_tracker#160]
**Platform:** Yoshino
**Device:** lilac
**Kernel version:** 4.9.103
**Android version:** 9

**Description**
Powering off device reboots the device instead of powering off. Boots to the white Sony screen, but not Android.

**Symptoms**
Device freezes upon booting to the white Sony screen.

**How to reproduce**
1. Power off the device through the power menu.
2. Leave the device to do its thing. Other devices may attain similar results.

**Comment by jerpelea** [comment]
the issue was caused by a crashing driver and was fixed
