### ISSUE TITLE
[Nile] - Android 9 - NO audio

### ISSUE THREAD

**Issue by jerpelea** [sonyxperiadev/bug_tracker#161]
**Platform:*nile* 
**Device:*all* 
**Kernel version:*4.9* 
**Android version:*9.0* 

**Description**
There is no audio

**Symptoms**
There is no audio

**How to reproduce**
start device and check dmesg

**Comment by kholk** [comment]
Issue solved today.

System sounds tested on SoMC Pioneer DSDS.
In-call sound to be tested.
