### ISSUE TITLE
[akari] build errors

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#166]
Platform: tama
Device: akari
Kernel version:
Android version: android-8.1.0_r46

**Description**

> build/core/base_rules.mk:390: warning: ignoring old commands for target `out/target/product/akari/vendor/etc/gps.conf'
> [ 99% 1445/1446] glob vendor/qcom/opensource/interfaces/wifi/supplicant/1.1/Android.bp
> ninja: error: 'out/target/product/akari/obj/KERNEL_OBJ/usr', needed by 'out/target/product/akari/obj/EXECUTABLES/android.hardware.light@2.0-service.sony_intermediates/service.o', missing and no known rule to make it
> 15:15:58 ninja failed with: exit status 1
> 
> #### failed to build some targets (58 seconds) ####
>

**Comment by MartinX3** [comment]
Fixed it by
1. prebuild the kernel with the script.
2. export TARGET_COMPILE_WITH_MSM_KERNEL=false

TARGET_COMPILE_WITH_MSM_KERNEL=true did not work.

**Comment by jerpelea** [comment]
kernels are added now !

**Comment by MartinX3** [comment]
@jerpelea 
Thank you very much for your hard work and the hard work of your team!

But one important question is still there.

https://github.com/sonyxperiadev/bug_tracker/issues/169#issuecomment-424278920
Got the hardware damaging bug fixed for the tama kernel code?

**Comment by jerpelea** [comment]
tama is not on the officially suported devices and will be added to the list when it will be ready. 
This is an OSS project developed in the open and hosted on github.
