### ISSUE TITLE
[Lilac] - Android 9 - Bootloop when using newest 9/14 OEM image

### ISSUE THREAD

**Issue by invalidsudo** [sonyxperiadev/bug_tracker#168]
**Platform:** yoshino
**Device:** lilac
**Kernel version:** 4.9
**Android version:** 9

**Description**
Device gets stuck on Sony white splash screen. Does not automatically reboot.

**Symptoms**
Device is unable to progress past splash screen and boot normally.

**How to reproduce**
Restore firmware to stock September update, flash AOSP 9.0.0_r6 through fastboot with OEM image and attempt to boot.

**Comment by russel5** [comment]
Yes, i can confirm that. If use old oem files k4.9 for android 8.1 phone boot up normal, but have so many bugs.

**Comment by russel5** [comment]
Any info @jerpelea ?

**Comment by jerpelea** [comment]
I can not replicate the issue and I will try on a clean build

**Comment by russel5** [comment]
One more, if turn off force encryption phone boot I see bootanimation, but it stuck on it and after 1 or 2 minute phone reboot

**Comment by jerpelea** [comment]
please run fastboot getvar all in fasboot mode

**Comment by jerpelea** [comment]
thanks
I will try the same SW

**Comment by russel5** [comment]
any info or ETA @jerpelea ?

**Comment by jamuir** [comment]
I have seen boot failures like this when keymaster does not start up.  Disabling encryption gets you a little further in the boot process (far enough to grab logs), but then it still reboots.

are you wiping the data partition after you flash?

`fastboot -w reboot` ?

**Comment by invalidsudo** [comment]
I wiped userdata after flashing everything, doesn't boot.

**Comment by alviteri** [comment]
If adb is working can you post logs and dmesg ?

**Comment by russel5** [comment]
@alviteri here you go. this is without force encryption (FE), if use FE phone won't boot and can't male logcat
http://pasted.co/d3d2a38c
ping @jerpelea

**Comment by jerpelea** [comment]
@russel5 
please flash 47.1.A.12.270 software before you flash AOSP

I tested back and forth the v1 release and there is no issue on my device

**Comment by russel5** [comment]
@jerpelea i don't understand how version of firmware change something if all oem folder with general files replaces yours oem files and using it. Do you see logcat where always crash your oem files -- /odm/bin/hw/android.hardware.gatekeeper@1.0-service-qti
Lets make clear, because downgrade firmware are long story. So you try latest build for lilac and use latest beta OEM files, yes? And with force encryption your phone XZ1 Compact boot normal and worked, yes?

**Comment by jerpelea** [comment]
@russel5 I used maple as a test device for this issue (I will retry on poplar).
The keymaster firmware may be updated during a firmware update and this is the reason I have to understand if on the old version it works fine

**Comment by russel5** [comment]
As i understand this issue was created only for lilac, no problem with another devices, as least no issues for other phones on this bug tracker
So i think this is not right try something on other device and tell that all works.
But i try your advice, flash 270 then AOSP

**Comment by jerpelea** [comment]
in the title you wrote yoshino which will signal a platform bug . Please update the title !
I will try to replicate it on lilac

**Comment by russel5** [comment]
Bro, i'm not author of this title, i'm only confirm that issue exist. And in title author wrote that issue on lilac
**Device:** lilac

**Comment by jerpelea** [comment]
the title should indiate the affected device/platform

**Comment by jerpelea** [comment]
@russel5 I think that I found and fixed the issue 
The fix will come in vendor v2

**Comment by russel5** [comment]
This is good news, thank you

**Comment by Pandomia** [comment]
@jerpelea 9.0 oem also bootloops for poplar 8341 while one user claims he got it to boot with poplar 8342(dual sim) in our forums. It's a weird issue, so I hope your fix will work for our device too.

https://forum.xda-developers.com/xperia-xz1/how-to/experiments-9-0-build-t3847813

**Comment by jerpelea** [comment]
the issue should affect both poplar and lilac

**Comment by alviteri** [comment]
Me using poplar (single sim) without problems lol

**Comment by insideTheFlux** [comment]
@jerpelea @Pandomia  I have to apologize... in my haste I overlooked 9.0 oem never working. It seems like only 4.4-8.1 and 4.9-8.1(beta) are the only functioning OEM binaries. Please excuse my stupidity. 👎

**Comment by invalidsudo** [comment]
By the way, I just tried flashing it over .270 firmware on my lilac and the issue recurred.

**Comment by russel5** [comment]
Hello @jerpelea , yesterday you commited oem v2 for android9
Right now I compiled full firmware for lilac, can you tell me when you post new oem files?

**Comment by jerpelea** [comment]
when they are ready we will post them

**Comment by russel5** [comment]
@jerpelea thanks for new oem. since now phone boot normal, but when you fix keymaster you broke bluetooth and this is very sad.

**Comment by jerpelea** [comment]
log?

**Comment by russel5** [comment]
I'm open new issue and post log
