### ISSUE TITLE
[Tone] - Android 9 - High CPU usage when wifi is turned on

### ISSUE THREAD

**Issue by LLJY** [sonyxperiadev/bug_tracker#170]
**Platform:** Tone
**Device:** Kagura
**Kernel version:** 4.9
**Android version:** 9.0

**Description:**
wp_supplicant seems to be in an infinite loop, trying to start p2p0 interface and constantly failing to do so. However, wifi remains functional.
The proposed solution seems to be appending p2p_disabled=1 to wpa_supplicant.conf, however this **DOES NOT** solve the issue as far as I have tried.

**Symptoms:**
When turning wifi on, cpu usage jumps from ~10-20% to over 60%.
adb logcat will be filled with logspam, as shown here: 
https://drive.google.com/open?id=1yba6uOv489AeGEvFut2S9WfaIYJE50pv

**How to reproduce**
Turn on wifi and view top and adb logcat output.

**Comment by LLJY** [comment]
https://github.com/CarbonBeta/android_frameworks_base/commit/a06a84edc4c59f36c2741bc8fa8caf929b00c0a1

this fixes it.

**Comment by oshmoun** [comment]
wfd has been disabled. issue can be closed
