### ISSUE TITLE
[maple] recovery-power-off causes a reboot back into recovery

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/bug_tracker#173]
**Platform:**  yoshino
**Device:** maple
**Kernel version:** 4.4
**Android version:** 8.1.0_r46

**Description**
build and flash a maple image.  Use "adb reboot recovery" to enter recovery mode.  Select "Power off" from the text menu.

If you keep the usb cable connected, then the device will power-off but then boot immediately back into recovery mode.

If you remove the usb cable before selecting "Power off", then the device will power off successfully, but when you power it on it boots back into recovery mode.

**Symptoms**
cannot power-off the device from recovery-mode.

**How to reproduce**
see above.

**Comment by jamuir** [comment]
I suspect the bootreason is somehow encoded in the sony-specific kernel args `startup` and `warmboot`.

**Comment by jerpelea** [comment]
yes and those args are patched in kernel so that they match the boot reason

**Comment by jamuir** [comment]
I do not see such a patch applied to the open devices 4.4 kernel.  There is
only a patch to set charger mode based on startup and warmboot.

**Comment by jamuir** [comment]
@jerpelea :  could you point me to the patch you mentioned?

**Comment by updateing** [comment]
> build and flash a maple image. Use "adb reboot recovery" to enter recovery mode.
It seems `adb reboot recovery` works for you, but I could not replicate that on my side. I need https://github.com/HamsterReserved/kernel/commit/bb26ae83d9aba20e63a96adbb0313b3ec6c1da52 to get reboot-recovery working. Maybe this issue could be fixed by the same commit.

**Comment by jerpelea** [comment]
please PR on both 6.4 and 2.3.2

**Comment by jamuir** [comment]
@updateing : yes, `adb reboot recovery` works fine for me on maple with android-8.1 (kernel 4.4).

The commit you point to may have the undesired effect of preventing pstore logs from being generated.

**Comment by updateing** [comment]
> preventing pstore logs from being generated

I have the same concern, but `adb reboot recovery` does fail for me - it boots right into Android system without the patch. I have not checked whether pstore is working, though.

And could you please check your bootloader version? Mine is shown below for reference:

```
(bootloader) version-baseband:1306-8501_47.1.A.16.20
(bootloader) version-bootloader:1306-5035_X_Boot_MSM8998_LA1.1_O_82
```

@jerpelea Shall we delay the PR until the correct logic is found?

**Comment by jerpelea** [comment]
pr as a reminder and we will look at it
the logic is in the tama and yoshino copylefts

**Comment by jamuir** [comment]
@updateing :  my base-band is different, but bootloader is the same as yours:

```bash
$ fastboot getvar all |& grep version
(bootloader) version-baseband:1306-8499_47.1.A.16.20
(bootloader) version-bootloader:1306-5035_X_Boot_MSM8998_LA1.1_O_82
```

**Comment by jamuir** [comment]
I think `adb reboot recovery` just does `setprop sys.powerctl reboot,recovery`.  Maybe try setting the prop manually to set if that makes a difference.

**Comment by jerpelea** [comment]
@jamuir updates?

**Comment by jamuir** [comment]
@jerpelea This is still broken.  If there is a PR I can test, then I will gladly do so.

**Comment by jerpelea** [comment]
@jamuir sorry it slipped through my list 
Did you fix it ?

**Comment by stefanhh0** [comment]
@jamuir Please test on android 10 and kernel 4.14 it is likely to be fixed with https://github.com/sonyxperiadev/kernel/pull/2311
