### ISSUE TITLE
[Poplar] Android 9.0 Sim2 non-functional

### ISSUE THREAD

**Issue by insideTheFlux** [sonyxperiadev/bug_tracker#174]
**Platform:** Yoshino
**Device:** Xperia XZ1 G8342 (poplar)
**Kernel version:** 4.9.103-ge069000-dirty
**Android version:** 9.0 -- android-9.0.0_r6

**Description**
Sim 2 is nonfunctional

**Symptoms**
I have two sim cards installed but only sim1 is visible, sim2 is grayed out. 
Works fine on my regular US firmware Oreo/September 2018 release. 

**How to reproduce**
Build AOSP(android-9.0.0_r6), try running two sim cards. Tried 8.1(kern 4.4), beta 8.1(4.9), and beta 9.0(4.9)

**Comment by insideTheFlux** [comment]
Confirm for me if this is the fix? 8 days ago.

https://github.com/sonyxperiadev/device-sony-poplar/pull/29/commits/8e672f49f63f01256fda878ceee67ad859ff4d7b

**Comment by jerpelea** [comment]
no

**Comment by insideTheFlux** [comment]
@jerpelea Ok. How do I then address this issue?

**Comment by insideTheFlux** [comment]
@jerpelea Shouldn't sim2 be working? I'm I doing something wrong?

**Comment by jerpelea** [comment]
It looks like poplar is affected by another bug and for now it does not detect the second sim while all other devices are working fine

**Comment by updateing** [comment]
Also happens on maple with kernel 4.4, Android 8.1 and vendor r15. I'm able to fix this by resetting kernel to https://github.com/sonyxperiadev/kernel/commit/fab496c948b531fa117849c7ea40adda932d0912 - this is a known working revision, but I have not figured out the exact failing commit.

**Comment by updateing** [comment]
Found the failing commit: https://github.com/sonyxperiadev/kernel/commit/d190754e5f41. But it seems like something is going wrong elsewhere?

**Comment by insideTheFlux** [comment]
@jerpelea what do you think of the above from @updateing?

**Comment by jerpelea** [comment]
the revert will fix the second sim on tone

**Comment by jerpelea** [comment]
fix 
https://github.com/sonyxperiadev/kernel/commit/d67917ead21cf9f484b5a30587b5fd81d00c861b

**Comment by jerpelea** [comment]
thanks @updateing for pointing out the revert.

**Comment by insideTheFlux** [comment]
@jerpelea I'm still getting no response from both SIMs now.
[https://imgur.com/a/DvGgbQm](url)

**Comment by jerpelea** [comment]
Android 9 is beta 2 if you updated your binaries with today's release
I will check the DS functionality ASAP

**Comment by insideTheFlux** [comment]
I'll try that later @jerpelea and I'm getting an on boot error(dialog popup) about device manufacturer too.
