### ISSUE TITLE
[Tama] - Android 8.1r46 - Possible Display Damage

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#179]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 8.1r46

**Description**
According to @kholk 
Possible Displaydamage.

**Symptoms**
Display is unable to resume from sleep or sometimes unable to even boot (glitches and reboot).
Display get damaged.

**How to reproduce**
Runnin the AOSP-Build

**Comment by jerpelea** [comment]
this early bug should be gone
