### ISSUE TITLE
[MAPLE] Sony Xperia XZ Premium (G8141 with single SIM) failed to boot

### ISSUE THREAD

**Issue by AnnaFangGraphite** [sonyxperiadev/bug_tracker#18]
**Device:** 
Sony Xperia XZ Premium (G8141) with single SIM card.

**Kernel version:** 
4.4 (from branch n-mr1_4.4)

**Android version:** 
android-7.1.1_r55

**Description**
The image built from the aosp tree (by following instructions on https://developer.sonymobile.com/open-devices/aosp-build-instructions/how-to-build-aosp-nougat-for-unlocked-xperia-devices/) failed to boot. The phone is stuck in the screen that shows SONY on a black background. 

**How to reproduce**
1. Follow the instructions on how to create nougat 7.1 aosp tree from this link, https://developer.sonymobile.com/open-devices/aosp-build-instructions/how-to-build-aosp-nougat-for-unlocked-xperia-devices/
2. Choose aosp_g8141 as the build target.
3. Build the aosp project.
4. Flash the XZ premium phone with SW_binaries_for_Xperia_AOSP_N_MR1_4.4_v04_yoshino.zip at bootloader with command "fastboot flash oem SW_binaries_for_Xperia_AOSP_N_MR1_4.4_v04_yoshino.zip". 
5. Flash the system.img, boot.img and userdata.img as instructed. 
6. The phone failed to boot to the end. The bootlog will be attached in this ticket.

**Comment by AnnaFangGraphite** [comment]
[log_boot.log](https://github.com/sonyxperiadev/bug_tracker/files/1435193/log_boot.log)

**Comment by jerpelea** [comment]
the zip has to be unpacked before flash

fastboot flash oem SW_binaries_for_Xperia_AOSP_N_MR1_4.4_v04_yoshino.img

version 5 will be release tomorrow

**Comment by AnnaFangGraphite** [comment]
Thanks very much for the tip. Yup, the unzipped oem image (version 4.4) works.
