### ISSUE TITLE
[Tama] - Android 8.1r46 - Graphics acceleration is not working (gralloc?)

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#181]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 8.1r46

**Description**
Graphics acceleration is not working (gralloc?)

**Symptoms**
Hot device.
Slow device.
Battery draining.

The display can appear to be "slow" (stuttering, low fps anyway) because of a bug with the userspace libraries on the clock calculation code. The same bug may prevent (does prevent, on SoMC Apollo DSDS) the display to resume from sleep with DSI UNDERFLOW errors. The solution to this resides in the userspace libsdedrm/libdisplayqos and HAL (has to forcefully match with blobs);

**How to reproduce**
Using the phone.

**Comment by jerpelea** [comment]
tested Antutu and 3dMark
Both are OK !
