### ISSUE TITLE
[Tama] - Android 8.1r46 - Brightness is not adjustable

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#182]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 8.1r46

**Description**
Brightness is not adjustable.
Brightness controls are fixed after @kholk  PR on the Lights HAL and tama-common on Android. @alviteri extended the solution to healthd for other purposes.

**Symptoms**
See description.

**How to reproduce**
Try to adjust the brightness.

**Comment by alviteri** [comment]
https://github.com/sonyxperiadev/device-sony-tama/commit/326867b8f5bdcdb5bee76b85a3d506597b703b98 do you have this merged locally ?

**Comment by MartinX3** [comment]
Oh, I didn't test the new fixes.
@jerpelea told me to seperate every entry of this
https://github.com/sonyxperiadev/bug_tracker/issues/169
into its own issue ticket.

We normal people shouldn't test it because of the appeared display hardware damage @kholk  reported.

**Comment by alviteri** [comment]
You can edit ueventd.rc via adb without build the whole rom and see if bug is gone .... Cheers

**Comment by MartinX3** [comment]
Thank you, but I am scared to continue running the AOSP rom until the hardware damaging bug got fixed.
So I am using the stock firmware. :)

**Comment by kholk** [comment]
This bug can be closed, since it's solved.

**Comment by MartinX3** [comment]
Should I close it or should I wait for @jerpelea ?
