### ISSUE TITLE
[Tama] - Android 8.1r46 - Test calls - Robotic sounds because of microphone?

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#184]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 8.1r46

**Description**
Test calls - Robotic sounds because of microphone?

**Symptoms**
Test calls - Robotic sounds because of microphone?

**How to reproduce**
Test calls - Robotic sounds because of microphone?

**Comment by jerpelea** [comment]
fixed
