### ISSUE TITLE
[Tama] - Android 8.1r46 - Sleep not working

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#186]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 8.1r46

**Description**
The device sleep issues are due to general misconfiguration, we had this back in the day on Loire, Tone, Nile and Yoshino. It's due to the fact that we are integrating not yet supported things in userspace (like camera, mainly) that will keep getting killed and restarting, preventing deep sleep (or any kind of sleep);

**Symptoms**
Sleep not working.

**How to reproduce**
Sleep not working.

**Comment by jerpelea** [comment]
the bug is fixed and the fix will be provided in blobs v3

**Comment by abioteau** [comment]
@jerpelea Do you means only blobs 9.0 v3 or also 8.1 v17

**Comment by jerpelea** [comment]
both will come soon

**Comment by jerpelea** [comment]
the oss code is already pushed
