### ISSUE TITLE
[Tama] - Android 8.1r46 - Device gets hot over time.

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#187]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 8.1r46

**Description**
Device gets hot over time.

**Symptoms**
Device gets hot over time.

**How to reproduce**
Device gets hot over time.

**Comment by jerpelea** [comment]
I have the device running for several days and I can not see any issue
The device will become warm when 3d mark runs
