### ISSUE TITLE
[Tama] - Android 8.1r46 - The SDCard is not mounted

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#189]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 8.1r46

**Description**
The SDCard is not mounted.
Maybe it was too big?
32GB, 64GB, 128GB, 256GB
Ext4, NTFS, FAT32, exFAT.

**Symptoms**
The SDCard is not mounted.

**How to reproduce**
The SDCard is not mounted.

**Comment by jerpelea** [comment]
fixed
https://github.com/sonyxperiadev/device-sony-tama/commit/87bc1adacdb2de723349f9746e45a741b6d89175
