### ISSUE TITLE
[ALL] sepolicy has unrecognized character as of recent commit

### ISSUE THREAD

**Issue by bobobo1618** [sonyxperiadev/bug_tracker#19]
```
device/sony/sepolicy/rdclean.te:3:WARNING 'unrecognized character' at token ''' on line 23385:
'
#line 3
```

Since this was a recent commit I thought it worth reporting in case it was unnoticed.

**Comment by oshmoun** [comment]
According to the message, this is a warning. Does the build still succeed even though this message appears?

**Comment by alviteri** [comment]
this is not a BUG

**Comment by bartcubbins** [comment]
@bobobo1618 can be closed.
https://github.com/sonyxperiadev/device-sony-sepolicy/pull/277

**Comment by alviteri** [comment]
https://android.googlesource.com/platform/system/sepolicy/+/android-8.0.0_r15/private/shell.te#13

**Comment by bartcubbins** [comment]
oops:)

**Comment by bobobo1618** [comment]
Yes, the build still completes, I just wanted to make sure someone was aware.
