### ISSUE TITLE
[Tama] - Android 8.1r46 - Bluetooth not working

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#191]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 8.1r46

**Description**
Bluetooth not working

**Symptoms**
Bluetooth not working

**How to reproduce**
Bluetooth not working

**Comment by jamuir** [comment]
We tested a GSI on the XZ2 and got bluetooth working after reverting the following commit:

https://android.googlesource.com/platform/build/+/292b8433c

Credit goes to phhusson for that fix:

https://github.com/phhusson/platform_build/commit/2949435c

Maybe the root folder `bt_firmware` is needed in a device specific build as well.

**Comment by oshmoun** [comment]
if it's just about the firmware folder then just add bt_firmware to  BOARD_ROOT_EXTRA_FOLDERS in platform repository

**Comment by jerpelea** [comment]
BT works fine
