### ISSUE TITLE
[Tama] - Android 8.1r46 - Test cellular data (2G, 3G, LTE) AND wifi (2.4GHz, 5GHz)

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#192]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 8.1r46

**Description**
Test cellular data (2G, 3G, LTE) AND wifi (2.4GHz, 5GHz)

**Symptoms**
Test cellular data (2G, 3G, LTE) AND wifi (2.4GHz, 5GHz)

**How to reproduce**
Test cellular data (2G, 3G, LTE) AND wifi (2.4GHz, 5GHz)

**Comment by kholk** [comment]
Can confirm WiFi working perfectly, but that was tested on Android 9

**Comment by jerpelea** [comment]
GSM working fine

**Comment by kholk** [comment]
Can we close this issue, since both wifi and GSM were tested working?
