### ISSUE TITLE
[Tama] - Android 8.1r46 - Test Media storage USB mode

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#193]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 8.1r46

**Description**
Test Media storage USB mode

**Symptoms**
Test Media storage USB mode

**How to reproduce**
Test Media storage USB mode

**Comment by jerpelea** [comment]
Both MTP and PTP work ok
