### ISSUE TITLE
[Tama] - Android 8.1r46 - Test sound/audio

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#194]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 8.1r46

**Description**
Test sound/audio

**Symptoms**
Test sound/audio

**How to reproduce**
Test sound/audio

**Comment by richardtullberg** [comment]
I'm guessing that all audio is now broken on tama akari?

**Comment by MartinX3** [comment]
It may be fixed, but need to be tested. :)

**Comment by jerpelea** [comment]
fixed
