### ISSUE TITLE
XZ2 Premium (Aurora) missing.

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#197]
Will it be ever added?
Are there any plans?
Because I see the XZ2, XZ2c and the XZ3.

Has it a locked bootloader?
Because

First a friend flashed fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
Then he flashed twrp.
Then the stock kernel in twrp.
It bootloops.
Then he flashed the stock kernel via fastboot.
It still bootloops.
Then he flashed  via Fastboot the vbmeta again and now it booted into the system again.

But if he modify the system in twrp and then flashes the vbmeta again to enable verified boot, the device boots with the changes.
It is weird.

**Comment by jerpelea** [comment]
This device will not be added to the Open devices

**Comment by jerpelea** [comment]
This device will not be added to the Open devices

**Comment by MartinX3** [comment]
Could you explain me what is different in the XZ2P? :)

**Comment by jamuir** [comment]
@MartinX3 : re flashing vbmeta.  The flag `--disable-verification` can cause a boot failure on some devices; try dropping it:

`fastboot --disable-verity flash vbmeta vbmeta.img`

**Comment by the-brad** [comment]
@jerpelea And what about pie? Any chance, you could make the dual cam compatible to androids dual cam api/driver? I read, it supports dual cam setups natively, now.

**Comment by jerpelea** [comment]
XZ2 Premium is not supported by the Open Devices
