### ISSUE TITLE
[Loire] TransPower non-functional on Android P

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#199]
**Platform:** loire
**Device:** kugo
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
transpower does not start automatically when booting up the device

**Symptoms**
the app isn't running in the background
`dumpsys sensorservice` Shows that the app isn't utilizing sensors (no open connections for the app)

**Comment by jerpelea** [comment]
the issue was caused by non working sensor service and should be fixed now

**Comment by oshmoun** [comment]
yup working now
`dumpsys sensorservice` is reporting that transpower is accessing sensors:
00:42:15 + 0x00000035 pid= 2521 uid= 1001 package=com.sony.transmitpower.sensor.Proximity samplingPeriod=66667us batchingPeriod=0us
