### ISSUE TITLE
CPU4 Error on X devices: Failed to read cpu-freq

### ISSUE THREAD

**Issue by xperiadev** [sonyxperiadev/bug_tracker#20]
**Platform:** 
**Device:** Xperia X
**Kernel version:** LA.BR.1.3.3_rb2.14
**Android version:** Android 6.0.1 R80

**Description**
X devices after suspend the following log message:

E KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu4/cpufreq/stats/time_in_state: open failed:
ENOENT (No such file or directory)

Logcat is filled with this message and this is just for cpu4 and not any other cpus. In the following you see snapshot of kmsg regarding CPU logs. Have you any idea about this?

cat /dev/kmsg | grep cpu 6,0,0,-;Initializing cgroup subsys cpuset 6,1,0,-;Initializing cgroup subsys cpu 6,2,0,-;Initializing cgroup subsys cpuacct
6,40,0,-;psci: Initializing psco_cpu_init
6,41,0,-;psci: Initializing psco_cpu_init
6,42,0,-;psci: Initializing psco_cpu_init
6,43,0,-;psci: Initializing psco_cpu_init
6,44,0,-;psci: Initializing psco_cpu_init
6,45,0,-;PERCPU: Embedded 14 pages/cpu @ffffffc0b3e58000 s33856 r0 d23488 u57344
7,46,0,-;pcpu-alloc: s33856 r0 d23488 u57344 alloc=14*4096
7,47,0,-;pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 [0] 4 [0] 5 2,70,2379,-;Unable to find CPU node for /cpus/cpu@101
3,71,2387,-;/cpus/cpu-map/cluster1/core1: Can't get CPU for leaf core
3,72,2401,-;/cpus/cpu@0: Missing clock-frequency property
3,73,2411,-;/cpus/cpu@1: Missing clock-frequency property
3,74,2420,-;/cpus/cpu@2: Missing clock-frequency property
3,75,2430,-;/cpus/cpu@3: Missing clock-frequency property
3,76,2441,-;/cpus/cpu@100: Missing clock-frequency property
3,77,2454,-;/cpus/cpu@103: Missing clock-frequency property
6,80,12435,-;cpu_clock_a72_init: A72 Power clocks configured 3,89,95596,-;cpu 0 reg dump setup failed 3,90,95604,-;cpu 1 reg dump setup failed 3,91,95610,-;cpu 2 reg dump setup failed 3,92,95615,-;cpu 3 reg dump setup failed 3,93,95621,-;cpu 4 reg dump setup failed 3,94,95626,-;cpu 5 reg dump setup failed
6,156,150225,-;cpu-clock-8976 b114000.qcom,cpu-clock-8976: Speed bin: 0 PVS Version: 0
 DEVICE=+platform:b114000.qcom,cpu-clock-8976
6,157,150381,-;platform b114000.qcom,cpu-clock-8976: Driver cpu-clock-8976 requests probe deferral
 DEVICE=+platform:b114000.qcom,cpu-clock-8976
6,268,187787,-;cpu-clock-8976 b114000.qcom,cpu-clock-8976: Speed bin: 0 PVS Version: 0
 DEVICE=+platform:b114000.qcom,cpu-clock-8976
6,270,191572,-;populate_opp_table: clock-cpu-8976: OPP tables populated (cpu 3 and 5)
6,271,191585,-;print_opp_table: clock_cpu: a53: OPP voltage for 400000000: 820000
6,272,191594,-;print_opp_table: clock_cpu: a53: OPP voltage for 1401600000: 1105000
6,273,191604,-;print_opp_table: clock_cpu: a72: OPP voltage for 400000000: 850000
6,274,191613,-;print_opp_table: clock_cpu: a72: OPP voltage for 1804800000: 1065000
6,275,191932,-;qcom,cpu-spm-8976 b111200.qcom,spm: Registered CPU SPM clocks
6,339,232377,-;cpufreq: driver msm up and running 4,471,316123,-;error setting kswapd cpu affinity mask
6,818,5126936,-;cpuidle: using governor null 6,897,6342663,-;bimc-bwmon 408000.qcom,cpu-bwmon: BW HWmon governor registered.
 DEVICE=+platform:408000.qcom,cpu-bwmon
3,898,6344968,-;devfreq qcom,cpubw.49: Couldn't update frequency transition information.
 DEVICE=+devfreq:qcom,cpubw.49
3,899,6345063,-;devfreq qcom,mincpubw.50: Couldn't update frequency transition information.
 DEVICE=+devfreq:qcom,mincpubw.50
6,1080,7693301,-;cpu cpu0: cpuquiet_add_dev
 SUBSYSTEM=cpu
 DEVICE=+cpu:cpu0
6,1081,7693311,-;cpu cpu1: cpuquiet_add_dev
 SUBSYSTEM=cpu
 DEVICE=+cpu:cpu1
6,1082,7693318,-;cpu cpu2: cpuquiet_add_dev
 SUBSYSTEM=cpu
 DEVICE=+cpu:cpu2
6,1083,7693325,-;cpu cpu3: cpuquiet_add_dev
 SUBSYSTEM=cpu
 DEVICE=+cpu:cpu3
6,1084,7693333,-;cpu cpu4: cpuquiet_add_dev
 SUBSYSTEM=cpu
 DEVICE=+cpu:cpu4
6,1085,7693341,-;cpu cpu5: cpuquiet_add_dev
 SUBSYSTEM=cpu
 DEVICE=+cpu:cpu5
13,1202,11363429,-;init: write_file: Unable to open '/proc/cpu/alignment': No such file or directory
13,1205,11382307,-;init: write_file: Unable to write to '/dev/cpuctl/cpu.shares': Invalid argument
13,1325,12513093,-;init: write_file: Unable to write to '/sys/class/devfreq/qcom,mincpubw.50/governor': No such device
13,1332,12514576,-;init: write_file: Unable to write to '/sys/devices/system/cpu/cpu0/online': Invalid argument
13,1333,12516643,-;init: write_file: Unable to open
'/sys/devices/system/cpu/cpu4/cpufreq/interactive/sampling_down_factor': No such file or directory
13,1334,12516951,-;init: write_file: Unable to write to '/sys/devices/system/cpu/cpu0/cpufreq/interactive/target_loads':
Invalid argument
13,1336,12517495,-;init: write_file: Unable to write to '/sys/devices/system/cpu/cpu1/online': Invalid argument
13,1337,12517536,-;init: write_file: Unable to write to '/sys/devices/system/cpu/cpu2/online': Invalid argument
13,1338,12518892,-;init: write_file: Unable to write to '/sys/devices/system/cpu/cpu4/online': Invalid argument
13,1339,12518943,-;init: write_file: Unable to write to '/sys/devices/system/cpu/cpu5/online': Invalid argument

**Symptoms**
Log file is filled with cpu errors. 

**How to reproduce**
Build Image for Xperia X after sony installation guide for Marshmallow...

**Comment by jerpelea** [comment]
@kholk please test

**Comment by kholk** [comment]
This partially cannot be solved. 
On kernel 3.10, when you hotplug out a cpu its corresponding cpufreq node will get removed, hence you will be unable to read the cluster 1 cpu stats.
It may be possible to solve the other errors.

**Comment by jerpelea** [comment]
please fix the other errors

**Comment by jerpelea** [comment]
The bug can not be reproduced on the current kernel branch aosp/LA.UM.5.7.r1.
please backport the patches to the legacy branch

**Comment by jerpelea** [comment]
the legacy branch should not be used since all the active devices have been migrated to the new active kernel
