### ISSUE TITLE
[All] Video recording crashes camera app on Android P

### ISSUE THREAD

**Issue by harryharryharry** [sonyxperiadev/bug_tracker#200]
**Platform:** Loire
**Device:** Kugo
**Kernel version:** 4.9.103-ge30d2727afeb
**Android version:** 9.0

**Description**
Upon starting a video recording the camera app instantly crashes with error message: 
"Can’t Connect to Camera". 
Logcat: http://ix.io/1oO5

**Symptoms**
Camera app crashes, no video recording possible.

**How to reproduce**
Open camera app, switch to video, press record.

**Comment by oshmoun** [comment]
a temp workaround would be to use opencamera or some other 3rd party camera app instead of the system's

**Comment by jerpelea** [comment]
11-06 13:33:55.646   737   804 E linker  : library "/system/lib64/extractors/.." ("/system/lib64") needed or dlopened by "/system/lib64/libstagefright.so" is not accessible for the namespace: [name="(default)", ld_library_paths="", default_library_paths="/system/lib64", permitted_paths="/system/lib64/drm:/system/lib64/extractors:/system/lib64/hw:/system/product/lib64:/system/framework:/system/app:/system/priv-app:/vendor/framework:/vendor/app:/vendor/priv-app:/odm/framework:/odm/app:/odm/priv-app:/oem/app:/system/product/framework:/system/product/app:/system/product/priv-app:/data:/mnt/expand"]
11-06 13:33:55.723   740   810 D StagefrightPluginLoader: Failed to load library: libstagefright_ccodec.so (dlopen failed: library "libstagefright_ccodec.so" not found)

**Comment by jerpelea** [comment]
tama fix 
https://github.com/sonyxperiadev/device-sony-tama/commit/de91b98b1baa73fbe268aa83e1d800027829ca90#diff-03543afaa3229edc0ad860f710edeb44L86

**Comment by jerpelea** [comment]
all others 
https://github.com/sonyxperiadev/camera/commit/60526337434ee091e80707c6484709b589d81584

**Comment by bartcubbins** [comment]
Video recording is fine on my suzu

**Comment by ix5** [comment]
On tone https://github.com/sonyxperiadev/device-sony-tone/commit/a8cf2908fa80def497f9f312edd86402954627b8 needs to be reverted until there is proper HFR support in v4 blobs.
Issue can be closed.
