### ISSUE TITLE
Error building AOSP

### ISSUE THREAD

**Issue by insideTheFlux** [sonyxperiadev/bug_tracker#201]
**Platform:** *Yoshino* 
**Device:** *Poplar* 
**Kernel version:** *4.9-* 
**Android version:** *Android 9* 

**Description**
```
[  8% 8750/105019] Check module type: out/target/product/poplar/obj_arm/SHARED_LIBRARIES/libOmxVenc_intermediates/link_type
FAILED: out/target/product/poplar/obj_arm/SHARED_LIBRARIES/libOmxVenc_intermediates/link_type 
/bin/bash -c "(mkdir -p out/target/product/poplar/obj_arm/SHARED_LIBRARIES/libOmxVenc_intermediates/ && rm -f out/target/product/poplar/obj_arm/SHARED_LIBRARIES/libOmxVenc_intermediates/link_type ) && (build/make/tools/check_link_type.py --makefile hardware/qcom/media/sdm845/mm-video-v4l2/vidc/venc/Android.mk --module libOmxVenc --type \"native:vendor\" --allowed native:vendor --allowed native:vndk  out/target/product/poplar/obj_arm/STATIC_LIBRARIES/libOmxVidcCommon_intermediates/link_type     out/target/product/poplar/obj_arm/STATIC_LIBRARIES/libunwind_llvm.vendor_intermediates/link_type     out/target/product/poplar/obj_arm/STATIC_LIBRARIES/libclang_rt.ubsan_minimal-arm-android.vendor_intermediates/link_type     out/target/product/poplar/obj_arm/STATIC_LIBRARIES/libcompiler_rt-extras.vendor_intermediates/link_type     out/target/product/poplar/obj_arm/SHARED_LIBRARIES/liblog.vendor_intermediates/link_type     out/target/product/poplar/obj_arm/SHARED_LIBRARIES/libcutils.vendor_intermediates/link_type     out/target/product/poplar/obj_arm/SHARED_LIBRARIES/libc2dcolorconvert_intermediates/link_type     out/target/product/poplar/obj_arm/SHARED_LIBRARIES/libqdMetaData_intermediates/link_type     out/target/product/poplar/obj_arm/SHARED_LIBRARIES/libc++.vendor_intermediates/link_type ) && (echo \"native:vendor\" >out/target/product/poplar/obj_arm/SHARED_LIBRARIES/libOmxVenc_intermediates/link_type )"
hardware/qcom/media/sdm845/mm-video-v4l2/vidc/venc/Android.mk: error: libOmxVenc (native:vendor) should not link to libOmxVidcCommon (native:platform)
[  8% 8754/105019] Build hyb out/target/product/poplar/obj/ETC/hyph-hu_intermediates/hyph-hu.hyb <- external/hyphenation-patterns/hu//hyph-hu.pat.txt
21515 unique nodes, 102669 total
ninja: build stopped: subcommand failed.
20:37:26 ninja failed with: exit status 1

#### failed to build some targets (26:16 (mm:ss)) ####

```

**Symptoms**
While building AOSP I get this error now.
security revision: Oct 2018
build: PPR2.181005.003
branch: android-9.0.0_r10

**How to reproduce**
Try to build latest Oct 2018 AOSP for Poplar.

**Comment by invalidsudo** [comment]
Why did you close this issue? I'm having the same problem.

**Comment by insideTheFlux** [comment]
I was thinking that a build error was not going to be considered a bug.

**Comment by MartinX3** [comment]
Of course it is a bug. :)

**Comment by insideTheFlux** [comment]
Any of you have latest AOSP 9.0 _r10 building successful? @jerpelea @kholk

**Comment by jerpelea** [comment]
yes but you have to fix gps and media locally until we get the new gits from pixel 3

I am avoiding to fork those gits to push the simple fixes!

**Comment by insideTheFlux** [comment]
@jerpelea I'm not even sure how to fix gps/media. I'll wait it out. Approximately how long do you think it will take to get from pixel 3?

**Comment by kholk** [comment]
Noone knows that, bar Google.

Shouldn't take long tho.....

**Comment by insideTheFlux** [comment]
@jerpelea @kholk When this happens then what do we need to do to be up to date? Re-run repo sync or just remove the workspace and start a new one?

**Comment by kholk** [comment]
The build guide on the Sony website will be updated and you'll have to follow that, as always.

**Comment by mehakimz** [comment]
Is that ok to copy the hardware/qcom/gps/sdm845 from android-8.1.0_r48 branch?

**Comment by MartinX3** [comment]
> Is that ok to copy the hardware/qcom/gps/sdm845 from android-8.1.0_r48 branch?

https://github.com/sonyxperiadev/bug_tracker/issues/203
Sounds like my bug?

**Comment by insideTheFlux** [comment]
@jerpelea @kholk 
Where is this coming from again? The compile went further but this is the new error.
======================================================

`
1 error generated.
[  0% 7/29679] target thumb C++: camera.msm8998_32 <= vendor/qcom/opensource/camera/QCamera2/HAL/QCamera2HWI.cpp
FAILED: out/target/product/poplar/obj_arm/SHARED_LIBRARIES/camera.msm8998_intermediates/HAL/QCamera2HWI.o 
/bin/bash -c "PWD=/proc/self/cwd  prebuilts/clang/host/linux-x86/clang-4691093/bin/clang++ 	-I vendor/qcom/opensource/camera/QCamera2/../mm-image-codec/qexif -I vendor/qcom/opensource/camera/QCamera2/../mm-image-codec/qomx_core -I vendor/qcom/opensource/camera/QCamera2/include -I vendor/qcom/opensource/camera/QCamera2/stack/common -I vendor/qcom/opensource/camera/QCamera2/stack/common/leak -I vendor/qcom/opensource/camera/QCamera2/stack/mm-camera-interface/inc -I vendor/qcom/opensource/camera/QCamera2/util -I vendor/qcom/opensource/camera/QCamera2/HAL3 -I hardware/libhardware/include/hardware -I hardware/qcom/media/sdm845/libstagefrighthw -I hardware/qcom/media/sdm845/mm-core/inc -I system/core/include/cutils -I system/core/include/system -I system/media/camera/include/system -I vendor/qcom/opensource/camera/QCamera2/HAL -I out/target/product/poplar/obj/include/qcom/display -I hardware/qcom/display/sde/libqservice -I vendor/qcom/opensource/camera/QCamera2 -I out/target/product/poplar/obj_arm/SHARED_LIBRARIES/camera.msm8998_intermediates -I out/target/product/poplar/gen/SHARED_LIBRARIES/camera.msm8998_intermediates \$(cat out/target/product/poplar/obj_arm/SHARED_LIBRARIES/camera.msm8998_intermediates/import_includes)   -isystem out/target/product/poplar/obj/include -isystem kernel/sony/msm-4.9/common-headers/kernel-headers -c  -fomit-frame-pointer -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-expansion-to-defined -Wno-zero-as-null-pointer-constant -fdebug-prefix-map=\$PWD/= -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -nostdlibinc -msoft-float -march=armv8-a -mfloat-abi=softfp -mfpu=neon-fp-armv8 -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -D__ARM_FEATURE_LPAE=1 -target arm-linux-androideabi -Bprebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin  -Wsign-promo -Wno-inconsistent-missing-override -Wno-null-dereference -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -Wno-gnu-include-next -fvisibility-inlines-hidden  -std=gnu++14 -mthumb -Os  -fno-rtti -Wall -Wextra -Werror -DFDLEAK_FLAG -DMEMLEAK_FLAG -DQCAMERA_HAL1_SUPPORT -DSYSTEM_HEADER_PREFIX=sys -DHAS_MULTIMEDIA_HINTS -D_ANDROID -DVANILLA_HAL -std=c++11 -std=gnu++0x -DDEFAULT_DENOISE_MODE_ON -DHAL3 -DQCAMERA_REDEFINE_LOG -DVENUS_PRESENT -DUBWC_PRESENT -DTARGET_MSM8996 -DUSE_CAMERA_METABUFFER_UTILS -DTARGET_HAS_CASH -D__ANDROID_API__=28 -D__ANDROID_VNDK__ -fPIC -D_USING_LIBCXX -DANDROID_STRICT   -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-null-pointer-arithmetic -Wno-enum-compare -Wno-enum-compare-switch   -MD -MF out/target/product/poplar/obj_arm/SHARED_LIBRARIES/camera.msm8998_intermediates/HAL/QCamera2HWI.d -o out/target/product/poplar/obj_arm/SHARED_LIBRARIES/camera.msm8998_intermediates/HAL/QCamera2HWI.o vendor/qcom/opensource/camera/QCamera2/HAL/QCamera2HWI.cpp"
In file included from vendor/qcom/opensource/camera/QCamera2/HAL/QCamera2HWI.cpp:46:
In file included from vendor/qcom/opensource/camera/QCamera2/HAL/QCamera2HWI.h:40:
In file included from vendor/qcom/opensource/camera/QCamera2/HAL/QCameraChannel.h:34:
vendor/qcom/opensource/camera/QCamera2/HAL/QCameraMem.h:39:10: fatal error: 'OMX_QCOMExtns.h' file not found
#include "OMX_QCOMExtns.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
[  0% 8/29679] target thumb C++: camera.msm8998_32 <= vendor/qcom/opensource/camera/QCamera2/HAL3/QCamera3PostProc.cpp
ninja: build stopped: subcommand failed.
21:24:22 ninja failed with: exit status 1

#### failed to build some targets (47 seconds) ####

`

**Comment by jerpelea** [comment]
please wait until we get the updated media and GPS gits or fix them locally

**Comment by jerpelea** [comment]
I pushed today gps and media repos 
now the build is fixed
