### ISSUE TITLE
OTA on XA2

### ISSUE THREAD

**Issue by AlexandreStumpf** [sonyxperiadev/bug_tracker#205]
**Platform:** 
**Device:** 
XA2
**Kernel version:** 
4.4
**Android version:** 
8.1

**Description**
We have OTA working fine on XZ1 but it is not working on XA2, that uses A/B. We need instructions and tips on how to make it works. What happens is that when we apply the OTA, the phone enters in a reboot loop and does not work anymore.

**Symptoms**
Phone reboots for several times and display a message showing that it is corrupted.

**How to reproduce**
Apply the OTA

**Comment by AlexandreStumpf** [comment]
A update on this issue:

We are using RecoverySystem.installPackage to apply the OTA to XZ1.

Can we use the same approach for XA2 (A/B)?

Thanks

**Comment by AlexandreStumpf** [comment]
Hello,

Do we must have to use update_engine to apply an OTA to a XA2 (A/B)? Or is there any other way to do it?

Thanks,

**Comment by jerpelea** [comment]
if there is no successful boot or 7 times the device will display the device is corrupted message

**Comment by AlexandreStumpf** [comment]
By the update code you mean update_engine?

**Comment by jerpelea** [comment]
update code means the update framework which includes different ways to handle different devices

**Comment by AlexandreStumpf** [comment]
I am sorry but I am not aware about the Update framework. We have our own OTA software that is working fine on xz1 but not on xa2.

Is there a repository for the update framework?

**Comment by jerpelea** [comment]
this means the whole code that takes care of updating a device

**Comment by AlexandreStumpf** [comment]
Ok, specific for xa2, should we use the update_engine software to update the device or is there any other way to do it?

**Comment by jerpelea** [comment]
all A/B devices use update_engine if you want to use the A/B updates.

**Comment by AlexandreStumpf** [comment]
Ok, thanks.

Is it possible to update an a/b device the same way we use in xz1 for example?

**Comment by jerpelea** [comment]
it should be if you force the A partition to be always mounted (in kernel dt and fstab) and you mount a partition as cache partition
