### ISSUE TITLE
[Website] Software binaries page shows only latest versions

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#206]
this issue is about the list of software binaries accessible under the link:
https://developer.sony.com/develop/open-devices/downloads/software-binaries

the list gets periodically updated, but with each update the older versions of vendor binaries are completely removed!

for example if there's a newer version of the binaries for loire meant for android 8.1 and kernel 4.4 then the older version meant for the same combination of android and kernel versions gets completely removed from the list.
this is completely impractical because newer binaries releases aren't always backwards compatible. if a user is running an old system on his device, then updates to the latest binaries release for the android and kernel combination his device is on, then it's not guaranteed his device will boot up properly. If the said user hasn't kept the older binaries release he was using before stored somewhere, then he can never boot up using the system currently installed on his device!

please also allow downloading of older binaries releases from the webpage. that would be immensely helpful.

**Comment by carlosruiloba** [comment]
The issue has been addressed, it might take a few days before older versions are available.

**Comment by oshmoun** [comment]
thanks for the heads up!
Can confirm that there are now multiple versions of the software binaries for the android 8.1 and kernel 4.4 combination.

**Comment by carlosruiloba** [comment]
Older versions of binaries for Android 8.1 has been added to the list, https://developer.sony.com/develop/open-devices/downloads/software-binaries

**Comment by abioteau** [comment]
@carlosruiloba There is an error on website https://developer.sony.com/file/download/software-binaries-for-aosp-pie-android-9-0-kernel-4-9-tone-latest/ page should be for v1. Could you fix it?

**Comment by carlosruiloba** [comment]
Thanks for noticing! The error has been fixed.
