### ISSUE TITLE
Crash on developer options in Settings

### ISSUE THREAD

**Issue by AlexandreStumpf** [sonyxperiadev/bug_tracker#209]
**Platform:** 
Pioneer
**Device:** 
XA2
**Kernel version:** 
default
**Android version:** 
8.1

**Description**
Crash when open Developer Options in settings
**Symptoms**
Crash
**How to reproduce**
Open Settings -> System -> Developer Options

Here are some logs:

10-16 10:59:14.363  4505  4505 D SubSettings: Launching fragment com.android.settings.development.DevelopmentSettings 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry: No service published for: oem_lock 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry: android.os.ServiceManager$ServiceNotFoundException: No service published for: oem_lock 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.os.ServiceManager.getServiceOrThrow(ServiceManager.java:75) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.SystemServiceRegistry$72.createService(SystemServiceRegistry.java:787) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.SystemServiceRegistry$72.createService(SystemServiceRegistry.java:785) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.SystemServiceRegistry$StaticServiceFetcher.getService(SystemServiceRegistry.java:987) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:914) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.ContextImpl.getSystemService(ContextImpl.java:1667) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:171) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.Activity.getSystemService(Activity.java:5925) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at com.android.settings.SettingsPreferenceFragment.getSystemService(SettingsPreferenceFragment.java:500) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at com.android.settings.development.DevelopmentSettings.onCreate(DevelopmentSettings.java:396) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.Fragment.performCreate(Fragment.java:2489) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1237) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2407) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2186) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2142) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:799) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:742) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at com.android.settings.SettingsActivity.launchSettingFragment(SettingsActivity.java:429) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:321) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.Activity.performCreate(Activity.java:7009) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.Activity.performCreate(Activity.java:7000) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.ActivityThread.-wrap11(Unknown Source:0) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.os.Handler.dispatchMessage(Handler.java:106) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.os.Looper.loop(Looper.java:164) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at android.app.ActivityThread.main(ActivityThread.java:6494) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at java.lang.reflect.Method.invoke(Native Method) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
10-16 10:59:14.370  4505  4505 E SystemServiceRegistry:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
![2018-10-16](https://user-images.githubusercontent.com/3493532/47023749-b03c9680-d136-11e8-9578-e00fa20c7bd1.jpg)

**Comment by AlexandreStumpf** [comment]
Yes

**Comment by jerpelea** [comment]
please never build an eng build unless you need it
the regular builds are user and userdebug
