### ISSUE TITLE
[all] enrolled fingerprints are not accepted after a certain period of time

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#21]
**Platform:** loire, tone, yoshino
**Device:** all
**Kernel version:** 4.4
**Android version:** 8.0

**Description**
When using fingerprints, it might happen that detection will always fail for already enrolled fingerprints.
The only solution is to manually delete fingerprint data from /data/system/...

**Symptoms**
Trying to unlock the device with an enrolled fingerprint fails.
Trying to delete the fingerprints in order to re-enroll them fails.

**How to reproduce**
Enroll a couple of fingerprints, then use the device as usual. At some point, all tries to authenticate using the enrolled fingerprints shall fail.

**Comment by oshmoun** [comment]
The issue here seems to be related to negative ids. The authentication breaks as soon as there's a negative id in /data/system/users/0/settings_fingerprint.xml

**Comment by oshmoun** [comment]
Ok this seems to be the cause. Android is reopening fingerprint hal, and that seems to cause things to go awry.

**Comment by notz** [comment]
Seems that finger print scanner is looping also deleteing of old fingerprints isn't working.
```
11-09 09:06:20.439   747  8095 E FPC IMP : Error waiting for irq: -1
11-09 09:06:20.465   747  8095 D AOSP FPC HAL: auth_thread_loop : Got Input with status 1001
11-09 09:06:20.466   747  8095 D FPC IMP : fpc_capture_image
11-09 09:06:20.469   747  8095 D FPC IMP : fpc_wait_finger_lost
11-09 09:06:20.479   747  8095 E FPC IMP : Finger lost as expected
11-09 09:06:20.480   747  8095 D FPC IMP : fpc_wait_finger_down
11-09 09:06:20.486   747  8095 E FPC IMP : Wait finger down result: 0
11-09 09:06:21.489   747  8095 D FPC COMMON: timeout
11-09 09:06:21.492   747  8095 E FPC IMP : Error waiting for irq: -1
11-09 09:06:21.519   747  8095 D AOSP FPC HAL: auth_thread_loop : Got Input with status 1001
11-09 09:06:21.519   747  8095 D FPC IMP : fpc_capture_image
11-09 09:06:21.523   747  8095 D FPC IMP : fpc_wait_finger_lost
11-09 09:06:21.533   747  8095 E FPC IMP : Finger lost as expected
11-09 09:06:21.534   747  8095 D FPC IMP : fpc_wait_finger_down
11-09 09:06:21.541   747  8095 E FPC IMP : Wait finger down result: 0
11-09 09:06:22.543   747  8095 D FPC COMMON: timeout
```

```
11-09 09:08:42.852  1060  1060 W FingerprintService: Client com.android.settings failed to respond to cancel, starting client android.os.BinderProxy@5e198e3
11-09 09:08:42.853  1060  1060 V FingerprintService: starting client RemovalClient(android.os.BinderProxy@5e198e3), initiatedByClient = false)
11-09 09:08:42.855  8362  8362 D FPC IMP : fpc_del_print_id
11-09 09:08:42.855  8362  8362 D FPC IMP : send_custom_cmd
11-09 09:08:42.866  8362  8362 D android.hardware.biometrics.fingerprint@2.1-service: onError(6)
11-09 09:08:42.869  8362  8362 E android.hardware.biometrics.fingerprint@2.1-service: An unknown error returned from fingerprint vendor library: -1
11-09 09:08:42.870  1060  1060 W FingerprintService: startRemove with id = -1898422450 failed, result=1
11-09 09:08:42.872  1060  1060 V FingerprintService: Done with client: android.os.BinderProxy@5e198e3
11-09 09:08:42.873  1060  1060 V FingerprintService: handleError(client=android.os.BinderProxy@5e198e3, error = 6)
11-09 09:08:42.876  5333  5333 W FingerprintManager: Invalid error message: 6, 0
```

**Comment by jerpelea** [comment]
@BuzzBumbleBee
@EnJens

**Comment by dimitar10** [comment]
I can confirm the same behaviour for **suzu** and **kagura** as well. It happens on both 7.1.1 and 8.0.0. Additionally, this behaviour is not only caused by reboots but also by factory resets i.e. if after a fresh flash and enrollment of fingerprints the device is working OK, you can factory reset the device and the issue will appear after adding new fingerprints.

**Comment by oshmoun** [comment]
An unverified theory about what happens, feel free to ignore:
The database file created is not accessible after the hal instance that created it is closed. That means that the data about enrolled fingerprints are not recognized by later hal instances (after a reboot, crash etc..). Writing to the database is impossible as well.
It seems that when creating the database, something is setup in the hal that makes reading and writing to database still possible. After a reload, that "thing" is lost, and the database is inaccessible. Could there be some sort of a transient property that's not stored properly by our hal?
Luckily though, this doesn't happen always, and after some tries of creating and then removing the database, it seems to remain accessible always.

**Comment by kholk** [comment]
@oshmoun Please change the tag from kugo to ALL.

**Comment by jerpelea** [comment]
1. remove user.db and settings_fingerprint.xml
2. reboot
3. go to settings->fingerprint and enroll a fingerprint
4. after finishing, go back to the fingerprint list and remove the just enrolled fingerprint
5. go out of the list, now the hal should have restarted (logcat | grep fingerprint_open should return two lines)
6. you're all set, the database is sane and you can enroll and delete fingerprints as much as you want! (edited)

**Comment by jamuir** [comment]
I see continual FPC logcat spam on maple even when no fingerprints have been enrolled.

**Comment by tomgus1** [comment]
I can confirm the workaround is working on Suzu. 

**Kernel version**: 4.4 (LA.UM.5.7)
**Android version**: 8.0

**Comment by oshmoun** [comment]
A small update on the workaround, it doesn't seem to work anymore on loire with aosp 8.1
It fails to read the database, and shows this error log in logcat:
https://github.com/sonyxperiadev/vendor-sony-oss-fingerprint/blob/master/fingerprint.c#L378

**Comment by MarijnS95** [comment]
@oshmoun I've never been able to get the workaround to work on Omnirom since it's first 8.1 release.
I get the same error when the FPC loads, with code `-6` ([`FPC_ERROR_IO` apparently](https://github.com/sonyxperiadev/vendor-sony-oss-fingerprint/blob/7a3b1d936dc827102fd87216977671db8e2fe80c/fpc_imp_loire_tone.c#L64)).

As soon as I kill the HAL I see the following messages appear in `dmesg`:

```
[ 1142.358703] init: Service 'fps_hal' (pid 6647) killed by signal 9
[ 1142.358770] init: Sending signal 9 to service 'fps_hal' (pid 6647) process group...
[ 1142.358992] init: Successfully killed process cgroup uid 1000 pid 6647 in 0ms
[ 1142.360990] init: starting service 'fps_hal'...
[ 1142.367904] init: property_set("ro.boottime.fps_hal", "1142363496437") failed: property already set
[ 1142.368839] QSEECOM: qseecom_unload_app: App id 458754 now unloaded
[ 1142.417237] QSEECOM: qseecom_load_app: App (keymaste) does'nt exist, loading apps for first time
[ 1142.428585] scm_call failed: func id 0x32000101, ret: -2, syscall returns: 0xffffffda, 0x0, 0x0
[ 1142.428708] QSEECOM: qseecom_load_app: scm_call to load app failed
[ 1142.428777] QSEECOM: qseecom_ioctl: failed load_app request: -22
[ 1142.436667] QSEECOM: qseecom_load_app: App (tzfingerprint) does'nt exist, loading apps for first time
[ 1142.839903] QSEECOM: qseecom_load_app: App with id 524290 (tzfingerprint) now loaded
```

The `qseecom` errors appear at first startup as well. However, `Error loading user database` only appears after the screen turns on or off.

I don't think this'll help debugging (and it might not be related anyway), but I just wanted to put it out there and chime in; playing around with Android ROM's and the kernel has been a learning experience for me thus far.

**Platform**: loire
**Device**: suzu
**Kernel version**: 4.4.114-gb24fbb874c33 (LA.UM.6.4)
**Android version**: 8.1 (Omnirom)

(On a completely unrelated note, nightlight doesn't work either. At this point I don't know if this is specific to Omnirom or applies to Sony AOSP in general, so I have no idea where to report it. All I know is that `sdm-color.so` is missing, which apparently is a proprietary library. It's either (intentionally) missing from the software binaries, or incorrectly expected to be present).

**Comment by kholk** [comment]
Quick "question" (no, it's not a question)...

Are we really supposed to reload the keymaster TZ "app"? :))))))

**Comment by oshmoun** [comment]
@MarijnS95 yes, the workaround doesn't seem to work anymore on 8.1 so thanks for confirming that.
It did work on 8.0 though iirc.
The logcat seems ok at first glance, since it eventually loads the apps, and fpc does work if the database is created in the same hal instance. The issue only appears when it needs to reads the database to know about already existing data.
(About the completely unrelated note, please open a new issue in this repository)

@kholk where do you see that keymaster is reloaded? I can only see it loaded once per hal instance.

**Comment by kholk** [comment]
Yes obi... Exactly. :D

**Comment by oshmoun** [comment]
ah, I see what you mean.
Checking if keymaster app is already loaded before trying to load it in the hal could be possible with app_load_query, assuming the name implies the function.
Although it's pretty unlikely to have any effect on the bug at hand

**Comment by EnJens** [comment]
@kholk if you can demonstrate any other way to get a handle to the keymaster app, please do tell.

As far as I understand, calling load app doesn't actually load it if it's already loaded. It just returns a handle to the already loaded (regardless of who loaded it) application.

**Comment by jerpelea** [comment]
post loire devices don't have keymaster firmware in userspace
HAL will fail to load it

**Comment by kholk** [comment]
Yea Alin, but they are anyway getting the handle in the same way and managed the same way (to a certain extent)...

@EnJens There are actually multiple ways, or.. Were. I've studied the TZ quite a lot back in the Z2 Tablet days.... I should still have my notes about it somewhere on my HDD, whenever I find some time to search, I'll tell you something good, hopefully :D

**Comment by jerpelea** [comment]
yes but Hal now tries to load the old firmware

**Comment by oshmoun** [comment]
for tone and yoshino users:
please check if this resolves the issue for you
https://github.com/sonyxperiadev/vendor-sony-oss-fingerprint/pull/16
Then try to replicate the issue by:
1. removing the existing user.db and settings_fingerprint.xml
2. rebooting
3. enrolling/removing fingerprints normally
4. rebooting

**Comment by MarijnS95** [comment]
@oshmoun I've never used AOSP 8.0 so I can't comment on that unfortunately. I'll open a new issue asap, same for the missing `vendor-broadcom-wlan` repo.

I assume you're not asking for `loire`/`suzu` users because you've tested that already, but just to "confirm", `AOSP FPC HAL: Error loading empty user database: -6` is logged after rebooting.

**Comment by jerpelea** [comment]
@MarijnS95 
the "missing vendor-broadcom-wlan" is there
https://github.com/sonyxperiadev/local_manifests/blob/master/broadcom.xml#L4

**Comment by MarijnS95** [comment]
@jerpelea I was asking specifically for omnirom, because I wasn't sure what the right place was for filing issues. I've already found out that it's a little more complicated than getting the reference mainlined; I do use that repository for it though.

**Comment by jerpelea** [comment]
ok

**Comment by oshmoun** [comment]
Closing this issue, since it has been
confirmed resolved with the merged https://github.com/sonyxperiadev/vendor-sony-oss-fingerprint/pull/16

Please do note though that loire and yoshino devices have different issues that prohibit proper functionally of fpc. This will need to be resolved too.
