### ISSUE TITLE
Not able to get unlocking code for XA2 Plus

### ISSUE THREAD

**Issue by saukko** [sonyxperiadev/bug_tracker#210]
**Device:** XA2 Plus

**Description**
Currently it is not possible to unlock XA2 Plus devices at https://developer.sony.com/develop/open-devices/get-started/unlock-bootloader/

**Comment by jamuir** [comment]
Do you mean "XA2 Plus" is not in the list of devices (at the bottom of the page)?

If you try selecting a different device (e.g. "Xperia XA2"), then it might work.

**Comment by carlosruiloba** [comment]
Xperia XA2 Plus has now been added to the unlock bootloader list, https://developer.sony.com/develop/open-devices/get-started/unlock-bootloader/
