### ISSUE TITLE
[TAMA] [AKARI] Unable to unlock bootloader in PIE

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#211]
**Platform:** tama
**Device:** akari

Since upgrading to PIE via OTA it is not longer possible to unlock the bootloader in the developer settings.
The Button is gray.
The support is telling me that this is intended since PIE.

So will the xperia AOSP project be stopped on the TAMA line?

**Comment by jerpelea** [comment]
There is a bug in the P release and we are working on fixing it ASAP
please DO NOT UPDATE your device to P if you want to unlock your device until the bug is fixed (minimum 2 Months)

**Comment by jerpelea** [comment]
please DO NOT UPDATE devices to P

**Comment by MartinX3** [comment]
Once it happen (because of OTA this happens ASAP), there is no way back?

**Comment by jerpelea** [comment]
NO

**Comment by MartinX3** [comment]
Shit, I inform as many people I can get!

**Comment by jerpelea** [comment]
flashtool may be an option for downgrade

**Comment by MartinX3** [comment]
One guy reported me that in OREO the button is still gray.

**Comment by jerpelea** [comment]
I tested an O device and it is not gray 

you have to put a SIM in the phone for the phone to enable the option

**Comment by MartinX3** [comment]
That may be the issue.

But your test phone **was not unlocked** before?
So you upgraded a "locked" phone to pie, you tried the developer options, then you downgraded it again and tried the developer options again?

**Comment by jerpelea** [comment]
I unlocked the device on O

**Comment by MartinX3** [comment]
I am glad that this is not a persistent problem and a downgrade makes it possible to unlock the bootloader. :)

**Comment by AndroPlus-org** [comment]
@jerpelea
This problem is also happens on XZ3 (Tama - Akatsuki) and there is no O ROM for XZ3.
How can we unlock bootloader on the devices shipped with Pie?

**Comment by jerpelea** [comment]
fixed
release ASAP

**Comment by MartinX3** [comment]
I love you all for your hard work!
