### ISSUE TITLE
[akari] console-ramoops isn't available after kernel panic

### ISSUE THREAD

**Issue by icefalcon2225** [sonyxperiadev/bug_tracker#212]
Platform: tama
Device: Xperia XZ2 H8266 (akari)
Kernel version: 4.9.103-gb1cbb20
Android version: 8.1.0_r47 OPM6.171019.030.K1

**Description**
console-ramoops does not appear in /sys/fs/pstore after a kernel panic.  The pstore is mounted on /sys/fs/pstore as expected, but no console-ramoops file appears there after a kernel panic.

**How to reproduce**
After a kernel panic and reboot on the Xperia XZ2, look in /sys/fs/pstore when the device comes back up.  The console-ramoops file is missing.

**Comment by jamuir** [comment]
did you check the kernel config to see if pstore is enabled?

**Comment by icefalcon2225** [comment]
I think that PSTORE is enabled.  I looked in kernel/sony/msm-4.9/kernel/arch/arm64/config/aosp_tama_akari_defconfig, and all three entries containing PSTORE are enabled:
```
     $ grep PSTORE kernel/sony/msm-4.9/kernel/arch/arm64/configs/aosp_tama_akari_defconfig 
CONFIG_PSTORE=y
CONFIG_PSTORE_CONSOLE=y
CONFIG_PSTORE_RAM=y
```
Is there anything else that should also be enabled for pstore to work?  Thanks.

@jamuir

**Comment by oshmoun** [comment]
is console-ramoops the only thing missing? do you see pmsg or anything else under /sys/fs/pstore or is it completely empty?

**Comment by icefalcon2225** [comment]
/sys/fs/pstore is completely empty.  So, you are correct in that it is missing the pmsg file in addition to the ramoops file.

**Comment by kholk** [comment]
We may not be setting the right parameters in the PMIC reboot reason registers. That's usually the cause.

**Comment by hitmoon** [comment]
> We may not be setting the right parameters in the PMIC reboot reason registers. That's usually the cause.

I have a qcom 8996 phone with this issue too. How can I check PMIC reboot reason of kenel panic ?
