### ISSUE TITLE
[Loire] Android 9.0_r10 with vendor binaries v2 no mobile network (no Sim card)

### ISSUE THREAD

**Issue by iDavLaFF** [sonyxperiadev/bug_tracker#215]
**Platform:** Loire
**Device:** Suzu
**Kernel version:** 4.9.103-gf0b1578883a9
**Android version:** 9.0

**Description**
With vendor binaries v2 SIM-card not detect

**Symptoms**
No SIM detection

**How to reproduce**
No Sim card in mobile data toggle; Baseband version: unknown; *#*#4636#*#* close at once; the window with IMEI is empty.

**Comment by jerpelea** [comment]
logcat -b radio

**Comment by iDavLaFF** [comment]
> logcat -b radio

[logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/2497408/logcat.txt)

**Comment by jerpelea** [comment]
tnx
I replicated the bud and a fix will come ASAP

**Comment by insideTheFlux** [comment]
Is this related to the closed poplar(sim cards non-functional) issue I posted a while ago @jerpelea?

**Comment by iDavLaFF** [comment]
@jerpelea and again on boot to system show window (Android System: There's an internal problem with your device...)

**Comment by jerpelea** [comment]
please sync r10 and rebuild your sw! then flash vendor v2_beta

**Comment by jerpelea** [comment]
from your log
android.hardware.radio.config@1.0.so not found

**Comment by harryharryharry** [comment]
I have a F5321 (kugo) and I'm having the same issue. I just synced, rebuilt and dirty flashed omnirom (btw android/default.xml shows r12) and flashed v2_beta but still no sim detected.

**Comment by harryharryharry** [comment]
I have this issue too on my f5321 (kugo). I synced, rebuilt and dirty flashed omnirom 9 (_r12) and then v2_beta. The sim is not detected at first but it is a couple of minutes after I boot now.

**Comment by jerpelea** [comment]
loire devices have a bug that affects RIL
i was asking for resync because in the previous log a lib was missing.

**Comment by harryharryharry** [comment]
Ok, so the sim initialization timeout on boot is expected behaviour for now ?

**Comment by jerpelea** [comment]
loire has a bug
I could not replicate issuss on the other platforms

**Comment by iDavLaFF** [comment]
> loire i suppose

yes

**Comment by jerpelea** [comment]
the bug was fixed and the fix will come on vendor v3

**Comment by Dark98** [comment]
@jerpelea kugo at least, still seems to have very slow SIM detection with ODM V3, it gets detected eventually bits it's much slower then v1

**Comment by MartinX3** [comment]
TAMA XZ2 -> OEM v5 -> AOSP 9.0r30
Sadly slow mobile network connection.

**Comment by MartinX3** [comment]
@jerpelea
