### ISSUE TITLE
[tone][kagura] qcom/display: Switching to LA.UM.7.3.r1 breaks the build

### ISSUE THREAD

**Issue by ix5** [sonyxperiadev/bug_tracker#216]
**Platform:** Tone
**Device:** Kagura
**Kernel version:** 4.9
**Android version:** 9.0.0_r10

**Description**
We're using the `LA.UM.7.3.r1` tree instead of `LA.UM.6.3.r1` for [hardware-qcom-display](https://github.com/sonyxperiadev/hardware-qcom-display/) since [Wednesday](https://github.com/sonyxperiadev/local_manifests/commit/d90f9e16421acb90a6a36662d3fda6c6a5dbcf2b).

**Symptoms**
Error log:
```
[928/928] including vendor/qcom/opensource/wlan/wcnss-service/Android.mk ...
hardware/qcom/display/sde/sdm/libs/hwc2/../../../common.mk: error: hwcomposer.msm8996 (SHARED_LIBRARIES android-arm64) missing vendor.display.config@1.2 (SHARED_LIBRARIES android-arm64) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
hardware/qcom/display/sde/sdm/libs/hwc2/../../../common.mk: error: hwcomposer.msm8996 (SHARED_LIBRARIES android-arm) missing vendor.display.config@1.2 (SHARED_LIBRARIES android-arm) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:833: error: exiting from previous errors.
```

**How to reproduce**
Build with current local_manifests master branch.

**Comment by ix5** [comment]
Duh, I'm meant to use `local_manifests` android_9.0.0_r10 to build for kagura instead of master, aren't I?

**Comment by jerpelea** [comment]
please use r10 as instructed by the build guide for all devices except tama platform
