### ISSUE TITLE
[tama] fastboot boot causes bootloop

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#219]
**Platform:** tama
**Device:** akari, apollo, aurora

**Description**
Dear Sony-Team, I changed the ramdisk to use TWRP.
It is working fine, but there is one thing I've never seen before.
Even on XA2 and XZ1 it is working the old way.

I can't boot the recovery with 
`fastboot boot twrp.img`

I need to initially execute
`fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img`
every time after I used newflasher.
And every time I want to install TWRP, I need to 
`fastboot flash boot twrp.img`

By the way I then need in TWRP to flash again the same stock boot.img and the same RAMDISK again, to be able too use TWRP and boot into the system.

On the XA2 and XZ1 and other devices like Galaxy S9 or OnePlus 6, they only need to
`fastboot boot twrp.img`
to get into the recovery.

Did something changed with the XZ2, XZ2C, XZ2P?
How to be able to use 'fastboot boot' ?

**Symptoms**
Bootloop

**How to reproduce**
- fastboot boot twrp.img

instead of

- fastboot flash boot twrp.img
- fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img

**Comment by jerpelea** [comment]
tama uses boot.img dtbo.img and vbmeta.img to for kernel, dtb overlay and vbmeta
TWRP is not supported by Open Devices but you can use the android recovery

**Comment by jerpelea** [comment]
tama uses boot.img dtbo.img and vbmeta.img to for kernel, dtb overlay and vbmeta
TWRP is not supported by Open Devices but you can use the android recovery

**Comment by MartinX3** [comment]
@jerpelea
So the xz1 and xa2 doesn't use these things?
Because there the fastboot boot twrp.img works.

**Comment by jerpelea** [comment]
no
those devices do not use vbmeta and dtbo

**Comment by MartinX3** [comment]
Thank you very much, @jerpelea !
So there is no way to include these in the bootimage.img to make it usable with
"fastboot boot bootimage.img" ?

**Comment by jerpelea** [comment]
I never tried to boot TWRP on tama

**Comment by MartinX3** [comment]
fastboot boot aosp.img doesn't either work with the stock firmware on this device.
I also need to flash the dtbo.img

So if I want to switch the kernel I can't include the dtbo into the boot.img?
@jerpelea
