### ISSUE TITLE
[tone][loire] compass does not work reliably

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#22]
**Platform:** loire, tone
**Device:** kugo, suzu, kagura
**Kernel version:** 4.4
**Android version:** 8.0

**Description**
The compass does not seem functional, some apps tested do not report any compass value, these include Google maps and GPS toolbox. 
Other apps like Phonetester report errant values. 

**Symptoms**
Google maps doesn't show the current orientation
GPS Toolbox always reports 0°
Phonetester reports values in the range from 300° to about 50° (going through 0°)

**How to reproduce**
Try to use any apps that makes use of the compass
it sometimes might decide to randomly work, but a couple reboots should help reproduce the issue.

**Comment by jerpelea** [comment]
I checked compas functionality in Phone Tester and it works normal 

please install Phonetester and check it compass is corectly reported 

Please note that Google apps are not supported by this project!

**Comment by oshmoun** [comment]
Can confirm that Phonetester shows a working compass.
Will test more apps then and see if the issue really only affects apps that is Google's services

**Comment by djselbeck** [comment]
I had a non working compass on tone a few times. Was fine after power off and restart. Normal reboot has not helped (may be related)

**Comment by oshmoun** [comment]
issue confirmed fixed after iommu rewrite
https://github.com/sonyxperiadev/kernel/pull/1508

**Comment by oshmoun** [comment]
It seems the issue is not quite resolved!
It happens randomly upon boot, and sticks until rebooting.

**Comment by oshmoun** [comment]
The issue is now (hopefully definitely) resolved with the removal of the sensors service
https://github.com/sonyxperiadev/device-sony-common/pull/362
Compass has so far survived all reboots here
