### ISSUE TITLE
[lilac] [tone] Fingerprint enrollment causes reboot.

### ISSUE THREAD

**Issue by russel5** [sonyxperiadev/bug_tracker#220]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9
**Android version:** 9

**Description**
Fingerprint setup causes the phone freeze then phone reboot.

**Symptoms**
Fingerprint setup causes the phone freeze then phone reboot.

**How to reproduce**
Try to setup fingerprint on lilac.

Logcat --> http://pasted.co/6b83a5dc

**Comment by ix5** [comment]
Same happens on kagura/tone.
@russel5 did you fix it in https://github.com/sonyxperiadev/vendor-sony-oss-fingerprint/blob/master/android.hardware.biometrics.fingerprint%402.1-service.sony.rc ?

**Comment by russel5** [comment]
@ix5 i'm just compiled firmware without fingerprint.

**Comment by russel5** [comment]
@jerpelea oem v3 fix this problem?

**Comment by jerpelea** [comment]
the fingerprint is OSS

**Comment by russel5** [comment]
rebuild, still same bug. random reboot with logspam HAL fingerprint

**Comment by VictorRyabov** [comment]
Confirmed on my lilac. @alviteri how about you?

**Comment by ix5** [comment]
Sure you're on 4.9.137? I could reliably reproduce it on .103 before, but not any more. Clean install.

**Comment by russel5** [comment]
since last two pull requests in fingerprint tree fix this issue
@jerpelea can you merge it?
