### ISSUE TITLE
[All] Pie r10 tag needs to be updated

### ISSUE THREAD

**Issue by ix5** [sonyxperiadev/bug_tracker#221]
**Platform:** All
**Device:** All
**Kernel version:** All
**Android version:** 9.0.0

**Description**
The android-9.0.0_r10 tag is not available for many AOSP repos anymore, the last available is r11, and we should ideally update to r12.

Also, at least this patch no longer applies:
`[Replace hardcoded build barrier with a generic one](https://android.googlesource.com/platform/hardware/qcom/bootctrl/+/0ae34c3) is invalid since [Android.mk: add sdm710]( https://android.googlesource.com/platform/hardware/qcom/bootctrl/+/a8e07aecb24898d7d2b49cb785b0c193a4b134b4)

**Symptoms**
`repo sync` is unable to fetch non-existent r10 tags.
Examples:
```
Fetching project platform/external/libexif
fatal: Couldn't find remote ref refs/tags/android-9.0.0_r10
Fetching project platform/hardware/qcom/sdm845/data/ipacfg-mgr
fatal: Couldn't find remote ref refs/tags/android-9.0.0_r10
Fetching project platform/external/skqp
Fetching project platform/hardware/qcom/sdm845/thermal
fatal: Couldn't find remote ref refs/tags/android-9.0.0_r10
fatal: Couldn't find remote ref refs/tags/android-9.0.0_r10
fatal: Couldn't find remote ref refs/tags/android-9.0.0_r10
fatal: Couldn't find remote ref refs/tags/android-9.0.0_r10
error: Cannot fetch platform/hardware/qcom/sdm845/gps
Fetching project platform/external/lisa
fatal: Couldn't find remote ref refs/tags/android-9.0.0_r10
error: Cannot fetch platform/hardware/qcom/sdm845/bt
error: Cannot fetch platform/hardware/qcom/sdm845/data/ipacfg-mgr
error: Cannot fetch platform/hardware/qcom/sdm845/thermal

error: Exited sync due to fetch errors
```

**How to reproduce**
Use `repo init -u https://android.googlesource.com/platform/manifest -b android-9.0.0_r10` as per build instructions and `repo sync`.

**Comment by jerpelea** [comment]
plese remove your old repo and start in a clean folder

**Comment by ix5** [comment]
Deleting manifests.git and starting over fixed it. Thanks!
