### ISSUE TITLE
[Website] Download subdomain still uses Symantec certificate

### ISSUE THREAD

**Issue by MarijnS95** [sonyxperiadev/bug_tracker#223]
Unlike `developer.sony.com`, `dl.developer.sony.com` still uses the old Symantec certificate which is not allowed/safe anymore.
Most (if not all) modern browsers (should) block it by now, making users unable to download software binaries and open source archives. Please replace the certificate with the newer one.

**Comment by carlosruiloba** [comment]
Thansk for notifying this! The certificate has been replaced.

**Comment by MarijnS95** [comment]
Thanks! Binaries can be downloaded again.
