### ISSUE TITLE
[ALL PLATFORMS] 1080P@60FPS recording

### ISSUE THREAD

**Issue by RobbieBnt** [sonyxperiadev/bug_tracker#224]
**Platform: any** 
**Device: any** 

**Description**
On AOSP we can record 1080P@30fps video using k4.4 and the latest blobs. But IMX300 and IMX400 are capable of capturing more.
Many thanks to Alin for listening to me for all these 9 months of asking :)

**How to reproduce**
Try to record any video with either 4.4 or 4.9 kernels.

**Comment by jerpelea** [comment]
the new modes are enabled and can be used starting with vendor v4

**Comment by RobbieBnt** [comment]
Can't get it working. Using v4 blobs from [there](https://developer.sony.com/file/download/software-binaries-for-aosp-pie-android-9-0-kernel-4-9-loire-v4/). Should I panic right now or I do need to wait until more... official release of them?

[https://drive.google.com/file/d/1ozzMwUEh3nuKuD2CVZU280kaQ5XK72uK/view?usp=sharing](Screenshot, OpenCamera was used)

**Comment by lubik1** [comment]
Can confirm, only 30fps record great on last v4 binaries. On OpenCamera 60fps glitch on viewfinder and get error then thying record video. With Google Cam it record with 60fps but if i enable stabilisation - it glitch and present green artifacts like a stripes.


![gif](https://user-images.githubusercontent.com/19878552/50288645-2fb85000-046f-11e9-9e2b-a5ee3d7e4e2c.gif)
