### ISSUE TITLE
OTA on h3123

### ISSUE THREAD

**Issue by AlexandreStumpf** [sonyxperiadev/bug_tracker#226]
**Platform:** 
Nile
**Device:** 
XA2
**Kernel version:** 
4.4
**Android version:** 
8.1

**Description**
We have the OTA working on XA2 h4113, but is does not work on h3123. The OTA is applied ok and the system boot on the new partition, but it freeze and does not complete the boot process. We have no idea what is the problem and the difference between h4113 and h3123. Can anyone pease help us?

**Comment by MartinX3** [comment]
https://xpericheck.com/
Take a look and write XA2 in the filter. :)

**Comment by jerpelea** [comment]
for the moment we do not support OTA updates on unlocked phones and you can implement a local solution as a workaround

**Comment by jamuir** [comment]
> for the moment we do not support OTA updates on unlocked phones

is your comment specific to the XA2?

**Comment by MartinX3** [comment]
I think so.
He wrote "unlocked phones". :)

**Comment by jerpelea** [comment]
with a local implementation OTA works on supported devices

**Comment by jerpelea** [comment]
please check bootloader version and partition size for all variants that are not supported in github
