### ISSUE TITLE
[pioneer] /tmp directory does not exist on h3113

### ISSUE THREAD

**Issue by berengerfoucher** [sonyxperiadev/bug_tracker#227]
**Platform:**  nile
**Device:** pioneer
**Kernel version:** 4.4
**Android version:** 8.1.0

**Description**
No tmp directory after the device just booted.

**Symptoms**
It looks like init is not able to create /tmp directory. mkdir command (still in the init) returns -30, then mount point does not exist. It seems weird because application may try to read and write from this directory.

Is it the expected behavior ?

**How to reproduce**
This problem occured on a clean build of Android 8.1 (userdebug) for h3113.

Thank you for your help!

**Comment by jerpelea** [comment]
the folder seems to be deprecated in Android and removed 
https://github.com/sonyxperiadev/device-sony-common/commit/757ef70088ca1ca8116af1f2eec49d89c09715a2

**Comment by MartinX3** [comment]
What do we use now instead of temp? :)
