### ISSUE TITLE
[All] - Android 9 - Can't enable wifi tethering

### ISSUE THREAD

**Issue by harryharryharry** [sonyxperiadev/bug_tracker#228]
**Platform:** Loire
**Device:** Kugo
**Kernel version:** 4.9.103-g420130fea212
**Android version:** 9.0

**Description**
Wifi tethering disables a few seconds after enabling it.
logcat: http://ix.io/1rbj (tethering enabling attempt at the very end of the logcat)

**Symptoms**
No wifi tethering possible.

**How to reproduce**
Attempt to enable wifi tethering in settings.

**Comment by ix5** [comment]
I can confirm this is happening on tone(kagura) as well. Obi says this means it is a general Pie issue and not brcmfmac.
> I believe it's the same issue prohibiting wireless display from working
> Something is up with creation of network interfaces
-- obi

Log attached
[wifi-hotspot.txt](https://github.com/sonyxperiadev/bug_tracker/files/2568319/wifi-hotspot.txt)

**Comment by oshmoun** [comment]
confirmed happening on tama as well

**Comment by jerpelea** [comment]
TrafficController: Failed to add iface wlan0(20): Bad file descriptor

**Comment by oshmoun** [comment]
wifi tethering works fine when mobile data is disabled.
Issue has to do with iptables
`11-21 19:02:33.702  1426  1447 E Tethering: [wlan0] ERROR Exception enabling NAT: java.lang.IllegalStateException: command '502 nat enable wlan0 rmnet_data0 1 192.168.43.0/24' failed with '400 502 Nat operation failed (No such device)'
`

**Comment by jerpelea** [comment]
fixed

**Comment by oshmoun** [comment]
https://github.com/sonyxperiadev/kernel-defconfig/pull/19
that should do it for all
