### ISSUE TITLE
[tone][kagura] Camera button not recognized correctly

### ISSUE THREAD

**Issue by ix5** [sonyxperiadev/bug_tracker#229]
**Platform:** tone
**Device:** kagura
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
<strike>Camera key is completely ignored on kagura.</strike>
Camera key is recognized as `UNKNOWN` (check with flar2`s [Button Remapper](https://play.google.com/store/apps/details?id=flar2.homebutton&hl=en_US))

[Add camera key long press handling](https://android-review.googlesource.com/c/platform/frameworks/base/+/727815) does not fix it.

Will investigate and get logs. On which level do I have to look? Logcat is completely silent when pressing the camera button.

**Comment by kholk** [comment]
cat /dev/input/eventX where X corresponds to the event number assigned to gpio-keys

**Comment by ix5** [comment]
Upon further testing, it seems `/dev/input/event2` is spewing the "random" chars for volume keys AND camera button.
(For completeness, `/dev/input0` reacts to the power button.)

**Comment by kholk** [comment]
Then the event is getting sent just fine... It's just an userspace issue.

**Comment by jerpelea** [comment]
fixed

**Comment by ix5** [comment]
Please reopen, as camera key is only recognized as `UNKNOWN`.

**Comment by ix5** [comment]
Some magic commit fixed this, but I cannot remember which one it was.
Anyway, closed for kagura at least.
