### ISSUE TITLE
[suzu] No video for secondary (front-facing) camera

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#23]
**Platform:** loire
**Device:** suzu
**Kernel version:** 4.4 (prebuilt)
**Android version:** 7.1.1 and 8.0
**Firmware version:** v05

**Description**
The secondary (front-facing) camera does not record video.

**Symptoms**
- it (almost) freezes the application 
- almost always followed by "Camera error: Can't connect to the camera" error message
- see screenshot at the bottom

**How to reproduce**
1. Start camera app (main camera is selected by default).
2. Switch to video.
3. Select the front-facing camera from the right bottom menu.

**Screenshots**

![screenshot_20171107-141650](https://user-images.githubusercontent.com/33422321/32498114-0a4a4bfc-c3cf-11e7-8d70-b184e3550c2b.png)

**Comment by alviteri** [comment]
@jerpelea this is legated to aosp camera app ... Google Camera works

**Comment by jerpelea** [comment]
fix it! we dont use google apps!

**Comment by jerpelea** [comment]
bug is confirmed and it can be reproduced on AOSP camera

**Comment by kholk** [comment]
@dimitar10 I can also confirm the bug on AOSP Camera.
While we fix the bug, consider using Open Camera to temporarily mitigate the issue.

Thanks for reporting!

**Comment by oshmoun** [comment]
frontcam video is basically just as reliable as backcam here on kugo.
I.e it takes some tries before a video is actually recorded.

**Comment by oshmoun** [comment]
this issue, at least in its current form, is not replicable anymore.
I.e there is no more artifacting (or at least there shouldn't be)
please confirm/deny, thanks!

**Comment by kholk** [comment]
The issue on suzu is very specific. I am aware of the situation  we have multiple solutions for it.
Please hold on a lil, we are evaluating which is the best solution to apply.

**Comment by kholk** [comment]
Solved with https://github.com/sonyxperiadev/kernel/pull/1516

Please confirm.

**Comment by jerpelea** [comment]
fixed
