### ISSUE TITLE
[tone][kagura] Crash while attempting to start video recording in AOSP camera

### ISSUE THREAD

**Issue by ix5** [sonyxperiadev/bug_tracker#230]
**Platform:** tone
**Device:** kagura
**Kernel version:** 4.9
**Android version:** 9

**Description**
The viewfinder works fine, but as soon as the record button is pressed the camera application crashes.

**Symptoms**
See attached log. The short version is:
```
CAM_VideoModule: null camera within proxy, not recording
MediaRecorder: start called in an invalid state: 1
CAM_VideoModule: Could not start media recorder. 
CAM_VideoModule: java.lang.IllegalStateException
CAM_VideoModule: 	at android.media.MediaRecorder.start(Native Method)
```

**How to reproduce**
Open stock camera app, switch to video recording, hit record.

**Logcat:** [camera-crash-video.txt](https://github.com/sonyxperiadev/bug_tracker/files/2556224/camera-crash-video.txt)

**Comment by jerpelea** [comment]
duplicate https://github.com/sonyxperiadev/bug_tracker/issues/200

**Comment by jerpelea** [comment]
pleas post all info in the other ticket
