### ISSUE TITLE
[tone][kagura] Top speaker disabled on boot for media

### ISSUE THREAD

**Issue by ix5** [sonyxperiadev/bug_tracker#231]
**Platform:** tone
**Device:** kagura
**Kernel version:** 4.9
**Android version:** 9

**Description**
After bootup, media audio does not get played through the top speaker, only the bottom speaker works. Oddly enough, when changing the call volume in Settings, the top speaker starts working, until the next reboot.

I've captured everything from bootup to changing the volume via `logcat -b all`. See [attached logcat](https://sx.ix5.org/onboot-mediaaudiomuted-full.txt).

**Comment by jerpelea** [comment]
@richardtullberg please check

**Comment by ix5** [comment]
Any updates on this? @djselbeck any ideas with your dora?
The only suspicious lines I see are high-level:
```
MediaRouter: onRestoreRoute() : route=RouteInfo{ name=Phone, description=null, \
  status=null, category=RouteCategory{ \
  name=System types=ROUTE_TYPE_LIVE_AUDIO \
  ROUTE_TYPE_LIVE_VIDEO  groupable=false }, \
  supportedTypes=ROUTE_TYPE_LIVE_AUDIO \
  ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
MediaRouter: Selecting route: RouteInfo{ name=Phone, description=null, \
  status=null, category=RouteCategory{ \
  name=System types=ROUTE_TYPE_LIVE_AUDIO \
  ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO \
  ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
```

**Comment by oshmoun** [comment]
@kholk pinctrl

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/kernel/pull/1938/commits/1cf1e0e5a2219256af2f52dbcfc1b504fb978efa
