### ISSUE TITLE
[tone][kagura] Charging only works when charger is plugged in while screen on

### ISSUE THREAD

**Issue by ix5** [sonyxperiadev/bug_tracker#232]
**Platform:** tone
**Device:** kagura
**Kernel version:** 4.9
**Android version:** 9

**Description**
Charging only works when charger is plugged in while screen on.

**How to reproduce**
Turn screen off, plug charging cable in -> Not recognized
Turn screen on, plug charging cable in -> Starts charging

This is irrespective of whether the device has been asleep for only a second or several minutes.

**Comment by davidevinavil** [comment]
We have same issue (random) with zuk z2 and a.4 kernel
But in our case, it charge even there is no arrow in battery and can't see "IN CHARGE" in battery settings
When disconnect cable, charger led still on and need to plug again cable and disconnect to make it off

**Comment by iDavLaFF** [comment]
same issue on Loire platform.

**Comment by ix5** [comment]
Rebuilding with https://github.com/sonyxperiadev/kernel/pull/1845

**Comment by ix5** [comment]
Fixed by https://github.com/sonyxperiadev/kernel/pull/1845 (on tone at least)

**Comment by MarijnS95** [comment]
Same for suzu.
