### ISSUE TITLE
[tone][dora]HEVC 10bit video playback problem

### ISSUE THREAD

**Issue by sjllls** [sonyxperiadev/bug_tracker#233]
**Tone:** 
**Dora:** 
**4.9:** 
**9.0:** 

**Description**
On AOSP 9.0, playing the HEVC 10bit  format video will appear color blocks and jams. The decoder may have a problem.

**Symptoms**
Videos will appear color blocks and jams.

**How to reproduce**
Play a HEVC 10bit  format video with vlc.

**Comment by jerpelea** [comment]
Hi 
I used the 3Mbps and 10Mbps samples from this website 
http://jell.yfish.us/

Both samples played without any issue

**Comment by sjllls** [comment]
@jerpelea Yes, comfirmed this issue had been solved with new source codes.
Thanks for your efforts!
