### ISSUE TITLE
[loire][kugo] build failed AOSP 8.1 

### ISSUE THREAD

**Issue by jw96** [sonyxperiadev/bug_tracker#234]
**Platform:** Loire
**Device:** Kugo
**Kernel version:** 4.4
**Android version:** 8.1

**Description**
I'm trying to build branch android-8.1.0_r51 of AOSP
But I get error.
No idea why this happened.

Here is the full (I think) log:
[LOG](https://pastebin.com/Fib7twL4)

**Symptoms**
build stops at:
[  7% 2299/30840] host Executable: fec...obj/EXECUTABLES/fec_intermediates/fec)
ninja: build stopped: subcommand failed.
16:44:02 ninja failed with: exit status 1
16:44:02 Unable to parse ninja entry " {a lot of: \x00\x00\x00\x00\x00} x00\x0045705": invalid syntax

**How to reproduce**
Just follow tutorial from → [Here CLICK](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-nougat-8-1-oreo-4-4)

**Build machines**
Manjaro , x64, i7-2620M, 8gb ram, 496gb swap
Debian 9, x64, Pentium T4200, 4gb ram, 496gb swap

**Comment by jerpelea** [comment]
one cause may be an incomplete download 
please run :
rm -rf out 
./repo_update.sh
then try to build again

**Comment by jerpelea** [comment]
the second cause may be caused by the fact that the Linux distribution that you are using is untested and we can not provide solutions
