### ISSUE TITLE
[maple] android-8.1, build failure caused by libjson module conflict

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/bug_tracker#236]
**Platform:** yoshino
**Device:** maple (single-sim)
**Kernel version:** 
**Android version:** 

**Description**
I started hitting this last week (8 Nov):

```
build/core/base_rules.mk:238: error: hardware/qcom/msm8998/json-c: MODULE.TARGET.SHARED_LIBRARIES.libjson already defined by device/sony/common/hardware/json-c.
13:59:31 ckati failed with: exit status 1

#### failed to build some targets (41 seconds) ####
```

**Comment by jamuir** [comment]
the conflict is between these two files:

```
./hardware/qcom/msm8998/json-c/Android.mk
./device/sony/common/hardware/json-c/Android.mk
```

**Comment by jamuir** [comment]
@jerpelea  the build failure is caused by the following change that was pushed on 7 Nov:

https://github.com/sonyxperiadev/device-sony-common/commit/9566d81fc8a3e321fa1e5989cfe66095b9cbd50f

**Comment by jerpelea** [comment]
fixed 
https://github.com/sonyxperiadev/local_manifests/commit/f42055275c8332b516d6faabec542644d70fe55f

**Comment by jerpelea** [comment]
thanks for the notification!

**Comment by jamuir** [comment]
you guys should really be doing regularly scheduled builds to catch problem like this.
