### ISSUE TITLE
Google camera

### ISSUE THREAD

**Issue by belov555** [sonyxperiadev/bug_tracker#237]
**Loire:** 
**suzu:** 
**4.9.103:** 
**9:** 

**Description**
Google camera, photo,frontal shoots excellent, video shoots well

**Symptoms**
when taking a photo,

**How to reproduce**
how to fix?
![img_20181110_202159](https://user-images.githubusercontent.com/23725582/48371798-6c9d6400-e6c5-11e8-8076-4ef7d434e802.jpg)

**Comment by oshmoun** [comment]
can you specifiy which gcam version were you using?

**Comment by jerpelea** [comment]
I can not replicate this bug in AOSP camera or Open Camera apps

**Comment by oshmoun** [comment]
@Gray47Maxx can you please state the exact version you used? HDR+ is not exactly available using gcam from the playstore

**Comment by Gray47Maxx** [comment]
@oshmoun yep, of course. 

Broken HDR+ is confirmed by me on: "Tolyan009: MGC_6.1.013_B-S-G-based_v.0.4_TlnNeun", "Tolyan009: MGC_5.3.015_B-S-G-based_v.1.0.15_final_fix_TlnNeun.apk" (everything works fine on 4.4 with this cam), and latest "BSG: MGC_6.1.021_MI8_V1a". [Here](https://www.celsoazevedo.com) is the source of all the cams. 

And, as I mentioned before, at least one of these cams captured pics with HDR+ on k4.4 and latest binaries for it, so...

**Comment by oshmoun** [comment]
Thanks, confirmed the issue
Actually even tried previously know-working versions like arnova v6
Seems like a regression, but logcat does not contain an obvious error
can you try previous odm images for 4.9 to see if this ever worked on 4.9?

**Comment by Gray47Maxx** [comment]
If I'll be free this evening - I'll try to do it today. Else - only tomorrow, sorry. 

But I think someone will try to do it soon

**Comment by jerpelea** [comment]
you should try to revert the latest changes in vendor/qcom/camera

**Comment by jerpelea** [comment]
while you use v3

**Comment by belov555** [comment]
Here I found a version of Arnova, shoots as it should, but it slows down.
![img_20181123_210557](https://user-images.githubusercontent.com/23725582/48957925-9d528880-ef64-11e8-9e58-8238c58501bc.jpg)

**Comment by Gray47Maxx** [comment]
Guess this port can use HDR+ w/o full C2API support (it's limited on current blobs, at least that's what Camera2 Probe says).

**Comment by jerpelea** [comment]
google camera is not supported or tested since it is not available on devices without Gapps

**Comment by jerpelea** [comment]
I am happy to see that you managed to find a working version

**Comment by jerpelea** [comment]
we are looking at it
