### ISSUE TITLE
[Suzu] - Android 8 - USB tethering dysfunctional

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#24]
**Platform:** loire
**Device:** suzu
**Kernel version:** 4.4 (prebuilt)
**Android version:** 7.1.1 and 8.0
**Firmware version:** v05

**Description**
**7.1.1**: Users can't enable USB tethering at all.
**8.0**: Users can enable USB tethering on the device but the PC can't establish a network connection with the device.

**Symptoms**
**Oreo**: USB Tethering can be enabled, but internet is not provided to the connected PC, despite its availability on the device. Actually, the PC cannot even connect to the interface, although it keeps trying.

**How to reproduce**
Apps -> Settings -> Network & Internet -> Hotspot & tethering -> USB tethering toggle button

**Logs** 
N/A

**Comment by kholk** [comment]
Issue is present on both Loire phones.
Please change the title tag to Loire.

**Comment by jerpelea** [comment]
this is a common problem already reported here 
https://github.com/sonyxperiadev/bug_tracker/issues/36

**Comment by jerpelea** [comment]
[   29.986482] RNDIS_IPA NetDev was initialized
[   29.986832] msm_hsusb msm_hsusb: [ci13xxx_start] hw_ep_max = 32
[   29.986851] msm_hsusb msm_hsusb: CI13XXX_CONTROLLER_RESET_EVENT received
[   29.986864] msm_hsusb msm_hsusb: CI13XXX_CONTROLLER_UDC_STARTED_EVENT received
[   29.986874] msm_hsusb msm_hsusb: CI13XXX_CONTROLLER_CONNECT_EVENT received
[   29.987595] init: write_file: Unable to write to '/config/usb_gadget/g1/UDC': Device or resource busy
[   30.055385] SELinux: unrecognized netlink message: protocol=0 nlmsg_type=3493 sclass=netlink_route_socket
[   30.055530] SELinux: unrecognized netlink message: protocol=0 nlmsg_type=3493 sclass=netlink_route_socket
[   30.072816] SELinux: unrecognized netlink message: protocol=0 nlmsg_type=3493 sclass=netlink_route_socket
[   30.086749] qtaguid: tag_stat: stat_update() bond0 not found
[   30.087880] qtaguid: tag_stat: stat_update() wlan0 not found
[   31.300650] usb_bam_alloc_buffer: Already allocated memory
[   31.300932] msm_ep_config() failed for OUT EP

**Comment by aolexiy** [comment]
https://github.com/sonyxperiadev/kernel/pull/1707 - revert to fix default rndis interface descriptor to allow rndis_host linux driver to pick it up

**Comment by aolexiy** [comment]
@dimitar10 ugh, sorry, suzu is still broken, trying to look at that

**Comment by jerpelea** [comment]
This bug will not be fixed
