### ISSUE TITLE
GatekeeperHalDevice status -30 after XZ1 Compact system update

### ISSUE THREAD

**Issue by nadam** [sonyxperiadev/bug_tracker#241]
Apologies if this is the wrong place to seek help, but I couldn't find another place and searching for GatekeeperHalDevice returns 0 results on Google at the moment.

**Platform:** ?
**Device:** XZ1 Compact
**Kernel version:** ?
**Android version:** Propably 9 (Pie)

**Description**
After a system upgrade last night I can't login although I use the correct PIN code. The log says:
2018-11-16 13:36:34.557 714-714/? E/GatekeeperHalDevice: verify
2018-11-16 13:36:34.557 714-714/? E/GatekeeperHalDevice: ret: 0
2018-11-16 13:36:34.557 714-714/? E/GatekeeperHalDevice: resp->status: -30

**Symptoms**
I have the same PIN code for the sim card and the phone. When I reboot the phone I can get passed the first entry which is for the sim card. The second attempt gives "Incorrect PIN".

Interesting detail: After a few random invalid PIN attempts the phone lets me wait 30 seconds after each try. However, when I enter the correct PIN code I don't get this limitation although it says "Incorrect PIN". Instead I can do a few more attempts (with other PIN codes) before it goes back to the 30 second wait.

**How to reproduce**
I'm not sure how anyone can reproduce this. If location matters for updates, I bought the phone in a Sony store in Bangkok and I got the update ota in Sweden.

**Comment by jerpelea** [comment]
is this an AOSP build?

**Comment by nadam** [comment]
Probably not. Sorry. Do you know where I could get help with this kind of issue?

**Comment by jerpelea** [comment]
please contact customer service

**Comment by nadam** [comment]
I've done that already and they have no idea what GatekeeperHalDevice is either. Thanks anyway.

**Comment by jerpelea** [comment]
For any issued related to the official SW you must contact a service point or customer service so that they can investigate the bug and fix it .
Unfortunately we can not help since the software is different
