### ISSUE TITLE
[TAMA] Try to build nitrogen.

### ISSUE THREAD

**Issue by Chiyoda0913** [sonyxperiadev/bug_tracker#242]
Platform: TAMA
Device: Akari H8296
Kernel version: 4.9.103
Android version: P

**Description**
It seems need to edit local_manifests. Or I can't sync repo.

**Symptoms**
remote: Enumerating objects: 5, done.        
remote: Counting objects: 100% (5/5), done.        
remote: Compressing objects: 100% (1/1), done.        
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0        
From https://github.com/nitrogen-project/android_manifest
   2bd614b..da3cec3  p          -> origin/p
project .repo/manifests/
Updating 2bd614b..da3cec3
Fast-forward
 nos.xml | 1 +
 1 file changed, 1 insertion(+)

fatal: remove-project element specifies non-existent project: platform/hardware/qcom/gps

**Comment by oshmoun** [comment]
remove the line that removes the project from local_manifests and it should work
but in any case this does not really belong here, so please close the issue
