### ISSUE TITLE
[tama] slot b is unbootable

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#246]
**Platform:** tama
**Device:** apollo
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
setting slot b as active slot and flashing all the required images does not result in a booting device

**Symptoms**
device does not boot on slot b

**How to reproduce**
assuming you have a working build on slot a
1. populate slot b partitions of the following partitions with their slot a counterparts:
    system, dtbo, boot, vendor, oem, vbmeta, dsp, bluetooth, modem
2. `fastboot --set-active=b`
3. reboot

**Comment by jerpelea** [comment]
if all partitions are cobrectly flashed the device boots from slot B

**Comment by oshmoun** [comment]
can confirm that helps
done with a flashable zip used for Motorola devices
https://drive.google.com/file/d/1oiry9UfP2tf-5A6nQBF7pn2t2eSGKt0F/view
