### ISSUE TITLE
[yoshino] Can't connect to camera

### ISSUE THREAD

**Issue by ploth** [sonyxperiadev/bug_tracker#250]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9
**Android version:** 9

**Description**
Camera doesn't work.

**Symptoms**
After opening the camera app it says "Can't connect to camera"

**How to reproduce**
Open camera app.
`SW_binaries_for_Xperia_Android_9.0_2.3.2_v3_yoshino.img` was used

**Comment by russel5** [comment]
Yep, can confirm it on lilac. Camera works when phone just boot up, after some time not work anymore. If you switch to record video camera stop working immediately.
Don't know if this matter, but I can't see any video files on lilac too

**Comment by jerpelea** [comment]
please create a ticket for every issue

**Comment by jerpelea** [comment]
@ploth is this a user or userdebug build ?

**Comment by ploth** [comment]
It is a `userdebug` build. I had the choice between `en` and `userdebug`.

**Comment by jerpelea** [comment]
reboot device and please post the output of 
adb shell dmesg | grep imx

**Comment by jerpelea** [comment]
i tested maple now and it works fine 
preview - ok
snapshot - ok 
video recording crashing for now

**Comment by ploth** [comment]
Unfortunately this isn't possible since it was a device which is used in production. For now it runs an Android 8.1 with a 4.4 Kernel.

**Comment by jerpelea** [comment]
if you used the video recording please go to settings and clear userdata for camera app 

you can use video recording on the Open Camera app

**Comment by russel5** [comment]
@jerpelea do you test after new source commits?
And camera works for some time, after 5-10-15 minutes camera stop working

**Comment by jerpelea** [comment]
What is the issue ?
I tested suzu, dora, maple, pioneer and apollo with the HEAD and all sleep fine

**Comment by russel5** [comment]
https://github.com/sonyxperiadev/bug_tracker/issues/257

**Comment by jerpelea** [comment]
for camera please sync, build and test the new image with userdata wipe 

Regards
Alin

**Comment by jerpelea** [comment]
can't replicate anymore

**Comment by billchenchina** [comment]
Tested with dora, reproduced.
