### ISSUE TITLE
[yoshino] Disconnects from WLAN

### ISSUE THREAD

**Issue by ploth** [sonyxperiadev/bug_tracker#251]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9
**Android version:** 9

**Description**
The phone disconnects itself from wlan networks. Sometimes it is possible to work for a while (maybe 30 minutes) and then it looses the connection to the wlan. The wlan icon at the top bar disappears. if you enter the wlan settings the network is still there and known to the phone. To reconnect I need to tap the ssid again and it connects to it without asking. I tried different networks and even set a static IP. Revoked permission from any app to manage the wlan state of the phone. Reset the network settings, rebooted and repeated that two times. The error is still there.

**Symptoms**
Wlan symbol disappears at the top bar.

**How to reproduce**
Don't know exactly.

**Comment by russel5** [comment]
May be you are need change internet plan in wlan settings?

**Comment by jerpelea** [comment]
I am using lilac as my device and I can not replicate this issue 
Please check the WLAN signal strength

**Comment by kholk** [comment]
Solved with https://github.com/sonyxperiadev/device-sony-yoshino/pull/113
