### ISSUE TITLE
[TAMA] [CAMERA] Very dark pictures on snapshot

### ISSUE THREAD

**Issue by kholk** [sonyxperiadev/bug_tracker#252]
**Platform:** SoMC Tama
**Device:** ALL
**Kernel version:** 4.9.xxx
**Android version:** 9.0

**Description**
Camera preview is good-ish... but snapshot produces a totally unusable image.

**Symptoms**
There is a brigher spot at the center of the image, but the whole image is very very dark and
in this state the camera is totally unusable. This happens on both front and back cameras
and on all apps, since it's a proprietaries related issue.

**How to reproduce**
Take a picture...... :)

**Comment by sraase** [comment]
We are aware of the issue and working on it. The camera support is very early still.
Sorry for the delayed answer, and for not providing a solution yet.

**Comment by kholk** [comment]
With v4 this issue is basically solved ONLY ON AOSP CAMERA.
External apps, like Open Camera, Camera FV-5, Manual Camera (and I'm mostly sure also all others that I haven't just mentioned) still produce this issue.

I've made a lil research on my own on this topic, but I couldn't really find any hint to give. Sorry.

**Comment by jerpelea** [comment]
@kholk 
v8 is released !
please rebuild and test

**Comment by jerpelea** [comment]
camera exposure improved but it is not yet as it should

**Comment by kholk** [comment]
The camera can now be used with external apps to some extent.

It is still impossible to get the full potentiality out of it because of the very high minimum ISO (ISO485) achievable by the camera.
Overall the pictures are mediocre (before v8 they were poor, so, it's a good step forward).

**Comment by jerpelea** [comment]
please reopen it on Android 10 after you test v3 release
