### ISSUE TITLE
[tama] bluetooth crashes when trying to pair new device

### ISSUE THREAD

**Issue by fl3x1324** [sonyxperiadev/bug_tracker#256]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
Bluetooth crashes when trying to scan for new device.

**Symptoms**
The Bluetooth UI freezes and then crashes.

**How to reproduce**
Try to pair a new device.
[logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/2634905/logcat.txt)
.

**Comment by oshmoun** [comment]
should be fixed with these:
https://github.com/sonyxperiadev/device-sony-sepolicy/pull/428
https://github.com/sonyxperiadev/device-sony-tama/pull/34
https://github.com/sonyxperiadev/device-sony-common/pull/550

Would be great if you could test and confirm!

**Comment by fl3x1324** [comment]
@oshmoun Thanks! Appreciate it. Maybe next week, when I gain some free time. :)

**Comment by MartinX3** [comment]
@fl3x1324
Is this the same problem?
https://github.com/sonyxperiadev/bug_tracker/issues/296

**Comment by jerpelea** [comment]
the bluetooth works fine with HEAD
