### ISSUE TITLE
Are vulnerabilities disclosed in Android Security Bulletins properly fixed?

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [sonyxperiadev/bug_tracker#258]
Sometimes vendors by mistake or deliberately set Security Patch Level to a newer value even if all the vulnerabilities haven't been fixed. This applies most often to vulnerabilities that can't be fixed solely in AOSP code, but require changes in vendor blobs too.

Can I be sure that the Security Patch Level shown in AOSP built according to Sony's instructions never indicates the whole vulnerability set in a given Security Bulletin was fixed even though vulnerabilities in some vendor blobs haven't been fixed?

> Android vendors are expected to set the security patch level accurately. Some are probably making small mistakes or even intentionally being dishonest about the patch level for vendor issues that they haven't patched. However, I doubt that Sony is doing that on purpose so it's likely accurate for the most part. You should check which patch level their stock OS claims to have and make sure what they're publishing matches their official releases.
You need to make sure that they provide both an updated vendor image, presumably identical to the stock OS along with low-level firmware updates for the bootloader, TrustZone, etc. You also need to make sure those are being included in your signed factory images and update packages. See android-prepare-vendor for how to set this all up properly, although other devices may do things differently. For example, the Nexus 5X made it significantly more difficult to update firmware. It used non-standard commands to perform atomic updates for the low-level firmware so updates generated with the firmware would fail with the AOSP update-binary. It was necessary to include the update-binary from the stock OS over-the-air update packages because it statically linked an LG updater library. A standard firmware update library from Qualcomm became open source for Pixels and later devices with A/B updates and may be usable elsewhere, although it may take work to set up for another device if they aren't providing you that in a device repository.
~ strcat

Are vulnerabilities disclosed in Android Security Bulletins fixed in AOSP Pie for Xperia X and other devices supported by Sony Open Devices? According to https://developer.sony.com/develop/open-devices/latest-updates they should have the Security Patches for everything from November 2018 bulletin, because the latest version is from 2018-11-19.

**Comment by MartinX3** [comment]
Please test it with the App
SnoopSnitch

**Comment by gerg5c42g542g2c54g52c** [comment]
@MartinX3 I don't own an Xperia phone to do that. Plus I doubt some app is able to inspect vendor binaries for CVE fixes. If you disagree, please tell me how this app checks this and if it's checking vendor image and firmware.

**Comment by jerpelea** [comment]
@gerg5c42g542g2c54g52c a complete security patch may involve bootloader, firmware or vendor patches.

The bootloader and firmware updates are handled by flashing the device with the latest firmware with our tools while the device receives official updates.
after the official support ends there are updates only for vendor and kernel

**Comment by gerg5c42g542g2c54g52c** [comment]
Does this mean it _does_ involves bootloader, firmware, vendor patches whenever there's anything to be fixed in them or just _may_ involve?

> while the device receives official updates
How long is that? Fe. Xperia X won't get Android 9 and it already got Android 8, does that mean the AOSP for it didn't get any bootloader and firmware patches disclosed after the date the stock OS was updated to Android 8 or does it still get them for X months?

**Comment by MartinX3** [comment]
https://developer.sony.com/develop/open-devices/get-started/supported-devices-and-functionality

**Comment by gerg5c42g542g2c54g52c** [comment]
@MartinX3 I belive that by official updates @jerpelea meant updates of the stock ROM and not updates of Open Devices AOSP ROM, but let's see.

**Comment by jerpelea** [comment]
for a complete security patch you have to 
1. flash the stock firmware using https://developer.sony.com/develop/open-devices/get-started/flash-tool/
2. build and flash the AOSP 

@gerg5c42g542g2c54g52c which device do you have?

**Comment by gerg5c42g542g2c54g52c** [comment]
@jerpelea Xperia X.

>     * After official support ends you can still get security updates for kernel and Android but loader and firmware will be stuck to the latest official release
How long is the official support for the devices in Open Devices program then?

> for a complete security patch you have to
> 
>     1. flash the stock firmware using https://developer.sony.com/develop/open-devices/get-started/flash-tool/
> 
>     2. build and flash the AOSP
Does this (flashing the stock OS before flashing AOSP) have to be done every time I flash an update to my AOSP build to receive complete security patch? If so, why is it this way? It's extremely troublesome for no meaningful reason.

Is the Security Patch Level still being bumped after the official support ends (and therefore complete security patches aren't provided anymore) or is it frozen on the last complete patch?

**Comment by MarijnS95** [comment]
> Does this (flashing the stock OS before flashing AOSP) have to be done every time I flash an update to my AOSP build to receive complete security patch?

You don't need to flash the entire OS, only the _firmware_ as @jerpelea said. This functionality was added to flashtool about a month ago: https://developer.sony.com/posts/flash-tool-updated-with-new-feature/

**Comment by MartinX3** [comment]
Sadly flash tool is a windows only application, while you need linux compiling a custom rom.

It should be platform independent.

**Comment by gerg5c42g542g2c54g52c** [comment]
That's cool, but I still don't know the answers to the rest of the questions, especially about the official support duration for Xperia X and other devices.

**Comment by jerpelea** [comment]
the official support is communicated officially for each product.

**Comment by jerpelea** [comment]
Xperia X does not support A/B updates
