### ISSUE TITLE
[poplar] Battery always 20%

### ISSUE THREAD

**Issue by lATAl** [sonyxperiadev/bug_tracker#259]
**Platform:** yoshino
**Device:** poplar
**Kernel version:** 4.9
**Android version:** 9

**Description**
After flash aosp. Battery always show 20%

**How to reproduce**
On my xz1, after flash aosp and oem then reboot. Battery always 20%

**Comment by jerpelea** [comment]
please attach dmesg  from boot?

**Comment by lATAl** [comment]
[dmesg.txt](https://github.com/sonyxperiadev/bug_tracker/files/2657154/dmesg.txt)
@jerpelea Here is the result of `adb shell dmesg > dmesg.txt`

**Comment by lATAl** [comment]
Here is dmesg after reboot. Battery continue stuck at 20%.
[dmesg2.txt](https://github.com/sonyxperiadev/bug_tracker/files/2657233/dmesg2.txt)

**Comment by lATAl** [comment]
Battery now correct.

A few minutes later, I push Power + Up Vol don't response, plug USB don't see anything. After that, I plug the phone to wall changer then go for a walk.

When I go home. plus Power then power + up vol then power + down vol but my phone is not responding. Plug it to USB and try again several times, the phone vibrated then boot up.

But now my phone sometimes can't wake up after sleep. I tried pressing hard buttons many times in different ways when it came up when it did not respond at all. 

Now I sometimes have to fight to turn it on

**Comment by jerpelea** [comment]
I can not replicate the issue

**Comment by balthild** [comment]
I encountered this bug on my G8342 too, on both Android 8.1 and 9.0. Flashing other system (e.g. LOS, PE) doesn't resolve it, so I think it might be some problem in the vendor or kernel.

There's another person on XDA has met the bug: https://forum.xda-developers.com/xperia-xz1/help/project-treble-gsi-roms-pie-update-t3894484/page2#post78817832

**Comment by balthild** [comment]
Here's the dmesg output.

[dmesg-8.1.txt](https://github.com/sonyxperiadev/bug_tracker/files/2836372/dmesg-8.1.txt)
