### ISSUE TITLE
[kugo] Random reboots to 'Android' logo. Possibily due to Wi-Fi

### ISSUE THREAD

**Issue by bamsbamx** [sonyxperiadev/bug_tracker#26]
**Platform:** Loire
**Device:** Kugo
**Kernel version:** 4.4
**Android version:** Oreo 8.0.0_r15

**Description**
I have built AOSP sources (not modified) from sonyxperiadev using the following guide https://developer.sonymobile.com/open-devices/aosp-build-instructions/how-to-build-aosp-oreo-for-unlocked-xperia-devices/ with commits updated to 6th November

**How to reproduce**
However, the phone reboots from time to time to Android logo (soft-reboot) by itself. It seems it happens under 2 conditions:

1. Have Wi-Fi turned ON (not sure if has to be connected to any network) (WiFI turned OFF -> no reboot)
2. Leave the phone with screen OFF for some time (maybe until entering Wakelock?)
3. Not be plugged in to charger
4. After some time, the device reboots into Android logo and will be stuck there until hard reboot (VolUp + Power for some seconds). After that, the device will boot without any problem

**Maybe related to the problem:** when accessing Wi-FI section in Settings, the app will ANR and close by itself

**Here I leave logcats:** via attached file or via gist (you can see the problem after line 7224, although there are more errrors some lines before that). In the logs, you can see "beggining of main" in line 8212 due to the reboot:

- https://gist.github.com/bamsbamx/010150781a961e71c29f3a83ffbf8c0c (note github truncates the file and you have to click "View full file")
- [logs.txt](https://github.com/sonyxperiadev/bug_tracker/files/1453059/logs.txt)

**Comment by bamsbamx** [comment]
I see this issue may be related: https://github.com/sonyxperiadev/bug_tracker/issues/4

However, the prebuilt dtbs in https://github.com/sonyxperiadev/vendor-sony-kernel/tree/aosp/LA.UM.5.7.r1 were not updated with this fix as those patches were applied one day after uploading prebuilt binaries. I must try building kernel first

**Comment by bamsbamx** [comment]
After applying patches to fix https://github.com/sonyxperiadev/bug_tracker/issues/4 , I can confirm this issue is gone. 

However, the prebuilts in this repo https://github.com/sonyxperiadev/vendor-sony-kernel/tree/aosp/LA.UM.5.7.r1 are not updated yet, and contain the bug

**Comment by jerpelea** [comment]
prebuilts are building and will be updated ASAP
