### ISSUE TITLE
[not bug] stock fw singlesim to dualsim

### ISSUE THREAD

**Issue by Gouster4** [sonyxperiadev/bug_tracker#260]
**Platform:tama
**Device:akari
**Kernel version:4.9
**Android version:9.0

**Description**
Its not a AOSP bug. I know it shouldnt be here, but i didnt found any better place where i can get support. Soory about that.
I have XZ2 DualSim device.
Im using H8266_Customized CE1_1313-3193_52.0.A.3.84_R2B firmware,
but i want to use H8216_Orange MCV FR-ES-PL-SK-RO_1313-8452_52.0.A.3.84_R6B with dualsim support.

As my career is OrangeSK, i want theyr customization to get VOLTE working, but i want still have dualsim option. Suddenly, OrangeSK doesnt sell dualsim, so there isnt any OrangeSK customization for dualsim device.

I want combine those two firmwares to get volte settings from singlesim, and still be able to read both simcars.

Which partitions i need from which firmware?
Thanx, and sorry again for offtopic.

**Comment by jerpelea** [comment]
I am sorry but we do not support cross flashing !
