### ISSUE TITLE
Green Pictures / Black preview - Stock Firmware 52.0.A.3.126

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#261]
**Platform:** tama
**Device:** akari & apollo
**Kernel version:** 4.9 
**Android version:** 9.0
**Firmware version:** 52.0.A.3.126 

Dear @jerpelea 
The 52.0.A.3.126 stock update fixed the bootloader unlock bug but now, the camera takes green pictures on unlocked devices for some users and at my site in messenger apps which has a camera function.

At my site my camera preview became black, even on third party apps, but I can still take pictures, even with third party apps.
(Video preview and taking videos is working, not for third party apps, they can't preview or record videos)

The entire camera worked before and if we downgrade to the november patch it works again.

Is this intended or a bug?

**Comment by pwallin** [comment]
Which SW version was used when you unlocked boot loader? 
I unlocked my phone on 52.0.A.3.126 and camera seems to work.

**Comment by MartinX3** [comment]
Wow, I unlocked it on oreo.

**Comment by phyxar** [comment]
> Which SW version was used when you unlocked boot loader?
> I unlocked my phone on 52.0.A.3.126 and camera seems to work.

are you sure...? i haven't unlock my phone, wait for camera things to work for sure

**Comment by pwallin** [comment]
52.0.A.3.126 has a fix for green camera picture issue on unlocked devices BUT it only works on devices that has been booted up least once with this software before unlocking boot loader. 
I'm afraid it doesn’t help if you unlocked already on Oreo.

**Comment by MartinX3** [comment]
In my opinion, this is disgusting. :)

**Comment by mirh** [comment]
If the "fix" still sticks after unlock, then it's something of *physical* that can be replicated, I would assume?

**Comment by MartinX3** [comment]
@jerpelea did you saw this issue? :)
What's the actual state? :)

**Comment by jerpelea** [comment]
my colleague already answered

**Comment by MartinX3** [comment]
Is there something we can do?

This wasn't communicated in the past by sony, so we had no chance to wait with unlocking.

**Comment by MartinX3** [comment]
@jerpelea

**Comment by jerpelea** [comment]
@mirh

**Comment by MartinX3** [comment]
@mirh

**Comment by mirh** [comment]
wat

**Comment by mirh** [comment]
And how would I know?

**Comment by MartinX3** [comment]
@jerpela did you mention the wrong user?

**Comment by MartinX3** [comment]
@jerpelea did you mention the wrong user?

**Comment by x-jokay** [comment]
I can confirm this for `Stock 52.0.A.3.126` on a Xperia XZ2 Compact.

Needed to downgrade to Oreo previously to be able to switch on OEM unlocking and now the camera preview isn't working anymore.

**Comment by MartinX3** [comment]
@jerpelea 
So we need to create a solution on our own to get our camera preiew back on .126? :(

**Comment by jerpelea** [comment]
@pwallin please comment

**Comment by MartinX3** [comment]
@pwallin ?
