### ISSUE TITLE
[tone][kagura] High battery drain with Android 9 

### ISSUE THREAD

**Issue by djselbeck** [sonyxperiadev/bug_tracker#267]
**Platform:** Tone
**Device:** Kagura
**Kernel version:**  

`Linux localhost 4.9.142-g76e5ce214272 #1 SMP PREEMPT Sun Dec 16 13:27:37 CET 2018 aarch64`

**Android version:** [Sony/aosp_f8331/kagura:9/PQ1A.181205.006/hendrik12161317:userdebug/dev-keys]

**Description**
After updating to Android 9 the battery usage of the kagura device seems to have increased significantly. My device lost ~40% over my last night time (6-7hours).

**Symptoms**
Fast drained battery

**How to reproduce**
Use Android 9 on kagura device.

I attach a dump of my batterystats and power usage statistics from dumpsys

[dumpsys_batterystats_xz_9.txt](https://github.com/sonyxperiadev/bug_tracker/files/2684966/dumpsys_batterystats_xz_9.txt)
[dumpsys_battery_xz_9.txt](https://github.com/sonyxperiadev/bug_tracker/files/2684967/dumpsys_battery_xz_9.txt)
[dumpsys_power_xz_9.txt](https://github.com/sonyxperiadev/bug_tracker/files/2684968/dumpsys_power_xz_9.txt)

Edit:

I use no Google Apps but have microg installed.

**Comment by Gray47Maxx** [comment]
Can confirm this on loire as well. Not that significant, but it really is here. I'll attach dumps this evening.

**Comment by djselbeck** [comment]
I've downgraded my kagura device to Android 8.1 and the battery life is now really great again (lost 3% over my last night time, 6hours roughly).

**Comment by djselbeck** [comment]
Not possible for me at the moment. I only have two devices (lilac and kagura) and I need kagura as lilac is just not usable at all.

**Comment by jerpelea** [comment]
sample files 
http://jell.yfish.us/

**Comment by jerpelea** [comment]
I tested the 3 Mbps and 10 Mbps and both work fine
