### ISSUE TITLE
[yoshino][lilac] Device freezes upon activation of ExtendedSettings

### ISSUE THREAD

**Issue by djselbeck** [sonyxperiadev/bug_tracker#270]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.142-g044e4daee638
**Android version:** Sony/aosp_g8441/lilac:9/PQ1A.181205.006/hendrik12161811:userdebug/dev-keys

**Description**
The device freezes some time after entering the PIN of the SIM and the PIN of the device (device locked with PIN). The last entry always is 

> 
> 12-18 10:17:26.648  1104  1138 W libprocessgroup: kill(-2481, 9) failed: No such process
> 12-18 10:17:26.660  1104  1137 I ActivityManager: Start proc 3168:sonyxperiadev.extendedsettings/1000 for broadcast sonyxperiadev.extendedsettings/.BootBroadcastReceiver
> 12-18 10:17:26.665  3168  3168 I Zygote  : seccomp disabled by setenforce 0
> 12-18 10:17:26.678   614   614 I Zygote  : Process 2481 exited due to signal (9)
> 12-18 10:17:26.694  1104  1138 W libprocessgroup: kill(-2481, 9) failed: No such process
> 12-18 10:17:26.694  1104  1138 I libprocessgroup: Successfully killed process cgroup uid 1000 pid 2481 in 49ms

If i power cycle the device a bit after entering both PINs on and off the device will boot fine.

**Symptoms**
Freezed device / Reboot occurs

**How to reproduce**
Boot device with PIN lock enabled. (At first I thought it happens only with Display calibrations set, but it will also happen now after I reset the data of package ExtendedSettings). But setting a display profile will help to reproduce.

**Comment by djselbeck** [comment]
If I am able to boot the device I can see this in the log file:

> 12-18 10:29:30.123  1124  1147 I ActivityManager: Start proc 4291:sonyxperiadev.extendedsettings/u10s1000 for broadcast sonyxperiadev.extendedsettings/.BootBroadcastReceiver
12-18 10:29:30.130  3983  4027 D InstalledAppProviderSer: insertAppIntoDb com.android.musicfx
12-18 10:29:30.132  3833  3833 D BluetoothGatt: discoverServices() - device: CA:A8:7F:BA:BF:09
12-18 10:29:30.134  2964  3015 E bt_btif_gattc: btif_gattc_upstreams_evt: Unhandled event (7)!
12-18 10:29:30.135  2964  3015 E bt_btif_gattc: btif_gattc_upstreams_evt: Unhandled event (7)!
12-18 10:29:30.138   621   621 I Zygote  : Process 3685 exited due to signal (9)
12-18 10:29:30.139  2964  3015 D bt_bta_gattc: bta_gattc_get_gatt_db
12-18 10:29:30.140  3833  3847 D BluetoothGatt: onSearchComplete() = Device=CA:A8:7F:BA:BF:09 Status=0
12-18 10:29:30.142  3833  3833 D BluetoothGatt: configureMTU() - device: CA:A8:7F:BA:BF:09 mtu: 512
12-18 10:29:30.155  3983  4027 D InstalledAppProviderSer: insertAppIntoDb com.android.nfc
12-18 10:29:30.158  1124  1148 W libprocessgroup: kill(-3685, 9) failed: No such process
12-18 10:29:30.158  1124  1148 I libprocessgroup: Successfully killed process cgroup uid 10072 pid 3685 in 49ms
12-18 10:29:30.165  4291  4291 W System.err: java.io.FileNotFoundException: /sys/devices/mdss_dsi_panel/pcc_profile (Permission denied)
12-18 10:29:30.166  4291  4291 W System.err: 	at java.io.FileOutputStream.open0(Native Method)
12-18 10:29:30.166  4291  4291 W System.err: 	at java.io.FileOutputStream.open(FileOutputStream.java:308)
12-18 10:29:30.166  4291  4291 W System.err: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
12-18 10:29:30.167  4291  4291 W System.err: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:119)
12-18 10:29:30.167  4291  4291 W System.err: 	at java.io.FileWriter.<init>(FileWriter.java:63)
12-18 10:29:30.167  4291  4291 W System.err: 	at sonyxperiadev.extendedsettings.ExtendedSettingsFragment.performDisplayCalibration(ExtendedSettingsFragment.java:507)
12-18 10:29:30.168  4291  4291 W System.err: 	at sonyxperiadev.extendedsettings.BootBroadcastReceiver.onReceive(BootBroadcastReceiver.java:52)
12-18 10:29:30.168  4291  4291 W System.err: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3417)
12-18 10:29:30.168  4291  4291 W System.err: 	at android.app.ActivityThread.access$1200(ActivityThread.java:200)
12-18 10:29:30.168  4291  4291 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
12-18 10:29:30.169  4291  4291 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-18 10:29:30.169  4291  4291 W System.err: 	at android.os.Looper.loop(Looper.java:193)
12-18 10:29:30.169  4291  4291 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
12-18 10:29:30.170  4291  4291 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
12-18 10:29:30.170  4291  4291 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-18 10:29:30.171  4291  4291 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ix5** [comment]
`System.err: java.io.FileNotFoundException: /sys/devices/mdss_dsi_panel/pcc_profile (Permission denied)`
Seems it can't read the calibration file for the panel. Can you check the permissions on that file?

**Comment by djselbeck** [comment]
This was caused by the ExtendedSettings app also running in work mode. It is unrelated to the crash

**Comment by MarijnS95** [comment]
Could you share pstore logs after a crash? When the device reboots (without manually rebooting, or cold-(re)starting), simply share the files from `/sys/fs/pstore`. These should contain both (truncated) dmesg just before the crash, and a very mangled but still somewhat readable `logcat`. This might help point in the direction of the cause.

**Comment by stefanhh0** [comment]
Here are the files from `/sys/fs/pstore`
[pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2823735/pstore.tar.gz)

**Comment by jerpelea** [comment]
please do a clean build 
I can not replicate the reported bug on any of my devices

**Comment by djselbeck** [comment]
I can still replicate this on lilac with a clean build. (Always doing a clean build)

**Comment by jerpelea** [comment]
I have a device pin and I can enter Externded Settings and pick a display calibration profile without a crash

**Comment by jerpelea** [comment]
I am sorry but I can not reproduce the issue

**Comment by jerpelea** [comment]
please sync in a clean folder and try to build without any modification

**Comment by ix5** [comment]
I've had this happen with a clean sync as well on kagura on 2019-02-03.
Haven't been able to reproduce it yet though.

```
<2>[ 4598.574300] Bad mode in Error handler detected on CPU3, code 0xbe000000 -- SError
<0>[ 4598.574439] Internal error: Oops - bad mode: 0 [#1] PREEMPT SMP
<6>[ 4598.574514] Modules linked in:
<6>[ 4598.574633] CPU: 3 PID: 913 Comm: Binder:576_3 Tainted: G        W       4.9.152-g0ceba719571b-dirty #6
<6>[ 4598.574756] Hardware name: SoMC Kagura-ROW (DT)
<6>[ 4598.574861] task: ffffffc09ca35e80 task.stack: ffffffc09fbb0000
<6>[ 4598.574939] PC is at 0x74b6671d84
<6>[ 4598.574997] LR is at 0x74b662a268
<6>[ 4598.575074] pc : [<00000074b6671d84>] lr : [<00000074b662a268>] pstate: a0000000
<6>[ 4598.575130] sp : 0000007433501220
<6>[ 4598.575232] x29: 0000007433501310 x28: 0000000000000000 
<6>[ 4598.575411] x27: 00000074b689d408 x26: 0000000000000000 
<6>[ 4598.575648] x25: 0000007433501588 x24: 0000000000000048 
<6>[ 4598.575804] x23: 00000000fffffff7 x22: 00000000c0306201 
<6>[ 4598.576017] x21: 0000007435c7a7d0 
<3>[ 4598.576019] pp_pcc_cache_params_v1_7: failed to copy v17 pcc
<6>[ 4598.576055] somc_panel_pcc_setup: (401):(ru[0], ru[1])=(0, 8), (rv[0], rv[1])=(0, 8)
<6>[ 4598.576223] somc_panel_pcc_setup: (410):ct=0 area=82 ud=38 vd=38 r=0x00008000 g=0x00007C90 b=0x00006EDB
<6>[ 4598.576322] x20: 0000007435c7a6c0 
x19: 0000007433501588 x18: 00000074335004c0 
<6>[ 4598.576588] x17: 00000074b662a1d4 x16: 00000074b82a9cc8 
<6>[ 4598.576750] x15: 00000a6b70954443 x14: 001406f36e26fd00 
<6>[ 4598.576952] x13: 000000005c56eeee x12: 0000000000000018 
<6>[ 4598.577112] x11: 0000000000000000 x10: 0000000000000001 
<6>[ 4598.577316] x9 : 00000074335012d8 x8 : 000000000000001d 
<6>[ 4598.577475] x7 : 0000000000411ca0 x6 : 0000000000000000 
<6>[ 4598.577636] x5 : 0000000000000000 x4 : 0000000000000000 
<6>[ 4598.577797] x3 : 0000000000000000 x2 : 0000007433501328 
<6>[ 4598.577956] x1 : 00000000c0306201 x0 : 0000000000000000 
<0>[ 4598.578161] Process Binder:576_3 (pid: 913, stack limit = 0xffffffc09fbb0000)
<4>[ 4598.578267] ---[ end trace fe5a66107ae8e127 ]---
```

**Comment by jerpelea** [comment]
please share the output of
fastboot getvar all

**Comment by ix5** [comment]
```
(bootloader) version:0.5
(bootloader) max-download-size:	0x10000000
(bootloader) partition-type:cache:ext4
(bootloader) partition-size:cache:	 0x10000000
(bootloader) partition-type:userdata:ext4
(bootloader) partition-size:userdata:	 0x58e000000
(bootloader) partition-type:system:ext4
(bootloader) partition-size:system:	 0x171600000
(bootloader) secure:no
(bootloader) version-baseband:1302-9157_41.3.A.2.192
(bootloader) version-bootloader:1299-4832 S1_Boot_MSM8996_LA2.0_O_204
(bootloader) serialno:XXX
(bootloader) product:F8331
```

**Comment by jerpelea** [comment]
@ix5 

To have the same firmware base I would also recommend that you first flash 47.2.A.2.33 on your device using flashtool https://developer.sony.com/develop/open-devices/get-started/flash-tool/

**Comment by jerpelea** [comment]
@ix5 please check after you flashed the 47.2 firmware

**Comment by djselbeck** [comment]
Upgrading to 47.2.A.2.33 firmware did not help. Unfortunately I have no idea how to debug the problem. /sys/fs/pstore contains no dmesg output after the crash occurs.

**Comment by ix5** [comment]
> @ix5
> 
> To have the same firmware base I would also recommend that you first flash 47.2.A.2.33 on your device using flashtool https://developer.sony.com/develop/open-devices/get-started/flash-tool/

Kagura's last firmware was `41.3.A.2.192` afaik. It's EOL in terms of official updates.

**Comment by stefanhh0** [comment]
I can't upgrade to anything else the phone persists to stay on:
```
(bootloader) version-baseband:1307-7511_47.1.A.16.20
(bootloader) version-bootloader:1306-5035_X_Boot_MSM8998_LA2.0_P_104
```
Upgrading to any different Version seems to succeed but after a reboot it still says:
`1307-7511_47.1.A.16.20`

Customization:
`CDF: 1311-0104 R22B`

I've tried all three available firmware updates in emma but none succeeded.

See also the screenshots. Anyone with an idea? Next attempt would be to flash the full Software Update instead of Firmware Update... Is it possible to change the customization, so flashing the latest Customized_UK although when the phone is on Customzed_NOBA?

![availableservices](https://user-images.githubusercontent.com/28729344/52358054-94d3ff00-2a37-11e9-9b30-b8632ecb2602.png)
![successfullflash](https://user-images.githubusercontent.com/28729344/52358066-99001c80-2a37-11e9-92ab-327a6d68eedb.png)

**Comment by jerpelea** [comment]
I am sorry but you confuse me
this bug is reported on lilac not kagura!

please flash the full firmware 47.2.a.2.33 then boot 1 time the device with a sim and the Sony SW

**Comment by stefanhh0** [comment]
Just flashed the the full Software Update instead of the Firmware Update.

Now I am on the right Firmware-Version:
```
(bootloader) version-baseband:1307-7511_47.2.A.2.33
(bootloader) version-bootloader:1306-5035_X_Boot_MSM8998_LA2.0_P_104
```

Next I'll reflash aosp and verify that the screen calibration error is gone.

**Comment by stefanhh0** [comment]
I can still reproduce. The freeze occured when switching forth and back between D50 and D65 and worked a little with the phone (klicking through the menus). Besides the fact that twrp was flashed as recovery no other modifications have been in place (no additional apps, no magisk and a vanilla userdata.img)
**Kernel version:** 4.9.154-gc9e8e6f780ac-dirty
**Android version:**  android-9.0.0_r31

```
(bootloader) hw-revision:20001
(bootloader) unlocked:yes
(bootloader) off-mode-charge:0
(bootloader) charger-screen-enabled:0
(bootloader) battery-soc-ok:yes
(bootloader) battery-voltage:4257
(bootloader) version-baseband:1307-7511_47.2.A.2.33
(bootloader) version-bootloader:1306-5035_X_Boot_MSM8998_LA2.0_P_104
(bootloader) erase-block-size: 0x1000
(bootloader) logical-block-size: 0x1000
(bootloader) variant:MSM UFS
```

[console-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2837677/console-ramoops-0.txt)
[dmesg-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2837678/dmesg-ramoops-0.txt)
[pmsg-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2837679/pmsg-ramoops-0.txt)

**Comment by stefanhh0** [comment]
@jerpelea could you reproduce it? I think there is still something wrong with those calibration settings causing freeze -> kernel panic and reboot. Would you mind reopening this bug?
[dmesg-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2837678/dmesg-ramoops-0.txt) contains the crash.

@djselbeck did you double-check that you are on the right firmware version after flashing? I had to do do it like Alin mentioned in: https://github.com/sonyxperiadev/bug_tracker/issues/270#issuecomment-461110712.

**Comment by stefanhh0** [comment]
With a clean build from today and kernel 4.9.154-ge17b3925fe2a-dirty I can't reproduce the crash anymore.

**Comment by stefanhh0** [comment]
It re-ocurred phone setting was on D65:
**Kernel version:** 4.9.154-ge17b3925fe2a-dirty
 **Version-baseband:** 1307-7511_47.2.A.2.33

This time I ran adb logcat
Log when the crash occured: 
[adb_logcat-1.txt](https://github.com/sonyxperiadev/bug_tracker/files/2844257/adb_logcat-1.txt)
Log of the reboot:
[adb_logcat-2.txt](https://github.com/sonyxperiadev/bug_tracker/files/2844258/adb_logcat-2.txt)
pstore content after the crash and reboot:
[adb_logcat-2.txt](https://github.com/sonyxperiadev/bug_tracker/files/2844260/adb_logcat-2.txt)
