### ISSUE TITLE
[yoshino][lilac] SELinux related build failure

### ISSUE THREAD

**Issue by djselbeck** [sonyxperiadev/bug_tracker#271]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 044e4daee638532b8c532008a6f581f943229f59 (aosp/LE.UM.2.3.2.r1.4)
**Android version:** android-9.0.0_r21

**Description**
AOSP fails to build for the lilac device (succeeds for kagura)

Build log snippet:

> [ 26% 27377/104451] build out/target/product/lilac/obj/ETC/sepolicy.recovery_intermediates/sepolicy
out/host/linux-x86/bin/checkpolicy:  loading policy configuration from out/target/product/lilac/obj/ETC/sepolicy.recovery_intermediates/sepolicy.recovery.conf
out/host/linux-x86/bin/checkpolicy:  policy configuration loaded
out/host/linux-x86/bin/checkpolicy:  writing binary representation (version 30) to out/target/product/lilac/obj/ETC/sepolicy.recovery_intermediates/sepolicy.tmp
[ 26% 27387/104451] build out/target/product/lilac/obj/ETC/sepolicy_neverallows_intermediates/sepolicy_neverallows
FAILED: out/target/product/lilac/obj/ETC/sepolicy_neverallows_intermediates/sepolicy_neverallows 
/bin/bash -c "(rm -f out/target/product/lilac/obj/ETC/sepolicy_neverallows_intermediates/sepolicy_neverallows ) && (ASAN_OPTIONS=detect_leaks=0 out/host/linux-x86/bin/checkpolicy -M -c 		30 -o out/target/product/lilac/obj/ETC/sepolicy_neverallows_intermediates/sepolicy_neverallows out/target/product/lilac/obj/ETC/sepolicy_neverallows_intermediates/policy.conf )"
libsepol.report_failure: neverallow on line 638 of system/sepolicy/public/domain.te (or line 10516 of policy.conf) violated by allow wcnss_service per_mgr_service:service_manager { find };
libsepol.report_failure: neverallow on line 638 of system/sepolicy/public/domain.te (or line 10516 of policy.conf) violated by allow rild per_mgr_service:service_manager { find };
libsepol.check_assertions: 2 neverallow failures occurred
Error while expanding policy
out/host/linux-x86/bin/checkpolicy:  loading policy configuration from out/target/product/lilac/obj/ETC/sepolicy_neverallows_intermediates/policy.conf
[ 26% 27418/104451] //external/skia:libskia clang++ src/core/SkBlurImageFilter.cpp
ninja: build stopped: subcommand failed.
12:38:10 ninja failed with: exit status 1

**Comment by MarijnS95** [comment]
This is expected. https://github.com/sonyxperiadev/device-sony-sepolicy/pull/423 was merged without disabling full treble (which is automatically enabled when `PRODUCT_SHIPPING_API_LEVEL` is set).

For now, you can add `PRODUCT_FULL_TREBLE_OVERRIDE := false` to your custom config or to the product/board configuration.

**Comment by jerpelea** [comment]
the patch has been reverted for now until we fix it
