### ISSUE TITLE
Discovery: reboot on changing "Call volume"

### ISSUE THREAD

**Issue by sraase** [sonyxperiadev/bug_tracker#272]
**Platform:** Nile
**Device:** Discovery
**Kernel version:** 4.9.142-g3929bf106487
**Android version:** 9

**Description**
When trying to change the "Call volume" in Settings/Sound, the phone reboots.

**Symptoms**
Phone reboots.

**How to reproduce**
Go to Settings/Sound, change Call volume slider.

**Comment by kholk** [comment]
Solved in https://github.com/sonyxperiadev/kernel/pull/1867
