### ISSUE TITLE
Discovery: copying files using MTP or PTP reboots phone

### ISSUE THREAD

**Issue by sraase** [sonyxperiadev/bug_tracker#273]
**Platform:** Nile
**Device:** Discovery
**Kernel version:** 4.9.142-g3929bf106487
**Android version:** 9

**Description**
After connecting the phone to a PC (Linux) and changing the USB Preferences to "File Transfer" or "PTP", trying to copy a file (or JPG) to the device reboots the phone.

Logcat contains a single line before the crash:
12-18 13:54:23.637  2119  2634 D MtpServer: path: /storage/emulated/0/fastboot parent: 0 storageID: 00010001

**Symptoms**
Phone reboots.

**How to reproduce**
Connect phone to PC, select "File Transfer" or "PTP". Copy a file to the phone.

**Comment by ix5** [comment]
Iirc this used to happen on tone as well, but only on Windows. Stopped happening maybe a month or so ago.

Maybe look out for `configfs` errors?

This is what a successful mtp enablement looks like on kagura after having a device connected via adb and switching to mtp:
```
SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.android.settings#0
commit_sys_config_file: [settings-1-0,19]
CPU0    : update max cpu_capacity 1024
sysui_action: [1276,]
sysui_multi_action: [757,1276,758,4]
UsbDeviceManager: Setting USB config to mtp,adb
init    : processing action (sys.usb.config=none && sys.usb.configfs=1) from (/init.usb.configfs.rc:1)
dwc3 6a00000.dwc3: failed to stop controller
adbd    : aio: got error event on read total bufs 1: Cannot send after transport endpoint shutdown
adbd    : aio: got error event on write total bufs 1: Cannot send after transport endpoint shutdown
adbd    : remote usb: 1 - write terminated: Cannot send after transport endpoint shutdown
init    : Sending signal 9 to service 'adbd' (pid 643) process group...
libprocessgroup: Successfully killed process cgroup uid 0 pid 643 in 35ms
init    : Service 'adbd' (pid 643) received signal 9
init    : Untracked pid 9433 received signal 9
init    : processing action (init.svc.adbd=stopped) from (/init.usb.configfs.rc:14)
init    : processing action (sys.usb.config=mtp,adb && sys.usb.configfs=1) from (/init.usb.configfs.rc:32)
init    : starting service 'adbd'...
init    : processing action (sys.usb.config=mtp,adb && sys.usb.configfs=1) from (/vendor/etc/init/init.usb.rc:95)
init    : Created socket '/dev/socket/adbd', mode 660, user 1000, group 1000
        : read descriptors
        : read strings
init    : processing action (sys.usb.config=mtp,adb && sys.usb.configfs=1 && sys.usb.ffs.ready=1) from (/init.usb.configfs.rc:35)
        : mtp_open
android_work: sent uevent USB_STATE=DISCONNECTED
android_work: sent uevent USB_STATE=CONNECTED
android_work: sent uevent USB_STATE=DISCONNECTED
android_work: sent uevent USB_STATE=CONNECTED
configfs-gadget gadget: high-speed config #1: b
android_work: sent uevent USB_STATE=CONFIGURED
```

**Comment by oshmoun** [comment]
can't replicate this issue on pioneer, no matter how much data I copy, be it many small files or large single files.
The build I'm testing on includes the latest kernel fixes
HEAD is at https://github.com/sonyxperiadev/kernel/commit/370bbbcf453f823136c222183376775d0417f854
Can you please try again to check if the issue persists on your discovery?

**Comment by sraase** [comment]
I can't reproduce that problem. It used to crash instantly (independent of file size).
So I assume the problem has been fixed in the last month.

**Comment by jerpelea** [comment]
Thanks for confirming
