### ISSUE TITLE
[loire] Camera lacks of full Camera 2 API support

### ISSUE THREAD

**Issue by Gray47Maxx** [sonyxperiadev/bug_tracker#275]
**Platform:** loire
**Device:** suzu 
**Kernel version:** 4.9
**Android version:** 9.0

**Problem:** 
The camera is not supporting full C2API, which leads to problems with using third-party cameras like Google Camera. Binaries: v3 and possibly v4.

The bug is not presented with kernel 4.4 and latest blobs for it, that's why I thought this _is_ a bug. 

**How to reproduce:**
Try to probe it using something like Camera 2 Probe app.

![Screenshot by @lubik1](https://drive.google.com/file/d/1sN2VTgZexufquUOR1PWa-BPy3hJcOztH/view?usp=drivesdk) 

[Screenshot by @lubik1](https://drive.google.com/file/d/1sN2VTgZexufquUOR1PWa-BPy3hJcOztH/view?usp=drivesdk)

**Comment by RobbieBnt** [comment]
Also confirming this issue on loire. Guess it's true for all platforms?

**Comment by Gray47Maxx** [comment]
Maybe. Can someone check, please?

**Comment by bartcubbins** [comment]
Only on loire

**Comment by Gray47Maxx** [comment]
Hmm... Can this be fixed, @jerpelea?

**Comment by jerpelea** [comment]
I checked the kugo device with both android 8.1 and 9.0 
The device has the same limited camera for the main camera

**Comment by jerpelea** [comment]
initStaticMetadata: 8785: SRA LIMITED CHECK: no per-frame 0, yuv 0, mono 0, supportBurst 0
**supportBurst 0** has to be supported for FULL API2

**Comment by jerpelea** [comment]
workaround found 
it will be released in v5

**Comment by Gray47Maxx** [comment]
@jerpelea and btw a quick question - can we improve the ISO on platforms? Sometimes 1200 is kinda not enough...

@robbiebnt told me something about noices and stuff, but I guess it can be fixed by proper software. Or we need something like camera mitigation for it as well?

**Comment by jerpelea** [comment]
@Gray47Maxx this is all that can be done witout increasing noise
