### ISSUE TITLE
[Suzu] No audio during call

### ISSUE THREAD

**Issue by XperiaDeveloper** [sonyxperiadev/bug_tracker#277]
**Platform:** Loire
**Device:** Suzu
**Kernel version:** 4.4
**Android version:** Android 8.1.0-r52
**Firmware version:** v16 [Software binaries for AOSP Oreo (Android 8.1) – Kernel 4.4 – Loire](https://developer.sony.com/file/download/software-binaries-for-aosp-oreo-android-8-1-kernel-4-4-loire/)
**Build type:** Debug and user build

**Description**
I have build and flashed Android 8.1.0-r52 on XperiaX device following the instruction provided in [here](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-nougat-8-1-oreo-4-4/).
When I place a voice call from or to a XperiaX device, the call is established successfully. I can hear the Ring tone and the typing sound but no voice is going throw.

I got the same results also using a headphone and a Bluetooth-headset.

Attached you can find a log file.
[sony_log.log](https://github.com/sonyxperiadev/bug_tracker/files/2694874/sony_log.log)

**Related Issues**
This may be related to a previous reported issue [[maple]](https://github.com/sonyxperiadev/bug_tracker/issues/25)

**How to reproduce**
Place a voice call
Try to make a conversation

PS: sorry for the repost

**Comment by XperiaDeveloper** [comment]
It works after reboot tho

**Comment by jerpelea** [comment]
the issue is caused by a race in the adspcrpcd service startup

**Comment by jerpelea** [comment]
please revert commit 4eb90a1615ddc2dddac91bbf828b1e9b6986c562 and try again

**Comment by XperiaDeveloper** [comment]
Hi Alin,
thanx for quick response. After reverting the patches:

1.  We have voice on calls. 
2.  Reverting doesn't fix the issue #265.
3. We mentioned that first SIM PIN is not accepted. Second try is accepted. Should we write another ticket for this?

**Comment by jerpelea** [comment]
it is important to check on the first boot after userdata is wiped

**Comment by XperiaDeveloper** [comment]
For testing we flash always the userdata.img (as well as boot, recovery, system, cache, and oem). So the userdata should be in a clear state.

**Comment by jerpelea** [comment]
please open a PR for the patch revert

**Comment by jerpelea** [comment]
the race condition appears to be fixed
