### ISSUE TITLE
[Tama] camera preview freezes

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#278]
**Platform:** tama
**Device:** apollo
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
Occasionally, camera preview will just freeze. Sometimes it survives the freeze and preview continues working after a while, and sometimes just crashes.

**How to reproduce**
Open any camera app, start taking snapshots, changing focus/exposure etc..
The preview is bound to freeze and maybe crash soon after.

**Comment by oshmoun** [comment]
@sraase this is probably a known issue like #252 but still worth having it mentioned here

**Comment by jerpelea** [comment]
can you still replicate it on v4?

**Comment by oshmoun** [comment]
yes this still happens on v4, the state has not changed between v3 and v4
random freezes and crashes still occur

**Comment by sraase** [comment]
@oshmoun I did a small stress test on v5 and did not see the behaviour (with the AOSP camera). Can you reproduce the issue still?

**Comment by kholk** [comment]
I can replicate on Akatsuki. The preview randomly freezes, and that's also on the AOSP camera app.

**Comment by alviteri** [comment]
same on akari with aosp camera

**Comment by sraase** [comment]
> opened AOSP camera and switched a couple times between snapshot and video modes.

Thanks for that information. I can reproduce that now.

**Comment by kholk** [comment]
As a side note, it sometimes happens also when you switch between back and front camera.

**Comment by jerpelea** [comment]
fixed in v6

**Comment by oshmoun** [comment]
While a lot better in v6, it is not completey fixed
switching to frontcam and back still causes a freeze followed by a camera disconnect sometimes
also, the backcam sometimes just suddenly crashes: https://del.dog/icecoziviq
