### ISSUE TITLE
[Website] Still not list the XZ2, XZ2C and XZ3

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#280]
https://developer.sony.com/develop/open-devices/get-started/supported-devices-and-functionality/supported-devices-maintained/
https://developer.sony.com/develop/open-devices/get-started/supported-devices-and-functionality/

Maybe somewhere else, too. :)

**Comment by bartcubbins** [comment]
Xz2p is not supported by SODP:(

**Comment by MartinX3** [comment]
Woops, sorry, my mistake :)

And in my opinion the missing support is sad for everyone who bought the XZ2P because of the wonderfull Sony AOSP community. :)

**Comment by jerpelea** [comment]
unfortunately XZ2P can not be supported

**Comment by MartinX3** [comment]
Yes, because of its special camera hardware. :)

But the XZ2, XZ2C and XZ3 are still missing there.

**Comment by nospower** [comment]
https://github.com/sonyxperiadev/device-sony-akari
Is this not what you are looking for?

**Comment by MartinX3** [comment]
Nice. Fixed.
But sadly still missing here
https://developer.sony.com/develop/open-devices/get-started/supported-devices-and-functionality/current-platform-functionality-maintained/

**Comment by Gouster4** [comment]
I think XZ2C can be partialy supported, with use of stock cam blobs. (Aosp with cosed-source stock camera). Sure, its not optimal way, buy at least something.

**Comment by jerpelea** [comment]
The Xperia XZ2 Compact is supported by the project including camera
