### ISSUE TITLE
[lilac]Camera still not work

### ISSUE THREAD

**Issue by russel5** [sonyxperiadev/bug_tracker#281]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9
**Android version:** 9
**OEM:** v4

**Description**
After some time can't connect to camera

**Symptoms**
After some time camera stop working and write "Failure can't connect to camera"
Logcat
`12-22 14:02:55.727 E/CAM_FatalErrorHandler(4811): Handling Camera Access Failure:`

**How to reproduce**
Give your device some time and try to open camera

**Comment by russel5** [comment]
Logcat with errors are here
https://drive.google.com/open?id=1MCGdq-6NJrmSrQtcmEaWITdAjHbCL88S

**Comment by jerpelea** [comment]
pleaser boot the device and test camera again



On Sat, Dec 22, 2018 at 10:31 AM +0100, "russel5" <notifications@github.com<mailto:notifications@github.com>> wrote:


Logcat with errors are here
https://drive.google.com/open?id=1MCGdq-6NJrmSrQtcmEaWITdAjHbCL88S

**Comment by russel5** [comment]
I'm booted several times

**Comment by jerpelea** [comment]
did you wipe userdata?
what app do you use ?

**Comment by VictorRyabov** [comment]
[2018-12-23-09-57-02.txt](https://github.com/sonyxperiadev/bug_tracker/files/2705791/2018-12-23-09-57-02.txt)
Error on clean install. (all was wiped)

**Comment by sjllls** [comment]
Camera works fine on poplar, built on 12.24.2018, with OEM v4, wiped userdata.

**Comment by sjllls** [comment]
> The camera works fine on a quick test !
> 
> Please provide more details how to replicate the bug ?
> What app are you using ?

Hi, Alin,
I upload the adb log on XZ1's build on 2019.1.4
After booting, the camera is fine. But once you screen-off and wake the phone. The camera must disconnect. I just test aosp stock camera on this build.
But camera work fine with SonyAospteam's build on  2018.12.24. Both stock camera and Gcam.

@jerpelea  
[xz1.log](https://github.com/sonyxperiadev/bug_tracker/files/2737524/xz1.log)

**Comment by djselbeck** [comment]
Can confirm this for Lilac as well for OEM v5 and build from 23.01.19

**Comment by djselbeck** [comment]
Seems to work after each reboot until the device enters deep sleep

**Comment by jerpelea** [comment]
this is good info 
thanks for testing it
