### ISSUE TITLE
[Tama] sensor for pickup detection does not work

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#282]
**Platform:** tama
**Device:** apollo, akatsuki
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
sensors hal reports not being able to register pickup detection

**Symptoms**
no support for pickup detection, which can be supported in aosp

**How to reproduce**
reboot and check logcat to see the errors from sensors hal

**Comment by oshmoun** [comment]
the issue seems to be our sensors hal
copying the one from stock leads to the sensor being reported as activated

**Comment by oshmoun** [comment]
the config has absolutely nothing to do with this.
the sensors hal does not try to init the sensor because it does not register a sensor of the type `android.sensor.pick_up_gesture`

**Comment by jerpelea** [comment]
ok
I missread! i will investigate it for v5 release

**Comment by Chiyoda0913** [comment]
Still don't have the option in v5

**Comment by jerpelea** [comment]
fixed in v6

**Comment by Chiyoda0913** [comment]
Thanks for that

Alin Jerpelea <notifications@github.com> 于 2019年2月22日周五 下午5:13写道：
