### ISSUE TITLE
[Yoshino] All yoshino platform devices will freeze on Pie.

### ISSUE THREAD

**Issue by sjllls** [sonyxperiadev/bug_tracker#286]
**Platform:** Yoshino
**Device:** All yoshino platform devices
**Kernel version:** 4.9
**Android version:** 9.0
**Software Binaries version:** V4

**Description**
All yoshino platform devices will freeze on Pie after closing the screen.

**How to reproduce**
Build Rom with newest source codes and run it.

**Comment by djselbeck** [comment]
Probably a duplicate of #257

**Comment by sjllls** [comment]
This problem has solved on poplar, build with pre-build kernel on 2019.1.5.

@jerpelea
