### ISSUE TITLE
Incomplete performance on AOSP 9 ROMs

### ISSUE THREAD

**Issue by DGoX** [sonyxperiadev/bug_tracker#287]
**Platform:** suzu
**Device:** Sony Xperia X
**Kernel version:** 4.9
**Android version:** 9

**Description**
Sony X's overall performance is not very good on AOSP 9 ROMs.

**Symptoms**
List of apps is lagging, applications run longer than on official firmware, benchmarks score is twice smaller.

**How to reproduce**
Scroll through anything in any application like YouTube, Google App, Facebook, etc.
Run any benchmark test (for example GeekBench) and compare results with stock results.

**Comment by jerpelea** [comment]
the AOSP is intended for developers as a core platform

**Comment by b1mt3** [comment]
> the AOSP is intended for developers as a core platform

Hello, @jerpelea 
sorry for the intrusion, but allow me to elaborate on your comment,
and correct me if I'm wrong:

The whole concept of Sony Open Device is to provide the basis for ROM developers, i.e. as soon as there is a booting image (and provided the hardware is operating correctly), it becomes the developers' duty to smooth out any performance shortcomings and add features if desired?

Thank you for your time,
With kind regards,
Said.

**Comment by jerpelea** [comment]
the platform us tested with the provided code but we can not test what developers add or change (ex apps) that may impact on performance
