### ISSUE TITLE
[suzu] Minimal brightness is too hight

### ISSUE THREAD

**Issue by YuriyMosiychuk** [sonyxperiadev/bug_tracker#288]
**Platform:** loire
**Device:** suzu
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
Minimal brightness is too hight. Device not comfortable to use.

**How to reproduce**
Set brightness to 0 and see on display at night.

**Comment by jerpelea** [comment]
the brightness level can be customized in the xml
