### ISSUE TITLE
Android P Build error

### ISSUE THREAD

**Issue by tak40548798** [sonyxperiadev/bug_tracker#289]
Platform: loire
Device: suzu xperia x f5121
Kernel version: 4.9
Android version: android-9.0.0_r21

Description:
I am doing it according to the website.
[https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0)

terminal picture
[https://imgur.com/a/t08GNrC](https://imgur.com/a/t08GNrC)

[ 97% 86508/88632] //frameworks/base/libs/hwui:libhwui link libhwui.so
Warning: request a ThreadPool with 1 threads, but LLVM_ENABLE_THREADS has been turned off
[ 97% 86509/88632] //frameworks/base/libs/hwui:libhwui link libhwui.so [arm]
Warning: request a ThreadPool with 1 threads, but LLVM_ENABLE_THREADS has been turned off
ninja: build stopped: subcommand failed.
20:00:42 ninja failed with: exit status 1

**Comment by jerpelea** [comment]
please check your host os!

**Comment by MartinX3** [comment]
@tak40548798

I can say that Ubuntu 18.04 is working as a build Plattform.

**Comment by MartinX3** [comment]
It should work too.
I saw now that you use OpenJDK 9
I use OpenJDK 8

And if you want you can upgrade to 18.04
It is stable in my opinion. (Using Linux Mint 19.1)

```
$ apt policy openjdk-8-jdk
openjdk-8-jdk:
  Installiert:           8u191-b12-0ubuntu0.18.04.1
```
```
$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```
