### ISSUE TITLE
[suzu] Device (often) gets stuck in powering off

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#29]
**Platform:** loire
**Device:** suzu
**Kernel version:** 4.4 (prebuilt)
**Android version:** 7.1.1
**Firmware version:** v05

**Description**
The device gets stuck in powering off (by the user pressing the `POWER` button), rouhgly after 10+ mins of uptime. Several simple tests indicated that the first occurrence of the issue happens around this time. The issues happens rather often, but not always.

**Symptoms**
- The device is stuck in powering off, but is accessible via adb
- Only way to reboot it is by `adb  reboot`
- After the device is stuck the UI gets continuosly more sluggish (e.g. significant lag with screen turning on and off by pressing the `POWER` button)

**How to reproduce**
1. Power on device
2. Wait around 10 minutes
3. Long press the power button and select `Power off`

**Logs**
- `dmesg` gets flooded with the following, some time after the device gets stuck:
```[ 1134.894161] dhdsdio_sendfromq: Device asleep
[ 1134.894165] dhdsdio_sendfromq: Device asleep
[ 1134.894169] dhdsdio_sendfromq: Device asleep
[ 1134.894173] dhdsdio_sendfromq: Device asleep
[ 1134.894178] dhdsdio_sendfromq: Device asleep
[ 1134.894182] dhdsdio_sendfromq: Device asleep
[ 1134.894186] dhdsdio_sendfromq: Device asleep
[ 1134.894190] dhdsdio_sendfromq: Device asleep
[ 1134.894194] dhdsdio_sendfromq: Device asleep
[ 1134.894198] dhdsdio_sendfromq: Device asleep
[ 1134.894202] dhdsdio_sendfromq: Device asleep
```

**Comment by jerpelea** [comment]
this error should be fixed with the latest prebuilt kernel

**Comment by dimitar10** [comment]
I can confirm that the issue does not appear with the prebuilt kernel from Nov 8, so I am closing it.
