### ISSUE TITLE
[akari] No sounds on calls

### ISSUE THREAD

**Issue by Chiyoda0913** [sonyxperiadev/bug_tracker#290]
Android 9.0_r21
No sounds during calls.

**Comment by MartinX3** [comment]
Using this build
https://androidfilehost.com/?w=files&flid=287563
akari-img-9-PQ1A.181205.006-20181222.zip
Correct, @Chiyoda0913 ?

**Comment by Chiyoda0913** [comment]
@MartinX3 Yes, bro. As I told you in telegram.

**Comment by MartinX3** [comment]
@Chiyoda0913 
This information is needed by the Sony developers, bro. :P
(Codecheckout Date)

**Comment by jerpelea** [comment]
@Chiyoda0913 please do not share builds on github

**Comment by oshmoun** [comment]
Can you check if you have `/vendor/priv-app/QcRilAm`?

**Comment by Chiyoda0913** [comment]
> @Chiyoda0913 please do not share builds on github

would you like to point out the link of builds. I didn't remenber I had share builds on github. sorry for that.

**Comment by MartinX3** [comment]
And if you don't find them, you could use my builds on XDA / Android File Host. :)

**Comment by Chiyoda0913** [comment]
@oshmoun ok, I got it after rebuild. QcRilAm was missed. I will close this issue
