### ISSUE TITLE
[loire/maybe all] Battery drainage when SIM is inserted

### ISSUE THREAD

**Issue by RobbieBnt** [sonyxperiadev/bug_tracker#292]
**Platform:** loire
**Device:** suzu
**Kernel version:** 4.9
**Android version:** 9.0
**Binaries version:** v4

**Description**
Basically when we don't have any SIMs inserted, our battery drain becomes pretty much normal, BUT if we do have SIM card in a device, it starts to drain it much, MUCH faster. Probably related to [this](https://github.com/sonyxperiadev/bug_tracker/issues/267) issue.

**Symptoms**
High battery drainage with SIM and low without it.

**How to reproduce**
Get a device with k4.9 and AOSP and use it for a day/hour/etc with SIM. Then repeat, but w/o. You'll see the drastic improvement.

**Comment by Gray47Maxx** [comment]
Yes, can confirm it on suzu as well

Looks like Loire is the most problematic one, lol

**Comment by lubik1** [comment]
I can confirm abnormal battery drain with all 9.0 builds with 4.9 kernel and v4 binaries on Suzu. It much less drain without sim card, looks like it's a reason of.

**Comment by oshmoun** [comment]
that's kind of normal isn't it? the modem needs power to maintain a signal.
or were the tests done in airplane mode?

**Comment by Gray47Maxx** [comment]
@oshmoun true of course, but the difference between SIM card inserted and without it isn't noticeable on, for example, stock comparing to 4.9-based AOSP

**Comment by oshmoun** [comment]
may I suggest testing with airplane mode nevertheless? that way we can tell if the drain related to actual functionality

**Comment by Gray47Maxx** [comment]
No problems, will check it asap

**Comment by Gray47Maxx** [comment]
@oshmoun tested with airplane mode. The drain still persists, still more than on stock, and it's not better than without SIM

I think the problem is somewhere in RIL part...

**Comment by YuriyMosiychuk** [comment]
+1, confirm

**Comment by oshmoun** [comment]
is the same observable on 8.1 with 4.4 kernel? Asking because having a working base to compare against would be helpful.
The stock kernel is too ancient to serve that purpose imho.

**Comment by chris42** [comment]
On X Compact (Loire), 8.1, 4.4 I have "regular" battery usage.
Getting roughly 2 days out of a full charged battery with normal use (few calls, a bit of surfing, messaging).
Heavy usage, with lots of screen-on time and calls reduces it to a day.
Airplane mode of course increases it a lot, but was never able to get more than 3-4 days out of it.
This has been pretty consistent over time and not much changed since I first started using AOSP (I think on 7.0)

**Comment by jerpelea** [comment]
please wait for v5 to compare battery
