### ISSUE TITLE
X compact wifi failed

### ISSUE THREAD

**Issue by stanos4** [sonyxperiadev/bug_tracker#295]
**Platform: Loire
**Device: X Compact
**Kernel version: 4.4
**Android version: 8.1

**Description**
At some point I'm unable to switch ON the wifi adapter and system reboot is required. I'm not sure whether this could be the cause, but I use Xposed with microG services.

Here is the dmesg output: https://pastebin.com/PTmMsUVT

**Symptoms**
wifi adapter cannot be eventually switched on

**How to reproduce**
Random amount of time and wifi adapter switch ON and OFF cycles. No exact pattern to reproduce was discovered - sometimes it happens within few minutes after reboot and <5 wifi ON/OFF cycles but sometimes it doesn't happen for many hours. Switching the adapter OFF and ON will eventually lead to the problem though.

**Comment by mp107** [comment]
I can confirm the issue. I was also affected by this issue many times.

**Comment by chris42** [comment]
Do you both have microg with Xposed?

I have a X Compact with microg as well and didn't see this problem (little difference: I compile signature spoofing and microg together with the ROM).

**Comment by mp107** [comment]
I have Magisk and Xposed framework installed, no microg or gapps.

**Comment by stanos4** [comment]
I do, but without signature spoofing

**Comment by chris42** [comment]
Would be worthwhile checking your build without the Xposed framework, to rule it out.
Also helpful for the Sony guys would be your build information and which vendor blobs you are using.

@stanos4: You will need signature spoofing for microg, otherwise it does not work. Either built in the ROM or via a Xposed module.

**Comment by jerpelea** [comment]
I can not replcate the bug with the latest code 
please test!
