### ISSUE TITLE
[tama] crashes about bluetooth & android.process.media and the sdcard is marked as "corrupt" and not usable

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#297]
**Platform:** tama
**Device:** akari H8296 with a single sim card on slot 1 & an sdcard on slot 2
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
On first boot, the bluetooth service has a crash loop.

And I get crashes about bluetooth & android.process.media and the sdcard is marked as "corrupt" and not usable, after a second boot or going into airplane mode.

**Symptoms**
Looping crash messages.

And I get crashes about bluetooth & android.process.media and the sdcard is marked as "corrupt" and not usable, after a second boot or going into airplane mode.

**How to reproduce**
Build a **CLEAN** Dual Sim ROM.

Insert a SDCARD with an exFAT filesystem the AOSP doesn't support.
(Which is an important flash file system for users directly connecting their SDCARD with their computer to avoid the SLOW MTP).

First boot with H8296 dual sim with one sim card and one SDCARD.

I activate airplane mode and the crash went away.
Then I choose my SIM 1 as call, internet, SMS simcard and deactivate airplane mode again.
No crash anymore at homescreen.

But it crashes after I activate bluetooth, with the message "bluetooth keeps stopping".
Then it deactivates bluetooth.

**Logs**
[dmesg.txt](https://github.com/sonyxperiadev/bug_tracker/files/2737982/dmesg.txt)
[logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/2737983/logcat.txt)

Link to https://github.com/sonyxperiadev/bug_tracker/issues/296

**Comment by MartinX3** [comment]
@oshmoun
@jerpelea

The cause of the error (i found the idea in my logcat log) is the not supported sdcard.

My sdcard is formatted with exfat.
The system can't read it and thinks it is corrupt.

The question is:
1. Why crashes every app with file data access, like the camera app or the music player?
2. Why dissappeared nfc?
3. Why crashes bluetooth?

Shouldn't the system not "ignore" an corrupted sdcard or one with a not supported file system?

**Comment by MartinX3** [comment]
I did a reformat of my SDCARD

From MSDOS exFAT
to
GPT EXT4

Now instead of the message my SDCARD is corrupt, I get the message, that my SDCARD has an unsupported format.

Everything works and I don't get crashes with this unsupported format.
While the unsupported format exFAT makes crashes and is marked as corrupt.

**Comment by MartinX3** [comment]
btw.
Why isn't EXT4 supported as SDCARD format?
It's a native Linux Kernel format?

**Comment by Gray47Maxx** [comment]
I can confirm unsupported SD card format on loire (suzu). Tested with both exFAT and EXT4, in both cases it says that it's not supported

**Comment by jamuir** [comment]
> Why isn't EXT4 supported as SDCARD format?
> It's a native Linux Kernel format?

I believe that sdcard management is done by vold, and the unsupported format messages are probably coming from it.

You need to patch vold to support the new format.

**Comment by MartinX3** [comment]
@Gray47Maxx 
Did loire (suzu) crashed with exFAT in bluetooth, too, while ext4 is crash free?

@jamuir 
But why does extFAT leading to bluetooth and app crashings, a missing NFC option and showing an "corrupted sdcard" message,
while ext4 doesn't lead to crashes and just show me a message, that the SDCARD has an unsupported format?

Btw. shouldn't be ext4 and exFAT included by default?

**Comment by MartinX3** [comment]
ext4 is not supported by stockrom.
But exFAT is supported.

NTFS is not good for a flash storage. (I even don't know if it is supported)
And FAT32 doesn't support files bigger than 4GB.
(I use a 128GB SDCARD and want to storage a movie.)

**Comment by Gray47Maxx** [comment]
@MartinX3 can't replicate it

**Comment by MartinX3** [comment]
@Gray47Maxx
Then this maybe an akari bug ? :)

**Comment by MartinX3** [comment]
@kholk
Akari tama

fat32
supported and usable

ext4
not supported and the aosp is telling me that the sdcard is not usable

exFat
Not usable, sdcard marked as corrupt, Bluetooth crashes, NFC menu icon disappeared, every app which wants to access files crashes and Android.media process crashes, too.

**Comment by kholk** [comment]
Thanks, now we've got a full picture of it.

**Comment by jerpelea** [comment]
@MartinX3 did you menage to retest with a smaller card?

**Comment by jerpelea** [comment]
@MartinX3 I cant replicate it on my card formated FAT32

**Comment by MartinX3** [comment]
@jerpelea
**GPT Fat32** was the one worked fine.

**GPT ext4** -> AOSP tells me that the file system is not supported

**MSDOS exFAT** (Windows 10 SDCARD/SSD standard filesystem and usable in stock sony) -> crashes, problems, etc.)

**Comment by MartinX3** [comment]
Before I forget it.
As far as I remember correctly, the MSDOS exFAT formatted SDcard worked on OmniROM.
I didn't test it with GPT ext4 as I found the cause later only in sony AOSP.

**Comment by kholk** [comment]
I know what's wrong.....
I've had time to look at it and it's -really- stupid.

You miss fsck.exfat.
To temporarily solve the issue, you can do this:

adb root
adb remount (eventually adb disable-verity, if you have verity ON)

Open a shell and:
`
echo "#!bin/sh
exit 0" > /system/bin/fsck.exfat
chcon u:object_r:fsck_exec:s0 /system/bin/fsck.exfat
`

The issue is that you miss that program and, for now, as far as I
know, there is no open source fsck.exfat for kernel implementations.
There is one, but that's for FUSE ExFAT and that won't work.

Keep in mind that this will FAKE a successful fsck on your ExFAT
SDCard / USB HDD and won't mean that your filesystem is not
corrupt (in case it is). Moreover, this means that - in case that your
filesystem gets corrupted for some reason - you will have to plug
your SDCard or your _whatever_ in a PC to run a real fsck.

I hope that we can find an opensource fsck for ExFAT so that
we will be able to solve this situation the right way.

Enjoy the temporary solution.

**Comment by jerpelea** [comment]
@MartinX3 updates

**Comment by MartinX3** [comment]
@MartinX3 
Oh, I thought I should wait until an open source implementation appeared, since the fake  **fsck.exfat** doesn't repair the sdcard file system.
Of course I can retest it tomorrow after my exam.

**Comment by jerpelea** [comment]
@MartinX3 did you manage to test with the OSS **fsck.exfat**?

**Comment by MartinX3** [comment]
@jerpelea
Sorry, yes
https://github.com/SonyAosp
I was able to mount and use my extfat sdcard
But the Sony open devices volunteers told me that it won't be merged in Xperiadev
@ix5 ? @oshmoun ? @kholk ?

**Comment by jerpelea** [comment]
@MartinX3 please link the git not the account

**Comment by MartinX3** [comment]
Sorry, migraine
Will get the needed repos/commits together and list them as complete as I can :)

**Comment by jerpelea** [comment]
the exFAT git has been added to the project and the build is enabled
https://github.com/sonyxperiadev/local_manifests/commit/2382083c7c19cf8da9a51618aeb064ebbe74f5aa
https://github.com/sonyxperiadev/device-sony-common/commit/9cebcd26da2a1c5c10983647ec26afd79758ec9c

**Comment by MartinX3** [comment]
Thank you very much, you was faster than me. :)
