### ISSUE TITLE
[Suzu] Wi-Fi Hotspot (Tethering) 5.0GHz band

### ISSUE THREAD

**Issue by lubik1** [sonyxperiadev/bug_tracker#299]
**Platform:** Loire
**Device:** Suzu
**Kernel version:** 4.9.146

**Android version:** 9.0.0_r21 blobs v4

**Description**
If you enable 5Ghz band - you cant enable wi-fi hostpot (tethering), it turns off. This function is present on sonyxperiadev aosp sources, so must it work?

**Symptoms**
When you go to settings-network, internet-hostspot, tethering-Wi-Fi hostpot-Advanced-Ap Band-5.0Ghz band and turn on hostspot it automaticaly turn it off

**How to reproduce**
Just try swich to 5Ghz and turn wi-fi hostpot on

log included
[1.log](https://github.com/sonyxperiadev/bug_tracker/files/2745091/1.log)

**Comment by ix5** [comment]
Same thing happens on kagura/tone:
[2019-01-10-tether-5ghz.txt](https://github.com/sonyxperiadev/bug_tracker/files/2746491/2019-01-10-tether-5ghz.txt)
[2019-01-10-tether-5ghz-dmesg.txt](https://github.com/sonyxperiadev/bug_tracker/files/2746492/2019-01-10-tether-5ghz-dmesg.txt)

**Comment by harryharryharry** [comment]
Some symptoms for kugo.

**Comment by oshmoun** [comment]
looks like an issue in broadcom's hal
switching to qcom's implementation fixes the issue here on kugo
need to see if this is really a viable solution to use for both affected platforms (loire and tone)

**Comment by oshmoun** [comment]
Should be resolved now, can you please test and confirm?

**Comment by ix5** [comment]
This issue is still present, please reopen @jerpelea

**Comment by mhtvsSFrpHdE** [comment]
@oshmoun How did you do that in specified? Like changing some build configuration?
Here is maple 9.0 r46 & msm4.9, encountering all the problems and even Wi-Fi itself can't turn on.

**Comment by oshmoun** [comment]
not sure i understand the question. but in any case, maple does not utilize broadcom hardware for wifi so this issue is unrelated. please consider opening a new issue to describe what you're observing

**Comment by mhtvsSFrpHdE** [comment]
@oshmoun Got it. I go https://github.com/sonyxperiadev/bug_tracker/issues/533 first, in the bottom of issue he mentioned here

ix5

> Please close the issue and follow #299

I'm considering to try `msm4.9 + Android 10 r33` or use  
https://github.com/stefanhh0/aosp-10 to see if this is fixed in later version.

**Comment by dslul** [comment]
> looks like an issue in broadcom's hal
> switching to qcom's implementation fixes the issue here on kugo
> need to see if this is really a viable solution to use for both affected platforms (loire and tone)

@oshmoun Did you apply this fix to your omnirom builds for suzu? How did you do it? I never got any problem in one year of usage (except for reboots), both usb tethering and wifi hostpot worked fine. Now with the latest kernel patches random reboots seem to be gone, but tethering and hotspot don't work at all.
