### ISSUE TITLE
[LOIRE] [ALL] Random loud buzzing sounds on audio playback

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#3]
**Platform**: SoMC Loire
**Device**: ALL
**Kernel version**: 4.4.xx
**Android version**: 8.0 (/ALL)

**Description**
When audio is being played, there is a chance that instead, a loud buzzing/crackling sound is heard, even when device is muted.

**How to reproduce**
1. Make a phonecall
2. End the phonecall
3. Run a 3dmark benchmark test
4. Start music playback in any music player

At some point, the buzzing should occur.

**Comment by oshmoun** [comment]
The issue has been mitigated greatly, but still happens.

**Comment by notz** [comment]
It occurs nearly on any video. This bug makes the device unusable.

**Comment by oshmoun** [comment]
this is solved now thanks to this PR:
https://github.com/sonyxperiadev/kernel/pull/1508
