### ISSUE TITLE
[tone] The dreaded tone 4.9 deep sleep bug

### ISSUE THREAD

**Issue by ix5** [sonyxperiadev/bug_tracker#300]
**Platform:** tone
**Device:** kagura
**Kernel version:** 4.9
**Android version:** 

**Description**
We never bothered to write down this bug, since it's so widely known. Since kernel 4.9, the device fails to properly enter deep sleep. Whereas on 4.4 it would enter deep sleep for about 5 minutes at a time, it re-awakens after about 5 seconds on 4.9.

**Symptoms**
Device wakes up(screen remains off) after 5 seconds of deep sleep, then immediately goes back to sleep again. This cycle continues indefinitely.
This also leads to the display wake-up taking anywhere between one and ~10 seconds.

**How to reproduce**
Turn the screen off. The device has to be by itself, with no USB connection or charger.

**Comment by jerpelea** [comment]
duplicated https://github.com/sonyxperiadev/bug_tracker/issues/267
