### ISSUE TITLE
[tone][kagura] Front Camera Not Focusing Compared to Stock

### ISSUE THREAD

**Issue by danielaniq28** [sonyxperiadev/bug_tracker#301]
Platform: tone
Device: kagura
Kernel version: 4.9
Android version: 9

Description
Front Camera stuck at certain focus level, and produces blurry photos

Symptoms
Pictures are blurry and stuck at certain focus level

How to reproduce
Use gcam or any camera and take front camera picture.

**Comment by DGoX** [comment]
The same on loire

**Comment by jerpelea** [comment]
Depending on device's tolerance the OSS implementation will fail some time because we are not reading the EEprom data
