### ISSUE TITLE
[Maple] Still can't wake up from deep sleep

### ISSUE THREAD

**Issue by Artoriarcher** [sonyxperiadev/bug_tracker#302]
**Platform:** Yoshino
**Device:** Maple[G8142]
**Kernel version:** 4.9
**Android version:** 9.0
**OEM version:** v4

**Description**
-My Maple can't wake up from deep sleep(5-10min or longer)
-To continue to use the Maple, must force restart
-And then after a long time, it will can't wake up from deep sleep again
**Symptoms**
Device can't wake up from deep sleep 

**How to reproduce**
Install aosp with the latest oem in Maple, let it enter deep sleep

**Comment by kholk** [comment]
The issue has been resolved with https://github.com/sonyxperiadev/kernel/pull/1884

This can closed. Thanks everyone for reporting and testing the various proposed solutions.
