### ISSUE TITLE
XA2 Plus captured image is rotated by 90 grad 

### ISSUE THREAD

**Issue by XperiaDeveloper** [sonyxperiadev/bug_tracker#303]
**Platform:** Nile
**Device:** XA2 Plus Dual
**Kernel version:** 4.4
**Android version:** 8.1

**Description**
When taking an image, the captures data is rotated by 90 degrees. This fault appears only if the device is straight. In a horizontal position images are captures correctly.

**Steps to reproduce:**
    Open system Camera App
    By holding the device straight take a photo
    Open Gallery

**Actual Behavior:**
Image is rotated by 90 degrees. 

 

**Expected Behavior:**
Image is captured correctly and not rotated.

**Comment by jerpelea** [comment]
If sensors are not reporting the device orientation the camera can not process correctly the camera rotation.

The issue is caused by the sensors race condition and it appears to be fixed after the last patch

**Comment by dimitar10** [comment]
Issue seems to persist on XA2 and XA2 Ultra, kernel 4.4.172-gbec4b88-dirty and nile-v16 firmware.

**Comment by dimitar10** [comment]
@jerpelea the issue is still present on the XA2 (I haven't checked it yet on the XA2 Ultra), with kernel 4.4.172-g8dfdd1b-dirty and nile-v17 firmware. With firmware v15 and what was then current in the kernel, the issue was fixed, and it was evident that it has appeared again only after v16 firmware was published, if I'm not mistaken.

**Comment by jerpelea** [comment]
I will check what the regression is 
thanks for pointing it out

can you please check v15 with current kernel ?

**Comment by dimitar10** [comment]
The behaviour is the same with v15 and newest kernels (both prebuilt and built from source). After searching through some of my older builds, the latest one that I have in which the issue is not present is with kernel 4.4.156-gd67917e-dirty and v15.

**Comment by jerpelea** [comment]
does it work with v17 and the old kernel?

**Comment by dimitar10** [comment]
Yes, it does. Just checked it.

**Comment by jerpelea** [comment]
then we should search for the offending kernel commit
