### ISSUE TITLE
[Discovery] boot.img exceeds max size

### ISSUE THREAD

**Issue by ploth** [sonyxperiadev/bug_tracker#305]
**Platform:** Nile
**Device:** Discovery, XA2 Ultra, H3213
**Kernel version:** 4.9
**Android version:** android-9.0.0_r30

**Description**

`fastboot flash boot boot.img` results in:
```zsh
target didn't report max-download-size
sending 'boot' (22549 KB)...
FAILED (remote: Requested download size is more than max allowed
)
finished. total time: 0.000s
```

**How to reproduce**

Build `android-9.0.0_r30` branch for `aosp_h3213-userdebug` and try to flash `boot.img`

**Comment by jerpelea** [comment]
ls -l boot.img please

**Comment by jerpelea** [comment]
I cant replicate on a vlean build

**Comment by ploth** [comment]
`$ ls -l boot.img
-rw-r--r-- 1 ploth ploth 23090472 Jan 20 10:54 boot.img`

**Comment by stefanhh0** [comment]
I had the same problem. Reason was that I tried to flash while my notebook was on battery. As soon as I plugged in the power-cord and restarted the phone into bootloader it worked without any problems.

I've just retried that procedure and could reproduce it, maybe you have the same problem:

Failed attempt:
root@mars:/home/stefan/android-bin/2019_01_18# fastboot flash vendor vendor.img 
target didn't report max-download-size
sending 'vendor' (50236 KB)...
FAILED (remote: Requested download size is more than max allowed
)
finished. total time: 0.000s

After re-plugging the power-cord and rebooting the phone into the bootloader again it worked:  
root@mars:/home/stefan/android-bin/2019_01_18# fastboot flash vendor vendor.img 
target reported max download size of 536870912 bytes
sending 'vendor' (50236 KB)...
OKAY [  1.905s]
writing 'vendor'...
OKAY [  0.003s]
finished. total time: 1.908s

**Comment by ploth** [comment]
Sounds like black magic ;)
I was on AC the entire time, I had to reenter the fastboot mode multiple times before I was able to flash again.

**Comment by stefanhh0** [comment]
Good that it works now. Another reason could be an unstable usb connection... Next time you could also try using a different usb plug or cable.

When switching to battery, several power saving mechanisms kick in - that would be a better explanation than good old witchcraft :-)

**Comment by MartinX3** [comment]
Sometimes it gets buggy for me too
Random throwing errors
But in the last time it worked again without these problems

**Comment by ploth** [comment]
Just to throw in more black magic :D I changed my workplace and put my laptop in standby for that. Then it worked using the same usb cable from before.

**Comment by MartinX3** [comment]
I got the same random errors again and need to restart my phone into fastboot after every "fastboot flash".
And sometimes while fastboot wants to flash the device just restarts. :D

**Comment by waltercool** [comment]
> I got the same random errors again and need to restart my phone into fastboot after every "fastboot flash".
> And sometimes while fastboot wants to flash the device just restarts. :D

Yeah, I can reproduce the same. No idea if this is a Linux specific issue or not, tried 3 different versions of fastboot, used different Linux distros (own Gentoo + Ubuntu 18.04 + Debian), even a different computer with Linux, and same problem.

For now I can't test myself with Windows because I don't have a partition for that, and doesn't work for me using QEMU, got usb connect/disconnect issues.

I will try today later using a borrowed Windows, I read somewhere at XDA about using Sony's fastboot drivers may solve the problem.

**Comment by waltercool** [comment]
Update:

Tried on a OSX and worked correctly. I would guess this is a Linux specific issue.

At Linux, it fails to me using fastboot version 28.0.1-4986621

**Comment by jamuir** [comment]
I've found communication with sony devices over fastboot to be quite flakey (and I have tested a number of different sony devices).

I started testing the connection by repeatedly running `fastboot getvar product`.  About 5 or 6 times out of 10 that command would fail.  I raised a ticket on this (outside of Sony Open Devices) but there was no resolution.

When I started using a usb hub, the problem went away for me.  Maybe it has something to do with the voltage supplied by the usb connection.

I also found that the connection was stable when I tried on a mac.

**Comment by djselbeck** [comment]
I have problems with my Linux on a lenovo x240 and Yoshiko/lilac and tone/kagura when directly connected to the machine. It works when I disable USB3 in the BIOS.

It however works with USB3 and a hub between.

**Comment by waltercool** [comment]
> I have problems with my Linux on a lenovo x240 and Yoshiko/lilac and tone/kagura when directly connected to the machine. It works when I disable USB3 in the BIOS.
> 
> It however works with USB3 and a hub between.

I can confirm the hub as solution. Thanks!

**Comment by MartinX3** [comment]
With my ThinkPad T460P Ultra Dock 90W and AC I get the weird errors at USB3 and USB2.
But at my Windows 10 PC with USB3 and USB2 it is stable.

**Comment by djselbeck** [comment]
I also use the UltraDock and the ports are as unstable as the ones on the device itself for me. I have two Dell displays with integrated USB3 hubs, connected to the dock and when I use these for fastboot it will work 100% reliable.

**Comment by MartinX3** [comment]
Now I understand my bug in the past.
https://github.com/sonyxperiadev/bug_tracker/issues/240

**Comment by Haxk20** [comment]
I have the exact same issue on my device (mermaid). Will try USB hub. Does it have to be powered one or just normal one ?

**Comment by waltercool** [comment]
> I have the exact same issue on my device (mermaid). Will try USB hub. Does it have to be powered one or just normal one ?

Just a normal one. I assume USB hub distribute power supply independent from computer. I tried with USB 2.0 and USB 3.0 and works great. Just fails when directly connected.
