### ISSUE TITLE
[Discovery] Unable to boot android-9.0.0_r30

### ISSUE THREAD

**Issue by ploth** [sonyxperiadev/bug_tracker#306]
**Platform:** Nile
**Device:** Discovery, XA2 Ultra, H3213
**Kernel version:** 4.9
**Android version:** android-9.0.0_r30

**Description**

Unable to boot after clean build and flashing as follows:

```zsh
fastboot flash boot boot.img
fastboot flash system system.img
fastboot flash vendor vendor.img
fastboot flash userdata userdata.img
fastboot flash oem SW_binaries_for_Xperia_Android_9.0_2.3.2_v4_nile.img
```

Retried multiple times.

**Symptoms**

Phone is stuck at Sony Logo. `adb` is not available.

**How to reproduce**

Build `android-9.0.0_r30` and flash images.

**Comment by djselbeck** [comment]
Same on lilac/yoshino. Last build that works for me is from 11.01. Builds from 17.1 and 19.1 are not booting

**Comment by MartinX3** [comment]
Same on TAMA/akari
thought I did a mistake

**Comment by MartinX3** [comment]
@ix5 thank you for hinting it
https://github.com/sonyxperiadev/device-sony-common/commit/7d5c880aa1a82c95df2c41154f51ff30187e4496
we need to wait for vendor blobs v5

**Comment by Raphos** [comment]
Hi,
Same here on XZ2 Compact Dual H8324.

**Comment by stefanhh0** [comment]
Thx for the info. Trying to do it as follows then:
```
pushd device/sony/common
git checkout dbc9da0
popd
make clean && make -j 4
```

**Comment by jerpelea** [comment]
The problem is fixed and the v5 blobs will be available soon.
