### ISSUE TITLE
[loire] No 20MP option available

### ISSUE THREAD

**Issue by Gray47Maxx** [sonyxperiadev/bug_tracker#307]
**Platform:** loire
**Device:** suzu
**Kernel version:** 4.9.146
**Android version:** 9.0
**Binaries version:** [v5a](https://developer.sony.com/file/download/software-binaries-for-aosp-pie-android-9-0-kernel-4-9-loire-2/)

**Description**
Since v5a we've lost the ability to capture more than 17 megapixels (5504x3104).

**Symptoms**
The maximum resolution for capturing is limited by 17MP, whereas v4 blobs allowed us to capture 20.

**How to reproduce**
Get any camera app you like and try to set the maximum resolution.

**Comment by belov555** [comment]
![screenshot_ _20190121-094147](https://user-images.githubusercontent.com/23725582/51468288-3fc99500-1d77-11e9-9c12-8d12a235ea52.png)
I confirm

**Comment by jerpelea** [comment]
This is not a bug!
17Mp is the HW limit for full API 2 capability

**Comment by Gray47Maxx** [comment]
Then how was it working on k4.4? It has full API 2 support _and_  capability to take photos in 20mp mode...

**Comment by jerpelea** [comment]
Android 8.1 has the same capability as v4

**Comment by gerg5c42g542g2c54g52c** [comment]
@Gray47Maxx how did you find a link to the v5a vendor image? Nothing about it on any developer.sony.com page.

**Comment by Gray47Maxx** [comment]
@jerpelea oh you were right... But maybe there is a way to bypass it? Some dirty hacks for example...

@gerg5c42g542g2c54g52c the real magician never tells anyone his [secret](https://t.me/SMDW_downloads) ;)

**Comment by jerpelea** [comment]
The HW limitation is there and you will not be able to have the minimum requirements for API 2 unless you fake the capability.

**Comment by gerg5c42g542g2c54g52c** [comment]
@jerpelea is no 1080p/60fps also an unfixable hardware limitation?

**Comment by gerg5c42g542g2c54g52c** [comment]
I can't enable 60fps for 1080p in Open Camera, it can be enabled only for 720p. No fps option in AOSP Camera.

**Comment by jerpelea** [comment]
did you update media_profiles?

**Comment by gerg5c42g542g2c54g52c** [comment]
No, shouldn't this be in the repo?

There's no 4K in loire's media_profiles file and yet it's possible to record in this resolution. Perhaps 1080/60 isn't the highest supported?

**Comment by jerpelea** [comment]
on loire I am not sure that this mode will work. The same sensor is found on other platforms.

**Comment by gerg5c42g542g2c54g52c** [comment]
@jerpelea 

> did you update media_profiles?

Is this what you mean? I added a highspeed1080p profile based on highspeed720p and changed maxFrameRate for h264 to 120fps. I'll soon be testing if this is correct.

```
diff --git a/device/sony/loire/rootdir/vendor/etc/media_profiles_V1_0.xml b/device/sony/loire/rootdir/vendor/etc/media_profiles_V1_0.xml
index 350d5cc..b372f7c 100644
--- a/device/sony/loire/rootdir/vendor/etc/media_profiles_V1_0.xml
+++ b/device/sony/loire/rootdir/vendor/etc/media_profiles_V1_0.xml
@@ -162,6 +162,19 @@
                     channels="1" />
          </EncoderProfile>
 
+        <EncoderProfile quality="highspeed1080p" fileFormat="mp4" duration="30">
+             <Video codec="h264"
+                   bitRate="42000000"
+                   width="1920"
+                   height="1080"
+                   frameRate="60" />
+             <!-- audio setting is ignored -->
+             <Audio codec="aac"
+                    bitRate="96000"
+                    sampleRate="48000"
+                    channels="2" />
+         </EncoderProfile>
+
         <ImageEncoding quality="95" />
         <ImageEncoding quality="80" />
         <ImageEncoding quality="70" />
@@ -315,7 +328,7 @@
         minBitRate="64000" maxBitRate="100000000"
         minFrameWidth="176" maxFrameWidth="3840"
         minFrameHeight="144" maxFrameHeight="2160"
-        minFrameRate="15" maxFrameRate="30" />
+        minFrameRate="15" maxFrameRate="120" />
 
     <VideoEncoderCap name="h263" enabled="true"
         minBitRate="64000" maxBitRate="2000000"
```

**Comment by gerg5c42g542g2c54g52c** [comment]
@jerpelea I tested the above patch and I still cannot record 1080p/60fps videos in Open Camera. Am I doing something wrong? Can this be fixed?

**Comment by Gray47Maxx** [comment]
Apparently something happened and now loire can in 20MP again.
