### ISSUE TITLE
[Discovery] Unable to use provider network

### ISSUE THREAD

**Issue by ploth** [sonyxperiadev/bug_tracker#309]
**Platform:** Nile
**Device:** Discovery (H3213)
**Kernel version:** 4.9
**Android version:** android-9.0.0_r30

**Description**

SIM card is unlocked. I'm not able to start a call. I got a message from my provider that someone called me but it is not possible to call someone or use mobile internet. The network provider was automatically selected and is correct.

**Symptoms**

Unable to call anybody. It doesn't start to ring. WebView states: `net::ERR_INTERNET_DISCONNECTED`

**How to reproduce**

Flash `boot, system, vendor, userdata and v5 oem`.

**Comment by oshmoun** [comment]
the issue should be fixed now

**Comment by ploth** [comment]
It's still on [r30](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0#tutorial-step-3) on this site. What is needed? Are there any new blobs?

**Comment by jerpelea** [comment]
you should rebuild your kernel or wait for new prebuilt one (It is building now)
