### ISSUE TITLE
[maple] Factory data reset renders device unbootable

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#31]
**Platform:** yoshino
**Device:** maple
**Kernel version:** 4.4 (prebuilt, Nov 8)
**Android version:** 8.0.0
**Firmware version:** v05

**Description**
After initiating a factory data reset, the device tries to reboot, it fails, and shuts down.

**Symptoms**
After the failed factory data reset attempt the device will not boot at all, even retrying to boot it via the `POWER` button won't work. The device will enter into a boot loop if connected to a charger. If the device is booted into `fastboot` mode and then the `fastboot reboot` command is issued, the device continues to work correctly as before the factory reset (the factory reset is never performed).

**How to reproduce**
`Settings App -> System -> Reset -> Factory data reset -> Reset phone -> Erase everything`

**Logs**
N/A

**Comment by kholk** [comment]
This issue should be present only on Maple.

Can anyone please try to repeat the steps on Poplar and/or Lilac?

**Comment by jerpelea** [comment]
tested poplar and device boots fine

**Comment by jerpelea** [comment]
bug confirmed 
I am fixing it

**Comment by jerpelea** [comment]
fixed (first boot will take a wile)

**Comment by jerpelea** [comment]
tested also on Android 7.1 and bug is fixed
