### ISSUE TITLE
[suzu] All USB preferences grayed out.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [sonyxperiadev/bug_tracker#310]
Clean AOSP 9, vendor v5.

![screenshot](https://user-images.githubusercontent.com/19863386/51566583-30d90480-1e95-11e9-8b39-aac1de4ef40c.png)

**Comment by jerpelea** [comment]
I added a basic USB HAL from lineage OS and the menu is working fine now on both suzu and dora devices 
Please sync and rebuild
