### ISSUE TITLE
[suzu] UI not displayed properly (Launcher3).

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [sonyxperiadev/bug_tracker#311]
Clean unmodified AOSP 9, vendor v5. Default AOSP launcher Launcher3.

I think time should be on the right of the top bar, not on the left. The top drawer (quick icons after sliding from the top) is pretty messed up, icons don't fit the screen, the top bar becomes huge, it looks really bad and non-standard. I only ever experienced AOSP built by other people before, so can't be sure what's responsible for this, but it never looked like this.

![1](https://user-images.githubusercontent.com/19863386/51566680-83b2bc00-1e95-11e9-8587-23841e9c5ecc.png)
![2](https://user-images.githubusercontent.com/19863386/51566681-83b2bc00-1e95-11e9-982d-c83f3f49b891.png)
![3](https://user-images.githubusercontent.com/19863386/51566682-83b2bc00-1e95-11e9-81d6-a16924123f55.png)

Also, many options in Settings are missing that were available in AOSP ROMs like Camera on lockscreen for example.

**Comment by invalidsudo** [comment]
The quick toggles not fitting on the first slide down is the only problem I see.

I'm 99.9% sure that the rest is normal design introduced with Android Pie.

**Comment by jerpelea** [comment]
We do not change any of the AOSP options. This is the normal design in Android 9
