### ISSUE TITLE
[lilac] Erratic boot behavior

### ISSUE THREAD

**Issue by invalidsudo** [sonyxperiadev/bug_tracker#313]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.150
**Android version:** 9

**Description**
This was from my experience with a clean AOSP build today. Usually what happens is the Sony splash screen is displayed, then the device reboots. Sometimes, the Android boot animation appears after the Sony splash screen, but the device reboots from there. There's a very slim chance, around 1 in 50, that the device will continue to boot into Android, but it's useless because a System UI has crashed message is displayed, after which the device reboots and the cycle continues.

Around two weeks ago I managed to fully boot into Android by connecting the device to my computer with a USB cable, but I couldn't reproduce it afterwards.

Also, what's with the Sony splash screen glitching?

**Symptoms**
Chance of successfully booting is extremely random.

**How to reproduce**
Flash boot, system, userdata, cache, recovery, vendor, and v5 OEM image, then attempt to boot. Do not flash anything else such as TWRP or Magisk.

**Comment by jerpelea** [comment]
please run
fastboot getvar all 
I want to see what bootloader you have and what was the latest SW flashed 

Thanks

**Comment by invalidsudo** [comment]
The following is the output of fastboot getvar all: https://pastebin.com/R2nH1Ywn

I made sure to build the kernel and not build with the prebuilt after the PR, but the problem is still not resolved. 

I will wait for [sonyxperiadev/kernel#1887](https://github.com/sonyxperiadev/kernel/pull/1887) to be merged, then try again.

If you were able to test it on Lilac, why am I not able to boot mine? Should I clear ccache before building?

**Comment by jerpelea** [comment]
please downgrade the device to the latest 47.1.a.x.x SW available on Emma

**Comment by invalidsudo** [comment]
Downgraded to 47.1.A.16.20, problem persists. 

Output of fastboot getvar all: https://pastebin.com/UrqGtRUT

Just to be clear, I will state my procedure again. 

After getting firmware from XperiFirm and flashing via newflasher, I went straight to fastboot mode from flash mode without booting into the system, and then I flashed oem, boot, system, vendor, and userdata. I then attempted to boot into the system.

**Comment by jerpelea** [comment]
please add a sim card and boot the device
on the first boot your device will perform several configuration steps that are needed

**Comment by invalidsudo** [comment]
Noted. Do I need to go through the full setup process, or is it ok if I just stay booted for a minute or so?

**Comment by invalidsudo** [comment]
Built and flashed kernel with [sonyxperiadev/kernel#1887](https://github.com/sonyxperiadev/kernel/pull/1887), device boots now! Thank you so much @kholk! Please close this issue.

**Comment by invalidsudo** [comment]
I would also like to add that 47.1.a.x.x firmware and a first boot is required. Everything else doesn't matter.

**Comment by djselbeck** [comment]
As said in #364 I think I am affected by this bug
