### ISSUE TITLE
Can't sign the builds. dev-keys are always used. No system.img generated.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [sonyxperiadev/bug_tracker#314]
How does one sign their builds with their own keys? Whatever I do, the built AOSP says that it's built with dev-keys which I guess are test keys. I want to build proper production images signed with my own keys.

When I do `make target-files-package` instead of `make`, there's no system.img in out/target/product/suzu, there's one in out/target/product/suzu/obj/PACKAGING/target_files_intermediates/aosp_f5121-target_files-eng.host/IMAGES but it doesn't work.

Also, why is there `eng` in `aosp_f5121-target_files-eng.host` when I chose the build to be a `user` BUILDTYPE, does this mean it's an `eng` BUILDTYPE?

Should I replace the keys in build/target/product/security and vendor/oss/release-keys and do `make`? That doesn't sound like the right way to do this, there's probably a reason why the test keys are separate (different files) from release keys and why there is a target-files-package target. Or is there a normal way to do this?

**Comment by chris42** [comment]
Please see the android guide here: https://source.android.com/devices/tech/ota/sign_builds
It gives step by step instructions.

**Comment by jamuir** [comment]
> Also, why is there eng in aosp_f5121-target_files-eng.host when I chose the build to be a user BUILDTYPE, does this mean it's an eng BUILDTYPE?

If you do a build without setting the variable `BUILD_NUMBER`, then the string "eng" is used to indicate that this an engineering build (it has nothing to do with the "eng" build type):

https://android.googlesource.com/platform/build/+/master/core/version_defaults.mk#307

**Comment by jamuir** [comment]
In the Sony tree, the variable `PRODUCT_DEFAULT_DEV_CERTIFICATE` is set so that the keys under `vendor/oss/release-keys` get used (this is why you see "dev-keys" in the build fingerprint):

https://github.com/sonyxperiadev/device-sony-common/commit/89d7e032c61daedc9c8936f816ec667be1fafec9

There really isn't much point to setting `PRODUCT_DEFAULT_DEV_CERTIFICATE`, however.  I would like to see it dropped from the tree (it previously broke some re-signing operations).

The standard way to re-sign builds is given in the link provided by @chris42 .

**Comment by gerg5c42g542g2c54g52c** [comment]
When I do
```
make installclean
make dist
```
I get this error:
```
Running: system/extras/verity/build_verity_metadata.py build 7720988672 /tmp/tmpkYvC7K_verity_images/verity_metadata.img c2780a2a7ebb72d7f093872fdef038c8ab881671b59dacf3d6e5de75c32ed475 aee087a5be3b982978c923f566a94613496b417f2af592639bc80d141e34dfe7 /dev/block/platform/soc/7824900.sdhci/by-name/system verity_signer build/target/product/security/verity.pk8
['verity_signer', '/tmp/tmpp25Qhe.table', 'build/target/product/security/verity.pk8', '/tmp/tmpDvNCbK.sig']
Running: fec -e -p 0 out/target/product/suzu/obj/PACKAGING/target_files_intermediates/aosp_f5121-target_files-eng.host/IMAGES/system.img /tmp/tmpkYvC7K_verity_images/verity.img /tmp/tmpkYvC7K_verity_images/verity_fec.img
terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
Could not build FEC data! Error: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc

Traceback (most recent call last):
  File "build/make/tools/releasetools/add_img_to_target_files", line 824, in <module>
    main(sys.argv[1:])
  File "build/make/tools/releasetools/add_img_to_target_files", line 818, in main
    AddImagesToTargetFiles(args[0])
  File "build/make/tools/releasetools/add_img_to_target_files", line 727, in AddImagesToTargetFiles
    output_zip, recovery_img=recovery_image, boot_img=boot_image)
  File "build/make/tools/releasetools/add_img_to_target_files", line 150, in AddSystem
    block_list=block_list)
  File "build/make/tools/releasetools/add_img_to_target_files", line 281, in CreateImage
    assert succ, "build " + what + ".img image failed"
AssertionError: build system.img image failed
[ 99% 2347/2359] Target system fs image: out/targ...bj/PACKAGING/systemimage_intermediates/system.img
ninja: build stopped: subcommand failed.
16:42:05 ninja failed with: exit status 1
```

I'll try rebuilding from scratch (make clobber) tomorrow, but it would be nice to know if it makes any sense to waste 7 hours on this.

**Comment by jamuir** [comment]
I suspect you are either out of disk or memory.

Try re-running the "fec" command:

```
fec -e -p 0 out/target/product/suzu/obj/PACKAGING/target_files_intermediates/aosp_f5121-target_files-eng.host/IMAGES/system.img /tmp/tmpkYvC7K_verity_images/verity.img /tmp/tmpkYvC7K_verity_images/verity_fec.img
```

**Comment by gerg5c42g542g2c54g52c** [comment]
The fec command reported no such file in /tmp. I resynced the repo, rebooted and set -j to a lower value and it worked, so I think you were right (even though my disk or memory weren't full, swap was at 60% at one point though).

> If you do a build without setting the variable `BUILD_NUMBER`, then the string "eng" is used to indicate that this an engineering build (it has nothing to do with the "eng" build type):
> 
> https://android.googlesource.com/platform/build/+/master/core/version_defaults.mk#307
Is something like `export BUILD_NUMBER=build1` the right way to set it?

**Comment by jamuir** [comment]
I think it is normal for userdata.img to be absent from the re-signed target-files zip (I recall reading something about that in the re-signing scripts).  In any case, you don't usually need to flash the userdata partition.  Note that you can wipe userdata using `fastboot -w`.

re `BUILD_NUMBER`:  yes, you can set it using "export".  It is usually assigned a number, e.g. `export BUILD_NUMBER=42`.

**Comment by ix5** [comment]
@gerg5c42g542g2c54g52c you say you need 7 hours? I am very sorry to hear that. Look into ccache, it will at least speed up the C/C++ parts of the build.

And maybe think about getting an SSD and a new processor. A full build with no caches whatsoever takes ~3 hours for me, a partial rebuild is done in about 5 minutes, including signing and compression.

**Comment by ix5** [comment]
A _partial_ rebuild with warm caches shouldn't take 7 hours, that's what I meant.

**Comment by MartinX3** [comment]
@ix5 yes
5 minutes with 'make installclean'
And 20-30 minutes if you remove the target folder.

**Comment by gerg5c42g542g2c54g52c** [comment]
@jamuir When I do `fastboot -w` the system doesn't boot, it freezes on the android on black background screen. When I flash userdata.img from another test-key build, it boots, but I'm worried this is insecure and that userdata.img should be signed too.

@ix5 I do use ccache already, but for some reason it's cache is only 1GB, I don't know why, perhaps Google changed their mind on ccache support (info about ccache was removed from source.android.com)? CCACHE_MAXSIZE=0, CCACHE_NLEVELS=8 and USE_CCACHE=1 are set and there's terabytes of free space. The cache is on the same HDD as all the build files. Android 8 builds were faster for me, 5 hours, but Android 9 takes 7, sometimes even 8 hours. This are full builds after make clobber, if I do make installclean instead then it takes 20-30 minutes. Yes, I'll be upgrading this machine in the following months.

**Comment by ix5** [comment]
@gerg5c42g542g2c54g52c You can try to change your ccache size again. Man, this breaks my heart to see you suffer ;)

`prebuilds/misc/linux-x86/ccache/ccache -M 50G`
Then check with `prebuilds/misc/linux-x86/ccache/ccache -s` that it really got applied before you waste another bunch of hours.

**Comment by jerpelea** [comment]
How much RAM do you have?

**Comment by gerg5c42g542g2c54g52c** [comment]
@ix5 I tried doing `fastboot format userdata` instead of `fastboot -w`, but the result is the same, system unbootable. Maybe there is in fact something in this image beyond just zeros.

Turns out the ccache bundled with AOSP was used instead of the one installed on the machine. I think the issue is that it's a very old version that doesn't support the CCACHE_MAXSIZE= environment variable, so it successfully run and the other variables were applied, but not this one...

I guess I could symlink the newer version installed on my system to prebuilts/misc/linux-x86/ccache or try somehow changing the conf files which I'm guessing is the one in the cache dir, but who knows which one is used..

@jerpelea 8GB RAM + 8GB swap.

**Comment by jerpelea** [comment]
try to disable HT or add another 8GB to reduce swap usage

**Comment by gerg5c42g542g2c54g52c** [comment]
@jerpelea I disabled HT in the OS (echo 0 > /sys/devices/system/cpu/cpuX/online - for two threads out of four, I made sure I disabled threads on distinct cores) and did `make dist -j2`, it seems significantly slower (even than doing `make dist -j2` without disabling HT, I'm not sure why), but it failed with the same error. I get this error always when creating the system.img, perhaps simply memory usage cannot be lowered at that stage. Creating images is in fact the only moment when i ever get high memory usage (3-5GB of swap), otherwise there's only about 3-5GB of RAM use, 0 swapping.

It's worth noting that this build was done with a minor modification (one prebuilt apk), I couldn't yet get it to finish with this modification. Rebooting and `make dist -j3` was tried too.

I'll be trying again, but if it doesn't work, I'll do `make clobber` and do the build without that modification.

**Comment by jerpelea** [comment]
I never tried to build with less than 16 on a 8 core (bare metal)

**Comment by chris42** [comment]
Not sure if a good idea. Possibly when the underlying release changes you will need make clean. I always ended up in a mess when just trying to rebuild after the android source release changed. Which is normally be monthly... right? * cough * @jerpelea ;-)

You should really consider upgrading to 16GB for your build. I never could make an Oreo build work properly with 8GB. Even with 16GB it sometimes fails if something else tries to get lot of memory.
The thing when getting errors on low memory or a broken build is, that not always the corresponding error will be: out of memory. You will get errors that no one else can reproduce.

**Comment by jamuir** [comment]
> Only -w will wipe the partition, leaving you with no filesystem. You will want to re-format it.

`fastboot -w` will format userdata and cache as well. See `fastboot --help`.

**Comment by jamuir** [comment]
@gerg5c42g542g2c54g52c: can this be closed?

**Comment by gerg5c42g542g2c54g52c** [comment]
Yes, the signing process works. The build is stable when using unsigned userdata.img and rebuilding without cleaning to fix the `fec` error. One can wipe in TWRP and it'll work. The build takes 3 hours with 16GB of ccache cache, this is really good for such a slow machine. Thanks for all the help!

**Comment by jerpelea** [comment]
@jamuir https://github.com/sonyxperiadev/device-sony-common/commit/af2a08662a49c211b5a0ed3e0320a7b29e6078ee

enjoy
