### ISSUE TITLE
[Suzu] Bluetooth doesn't work well in sleep mode

### ISSUE THREAD

**Issue by DGoX** [sonyxperiadev/bug_tracker#316]
**Platform:** Loire
**Device:** Suzu
**Kernel version:** 4.9.144
**Android version:** 9.0.0 binaries v5

**Description**
When listening to music in a locked state through bluetooth after the ~first minute it starts to lag extremely and then interrupts. It helps to reconnect the device, but only for ~one minute.

**Symptoms**
Loss of sound lossless connection in a locked state after one (sometimes two) minute of listening to music via bluetooth.

**How to reproduce**
Turn on the bluetooth, plug in the wireless headphones, turn on the music and turn off the screen and wait about one minute.

**Comment by jamuir** [comment]
Can you post some logs?

**Comment by DGoX** [comment]
Sure @jamuir 
[alogcat.2019-02-01-07-58-06+0300.txt](https://github.com/sonyxperiadev/bug_tracker/files/2820615/alogcat.2019-02-01-07-58-06%2B0300.txt)

**Comment by kholk** [comment]
I've just engineered a possible solution for this issue, thanks to @oshmoun isolating the producer to a specific clock.

Can you please test again with this patchset?
sonyxperiadev/kernel#1985

Thanks!

**Comment by iDavLaFF** [comment]
> Can you please test again with this patchset?

This patch fix it. Thanks
