### ISSUE TITLE
[yoshino][lilac] Intermittent reboots

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#317]
**Platform:** yoshino
**Device:** lilac (g8441)
**Kernel version:** 4.9.150 sonyxperiadev/kernel@da15a42c106ebe6093aedfa0cd80fead499ea04b
**Android version:** android-9.0.0_r30

**Description**
Intermittent reboot of the phone starting 09:38 (see: [dropbox.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2804576/dropbox.tar.gz)). I was listening to music using the vanilla music player, the headphones were connected via cable. Bluetooth was not involved since it was switched off. It rebooted 3times, seamed to me like a boot loop. I pressed volume up + power to do a hard reset. After that the phone booted okay and was running stable from that on. 

I hope the files from /data/system/dropbox help finding the root cause. If not, please let me know what I could do to provide better information to find the reason for the reboots.

**Symptoms**
Intermittent reboot of the phone.

**How to reproduce**
I can't reproduce. It occurs intermittent.

**Comment by stefanhh0** [comment]
Phone rebooted again (23:24), this time I just activated flight-mode. I've attached another 
[dropbox2.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2805293/dropbox2.tar.gz).

**Comment by djselbeck** [comment]
I also had two reboots yesterday and reapplied the PR 1889 again, so far I would say it is more stable, but I need more time to verify.

**Comment by stefanhh0** [comment]
So, it is expected that PR 1889 will improve things? In the meantime I've updated my phone using the kernel 4.9.152 (sonyxperiadev/kernel@efdda8e) and the overall stability has improved a lot.
However just tried playing music over BT today which caused reboots. Well I'll just wait until PR 1889 is integrated and retry and report.

**Comment by stefanhh0** [comment]
Today my phone was really unstable, 22 reboots. It was caught in a reboot-loop. Following happened:
```
- Listening to music via cable
- Stopped music playing
- Shortly after stopping the music, phone rebooted spontaneously

- Begin of the loop: 
- The sim pin dialog showed up
- Entering the sim pin 
- Entering the phone pin
- screen comes "andoid starting..." or so
- UI loaded (with clock widget and so on)
- ~2 seconds later, the phone freezes and reboots.
```

This occurred many times repeatedly. 

It seems to be when I don't wait for the sim pin dialog showing up but instead immediately after reboot entering the phone pin and after that the sim pin then the reboot-loop was stopped. But I am not sure if that is reliable workaround or if that is just unrelated.

`Linux version 4.9.152-gefdda8efc383-dirty`(sonyxperiadev/kernel@efdda8efc383)
Todays dropbox: [dropbox3.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2823364/dropbox3.tar.gz)

**Comment by djselbeck** [comment]
I think this reboot loop problem is related to #270 .

**Comment by djselbeck** [comment]
I can reliable boot my device if I enter the DEVICE pin fast before the SIM pin dialog appears. Then I wait until the display calibration is applied (red tint for D50). Then I enter my Sim pin

**Comment by stefanhh0** [comment]
Thanks, good to know that. It is the same in my situation. 
@MarijnS95 as you suggest, I'll provide the files from `/sys/fs/pstore` next time it occurs.

**Comment by stefanhh0** [comment]
Since reverting Extended Settings -> Display white point calibration to the factory default (6000K) no boot loop reoccurred. However sometimes it still reboots. Find attached pstore content from the latest reboot: 
[pstore2.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2824848/pstore2.tar.gz)

**Comment by jerpelea** [comment]
@stefanhh0 
Please sync and build then check if the issue persists

**Comment by stefanhh0** [comment]
Yes, okay. I'll get back with my findings asap.

**Comment by stefanhh0** [comment]
Two days ago (02/17/2019 17:52 CET) a reboot occurred while navigating through the filesystem using total commander and on that reboot also a dmesg file was written, see attachment for the full logs.

**Kernel version:** 4.9.155-g6bfef4567184
**Build:** aosp_g8441-userdebug 9 PQ2A.190205.001 eng.stefan.20190215.011731 test-keys (repo_update.sh execution timestamp was around 02/15/2019 01:15 CET)

[pstore-with-dmesg.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2878280/pstore-with-dmesg.tar.gz)

**Comment by stefanhh0** [comment]
Latest recorded crash/reboot from today

**Kernel version:** 4.9.158-g2a6aed6cbb15
**Android version:** android-9.0.0_r31
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v6_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190205.001 eng.stefan.20190227.073355
**Version baseband:** 1307-7511_47.2.A.8.24
**Logfiles:** [pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2916377/pstore.tar.gz)

I am seeing that also others have such problems, like in #349 and #348.

**Comment by infixremix** [comment]
Seems to be a hardware codec issue

**Comment by russel5** [comment]
I'm build new firmware 27.02 and used it almost two days. I'm not have this issue anymore.
But I'm flash via newflasher Oreo firmware 47.1.A.16.20 and setup it with my sim. Only after that install my build and not have this issue

**Comment by jerpelea** [comment]
I mentioned several times that you should use the 47.1.A.16.20 SW before flashing AOSP. For now please do not flash any 47.2.x.xxx.xxx releases because are still AOSP stability issues on the new base

**Comment by infixremix** [comment]
Alright will pass this on. Sorry for the hassle

**Comment by stefanhh0** [comment]
Okay thanks Alin, I understand, I'll remain on 47.1.A.16.20 as well as long as aosp and the newer baseband are not working that good together.  

After reverting (booting with sim) and flashing a fresh aosp-build with following configuration a crash/reboot ocurred.

**Kernel version:** 4.9.158-gf426cb9a7677
**Android version:** android-9.0.0_r31
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v6_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190205.001 eng.stefan.20190228.191439
**Version baseband:** 1307-7511_47.1.A.16.20
**Build includes latest commit:** sonyxperiadev/device-sony-yoshino@d53121945d0b32e13eb8c9417e9d4ba14afbc80c
**Logfiles:** [pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2917422/pstore.tar.gz)

**Comment by jerpelea** [comment]
one of the instability causes was identified in the zram and the offending patches were reverted 
please rebuild the kernel and check if you can replicate the reported issues

**Comment by stefanhh0** [comment]
@jerpelea I am testing this during the next days and will report my findings. My phone is already on a fresh aosp-build. Until now no intermittent reboot occurred yet, but it is a little bit to early to be sure that it is now stable...

**Comment by stefanhh0** [comment]
Over the last two days my phone ran pretty stable. I have posted the only crashes in #348. Therefore I just close this ticket, since the zram fixes have increased the overall stability a lot for me. Good job!
