### ISSUE TITLE
[yoshino][maple] excessive bluetooth activity

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/bug_tracker#318]
**Platform:** yoshino
**Device:** maple (dual-sim)
**Kernel version:** 4.4.168-g44235a04f24d
**Android version:** 8.1
**odm image:** 8.1.0_4.4_yoshino_v16

**Description**
`/odm/lib64/hw/android.hardware.bluetooth@1.0-impl-qti.so` appears to be stuck in some type of loop and emits the same sequence of logcat messages about every 4-5 seconds (see below).

I see this behaviour only after flashing an open-gapps package on top of a sony image ~(and then wiping userdata & cache)~.  **I do not see this behaviour in a vanilla sony build**.  It may be that the additional apps are exposing some type of race condition in the qti bluetooth implementation.

```
01-01 07:18:40.320 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Received IBS_WAKE_IND: 0xFD
01-01 07:18:40.322 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): SerialClockVote: vote for UART CLK ON
01-01 07:18:40.327 E/vendor.qti.bluetooth@1.0-wake_lock(  665): Acquire wake lock not initialized
01-01 07:18:40.328 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Writing IBS_WAKE_ACK
01-01 07:18:40.330 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Received IBS_WAKE_IND: 0xFD
01-01 07:18:40.331 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Writing IBS_WAKE_ACK
01-01 07:18:40.414 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
01-01 07:18:40.416 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): SerialClockVote: vote for UART CLK OFF
01-01 07:18:40.417 E/vendor.qti.bluetooth@1.0-wake_lock(  665): Release wake lock not initialized/acquired
01-01 07:18:40.426 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Received IBS_WAKE_IND: 0xFD
01-01 07:18:40.427 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): SerialClockVote: vote for UART CLK ON
01-01 07:18:40.429 E/vendor.qti.bluetooth@1.0-wake_lock(  665): Acquire wake lock not initialized
01-01 07:18:40.430 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Writing IBS_WAKE_ACK
01-01 07:18:40.830 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
01-01 07:18:40.831 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): SerialClockVote: vote for UART CLK OFF
01-01 07:18:40.833 E/vendor.qti.bluetooth@1.0-wake_lock(  665): Release wake lock not initialized/acquired
01-01 07:18:45.221 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Received IBS_WAKE_IND: 0xFD
01-01 07:18:45.223 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): SerialClockVote: vote for UART CLK ON
01-01 07:18:45.228 E/vendor.qti.bluetooth@1.0-wake_lock(  665): Acquire wake lock not initialized
01-01 07:18:45.229 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Writing IBS_WAKE_ACK
01-01 07:18:45.730 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
01-01 07:18:45.730 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): SerialClockVote: vote for UART CLK OFF
01-01 07:18:45.731 E/vendor.qti.bluetooth@1.0-wake_lock(  665): Release wake lock not initialized/acquired
01-01 07:18:50.395 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Received IBS_WAKE_IND: 0xFD
01-01 07:18:50.396 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): SerialClockVote: vote for UART CLK ON
01-01 07:18:50.400 E/vendor.qti.bluetooth@1.0-wake_lock(  665): Acquire wake lock not initialized
01-01 07:18:50.401 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Writing IBS_WAKE_ACK
01-01 07:18:50.712 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
01-01 07:18:50.714 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): SerialClockVote: vote for UART CLK OFF
01-01 07:18:50.716 E/vendor.qti.bluetooth@1.0-wake_lock(  665): Release wake lock not initialized/acquired
01-01 07:18:50.731 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Received IBS_WAKE_IND: 0xFD
01-01 07:18:50.732 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): SerialClockVote: vote for UART CLK ON
01-01 07:18:50.734 E/vendor.qti.bluetooth@1.0-wake_lock(  665): Acquire wake lock not initialized
01-01 07:18:50.735 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Writing IBS_WAKE_ACK
01-01 07:18:50.899 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
01-01 07:18:50.901 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): SerialClockVote: vote for UART CLK OFF
01-01 07:18:50.902 E/vendor.qti.bluetooth@1.0-wake_lock(  665): Release wake lock not initialized/acquired
01-01 07:18:54.883 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Received IBS_WAKE_IND: 0xFD
01-01 07:18:54.883 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): SerialClockVote: vote for UART CLK ON
01-01 07:18:54.886 E/vendor.qti.bluetooth@1.0-wake_lock(  665): Acquire wake lock not initialized
01-01 07:18:54.887 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Writing IBS_WAKE_ACK
01-01 07:18:54.932 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
01-01 07:18:54.933 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): SerialClockVote: vote for UART CLK OFF
01-01 07:18:54.933 E/vendor.qti.bluetooth@1.0-wake_lock(  665): Release wake lock not initialized/acquired
01-01 07:18:54.936 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Received IBS_WAKE_IND: 0xFD
01-01 07:18:54.936 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): SerialClockVote: vote for UART CLK ON
01-01 07:18:54.937 E/vendor.qti.bluetooth@1.0-wake_lock(  665): Acquire wake lock not initialized
01-01 07:18:54.937 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Writing IBS_WAKE_ACK
01-01 07:18:55.388 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
01-01 07:18:55.390 I/vendor.qti.bluetooth@1.0-ibs_handler(  665): SerialClockVote: vote for UART CLK OFF
01-01 07:18:55.391 E/vendor.qti.bluetooth@1.0-wake_lock(  665): Release wake lock not initialized/acquired
```
Full logcat here: 
[logcat-full.txt](https://github.com/sonyxperiadev/bug_tracker/files/2809804/logcat-full.txt)

**Symptoms**
The main symptom is excessive logcat spam.  I have also noticed some bt audio issues on maple (sound dropping sporadically for 1-2 seconds), but it's unclear if they are related to this.

**How to reproduce**
see above.

(edit:  wiping userdata and cache is not necessary)

**Comment by MarijnS95** [comment]
Seeing the same spam on Discovery and Akatsuki. The former one being without opengapps (or anything else). Both run a locally compiled Omnirom 9 image on kernel 4.9 and blobs v5.
If I remember correctly, this is one of the `In-Band Switching` messages that should be captured and dealt with elsewhere, but instead end up in the bluetooth hal. On the other hand, the HAL seems to vote for turning the UART clock on and off correctly, which is what's supposed to happen. In that case, these are just debug messges that should be hidden.

**Comment by jamuir** [comment]
thanks for confirming you see the same logs.

It's possible they are normal debug messages.  However, in that case, I don't understand why they would be absent from my vanilla sony maple build (although you said you see them in a vanilla discovery build).

**Comment by jamuir** [comment]
@jerpelea :  are those repeated log messages normal?  do you see them?

**Comment by oshmoun** [comment]
Noticed these props in crosshatch sources:
https://android.googlesource.com/device/google/crosshatch/+/master/device.mk#364
Since these props are not set currently, not sure what the hal implementation defaults to.

**Comment by jerpelea** [comment]
@jamurir I will silence them in v6

**Comment by jamuir** [comment]
Thanks.  Don't forget about oreo (the logs I posted are from 8.1 with oem
v16).

It would be nice to know what is triggering these logs (i.e. why do we see
them in some builds and not others).

**Comment by DGoX** [comment]
@jerpelea also fix bluetooth on suzu please

**Comment by jamuir** [comment]
@jerpelea :  do you know what is triggering these logs?  why do we see them in some builds but not others?

**Comment by jerpelea** [comment]
@jamuir I cant replicate reliably

**Comment by jamuir** [comment]
ok.  thanks for your reply.

Here is what I've found with oreo builds:

1. in a vanilla Sony Open devices build, the bt logs are not generated.
2. if you flash a nano opengapps package on top of a vanilla Sony Open devices build and then wipe the device, then the bt logs are generated.

**Comment by jamuir** [comment]
@jerpelea :  note that the logs stop when the screen turns off.

**Comment by oshmoun** [comment]
@jamuir can you try disabling bluetooth scanning? it's an option under location

**Comment by jamuir** [comment]
good idea.

Unfortunately, it is already disabled.  Toggling it on and off does not change the log spew.

Are the logs supposed to disappear if `android.hardware.bluetooth@1.0-impl-qti.so` successfully acquires a wake-lock?  Maybe that is the cause.

**Comment by oshmoun** [comment]
@jamuir actually, the hal is successfully acquiring a wakelock
i can see `hal_bluetooth_lock` being acquired here

**Comment by jerpelea** [comment]
I will see what I can do

**Comment by jamuir** [comment]
After some more digging, I think the bt hal is working normally.

The images I examined (the ones with the bt log spam) had no network connectivity.  I just noticed that after I connect to wifi, the bt activity stops.

What I think is happening is that one the google apps is repeatedly doing bt scans, possibly in an attempt to determine a location.  After the network comes up, the bt scans stop (possibly because it now has a better way to determine location).

If you leave network disconnected and toggle "Location" off and on (under Settings \ Security & Location \ Location), then you can make the bt logs stop and start.

@jerpelea I don't think there is anything broken here (and there is no need to create a debug hal).  I will close.

@MarijnS95 I don't understand why you are seeing the bt log spam without Google Play services.  Maybe you have some other location provider in your Pie images.

**Comment by MarijnS95** [comment]
@jamuir I cannot find a reliable wifi+location on/off state to trigger the spam. Both devices have bluetooth scanning "turned off".
Unfortunately, they are very inconsistent on Akatsuki; sometimes don't see them for over 5 minutes
The logs occur pretty consistently with `NuPlayerDriver: notifyListener_l` on Discovery, though.

It would indeed be very interesting to know who and why is requesting these consecutive sleeps and wakes. Best guess is that it's the BT chip itself (or something along the pipeline going there). This could be normal behaviour though.
