### ISSUE TITLE
[TAMA][AKARI][9.0][4.9] Higher battery consumption in IDLE than STOCK with many Apps

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#320]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9.152
**Android version:** 9.0

I'm using the App "AccuBattery" to measure the energy consumption while idle.
On stock PIE it is -18mA. (Jan 2019 Firmware)
On AOSP it is -55mA.

The STOCK has every APP i use to work with.
On AOSP there is only Magisk, TWRP, Pico GAPPS and Chrome.
The same behaviour exists on OmniROM.

Let me know if I can provide you with some logs or something you need. :)

I am now on OmniROM (build 22. april) and lost 23% at night after 8h (3%/h) with 7h deep sleep.
I add the files from today (2019-05-17-08_15)
[BetterBatteryStats-2019-05-17_080651866.txt](https://github.com/sonyxperiadev/bug_tracker/files/3190117/BetterBatteryStats-2019-05-17_080651866.txt)
[dmesg-2019-05-17_080652176.txt](https://github.com/sonyxperiadev/bug_tracker/files/3190118/dmesg-2019-05-17_080652176.txt)
[logcat-2019-05-17_080652075.txt](https://github.com/sonyxperiadev/bug_tracker/files/3190119/logcat-2019-05-17_080652075.txt)
[batterybugreport.zip](https://github.com/sonyxperiadev/bug_tracker/files/3190121/batterybugreport.zip)

New logs
87% deep sleep
1,2%/h in the night
9% battery loss
7 h 47 m 8 s timespan
Could that be because I have 5 email accounts with 30min polling each
[batterybugreport-2019-05-18_085357588.zip](https://github.com/sonyxperiadev/bug_tracker/files/3193774/batterybugreport-2019-05-18_085357588.zip)
[BetterBatteryStats-2019-05-18_091246663.txt](https://github.com/sonyxperiadev/bug_tracker/files/3193775/BetterBatteryStats-2019-05-18_091246663.txt)
[dmesg-2019-05-18_091246813.txt](https://github.com/sonyxperiadev/bug_tracker/files/3193776/dmesg-2019-05-18_091246813.txt)
[logcat-2019-05-18_091246702.txt](https://github.com/sonyxperiadev/bug_tracker/files/3193777/logcat-2019-05-18_091246702.txt)

**Comment by DGoX** [comment]
The same on suzu

**Comment by mirh** [comment]
Still a thing?

**Comment by MartinX3** [comment]
It seems so
There is the assumption that stock has a more aggressive battery saving.

**Comment by mirh** [comment]
Then if it even affected Loire, I guess like this could even explain as well some bad numbers I was getting with kagura.

**Comment by oshmoun** [comment]
is this still relevant?

**Comment by MartinX3** [comment]
I think that would require a new battery test with the august stock and the SODP august changes or so.
We've got performance updates merged which in theory should extend the battery live at the same tasks.
