### ISSUE TITLE
[TAMA][AKARI][9.0][4.9] Backcamera lacks full camera 2 api support (Level_3 missing)

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#321]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9.152
**Android version:** 9.0

I checked the camera 2 api with the app "Camera2 probe" from Google Play Store.
Missing features:
- LEVEL_3
- Auto focus EDOF

Will this get added?

According to Google Android Docs
> LEVEL_3: These devices support YUV reprocessing and RAW image capture, along with additional output stream configurations.

Level_3 is supported since HALv3.2.
The new snapdragon 845 should be able to support it in hardware.

**Comment by jerpelea** [comment]
@MartinX3 
v8 is released !
please rebuild and test

**Comment by oshmoun** [comment]
tested, both "Level_3" and "Auto focus EDOF" are still reported missing

**Comment by MartinX3** [comment]
I can confirm it on my tama akari xz2.

**Comment by sraase** [comment]
I can confirm as well, and it will need some looking into. Same for the front camera.

**Comment by sraase** [comment]
The Tama back camera uses a regular auto-focus system, so EDOF should not be reported at all. Please correct me if I am mistaken here.

The LEVEL_3 issue runs deeper than I expected. As far as I can tell, the camera platform always reports FULL in the version we use, independent of the sensor driver. Obviously, this also affects the front camera.

**Comment by MartinX3** [comment]
Is this supported or possible @sraase ?
https://developer.android.com/reference/android/hardware/camera2/CameraMetadata.html#REQUEST_AVAILABLE_CAPABILITIES_YUV_REPROCESSING
According to
https://source.android.com/devices/camera/versioning
YUV and RAW are the main things in LEVEL_3.

**Comment by sraase** [comment]
My Apollo reports RAW, YUV_REPROCESSING and PRIVATE_REPROCESSING.
To my knowledge, that support has been there from the beginning.
I just tested PRIVATE_REPROCESSING - works fine.

**Comment by MartinX3** [comment]
Oh, that's weird why it still reports a missing LEVEL_3.
maybe because of the not good declared `along with additional output stream configurations` in the documentation.

**Comment by sraase** [comment]
I use "adb shell -n dumpsys media.camera | less".
The decision on whether a camera is LEVEL_3 is not done by Android.
On my phone, "Camera2 Probe" correctly reports both types of REPROCESSING.

**Comment by MartinX3** [comment]
Thank you `adb shell -n dumpsys media.camera | less` is just perfect.

Sadly "Camera2 Probe" doesn't show me a REPROCESSING section on my akari or YUV/PRIVATE.

Luckily "https://play.google.com/store/apps/details?id=com.camera2.test" shows me more useful informations, similar to the shell command you gave me. :)

**Comment by MartinX3** [comment]
Now I am very unsure if we can close this ticket or not.

**Comment by sraase** [comment]
Maybe I am using a different version of the Camera2 Probe app. It doesn't matter though, if it is shown in dumpsys, then it is there.

I think this ticket should stay open for now, since the issue is real - just that I can't easily cook up a solution.

**Comment by jerpelea** [comment]
please retest on Android 10 and vendor v3 release then open a ticket for Android 10
