### ISSUE TITLE
[TAMA][AKARI][9.0][4.9] Mobile Network Delay

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#322]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9.152
**Android version:** 9.0

It taks a bit to get a cellular connection, or internet or to be ably to unlock the simcard (tells me the pin is wrong but doesn't reduce my amount of tries).

**Comment by jerpelea** [comment]
it looks normal
