### ISSUE TITLE
XA2[GAPPS SPLASH SCREEN]

### ISSUE THREAD

**Issue by infixremix** [sonyxperiadev/bug_tracker#323]
**Platform:*SDM630* 
**Device:*PIONEER [XA2]* 
**Kernel version:*4.9* 
**Android version:*9.0* 

**Description**
Flashing gapps causes the device to get stuck on splash screen even after removing priv-app whitelist. Cant get logs on  the splash so to be truthful I don't know how this is gonna help but I thought I would tell you.

**Symptoms**
stuck on splash after flashing gapps.

**How to reproduce**
Flash aosp and then flash gapps.

**Comment by MartinX3** [comment]
Please write in the terminal "adb shell logcat > logcat.log" (google plattform tools are needed)
The command will wait for a device.
Connect your XA2 with your computer and boot it into the system.
It should now create the file.

**Comment by infixremix** [comment]
im not that much of a noob. Ill make and engineering build to try and get logs.

**Comment by infixremix** [comment]
Closing issue gapps issue not yours.
