### ISSUE TITLE
[dora] userdata preformatted incorrectly during build process

### ISSUE THREAD

**Issue by b1mt3** [sonyxperiadev/bug_tracker#325]
**Platform:** tone
**Device:** dora
**Kernel version:** 4.9
**Android version:** 8.1

**Description**
Flashing the images onto **F8132** model (**64GB**) results in /data being formatted at only 32GB

**Symptoms**
/data is displaying 32GB

**How to reproduce**
Build the latest branch (_android-8.1.0_r52_) and flash the images. Formatting the userdata to ext4 results in being stuck at a boot animation.

**Comment by jerpelea** [comment]
@b1mt3 please provide the output from fastboot getvar all from your device

**Comment by b1mt3** [comment]
Here you go @jerpelea 
```
(bootloader) version:0.5
(bootloader) max-download-size:	0x10000000
(bootloader) partition-type:cache:ext4
(bootloader) partition-size:cache:	 0x10000000
(bootloader) partition-type:userdata:ext4
(bootloader) partition-size:userdata:	 0xc72400000
(bootloader) partition-type:system:ext4
(bootloader) partition-size:system:	 0x1d3800000
(bootloader) secure:no
(bootloader) version-baseband:1300-5317_41.3.A.2.149
(bootloader) version-bootloader:1299-4832 S1_Boot_MSM8996_LA2.0_O_204
(bootloader) serialno:CB512AG1NV
(bootloader) product:F8132
all: 
Finished. Total time: 0.133s
```
Thank you for the assistance and your time!

**Comment by jerpelea** [comment]
fixed

**Comment by b1mt3** [comment]
Confirmed,
thank you very much for your help, @jerpelea
