### ISSUE TITLE
[dora] proximity sensor issue

### ISSUE THREAD

**Issue by b1mt3** [sonyxperiadev/bug_tracker#328]
**Platform:** tone
**Device:** dora
**Kernel version:** 4.9
**Android version:** 8.1

**Description**
Proximity sensor is not operational

**Symptoms**
When on call, bringing the phone close to ear doesn't trigger the display to turn off.

**How to reproduce**
Launch Phone app, dial a number and block the sensor with a finger or just bring the device to the ear.

**Comment**
Checked the light sensor, and it is operational: adaptive brightness works as expected.

**Comment by jerpelea** [comment]
Android 8.1 and kernel 4.9 are not a a supported combination

I tested android 9 with kernel 4.9 and Proximity works fine 

you can use PhoneTester apk to test all sensors

**Comment by b1mt3** [comment]
Hello, @jerpelea 
Unfortunately, the issue persists: since I confirmed via PhoneTester, the phone rebooted itself twice, and since then the app reports 'Not supported' on all the sensors.
I could provide the screenshot, but the content will not provide more than my words: plain 'Not supported' for all sensors.
Could you suggest any analysis approach?

**Comment by jerpelea** [comment]
@b1mt3 the issue is caused by the sensor service startup.
It looks like it sometimes starts before the DSP is up and we will have to tweak the init script

**Comment by b1mt3** [comment]
@jerpelea I see.
Thank you for the insight. Do you think I might be able to assist and sort this 'hiccup' by myself? Or I'd better wait for your call?

**Comment by jerpelea** [comment]
those are the init script 
https://github.com/sonyxperiadev/device-sony-common/tree/master/rootdir/vendor/etc/init
you can always help if you have time

**Comment by b1mt3** [comment]
@jerpelea 
Leave it to me then, I'll see it done. And thank you for your time @jerpelea
