### ISSUE TITLE
[yoshino][lilac] None default display white point calibration causes reboots

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#335]
**Platform:** yoshino
**Device:** lilac
**Kernel version:** 4.9.154-ge17b3925fe2a-dirty
**Android version:** android-9.0.0_r31
**Version baseband:** 1307-7511_47.2.A.2.33
**Latest commit after repo_sync.sh:** sonyxperiadev/device-sony-suzu@f4661f74803ac0ded9901a55ebe1fe32f9c51e36

**Description**
When setting e.G. "D65: 6500K" in "Extended settings" -> "Display white point calibration" the phone freezes and reboots often.

**Symptoms**
After entering the device PIN system hangs and reboots.

**How to reproduce**
- Set: "Extended settings" -> "Display white point calibration" -> "D65: 6500K"
- Restart
- Wait for Enter Sim PIN Dialog -> Enter PIN
- Wait for phone connected to telecommunication service provider
- Enter device PIN
- After a short time (< 10s) hang and reboot

The bug is not 100% reproducible. I've tried many times, however I think I never had to repeat aboves procedure more than 5 times to run into this issue. The behavior seems to be triggered by some sort of race-condition/timing behavior (just a guess out of the wild). Most of the times no dmesg file can be found in `/sys/fs/pstore`. But sometimes it succeeds writing the dmesg file. I've attached both types of occurrences, the one with dmesg file and the one without dmesg file. The adb_logcat.logs contain the output from `adb logcat 2>&1 | tee adb_logcat.log` beginning with the device boot until the point when the phone freezed and rebooted.

**Files**
[logfiles_with_dmesg.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2849395/logfiles_with_dmesg.tar.gz)
[logfiles_without_dmesg.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2849396/logfiles_without_dmesg.tar.gz)

**Comment by MarijnS95** [comment]
I have recently done some alterations to PCC:
https://github.com/sonyxperiadev/packages_apps_ExtendedSettings/pull/41

**Comment by stefanhh0** [comment]
Okay, I'll give it try. Did a: `git revert -m 1 da15a42c106ebe6093aedfa0cd80fead499ea04b`and rebuilding the bootimage now.

**Comment by stefanhh0** [comment]
For reference, this issue was afaik first reported in #270.

**Comment by jerpelea** [comment]
@stefanhh0 please test on the latest code

**Comment by stefanhh0** [comment]
@jerpelea thanks for getting back to me on this. Unfortunately it is still reproducible. See the attached logfiles. The adb logcat is from starting the phone until the crash. This time dmesg file was written on the first crash and I didn't have to repeat the procedure. The crash itself occurred this time on the first attempt after switching to D65: 6500K and rebooting (I have done it as outlined in the 'How to reproduce' section above).

Used Software:
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v6_yoshino.img
**Kernel Version:**  4.9.158-gcaee277f4487
**Build:** aosp_g8441-userdebug 9 PQ2A.190205.001 eng.stefan.20190222.201553 test-keys
**Version baseband:** 1307-7511_47.2.A.2.33

**Logfiles:** [adb_logcat_pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2896555/adb_logcat_pstore.tar.gz)

**Comment by stefanhh0** [comment]
Just for the sake of completeness I've also checked whether this issue might have been also fixed with The latest zram fix but that is not the case. It is still reproducible on following build:

**Kernel version:** 4.9.158-g40f2ede5e12a
**Android version:** android-9.0.0_r31
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v6_yoshino.img
**Build:** aosp_g8441-eng 9 PQ2A.190205.001 eng.stefan.20190301.194549
**Version baseband:** 1307-7511_47.1.A.16.20

Sometimes dmesg is missing, the reason for that is that after the phone freezes, not a single reboot occurs but two. At least I interpret it that way since the vibrator is activated twice in a short distance before the phone boots up normally. Sometimes  when the vibrator is activated once on reboot also a dmesg is available. Does that makes sense or am I wrong with my assumption here? Currently I don't manage it to have just a single boot, therefore dmesg is always missing...

Despite the fact that dmesg is missing, are the pstore files anyhow useful for you? Hope so.
[pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2921458/pstore.tar.gz)

**Comment by jerpelea** [comment]
the bug is not replicable after the devices are switched to SDE

**Comment by stefanhh0** [comment]
Good to hear that, I'll give it a try as soon as v8 is available, thanks for the fix and letting me know.

**Comment by stefanhh0** [comment]
@jerpelea with 
**Kernel version:** 4.9.168-g4ebcb68cc743
**Android version:** android-9.0.0_r35
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190405.003 eng.stefan.20190418.191851
**Version baseband:** 1307-7511_47.1.A.16.20

Extended Settings no longer contains the white point calibration entry, is that intended? If so, is there any other way to change white point calibration in order to test it?
