### ISSUE TITLE
[Tama][Akatsuki] Bottom speaker does not cover lower frequency spectrum

### ISSUE THREAD

**Issue by MarijnS95** [sonyxperiadev/bug_tracker#336]
**Platform:** Tama
**Device:** Akatsuki
**Kernel version:** 4.9
**Android version:** 9.0.0 (Omnirom)

**Description**
The bottom speaker produces, despite it's relative larger size related to the top one, no low-frequency sounds. It has been confirmed by a stock Akatsuki user that it's opposite on stock, where the bottom speaker produces more than the top one (however, it is unknown if the top speaker is not supposed to cover any of the low frequency spectrum). For a proper stereo experience, both speakers should produce more or less the same, or at least as much as they're able to.

**Symptoms/How to reproduce**
Play music, and hold your ear to both speakers. Notice how the top speaker produces more low-frequency sounds, which are effectively missing from the bottom one.

**Comment by MarijnS95** [comment]
@richardtullberg Tagging you since you seem to be the audio/calibration expert. I couldn't find much in the >3000 line mixer_paths, so assume this is an acdb dsp calibration issue.

**Comment by richardtullberg** [comment]
Hi @MarijnS95,
Thanks for investigating the issue. I have also done a fast check in the mixer paths and other areas and I think you are right.
I think I know what the issue is and will check it out as soon as possible and if the issue is what I think it is I will come back to you about it.

BR Richard

**Comment by richardtullberg** [comment]
Hi @MarijnS95 

could you test this patch?
https://github.com/sonyxperiadev/device-sony-tama/commit/fe91a08158cfdaca4ee32f001501b40bfec1faf5

BR Richard

**Comment by MarijnS95** [comment]
@richardtullberg I'll try that as soon as I get in an environment where I can play loud music, later this afternoon.

Thanks a ton in advance :smile:

**Comment by MarijnS95** [comment]
Hi @richardtullberg, been going back and forth a lot between `15` and `124`, and the speakers definitely sound way more equal on the latter. However, it also sounds way more "flat" and "thin", whereas `15` feels much more natural and "warm" in some way.
In other words, on acdb 15 I have the idea the top speaker sounds close to a proper pair of headphones, (when listening closely), whereas 124 misses parts of the frequency spectrum and flattens details out.

Are there any other calibrations I could try?

**Comment by richardtullberg** [comment]
@MarijnS95, just to go back to the initial issue, is the lower frequencys that were missing in the bottom speaker still missing or do you think it is better?
Or clarify more, is the sound of this calibration setting equal or close to the sound of a Xperia Stock Akatsuki sounds?

BR Richard

**Comment by MarijnS95** [comment]
The bottom speaker definitely puts out more of the lower frequencies, just about as much or slightly less than the top speaker.

I have never used stock on the Akatsuki, and rather not go through the time-consuming process of backing up this daily driver, flashing stock, and hoping to be able to audibly compare it with sound produced on aosp.
However, I am able to use acdb files from stock (end of 2018 atm) and those sound completely different, up to the point that I have no idea what these phone speakers are supposed to sound like. In any case, these sound like having less bass/warmth than the top speaker on aosp `15`, with both speakers getting close to sounding the same (just like aosp id `124`, the bottom speaker sounds ever so slightly less clear and bassy than the top one).

**Comment by MarijnS95** [comment]
@richardtullberg Looks like I forgot to tag you.
No hurry, no worry. Just a heads-up :wink:
