### ISSUE TITLE
[Yoshino][Poplar, Maple]Camera noise on Yoshino platform.

### ISSUE THREAD

**Issue by sjllls** [sonyxperiadev/bug_tracker#337]
[**Platform:**](url)  Yoshino
**Device:**  Poplar, Maple
**Kernel version:** 4.9
**Android version:** 9.0.0_r31
**OEM version:** V5

**Description**
IMX400 on the Yoshino platform has a lot of red and green noise when taking photos, whether it is daytime or night.. Especially in the dark area.
I tested system-camera and Gcam, both of them have this issue.

**Symptoms**
Noise will increase as the light dims. The photo taking in night is so bad.
I am not sure this is related to AOSP or IMX400’s DRAM.  I don't meet this issue on suzu.

**How to reproduce**
Build AOSP, and take a photo. Enlarge photo to 100% size. You will see the red and green noise.

**Photo No.1, system camera.**
![img_19700815_054213](https://user-images.githubusercontent.com/29087038/52773783-b99f2680-3076-11e9-832f-b03b94796fa1.jpg)

**Enlarge it**
![img_19700815_054213](https://user-images.githubusercontent.com/29087038/52774052-5f529580-3077-11e9-86d0-f64954dc16f5.png)

**Photo No.2, system camera.**
![img_19700815_054333](https://user-images.githubusercontent.com/29087038/52774083-7b563700-3077-11e9-9180-60e494cbd783.jpg)

**Enlarge it No.1**
![1](https://user-images.githubusercontent.com/29087038/52774171-9de85000-3077-11e9-8cae-8ca0f7d8f4ee.jpg)

**Enlarge it No.2**
![2](https://user-images.githubusercontent.com/29087038/52774386-033c4100-3078-11e9-8408-e8c838d7d7d8.jpg)

**Comment by jerpelea** [comment]
Hi,
Each device has a different sensor and Each sensor has a different noise level.

It is normal for the noise to increase when there is less light and usually it is removed by post processing. 
You can remove the nose with any 3rd party app

Regards
Alin
