### ISSUE TITLE
[Documentation] Build guide Oreo 8.1 out-of-date

### ISSUE THREAD

**Issue by chris42** [sonyxperiadev/bug_tracker#338]
**Platform:** All
**Device:** All
**Kernel version:** 4.4
**Android version:** 8.1

**Description**
Build guides for Oreo 8.1 still on December 2018 Patch Level.

**Comment by jerpelea** [comment]
The build guide is in sync wiht the latest release for Android 8.1

https://source.android.com/setup/start/build-numbers

**Comment by chris42** [comment]
Sorry, missed, that the Nexus 5X, 6P base is EOL. Hence There will be no more guaranteed security updates for it. Following that we will not have security updates for Oreo 8.1 anymore. Thought it would be worthwhile to note that here.

**Comment by abioteau** [comment]
This is right for Nexus 5X and 6P. But there is newest security updates for Pixel C: android-8.1.0_r61

@jerpelea, it is possible to update on this latest Oreo AOSP tag?

**Comment by jerpelea** [comment]
@abioteau Pixel C is a tablet and it may not have critical fixes for phones
