### ISSUE TITLE
Vibrator service 

### ISSUE THREAD

**Issue by infixremix** [sonyxperiadev/bug_tracker#339]
**Platform:*sdm630* 
**Device:*xa2* 
**Kernel version:*4.9* 
**Android version:*9.00* 

**Description**
Hi ive been using your trees and repos to build lineage os however I keep getting this error on boot .
I have searched absolutely everywhere theres nothing. I understand if you don't want to help as im building lineage os but you guys know the repos much better than me and could possibly know why this is happening.
`.
05-13 05:18:41.410  1417  1417 E         : Vibrator device does not exist. Cannot start vibrator

05-13 05:18:41.410  1417  1417 E VibratorService: vibrator_open failed: -19

05-13 05:18:41.411  1417  1417 E VibratorService: Passthrough failed to open legacy HAL.

05-13 05:18:41.411  1417  1417 E android.hardware.vibrator@1.0-service: Could not get passthrough implementation for android.hardware.vibrator@1.0::IVibrator/default.

05-13 05:18:41.598  1210  1210 W ServiceManagement: Waited one second for android.hardware.vibrator@1.0::IVibrator/default. Waiting another...`

full logs
https://gist.github.com/infixremix/ad5f1896c8a9a76f63a7e429783ffa9b
dmesg
https://gist.github.com/infixremix/ab42c6cba42b96279aafdd8d63441fe3

**Symptoms**
Its not booting.

**Comment by skris08** [comment]
@infixremix You might have noted that, Vibrator is not physically connected to the device.
_05-13 05:18:41.410 1417 1417 E : Vibrator device does not exist. Cannot start vibrator

05-13 05:18:41.410 1417 1417 E VibratorService: vibrator_open failed: -19_

If you want to bypass the service failure, by adding 

disabled
oneshot 

parameters to the service rc file.
