### ISSUE TITLE
[maple] Notification LED does not blink for notifications

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#34]
**Platform:** yoshino
**Device:** maple
**Kernel version:** 4.4 (9c6cb35, manually built on 13 Nov)
**Android version:** 8.0.0
**Firmware version:** v05

**Description**
The notification LED does not blink for notifications.

**Symptoms**
The notification LED seems to be working for charging, but not for applications that use it for notifying the user.

**How to reproduce**
Use any application that uses the notification LED (various messaging apps etc.)

**Logs**
N/A

**Comment by kholk** [comment]
Solved with PR https://github.com/sonyxperiadev/kernel/pull/1517

**Comment by jerpelea** [comment]
fixed
