### ISSUE TITLE
[suzu] Freezes and restarts.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [sonyxperiadev/bug_tracker#340]
**Platform:** loire
**Device:** suzu
**Kernel version:** 4.9
**Android version:**  9.0.0_r31
Latest firmware and vendor v5. Built feb 16.

**Description**
The device freezes at seemingly random moments when performing tasks like tap holding to copy in Firefox or swiping.

It also sometimes restarts, I think it only happened while the screen was off.

**Comment by jerpelea** [comment]
one of the instability causes was identified in the zram and the offending patches were reverted 
please rebuild the kernel and check if you can replicate the reported issues

**Comment by jerpelea** [comment]
@gerg5c42g542g2c54g52c I can't reproduce the error on lilac with HEAD^
