### ISSUE TITLE
[suzu] USB tethering uses celullar data even tough wifi is available.

### ISSUE THREAD

**Issue by cloudyfuel** [sonyxperiadev/bug_tracker#341]
**Platform:** loire
**Device:** suzu
**Kernel version:** 4.9
**Android version:** 9.0.0_r31
Latest firmware and vendor v5. Built feb 16.

**Description**
Just turned on USB tethering and started downloading some big files, a minute later I'm notified that my data plan was used out. ~100Mb/s WiFi was connected all this time, the UI showed full signal for it, I tried disabling data on the phone and opening a webpage in a browser on the phone, opened quickly no prob. Tried the same on the USB tethered device, internet doesn't work. Tried disabling and enabling again USB tethering (without re-enabling data), it works. Sigh.

**Comment by harryharryharry** [comment]
Just tested on kugo, can confirm.

**Comment by gerg5c42g542g2c54g52c** [comment]
There seem to be other problems with wifi. If using the phone in a distant location from the access point it losses wifi signal (one moment the icon shows half the signal, the other no wifi) or wifi works at one moment just for the icon to show the X indicating no signal, even though the signal is there (disabling and enabling wifi or simply waiting works).
