### ISSUE TITLE
[yoshino][lilac] Crash on shutdown and reboot

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#343]
**Platform:** yoshino
**Device:**  lilac
**Kernel version:** 4.9.158-gcaee277f4487 
**Android version:** android-9.0.0_r31
**Build:** aosp_g8441-userdebug 9 PQ2A.190205.001 eng.stefan.20190222.201553
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v6_yoshino.img

**Description**
The shutdown and reboot isn't done cleanly when USB is connected and USB debugging is activated.  

**Symptoms**
On shutdown the system does not always boot into flashtool mode (green led) but crashes and boots up normally. After that files in /sys/fs/pstore can be found.

On rebooting the phone the vibrator is activated twice (that means two reboots, correct?) after the system was back online, files have been in  /sys/fs/pstore. The reboot failure is not as good reproducible as the shutdown problem. It required many attempts and I haven't found a recipe how to reproduce it more reliable. 

**How to reproduce**
Shutdown:
- Bootup phone
- Enter SIM PIN
- Wait for telco provider connect
- Enter device PIN
- Connect the phone via usb
- Enable usb debugging
- Run adb logcat on the host and wait some seconds (~10s) until the majority of phone start/logging is done
- Trigger regular shutdown via GUI 
- crash and reboot occurs

Reboot:
- Bootup phone
- Enter SIM PIN
- Wait for telco provider connect
- Enter device PIN
- Connect the phone via usb
- Enable usb debugging
- Run adb logcat on the host and wait some seconds (~10s) until the majority of phone start/logging is done
- Trigger regular restart via GUI 
- crash and reboot occurs

**Logfiles**
Shutdown: [adb_logcat_pstore_shutdown.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2896638/adb_logcat_pstore_shutdown.tar.gz)
Reboot: [adb_logcat_pstore_reboot.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2896658/adb_logcat_pstore_reboot.tar.gz)

For reference there has been a previous issue #268 and there has been already done some fixes in v6, however something seems still to be open.

**Comment by jerpelea** [comment]
one of the instability causes was identified in the zram and the offending patches were reverted 
please rebuild the kernel and check if you can replicate the reported issues

**Comment by stefanhh0** [comment]
Great, good job, Alin and all others that worked on it. The problem is no longer reproducible on a fresh aosp-build!

**Comment by russel5** [comment]
After few attempts bug still persist
[pstore.zip](https://github.com/sonyxperiadev/bug_tracker/files/2921574/pstore.zip)

**Comment by stefanhh0** [comment]
@russel5 Tried several times more following aboves shutdown recipe also with variants, I couldn't reproduce this anymore. Are you doing something different than I do? Have you flashed only the boot.img? I have flashed boot, vendor and system (not userdata though) from a fresh build yesterday. However I have done a aosp_g8441-eng build not a aosp_g8441-userdebug build. But that shouldn't make any difference, should it?

**Comment by russel5** [comment]
what i'm find in logs
`WARNING: CPU: 4 PID: 1279 at clk_branch_wait+0x124/0x140
<CORE> IPCRTR_mpss_smem: glink_tx_common: Intent Request with size: 36 not granted for lcid
IPC_RTR: ipc_router_glink_xprt_write: Error -11 while tx
IPC_RTR: ipc_router_glink_xprt_write: mpss_IPCRTR chnl reset
<CORE> smem:mpss glink_open: Error 0 - unable to find transport
<LBSRV> smem:mpss:LOOPBACK_CTL_APSS glink_lbsrv_open_worker: unable to open channel
<SSR> glink_ssr_notify_rx: Missing do_cleanup data!
<SSR> notify_for_subsystem: Subsystem lpass failed to respond. Restarting.
<SSR> notify_for_subsystem: Subsystem rpm failed to respond. Restarting.
Kernel panic - not syncing: notify_for_subsystem: RPM failed to respond!`

Ping @jerpelea @kholk

**Comment by stefanhh0** [comment]
With a new userdebug build it is reproducible again:

**Kernel version:** 4.9.158-g40f2ede5e12a
**Android version:** android-9.0.0_r31
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v6_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190205.001 eng.stefan.20190302.081554
**Version baseband:** 1307-7511_47.1.A.16.20
**Logs:** [logs.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2922197/logs.tar.gz)

**Comment by jerpelea** [comment]
@stefanhh0 
I can't reproduce the error on a 47.1.A.16.20 base 
I flashed the SW with EMMA
then started the device with a SIM card 
and then I flashed AOSP based on the latest code (userdata wiped)

**Comment by stefanhh0** [comment]
@jerpelea 
I retested as well with a current build and after a second attempt I could still reproduce it on shutdown.
Are you using a userdebug build? Just asking since with an eng build it seems not or not that good reproducible. 

I have used following configuration for the test:
 
**Kernel version:** 4.9.160-gc3a9863a5575
**Android version:** android-9.0.0_r34
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v6_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190305.002 eng.stefan.20190305.084745
**Version baseband:** 1307-7511_47.1.A.16.20
**Pstore files:** [pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2931116/pstore.tar.gz)

However my phone was originally flashed to 47.1.A.16.20 using newflasher and not emma + in this attempt userdata has not been wiped + twrp, opengapps and magisk have been installed.

I will try to reproduce it now with flashing 47.1.A.16.20 using emma and booting into the stock with sim, afterwards I'll flash plain aosp (incl. userdata.img) and will then retry reproducing it on the plain aosp without changing anything.

**Comment by jerpelea** [comment]
@stefanhh0 I use userdebug

thanks for testing clean

**Comment by stefanhh0** [comment]
I have done that test and found a different behavior. The phone shuts down, logcat finishes to log: [adb_logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/2931379/adb_logcat.log)
After that, the green led remains on for around 5 minutes. I have verified that the phone was not in flashtool mode via newflasher, it reported:
```
root@mars:/home/stefan/android/firmware/newflasher# ./newflasher.x64 
--------------------------------------------------------
            newflasher.x64 v13 by Munjeni @ 2017/2018           
--------------------------------------------------------

Determining available free space:

  Available space to caller    = 120720 MB
  Total space on current drive = 953866 MB
  Free space on drive          = 121702 MB

No usb device with vid:0x0fce pid:0xb00b !
```
After the five minutes the green led vanished and the phone bootet into flashtool mode (green led was shining again). I was then able to access it via newflasher successfully:
```
root@mars:/home/stefan/android/firmware/newflasher# ./newflasher.x64 
--------------------------------------------------------
            newflasher.x64 v13 by Munjeni @ 2017/2018           
--------------------------------------------------------

Determining available free space:

  Available space to caller    = 120718 MB
  Total space on current drive = 953866 MB
  Free space on drive          = 121700 MB
found device with vid:0x0fce pid:0xb00b.

Optional step! Type 'y' and press ENTER if you want dump trim area, or type 'n' and press ENTER to skip.
Do in mind this doesn't dump drm key since sake authentifiction is need for that!
```
After booting to the system `/sys/fs/pstore` is clean. I hope that helps and you can reproduce this behavior.

**Comment by stefanhh0** [comment]
I've just flashed twrp, booted into the system (still plain aosp without any other modifications than flashing twrp to the recovery partition, did a "adb reboot recovery"  and then a crash occurred. Unfortunately I haven't recorded adb_logcat this time... but pstore contains a dmesg file again.
[pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2931489/pstore.tar.gz)

**Comment by jerpelea** [comment]
@stefanhh0 please test on v8 after release 
I cant replicate it anymore

**Comment by stefanhh0** [comment]
Okay, I will do that and will report back as soon as possible with my findings. Thanks for all your efforts, that is very much appreciated.

**Comment by jerpelea** [comment]
@stefanhh0 
v8 is released !
please rebuild and test

**Comment by stefanhh0** [comment]
**Kernel version:** 4.9.168-g4ebcb68cc743
**Android version:** android-9.0.0_r35
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190405.003 eng.stefan.20190418.191851
**Version baseband:** 1307-7511_47.1.A.16.20

I've retested the shutdown scenario as outlined in the initial comment of this issue. I did not test it on a vanilla aosp but on the aosp without overwritten userdata and installed Magisk-v19.0 and open_gapps-arm64-9.0-pico-20190418. I could reproduce the problem after 4th attempt. Phones vibrator was activated twice and pstore contains this time all three files:
[pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/3096435/pstore.tar.gz)

Hope that helps.

**Comment by stefanhh0** [comment]
Testing on:
**Kernel version:** 4.9.174-gd7ab313501f1
**Android version:** android-9.0.0_r37
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ3A.190505.002 eng.stefan.20190514.014237
**Version baseband:** 1308-8921_47.1.A.16.20

After 4th shutdown, phone did not boot into flashtool mode (green led) but did a regular system boot instead. No files have been found in /sys/fs/pstore, so no crash occurred but the behavior is still not as expected sometimes.

The logcat contains the shutdown sequence maybe there is something useful contained...
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3175910/logcat.log)

**Comment by stefanhh0** [comment]
On the 8th shutdown attempt I could reproduce the crash.

The logcat.log is from the shutdown sequence, then a crash occurred and the phone did a reqular system boot due to the previous crash. The crash contains this time a dmesg file.

[pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/3175941/pstore.tar.gz)
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3175942/logcat.log)

So the bug is still open on:
**Kernel version:** 4.9.174-gd7ab313501f1
**Android version:** android-9.0.0_r37
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ3A.190505.002 eng.stefan.20190514.014237
**Version baseband:** 1308-8921_47.1.A.16.20
