### ISSUE TITLE
[dora] Endless soft reboots when Firefox Focus starts

### ISSUE THREAD

**Issue by Mohnach** [sonyxperiadev/bug_tracker#346]
**Platform:** Tone
**Device:** F8132
**Kernel version:** 4.9.154
**Android version:** 9.0.0_r31

**Description**
Sometimes after a deep sleep, creating a new tab in Firefox Focus causes a soft reset cycle with OutOfMemoryError.
Maybe, it is a firefox problem

**Symptoms**
Endless soft reboots

**How to reproduce**
I got it randomly 2 times (one with v5 binaries and another one with v6)

Logcat: [logcat1.txt](https://github.com/sonyxperiadev/bug_tracker/files/2897787/logcat1.txt)

**Comment by jerpelea** [comment]
one of the instability causes was identified in the zram and the offending patches were reverted 
please rebuild the kernel and check if you can replicate the reported issues

**Comment by Mohnach** [comment]
@jerpelea, device reboots after sony logo with the new boot image (from Mar 1). It load correctly with prebuilt kernel [2.3.2.r1.4] Linux 4.9.158 from Feb 22, 2019

**Comment by stefanhh0** [comment]
Try flashing the full aosp build not just boot.img, chances are good that it fixes the problem...

**Comment by Mohnach** [comment]
Thanks for the recomendadion! I have already tried this, but it didn't work. My build from 1st of March loaded correctly only with old boot.img (from 22 Feb).

**Comment by Mohnach** [comment]
New prebuild kernel from March 4 is loads correctly. ZRam is disabled. I will try to reproduce an error

**Comment by Mohnach** [comment]
I think, that this crash is not a cause, but a consequence. But i have not ideas, how to reproduce this purposefully: the error was happened during normal daily use

**Comment by stefanhh0** [comment]
I guess it would make sense that you close the ticket then, since it is not reproducible and since it was originally reported on an old version. If you get crashes/reboots on your daily use again then you should provide the files found in /sys/fs/pstore for further analysis in a new issue.

**Comment by stefanhh0** [comment]
@Mohnach another thing, you are writing about endless soft reboots. So, you are experiencing kind of a boot-loop then? If so, how do you end the boot-loop? There is also another ticket that can cause a  bootloop like behavior:  #335. Have you changed the original white point calibration settings in the Extended System Settings? Then it could be the case that you are affected by that issue.

**Comment by Mohnach** [comment]
@stefanhh0 ok, i will attach pstore-file in future tickets. Thanks for the recomendadion
If i remember correctly, only the UI load was endless: black screen -> wallpaper -> lock screen -> force close error -> go to 1. it stopped after i turned off the phone.
I definitely did not change the white point calibration settings.
