### ISSUE TITLE
[suzu] GPS stops working.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [sonyxperiadev/bug_tracker#347]
**Platform:** loire
**Device:** suzu
**Kernel version:** 4.9
**Android version:**  9.0.0_r31

**Description**
Usually (it rarely works without a reboot) when I open any app that provides maps with location tracking, my location never shows up even though location is turned on. It does show up though if I restart the phone (with the phone in the same physical place).

**Comment by jerpelea** [comment]
@gerg5c42g542g2c54g52c are you using AOSP?

**Comment by jerpelea** [comment]
I am using v6 with the latest sources and I can not see any issues with the GPS

**Comment by djselbeck** [comment]
I had some problems recently with lilac and figured out that it was a network-based location provider injecting a wrong position. The result was that my device saw zero GPS satellites in GPSTest[1] until I reset the help data (called this way in GPSTest). Not sure if this is related but it might be worth a try.

Not sure which NLP exactly was the cause but I think it was DeJaVu [2]

[1] https://f-droid.org/de/packages/com.android.gpstest.osmdroid/

[2] https://f-droid.org/de/packages/org.fitchfamily.android.dejavu/

**Comment by gerg5c42g542g2c54g52c** [comment]
Yup, clean AOSP, no GApps, no network-based location, vendor v5. I didn't flash vendor v6 yet, because my build has TARGET_VENDOR_VERSION=v5. I will rebuild and flash new vendor when the new security fixes arrive and report if anything changed.

**Comment by jerpelea** [comment]
@gerg5c42g542g2c54g52c I can't reproduce it with current HEAD^
