### ISSUE TITLE
Xperia xa2 - Random reboots

### ISSUE THREAD

**Issue by infixremix** [sonyxperiadev/bug_tracker#349]
**Platform:** nile
**Device:** pioneer
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
Random reboots. Cant determine the cause.

**Symptoms**
The device freezes and soft reboots .
sometimes fully reboots too
**How to reproduce**
Use something that uses high animations scaling like snapchat facebook. Sometimes even typing animation causes a freeze. i doubt it is animations because it occasionally reboots in idle. See logs attached.

**Comment by ix5** [comment]
@infixremix you forgot to attach any logs ;)

**Comment by infixremix** [comment]
Ah shit will do in a min

**Comment by infixremix** [comment]
[longlog.txt](https://github.com/sonyxperiadev/bug_tracker/files/2915931/longlog.txt)

**Comment by oshmoun** [comment]
this is probably the known iommu issue, but to be sure, please upload pstore next time it happens

**Comment by infixremix** [comment]
@oshmoun Will do. The logs were on a freeze. Its an issue on rendering.

**Comment by jerpelea** [comment]
one of the instability causes was identified in the zram and the offending patches were reverted 
please rebuild the kernel and check if you can replicate the reported issues

**Comment by infixremix** [comment]
@jerpelea will do. Thanks will report later.

**Comment by infixremix** [comment]
@jerpelea **Seems** to have fixed that issue. Had one reboot which seems to be the same issue as the Bluetooth one. Had none recently , In the last 8 hours.
Thanks.

**Comment by oshmoun** [comment]
@infixremix considering the commit that removes zram also seems to break boot, i doubt you had zram disabled in your test. to be sure if that, please post the result of `free -h`

**Comment by infixremix** [comment]
> @infixremix considering the commit that removes zram also seems to break boot, i doubt you had zram disabled in your test. to be sure if that, please post the result of free -h

Ye, just had another reboot must have been ram usage.

**Comment by infixremix** [comment]
> @infixremix considering the commit that removes zram also seems to break boot, i doubt you had zram disabled in your test. to be sure if that, please post the result of free -h

actually it is swap is 0

**Comment by oshmoun** [comment]
@infixremix i don't agree with the issue being related to zram or ram usage of anything else similar.
the reason is simple enough, if you would check pstore. there is an explicit iommu error, or at least that was the case for my nile.

**Comment by jerpelea** [comment]
@oshmoun I never said that all issues will magically disapear when ZRAM is removed. I sayed that some instability was cauzed by ZRAM and that can be easy replicated by enabling ZRAM and LZ4.

**Comment by infixremix** [comment]
> iommu erro

iommu is related to ram and zram lol

**Comment by oshmoun** [comment]
@jerpelea that kind of testing seems inaccurate. the fact that any observed instability can be mitigated by disabling some driver does not rule out that the cause lies elsewhere, and not in the disabled driver. that is why i asked for pstore, to get the cause reported by the kernel, which will allow for a more valid diagnosis.
i wouldn't mind running the same memory test here though, what app were you using for that?

**Comment by oshmoun** [comment]
@infixremix I'm sorry for not further expanding on my point about iommu, just didn't think it was relevant as long as the suspicion lied elsewhere.
observations here point towards an issue with the switch to sde. the iommu error can be reliably reproduced by running pcmark battery benchmark. switching back to fbdev causes the iommu crash to be replaced with an app fc (the benchmark closes). i have not checked why the latter happens, since the iommu crash seemed more immediate.

**Comment by jerpelea** [comment]
@oshmoun you can even try to use Antutu and you will see various memory errors

**Comment by infixremix** [comment]
@jerpelea also I don't want to make another issue of you know about it. However do you know about CPU and GPU for screen composing. We can force the use of the GPU composing and not CPU . If we use both we get green screen on full screen video players and Google camera. Do you know about this ?

**Comment by oshmoun** [comment]
@infixremix thanks for hinting disabling hw overlays. Thought I had already tested running pcmark with that, but seems not.
With sde and disabled hw overlay, which reverts to gpu composition like it was back fbdev, pcmark battery benchmark seems to not crash the device anymore. However, the benchmark still abruptly closes like always. Will test antutu and see if that exhibits the same behavior.

**Comment by infixremix** [comment]
@oshmoun with it disabled there's no point doing a benchmark.

**Comment by oshmoun** [comment]
@infixremix I do not quite see the logic behind that. Disabling hw overlays means the composition is done on the gpu, same as it was before switching from fbdev to sde. To be more explicit, we always were using gpu composition, and only since the switch to sde has that changed.
If you want to check for yourself, you can switch back from sde to fbdev, then run `dumpsys SurfaceFlinger` before and after toggling "disable hw overlays". You'll see that the output will remain the same.

**Comment by infixremix** [comment]
@oshmoun Green screen is to do with. Open Media Acceleration.

**Comment by oshmoun** [comment]
that's an interesting thought. did you test with sw decoders then to see if the issue is gone that way?

**Comment by infixremix** [comment]
Na it definitely is. I made a build with stock libs for OMX

**Comment by infixremix** [comment]
You could test a new hal not qcoms

**Comment by oshmoun** [comment]
can you please list which libs you replaced?

**Comment by infixremix** [comment]
Look in propirety vendor and media OMX in tree

**Comment by infixremix** [comment]
However it's to do with treble I think

**Comment by infixremix** [comment]
As you guessed my way wouldn't work ;-) same error

**Comment by oshmoun** [comment]
Thanks for confirming that :)
Found out how to fix the green screen in kernel, but unfortunately not going to work with the current setup:
https://github.com/sonyxperiadev/kernel/pull/1929
This works if nile is reverted to using fbdev, confirmed working here.

**Comment by infixremix** [comment]
Thanks for your hardwork. Interesting that it was kernel wouldn't have looked there. Good call. Do you have a source with fbdev?

**Comment by oshmoun** [comment]
Oops sorry, missed answering the question.
Assuming you are building the kernel inline, you can simply regenerate defconfig using `kernel/sony/msm/arch/arm64/sony/update-defconfig.sh`
Just make sure to disable DRM for nile:
https://github.com/sonyxperiadev/kernel-defconfig/blob/aosp/LE.UM.2.3.2.r1.4/update_defconfig.sh#L46
Then you can rebuild the kernel and get back fbdev. Make sure to pick the display patch too:
https://github.com/sonyxperiadev/hardware-qcom-display/pull/19

**Comment by infixremix** [comment]
Alright thanks alot

**Comment by oshmoun** [comment]
The green video issue should now be resolved
The general instability still persists

**Comment by infixremix** [comment]
I hope gpu composing is temporary

**Comment by jerpelea** [comment]
@infixremix 
v8 is released !
please rebuild and test

**Comment by infixremix** [comment]
@jerpelea Sorry for the late reply. Currently trying everything to get my pioneer fixed (Fried pvc bored) and warranty void ; This is Resulting to a home diy project. I will not be able to test anything till next week sorry for any troubles this may cause.

**Comment by kholk** [comment]
This resolves your issue.
https://github.com/sonyxperiadev/kernel/pull/1977

**Comment by infixremix** [comment]
Sorry can't test phone caught fire and claim warranty and waiting for the part to come from china should have been here a week ago so idk if i will ever have a nile again :/

**Comment by jerpelea** [comment]
fixed 
https://github.com/sonyxperiadev/kernel/commit/fc821b0441e9b5b17e6f40e9f0f26f385eec3a9d
