### ISSUE TITLE
[Yoshino/Maple] Volume up does not work, random reboots and freezes

### ISSUE THREAD

**Issue by tritone11** [sonyxperiadev/bug_tracker#350]
**Platform:** Yoshino
**Device:** Maple
**Kernel version:** 4.4.148-perf+
**Android version:** 9

**Description**
The device volume up button is not responding for long periods of time. It is not a hardware related issue as at reboot it works perfectly and then stops. Sometimes it starts working and again. Apparently randomly, the device reboots or freezes.

**Symptoms**
Volume up not working, freezes and reboots.  
From logs (maybe related?):

```
01-01 02:15:51.027   870   870 W DeviceHAL: Error from HAL Device in function get_master_volume: Function not implemented
01-01 02:15:51.027   870   870 W DeviceHAL: Error from HAL Device in function get_master_mute: Function not implemented
01-01 02:15:51.027   870   870 W DeviceHAL: Error from HAL Device in function set_master_volume: Function not implemented
01-01 02:15:51.027   870   870 W DeviceHAL: Error from HAL Device in function set_master_mute: Function not implemented
```

**How to reproduce**
Unknown. The same issue happened with Oreo last year. It seems to be related with the headphone jack.    
  
**Logs**
[xz.log](https://github.com/sonyxperiadev/bug_tracker/files/2919273/xz.log)

**Comment by Paulbouchara** [comment]
Are you on 4.4 kernel on android 9 ?
The kernel tag makes me think you're on stock, don't ya ?
Keep in mind that this bug tracker is for AOSP bugs only, we have no power of action on stock

**Comment by infixremix** [comment]
They just fixed reboots

**Comment by tritone11** [comment]
> Are you on 4.4 kernel on android 9 ?
> The kernel tag makes me think you're on stock, don't ya ?
> Keep in mind that this bug tracker is for AOSP bugs only, we have no power of action on stock

Sorry, not noticed
