### ISSUE TITLE
[dora] Motion sensors are not available

### ISSUE THREAD

**Issue by Mohnach** [sonyxperiadev/bug_tracker#352]
**Platform:** Tone
**Device:** F8132
**Kernel version:** 4.9.158
**Android version:** 9.0.0_r31

**Description**
Motion sensors are not available

**Symptoms**
Screen rotation does not work. Motion sensors are not listing in sensors list (see screenshot from cpu-z app): only temperature sensors are available

**How to reproduce**
Build aosp from March 4th. Problem does not reproduced on build from Feb 26th

Logcat: [logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/2927874/logcat.txt)

![screenshot_20190304-220743](https://user-images.githubusercontent.com/46724603/53756366-02a20800-3eca-11e9-81a0-b36989211373.png)

**Comment by Mohnach** [comment]
For workaround i returned next strings to sensors.rc:
```
on property:vendor.qcom.devup=1
    start sensors
```
It is strange that they do not start on the event "on property:vold.decrypt=trigger_post_fs_data"

**Comment by MarijnS95** [comment]
Did you pull in https://github.com/sonyxperiadev/device-sony-common/commit/828c821b265d6ebc0d6160dcfa98d6eb2cadf542 already? There have been some changes and fixes to sensor startup that follow your findings of the issue appearing around 4 March.
See also https://github.com/sonyxperiadev/device-sony-common/commits/master/rootdir/vendor/etc/init/sensors.rc

**Comment by Mohnach** [comment]
Yes, I launched repo_update today: it doesn't help. if I understand correctly, my device is in encrypted case:
```
$ getprop | grep crypto
[ro.crypto.fs_crypto_blkdev]: [/dev/block/dm-1]
[ro.crypto.state]: [encrypted]
[ro.crypto.type]: [block]
```

**Comment by jerpelea** [comment]
Android 8.1 or 9?

**Comment by Mohnach** [comment]
9 r31

**Comment by Mohnach** [comment]
Until February commits, the sensors were unavailable only at the first launch after a clean installation. And reboot fixed them.
After these commits, sensors are not available even after reboot

**Comment by jerpelea** [comment]
are you on vendor v7 ?

**Comment by jerpelea** [comment]
the cause of the race condition was fixed and the unneeded service is excluded from legacy devices

**Comment by jerpelea** [comment]
sensors are consistently starting on all boots
