### ISSUE TITLE
[suzu] Bootloop after system boot.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [sonyxperiadev/bug_tracker#355]
**Platform:** loire
**Device:** suzu
**Kernel version:** 4.9
**Android version:** android-9.0.0_r34
vendor v6

**Description**
After booting the OS, the device restarts.

**Symptoms**
Some visible problems that didn't occur on earlier versions are notifications of 'phone keeps restarting', flashlight icon grayed out, data icon grayed out for a while since boot, then a message saying 'powering off'.

**How to reproduce**
Flash boot, system, recovery and oem images or flash boot, system, recovery, oem and userdata images and restore backed up data partition in TWRP.

**Comment by infixremix** [comment]
test without restoring data.

**Comment by sjllls** [comment]
Tested on 2019.3.23
Boot successfully.
Try to format data and cache partitions.

Platform: loire
Device: suzu
Kernel version: 4.9
Android version: android-9.0.0_r34
OEM: V7
