### ISSUE TITLE
[website] wrong sha256sum for yoshino sw binaries

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/bug_tracker#356]
**Platform:** 
**Device:** 
**Kernel version:** 
**Android version:** 

**Description**
You can download v17B (dated 5 March 2019) of the yoshino SW binaries zip here:

https://developer.sony.com/file/download/software-binaries-for-aosp-oreo-android-8-1-kernel-4-4-yoshino/

![Screenshot_20190309_132929](https://user-images.githubusercontent.com/5332385/54075642-b0693a00-426f-11e9-83f5-1353ee219cdb.png)

The sha256sum appears to be wrong.

I have downloaded the zip file multiple times and always get the following:

```
$ sha256sum SW_binaries_for_Xperia_Android_8.1.6.4_r1_v17B_yoshino.zip
d4c77ddcc0075d1242a4a0d9b6cf375156a873dae53e5c2f702052c85651c7bf  SW_binaries_for_Xperia_Android_8.1.6.4_r1_v17B_yoshino.zip
```
If you unzip the file and compute the hash of the img file, then it still does not match.

**Symptoms**
the hash is wrong.

**How to reproduce**
download the zip and compute its sha256sum.

**Comment by jamuir** [comment]
On a related matter, wouldn't it be easier to maintain the publication/distribution of the SW binaries in a git project?  The SW binaries web page looks nice, but it would seem to require much more maintenance than a git project.

**Comment by oshmoun** [comment]
Not moving to git probably has to do with the EULA requirement, though I agree that the current way is hardly optimal. I mean, this issue suggests that the hash was not automatically generated from the uploaded file, but manually written.

**Comment by jerpelea** [comment]
I am sorry for the issue 
we will solve it ASAP
