### ISSUE TITLE
[Lilac][Yoshino] USB Tethering crashes device

### ISSUE THREAD

**Issue by djselbeck** [sonyxperiadev/bug_tracker#357]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.160-g0cefce455591-dirty
**Android version:** [ro.vendor.build.fingerprint]: [Sony/aosp_g8441/lilac:9/PQ2A.190305.002/hendrik03091045:userdebug/test-keys]

**Description**
Enabling USB Tethering from the connectivity settings will instantly freeze the device

**Symptoms**
Device freezes and then reboots

**How to reproduce**
Enable USB tethering from device settings

**Comment by djselbeck** [comment]
Forgot pstore files:

[console-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2952222/console-ramoops-0.txt)
[pmsg-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2952223/pmsg-ramoops-0.txt)

**Comment by jerpelea** [comment]
the bug seems to be fixed in v8 release
