### ISSUE TITLE
[Lilac][Yoshino] Unstable SD card access

### ISSUE THREAD

**Issue by djselbeck** [sonyxperiadev/bug_tracker#358]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.160-g0cefce455591-dirty
**Android version:** Sony/aosp_g8441/lilac:9/PQ2A.190305.002/hendrik03091045:userdebug/test-keys

**Description**
Heavy usage of a SD card can result in reboots of the device. The SD card is a 400GB microSD from Sandisk. I can trigger several reboots if I reset my media database from the apps settings. I have around 200gb mp3 files on my SD and the device reboots multiple times while rescanning for media files. The pstore contains some MMC related error. 

**Symptoms**
Device just freezes and reboots.

**How to reproduce**
Heavy usage of SD card?
[console-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2978045/console-ramoops-0.txt)
[pmsg-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2978046/pmsg-ramoops-0.txt)

**Comment by jerpelea** [comment]
Can you attach logcat

**Comment by jerpelea** [comment]
skipping huge ID3 metadata of size 3146752
failed to extract an album art

it looks like some of your files have issues and you may trigger a media scanner bug

**Comment by jerpelea** [comment]
I was unable to see any instability on the SD Card by doing IO tests

**Comment by djselbeck** [comment]
But they should not trigger a device reboot or am I mistaken? I try to fetch a logcat later

**Comment by Paulbouchara** [comment]
I did a test on my SD card on maple
I had no issues so far, is your card formatted in exfat ? Have you build the latest head for sod before testing?

**Comment by djselbeck** [comment]
It is vfat (32) formatted. I will now reset my media db reboot and try to get a logcat

**Comment by kholk** [comment]
In theory it shouldn't trigger a reboot, you're right, but whatever... When I was using maple as a daily driver on 4.9 Pie, I was also using a exfat formatted 128GB SD but I've never had any reboot related to sdhci issues.

Perhaps there's some issue happening only with very high capacity cards?

Can you try a standard capacity card? (8-256GB)
Also, can you please verify that your huge card works properly in another phone or a SD reader on your PC?

**Comment by djselbeck** [comment]
yes of course. Both. But it will take some time ;)

**Comment by kholk** [comment]
Don't worry man, we're not in a hurry :p

**Comment by djselbeck** [comment]
So here are some insights:

- I tested the SD card in my Lenovo x260 with dd on the complete blockdevice (dd if=/dev/mmcblk0 of=/dev/zero bs=1M) without any error
- Reset my music db and logcat connected (display on) no crash occurred 
- Reset my music db and logcat connected (display off) no crash occurred 
- Reset my music db nothing connected on USB -> device froze (again MMC error in console log)

When I get home I will try a smaller SD card (should be 128gb if I am correct)

[console-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2983844/console-ramoops-0.txt)
[pmsg-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/2983845/pmsg-ramoops-0.txt)

**Comment by stefanhh0** [comment]
If you have enough space, you could also try verifying that the fs is really okay using:
```
dd if=/dev/mmcblk0 of=/tmp/sdcard.img bs=10M
kpartx -av /tmp/sdcard.img
fsck.vfat -v /dev/mapper/loop0p1
```

Or you try verifying it from your android device directly via:
`/system/bin/fsck_msdos` but I am not sure if it is basically the same as fsck.vfat, however I guess it will probably do it's job fine as well. 

Have you formatted the card initially yourself? You could just recreate the fs using 
`mkfs.vfat /dev/mmcblk0`, copy the files over to it and wait for `sync` to complete before ejecting the sdcard. Probably you know all of that, I just want to make sure everything was done as it should be in the first place.

**Comment by jerpelea** [comment]
@djselbeck do you have any updates on this report

**Comment by djselbeck** [comment]
Hi sorry, I forgot about this. I can confirm two things. The SD card works completely stable with Lilac on Stock firmware and on Kagura with AOSP.
