### ISSUE TITLE
[all] [Nougat] USB Tethering can't be enabled at all

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#36]
**Platform:** loire, tone, yoshino
**Device:** suzu, kagura, maple
**Kernel version:** 4.4 (567bc74, manually built on Nov 13)
**Android version:** 7.1.1
**Firmware version:** v05

**Description**
USB Tethering can't be enabled at all

**Symptoms**
The user is not able to turn on USB tethering.

**How to reproduce**
Apps -> Settings -> Network & Internet -> Hotspot & tethering -> USB tethering toggle button

**Logs**
N/A

**Comment by erikcas** [comment]
On suzu the toggle turns on. Dmesg of my ubuntu box with suzu attached also shows that usb is connecting as a networking device:

[ 5023.427751] usb 2-1.2: new high-speed USB device number 17 using ehci-pci
[ 5023.538074] usb 2-1.2: New USB device found, idVendor=18d1, idProduct=01e0
[ 5023.538079] usb 2-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 5023.538081] usb 2-1.2: Product: Xperia X
[ 5023.538084] usb 2-1.2: Manufacturer: Sony
[ 5023.538086] usb 2-1.2: SerialNumber: BH9007LR56
[ 5025.999495] usb 2-1.2: usbfs: USBDEVFS_CONTROL failed cmd adb.linux.64 rqt 128 rq 6 len 256 ret -71
[ 5026.022223] usb 2-1.2: USB disconnect, device number 17
[ 5026.243898] usb 2-1.2: new high-speed USB device number 18 using ehci-pci
[ 5026.357621] usb 2-1.2: New USB device found, idVendor=18d1, idProduct=81e0
[ 5026.357625] usb 2-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 5026.357628] usb 2-1.2: Product: Xperia X
[ 5026.357631] usb 2-1.2: Manufacturer: Sony
[ 5026.357633] usb 2-1.2: SerialNumber: BH9007LR56
[ 5026.360557] rndis_host 2-1.2:1.0 usb0: register 'rndis_host' at usb-0000:00:1d.0-1.2, RNDIS device, 82:5f:62:43:6e:c2
[ 5026.377461] rndis_host 2-1.2:1.0 enp0s29u1u2: renamed from usb0
[ 5026.408648] IPv6: ADDRCONF(NETDEV_UP): enp0s29u1u2: link is not ready

Ifconfig shows the new renamed usb device:

enp0s29u1u2 Link encap:Ethernet  HWaddr 82:5f:62:43:6e:c2  
          inet6 addr: fe80::24f0:62a1:7b6f:83ba/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

relevant snippet logcat:
https://gist.github.com/erikcas/f48df9e86bf4ec4cfdf468d3fafa3769

it does not work however. Maybe we miss a property?

**Comment by jerpelea** [comment]
confirmed

**Comment by jerpelea** [comment]
Tone platform is ok

**Comment by jerpelea** [comment]
Tone platform is ok

**Comment by jerpelea** [comment]
yoshino platform fixed

**Comment by jerpelea** [comment]
please open another ticket for loire platfrom

**Comment by jerpelea** [comment]
it looks like this is a bug in Android 7.1

**Comment by erikcas** [comment]
really @jerpelea is it? Loire (and I think some people assumption is that I am running 3.10 but let me make sure again I am running suzu on k4.4 android-8.0) has it NOT working as I described above, which also was, again, on k4.4 android-8.0 suzu

**Comment by jerpelea** [comment]
ok
i will also check susu

**Comment by jerpelea** [comment]
to sumarize
this is an Android 7.1 bug when kernel 4.4 is used and it requires code backport from Android 8
with the same kernel and device configuration the functionality is available Android 8.0
