### ISSUE TITLE
Xperia X Android 8.1 can not establish stable RSAP connection

### ISSUE THREAD

**Issue by XperiaDeveloper** [sonyxperiadev/bug_tracker#360]
**Platform:** Loire
**Device:** Xperia X
**Kernel version:** 4.4
**Android version:** 8.1.0-R52

**Description**
Trying to connect the device with bluetooth RSAP to car. The bluetooth connection with the device is esablished. Then it asks for SIM PIN and then crashes. A dialog shows "unexpected failure". 

Please see the attached log file. Error experienced between 8:14 and 8:15. 
[log-vanilla-rsap.log](https://github.com/sonyxperiadev/bug_tracker/files/2996376/log-vanilla-rsap.log)

**Symptoms**
Crashing bluetooth connection. 

**How to reproduce**
[As described in description]

**Comment by jerpelea** [comment]
can you post the dmesg for the same bug

**Comment by jerpelea** [comment]
I tried to replicate the bug with my card but unfortunately I don't have RSAP

**Comment by XperiaDeveloper** [comment]
Here you will find the related dmesg [log-vanilla-dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3003865/log-vanilla-dmesg.log)

**Comment by jerpelea** [comment]
Unfortunately the dmesg does not help 
can you increase verbosity in the BT HAL and try again

**Comment by XperiaDeveloper** [comment]
Hi, 
sorry for delay. I had no access to car with RSAP the whole last week. 

Here you find the logs with more debugging. Time to try to connect was between 8:04-8:05.

[log-vanilla-dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3057451/log-vanilla-dmesg.log)
[log-vanilla.log](https://github.com/sonyxperiadev/bug_tracker/files/3057452/log-vanilla.log)

**Comment by oshmoun** [comment]
can you please try with a kernel built with this commit checked out?
https://github.com/sonyxperiadev/kernel/commit/823f674490e8352b4f0e4ac109ae5edf1b50ffb5

**Comment by XperiaDeveloper** [comment]
Hi, I tried with the kernel with the suggested commit. The RSAP connection works then fine :). 

Could you point to some specific commits which could be eventually cherry-picked? (Currently we are on this commit: https://github.com/sonyxperiadev/kernel/commit/44235a04f24d81465c2d4ea0a7c46505b41601f8)

[log-vanilla-dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3111172/log-vanilla-dmesg.log)
[log-vanilla-rsap.log](https://github.com/sonyxperiadev/bug_tracker/files/3111173/log-vanilla-rsap.log)

**Comment by oshmoun** [comment]
@XperiaDeveloper thanks for testing.
there are no commits to pick, but you might be able to revert a set of commits to achieve what you want. I don't have such a list ready for you unfortunately.
I've got to ask though, can you reliably trigger the issue currently? i.e does RSAP always fail immediately or does it sometimes successfully pairs for a while then suddenly fails while in use?

**Comment by jerpelea** [comment]
@XperiaDeveloper did you cherrypick that commit or you used built the kernel on that commit?

**Comment by oshmoun** [comment]
@jerpelea he did a checkout of that commit.
Picking that commit changes nothing as it is already applied in the 4.4 branch
```
$ git cherry-pick 823f674
HEAD detached at sonyxperiadev/aosp/LA.UM.6.4.r1
You are currently cherry-picking commit 823f674490e8.

nothing to commit, working tree clean
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'
```

**Comment by jerpelea** [comment]
@oshmoun then we have more than 800 commits to bisect and find the regression

unfortunately he is the only one that has a car to test and we can not speedup the process

**Comment by XperiaDeveloper** [comment]
> @XperiaDeveloper thanks for testing.
> there are no commits to pick, but you might be able to revert a set of commits to achieve what you want. I don't have such a list ready for you unfortunately.

Revert or cherry-pick should be both fine. I don't just want to move the kernel three months ahead, I'm afraid that some other components would not work then. 

> I've got to ask though, can you reliably trigger the issue currently? i.e does RSAP always fail immediately or does it sometimes successfully pairs for a while then suddenly fails while in use?

Always reliably failing after pairing.

> looping in @kholk so he now has the proof he wanted of the bt issue being related to clocks.

**Comment by XperiaDeveloper** [comment]
> @oshmoun then we have more than 800 commits to bisect and find the regression
> @XperiaDeveloper can you checkout d363743c8506f72583636fc01b98db3891e1f1a5 to narrow the search
> 
> unfortunately you are the only one that has a car to test RSAP and we can not speedup the process

I'll check that and give you feedback asap.

**Comment by XperiaDeveloper** [comment]
> @oshmoun then we have more than 800 commits to bisect and find the regression
> @XperiaDeveloper can you checkout d363743c8506f72583636fc01b98db3891e1f1a5 to narrow the search
> 
> unfortunately you are the only one that has a car to test RSAP and we can not speedup the process

Using this commit the connection established but crashed after making a call. Do you need the logcat output for this case?

**Comment by oshmoun** [comment]
@XperiaDeveloper could you please test with this modification?
https://github.com/sonyxperiadev/kernel/pull/1967

**Comment by XperiaDeveloper** [comment]
Any update on this issue. Last commit from "oshmoun" had no action for me. So could you isolate the relevant commits?

**Comment by kholk** [comment]
@XperiaDeveloper I've just engineered a possible solution for this issue, thanks to @oshmoun isolating the producer to a specific clock.

Can you please test your RSAP connection again with this patchset?
https://github.com/sonyxperiadev/kernel/pull/1985

Thanks!

**Comment by XperiaDeveloper** [comment]
Hi @kholk actually we need the patchset for Android 8 based on LA.6.4.1 (our last commit from Alin 44235a04). 
Your change is as I see based on LE.UM.2.3.2.r1.4 and the set could not be cherry-picked into our repo.

**Comment by jerpelea** [comment]
Deprecated Android version
