### ISSUE TITLE
[Yoshino] State of version baseband compatibility with 47.2.A.XX.XX

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#361]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** **Kernel version:** 4.9.162-ge1ccab69b98e
**Android version:** android-9.0.0_r34
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v7_yoshino.img
**Version baseband:** 1307-7511_47.1.A.16.20

In the past @jerpelea has mentioned several times that the current state of AOSP 9 together with 47.2.A.XX.XX version baseband is not stable and therefore it is recommended to stay on 47.1.A.16.20. With todays release of v7 oem I'd like to ask if this is still the case or if it would make sense to switch to the current 47.2.A.8.24 version baseband?

**Comment by jerpelea** [comment]
please use the stable base

**Comment by stefanhh0** [comment]
Thanks for the answer Alin! Will do so.
