### ISSUE TITLE
[tone] [kagura], [?] Crackling speaker sound on medium to high volume

### ISSUE THREAD

**Issue by ix5** [sonyxperiadev/bug_tracker#365]
**Platform:** tone
**Device:** kagura, possibly others
**Kernel version:** 4.9
**Android version:** 9.0 Pie

**Description**
After we fixed the top speaker issue, it has become apparent that the sound coming out of the top speaker has a lot of crackling once the volume level reaches more than ~50%.
All channels are affected: Media, Calling, Alarm, Ringtone.

**Comment by MartinX3** [comment]
Same on Tama akari with OEMv8 and OmniROM 9.0.
Build date 2019-04-22 17:50:47

**Comment by ix5** [comment]
Closing in favour of https://github.com/sonyxperiadev/bug_tracker/issues/411
