### ISSUE TITLE
[tone] [kagura] Calling only possible on speaker

### ISSUE THREAD

**Issue by ix5** [sonyxperiadev/bug_tracker#369]
**Platform:** tone
**Device:** kagura
**Kernel version:** 4.9
**Android version:** 9.0 Pie

**Description**
In-call audio is only routed through the speaker. It is not possible to switch to earpiece in the UI.

**Symptoms**
Tapping the button to change audio routes in the in-call UI does nothing, speaker is activated by default

logcat: [2019-04-14-aosp-calling.txt](https://github.com/sonyxperiadev/bug_tracker/files/3077198/2019-04-14-aosp-calling.txt)

**How to reproduce**
Build with branch `r35` for SoMC kagura and start a call

**Comment by jerpelea** [comment]
I tested the device today on a fresh build and it works as it should on both speaker and headpiece
I suspect that you have a dirty tree

**Comment by ix5** [comment]
This might have been due to the adsp errors/race conditions that necessitated restarting the audio HAL after bootup, which I had in my init for that build.

New build with v8 binaries, calls are fine, both earpiece and speaker. Crackling is still present above ~50% volume level, see https://github.com/sonyxperiadev/bug_tracker/issues/365
