### ISSUE TITLE
[kagura] Sporadic device verification failure, although device is UNLOCKED

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#37]
**Platform:** tone
**Device:** kagura
**Kernel version:** 4.4 (567bc74, manually built on Nov 13)
**Android version:** 7.1.1

**Description**
While attempting to offline charge the device, sometimes it will enter the **RED** boot state, although it should boot in the **ORANGE** state since the device state is **UNLOCKED**. Though the occurrence is not frequent, it is not negligible.

**Symptoms**
The device is correctly charging offline, however before the charging begins, the device sometimes will cycle through the following:
1. boot to ORANGE state, try to enter charging mode, fail and reboot
2. boot to RED state, shut down (but because it is on charger it will boot up again)
3. boot to ORANGE state, try to enter charging mode, success and continue with the battery charging animation.

Sometimes 1. and 2. will be repeated several times before continuing to 3.

**How to reproduce**
The issue is not easily reproducible. The few steps to reproduce it are simply to power off the device and plug it to the charger.

**Logs**
Perhaps access to the UART ports will be beneficial to debugging this issue, but at the moment we don't have that setup.

**Attached images**
![kagura-boot-failure](https://user-images.githubusercontent.com/33422321/32779156-ef0b348c-c93c-11e7-9935-1b7209753b79.jpg)

**Comment by jerpelea** [comment]
please update your kernel and common gits to the latest commit 
this bug has been fixed!

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/device-sony-common/commit/1aaf3a86c0526c4cdd3cb9f435dd8d3139c68e3b
https://github.com/sonyxperiadev/kernel/commit/ae8abbc19163390987b8ad8cded5b3a6d64b333b
are critical
