### ISSUE TITLE
[Yoshino] Cosmetic bootscreen issues after switch to SDE

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#371]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.168-g4ebcb68cc743
**Android version:** android-9.0.0_r35
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190405.003 eng.stefan.20190418.191851
**Version baseband:** 1307-7511_47.1.A.16.20

**Description**
Since AOSP build v8 and the switch to SDE I've observed that the boot screen looks partially worse than with previous builds. 

Especially a lot more colorful vertical thin lines are written on the white screen with black Sony logo, sometimes the lines cover the full display of the phone and are not just in the upper part of the display located. 

Also the black Sony logo moves sometimes out of the centered position a little towards the left edge of the phone or also to the right so that the 'y' is line-breaked into the next line.

The symptom is just a cosmetic issue rather than a real problem. Since you may want to fix it I've opened a new dedicated bug for it.

**Symptoms**
A lot of thin colorful vertical lines on the screen. The black Sony logo on the white boot screen is sometimes no longer in a centered position as it used to be in previous aosp builds.  

**How to reproduce**
It happens intermittently when booting.  It seems to be that it more often happens when the phone is connected to usb, but I am unsure if the connection to usb is really related to that...

**Comment by wyzco** [comment]
I have those too.

**Comment by kholk** [comment]
Yes it started appearing after the switch to the SDE driver and yes I'm aware of this issue.
Actually, not only Lilac is affected, as the entire Yoshino platform is! The issue got put on hold (since it is just a cosmetic thing) while we solve major issues on other platforms.

By the way, thanks for reporting!

**Comment by stefanhh0** [comment]
Sure, thanks for your letting us know. I have changed the title of the ticket accordingly.

**Comment by stefanhh0** [comment]
It is fixed now, using

**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14.176-g1fa7ff7f9100:
- https://github.com/sonyxperiadev/kernel/commit/6d2c74a49d312cb49ca65862321cc3c2fd0b890c
- https://github.com/sonyxperiadev/kernel/pull/2252
- https://github.com/sonyxperiadev/kernel/pull/2253
- https://github.com/sonyxperiadev/kernel/pull/2259
- https://github.com/sonyxperiadev/kernel/pull/2260

**Kernel compiler:** clang
**Android version:** android-10.0.0_r36
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v6_yoshino.img
**Version baseband:** 1307-7511_47.2.A.11.228
**Build:** aosp_g8441-userdebug 10 QQ2A.200501.001.B3 eng.stefan.20200510.170705
