### ISSUE TITLE
[Website] Impossible to unlock my Xperia X bootloader

### ISSUE THREAD

**Issue by Mashrmallow** [sonyxperiadev/bug_tracker#372]
**Platform:** Loire
**Device:** Sony Xperia X F5121 (suzu)
**Kernel version:** 3.10.84
**Android version:** Oreo 8.0.0

**Description**
When I try to unlock my bootloader in https://developer.sony.com/develop/open-devices/get-started/unlock-bootloader/ on my PC, I got a white page after submit my IMEI, I tryed different browser but same problem .

**Symptoms**
Impossible to unlock the bootloader .

**How to reproduce**
Try to unlock bootloader of Sony Xperia X F5121 (suzu) on https://developer.sony.com/develop/open-devices/get-started/unlock-bootloader/ .

**Comment by bartcubbins** [comment]
can confirm

**Comment by bartcubbins** [comment]
this bug is gone, can be closed
