### ISSUE TITLE
[Yoshino][Lilac] 3.5mm audio jack connection no longer working

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#373]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.168-g72f952b6f2b5
**Android version:** android-9.0.0_r35
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190405.003 eng.stefan.20190423.201213
**Version baseband:** 1307-7511_47.1.A.16.20

**Description**
When plugging in the headphones to the 3.5mm audio jack the audio is not played on the headphones but on the built-in phone speaker.

**Files**
logcat and dmesg from my attempts playing music via audio jack:
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3110784/dmesg.log)
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3110785/logcat.log)

**Comment by wyzco** [comment]
Mine is working but I'm on different 
kernel 4.9.168-g1d9356496af5
baseband 1310-9560_47.2.A.10.45

**Comment by stefanhh0** [comment]
@wyzco 1d9356496af5 is an older commit, could very well be that the bug was introduced with a more recent changes to one of the git repos. Or my audio jack is broken, which would be very sad.

Regarding the baseband version you are using, you should switch back to 47.1.A.16.20. I am not completely sure but I guess 47.2 is still considered unstable and should not be used together with aosp for the time being. See #361 for reference.

@jerpelea or are there any changes regarding the recommendations for using 47.2 baseband together with aosp?

**Comment by jerpelea** [comment]
please use 47.1.A.16.20 for best stability

**Comment by stefanhh0** [comment]
This wasn't an aosp issue but a dust / filament problem... I have cleaned my audio jack and pulled out some filament stuff... after that it works fine again. Sorry for the noise.
