### ISSUE TITLE
[TAMA][CAMERA] Camera died until restart

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#377]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
I can't use the camera anymore until I restart the device.

**Symptoms**
Black screen or "can't connect to camera"

**How to reproduce**
Open the barcode app "Barcode Scanner" (com.google.zxing.client.android) several times.
Open the AOSP camera app several times and switch between front/back camera and photo and video recording.

[logs-2019-04-28-15-26-17.zip](https://github.com/sonyxperiadev/bug_tracker/files/3125581/logs-2019-04-28-15-26-17.zip)
[logs-2019-04-29-12-22-37.zip](https://github.com/sonyxperiadev/bug_tracker/files/3126975/logs-2019-04-29-12-22-37.zip)
[logs-2019-04-29-12-21-24.zip](https://github.com/sonyxperiadev/bug_tracker/files/3126976/logs-2019-04-29-12-21-24.zip)

**Comment by jerpelea** [comment]
please test on Android 10 and vendor v3 then open a new ticket
