### ISSUE TITLE
[TAMA][CAMERA] Iso range is too small 486-7770 in the "opencamera" app

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#379]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
The iso range is smaller than on stock (from 50 to over 10000)

**Symptoms**
The iso range is smaller than on stock (from 50 to over 10000)

**How to reproduce**
Use the app "opencamera".
Put something on the lens.
Direct the lens into a bright light source.

**Comment by sraase** [comment]
The back camera has not received any exposure tuning as of now. Also, the shown ISO values might be completely bogus for all I know... please be patient.

**Comment by jerpelea** [comment]
please test on Android 10 and vendor v3 then open a new ticket
