### ISSUE TITLE
[TAMA][CAMERA] Distant objects are blurry

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#380]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
Distant objects are blurry

**Symptoms**
Distant objects are blurry

**How to reproduce**
Take a photo from text 5m-10m away.
Stock is far better.

**Comment by oshmoun** [comment]
check if this PR helps
https://github.com/sonyxperiadev/kernel/pull/1921

**Comment by MartinX3** [comment]
Thx
It seems that
sonyxperiadev/kernel#1921
is a workaround
