### ISSUE TITLE
[TAMA][CAMERA] Photos are looking like edited with a sharp filter on bright days 

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#381]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
Photos are looking like edited with a sharp filter on bright days 

**Symptoms**
Photos are looking like edited with a sharp filter on bright days 

**How to reproduce**
Take a photo from green plants at day.

**Comment by jerpelea** [comment]
please test on Android 10 and vendor v3 then open a new ticket
