### ISSUE TITLE
[TAMA][CAMERA] Photos are blurry and noisy if there isn't enough light (stock is better)

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#382]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
Photos are blurry and noisy if there isn't enough light (stock is better)

**Symptoms**
Photos are blurry and noisy if there isn't enough light (stock is better)

**How to reproduce**
Take a photo at the evening or maybe if the day is cloudy

**Comment by sraase** [comment]
The back camera has not received any exposure tuning as of now, so ... yeah, unfortunately this is expected for now. Please be patient.

**Comment by jerpelea** [comment]
please test on Android 10 and vendor v3 then open a new ticket
