### ISSUE TITLE
[TAMA][CAMERA] Frontcamera has wrong colors

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#383]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
Frontcamera has wrong colors.

**Symptoms**
Frontcamera has wrong colors.

**How to reproduce**
Use the front camera in the aosp app.

**Comment by sraase** [comment]
The front camera on Tama has not been tuned at all yet.
Please be patient, we are working on it.

**Comment by MartinX3** [comment]
@sraase
I am patient, i just want to list everything so nothing gets forgotten :)

**Comment by jerpelea** [comment]
please test on Android 10 and vendor v3 then open a new ticket
