### ISSUE TITLE
[TAMA][CAMERA] Backcamera has wrong colors

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#384]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
Backcamera has slightly wrong colors.
Not as bad/often as the frontcamera, but sometimes it happen.

**Symptoms**
Backcamera has slightly wrong colors.

**How to reproduce**
Use the backcamera. Sometimes it happen. Not as often as the frontcamera color bug.

**Comment by sraase** [comment]
The back camera has only received very limited color tuning. If the AWB algorithm selects a color temperature which has not been tuned, the colors will be off. We are aware, please be patient.

**Comment by sraase** [comment]
We still lack required ingredients for decent color-tuning. Sorry for the lack of progress...

**Comment by MartinX3** [comment]
Thank you for the transparent report. This makes any delay not bad. <3

**Comment by jerpelea** [comment]
please test on Android 10 and vendor v3 then open a new ticket
