### ISSUE TITLE
[TAMA][CAMERA] Camera preview is choking

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#385]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
Using "opencamera" app the camera preview is choking and flickering.

**Symptoms**
Using "opencamera" app the camera preview is choking and flickering.

**How to reproduce**
Use the opencamera app and look at the preview.

**Comment by sraase** [comment]
Could you please describe the problem? I can see a noticeable drop in frame rate when the AE algorithm choses long exposure times, but I don't think you refer to that?

**Comment by MartinX3** [comment]
@sraase 
I saw the framerate drop also.
The preview looks like jumping over frame steps.

The problem I am refering to is that as example very tine structures starting to wobbling, moving in the preview like jelly.

It is not the flickering or banding I mean, just like I would move jelly.

Sadly english is not my native language, but I hope I was able to describing it :(

**Comment by sraase** [comment]
I know what you refer to, can reproduce here. Thanks for the description.

(English isn't my native language, either.)

**Comment by jerpelea** [comment]
please test on Android 10 and vendor v3 then open a new ticket
