### ISSUE TITLE
[TAMA][CAMERA] "Opencamera" app focus issues while video recording

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#386]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
"Opencamera" app focus issues while video recording

**Symptoms**
"Opencamera" app focus issues while video recording

**How to reproduce**
Use the "opencamera" app to take video of different distants.
In my example I recorded the environment out of my window and then moved the camera to my computer monitor. There is black on white text didn't got focused.
It works with the AOSP camera app.

**Comment by sraase** [comment]
This is probably an AF tuning issue.

**Comment by jerpelea** [comment]
please test on Android 10 and vendor v3 then open a new ticket
