### ISSUE TITLE
[TAMA][CAMERA] Frontcamera lacks full camera 2 api support (Level_3 & others missing)

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#387]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
I checked the camera 2 api with the app "Camera2 probe" from Google Play Store.
Missing features, which aren't missing because the hardware is limited:
- LEVEL_3

**Comment by sraase** [comment]
The front camera on Akari and Apollo uses a fix-focus lens and does not have a flash LED. As far as I can see, not having these features is correct. What functionality did you expect?

**Comment by MartinX3** [comment]
@sraase 
I just listed first everything do we can sort out the entries which won't get fixed.
So I can remove the 3 entries with the word flash in it?

**Comment by sraase** [comment]
Yes, and also auto-focus does not exist on this hardware.
Regarding the LEVEL_3 issue, this will need fixing (same for the back camera).

**Comment by sraase** [comment]
The LEVEL_3 runs deeper than expected. Please let's continue the discussion in #321, since all sensors are affected.
