### ISSUE TITLE
[TAMA][CAMERA] AOSP camera app camera mode looks zoomed

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#388]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
The AOSP camera app camera mode looks zoomed.
It shoot zoomed pictures too.
In the video mode I see much more out of my view angle.

**Symptoms**
The AOSP camera app camera mode looks zoomed.
It shoot zoomed pictures too.
In the video mode I see much more out of my view angle.

**How to reproduce**
Use the omni aosp camera and switc between recording and camera mode.

**Comment by sraase** [comment]
You are correct. In "(16:9) 15.9 megapixels" mode, the AOSP camera application selects a 2976x2976 mode and crops it down to 16:9 aspect ratio, resulting in 2976x1674. All other modes behave correctly.
