### ISSUE TITLE
[tone] [kagura] Building source fails

### ISSUE THREAD

**Issue by jeroen-1978** [sonyxperiadev/bug_tracker#389]
Platform: tone
Device: kagura
Kernel version: 4.9
Android version: 9.0 Pie

**Description**
Building source fails with fresh tree and removed common-kernel folder.

**How to reproduce**
repo sync -q && ./repo_update.sh
source build/envsetup.sh && lunch aosp_f8331-userdebug
rm -r kernel/sony/msm-4.9/common-kernel
make clean && make -j12

[make output.txt](https://github.com/sonyxperiadev/bug_tracker/files/3127227/make.output.txt)

**Comment by oshmoun** [comment]
seems your host os is missing the `openssl` package

**Comment by jeroen-1978** [comment]
the host os has `openssl` installed.

**Comment by bartcubbins** [comment]
@jeroen-1978 apt install libssl-dev

**Comment by jeroen-1978** [comment]
@bartcubbins Thnx, that solved the problem!

@jerpelea can we add this package to the build manual, to make sure this question isn't asked in the future ?

**Comment by jerpelea** [comment]
thanks for reporting it we will update the build guide
