### ISSUE TITLE
[maple] Recovery UI not available, device stuck at Sony splash screen

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#39]
**Platform:** yoshino
**Device:** maple
**Kernel version:** 4.4 (4cefd8e, built on Nov 14)
**Android version:** 7.1.1
**Firmware version:** v05

**Description**
The recovery UI is not available, and the device seems to be stuck at the Sony splash screen.

**Symptoms**
The white Sony splash screen is shown. The device is booted in recovery mode correctly, since 
`$adb devices` will return something like:
```
List of devices attached
CB512E52WE	recovery
```
and issuing `$adb reboot` will make the device reboot correctly.

**How to reproduce**
Either issue the command `$adb reboot recovery` or if the device is powered off, press and hold the `POWER` and `VOLUME DOWN` buttons simultaneously.

**Logs**
N/A

**Comment by jerpelea** [comment]
releated to 
https://github.com/sonyxperiadev/bug_tracker/issues/31

I am fixing it

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/repo_update/commit/f3f8130845df68a9499c44f4d62d183c0729524a
fixed
