### ISSUE TITLE
[TAMA][AKARI] Flickering and screen artefacts with the usage of the apex home screen launcher

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#390]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
Flickering and screen artefacts with the usage of the apex home screen launcher

**Symptoms**
While using the omnirom dialog notifications breaking while animating.
The complete screen shows just the screen without any icons / elements for a second or less (flickering)

**How to reproduce**
Install the apex launcher
https://play.google.com/store/apps/details?id=com.anddoes.launcher

[log_by_raphos.zip](https://github.com/sonyxperiadev/bug_tracker/files/3128565/log_by_raphos.zip)
[logs-2019-04-29-18-57-25.zip](https://github.com/sonyxperiadev/bug_tracker/files/3128566/logs-2019-04-29-18-57-25.zip)

I found entries like
`04-29 18:57:14.932 W/OpenGLRenderer(18785): Incorrectly called buildLayer on View: PageIndicatorLineCaret, destroying layer...`

**Comment by kholk** [comment]
Are you sure that this is not a ROM/app issue?

I have never seen _anything_ like that, literally, on Akatsuki (which is the exact same
in this specific context).

**Comment by MartinX3** [comment]
I only see it in the apex launcher while using it a bit.
My omnirom build is from the 22. April 2019.

I don't know if the apex launcher triggers a bug or if itself has a bug, since the source code is sadly not open.

**Comment by jerpelea** [comment]
I can not replicate the bug on a fresh build

**Comment by MartinX3** [comment]
With the app "apex launcher" @jerpelea ?

**Comment by jerpelea** [comment]
AOSP and another launcher

**Comment by jerpelea** [comment]
I will try ASAP the APEX launcher on AOSP

**Comment by MartinX3** [comment]
It may take a few minutes playing and maybe you need to get a notification to trigger this weird graphics
The notification is then somehow corrupted
