### ISSUE TITLE
[TONE][DORA] No in-call sound at all

### ISSUE THREAD

**Issue by mydevilroot** [sonyxperiadev/bug_tracker#391]
**Platform:** Tone
**Device:** Dora
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
While I am calling someone the other person can't hear me and I can't hear him as well.
Also in reverted way, the same situation happens while someone calls me.

**Symptoms**
No in-call audio in phone calls at all.

**How to reproduce**
Built latest rom for dora (number 26) flash it with latest oem, try to make a phone call.

**Comment by kholk** [comment]
Have you built AOSP or some sort of other custom ROM?

In case, please build AOSP by following the directions on Sony's website:
https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0

**Comment by mydevilroot** [comment]
> 
> 
> Have you built AOSP or some sort of other custom ROM?
> 
> In case, please build AOSP by following the directions on Sony's website:
> https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0

Hi kholk,

Thank you for reply. Answering on your questions: 
Yes.

I've built official AOSP from Sony website by following directions - official one, reported bug present.
I've also built "SonyAOSP" from https://github.com/SonyAosp -> same result.
The very same result applies to "Omnirom" for Dora. No luck.

I have no idea what's wrong to be honest, any help would be really appreciated. I really would like to build fully working rom and share it on XDA. Thanks a lot for help in advance

**Comment by kholk** [comment]
Well, the last time I tried any Tone phone the whole thing was working flawlessly and was sleeping like a (crazy) baby (well, frequent wakeups for milliseconds and then back to sleep, that's OK).

What you are experiencing is truly strange.

I will build a ROM and will try to reproduce your issue locally ASAP. Please hold on for some moments..... :)

**Comment by mydevilroot** [comment]
> 
> 
> Well, the last time I tried any Tone phone the whole thing was working flawlessly and was sleeping like a (crazy) baby (well, frequent wakeups for milliseconds and then back to sleep, that's OK).
> 
> What you are experiencing is truly strange.
> 
> I will build a ROM and will try to reproduce your issue locally ASAP. Please hold on for some moments..... :)

Thanks a lot kholk for your efforts and time that you will spent on investigating the issues, please feel free to ask me anything, I will do my best to provide you information, or pre-built faulty rom. I still have build from 04 May 2019 (sonyAOSP) on my google drive online.

**Comment by jerpelea** [comment]
please check that adsprpcd is started correctly

**Comment by ix5** [comment]
The tone platform (dora, kagura, keyaki) did have some sound bugs but they should be fixed now.
If you still experience issues, maybe try https://github.com/sonyxperiadev/device-sony-common/pull/598

As @jerpelea wrote, the `vendor.adsprpcd` service may not start and thus takes all sound down with it.
You can check services with `ps -A` and `grep` for `adsprpcd`.

**Comment by jerpelea** [comment]
I can not replicate the bug on a fresh build

**Comment by mydevilroot** [comment]
> 
> 
> I can not replicate the bug on a fresh build

@jerpelea - Sadly I can reproduce on today's build (I had no chance of building previous ones, because I was away from Country without access to build server)

The issue is still present.
I've also noticed, that on Telegram app I can make a call, I can hear the other person, but he/she can't hear me. That's weird.

Could you please double check what's going on ? Maybe the fix was reverted by mistake ?
I will appreciate time spent on that. This is major bug for me and the last one that is preventing me (and other soon on XDA) to use the rom as daily driver. Thanks a lot for your time and efforts, again!

@ix5 - Thanks a lot for your content on this case too!

**Comment by ix5** [comment]
Just another idea @mydevilroot https://sx.ix5.org/info/post/dsp-file-relabling-for-sodp/
