### ISSUE TITLE
[Yoshino][Lilac] SIM PIN operation failed!

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#393]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.170-g705ae8e2576c
**Android version:** android-9.0.0_r35
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190405.003 eng.stefan.20190502.183239
**Version baseband:** 1308-8921_47.1.A.16.20

**Description**
- Flashed clean stock (G8441_Customized_US_1310-4371_47.1.A.16.20_R8B) 
- booted into it with inserted SIM
- Shutdown 
- Flashed an aosp build without any changes (no magisk, no gapps, no restored userdata) 

Directly after booting there is a new Message that wasn't shown on former aosp builds:
```
Android System
There's an internal problem 
with your device. Contact your 
manufacturer for details.
```
The message can be closed with OK

The SIM PIN dialog is shown. Below the SIM PIN dialog there are three different messages that switch over time in an arbitrary order:
```
SIM CARD IS LOCKED. - EMERGENCY CALLS ONLY
NO SERVICE
SIM CARD IS LOCKED. - NO SERVICE
```

When entering in that situation the SIM PIN, a message `SIM PIN operation failed!` is shown. Or if the SIM PIN was accepted then the SIM PIN is requested again after a short period of time.

Such a behavior is not happening on the stock.

When waiting a minute or so until SIM CARD IS LOCKED. - EMERGENCY CALLS ONLY remains below the SIM PIN dialog stable, then the SIM PIN can be entered without any problems.

I have the suspicion this problem is related to the shutdown problem in #375.

**How to reproduce**
- Flash stock G8441_Customized_US_1310-4371_47.1.A.16.20_R8B via emma (full flash not only firmware)
- Boot with inserted SIM
- Shutdown
- Flash a clean build of AOSP with fastboot
- Boot the phone
- Immediately after boot (don't wait!) enter SIM PIN -> SIM PIN operation failed! Message
- Now you have to reenter SIM PIN
- Sometimes even after SIM PIN was entered successfully the phone requests again entering the SIM PIN.
This is reproducible for me on every boot when entering the PIN immediately after bootup.

**Files**
I have collected logs after that happened:
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3144059/logcat.log)
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3144060/dmesg.log)
[bugreport-aosp_g8441-PQ2A.190405.003-2019-05-04-07-11-35.zip](https://github.com/sonyxperiadev/bug_tracker/files/3144061/bugreport-aosp_g8441-PQ2A.190405.003-2019-05-04-07-11-35.zip)

**Comment by stefanhh0** [comment]
**Kernel version:** 4.9.170-g36f5442b4dcc
**Android version:** android-9.0.0_r35
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190405.003 eng.stefan.20190502.183239
**Version baseband:** 1308-8921_47.1.A.16.20

The SIM card "disappeared" and did not come back (I haven't ejected it, android is no longer seeing it).

Logs are here
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3145126/dmesg.log)
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3145127/logcat.log)

Shortly after that, the phone crashed and rebooted (vibrator was activated twice, double crash?):
[pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/3145137/pstore.tar.gz)

**Comment by ix5** [comment]
> Directly after booting there is a new Message that wasn't shown on former aosp builds:
> 
> ```
> Android System
> There's an internal problem 
> with your device. Contact your 
> manufacturer for details.
> ```
That message is harmless, it only means that the boot-, system- or vendor images have been built at different times (fingerprint mismatch). You can run `make installclean` and then delete `out/target/product/lilac/build_*` before building and the message should disappear.

> **Files**
> I have collected logs after that happened:
> [logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3144059/logcat.log)
> [dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3144060/dmesg.log)
> [bugreport-aosp_g8441-PQ2A.190405.003-2019-05-04-07-11-35.zip](https://github.com/sonyxperiadev/bug_tracker/files/3144061/bugreport-aosp_g8441-PQ2A.190405.003-2019-05-04-07-11-35.zip)

Seems your sensors are borked as well, failing to open/create `sns.reg` (in `/persist/` ?)
```
E Sensors : sns_reg_la.c(287):Error creating registry file
W Sensors : sns_reg_mr.c(367):File init failed 5
[...]
E Sensors : sns_main.c(447):Timeout waiting for SMGR service. Exit sensors daemon!
W Sensors : sns_main.c(355):sns_main_exit called unlock daemon to exit
E Sensors : sns_main.c(561):Exiting! Err 0
```
That causes other parts to fail, e.g.
```
java.lang.RuntimeException: Unable to start receiver com.sony.transmitpower.sensor.FeatureIntentReceiver: java.lang.IllegalStateException: Sensor is null.
```

**Comment by ix5** [comment]
> The SIM card "disappeared" and did not come back (I haven't ejected it, android is no longer seeing it).
> 
> Logs are here
> [dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3145126/dmesg.log)
> [logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3145127/logcat.log)
> 
> Shortly after that, the phone crashed and rebooted (vibrator was activated twice, double crash?):
> [pstore.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/3145137/pstore.tar.gz)

The dmesg doesn't tell anything interesting(afaics), and the logcat as well.
But the pstore console-ramoops shows weird graphics stuff (@kholk somc_panel manager etc), sure the crashes are related to SIM stuff?

**Comment by stefanhh0** [comment]
Thanks a lot for explaining what causes the message to popup, I'll give it a try next time when building.

> sure the crashes are related to SIM stuff?

I am not sure. In fact over the last weeks AOSP was pretty unstable on lilac and crashed / rebooted a lot. With the more recent patches from the last 3 days in kernel it got better, but still not that stable. I hope some of the PR's in kernel will mitigate it a little at least they read as if they have the potential to fix a few of the issues - and also introducing new ones, well that is the game ;-).

Thanks for giving me feedback, very much appreciated. In case you have an idea what to provide additionally to tackle the SIM PIN problem just let me know. However I think it should be reproducible for the ones having a lilac at hand as described above fairly straightforward.

**Comment by stefanhh0** [comment]
The problem has been fixed with all the latest changes from you guys, thanks for all your hard work!

For reference the version infos with that it is working again as expected :
**Kernel version:** 4.9.174-gd7ab313501f1
**Android version:** android-9.0.0_r37
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ3A.190505.002 eng.stefan.20190514.014237
**Version baseband:** 1308-8921_47.1.A.16.20

**Comment by stefanhh0** [comment]
> > Directly after booting there is a new Message that wasn't shown on former aosp builds:
> > ```
> > Android System
> > There's an internal problem 
> > with your device. Contact your 
> > manufacturer for details.
> > ```
> 
> That message is harmless, it only means that the boot-, system- or vendor images have been built at different times (fingerprint mismatch). You can run `make installclean` and then delete `out/target/product/lilac/build_*` before building and the message should disappear.

@ix5 I gave that a try doing following:
```
make clean
make installclean
rm out/target/product/lilac/build_*
make -j 4
```
After executing the default target  via `make -j 4` the files out/target/product/lilac/build_* where regenerated and the message is in consequence still popping up when flashing all the images. Do I have to call then a different make target instead of the default target in order to prevent build_* file regeneration?

**Comment by ix5** [comment]
What I do is:
```
make installclean
rm out/target/product/<device>/build_*
make otapackage
```
No need for `make clean`, `installclean` suffices.

The `build_*` files of course get generated during a regular `make` or `make otapackage` or `make systemimage` run, they're the "blueprints" for the props in e.g. `/system/build.prop`.

`isBuildConsistent()` from [frameworks/base/core/java/android/os/Build.java#995](https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-9.0.0_r39/core/java/android/os/Build.java#995) checks whether `ro.build.fingerprint` and `ro.vendor.build.fingerprint` match.

We at SODP have an [additional check that compares](https://android-review.googlesource.com/c/platform/frameworks/base/+/728575) `ro.odm.expect.version` and `ro.odm.version` (which is set in `/odm/build.prop`).

If you check your logs at startup, you should see which check is failing, look out for `Mismatched fingerprints` messages.

My guess is that `/system/build.prop` and `/vendor/build.prop` do not have matching fingerprints, you can compare `out/target/product/lilac/system/build.prop` and `out/target/product/lilac/vendor/build.prop` to confirm.

If you're doing a simple `make`, the fingerprints should not be mismatched. But try anyway with `make otapackage` and see whether the issue persists.

**Comment by jamuir** [comment]
> We at SODP have an additional check that compares ro.odm.expect.version and ro.odm.version (which is set in /odm/build.prop).

@stefanhh0:  if it is the odm check that is failing, then you need to download a new SW-binaries package and flash your oem/odm image.

**Comment by ix5** [comment]
@jamuir he has the right odm version, see the first post.

**Comment by stefanhh0** [comment]
Cool, thanks for all the explanation, I have investigated it a little more but still couldn't figure out what is wrong.

Here is what I did:
```
stefan@mars:~/android/source/out/target/product/lilac$ find . -name build.prop
./obj/ETC/system_build_prop_intermediates/build.prop
./system/product/build.prop
./system/build.prop
./vendor/build.prop
./odm/build.prop

stefan@mars:~/android/source/out/target/product/lilac$ find . -name build.prop -exec grep -H -e 'ro.*fingerprint' '{}' \;
./obj/ETC/system_build_prop_intermediates/build.prop:ro.build.fingerprint=Sony/aosp_g8441/lilac:9/PQ3A.190505.002/stefan05162312:userdebug/test-keys
./system/build.prop:ro.build.fingerprint=Sony/aosp_g8441/lilac:9/PQ3A.190505.002/stefan05162312:userdebug/test-keys
./vendor/build.prop:ro.vendor.build.fingerprint=Sony/aosp_g8441/lilac:9/PQ3A.190505.002/stefan05162312:userdebug/test-keys

stefan@mars:~/android/source/out/target/product/lilac$ find . -name build.prop -exec grep -H -e 'ro.odm' '{}' \;
./vendor/build.prop:ro.odm.expect.version=9_4.9_yoshino_v8
./odm/build.prop:ro.odm.version=9_4.9_yoshino_v8
```

Those are the images I have flashed:
```
stefan@mars:~/android/bin/current$ ls -l
insgesamt 28
lrwxrwxrwx 1 stefan stefan 22 Mai 17 05:33 boot.img -> ../2019_05_16/boot.img
lrwxrwxrwx 1 stefan stefan 23 Mai 17 05:33 cache.img -> ../2019_05_16/cache.img
lrwxrwxrwx 1 stefan stefan 58 Apr 18 23:14 oem.img -> ../SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
lrwxrwxrwx 1 stefan stefan 31 Apr 26 01:55 recovery.img -> ../twrp-3.3.3-0-lilac-pie-1.img
lrwxrwxrwx 1 stefan stefan 24 Mai 17 05:33 system.img -> ../2019_05_16/system.img
lrwxrwxrwx 1 stefan stefan 24 Mai 17 05:33 vendor.img -> ../2019_05_16/vendor.img
```
So boot, cache, system and vendor are from the very same build.

Then I checked via adb shell:
```
lilac:/ $ getprop |grep -e 'ro.*fingerprint'
[ro.bootimage.build.fingerprint]: [Sony/aosp_g8441/lilac:9/PQ3A.190505.002/stefan05162312:userdebug/test-keys]
[ro.build.fingerprint]: [Sony/aosp_g8441/lilac:9/PQ3A.190505.002/stefan05162312:userdebug/test-keys]
[ro.vendor.build.fingerprint]: [Sony/aosp_g8441/lilac:9/PQ3A.190505.002/stefan05162312:userdebug/test-keys]

lilac:/ $ getprop |grep -e 'ro.odm'                                                                                                                                                                                                                       
[ro.odm.expect.version]: [9_4.9_yoshino_v8]
[ro.odm.version]: [9_4.9_yoshino_v8]
```
So that seems all to be rather consistent.

The output of:
```
Slog.e(TAG, "Mismatched fingerprints; system reported " + system
                        + " but vendor reported " + vendor);'
```
Could have been found in logcat, right?

So I grepped for it:
`lilac:/ $ logcat -d|grep -e fingerprints -e '[Mm]ismatch'`
and nothing was returned.

Additionally I have grepped for parts of the actual message:
`lilac:/ $ logcat -d|grep -i "internal problem"`
`lilac:/ $ logcat -d|grep -i "manufacturer"`
But that didn't show anything as well.

Is there something else that could trigger the message?
Well one thing I have observed is, that the output of following is now different then it used to be:
lilac:/ # uname -a
`Linux localhost 4.9.174-gfc821b0441e9 #1 SMP PREEMPT Thu May 16 23:39:02 CEST 2019 aarch64`

It used to be normally with a "-dirty" postfix like this:
`Linux localhost 4.9.174-gfc821b0441e9-dirty #1 SMP PREEMPT Thu May 16 23:39:02 CEST 2019 aarch64`

[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3193592/logcat.log)

Not that it is a a severe issue, but it would be just nice to know what is going on/wrong here.

**Comment by jerpelea** [comment]
@stefanhh0 
revert this patch
https://github.com/sonyxperiadev/kernel/commit/96e6d64d2d0cda43e77ef5274bd1118362c1d0c2

**Comment by stefanhh0** [comment]
@jerpelea reverted that commit and the message is gone now.

@all Thanks for your help and wish you a nice weekend :-)
