### ISSUE TITLE
[TAMA][CAMERA] Backcamera Megapixel count is too low

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#394]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
The sodp camera megapixel count is far lower than on stock.

**Symptoms**
StockFirmware -> 4:3 19MP & 16:9 17MP

SODP
OpenCamera & aosp camera -> 4:3 12MP & 16:9 15.87MP
GCAM -> 4;3 12MP

**How to reproduce**
Use a GCAM, use "OpenCamera", use the aosp camera, use stock.

**Comment by sraase** [comment]
On SODP, the highest available resolution is 5504x3104 (17.1 MP, 16:9 aspect ratio). You can check this by running "adb shell -n dumpsys media.camera" in availableStreamConfigurations.

Stock firmware also supports 5072x3808 (19.3 MP, 4:3 aspect ratio). We do not support this resolution for multiple reasons.

**Comment by MartinX3** [comment]
Dear @sraase ,
thank you again for your transparent response!

Is it possible to explain us the reasons, so we know why it will be never possible?

**Comment by sraase** [comment]
It broke Android CTS (compatibility test suite) in multiple ways. The imx400 is a multi-aspect sensor, so all modes are cropped. But Android requires that the activeArraySize is a valid mode and that no mode exceeds the activeArraySize (either horizontally or vertically). We chose 16:9 because it is closer to 30 fps (another Android requirement).

**Comment by MarijnS95** [comment]
@sraase Any idea how stock (and other OEMs that use multi-aspect sensors, which there probably are) work around this CTS test? It would be nice to have all modes available, after all.

**Comment by sraase** [comment]
The 4:3 mode causes a laggy camera since it doesn't do 30 fps (the 16:9 mode comes close).

**Comment by MarijnS95** [comment]
Is this a limitation of the hardware or the software? If the former, how does stock deal with that lagginess on 19.2MP?

**Comment by sraase** [comment]
It is a hardware limitation. Stock does not support those modes for video.

**Comment by lapineige** [comment]
So, if I understand correctly, you mean it's not possible to display the highest resolution onscreen while previewing camera data, but that the maximum resolution is used for the final picture ?

**Comment by sraase** [comment]
In the Camera2 API design, the sensor mode is decided once when a session is opened. So the maximum possible resolution (configured per-session) decides the preview frame rate, even if the preview resolution is much lower. We do not change sensor mode within a session.

**Comment by lapineige** [comment]
Ok, so that means the maximum picture resolution will be the 16:9  17MP one. Correct ?
Thanks for the explanation.

**Comment by sraase** [comment]
Correct. :-)
