### ISSUE TITLE
HDMI MHL

### ISSUE THREAD

**Issue by Gouster4** [sonyxperiadev/bug_tracker#395]
**Platform:Tama
**Device:Akari
**Kernel version:4.9
**Android version:Pie

**Description**
My phone isnt working with HDMI MHL Adapter.

**Symptoms**
Found connected device on tv, but got black screen and no audio.

**How to reproduce**
Just connect type-c HDMI adapter to phone and tv and try.

I know that this function wasnt working even in stock. But HW is ready for it, we just need SW solution.

**Comment by kholk** [comment]
I'm sorry to inform you that there is no MHL chip on the motherboard of any SoMC Tama device.
Also, the integrated HDMI in the SDM845 SoC is not wired to the connector.

This issue can be closed.

**Comment by Gouster4** [comment]
Oh. Souch a shame. Even my oooold xperia neo had builtin hdmi. My old xperia z1c was working with HDMI MHL, and XZ2 isnt. Why sony? U have prepared solution right on plate (SMD845 integrated HDMI), and u dont wire it. SONY, im disappointed about your HW.

**Comment by jerpelea** [comment]
there is nothing that we can do
