### ISSUE TITLE
DualShock4 Bluetooth

### ISSUE THREAD

**Issue by Gouster4** [sonyxperiadev/bug_tracker#396]
**Platform:Tama
**Device:Akari
**Kernel version:4.9
**Android version:Pie

**Description**
Dualshock4 controller mappings should be implemented in Pie.
It is working over OTG, but not over BT

**Symptoms**
DS4 got paired to my phone and successfully connected, but it doesnt do any input.

**How to reproduce**
Pair and connect DualShock4 controller.

**Comment by jerpelea** [comment]
I will take a look at this bug
