### ISSUE TITLE
[Akatsuki] [Tama] XZ3 not recognized by fastboot (Wrong driver uploaded to Sony website perhaps?)

### ISSUE THREAD

**Issue by QuadPiece** [sonyxperiadev/bug_tracker#398]
**Platform: Windows 10 x64 Enterprise** 
**Device: XZ3 (H9436)** 
**Kernel version: N/A** 
**Android version: N/A** 

**Description**
I was following the guide to unlock my phone's bootloader on a Windows machine: https://developer.sony.com/develop/open-devices/get-started/unlock-bootloader/how-to-unlock-bootloader/

During step 3 it tells me to install an `android_winbus.inf` file that is not referenced anywhere previously, and no link is provided for it. I assume it is the Android USB driver for fastboot, so I found this page via Google and downloaded the driver labeled "XZ3": https://developer.sony.com/develop/drivers/

![firefox_2019-05-08_12-49-50](https://user-images.githubusercontent.com/6379091/57370201-d6d42480-718f-11e9-83bd-dc8936e9ba4f.png)

However I am unable to install the driver as the device IDs in the .inf file do not match the IDs Windows 10 detected for my XZ3.

![firefox_2019-05-08_12-35-51](https://user-images.githubusercontent.com/6379091/57370026-67f6cb80-718f-11e9-904a-6c4ddce4178d.png)

As there is no driver for the "Android" device, fastboot does not recognize my phone, even though it should be accepting connections (LED is Blue)

If it helps, my phone was bought in Norway and had a "Nordic Edition" sticker on it. I doubt the "Nordic Edition" sticker was anything more than a marketing thing though.

**Comment by kholk** [comment]
@jerpelea ouch! That's bad!


@QuadPiece while this issue gets solved officially, I can advice you to install the adb/fastboot drivers from Google instead. These ones should work totally fine.

**Comment by QuadPiece** [comment]
I already have the Google adb/fastboot driver installed (Since I own a Google Pixel)

But that doesn't seem to recognize my XZ3 and get used either. I assume I can just edit the `.inf` file and add the correct hardware ID before installing the driver, but I prefer not risking damage to my device. And I'm mainly a Linux user, so this doesn't affect me that much. Just thought it was worth reporting.

**Comment by kholk** [comment]
You can safely edit that inf file, nothing will get damaged, don't worry!

**Comment by mydevilroot** [comment]
I had similar problems with fastboot driver (under windows), I've fixed it by manually installing the google one ( https://developer.android.com/studio/run/win-usb ) and then manually installing the driver by device management, and selecting Google Driver from the list. Works perfectly fine.

Under linux (Manjaro for flashing / ubuntu for building on google cloud) everything works flawlessly fine.

**Comment by jerpelea** [comment]
you can safely use the Google driver
