### ISSUE TITLE
 [LOIRE] [ALL] Wifi breaks deep sleep

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#4]
**Platform**: SoMC Loire
**Device**: ALL
**Kernel version**: 4.4.xx
**Android version**: 8.0 (/ALL)

**Description**
Activating wifi on loire needs to instabilities, especially when the device tries to sleep.

**How to reproduce**
1. Enable wifi
2. Connect to a network
3. Leave device idle
4. As soon as device tries to deep sleep, it should become very laggy, and reboot at some point.

**Comment by kholk** [comment]
I have pushed 3/4 of the fix, relying in the Linux MMC API.
The issue can be closed after @oshmoun's PR that will update the SDIO management in BCMDHD driver as, with modifications from both of us, the issue is resolved.

**Comment by oshmoun** [comment]
Pr is ready
https://github.com/sonyxperiadev/kernel/pull/1489

**Comment by jerpelea** [comment]
fixed with the latest patches
