### ISSUE TITLE
[ALL] Front camera is unable to focus as expected

### ISSUE THREAD

**Issue by kholk** [sonyxperiadev/bug_tracker#40]
**Platform:** SoMC Loire/Tone/Yoshino
**Device:** ALL (Kugo excluded)
**Kernel version:** LA.UM.5.7.r1 4.4 4047fef
**Android version:** 8.0.0 
**ODM Image version:** v5

**Description**
Issue happening only on front cameras with actuator (all devices, Kugo excluded as it is fixed focus).
The focus ranges seem to be wrong on the infinity side of the range.

**Symptoms**
Blurry preview, blurry photos when the subject is located at more than 40 centimeters of distance from the phone.

**How to reproduce**
The easiest way to reproduce is to try to take a picture of text at more than 40cm of distance from it.
More commonly, reproducible by distending your arm and trying to take a selfie.

**Comment by erikcas** [comment]
seems to be fine on suzu

**Comment by kholk** [comment]
Erik, on 3.10 is fine. It's broken on 4.4 only.

**Comment by erikcas** [comment]
@kholk I just doublechecked. I really built Oreo k4.4 and running it

**Comment by jerpelea** [comment]
improved in v6 release
