### ISSUE TITLE
[Akari] [Apollo] [Akatsuki] Wrong battery capacity

### ISSUE THREAD

**Issue by sboukortt** [sonyxperiadev/bug_tracker#400]
**Platform:** Tama
**Device:** Akari, Apollo, Akatsuki
**Kernel version:** 4.9
**Android version:** 9

**Description**
The battery capacities indicated in those devices’ `power_profile.xml` files do not match their official specifications.

More specifically:

- the XZ2 (Akari) should have [3180](https://www.sonymobile.com/global-en/products/phones/xperia-xz2/specifications/) instead of the current value of [3060](https://github.com/sonyxperiadev/device-sony-akari/blob/ab32260d5341b25d85e9d3a904c7968eb19061e7/overlay/frameworks/base/core/res/res/xml/power_profile.xml#L135)
- the XZ2 Compact (Apollo) should have [2870](https://www.sonymobile.com/global-en/products/phones/xperia-xz2-compact/specifications/) instead of [2760](https://github.com/sonyxperiadev/device-sony-apollo/blob/db920e459c6f746e270dd06b78f06b60819908a5/overlay/frameworks/base/core/res/res/xml/power_profile.xml#L135)
- the XZ3 (Akatsuki) should have [3330](https://www.sonymobile.com/global-en/products/phones/xperia-xz3/specifications/) instead of [3060](https://github.com/sonyxperiadev/device-sony-akatsuki/blob/ede347420027a64e15d0bd07b06beaaf610eb503/overlay/frameworks/base/core/res/res/xml/power_profile.xml#L135)

**Symptoms**
Applications such as [AccuBattery](https://play.google.com/store/apps/details?id=com.digibites.accubattery) or [AIDA64](https://play.google.com/store/apps/details?id=com.finalwire.aida64) report the wrong battery capacity.

![aida64](https://user-images.githubusercontent.com/16757512/57581318-f7fd8380-74b5-11e9-92a3-eb3fac602520.png)

**Comment by MartinX3** [comment]
Nice, thank you for reporting it (in the right place! :)

https://github.com/sonyxperiadev/device-sony-akatsuki/pull/15
https://github.com/sonyxperiadev/device-sony-akari/pull/17
https://github.com/sonyxperiadev/device-sony-apollo/pull/19

**Comment by sboukortt** [comment]
And thank you for the very quick fix! Sorry for the initial report, I did not know about this separate repository.

**Comment by MartinX3** [comment]
Just close the other and everything is fine. You're welcome! :)

**Comment by MartinX3** [comment]
@sboukortt 
https://d3nevzfk7ii3be.cloudfront.net/igi/3mrHqTXHEBvMWC2n.huge
The battery has 2 values.
One is a "minimal value", which is used in the stock firmware and the sodp firmware.
The second one is a higher value, used on the sony product datasheet on the website.
So the minimal value is okay.

It is the first time I saw this. Maybe this is normal and I just didn't recognized it in the past on otherphones. Hmmm.
So this issue ticket can be closed. :)
