### ISSUE TITLE
Kugo headphone sound problem

### ISSUE THREAD

**Issue by maluus** [sonyxperiadev/bug_tracker#404]
Platform: Loire
Device: Kugo
Kernel version: 4.9
Android version: 9

Description
When a wired headphone plugged in device continue to act as if it wasn't and all and every sound (music, ringtone, in call audio etc.) continues to come from speaker. Tried with two different headphones and both are the same. Also tested the headphones on other devices and no problem at all. (Probably one of the recent commits causes this because there wasn't such a problem a few weeks ago.) 
You can find attached logs. 
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3194245/dmesg.log)
[logcat_05-18-2019_12-45-44.txt](https://github.com/sonyxperiadev/bug_tracker/files/3194246/logcat_05-18-2019_12-45-44.txt)

Symptoms
No sound from wired headphones and device act as if it wasn't plugged in. 

How to reproduce
Just plug a wired headphone and try to listen music or make a phone call.

**Comment by stefanhh0** [comment]
I had such a problem as well some time back (see #373). You should check whether or not you have the same problem. I have just used a needle to pull out quite some dust and filament out of the audio jack afterwards physical connection was working again...

**Comment by harryharryharry** [comment]
No, this is a regression caused by:
https://github.com/sonyxperiadev/kernel/pull/1986

It's already on the radar, waiting to be fixed.

**Comment by maluus** [comment]
Pretty sure it's not a physical problem because after every test I'm restoring twrp backup which is stock 118 and its working normally.
________________________________

**Comment by harryharryharry** [comment]
Yeah, no doubt the PR I mentioned causes this issue, I had it myself. Reverting the merge will circumvent the issue.

**Comment by jerpelea** [comment]
fixed
https://github.com/sonyxperiadev/kernel/pull/1991
