### ISSUE TITLE
[kugo] USB OTG mounts and unmounts cyclically

### ISSUE THREAD

**Issue by Mo-Et** [sonyxperiadev/bug_tracker#405]
Platform: Loire

Device: kugo

Kernel version: 4.9

Android version: 9

### Description
When a USB thumbdrive (kingston micro duo type c) is plugged in, it mounts normally but unmounts after a few seconds. It then mounts again, and the process repeats (every 10s approx). I know the drive works because it can be mounted on the stock 34.4.A.118 kugo ROM for example.

[Log](https://vogue.crabdance.com/index.php/s/5ArqQBZnirnTqJJ) (drive is plugged in at 05-18 17:28:54.603 though I've let every message prior to it just in case)

[Dmesg](https://vogue.crabdance.com/index.php/s/2cDWDmf6fFoN9QR)

### Symptoms
Unstable drive cannot be used to copy or read files. 

### How to reproduce
Just plug the USB thumbdrive in.

**Comment by harryharryharry** [comment]
@bartcubbins Maybe you have an idea what's going on with the buffer I/O error in the dmesg?

**Comment by bartcubbins** [comment]
I will take a look and let you know
