### ISSUE TITLE
[tone] [kagura] Camera flashlight not in sync with shutter

### ISSUE THREAD

**Issue by ix5** [sonyxperiadev/bug_tracker#406]
**Platform:** tone
**Device:** kagura
**Kernel version:** 4.9
**Android version:** 9.0 Pie

**Description**
In the AOSP camera app, with flash turned on, the flash fires fine, but the shutter is delayed too much so that the picture is still dark.

**How to reproduce**
Build with `r37` and current kernel HEAD and `v8` binaries, open AOSP camera, turn on flashlight, take a picture.

**Comment by MarijnS95** [comment]
I assumed this was specific to Tama with the new camera framework; seems other phones are affected as well.

**Comment by xarinatan** [comment]
Seems likely, I have issues with the flash (and camera in general) as well but I have a tama apollo (xz2c). Seems like if I turn off autofocus in some applications the flash does manage to sync up, so perhaps the autofocus timing isn't correctly added to the flash delay or something along those lines..

**Comment by rinigus** [comment]
Probably known by others, mainly for pinging. Same goes on AOSP10, v9 binaries. On Tama/Apollo with the flash fired at the wrong time while acquiring image. Flash is used during focusing, switched off and triggered with the delay to ensure that it is not there when it is needed.

**Comment by MarijnS95** [comment]
@rinigus Same on Akatsuki. The snapshot is either too late or goes completely crazy, flickering for multiple seconds (likely trying to compensate for the sudden increase in brightness) before finally taking the picture.

> and triggered with the delay to ensure that it is not there when it is needed.

Unless I'm reading this wrong, "ensure" is an odd choice of words here :thinking: . Are you seeing something in the logs that is intentionally and explicitly (but wrongly) compensating for something?

**Comment by rinigus** [comment]
> Unless I'm reading this wrong, "ensure" is an odd choice of words here thinking . Are you seeing something in the logs that is intentionally and explicitly (but wrongly) compensating for something?

That was supposed to be enclosed with <ironic>, sorry
