### ISSUE TITLE
[Tone] [Kagura] There's an internal problem with your device. Contact your manufacturer for details.

### ISSUE THREAD

**Issue by duncanguthrie** [sonyxperiadev/bug_tracker#408]
**Platform:** Tone
**Device:** Kagura
**Kernel version:** 4.9.174
**Android version:** 9.0.0_r37

**Description**
When starting the device, an error message is displayed.

**Symptoms**
The following message is displayed:
_Android System
There's an internal problem with your device. Contact your manufacturer for details._

Furthermore, infrequently, the device will reboot after confirming 'OK' for this message. It is unclear if this is related.

I have not signed the builds. It uses the test-keys. I am not sure if this is part of the problem and would appreciate any clarification.

**How to reproduce**
I built from the tip of the 9.0.0_r37 revision of local_manifests. That is, p-mr1 for the upstream AOSP parts.

**Comment by jerpelea** [comment]
v9 will be released tomorrow
