### ISSUE TITLE
[tama][apollo] r37 build failed classes.dex hiddenapi

### ISSUE THREAD

**Issue by swisssam** [sonyxperiadev/bug_tracker#409]
**Platform:** tama
**Device:** apollo
**Kernel version:** 4.9
**Android version:** 9.0.0_r37

**Description**
Build fails with below error

**Symptoms**

> FAILED:` out/target/common/obj/JAVA_LIBRARIES/apache-xml_intermediates/dex-hiddenapi/classes.dex
> /bin/bash -c "(rm -rf out/target/common/obj/JAVA_LIBRARIES/apache-xml_intermediates/dex-hiddenapi/ ) && (mkdir -p out/target/common/obj/JAVA_LIBRARIES/apache-xml_intermediates/dex-hiddenapi/ ) && (find out/target/common/obj/JAVA_LIBRARIES/apache-xml_intermediates/dex/ -maxdepth 1 -name \"classes*.dex\" | sort | xargs -I{} cp -f {} out/target/common/obj/JAVA_LIBRARIES/apache-xml_intermediates/dex-hiddenapi/ ) && (find out/target/common/obj/JAVA_LIBRARIES/apache-xml_intermediates/dex-hiddenapi/ -name \"classes*.dex\" | sort | sed 's/^/--dex=/' | xargs out/host/linux-x86/bin/hiddenapi --light-greylist=out/target/common/obj/PACKAGING/hiddenapi-light-greylist.txt --dark-greylist=out/target/common/obj/PACKAGING/hiddenapi-dark-greylist.txt --blacklist=out/target/common/obj/PACKAGING/hiddenapi-blacklist.txt )"
> hiddenapi E 05-24 08:49:09 15162 15162 hiddenapi.cc:47] No DEX files specified
> hiddenapi E 05-24 08:49:09 15162 15162 hiddenapi.cc:47] Command: out/host/linux-x86/bin/hiddenapi --light-greylist=out/target/common/obj/PACKAGING/hiddenapi-light-greylist.txt --dark-greylist=out/target/common/obj/PACKAGING/hiddenapi-dark-greylist.txt --blacklist=out/target/common/obj/PACKAGING/hiddenapi-blacklist.txt
> hiddenapi E 05-24 08:49:09 15162 15162 hiddenapi.cc:47] Usage: hiddenapi [options]...
> 

**How to reproduce**
Building on Archlinux. Using a virtualenv for python2 and JAVA_HOME pointing to java-8-openjdk. Build fails during make after repo_update.sh, source build/envsetup.sh, lunch aosp_h8324-userdebug, make.

**Comment by ix5** [comment]
> Arch Linux

My guess is that the Java shipped with Arch is incompatible with the Android-required Java. It happens quite often that Arch is too far ahead, e.g. I once had Arch's libc prevent `flex` from running/dump core since the Android build env's `flex` was too out of date.

Not until too recently, Android was recommended to be built on Ubuntu 14.04 and then 16.04.

I'd advise you to save yourself some trouble and bite the bullet by setting up a Ubuntu `chroot`. For specifics you can take a look at my [Building Android](https://sx.ix5.org/info/building-android/#ubuntu-chroot) guide or DDG/Google.

**Comment by MartinX3** [comment]
Ubuntu 18.04 / Linux Mint 19.1 works, too.

**Comment by swisssam** [comment]
I probably should have tried that before. It completes fine in a Debian container. Thanks.

**Comment by Mikdadali** [comment]
please some one help

https://del.dog/aikaloguxe.txt

**Comment by MartinX3** [comment]
@Mikdadali you accidentally built for oneplus3
Please build for a supported xperia device
