### ISSUE TITLE
[TAMA] [Apollo] 960FPS mode not available

### ISSUE THREAD

**Issue by xarinatan** [sonyxperiadev/bug_tracker#410]
**Platform:** Tama
**Device:** Apollo (XZ2 Compact)
**Kernel version:** 4.9.170-g96e6d64d2d0c-dirty
**Android version:** 9

**Description**
The 960 FPS mode for the main camera does not appear to function on the opensource ROMs, with or without OEM package. There's no cameras that show 960FPS as available setting or burst modes or anything like that, perhaps it requires a special software though? I have not tested with the official sony camera app as I'd prefer to stay full FOSS. 
I'm not sure on what kind of term this support can be expected, or if at all, so I figured it'd make sense to make a ticket to keep track of it. 

**Symptoms**
no high FPS related settings available in any camera app

**How to reproduce**
Open any camera and search the settings for 960FPS or burst video recording modes

**Comment by jerpelea** [comment]
the 960 fps mode is not available in the OSS implementation

**Comment by xarinatan** [comment]
Very sad to hear, in my opinion that makes it much less of an open device. 
Does that also mean there's no official way for me to ever get that functionality on my phone again, as those binaries are automatically removed when the bootloader is unlocked? As far as I know the camera doesn't work anymore on the official ROM.. But I guess I'll give that another shot then to confirm that :/

**Comment by MartinX3** [comment]
For camera help please visit the XDA twrp central project page for your tama device :)

**Comment by xarinatan** [comment]
I'm sure there's hacky ways to get it working but the whole reason I got this device is because of Sony's 'famed' opensource support. I've used my own ROM so far and been happy about the fact I could use all of Qualcomm's features even without the OEM binaries flashed in, but as soon as Sony steps in with their camera and other bs it turns into a mess, and I find it kind of offensive that Sony gets to get away with barely meeting the legal expectations around Android/Linux GPL and boasting about their amazing opensource support by heavily leaning on Qualcomm's amazing opensource support. The best part of that was when I crippled my phone using the official instructions just to get the absolutely abominable Facebook app off the device, which had been installed as a *SYSTEM APP* somehow, I wonder how much money they got for that joke especially after they've been convicted for the spying practices in their app even if you weren't logged in, absolutely disgusting imho.
 
But whatever, it's legal I guess, just like it's legal for me to never buy another sony device.

**Comment by Paulbouchara** [comment]
Hi, the camera driver which is still in development is done with way less budget as the stock camera driver, so SOD have limited material to calibrate the sensors and the camera modules, furthermore it makes such level of FPS impossible because of thermal reasons, we don't want to fry your sensor just because you wanted a shiny 960fps 5 sec slomo.

If you really want the 960fps, make any gsi (an overlay or whatever) that would support that on stock blobs, then you could do those super slomos.
Cheers in your research and please forgive the SOD team not being able to afford 10k+ equipment for achieving those features.

**Comment by kholk** [comment]
I don't understand your point about "barely meeting the legal expectations" but whatever,
I'm not arguing against other people's opinions, even if I don't think that Sony is doing
anything legally borderline in any way here.

About the camera implementation on Tama (yeah, only on the Tama platform, actually)
on the Open Devices project, I agree that it currently sub-par and not yet ready... and
regarding this I can make you aware of the reason why it's like that.
Simply, the camera for SDM670/845 and later SoCs (XCAM) is totally different, you can
see it from the structure of the blobs that you get if you compare it with releases for
literally any other Sony platform that Open Devices support.

This means that the kind people doing the proprietary part for Open Devices needed
to re-engineer the thing and it is still a work in progress.
Looking at the monthly progress that they've done 'til now, I think that the framework
will provide an OK experience soon-ish but, regarding the 960FPS feature, that will
never be available on Open Devices.

Before you say that "on stock the camera works fine", there's a thing that you need
to know, which is that there is a big difference between stock and Open Devices:
here we're getting Qualcomm's implementation of the camera stuff, while on stock
you have the Sony proprietary "things", which are different.
This is also valid for the other platforms that are supported on Open Devices, such
as Loire, Tone, Nile, Ganges and Yoshino (which are working on the old camera
from Qualcomm that is very VERY usable and, personally, I find it way better than
the Sony implementation on stock ROMs).

Of course, this reply doesn't want to be an excuse for anybody but only a personal
opinion about the matter and my personal encouragement, as a heavy contributor
to this project and as a developer, to all the other developers at Sony and casual
ones, to keep up with the good work. Full respect from me.

Last thing, as a developer, I am sad that you aren't satisfied with the work that
many people (again, from Sony and not from Sony) have done here with their own
sweat in their own spare time that could've been used for other things instead.

**Comment by xarinatan** [comment]
@kholk I'm certainly very happy with the features that do work, and I'm very glad that people do invest effort into it, both outside and inside the company, but I find it sad that outside of Qualcomm's opensource disclosure there's so little commitment from the industry to make the world as a whole better by developing these features on an opensource basis, there's really little reason that that 'proprietary team' with their many resources couldn't contribute to the opensource project, hell the original version could've been opensource to begin with, what would you lose if that was done instead? 

I'm not angry at any people that work towards making the opensource experience better, not @jerpelea or any of the internal devs, nor @MartinX3 or @kholk or any of the other external devs. I'm angry at Sony (and some other companies) for pretending that you get an 'open device' when in reality they never planned on investing the resources to make the device really work on opensource platforms, especially when they're required to provide opensource ROMs to begin with due to the GPL license..
