### ISSUE TITLE
Update/Fix Build Instructions Please

### ISSUE THREAD

**Issue by mmarmm** [sonyxperiadev/bug_tracker#416]
PROBLEM 1:

https://developer.sony.com/develop/open-devices/guides/kernel-compilation-guides/how-to-build-and-flash-a-linux-kernel-for-aosp-supported-devices#ManuallyLinux64 ::

Step 3:

export CROSS_COMPILE=/android/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-

Should be (or at least this is what finally what started building for me until I hit another problem):

export CROSS_COMPILE=/android/aarch64-linux-android-4.9/bin/aarch64-linux-android-

PROBLEM 2:

https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions

Note: "... run Ubuntu (we used Ubuntu 14.04 LTS) ..."

- 14.04 LTS is End of Life: https://lists.ubuntu.com/archives/ubuntu-announce/2019-May/000244.html
- " openjdk-8-jdk " is not found on 14.04
- " zlib1g-dev:i386 " is not found on 14.04

? Are you building on 16.04 or 18.04 ?

Thank you.

**Comment by bartcubbins** [comment]
export CROSS_COMPILE is correct..

**Comment by danielgusvt** [comment]
@mmarmm CROSS_COMPILE should be a prefix, not a folder, so is fine.
Regarding the 2nd problem, I agree and @jerpelea should be noticed

**Comment by mmarmm** [comment]
I've updated the export above but it still needs fixing, git clone creates the final directory but the full path is exported:

git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/

export CROSS_COMPILE=/android/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-

The instructions ask to create /android, git clone creates an aarch64-linux-android-4.9/ directory with bin/aarch64-linux-android-gcc underneath it, no prebuilts directory found under that.
/android/

**Comment by jerpelea** [comment]
@mmarmm thanks for the notification we are using 16.04 LTS and the build guide will be updated ASAP

**Comment by MartinX3** [comment]
18.04 LTS works fine too :)
