### ISSUE TITLE
[LOIRE][KUGO] Sound adjustment problem

### ISSUE THREAD

**Issue by maluus** [sonyxperiadev/bug_tracker#417]
Platform: Loire
Device: Kugo
Kernel version: 4.9
Android version: 9

Description:
Volume buttons adjust media volume instead of notification volume even when no media is playing.
(There is another thing I want to point out but did not opened a new issue because I m not sure if it's intented behaviour or not. on stock firmware when headphones are plugged, both ringtone and notification sounds continue to come out of speakers. But on aosp only ringtone sound comes out of speaker, notification tone sounds only on headphones.)

Symptoms:
As described. 

How to reproduce:
Without playing any media, try to adjust notification volume using vol+/- buttons on the right side.

**Comment by ix5** [comment]
The media volume change should be the default behaviour of Android Pie.

The second point you mention might be messed-up media routes for notifications. @luk1337 you remember what the default should be?

**Comment by luk1337** [comment]
Uh I think that's the default behavior?

**Comment by maluus** [comment]
For the second point I just thought if it was the default behaviour both ringtone sound and notification sound should be coming from the same channel. But if it's the default behaviour there is nothing to whine :D thanks for your attention.
