### ISSUE TITLE
[Loire] [Kugo] Excess battery drain and reboot into recovery

### ISSUE THREAD

**Issue by maluus** [sonyxperiadev/bug_tracker#418]
Platform: Loire
Device: Kugo
Kernel version: 4.9
Android version: 9

Description: 
Last night when I go to sleep battery was around %55. When I woke up phone was in the recovery and battery had been down to %5. I took logs from recovery. Might be related to 9ab03839fa99e6eaf1c0f92fdb31a66c9af86d7a

Symptoms: 
Massive battery drain and boot into recovery. 

How to reproduce:
No idea. 
[recovery.log](https://github.com/sonyxperiadev/bug_tracker/files/3235809/recovery.log)
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3235810/dmesg.log)

**Comment by stefanhh0** [comment]
Just a question is it expected to have such an old kernel in twrp: 3.10.84-perf-g862f029df897?
Recovery shows: Starting TWRP 3.3.0-0-1da568fa. On twrp.me is also already a 3.3.1-0 version available for kugo.

I have a different device and there is no official build available for it, but I found a an up-to-date twrp 3.3.1-0 for it and that one includes kernel 4.4.180. I am not sure if sony aosp still supports  3.10 kernel at all...

**Comment by ix5** [comment]
The real issue here is that your device crashed and rebooted to recovery.
Try to get the contents of `/sys/fs/pstore` once you are in the recovery after another such crash/reboot.

Recovery consuming a lot of battery is another one, but we should not discuss it here.

**Comment by maluus** [comment]
Tonight it happened again. I checked the folder you mentioned in twrp but it was empty.

**Comment by chris42** [comment]
Just to let you know, I experienced a reboot as well. Phone just stopped and restarted. Difference for me: It boots back into system, not recovery.
Will see that I get some logs as soon as this happens again.

**Comment by maluus** [comment]
It still happens often but every time the said folder is empty. Any other way to take that info?

**Comment by maluus** [comment]
Probably gapps or magisk was causing. Magisk updated to 19.3 and I also flashed a recent gapps package and over three days no soft reboots nor reboot into recovery. I'll try a bit more and keep you updated.

**Comment by chris42** [comment]
I have this issue as well now, updated Magisk to 19.3 with no effect. Can't confirm battery drain, as it always happened over night while charging.

Also could not get any information via `/sys/fs/pstore`.
Any idea how to debug this?

**Comment by maluus** [comment]
Unfortunately mine too continues.

**Comment by ix5** [comment]
Can you please try whether https://github.com/sonyxperiadev/kernel/pull/2012 fixes your issue?

**Comment by chris42** [comment]
I always used precompiled kernels. From the documentation I guess following steps will be needed:
- Apply patch
- Delete device/sony/common-kernel
- Build (Kernel will automatically build with patch applied)

Is this correct?

**Comment by ix5** [comment]
The patch for the prebuilt kernel is `kernel/sony/msm-4.9/common-kernel` and you might have to use `make installclean` to get rid of all traces of the prebuilt kernel.
You don't have to delete the whole folder though, you can just replace the contained `Android.mk` and `Android.mk` with empty ones.

**Comment by maluus** [comment]
I also need some help here I guess since I'm not a developer. On my vm switched to folder android /kernel /Sony /msm-4.9/kernel /net /core and truex to run the command git cherry-pick (commit hash) but gives "fatal : bad revision (commit hash) what am I doing wrong?

**Comment by ix5** [comment]
Go to `kernel/sony/msm-4.9/kernel`.

You can't cherry-pick the commits out of thin air, you first need to download them locally. For that, fetch the branch of the pull request:
`git fetch sony pull/2012/head:pull-2012`

Now you can cherry-pick the two commits on top of your own branch:
`git cherry-pick f549197d0c58ad6093f4c7df92c8a1897ac75259 90c1217aab788eaf1114aec5da774070a0c3bfce`

**Comment by maluus** [comment]
Well I never used these commands before. I just searched how to use them and thought command itself would download the code. anyway it's building now. I ll inform you after some testing.

**Comment by chris42** [comment]
Build is running now as well.

@maluus FYI: If you have setup your build environment following the Sony guide, you'll be missing debian package `bc`

Put up an issue for that as well: #426

**Comment by maluus** [comment]
Well I'm building for a long time including kernel but didn't encountered problems. When first started there were some packages missing and I installed them too. May be it was one of them I don't remember. Anyway builded without problems and flashed. Testing now.

**Comment by chris42** [comment]
Flashed my build and phone is working so far. Will need to wait and see if the reboots still occur.

**Comment by maluus** [comment]
At the end of the first day, no reboot into recovery, rebooted once (but it might be related to some other problem. So I didn't alarmed just yet). I'll continue to inform.

**Comment by chris42** [comment]
So had a reboot today as well, while using the gallery and deleting files. Was just a reboot, not into recovery.

However can't tell what went wrong. Is there a way to access the syslog before reboot? With my logging tool I only get stuff starting with the boot!?
Also interesting: After it crashes, I need 2-3 reboots, until the device works again properly. Just after the automatic reboot, it is sluggish, barely any network connection, apps won't start, etc...

Regarding the reboot into recovery: Normally I got it every night, so far everything was fine.

**Comment by stefanhh0** [comment]
@chris42 Provide the files in /sys/fs/pstore after device crash/reboot. Any files in /data/tombstone may also be helpful for further analysis.

**Comment by chris42** [comment]
`/sys/fs/pstore` is empty, I found two tombstones, apparently something regarding fingerprint. O_o Will see that I upload them later.

**Comment by maluus** [comment]
Second day has gone without any crash into recovery or reboot. Also no soft reboots so far. Seems stable.

**Comment by stefanhh0** [comment]
Then this issue can be closed.
