### ISSUE TITLE
[Loire] [Kugo] WifiHAL Errors and connection problems

### ISSUE THREAD

**Issue by chris42** [sonyxperiadev/bug_tracker#419]
**Platform:** Kugo
**Device:** Loire
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
After having connection troubles via wifi, I checked the logs and found following entries over and over
```
E/WifiHAL (558): wifi_get_link_stats: requestResponse Error:-3

E/WifiVendorHal(1038): getWifiLinkLayerStats(l.937) failed {.code = ERROR_NOT_SUPPORTED, .description = }
```
I can't tell if it is connected to my connection problems, however as soon as I switch to mobile data, the problems are gone and reappear after activating wifi again.
Any clue what is wrong or what I could to to figure out what this is?

**How to reproduce**
Compiled AOSP with current guide and vendor image v9, flashed to device

**Comment by chris42** [comment]
So I figured, that it was not the reason of my connection problems, however it is spamming my logs and from time to time the wifi connection is gone.

**Comment by ix5** [comment]
Most likely a problem with the `brcmfmac` Wi-fi driver since it also happens on tone ever since the switch from `bcmdhd`.

`getWifiLinkLayerStats()` not being implemented shouldn't be critical as the stats are only used for bookkeeping, but worth investigating nonetheless.

Drop-outs of Wi-Fi connection are a different beast, what do you see in the logs when the connection drops? A full dmesg+logcat would be helpful.

**Comment by chris42** [comment]
It seems, that the drop out happens when the phone is idle/sleeping for some time. I turn it on and see, that the WiFi is disconnected. It then reconnects, but seems that it looses connection while sleeping.

You find a log here from the last hours: https://pastebin.com/h5SLQ6Du
It includes everything with the term "wifi". I XXXed out some private information.

If you need anything else, let me know.

**Comment by chris42** [comment]
Was anyone able to take a look into this?

**Comment by lATAl** [comment]
`Poplar` has same issue.
If turn off mobile data then remove/add sim card, after restart by click button `restart` in popup, I can connect to the wifi saved. But after it disconnect or if mobile data turn on, can't reconnect again, needs remove/add sim card again :(.

**Comment by ix5** [comment]
This is a separate issue, but tone devices seem to have issues with Wi-Fi not showing any networks at all after some time, needing a reboot.

**Comment by chris42** [comment]
So after building the kernel, #418 and #421 seem to be connected, but that and fix needs confirmation.
#423 apparently was solved just by re-building the kernel.

This issue here seems to be unrelated. My Wifi connection still drops out with new kernel build, as soon as the phone goes idle for a while.
Anything I can do to solve this?

**Comment by chris42** [comment]
Updated now to kernel
`4.9.182-g6593c13-dirty`
and kept baseband (due to nfc errors on other device with .118)
`1302-7793_34.4.A.2.107`

WifiHAL errors still show up and wifi is still disconnecting from time to time and when device is idle.

**Comment by chris42** [comment]
So updated to baseband .118 with the `4.9.182-g6593c13-dirty` kernel. 
Issue still persists and is quite annoying, as most apps do not cope well with the connection interruption.
Anything I can do to help solve this?

**Comment by stefanhh0** [comment]
@chris42 maybe you like to check if https://github.com/sonyxperiadev/kernel/pull/2188 helps.

**Comment by chris42** [comment]
Closing this in favour of #536
As Loire moved to legacy, it is probably better to streamline the infos and progress into one issue.
