### ISSUE TITLE
[loire][tone] location is not being calculated by GPS

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#42]
**Platform:** loire, tone
**Device:** kugo, kagura
**Kernel version:** 4.4
**Android version:** 8.0

**Description**
The device sometimes can't seem to get a location when using GPS.

**Symptoms**
Apps that want to access location fail to do that, or wait indefinitely on a fix.

**How to reproduce**
1. Enable either "High Accuracy" or "Device only" location mode in settings
2. Download the app "Phonetester"
3. Run the app and go to "GPS status"
4. It should try to get a location, but will fail even though it may get a lock on around 6-10 satellites, and even up to 15 in some case.

**Comment by jerpelea** [comment]
tested with Device only on loire,tone and yoshino
GPS position is obtained in 30sec or less with or without SIM

**Comment by jerpelea** [comment]
I can not replicate this bug

**Comment by oshmoun** [comment]
After further tests and comparisons with gps on android N, in the same locations where gps would not get a fix on O, i can say that gps is working just as well as it always has.
Other testers also confirm this observation. 
Closing this issue,sorry!
