### ISSUE TITLE
[TAMA][AKARI] Android Auto not supported

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#420]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
Android Auto not compatible.
According to Google the XZ2 and the car I tested it with are listed as compatible.

**Symptoms**
The car said no compatible device is connected, if I want to project the device or show the pictures.
Google Services say that my device is connected to an android auto car.

**How to reproduce**
Connect the device via bluetooth and usb cable.
Install the android auto app.
Use it.

I used the app "MatLog" to save the logs.
[device_info.txt](https://github.com/sonyxperiadev/bug_tracker/files/3247886/device_info.txt)
[dmesg.txt](https://github.com/sonyxperiadev/bug_tracker/files/3247887/dmesg.txt)

PS:
It was just a car I got access to for a short time as co-driver.
I do not know when I'll get access to an auto car again.

OnePlus 6 (SMD845) with OmniROM 9.0 works with android auto.

**Comment by jerpelea** [comment]
we do not support Android Apps
