### ISSUE TITLE
[Loire] [Kugo] Often Soft Resets 

### ISSUE THREAD

**Issue by maluus** [sonyxperiadev/bug_tracker#421]
Platform: Loire 
Device: Kugo 
Kernel version: 4.9 
Android version: 9 

Description:
Recently phone started to soft reset. I can't point out any specific case. It happens sometimes opening music player, sometimes reading an article on browser or on launcher main screen. It happens few times a day. Logs from the last time (During Web browsing) are attached. 
[2019-06-04_23.43.zip](https://github.com/sonyxperiadev/bug_tracker/files/3254476/2019-06-04_23.43.zip)

Symptoms: 
Device soft resets. 

How to reproduce:
Nothing to specify

**Comment by maluus** [comment]
Probably gapps or magisk was causing. Magisk updated to 19.3 and I also flashed a recent gapps package and over three days no soft reboots nor reboot into recovery. I'll try a bit more and keep you updated.

**Comment by chris42** [comment]
I have this issue as well now, updated Magisk to 19.3 with no effect. Will see that I gather some logs, however not sure, if logs are restarted after soft reset.

**Comment by ix5** [comment]
Can you please try whether https://github.com/sonyxperiadev/kernel/pull/2012 fixes your issue?

**Comment by chris42** [comment]
Just flashed new build with [sonyxperiadev/kernel#2012](https://github.com/sonyxperiadev/kernel/pull/2012). Will need some time to see if it is stable.

**Comment by maluus** [comment]
No soft resets so far. I'll inform after further use.

**Comment by maluus** [comment]
@jerpelea this issue was related to #418 and the same commits seem to solve this issue as well.

**Comment by chris42** [comment]
I am not sure if this is solved. I had two reboots since using the proposed commits. However I am not sure if this is connected. Will open a new issue, as soon as I encounter it again.
