### ISSUE TITLE
[dora] Can't connect to camera

### ISSUE THREAD

**Issue by billchenchina** [sonyxperiadev/bug_tracker#422]
**Platform:** Tone
**Device:** Dora
**Kernel version:** 4.9.177-g69cc32601555-dirty
**Android version:** 9

**Description**

Camera doesnt work

**Symptoms**

https://github.com/sonyxperiadev/bug_tracker/issues/250#issuecomment-441877626

Camera works well when phone just boot up, After some time, cant connect to Camera sometimes. Other times, the camers just turned green in color.

**How to reproduce**

Open camera app.

**Comment by billchenchina** [comment]
![Screenshot_20190612-091112](https://user-images.githubusercontent.com/7758042/59316682-45a61f80-8cf2-11e9-8a4e-c0eb3a647a2f.png)
This is a screenshot of the camera when the camera becomes green.

**Comment by billchenchina** [comment]
![IMG_20190612_091554](https://user-images.githubusercontent.com/7758042/59316783-bb11f000-8cf2-11e9-9528-c16be3172414.jpg)
Normal photo captured using front cam

**Comment by ix5** [comment]
Can you see whether https://github.com/sonyxperiadev/camera/pull/114 helps?

**Comment by billchenchina** [comment]
> Can you see whether [sonyxperiadev/camera#114](https://github.com/sonyxperiadev/camera/pull/114) helps?

Haven't, I'll try it soon. Thanks.

**Comment by sraase** [comment]
I had the same issue on nile, rebuilding the kernel fixed it (see #412 )

**Comment by billchenchina** [comment]
> Can you see whether [sonyxperiadev/camera#114](https://github.com/sonyxperiadev/camera/pull/114) helps?

I've tried this, but it doesnt work

**Comment by billchenchina** [comment]
> I had the same issue on nile, rebuilding the kernel fixed it (see #412 )

Rebuilding the kernel actually fixed.
Thanks @sraase
