### ISSUE TITLE
[Loire] [Kugo] Can't connect to camera error on Android P when using prebuilt kernel

### ISSUE THREAD

**Issue by chris42** [sonyxperiadev/bug_tracker#423]
**Platform:** Loire
**Device:** Kugo
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
After taking a picture, I get an error message "Can't connect to camera" and can't use the camera anymore. Need to reboot to take a picture again. Seems similar to #250.
Using v9 binaries. Sometimes you need to switch/restart the the camera app to get the error, before that the camera will just stay dark. e.g. to OpenCamera or Whatsapp

Logs: https://pastebin.com/mjcKG3B2

**Symptoms**
See Description

**How to reproduce**
Start Camera app, take picture.

**Comment by ix5** [comment]
Can you see whether https://github.com/sonyxperiadev/camera/pull/114 helps?

**Comment by chris42** [comment]
Hmmm... not sure where to put that? (Probably stupid question, however can't figure out how sony repositories are onnected)

I have
```
./device/google/marlin/camera/QCamera2/
./hardware/qcom/camera/msm8998/QCamera2/
./vendor/qcom/opensource/camera/QCamera2/
```

**Comment by chris42** [comment]
So did a new compile with the changes above in `./vendor/qcom/opensource/camera/QCamera2/` and error still occurs right after first picture. :-/

**Comment by sraase** [comment]
I had the same issue on nile, rebuilding the kernel fixed it (see #412 )

**Comment by chris42** [comment]
@sraase Thanks for that hint. 
I just compiled my kernel because of #418 and indeed, the error and green tint is gone for now.

@ix5 so question remains, why this happens. FYI: In this build I did NOT use [sonyxperiadev/camera#114](https://github.com/sonyxperiadev/camera/pull/114)

**Comment by ix5** [comment]
It seems odd that an unclean `$KERNEL_OUT`would manifest itself in green pictures only, but apparently that's the explanation...

**Comment by sraase** [comment]
My best guess is a compiler issue (your own kernels are built with gcc, while the prebuilt ones use clang).

**Comment by chris42** [comment]
So the workaround by compiling the kernel works. Will you still look into this on the prebuild kernel?

**Comment by pablomh** [comment]
FWIW I'm seeing the issue in pioneer, building a clean build (out/ completedly removed) with clang.

Next test is to build with https://github.com/sonyxperiadev/camera/pull/114.

**Comment by pablomh** [comment]
I can confirm that even after applying https://github.com/sonyxperiadev/camera/pull/114 and installing clean (userdata removed as well) the issue persists (on pioneer/nile).

**Comment by chris42** [comment]
@pablomh Have you tried rebuilding the kernel?
- setting `BUILD_KERNEL := true` in `kernel/sony/msm-4.9/common-kernel/KernelConfig.mk`
- `make installclean` before build

Your result would be interesting, as you are using clang

**Comment by pablomh** [comment]
I'll rebuild the kernel with GCC and get back with the result.

**Comment by jerpelea** [comment]
all kernels are prebuilt with gcc
