### ISSUE TITLE
[Documentation] missing package bc for kernel in build guide

### ISSUE THREAD

**Issue by chris42** [sonyxperiadev/bug_tracker#426]
Within the build guide for Pie (maybe others as well) the list of to be installed packages for your build environment is missing `bc`.
This is needed if you rebuild the kernel. As the kernel build instructions are referencing to the build guide, this package should be included.

Otherwise Error: `/bin/sh: 1: bc: not found` shows

**Comment by MartinX3** [comment]
Which Ubuntu version do you use?

**Comment by chris42** [comment]
Ubuntu Xenial (16.04) in docker
