### ISSUE TITLE
[loire][suzu] Front facing camera defocus

### ISSUE THREAD

**Issue by DGoX** [sonyxperiadev/bug_tracker#429]
**Platform:** loire
**Device:** suzu
**Kernel version:** 4.9
**Android version:** 9
**OEM** v9

**Description**
Blurry shots at all distances to the object, it always defocus.

**Symptoms**
Front facing camera can't focus at a distance >5cm.

**How to reproduce**
Open the camera app and try to focus on front facing camera.

**Comment by jerpelea** [comment]
this is a implementation limitation and can not be fixed
The focus limit should be 10-14cm
