### ISSUE TITLE
[Loire] [Kugo] Sound system problem

### ISSUE THREAD

**Issue by maluus** [sonyxperiadev/bug_tracker#430]
Platform:Loire 
Device:Kugo 
Kernel version:4.9 
Android version:9 

Description:
From time to time sound system messes up. Speakerphone doesn't work, no in call audio, answer button on headphones stops working etc. Sometimes all at once sometimes only one or two of these symptoms occur. After restart all starts to work again. I couldn't determine what causes this but I got logs from two different situation. 

Symptoms:
Varies as stated above

How to reproduce:
Not sure
[2019-06-24_08.11.zip](https://github.com/sonyxperiadev/bug_tracker/files/3322289/2019-06-24_08.11.zip)
[2019-06-24_15.53-No_in_call.zip](https://github.com/sonyxperiadev/bug_tracker/files/3322290/2019-06-24_15.53-No_in_call.zip)

**Comment by DGoX** [comment]
The same on suzu from time to time

**Comment by chris42** [comment]
@maluus I am streamlining all infos towards Loire/Kugo in #536. Not sure if the issues can be resolved, but I am trying to get an Android 10, Kernel 4.9 combination working, that is an improvement over the Pie version
