### ISSUE TITLE
[TONE] [KAGURA] Hotspot Wi-Fi Disconnection

### ISSUE THREAD

**Issue by fmmike** [sonyxperiadev/bug_tracker#431]
Platform: Tone
Device: Kagura
Kernel version: 4.9.182
Android version: 9.0 Pie

Description
The hotspot wifi connection stop working after one/two hours connection. 
After that is necessary reboot the phone.

How to reproduce
Switch On the Hotspot Wifi, use for two hours.

**Comment by ix5** [comment]
Please upload a logcat and dmesg.

**Comment by fmmike** [comment]
> Please upload a logcat and dmesg.

Could you help me understand where and how to take logs?

**Comment by MartinX3** [comment]
adb shell logcat > path/to/logcat.log
adb shell dmesg > path/to/dmesg.log

one of these needs to get cancelled via CTRL+C after you wait a bit, because it would look all the time for new events.
The other stops by itself if there is no more to log.

**Comment by fmmike** [comment]
I couldn't recover the log files but the problem is easily reproducible.

If a call is received during a hotspot connection, the service stops and it is no longer possible to connect even after the end of the call.

The phone must be restarted.

**Comment by ix5** [comment]
Please get us a log nevertheless.
You can either install [Matlog](https://f-droid.org/en/packages/com.pluscubed.matloglibre/) or you can use a system prop via `setprop persist.logd.logpersistd logcatd` which will save your logs in `/data/misc/logd/`.

**Comment by jerpelea** [comment]
no log provided
