### ISSUE TITLE
[tone] [kagura] MTP: Crashes when transferring files with Windows

### ISSUE THREAD

**Issue by ix5** [sonyxperiadev/bug_tracker#432]
**Platform:** Tone
**Device:** Kagura
**Kernel version:** 4.9.182 
**Android version:** 9.0 Pie

**Description**
Device crashes when attempting to transfer files via MTP from a Windows host.
Possibly related:
[[loire] mtp is broken for large files [2/2]](https://github.com/sonyxperiadev/bug_tracker/issues/77)
[[loire] mtp is broken for large files [1/2] ](https://github.com/sonyxperiadev/bug_tracker/issues/13)
[Discovery: copying files using MTP or PTP reboots phone #273 ](https://github.com/sonyxperiadev/bug_tracker/issues/273)

**Symptoms**
Hard crash from kernel panic
```
dwc3 6a00000.dwc3: swiotlb buffer is full (sz: 1048576 bytes)
DMA: Out of SW-IOMMU space for 1048576 bytes at device 6a00000.dwc3
Kernel panic - not syncing: DMA: Random memory could be DMA written
ipa ipa2_active_clients_panic_notifier:309 
---- Active Clients Table ----
IPA_CLIENT_APPS_WAN_CONS                 1378 ENDPOINT
SPS_RESOURCE                             -1378 SPECIAL
Total active clients count: 0
Kernel Offset: disabled
CPU features: 0x112008
Memory Limit: none
Rebooting in 5 seconds..
Going down for restart now
qcom,qpnp-power-on 400f000.qcom,spmi:pmi8994@2:qcom,power-on@800: PMIC@SID2: configuring PON for reset
msm_restart_prepare : cmd is NULL, set to reboot mode
```

**How to reproduce**
Attempt to transfer files from a Windows host via MTP. You will have to transfer a large amount of files, crashes seem to happen with large files as well.

---

Unrelated: We might need to investigate our `init.rc` files for adb/functionfs stuff, maybe some wrong attrs/ids?

**Comment by oshmoun** [comment]
a bit impractical not having a call trace don't you think? :)
https://github.com/sonyxperiadev/kernel/blob/aosp/LE.UM.2.3.2.r1.4/lib/swiotlb.c#L735-L740
changing these to BUG should give us that

**Comment by chris42** [comment]
Could it be, that the MTP overall is a bit whacky?
Using it during system time, always (since I own Xperia X Compact) ends for me in `libmtp error:  Could not get file from device.` under Linux. Windows just stops copying.
I always hat to switch to TWRP to copy files from the device. Maybe this is also a hint on solving the configuration?

**Comment by oshmoun** [comment]
applying the linked patch works around the issue by limiting the mtp request length
https://del.dog/ugayaselar.cc
I am not familiar enough with these things to deem this solution passable. however, should that be the case, we could simply adjust the sizes in init by writing to `/sys/module/usb_f_mtp/parameters/{mtp_rx_req_len,mtp_tx_req_len}`

**Comment by bartcubbins** [comment]
@Haxk20 please test with this PR https://github.com/sonyxperiadev/kernel/pull/2059/commits/aa5ff38887cd91e1ac3624b37449144d3b6c8fe1

**Comment by Haxk20** [comment]
I have made a new build. Cant test at this point due to laptop fastboot issues. Will do once i get on PC

**Comment by bartcubbins** [comment]
Don't test it, we will fix this in userspace

**Comment by Haxk20** [comment]
> Don't test it, we will fix this in userspace

Yes i read the PR. I mean i will test the userspace fix (limiting rx/tx)

**Comment by xdvom03** [comment]
This problem persists in Ubuntu 24.04 on Sony Xperia XQ-CC54.

**Comment by bartcubbins** [comment]
@xdvom03 I remember I faced a similar issue when bringing up some platform. Please open a new issue and attach the kernel logs
