### ISSUE TITLE
[Loire] [Kugo] Random reboots during use

### ISSUE THREAD

**Issue by chris42** [sonyxperiadev/bug_tracker#433]
**Platform:** Loire
**Device:** Kugo
**Kernel version:** 4.9
**Android version:** 9

**Description**
Device reboots randomly while using. Happened in different apps. After reboot of device, device itself seems to be only partially functional: no Wifi connection, apps won't start, services crash. Manual reboot needed to get the device running again.

Found a dmesg-ramoops with kernel panic in /sys/fs/pstore : [https://pastebin.com/PYgHKbLy](https://pastebin.com/PYgHKbLy)

**Symptoms**
Device reboots

**How to reproduce**
Could not find a pattern to reproduce

**Comment by MartinX3** [comment]
Similar to any of these?
https://github.com/sonyxperiadev/bug_tracker/issues/418
https://github.com/sonyxperiadev/bug_tracker/issues/421

**Comment by chris42** [comment]
Yes of course.... I participated in them...

**Comment by maluus** [comment]
I want to share my experience as well. After commits fixing #418 #420 I used the phone 34 days without similar problems. (Although 2 reboots happened I am suspicious that it's the same thing causing them. Could be result of some other problem. Because never went to the recovery in the end.) after sound related commits 2 days ago I compiled again and after a short while experienced a reboot into recovery again. But didn't encounter the symptoms @chris42 mentioned. Still working normally except sound system problems.

**Comment by chris42** [comment]
So I had a few more reboots. Also flashed a second device with a new build and got a reboot as well. (Additional to some NFC problems). The sound problems I could observe on my first device too.
So right now I have reboots, dropping Wifi, sound probems and NFC crashes... O_o

Since holiday season in Sweden has started, I guess till August I should better use Oreo again? ;-)

**Comment by maluus** [comment]
In my case no reboots, no NFC problem nor wifi drops. But sound problems are also with me.

**Comment by stefanhh0** [comment]
@chris42
@maluus 

Just a few questions, to help you figure out what the difference is:

- You are using exactly the same model (i.e. plain Xperia X Compact, not a special edition)?  
- You both have a most recently build of aosp running (output of `uname -a` shows the kernel commit you are on, it should be something with: 6593c13)
- Which version-baseband are you both using? (output of `fastboot getvar version-baseband`)

@chris42 from the log you have posted 8 days ago I can see you have been using: 
4.9.179-g828fd51-dirty I haven't found that hash via `git log 828fd51`have you been using a special branch or commit? Better ensure that you are on 6593c13 and then retry. Maybe that is already is already the solution to some of your problems...

**Comment by maluus** [comment]
I use my own room built including kernel without any other changes. The one I'm using is built 2 days ago just before commits #2002 and #1992 is not clean built obviously. With this state currently I only have sound system problems not the others Chris experience. 
![Screenshot_20190705-090359](https://user-images.githubusercontent.com/5315718/60701580-e4dec100-9f04-11e9-9fa1-f6102d69808f.png)

**Comment by chris42** [comment]
@stefanhh0 
Thanks, that was very helpful (even though not solving my problems). With that I could spot some differences and old kernel versions. Otherwise my devices are regular X Compact.
I synced and recompiled over night. My second device has now has current baseband `1302-7793_34.4.A.2.118` and Kernel version `4.9.182-g6593c13-dirty`
With that I get the nfc errors. Reboots, etc. I have to check

With the other device, I mostly got the reboots, wifi issues, etc. I have baseband `1302-7793_34.4.A.2.107` and kernel version `4.9.179-g828fd51-dirty`
I am hesitant to upgrade the sony firmware, as I do not want to get the nfc errors. They heat up the device and drain battery, so the device is pretty much unusable. The reboots and wifi drops are inconvenient, but bearable.

@maluus 
Could you pleas check `fastboot getvar version-baseband`? I get different values (see above) on my phones, even though the baseband version shown in the GUI is the same as yours on both.

**Comment by chris42** [comment]
For the reboots, I just got a adb logcat running while one happened. It seems normal (except the WifiHAL errors from #419 ), phone was syncing data to my nextcloud.

This happened on the device with `1302-7793_34.4.A.2.107` and `4.9.179-g828fd51-dirty`
(Did not change anything, it is a regular build from 18 June)

Last lines below. Phone rebooted right after that and logcat stopped:
```
07-05 13:14:16.983   598  1028 E Fence   : Throttling EGL Production: fence 31 didn't signal in 3000 ms
07-05 13:14:17.003   598   598 E Fence   : Throttling EGL Production: fence 27 didn't signal in 3000 ms
```

**Comment by chris42** [comment]
Updated now to
`4.9.182-g6593c13-dirty`
and kept (due to nfc errors on other device)
`1302-7793_34.4.A.2.107`

Will check if reboots still occour

**Comment by maluus** [comment]
fastboot shows baseband ver. 1302-7793_34.4.A.2.118

**Comment by chris42** [comment]
@maluus 
Thx. Already found, that apparently it is not the baseband (that thought was questionable either way). After flashing the `g6593c13` kernel to my `.107` device I got the same nfc errors as on the `.118` :-/ Moving back to my build from mid June removes the error again.
So need to figure out what else is different.

**Comment by maluus** [comment]
From which date that g6593c13?
________________________________

**Comment by chris42** [comment]
I synced yesterday evening, hence 04. July

**Comment by maluus** [comment]
Hmm I'm syncing now. Was thinking to try a newer build. so better not to flash it since you already provided some logs to debug. But if more testing is needed I can try anyway.
________________________________

**Comment by maluus** [comment]
As a side note when I commented I'd said no nfc crashes in my case but I just noticed the reason: nfc doesn't even exist in my settings let alone crashing. I m building now from latest sync.

**Comment by chris42** [comment]
I did not have it in my settings as well.
However, I found out, that some nfc related changes where done in kugo and loire after mid June, hence after my last (still working) build. Posted that into #437

**Comment by maluus** [comment]
Flashed new build still no nfc unfortunately.

**Comment by chris42** [comment]
Just got another reboot and found some files in the sys/fs/pstore. Please find attached.
Device was just freezing and then going into reboot. Right after boot, it took around 15 seconds and next freeze/reboot occurred.


[sys_fs_pstore.zip](https://github.com/sonyxperiadev/bug_tracker/files/3378526/sys_fs_pstore.zip)

**Comment by chris42** [comment]
So I updated to a newer build (g92003b3) and reboots still happen. Sadly sys/fs/pstore is empty. The device just reboots and then needs two or three additional boots, before functioning properly again.

**Comment by MartinX3** [comment]
Usually the second reboot resets pstore
Maybe a quick boot to twrp instead may reveal the pstore crash cause

**Comment by chris42** [comment]
Yes, that is how I found the files I posted before, however it seems that most times there is nothing pstore.
Only observation is, that my latest crashes are exclusively when using the device, not while it is idle. I am always interacting with it, when it stops to respond. I could not pinpoint it to an app, it happened pretty much in every app I have on the phone.

**Comment by maluus** [comment]
Same here. Never found the device rebooted when idle. In my case its very rare though. May be once in a 2-3 days.
________________________________

**Comment by MartinX3** [comment]
If you have a misc partition, you could write the reboot to recovery flag there
I sadly don't know the exact value
It forces the device to boot into the recovery until the flag got removed
So if it suddenly restarts it would boot directly into twrp and doesn't wipe the pstore if it has any data.
Of course you shouldn't manually reboot the device then.

**Comment by maluus** [comment]
Both Chris and I tried a lot of times even when it'd booted to recovery pstore was empty.
________________________________

**Comment by chris42** [comment]
So the question is, if anyone is actively looking into this? Same for #419 
I am happy to support anyone with builds, tests and logs (if not the pstore ones ;-D), as it is quite annoying to use the phone in this state.

**Comment by chris42** [comment]
So got another reboot and was able to get pstore files. Not sure how to read them though...

[pstore.zip](https://github.com/sonyxperiadev/bug_tracker/files/3563856/pstore.zip)

**Comment by stefanhh0** [comment]
One source for instability for some devices is the fingerprint sensor. Maybe also for Loire/Kugo?
See: #435 and #442.

**Comment by chris42** [comment]
I remember having a crash once which showed some fingerprint related logging, however these reboots do occur randomly while using the device. I can't tell if the fingerprint is somehow involved in this, as I do not understand the logging.

**Comment by chris42** [comment]
I actually found the tombstones from that crashes. However I can't say if that was connected to a reboot or not. But it might help someone to figure out what is going on?

[Tombstones.zip](https://github.com/sonyxperiadev/bug_tracker/files/3563946/Tombstones.zip)

**Comment by stefanhh0** [comment]
If it is the fingerprint sensor that causes the reboots you could check it via removing all registered fingerprints from the phone.

**Comment by chris42** [comment]
@stefanhh0 Did your crashes disappear completely after deactivating the fingerprint sensor in #442?

**Comment by maluus** [comment]
I don't think the problem is with fp sensor in our case. I don't remember it crashed just after waking up. It usually crashes during use. At least in my case.
________________________________

**Comment by chris42** [comment]
@maluus Chances are slim, but will try nevertheless. The ways of Loire are unknown.... ;-)

**Comment by chris42** [comment]
Yupp, as expected, still have the reboots. 3 since de-registering the fingerprints.

**Comment by chris42** [comment]
@jerpelea Do you know anything about loire/kugos future in the aosp world? Following #466 it seems it will take some time to adapt the kernel 4.14 and most people look at it for newer devices. Will this work for loire/kugo as well? Will it help the multitude of issues we have on 4.9 right now?

I have a spare device here and can test most things, however not the fix type of guy.
If loire/kugo will not be supported anymore, it would be nice to know, as search for a compact replacement will take serious time.

**Comment by jerpelea** [comment]
In this moment loire boots happy the 4.14 kernel and Android 10 but please note that there will be a long stabilization phase and bug hunting.

**Comment by chris42** [comment]
@jerpelea That is great news. You want others (like me) to test it, or should I wait a while?

**Comment by maluus** [comment]
Good to hear. Will continue using it and help with testing and building. Btw repo sync fails for a few days and guide for android 9 removed from web site is this for coming off 10?
________________________________

**Comment by Haxk20** [comment]
Im making a build of Q well im trying to at least. Have some issues with building it. With 4.14 so i will test and fix as much as im able to.

**Comment by jerpelea** [comment]
unless you are a kernel developer please wait until v2 release. at this stage there are many things disabled or not implemented.

**Comment by Haxk20** [comment]
Well i cant get 4.9 to build with Q anymore after last repo sync so i dont have other option

**Comment by Haxk20** [comment]
Or @jerpelea Have you got any guide how to build Q without 4.14 ?

**Comment by MarijnS95** [comment]
@Haxk20 Same as what [I said to Stefan](https://github.com/sonyxperiadev/bug_tracker/issues/456#issuecomment-533796995) a few days back, revert https://github.com/sonyxperiadev/device-sony-common/commit/249de5c1ad0ea282ad58d0625993cac78c00193a and you should be fine.

**Comment by Haxk20** [comment]
Damn will try. I missed that message

**Comment by jerpelea** [comment]
@Haxk20 that is something simple and we will not officially support it since you can use the 4.9 kernel and blobs yourself

**Comment by Haxk20** [comment]
@jerpelea Well yeah its simple once the build passes fine. as marijn pointed its not issue in kernel but the TEMP commit that i totally missed. There are so many repos here that its hard to keep track of all of them and which change might break something.
And well i mean once 4.14 is stable i think there is no reason what so ever to try to run 4.9 with Q.

**Comment by stefanhh0** [comment]
https://github.com/sonyxperiadev/bug_tracker/issues/456#issuecomment-533792254
contains a build script to build 4.9 with android 10. It needs to be adjusted for the target device since currently it is for yoshino/lilac only, however shouldn't be too difficult...

Adjustments have to go to all places where yoshino is found in the script.

I hope the script is complete and there is nothing missing...

**Comment by stefanhh0** [comment]
@chris42 maybe you like to check if https://github.com/sonyxperiadev/kernel/pull/2188 helps.

**Comment by yshui** [comment]
@chris42 is there any relevant information in `/sys/fs/pstore/*` after reboot?

**Comment by chris42** [comment]
A few times there were log files. Posted them above. If they are relevant, I can't tell. With Pie the device was always very wonky, having all sorts of issues. Sometimes the pstore is empty, as it seems to do a double reboot.
Will try the #2188 PR, however it will take some time, as I need to redo the build system and put everything together.

**Comment by vknecht** [comment]
> Will try the #2188 PR, however it will take some time, as I need to redo the build system and put everything together.

In case it helps, I've [posted builds](https://forum.xda-developers.com/showpost.php?p=81787289&postcount=69) including bootimages with sonyxperiadev/kernel#2188 rebased on almost latest kernel

**Comment by chris42** [comment]
The builds are helpful as they show if something improved. Thanks!
Do you have a buildscript or something? Then I could try to adapt it to Android 10

**Comment by stefanhh0** [comment]
@chris42 if you are using my build script, you just have to add something like that:
```
pushd kernel/sony/msm-4.9/kernel
_pick_pr sony 2188 24
popd
```

**Comment by chris42** [comment]
Just tested a bit starting of my last working script. It does not seem to be that easy.
Using "android-10_legacy" there are a few errors. In the cleanup now the "LA.UM.7.1.r1.xml", "display-commonsys-intf" and the patching for "qcom.xml" fails. Later the "Include default thermal hw module" and the location parts fails. I am not sure what to make out of this, I guess all the changes towards "android-10 legacy" created a mess.
I removed all this and it is building now, but will see tomorrow, if this is actually something usable. But for sure will need to check all changes of @ix5 @vknecht etc.

**Comment by chris42** [comment]
So tried to compile it pretty much following the Sony guide, you end up with error on the camera. I guess it is not yet correctly set up in the legacy branch? @jerpelea 
Will go through the changes of @ix5, however skimming through them, that looked more like other things.

```
[ 41% 49863/120540] target thumb C++: camera.msm8952_32 <= vendor/qcom/opensource/camera/QCamera2/QCamera
FAILED: out/target/product/kugo/obj_arm/SHARED_LIBRARIES/camera.msm8952_intermediates/QCamera2Factory.o
/bin/bash -c "PWD=/proc/self/cwd /usr/bin/ccache prebuilts/clang/host/linux-x86/clang-r353983c/bin/clang++ 	-I vendor/qcom/opensource/camera/QCamera2/../mm-image-codec/qexif -I vendor/qcom/opensource/camera/QCamera2/../mm-image-codec/qomx_core -I vendor/qcom/opensource/camera/QCamera2/include -I vendor/qcom/opensource/camera/QCamera2/stack/common -I vendor/qcom/opensource/camera/QCamera2/stack/common/leak -I vendor/qcom/opensource/camera/QCamera2/stack/mm-camera-interface/inc -I vendor/qcom/opensource/camera/QCamera2/util -I vendor/qcom/opensource/camera/QCamera2/HAL3 -I hardware/qcom/media/sdm660-libion/libstagefrighthw -I hardware/qcom/media/sdm660-libion/mm-core/inc -I system/core/libion/kernel-headers -I system/core/libion/include -I vendor/qcom/opensource/camera/QCamera2/HAL -I out/target/product/kugo/obj/include/qcom/display -I hardware/qcom/display/sde/libqservice -I vendor/qcom/opensource/camera/QCamera2 -I out/target/product/kugo/obj_arm/SHARED_LIBRARIES/camera.msm8952_intermediates -I out/target/product/kugo/gen/SHARED_LIBRARIES/camera.msm8952_intermediates \$(cat out/target/product/kugo/obj_arm/SHARED_LIBRARIES/camera.msm8952_intermediates/import_includes)   -isystem out/target/product/kugo/obj/include -isystem kernel/sony/msm-4.9/common-headers/kernel-headers -c  -fomit-frame-pointer -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -faddrsig -Wimplicit-fallthrough -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-zero-as-null-pointer-constant -Wno-sign-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -nostdlibinc -msoft-float -march=armv8-a -mfloat-abi=softfp -mfpu=neon-fp-armv8 -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -D__ARM_FEATURE_LPAE=1 -target armv7a-linux-androideabi -Bprebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin  -Wsign-promo -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -Wno-gnu-include-next -fvisibility-inlines-hidden  -std=gnu++17 -mthumb -Os  -fno-rtti -Wall -Wextra -Werror -DFDLEAK_FLAG -DMEMLEAK_FLAG -DQCAMERA_HAL1_SUPPORT -DSYSTEM_HEADER_PREFIX=sys -DHAS_MULTIMEDIA_HINTS -D_ANDROID -DVANILLA_HAL -DUSE_DISPLAY_SERVICE -std=c++11 -std=gnu++1y -DDEFAULT_DENOISE_MODE_ON -DHAL3 -DQCAMERA_REDEFINE_LOG -DVENUS_PRESENT -DTARGET_MSM8996 -DUSE_CAMERA_METABUFFER_UTILS -DTARGET_HAS_CASH -D__ANDROID_API__=29 -D__ANDROID_VNDK__ -fPIC -D_USING_LIBCXX -DANDROID_STRICT   -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-tautological-unsigned-zero-compare -Wno-c++98-compat-extra-semi -Wno-return-std-move-in-c++11  -MD -MF out/target/product/kugo/obj_arm/SHARED_LIBRARIES/camera.msm8952_intermediates/QCamera2Factory.d -o out/target/product/kugo/obj_arm/SHARED_LIBRARIES/camera.msm8952_intermediates/QCamera2Factory.o vendor/qcom/opensource/camera/QCamera2/QCamera2Factory.cpp"
In file included from vendor/qcom/opensource/camera/QCamera2/QCamera2Factory.cpp:40:
In file included from vendor/qcom/opensource/camera/QCamera2/HAL/QCamera2HWI.h:40:
In file included from vendor/qcom/opensource/camera/QCamera2/HAL/QCameraChannel.h:34:
vendor/qcom/opensource/camera/QCamera2/HAL/QCameraMem.h:43:10: fatal error: 'OMX_QCOMExtns.h' file not found
#include "OMX_QCOMExtns.h"
```

**Comment by MarijnS95** [comment]
That's the same issue as in https://github.com/sonyxperiadev/bug_tracker/issues/551, perhaps you can try the same solution?

**Comment by chris42** [comment]
Closing this in favour of #536 
As Loire moved to legacy, it is probably better to streamline the infos and progress into one issue.

**Comment by chris42** [comment]
@MarijnS95 Yes, it looks like, will try. Thanks a lot!
