### ISSUE TITLE
[Yoshino][Poplar] No touchscreen response.

### ISSUE THREAD

**Issue by insideTheFlux** [sonyxperiadev/bug_tracker#434]
**Platform: Yoshino**
**Device: Poplar**
**Kernel version: 4.9**
**Android version: android-9.0.0_r37**
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_yoshino.img
**Build:** aosp_g8342-userdebug 9 PQ3A.190505.002 eng.dying_.20190627.171831 test-keys
**Version baseband:** 1310-4358_47.2.A.10.80

**Description**
Phone boots up, the screen shows no signs of touch response. Therefore I cannot use the phone, I'm forced to use Vol+ w/ power button to reset.
I've tried flashing just the img files without OEM_v9, same problem. I've flashed OEM_v9, the issue persists after bootup.

Phone is utterly unusable with AOSP r_37

**How to reproduce**
With latest r_37, on poplar, attempt to use the phone after bootup.

**Comment by stefanhh0** [comment]
The version baseband you are using is known to have issues with aosp, please downgrade to:
47.1.A.16.20, use the sony flashtool to downgrade (https://developer.sony.com/develop/open-devices/get-started/flash-tool/download-flash-tool/). Don't use the firmware only image but the one that also wipes the userdata.

After you have flashed, start the stock with SIM inserted once. 
Reboot into fastboot verify with `fastboot getvar version-baseband` that you are on the expected version-baseband. After that flash aosp.

**Comment by insideTheFlux** [comment]
wow! Please tell me this is a temporary fix because falling back to an Oreo baseband sounds so backwards... I don't know what to say. 
Is AOSP ever usable through out updates/upgrades? It feels like it breaks every time with them.

**Comment by stefanhh0** [comment]
I am just an aosp user and don't know if and when yoshino is able to use the newer version-baseband.

**Comment by duffman128** [comment]
I have the same issue with the G8341. I tried downgrading as @stefanhh0 suggested and flashing AOSP with no resolution. I guess I'm forced to use GSI to keep my phone's security up-to-date.

**Comment by Paulbouchara** [comment]
Pick an older prebuilt kernel
The offender is glove mode enabling commit

**Comment by insideTheFlux** [comment]
So CONFIG_GLOVE_TOUCH=n then before kernel building?

**Comment by lazerl0rd** [comment]
@insideTheFlux Glove mode patch to disable for yoshino was merged already. It's to do with the screen DT.

**Comment by lazerl0rd** [comment]
Furthermore, if you use an older version that was prior to SDE - it should work.
