### ISSUE TITLE
[nile|ganges] [pioneer|kirin] Android Pie WebView rendering stuck when screen turns on after sleep

### ISSUE THREAD

**Issue by AngryGami** [sonyxperiadev/bug_tracker#436]
**Platform:** 
Reproduced on ganges and nile
**Device:** 
Reproduced on pioneer and kirin
**Kernel version:** 
4.9.182-gf18825b 
**Android version:** 
9

**WebView version**
Android System WebView 75.0.3770.101 (chromium based)

**Description**
We have a web view where there is only a button and counter. You can tap on it and see that counter increases. If you turn off screen of the device, and then turn it on again, you can tap and you will see that the counter does not increase, button animation also freeze. Sometime you need to turn screen off/on couple of times to get it stuck in this state but this is very consistent behavior. 
Important detail to reproduce this problem is that no lock screen need to be configured for device - i.e. you should see application immediately after turning screen on (no swipe, no pin code etc.).
You can unfreeze app if go to some other activity/app and go back - then counter will display proper value including taps that were made while app was frozen (which means that only rendering is broken, events from tap actually reaching javascript underneath).

We only was able to test this issue with pioneer (XA2, h4113) and kirin (Xperia 10, i4113), so maybe this problem exists for other devices as well. This problem is only appear with android Pie and only with AOSP based image - stock Sony and non-Sony devices works fine. All stock rom devices I was managed to test use Chrome based WebView but same 75.0.3770.101 version as AOSP image, so I assume this is NOT webview issue. Also, Oreo (android 8) with same webview works fine as well.

Here is sample project that demonstrate this issue:
[PieCordovaBug2.zip](https://github.com/sonyxperiadev/bug_tracker/files/3354416/PieCordovaBug2.zip)
It include source code and apk file under PieCordovaBug\platforms\android\app\build\outputs\apk\debug\

Here is screen cast that demonstrate this issue:
[bugdemo.zip](https://github.com/sonyxperiadev/bug_tracker/files/3354464/bugdemo.zip)

**Symptoms**
Application UI is frozen, no update of state is rendered.

**How to reproduce**
1) Build AOSP image for either pioneer or kirin device, flash it 
2) install showcase application (see attachment), 
3) disable lock screen, 
4) run application and tap button several times to see counter works, 
5) turn off screen (with power button), turn it on, tap button again, 
6) repeat 4 and 5 until it freeze, i.e. counter stops increasing.

**Comment by pablomh** [comment]
Confirmed on kugo (loire platform).

**Comment by luk1337** [comment]
Confirmed on AVD lol.

**Comment by AngryGami** [comment]
https://issuetracker.google.com/issues/136633138

**Comment by AngryGami** [comment]
Ok, I've found what is causing this and fixed it for my local repo, though I'm not sure my fix is 100% safe, therefore I might need some confirmation.

The reason why screen stop updating is that at some point during power off processing Surface.release() method get called. This is normal behavior and usually when power on again `android.app.ActivityThread` do relayout in `handleResumeActivity` method and doing that restores surface (or recreates it) deeper in the stack. Though `handleResumeActivity` method is strange regarding what is does with `softInputMode` field of `WindowManager.LayoutParams` class:
```java
    @Override
    public void handleResumeActivity(IBinder token, boolean finalStateRequest, boolean isForward,
            String reason) {
...
        final int forwardBit = isForward
                ? WindowManager.LayoutParams.SOFT_INPUT_IS_FORWARD_NAVIGATION : 0;
...
            if ((l.softInputMode
                    & WindowManager.LayoutParams.SOFT_INPUT_IS_FORWARD_NAVIGATION)
                    != forwardBit) {
/* ------------ */
                l.softInputMode = (l.softInputMode
                        & (~WindowManager.LayoutParams.SOFT_INPUT_IS_FORWARD_NAVIGATION)) 
                        | forwardBit;
/* ------------ */
...
                    wm.updateViewLayout(decor, l);
...
```
If `isForward` parameter is true it will set `forwardBit` to be `SOFT_INPUT_IS_FORWARD_NAVIGATION`  (0x100) and down in the if statement will check that `l.softInputMode` has `SOFT_INPUT_IS_FORWARD_NAVIGATION` bit not equals to `forwardBit` and if it is not - will try to clear it with `(l.softInputMode & (~WindowManager.LayoutParams.SOFT_INPUT_IS_FORWARD_NAVIGATION))` though at same time will set it back with `| forwardBit` because `forwardBit` is actually equal to `SOFT_INPUT_IS_FORWARD_NAVIGATION`. This leads to that next time `handleResumeActivity` method get called it will skip `updateViewLayout` and Surface won't be recreates/restored.
Another scenario is when `isForward` parameter is false, then `forwardBit` will be 0 and if statement essentially will check that `SOFT_INPUT_IS_FORWARD_NAVIGATION` bit is not set (by applying mask and checking that result is 0) and when it is not set - will clear it (!) and `OR` `forwardBit` (which is 0 - so does nothing).
This entire logic look bogus to me though I can't clearly see what was the intention, therefore it might be not. I also wasn't able to track down how and when `isForward` parameter is given to this method so maybe actual error is up in the stack and `handleResumeActivity` method should be called differently.
I might guess that intention was to just clear `SOFT_INPUT_IS_FORWARD_NAVIGATION` flag like it says in it's description:
```java
        /**
         * Bit for {@link #softInputMode}: set when the user has navigated
         * forward to the window.  This is normally set automatically for
         * you by the system, though you may want to set it in certain cases
         * when you are displaying a window yourself.  This flag will always
         * be cleared automatically after the window is displayed.
         */
        public static final int SOFT_INPUT_IS_FORWARD_NAVIGATION = 0x100;
```
though from looks of it - code above failed to do that.
My fix was to just remove `| forwardBit` from ` l.softInputMode = (l.softInputMode                        & (~WindowManager.LayoutParams.SOFT_INPUT_IS_FORWARD_NAVIGATION))  | forwardBit` and it worked fine with no apparent problems elsewhere.
I don't know how this issue actually not reproducible in "Q" because either `android-q-preview-5` or `master` tag/branch of framework/base project have this exact piece of code and therefore should behave the same. It might be that problem get fixed somewhere up the stack (i.e. with `isForward` parameter set to false somewhere) or `updateViewLayout` is called from somewhere else during power on or Surface actually not released and therefore not become stale. In either case I think bitwise operation causing this problem make no sense.

**Comment by AngryGami** [comment]
I'm sorry, can you say why have you closed this?

**Comment by MartinX3** [comment]
> I'm sorry, can you say why have you closed this?

It's an AOSP bug. Not a SODP bug. :)
According to https://issuetracker.google.com/issues/136633138#comment6 it's fixed in Q.
If I am correct P won't receive a fix? Or do I miss something?

**Comment by AngryGami** [comment]
SODP does lots of fixes to AOSP tree via repo_update.sh script in it's source tree (essentially fetching certain commits from upstream or elsewhere) so why not do similar stuff here?

> According to https://issuetracker.google.com/issues/136633138#comment6 it's fixed in Q.

It is not "fixed" - I've checked the code. It is just hidden/mitigated by some other stuff most likely.

**Comment by MarijnS95** [comment]
@AngryGami See it differently. It's not like this project _doesn't want_ to fix aosp issues.

However, `repo_update` is used to apply patches that make _hardware repositories compatible with our hardware_, and we like to keep it that way. Without it, core components will not work. Most of these are not fixes from aosp gerrit that have simply not been merged yet (even if it looks that way, we're making steps to keep hardware-specific patches local as Google will never use nor merge them anyway).

If you find this disappointing, feel free to apply a gerrit fetch to your local `repo_update`.

**Comment by AngryGami** [comment]
Ok, you are to decide here anyway, nothing I can really do except grumble :) 
Though I know for sure e.g. Samsung devices don't have this problem on same version of AOSP (Pie) as well as stock Sony image, i.e. there is someone who fixed this...

**Comment by MarijnS95** [comment]
@AngryGami It's not up to me to decide, 

Anyway, please check what webview renderer Samsung and Sony are using. Both come with Google apps (like pretty much any other phone) and have Chrome (which is updated through the play-store) selected by default. It is very likely the fix is already in place there.

You mention in your comment that the "fix" is most likely just hiding the issue, but the investigation indicates that `handleResumeActivity` could well be called wrong. Would you mind investigating whether that is the case?

**Comment by AngryGami** [comment]
> It's not up to me to decide.

Decide to close this issue I mean...

Webview renderer is not involved here. I thought it did but as I written after some digging and especially when found https://issuetracker.google.com/issues/136633138 - this is NOT webview only problem.

> You mention in your comment that the "fix" is most likely just hiding the issue, but the investigation indicates that handleResumeActivity could well be called wrong. 

I don't understand what you meant by that... Do you mean my fix? Or google saying they can't reproduce this in "Q" and therefore it is "fixed"? 
I can confirm that when I applied my fix to my build of AOSP and tested - bug disappeared and everything else works without any problems (i.e. I haven't broken anything with my fix). 
I have doubts that google fixed anything in Q because they claimed they can't reproduce it but code that is the culprit is still there untouched - so bug is still there, just mitigated/hidden by some other code. I didn't mean that my fix is hiding anything.

> Would you mind investigating whether that is the case?

I don't see any way to do that. To investigate further I lack understanding of intent that lies behind code - I can find call sites but I won't help me understand why they need certain values. I don't even understand what "isForward" means (only vague guesses). Though I'm pretty sure that problem is in bitwise operations because `l.softInputMode = (l.softInputMode & (~WindowManager.LayoutParams.SOFT_INPUT_IS_FORWARD_NAVIGATION)) | forwardBit` is meaningless - whatever was  then intent resetting bit and immediately setting it back makes no sense.

**Comment by MarijnS95** [comment]
Let's put it differently then. Why the suggestion to pick/apply some magic patch in `repo_update`, when it doesn't even seem to exist?

**Comment by AngryGami** [comment]
This is chicken-egg problem :)
If you agree to add such patch into repo_update - someone (me) can create it. But you won't agree to put it into repo_update because it doesn't exists. Though it is hardly a "patch" (measuring by amount of change required, I see you and @jerpelea committing much bigger things) and I don't want it to look magic, therefore this discussion. I thought I can find some experts that can see my reasoning and either say this is wrong and why it is wrong or confirm my idea so we make proper patch.

**Comment by jerpelea** [comment]
please send the workaround, add it to the google groups thread and let Google comment on it

**Comment by AngryGami** [comment]
Already did that. No response.
