### ISSUE TITLE
[Loire] [Kugo] NFC crashing over and over

### ISSUE THREAD

**Issue by chris42** [sonyxperiadev/bug_tracker#437]
**Platform:** Loire
**Device:** Kugo
**Kernel version:** 4.9
**Android version:** 9

EDIT: Using v9 vendor files

**Description**
com.android.nfc is crashing over and over.
I tried a new compile for #433 (make clean and make installclean) and flashed a new device. Figured it was warm and checked logs where I found repeated crash of nfc.
Not sure if it is connected to old #157?
- [Logs](https://pastebin.com/vKLFcBYq)
- [Tombstone](https://pastebin.com/0FFPjmWj)

**How to reproduce**
Flash device, start up, start logging.

**Comment by chris42** [comment]
Additional information:
The device I get these error on have following Kernel and baseband versions:
fastboot getvar version-baseband
`1302-7793_34.4.A.2.118` 
uname -a
`4.9.182-g6593c13-dirty`

I have another device with (WITHOUT the nfc error)
fastboot getvar version-baseband
`1302-7793_34.4.A.2.107`
uname -a
`4.9.179-g828fd51-dirty`

**Comment by chris42** [comment]
After a few reboots, I now also got the .nfc error on my second device with .107 baseband.
Hence it is not about the baseband (that thought was questionable either way). 
Moving back to my build from mid June removes the error again.
So need to figure out what else is different.

**Comment by chris42** [comment]
After looking at the exception and seeing a lot of thins regarding config and start of nfc, could this be connected to the moving around of libnfc-nci.conf in [Pull request #71](https://github.com/sonyxperiadev/device-sony-kugo/pull/71) in device-sony-kugo and its corresponding part in loire?

**Comment by maluus** [comment]
In my case the nfc is not even available. Neither nfc menu in settings nor the apps can use it. It's like not there hence no crashes related to it. Same built same baseband.

**Comment by chris42** [comment]
I just flashed a new build with the July _r44 tag. So far I could not observe the error, but will wait a few reboots to make sure.

@maluus The NFC config is in the bluetooth settings under connected devices. I remembered that different from Oreo.

**Comment by maluus** [comment]
Nope not there looked and searched in settings. Nowhere to be found.
________________________________

**Comment by stefanhh0** [comment]
@maluus Maybe it can be found if you change your system language to english?

It should be under Settings -> Connected devices -> Connection Preferences Bluetooth, NFC:
![Screenshot_20190706-131759](https://user-images.githubusercontent.com/28729344/60755489-ce159880-9ff0-11e9-9826-492bb55b9766.png)

**Comment by maluus** [comment]
I don't think it's related to system language. I used it before but now it's not there. 
![Screenshot_20190706-142408](https://user-images.githubusercontent.com/5315718/60755559-108fa300-9ffa-11e9-8e42-acaf1dd71c64.png)

**Comment by stefanhh0** [comment]
Although you don't think so, it could be related, e.g l10n resource is missing and instead of fallback nothing is shown...

Output of `adb shell dumpsys nfc` looks good?
Maybe your nfc chip died... No idea how that could be checked though...

**Comment by maluus** [comment]
I tried with an app from play store. Shows chip is not activated.
________________________________

**Comment by chris42** [comment]
Apparently we share a bond of our errors... either way your device or mine has it :-D

I was missing NFC yesterday: Following is the base of my build for today, that seems to work:
- remove all sources, ccache... basically start blank
- initialize sources with android-9.0.0_r44 branch and sync
- set kernel build to true
- make installclean, clean and clobber, just to be sure.... ;-)
- build (takes around 7-8h on my machine)

Why am I doing this? I have bad experience with switching the branch, not deleting the ccache on branch switch, etc. Although the cache seems to be quite ok in regular changes, I always resync my sources from a local mirror and delete everything, before the full monthly ROM compile. It seems over the top and time consuming, however I had the weirdest issues come up without it.

**Comment by maluus** [comment]
I just builded from the branch r44 and flashed. NFC came back. Activated and deactivated no crashes or problems. seems fine so far. I ll update if I encounter any problems.

**Comment by chris42** [comment]
So I compiled again for my second device and above errors are not happening there as well. I guess the problems we had were some unique combination. Will close this for now.

PS: Found some errors when enabling/disabling NFC, but will create a separate issue for that.
