### ISSUE TITLE
[maple] USB charging is not detected properly

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#44]
**Platform:** yoshino
**Device:** maple
**Kernel version:** 4.4.21 (1eaee3e-dirty)
**Android version:** 8.0.0
**Firmware version:** v05

**Description**
The device fails to properly detect the charger, either when connected to a PC or to an AC charger (Sony, 1.5A).

**Symptoms**
LED lights up for charging, but no lightning symbol on top of battery in notification bar. When the user enter the battery menu in settings, battery state is charging, but again, no lightning symbol on top of the battery. 

This issue came to focus because it prevents the user to encrypt the device, since one of the prerequisites for encryption is that the device is plugged in.

**How to reproduce**
Either reboot the device or just regularly power on the device, in both cases when it's not connected to a charger. It seems that if the device boots with the charger connected, this issue is not present. 

**Logs**

`adb shell dumpsys battery` output:

```
  AC powered: false
  USB powered: false
  Wireless powered: false
  Max charging current: 0
  Max charging voltage: 0
  Charge counter: 0
  status: 2
  health: 2
  present: true
  level: 94
  scale: 100
  voltage: 4247
  temperature: -2730
  technology: Li-ion
```

**Logcat**
```
--------- beginning of main
11-17 13:00:16.936 I/MSM-irqbalance(  601): Decided to move IRQ52 from CPU0 to CPU1
11-17 13:00:20.990 E/android.hardware.usb@1.0-service(  589): uevent received SUBSYSTEM=dual_role_usb
11-17 13:00:20.990 I/android.hardware.usb@1.0-service(  589): otg_default
11-17 13:00:20.990 I/android.hardware.usb@1.0-service(  589): canChangeMode: 0 canChagedata: 0 canChangePower:0
--------- beginning of system
11-17 13:00:20.991 I/UsbPortManager( 1234): ClientCallback: otg_default
11-17 13:00:20.992 I/UsbPortManager( 1234): USB port changed: port=UsbPort{id=otg_default, supportedModes=dual}, status=UsbPortStatus{connected=false, currentMode=none, currentPowerRole=no-power, currentDataRole=no-data, supportedRoleCombinations=[no-power:no-data]}, canChangeMode=false, canChangePowerRole=false, canChangeDataRole=false
11-17 13:00:21.943 I/MSM-irqbalance(  601): Decided to move IRQ5 from CPU0 to CPU1
11-17 13:00:24.058 E/android.hardware.usb@1.0-service(  589): uevent received SUBSYSTEM=dual_role_usb
11-17 13:00:24.059 I/android.hardware.usb@1.0-service(  589): otg_default
11-17 13:00:24.060 I/android.hardware.usb@1.0-service(  589): canChangeMode: 0 canChagedata: 0 canChangePower:0
11-17 13:00:24.062 I/UsbPortManager( 1234): ClientCallback: otg_default
11-17 13:00:24.063 I/UsbPortManager( 1234): USB port changed: port=UsbPort{id=otg_default, supportedModes=dual}, status=UsbPortStatus{connected=true, currentMode=ufp, currentPowerRole=sink, currentDataRole=device, supportedRoleCombinations=[sink:device]}, canChangeMode=false, canChangePowerRole=false, canChangeDataRole=false
11-17 13:00:24.595 I/zygote64( 1371): Do partial code cache collection, code=215KB, data=141KB
11-17 13:00:24.596 I/zygote64( 1371): After code cache collection, code=215KB, data=141KB
11-17 13:00:24.596 I/zygote64( 1371): Increasing code cache capacity to 1024KB
11-17 13:00:26.945 I/MSM-irqbalance(  601): Decided to move IRQ53 from CPU0 to CPU1
11-17 13:00:31.942 I/MSM-irqbalance(  601): Decided to move IRQ5 from CPU0 to CPU1
```

**Comment by jerpelea** [comment]
@kholk

**Comment by kholk** [comment]
The issue should be solved on 6.4.r1.

**Comment by jerpelea** [comment]
after test it should be backported to 5.7

**Comment by jerpelea** [comment]
i have not seen any issue on the 6.4 kernel

**Comment by kholk** [comment]
Backporting to 5.7 means at least 30 commits (to backport the whole SMB2-FG3-EXTCON), which isn't a good option IMHO.
I'd say to close this issue since we have a solution, which is to upgrade to the latest available software (kernel+userspace).

**Comment by jerpelea** [comment]
we can not replicate the bug
please check the bug again and close the ticket

**Comment by jerpelea** [comment]
@kholk if you have time please backport the commits since the 5.7 branch is used for Android 7.1 and 8.0

**Comment by jerpelea** [comment]
@dimitar10 please retest

**Comment by dimitar10** [comment]
The issue is not present anymore on Maple G8142, with Android 8.1.0 and the 4.4.114 kernel from the 6.4 branch. I will mark it as closed.
