### ISSUE TITLE
[Yoshino][Lilac] Fingerprint sensor cause crash

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#442]
**Device:** Lilac
**Platform:** Yoshino
**Kernel version:** 4.9.182-g89814a250e93
**Android version:** android-9.0.0_r44
**Software binaries version:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_yoshino.zip
**Version baseband:** 1308-8921_47.1.A.16.20
**Build:** aosp_g8441-userdebug 9 PQ3A.190705.003 eng.stefan.20190709.190050

**Description**
One source for the instability as reported in #399 seems to be when a fingerprint was registered and that fingerprint is used to unlock the device. Since I have removed my fingerprint and solely work with display PIN the device is a lot more stable and the double-crashes/reboots reported in #399 are a lot less frequent.    

**Symptoms**
Double crashes and reboots as reported in #399 due to usage of fingerprint sensor unlocking.

**How to reproduce**
Register a fingerprint for device unlocking. Once in while when trying to unlock the phone double crash and reboot occurs.

**Additional context**
One of the crashes where the fingerprint sensor was involved can be found in the other issue:
https://github.com/sonyxperiadev/bug_tracker/issues/399#issuecomment-503714559

**Comment by stefanhh0** [comment]
Uptime of the phone is more than 20h. I never had such a long uptime when the fingerprint sensor was activated.

**Comment by stefanhh0** [comment]
Testing this one again currently on Android 10 with all the latest changes to the fingerprint sensor code to see if this issue has been resolved meanwhile.

**Comment by stefanhh0** [comment]
One important observation that is missing here symptom wise. The reboot of the phone only happens after the phone haven't been used for some minutes and was then trying to wake it up. So maybe something in conjunction with powersaving resp. sleep modes.

**Comment by jerpelea** [comment]
legacy device
