### ISSUE TITLE
[Documentation] incorrect symbol '–' in tutorial-step-5 

### ISSUE THREAD

**Issue by billchenchina** [sonyxperiadev/bug_tracker#443]
**Platform:** General
**Device:** General
**Kernel version:** 
**Android version:** P 9.0.0

**Description**

In https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0#tutorial-step-5
```
To start the build, type:
make –j <insert the cpu thread number of your computer>
```
You should replace the hyphen from `–` to `-`

**Symptoms**
ninja: error: unknown target '–j6'
**How to reproduce**
Just Follow the documentation to build AOSP Pie 9.0.0

**Comment by ix5** [comment]
Still valid https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0-2#tutorial-step-5
https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-10-0-0#tutorial-step-5

Probably some auto-typography feature.

**Comment by jerpelea** [comment]
fixed

**Comment by ix5** [comment]
Still shows `–` instead of `-`.
