### ISSUE TITLE
Sony Dora : Android Pie android-9.0.0_r44/android-9.0.0_r40 problem

### ISSUE THREAD

**Issue by ext32** [sonyxperiadev/bug_tracker#445]
Compiling android-9.0.0_r44 and android-9.0.0_r44 (maybe also android-9.0.0_r37) with dora device resulting in a system without phone and not usable after first boot.
Android android-9.0.0_r34 and android-9.0.0_r35 works ok.
Please check and let me know if you need more info

**Comment by ix5** [comment]
There's an issue template that you should fill out so we have all the information we need from you.
You seem to have deleted all of that and just typed in your issue free-form. That's not very helpful.

Please describe:
- "Without phone": Do you mean that you cannot place calls?
- "Not usable after first boot": That can mean a large number of things. Is it slow, or completely unusable(blank screen, ...)?

And double-check that you flashed the correct OEM version - v9 as of now.

A **complete** `dmesg` and `adb logcat` would also help immensely.

For reference:

---

**Platform:** 
**Device:** 
**Kernel version:** 
**Android version:** 

**Description**
Write the issue description here.

**Symptoms**
Write the symptoms here.

**How to reproduce**
Write how to reproduce here.

**Comment by ext32** [comment]
Ok let me describe better the problem.
I am using my own aosp builds since last year.
I have a box that can compile aosp fine without any errors.
I have build and use version android-9.0.0_r35 and i am very happy with it.

I tried to compile every other version since r35(r37,r40,r44) just for testing(and for updating also).
I am followring  the instructions here https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0.
Compilation fine,no errors .
Produced boot,recovery,cache,userdata,system img files.
Flashing with fastboot and clean install. Pone starts without sim (say no sim detected) so language cannot be auto detected and can only be used as small tablet.
Flashing with fastboot (dirty or upgrading) over previous r35 version that works ok  the phone hangs.After 1-2 minutes or so ,  a black screen starts and if i press the power button for a while i can select only to power off the device.

Reverting back to previously compiled r35 image or build a new one from scratch  (same version) works ok if i wipe the device first.
Downgrading device to r35 after flashing buggy builds without wiping the device,dont work,ask me to wipe the device. 
I dont know how to get logcat or adb logs if the device cant start .

Thanx a lot for your time,i am terribly sorry i cant fill a more specific bug report for an issue like that.

**Comment by ix5** [comment]
You say "the phone starts without sim and can only be used as a small tablet".
So you get the UI already, which should be sufficient to obtain adb logs.

Please compile a `userdebug` build (use `lunch aosp_f8131-userdebug` instead of `lunch aosp_f8131-user`) and then just `adb logcat -b all > logcat.txt` from a computer with your device attached.

**Comment by ext32** [comment]
modifying /android/frameworks/base/packages/SystemUI/res/values directly or with an overlay make the system unstable.
Its strange since the only thing i am changing is the below lines :

    
    <integer name="quick_settings_num_columns">4</integer>

    
    <integer name="quick_settings_num_rows">1</integer>

    
    <integer name="quick_settings_user_time_settings_tile_span">1</integer>

    
    <string name="quick_settings_tiles_default" translatable="false">
        wifi,cell,bt,location,flashlight,dnd,rotation,battery,airplane,hotspot,saver,night
    </string>

    
    <string name="quick_settings_tiles_stock" translatable="false">
        wifi,cell,bt,location,flashlight,dnd,rotation,battery,airplane,hotspot,saver,night
    </string>
Any help is appreciated

**Comment by ix5** [comment]
That's an AOSP issue and has nothing to do with this project. Please file a bug report with Google, I believe the correct location is issuetracker.google.com.
You will need to provide them with more information than "make system unstable"...

There should be a range of "safe" values for SystemUI tunable values, you will need to find out yourself what it is.

Can you please close this bug?

**Comment by ext32** [comment]
Could be aosp issue could be just wrong sepolicy .Issue closed
