### ISSUE TITLE
[Kagura] Playback error.

### ISSUE THREAD

**Issue by Natalcia** [sonyxperiadev/bug_tracker#448]
**Platform:** Tone
**Device:** Kagura
**Kernel version:** 4.9.174-gb8bc8f9bebfa 
**Android version:** AOSP 9 Pie

**Description**
After few days of uptime videos can't play anymore. Youtube shows black screen but sound is fine, twitter shows playback error, mpv freezes and many more.

**Symptoms**
We can't play videos until reboot.

**How to reproduce**
I don't know, wait long time and for example youtube will freeze while watching video and then it's broken
[logcat_08-02-2019_16-55-02.txt](https://github.com/sonyxperiadev/bug_tracker/files/3462988/logcat_08-02-2019_16-55-02.txt)
.

**Comment by jerpelea** [comment]
@Natalcia updates on this ?
there were serveral fixes since the bug was posted but there is no followup

**Comment by Natalcia** [comment]
To be honest right now I'm back on stock, I have banking apps installed etc and can't really test if it's fixed
