### ISSUE TITLE
AOSP - Xperia X - Tone - Wifi P2P not working

### ISSUE THREAD

**Issue by P26Puteaux** [sonyxperiadev/bug_tracker#450]
**Platform:** Tone -
**Device:**  Xperia X
**Kernel version:** 
**Android version:** latest Oreo

**Description**
I try to use Wifi P2P in my ROM
No menu in UI can be seen to activate Wifi P2P with Oreo
Calling WifiP2PService generate issues, while it was possible to call it on 6.0.1_r74

**Symptoms**
"WifiP2pService: Unable to change interface settings: java.lang.IllegalStateException : command '44 interface setcfg p2p0 0.0.0.0 up' failed with '400 44 Failed to clear address (No such device)'
WifiP2pService : P2p socket connection failed".

- CommandListener: Failed to retreive HW addr for p2p0 (No such device) 

- WifiP2pService : Unable to change interface settings : java.IllegalStateException : command '39 interface setcfg p2p0 0.0.0.0 up' failed with '400 39 Failed to clear address (No such device)' 

**How to reproduce**
Can be reproduced easily, everytime

**Comment by jerpelea** [comment]
is this bug seen on Xperia X (loire platform) only ?

**Comment by sraase** [comment]
Can you try some intermediate Android versions, in order to pinpoint approximately whan it broke?

**Comment by P26Puteaux** [comment]
It son Loire platform correct. I dont have other device with me.
6.0.1_r74 was latest version it was working

**Comment by oshmoun** [comment]
the interface name changed after switching to brcmfmac, android needs to be made aware of that by setting the prop `wifi.direct.interface`

**Comment by jerpelea** [comment]
@oshmoun please remeber that the bug is about Android 8 !

**Comment by jerpelea** [comment]
please note 
https://github.com/sonyxperiadev/device-sony-loire/blob/o-mr1/rootdir/vendor/etc/wifi/wpa_supplicant_overlay.conf#L3

**Comment by oshmoun** [comment]
@P26Puteaux can you please check which driver is used for wifi? should be visible in the output of `ifconfig`

**Comment by P26Puteaux** [comment]
Thanks for your help
Here are some additional info

Last working version -6.0.1_r74.

Android 8 :

Ifconfig wlan0

wlan0 Link encap:Ethernet HWaddr 60:f1:89:d2:5b:bb Driver bcmsdh_sdmmc

Android 6 :

Ifconfig doesn’t send back info about driver on Marshmallow.

Ifconfig wlan0

wlan0 Link encap:Ethernet HWaddr 58:48:22:A6:72:A2

Ifconfig p2p-wlan0-0

p2p-wlan0-0 Link encap:Ethernet HWaddr 5A:48:22:A6:F2:A2

**Comment by oshmoun** [comment]
thanks for the info
you can try adding the prop `wifi.direct.interface=p2p-wlan-0` to `build.prop` to see if that makes it work

**Comment by P26Puteaux** [comment]
Thanks for your help

I had time to make some tries, modifying wifi.direct interface with following values
- p2p-wlan-0
- p2p-wlan0
- p2p-dev-wlan0
- p2p-wlan0-0

I got error message below
WifiP2pService : Unable to change interface settings: java.lang.IllegalStateException: command '24 interface setcfg p2p..0 0.0.0.0 up' failed with '400 24 Failed to clear address (No such device)'.

Only when used value p2p-wlan0 , value 24 is replaced by 34 in error message

I have no clue where is issue ...

**Comment by oshmoun** [comment]
https://github.com/sonyxperiadev/device-sony-loire/pull/255
any confirmation that this does indeed work fine is very welcome
