### ISSUE TITLE
[Question] How is selection of AOSP branch done?

### ISSUE THREAD

**Issue by chris42** [sonyxperiadev/bug_tracker#451]
Hi there, 

I just have a question: How is the base branch of AOSP determined? Right now it seems to follow the Pixel 3? Is it then right to assume to just pick the new Pixel 3 branch each month and compile (e.g. now from _r44 to _r46 for Android 9)? 
Or is more done and adapted?

Kind regards
  Chris

**Comment by MartinX3** [comment]
Usually this manual gets updated :)

https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0

**Comment by chris42** [comment]
Yes, I know that and I am interested in how that is chosen?

**Comment by jerpelea** [comment]
@chris42 we are following the closest Pixel
