### ISSUE TITLE
[loire] Kernel 4.4 + QCOM Camera: num_cameras=0

### ISSUE THREAD

**Issue by fredldotme** [sonyxperiadev/bug_tracker#452]
**Platform:** Loire
**Device:** Suzu
**Kernel version:** 4.4
**Android version:** 7.1

**Description**
When the QCOM camera HAL iterates available media-devices and related v4l sub-devices it doesn't find any appropriate camera devices, resulting in num_cameras set to 0.

**Symptoms**
```
QCamera : <MCI><INFO> get_num_of_cameras: 2785: num_cameras=0
```

**How to reproduce**
- Boot Ubuntu Touch for Suzu
- Check sudo logcat | grep -i camera

**Links and additional info**
https://github.com/Halium/projectmanagement/issues/98

**Comment by fredldotme** [comment]
In case building the images is too much to ask for, here is a prebuilt Halium image (including install instructions):

https://forum.xda-developers.com/xperia-x/development/rom-ubuntu-touch-sony-xperia-x-t3958100

To access the device you'll need a static IP address like `10.15.19.100` and SSH into `phablet@10.15.19.82`

Logcat can be started using:
`sudo env LD_LIBRARY_PATH=/system/lib64:/vendor/lib64 /system/bin/logcat | grep -i camera`

**Comment by fredldotme** [comment]
Additionally the sensor initialization fails:

```
10-13 19:52:32.850    34    34 I QCamera : <MCI><INFO> get_num_of_cameras: 2785: num_cameras=0
10-13 19:52:32.867    43    43 I mm-camera: <SENSOR>< INFO> 590: sensor_init_probe: failed: to probe eeprom bin sensors (non-fatal)
10-13 19:52:32.868    43    43 I mm-camera: <SENSOR>< INFO> 247: sensor_probe: [imx300] probe failed.
10-13 19:52:32.868    43    43 I mm-camera: <SENSOR>< INFO> 393: sensor_init_xml_probe: failed: to probe imx300
10-13 19:52:32.869    43    43 I mm-camera: <SENSOR>< INFO> 247: sensor_probe: [imx214] probe failed.
10-13 19:52:32.870    43    43 I mm-camera: <SENSOR>< INFO> 393: sensor_init_xml_probe: failed: to probe imx214
10-13 19:52:32.881    38    38 I mm-camera: <IMGLIB>< INFO> 2157: faceproc_sw_wrapper_load: Loading faceproc library
10-13 19:52:32.883    34    34 I mm-camera: <SENSOR>< INFO> 590: sensor_init_probe: failed: to probe eeprom bin sensors (non-fatal)
10-13 19:52:32.884    34    34 I mm-camera: <SENSOR>< INFO> 247: sensor_probe: [imx300] probe failed.
10-13 19:52:32.884    34    34 I mm-camera: <SENSOR>< INFO> 393: sensor_init_xml_probe: failed: to probe imx300
10-13 19:52:32.886    34    34 I mm-camera: <SENSOR>< INFO> 247: sensor_probe: [imx214] probe failed.
10-13 19:52:32.887    34    34 I mm-camera: <SENSOR>< INFO> 393: sensor_init_xml_probe: failed: to probe imx214
```

**Comment by jerpelea** [comment]
the camera was tested on AOSP and works ok
