### ISSUE TITLE
Front camera does not work on most of apps

### ISSUE THREAD

**Issue by XperiaDeveloper** [sonyxperiadev/bug_tracker#454]
**Platform:** Loire
**Device:** Suzu
**Kernel version:** 4.4
**Android version:** 8.1 
**Software binaries version:** R17

**Description**
The image doubles, and blue and gray stripes randomly appear. See the attached snapshot.
![Screenshot_20190801-131252](https://user-images.githubusercontent.com/39955310/64257452-ad50bd00-cf25-11e9-8659-af758242754d.png)

**Symptoms**
On front camera:
- Can not take photo. 
- Display is doubled
- Display has wrong color.

**How to reproduce**
Install one of the following apps and switch to front camera: 
- Camera MX
- Z Camera
- DSLR Camera

**Additional context**
Please see the attached log file. 
[log-vanilla-froncamera.log](https://github.com/sonyxperiadev/bug_tracker/files/3574625/log-vanilla-froncamera.log)

**Comment by YuriyMosiychuk** [comment]
The same problem on android 9 with any software binaries, but only in several apps such as Face Unlock, video messages in Telegram X, video calls in Instagram.
https://github.com/sonyxperiadev/bug_tracker/issues/332
