### ISSUE TITLE
[Ganges] No screen in recovery| Not working recovery ?

### ISSUE THREAD

**Issue by Haxk20** [sonyxperiadev/bug_tracker#458]
Platform:Ganges
Device: Mermaid
Kernel version:4.9.185
Android version: 9.0.0_r46
Software binaries version: latest 

**Description**
When i boot into stock recovery (Power + Volume Down) i get just black screen. I can control the recovery it seems because when i press power button the device reboots as expected if the first option is reboot to system.
I just did a little more testing and it seems that power button is just reboot because if i press volume buttons nothing happens and power button reboots the device.
Im also unable to get adb working.
`error: exec '/system/bin/sh' failed: No such file or directory
`

**How to reproduce**
Boot into recovery on Mermaid

**Additional context**
Im unable to get adb working so im attaching the boot image i build.
[boot.zip](https://github.com/sonyxperiadev/bug_tracker/files/3606643/boot.zip)

**Comment by ix5** [comment]
Is this still happening @Haxk20 ?

**Comment by Haxk20** [comment]
Recovery broken. But that patch fixed it. So close this one.
