### ISSUE TITLE
[ganges] Update from SDcard shows nothing in recovery

### ISSUE THREAD

**Issue by Haxk20** [sonyxperiadev/bug_tracker#459]
**Platform:** Ganges
**Device:** Mermaid
**Kernel version:** 4.9.185
**Android version:** 9
**Software binaries version:** latest

**Description**
When using recovery and trying to use update from SDcard it shows nothing. Its just empty even tho i have a zip file on internal and external SDcard. This makes it unable to flash Gapps

**Additional context**
I havent looked at fstab yet since i didnt have the time but i suppose it might just be a fstab issue.

**Comment by Haxk20** [comment]
just took a look at fstab there was mising encryptable=userdata which might be the cause of this. just made make clean few minutes ago so will take time before i can test if it fixes it

**Comment by Haxk20** [comment]
This has not fixed the issue sadly. I still cant flash anything from recovery which makes the recovery pretty much useless.

**Comment by ix5** [comment]
Is this still an issue?

**Comment by Haxk20** [comment]
Well recovery is completely down and not working and well yes it's still an
issue as we can't flash stuff from SD card even with working one.
