### ISSUE TITLE
[suzu][kagura] Can't send anything via Android Beam between a suzu and a kagura device

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#46]
**Platform:** loire, tone
**Device:** suzu, kagura
**Kernel version:** 4.4.21-g38895e1-dirty
**Android version:** 8.0.0

**Description**
Android Beam is not working at all when a Suzu device is trying to send a file to or receive a from (e.g. a photo) a Kagura device.

**Symptoms**
Android Beam appears to be working perfectly fine when the device send/receive to another devices such as a Maple device, or any other device that supports Android Beam. Very occasionally the receiving device will receive the file via Bluetooth, only when the sending device is trying to send the file via Android Beam to another device which was tapped to initiate the transfer.

**How to reproduce**
1. Select a file for sending.
2. Select Share Via -> Android Beam
3. Place devices close to each other with both of their NFC detection areas almost touching.

**Logcat**
```
216:05-25 14:02:59.224 E/NFC     ( 2563): invokeBeamInternal()
324:05-25 14:02:59.418 W/BeamShareActivity( 2563): Receiver not registered: com.android.nfc.BeamShareActivity$1@171ba1
594:05-25 14:03:00.327 I/RenderThread( 3911): type=1400 audit(0.0:41): avc: denied { search } for name="proc" dev="debugfs" ino=6325 scontext=u:r:nfc:s0 tcontext=u:object_r:debugfs_kgsl:s0 tclass=dir permissive=1
607:05-25 14:03:02.550 I/BrcmNfcNfa( 2563): NFC received ntf gid:1
608:05-25 14:03:02.551 I/BrcmNfcNfa( 2563): nfa_dm_nfc_response_cback () NFC_RF_FIELD_REVT(0x5007)
609:05-25 14:03:02.557 I/BrcmNfcNfa( 2563): NFC received ntf gid:1
610:05-25 14:03:02.557 I/BrcmNfcNfa( 2563): nfa_dm_nfc_response_cback () NFC_RF_FIELD_REVT(0x5007)
611:05-25 14:03:02.562 I/BrcmNfcNfa( 2563): NFC received ntf gid:1
612:05-25 14:03:02.563 I/BrcmNfcNfa( 2563): nfa_dm_nfc_response_cback () NFC_RF_FIELD_REVT(0x5007)
613:05-25 14:03:02.601 I/BrcmNfcNfa( 2563): NFC received ntf gid:1
614:05-25 14:03:02.601 I/BrcmNfcNfa( 2563): nfa_dm_nfc_response_cback () NFC_RF_FIELD_REVT(0x5007)
615:05-25 14:03:02.603 I/BrcmNfcNfa( 2563): NFC received ntf gid:1
616:05-25 14:03:02.603 I/BrcmNfcNfa( 2563): nfa_dm_nfc_response_cback () NFC_RF_FIELD_REVT(0x5007)
617:05-25 14:03:02.604 I/BrcmNfcNfa( 2563): NFC received ntf gid:1
618:05-25 14:03:02.605 I/BrcmNfcNfa( 2563): nfa_dm_nfc_response_cback () NFC_RF_FIELD_REVT(0x5007)
...
```

**Comment by kholk** [comment]
Sorry, I feel some confusion.
Suzu<=>Kagura KO
Suzu<=>Maple OK
Kagura<=>Maple ??

**Comment by dimitar10** [comment]
**Kagura<=>Maple OK** (both send and receive)

I tested the Kagura with both Oreo and Nougat, and the Maple was running Oreo.

And one other error occurred from the testing done previously:

`"The receiver's device doesn't support large file transfer via beam."`

, but at the moment I can't reproduce it on any of the three devices, and can't remember whether it occurred on the Suzu or the Kagura.

**Comment by LLJY** [comment]
Im unable to replicate this issue with my Suzu and kagura

**Comment by jerpelea** [comment]
unable to replicate
