### ISSUE TITLE
[ganges] Tele camera not available in AOSP ?

### ISSUE THREAD

**Issue by Haxk20** [sonyxperiadev/bug_tracker#462]
**Platform:** ganges
**Device:** Mermaid
**Kernel version:** 4.9.185
**Android version:** 9
**Software binaries version:** latest 

**Description**
When using any camera app. OpenCamera, Stock AOSP camera, Google camera i cant get second Tele camera to work.
In the logcat i took a photo. Switched camera API2 to 1.

**How to reproduce**
Use any camera app and try any possible way to enable second camera. In stock SONY camera there was 1x and 2x switch which would switch between the cameras. This isnt the case in any other app.

**Additional context**
[logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/3617659/logcat.txt)
[dmesgsony.txt](https://github.com/sonyxperiadev/bug_tracker/files/3617663/dmesgsony.txt)

**Comment by Haxk20** [comment]
Also im sorry for all the ganges issues im posting. IDK if not many users have not flashed AOSP on their phone which is likely as its pretty new phone but still its better to post the issues then be silent about them.

**Comment by Haxk20** [comment]
Here is also dumpsys media.camera. It seems like no client is attached to the second camera.
[cameradumpsys.txt](https://github.com/sonyxperiadev/bug_tracker/files/3623330/cameradumpsys.txt)

**Comment by oshmoun** [comment]
pretty certain this is simply to do with the fact that aosp does not support multiple backcameras, but I'm glad to be proven wrong if anybody has a counter-example.
so, is the ability to switch backcamera like that possible on any other device running a custom rom?

oh and don't worry about posting many issues, that's what the tracker is for :)

**Comment by MartinX3** [comment]
@oshmoun
I hope that helps somehow
https://source.android.com/devices/camera/multi-camera

**Comment by jerpelea** [comment]
the second camera was not implemented in the vendor side and there is no plan to implement it for the legacy devices

**Comment by Haxk20** [comment]
@jerpelea Legacy ? Mermaid and Kirin are half a year old. How can that be legacy device ? Sure the chip is 2017 but still i buy a NEW device and i cant have second camera because Sony decided that its not worth their time even tho it would maximally take 1 week for one guy to do it ?
When i buy a device and i start a development for it i expect that the vendor blobs would support all the hardware in the device and not that you develop the blobs but decided when they were developing it to not implement the second camera or what ?
I know that my talk wont have any damn result but its still crazy that i cant have both cameras.

**Comment by jerpelea** [comment]
For the camera there are 2 implementations and one is based on the old qcom camera framework. Unfortunately there is nothing I can do to add the second camera to this framework.

**Comment by Haxk20** [comment]
@jerpelea So basically until i flash stock firmware back i have no chance of getting second camera working ? If so thats just amazing.

**Comment by Haxk20** [comment]
@jerpelea And to make it clear. Im not mad at you. You are doing amazing work here on SODP but im sure you agree that its little crazy to not have the second camera working.
Sure the tele camera doent work and the main one works OK but so its kind of OK as the tele camera wasnt getting that much use either but its always nice to have it.

**Comment by ix5** [comment]
Unless Qualcomm decides to release a camera HAL (+ closed-source blobs!) that supports multiple cameras *and* works with "legacy" devices, there is little we can do.
It's not "one guy, one week", it's something that takes a whole team and a well-equipped lab to do.

The word "legacy" might have set you off unintentionally, Alin simply means that devices up until the ganges platform use camera framework A, and devices from kumano up use framework B, which happens to be quite different.
Retrofitting extra capabilities into framework A is out of scope and for the closed-source side of things, Qcom most likely won't lift a finger.

N.b. when I say "framework" I really mean CodeAurora Forum branch/tag...
Also, rewriting the camera framework means we can most likely no longer simply merge in updates from CAF - that'd get significantly harder and might introduce bugs as the whole thing doesn't have a publicly accessible test suite.

**Comment by sraase** [comment]
The new camera HAL (CamX) supports multiple cameras just fine. All four sensors on Griffin will be supported. But this HAL only supports Tama and Kumano, and cannot be used on Ganges.

**Comment by Haxk20** [comment]
> Unless Qualcomm decides to release a camera HAL (+ closed-source blobs!) that supports multiple cameras _and_ works with "legacy" devices, there is little we can do.
> It's not "one guy, one week", it's something that takes a whole team and a well-equipped lab to do.
> 
> The word "legacy" might have set you off unintentionally, Alin simply means that devices up until the ganges platform use camera framework A, and devices from kumano up use framework B, which happens to be quite different.
> Retrofitting extra capabilities into framework A is out of scope and for the closed-source side of things, Qcom most likely won't lift a finger.
> 
> N.b. when I say "framework" I really mean CodeAurora Forum branch/tag...
> Also, rewriting the camera framework means we can most likely no longer simply merge in updates from CAF - that'd get significantly harder and might introduce bugs as the whole thing doesn't have a publicly accessible test suite.

Thats a very good explanation of the issue. Thank you.
Yeah i understand that you cannot do much about closed source blobs.
Yes the word "legacy" did set me off a little im sorry.
I just wanted to say that it is very sad that when i buy a device thats literally half a year from its release and when i flash AOSP on it i would expect both cameras to work.
But anyways. How did stock firmware get both cameras working ? Because i mean the devs either had to port the new HAL to ganges, Create totally new HAL or just implememted multiple cameras into the old HAL.
Or did i miss something ?

**Comment by ix5** [comment]
Sony has their own proprietary camera HAL. We are using the partially open source Qcom camera HAL for SODP.

**Comment by mirh** [comment]
Just friendly reminder that anyhow, it is technically possible to use [stock](https://github.com/Myself5/android_device_sony_maple) [blobs](https://forum.xda-developers.com/xperia-xz1-compact/development/secd-extension-t3743615) on aosp [since](https://github.com/x-keita/android_device_sony_shinano-common) [ever](https://forum.xda-developers.com/xperia-z1/development/rom-lineageos-14-1-unofficial-t3628209). 
It's a tad more difficult though.

**Comment by Haxk20** [comment]
@mirh Im aware of this. I just dont want to do it TBH. I hate SHIMs ever since i had to make few of them on Xperia P. I would love to avoid shims as much as possible. So yes it is possible to use stock blobs but it would be a pain thats really not worth the second camera.
