### ISSUE TITLE
[Q] [Ganges] SIM card doesnt work

### ISSUE THREAD

**Issue by Haxk20** [sonyxperiadev/bug_tracker#463]
**Platform:** Ganges
**Device:** Mermaid
**Kernel version:** 4.9.185
**Android version:** 10
**Software binaries version:** latest

**Description**
When launching android 10 i get the option to enter passcode for SIM but when i do the dialog dissapears but SIM card doesnt work even after that.

**How to reproduce**
Boot android and enter sim code.

**Additional context**
At this point im unable to provide logcat or dmesg as i had to switch back to 9 as i need to receive calls.
Only thing i can share are system, vendor, boot, userdata images.

**Comment by MarijnS95** [comment]
Does systemui crash?
```
09-19 14:42:22.924  1432  2755 E AndroidRuntime: FATAL EXCEPTION: Thread-10
09-19 14:42:22.924  1432  2755 E AndroidRuntime: Process: com.android.systemui, PID: 1432
09-19 14:42:22.924  1432  2755 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int[] com.android.internal.telephony.ITelephony.supplyPinReportResultForSubscriber(int, java.lang.String)' on a null object reference
09-19 14:42:22.924  1432  2755 E AndroidRuntime: 	at com.android.keyguard.KeyguardSimPinView$CheckSimPin.run(KeyguardSimPinView.java:261)
09-19 14:42:22.937  1134  1466 I am_crash: [1432,0,com.android.systemui,818429453,java.lang.NullPointerException,Attempt to invoke interface method 'int[] com.android.internal.telephony.ITelephony.supplyPinReportResultForSubscriber(int, java.lang.String)' on a null object reference,KeyguardSimPinView.java,261]
```

The phone/telephony service is going crazy. It is funny that I saw that, but still had working telephony on Akatsuki. A fix is on the way!

**Comment by Haxk20** [comment]
@MarijnS95 You are always so quick. Good job. And thanks. Wont be able to test it but i will take your word for it that its fixed. Im now fixing my build of LineageOS for Ganges.

**Comment by MarijnS95** [comment]
Well I needed to be quick, being at risk of having telephony issues with Akatsuki when not near a computer (or not being able to take any of the other phones as temporary replacement).

Anyway, you might want to check https://github.com/afstamming/, and perhaps even contribute. We are looking to make an unholy SODP-on-Lineage effort, but no time has been invested from my side yet.

**Comment by Haxk20** [comment]
@MarijnS95 Indeed. Screen goes black for second or 2 and no SIM found after that. And count me in on that (Unholy port LOL). If you could just add ganges repos in there since i dont have write rights. I will commit changes i made so far.

**Comment by Haxk20** [comment]
just flashed Q back as lineage was working just fine and after applying your fix its indeed fixed.
Will leave opened until that PR is merged

**Comment by MarijnS95** [comment]
https://help.github.com/en/articles/closing-issues-using-keywords

This will automatically be closed once the merge button is clicked :wink: 
We still need to have a little discussion on the IMO ugly implementation (as I'm not intricately familiar with the RIL/telephony system in android) before that, though.

**Comment by Haxk20** [comment]
@MarijnS95 Im aware that this will be closed once merge button is clicked. I contributed to some projects to fix issues (mainly GNOME :))
