### ISSUE TITLE
[Q][ganges/possibly all] Alarms broken.

### ISSUE THREAD

**Issue by Haxk20** [sonyxperiadev/bug_tracker#465]
**Platform:** ganges but possibly all
**Device:** mermaid
**Kernel version:** 4.9.185
**Android version:** 10
**Software binaries version:** latest

**Description**
As title says. Alarms dont fire up.

**Symptoms**
Getting fired from work is pretty good sympom of it.

**How to reproduce**
Set an alarm and wait.

**Additional context**
[logcatalarm.txt](https://github.com/sonyxperiadev/bug_tracker/files/3639968/logcatalarm.txt)

**Comment by MarijnS95** [comment]
Without reading the logs, I think the fix has already been merged https://github.com/sonyxperiadev/repo_update/pull/108

**Comment by Haxk20** [comment]
Dangit i forgot to repo sync. Thanks @MarijnS95

**Comment by MarijnS95** [comment]
Yep, as expected:
```
09-22 18:27:00.144  6098  6098 I AlarmClock: Setting fire state to instance 1
09-22 18:27:00.148  1485  1485 D KeyguardClockSwitch: Updating clock: 627
09-22 18:27:00.170  6098  6098 V AlarmClock: *** notifyChange() id: 1 url content://com.android.deskclock/instances/1
09-22 18:27:00.183  6098  6098 D Events  : [Alarm] [Fire]
09-22 18:27:00.187  6098  6098 I AlarmClock: Scheduling state change 6 to instance 1 at Sun 6:37 PM (1569170220000)
09-22 18:27:00.200  6098  6098 I AlarmClock: Canceling upcoming AlarmClockInfo
09-22 18:27:00.211  6098  6098 V AlarmClock: AlarmService.start with instance: 1
09-22 18:27:00.220  6098  6098 V AlarmClock: Displaying alarm notification for alarm instance: 1
09-22 18:27:00.231  6098  6098 V AlarmClock: Clearing notifications for alarm instance: 1
09-22 18:27:00.239  1200  5245 W ActivityManager: Permission Denial: startForeground from pid=6098, uid=10095 requires android.permission.FOREGROUND_SERVICE
09-22 18:27:00.243  6098  6098 D AndroidRuntime: Shutting down VM
09-22 18:27:00.246  6098  6098 E AndroidRuntime: FATAL EXCEPTION: main
09-22 18:27:00.246  6098  6098 E AndroidRuntime: Process: com.android.deskclock, PID: 6098
09-22 18:27:00.246  6098  6098 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.android.deskclock.alarms.AlarmService@4c25b57 with Intent { act=change_state cat=[ALARM_MANAGER] dat=content://com.android.deskclock/instances/1 flg=0x10000004 cmp=com.android.deskclock/.alarms.AlarmService (has extras) }: java.lang.SecurityException: Permission Denial: startForeground from pid=6098, uid=10095 requires android.permission.FOREGROUND_SERVICE
```

> Getting fired from work is pretty good sympom of it.

:joy:
Blame google in this instance, [the fix](https://android-review.googlesource.com/c/platform/packages/apps/DeskClock/+/987326) is there for 3 months and nobody bothered to merge it to Q branches (as it stands, this still hasn't landed in `android10-dev` so we might as well carry around the backport until Android 11, or CL it ourselves).
(In all seriousness, I hope you haven't been fired... Pro-tip for next time is to always test the alarm, _and_ use a secondary device as backup. That's how I found and fixed this issue just the evening before needing it :see_no_evil:)
