### ISSUE TITLE
[Q][tone] Fail to build 

### ISSUE THREAD

**Issue by billchenchina** [sonyxperiadev/bug_tracker#468]
**Platform:** 
**Device:** Xperia X Performance
**Kernel version:** 
**Android version:** Q
**Software binaries version:** 

**Description**

Follow the guide https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-10-0-0#tutorial-step-1

**Symptoms**
Write the symptoms here.
```
:~/android$ make -j6
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=10
TARGET_PRODUCT=aosp_f8131
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=kryo
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=kryo
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.4.0-157-generic-x86_64-Ubuntu-16.04.6-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=QP1A.190711.019
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/sony/tone
============================================
wildcard(out/target/product/dora/clean_steps.mk) was changed, regenerating...
FAILED: ninja: 'kernel/sony/msm-4.14/common-kernel/kernel-dtb-dora', needed by 'out/target/product/dora/kernel', missing and no known rule to make it
11:09:23 ninja failed with: exit status 1

#### failed to build some targets (01:08 (mm:ss)) ####
```
**How to reproduce**
Write how to reproduce here.

**Additional context**
Add any other context, e.g. upload logs or screenshots about the bug here.

**Comment by jerpelea** [comment]
for the moment the release is intended for bugfixes and we are not providing a prebuilt kernel. If you are a kernel developer you know what to do.

**Comment by jerpelea** [comment]
prebuilt images will be added for the vendor beta release

**Comment by billchenchina** [comment]
Thanks! @jerpelea
