### ISSUE TITLE
Factory reset failed to erase data

### ISSUE THREAD

**Issue by AnnaFangGraphite** [sonyxperiadev/bug_tracker#47]
**Platform:** 
yoshino
**Device:** 
maple
**Kernel version:** 
4.4.21
**Android version:** 
android-7.1.1_r55 with Firmware v5.

**Description**
Factory reset does not erase app data.

**How to reproduce**
1. In the contacts app, create a local account.
2. Go to settings->Backup & reset->Factory data reset, click on "RESET PHONE".
4. Wait until the phone boots up.
5. The local account created at step 1 is still there.

**Comment by jerpelea** [comment]
do you have a recovery installed on device ?

**Comment by AnnaFangGraphite** [comment]
Flashing recovery image resolved the issue. Many thanks!
