### ISSUE TITLE
[Q][ALL] No notifications when SMS is received.

### ISSUE THREAD

**Issue by Haxk20** [sonyxperiadev/bug_tracker#472]
**Platform:** ALL
**Device:** Tested on XZ by logcat provider and tested on ganges by me. Issue exists on both.
**Kernel version:** 4.9.185
**Android version:** 10
**Software binaries version:** Latest 4.9 ones.

**Description**
When SMS is received there is supposed to be a notification but the notification fails to show due to permissions error.

**How to reproduce**
Receive a SMS on Android 10.

**Additional context**
[Logcat](https://del.dog/lucasaziwi) Logcat is not provided by me but by XZ user. Thanks.

**Comment by Haxk20** [comment]
Seems like Android 10 r1 changed target API level to 28 introducing the crap that android O did to permissions and notifications.

**Comment by Haxk20** [comment]
i changed targetapi level to 24 again but cant flash at this point

**Comment by MarijnS95** [comment]
Are you sure the log is in there? I cannot match it to what I see here after sending myself an SMS:

```
10-02 18:59:49.680 28781 28855 I MessagingAppDataModel: ProcessSentMessageAction: Done sending SMS message 102 in conversation 18; status is SUCCEEDED
10-02 18:59:49.680 28781 28855 I MessagingAppDataModel: ProcessPendingMessagesAction: Scheduling pending messages
[...]
10-02 18:59:49.904 28781 28781 V MessagingApp: SmsReceiver.deliverSmsMessages
10-02 18:59:50.219 28781 28855 I MessagingAppDataModel: ReceiveSmsMessageAction: Received SMS message 103 in conversation 18, uri = content://sms/inbox/5
10-02 18:59:50.220 28781 28855 I MessagingAppDataModel: ProcessPendingMessagesAction: Scheduling pending messages
10-02 18:59:50.336  1073  6270 E NotificationService: No Channel found for pkg=com.android.messaging, channelId=null, id=0, tag=com.android.messaging:sms:, opPkg=com.android.messaging, callingUid=10078, userId=0, incomingUserId=0, notificationUid=10078, notification=Notification(channel=null pri=1 contentView=null vibrate=default sound=content://settings/system/notification_sound tick defaults=0x6 flags=0x11 color=0xff689f38 category=msg vis=PRIVATE)
10-02 18:59:50.349 28781 28855 I MessagingAppNotif: Notifying for conversation 18; tag = com.android.messaging:sms:, type = 0
10-02 18:59:50.357  1073  1112 W BroadcastQueue: Background execution not allowed: receiving Intent { act=com.android.Bugle.intent.action.ACTION_NOTIFY_CONVERSATIONS_CHANGED flg=0x10 } to com.android.messaging/.widget.BugleWidgetProvider
10-02 18:59:50.361  1073  1112 W BroadcastQueue: Background execution not allowed: receiving Intent { act=com.android.Bugle.intent.action.ACTION_NOTIFY_MESSAGES_CHANGED flg=0x10 (has extras) } to com.android.messaging/.widget.WidgetConversationProvider
```

Same as with the alarm clock... targetSdkVersion:
https://android-review.googlesource.com/c/platform/packages/apps/Messaging/+/941082
But of course, why would this be merged to q branches/tags :man_facepalming:

**Comment by Haxk20** [comment]
> Are you sure the log is in there? I cannot match it to what I see here after sending myself an SMS:
> 
> ```
> 10-02 18:59:49.680 28781 28855 I MessagingAppDataModel: ProcessSentMessageAction: Done sending SMS message 102 in conversation 18; status is SUCCEEDED
> 10-02 18:59:49.680 28781 28855 I MessagingAppDataModel: ProcessPendingMessagesAction: Scheduling pending messages
> [...]
> 10-02 18:59:49.904 28781 28781 V MessagingApp: SmsReceiver.deliverSmsMessages
> 10-02 18:59:50.219 28781 28855 I MessagingAppDataModel: ReceiveSmsMessageAction: Received SMS message 103 in conversation 18, uri = content://sms/inbox/5
> 10-02 18:59:50.220 28781 28855 I MessagingAppDataModel: ProcessPendingMessagesAction: Scheduling pending messages
> 10-02 18:59:50.336  1073  6270 E NotificationService: No Channel found for pkg=com.android.messaging, channelId=null, id=0, tag=com.android.messaging:sms:, opPkg=com.android.messaging, callingUid=10078, userId=0, incomingUserId=0, notificationUid=10078, notification=Notification(channel=null pri=1 contentView=null vibrate=default sound=content://settings/system/notification_sound tick defaults=0x6 flags=0x11 color=0xff689f38 category=msg vis=PRIVATE)
> 10-02 18:59:50.349 28781 28855 I MessagingAppNotif: Notifying for conversation 18; tag = com.android.messaging:sms:, type = 0
> 10-02 18:59:50.357  1073  1112 W BroadcastQueue: Background execution not allowed: receiving Intent { act=com.android.Bugle.intent.action.ACTION_NOTIFY_CONVERSATIONS_CHANGED flg=0x10 } to com.android.messaging/.widget.BugleWidgetProvider
> 10-02 18:59:50.361  1073  1112 W BroadcastQueue: Background execution not allowed: receiving Intent { act=com.android.Bugle.intent.action.ACTION_NOTIFY_MESSAGES_CHANGED flg=0x10 (has extras) } to com.android.messaging/.widget.WidgetConversationProvider
> ```
> 
> Same as with the alarm clock... targetSdkVersion:
> https://android-review.googlesource.com/c/platform/packages/apps/Messaging/+/941082
> But of course, why would this be merged to q branches/tags man_facepalming

Exactly. Whyyyy would they maybe test it before release ? Hmmmm. Users dont need message notifications. Actually i was using the toast message as my notification when i unlocked my screen HAHAHA

**Comment by Haxk20** [comment]
BTW @MarijnS95 I just did ./repo_update.sh and well this came on me hardware/qcom/power/Android.mk:2: error: hardware/qcom/sdm845/Android.mk: No such file or directory

**Comment by Haxk20** [comment]
The symlink to some file is broken. There is nothing in the folder just the broken symlink

**Comment by MarijnS95** [comment]
You should remove the symlink manually.

**Comment by MarijnS95** [comment]
https://github.com/sonyxperiadev/device-sony-common/commit/fd3e6c8c993d3aa7ef7ae9856d37dc09d4bbcf3f
https://github.com/sonyxperiadev/local_manifests/commit/f2bc4d5e1bfd7d4b48d373350b70dac49c70d2af

**Comment by Haxk20** [comment]
Ahhh yeah. Just another repo sync forgot to remove symlink thing. Thanks

**Comment by MarijnS95** [comment]
https://github.com/sonyxperiadev/repo_update/pull/109
Can you check if this applies cleanly after a sync?
