### ISSUE TITLE
[Q][Griffin]Failed to build kernel for Griffin

### ISSUE THREAD

**Issue by m1omoe** [sonyxperiadev/bug_tracker#473]
Platform:kuanmo
Device:griffin
Kernel version:4.14
Android version:10

/bin/sh: 1: flex: not found
scripts/Makefile.lib:211: recipe for target 'scripts/dtc/dtc-lexer.lex.c' failed
make[2]: *** [scripts/dtc/dtc-lexer.lex.c] Error 127
scripts/Makefile.build:678: recipe for target 'scripts/dtc' failed
make[1]: *** [scripts/dtc] Error 2
make[1]: *** 正在等待未完成的任务....
  HOSTCC  scripts/mod/file2alias.o
  HOSTLD  scripts/genksyms/genksyms
  HOSTLD  scripts/mod/modpost
Makefile:579: recipe for target 'scripts' failed
make: *** [scripts] Error 2
make: *** 正在等待未完成的任务....
  UPD     include/config/kernel.release

**Comment by sjllls** [comment]
sudo apt-get install flex

**Comment by jerpelea** [comment]
please follow the build guide

sudo apt-get install bison g++-multilib git gperf libxml2-utils make zlib1g-dev:i386 zip liblz4-tool libncurses5 libssl-dev bc flex
Now you have the
