### ISSUE TITLE
[ALL] Question regarding oem.img and odm.img

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#475]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.194-gf6b931bb01ed
**Android version:** android-10.0.0_r1
**Software binaries version:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_yoshino.zip
**Version baseband:** 1308-8921_47.1.A.16.20
**Build:** aosp_g8441-userdebug 10 QP1A.190711.019 eng.stefan.20191004.061057

**Description**
Not a bug, more a question but since I don't know other channels I am using the bugtracker for it. Building the odm.img has just been activated. I have flashed that one as well and then tried to flash the oem (SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_yoshino.img) which failed due to missing partition. So not completely sure if 
- odm replaces oem 
- oem needs to be flashed to a different partition
- odm.img should not have been flashed (how do I get back then the oem partition?)

```
stefan@mars:~/android/bin/current$ fastboot flash odm odm.img 
target reported max download size of 536870912 bytes
sending 'odm' (688 KB)...
OKAY [  0.042s]
writing 'odm'...
OKAY [  0.000s]
finished. total time: 0.043s
stefan@mars:~/android/bin/current$ fastboot flash oem oem.img 
target reported max download size of 536870912 bytes
sending 'oem' (221048 KB)...
FAILED (remote: No such partition.)
finished. total time: 0.000s
```
WIth the odm.img flashed, the phone just booted fine.

**Comment by MarijnS95** [comment]
Local odm building has been updated to Android 10, but still needs to be disabled for local builds. Only @jerpelea has the closed-source libraries to build this image. See:
https://github.com/sonyxperiadev/device-sony-common/pull/617/files#diff-8a62d0751aac220225b290895c0b2903R4

Now, this is called an `odm` image (and mounted as such) but flashed on the `oem` partition. As far as I'm aware I have always flashed `oem` and have no idea why the bootloader (which doesn't care at all about any setting in any of the aosp repos) is refusing this one on your side. `fastboot getvar all` could provide an insight?

**Comment by jerpelea** [comment]
all our devices have a oem partition that we use for storing the vendor binaries. you can simply ignore the message from flash until the odm will be built on demand.
please note that Android 10 is still under heavy bringup on our devices.

**Comment by jerpelea** [comment]
all our devices have a oem partition that we use for storing the vendor binaries. you can simply ignore the message from flash until the odm will be built on demand.
please note that Android 10 is still under heavy bringup on our devices.

**Comment by stefanhh0** [comment]
```
$ fastboot getvar all
(bootloader) unlocked:yes
(bootloader) off-mode-charge:0
(bootloader) charger-screen-enabled:0
(bootloader) battery-soc-ok:yes
(bootloader) battery-voltage:4311
(bootloader) version-baseband:1308-8921_47.1.A.16.20
(bootloader) version-bootloader:1306-5035_X_Boot_MSM8998_LA1.1_O_82
(bootloader) variant:MSM UFS
(bootloader) partition-type:cache:ext4
(bootloader) partition-size:cache: 0x17C00000
(bootloader) partition-type:userdata:ext4
(bootloader) partition-size:userdata: 0x587D76000
(bootloader) partition-type:system:ext4
(bootloader) partition-size:system: 0x138800000
(bootloader) secure:no
(bootloader) serialno:BH901PHQ9E
(bootloader) serial:a6b61918
(bootloader) product:G8441
(bootloader) max-download-size:536870912
(bootloader) kernel:uefi
all: 
Finished. Total time: 0.005s
```

**Comment by stefanhh0** [comment]
With the latest build odm.img is no longer built and oem,img flashes just fine.

**Comment by MarijnS95** [comment]
Apparently not all devices report the full partition layout through `getvar`, not even by querying them manually. That said I still don't understand out how `odm` was flashable and `oem` reports `No such partition.`
