### ISSUE TITLE
Error when build kernel

### ISSUE THREAD

**Issue by Chiyoda0913** [sonyxperiadev/bug_tracker#476]
**Kernel version:** 4.14
**Android version:** 10

**Description**
Seems miss some files when I use the script <build-kernel-clang.sh> in common kernel to build defconfig.
It's same whem I use gcc.

**Symptoms**
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  GEN     ./Makefile
  WRAP    arch/arm64/include/generated/uapi/asm/errno.h
  WRAP    arch/arm64/include/generated/uapi/asm/ioctl.h
  WRAP    arch/arm64/include/generated/uapi/asm/ioctls.h
  WRAP    arch/arm64/include/generated/uapi/asm/ipcbuf.h
  WRAP    arch/arm64/include/generated/uapi/asm/kvm_para.h
  WRAP    arch/arm64/include/generated/uapi/asm/mman.h
  WRAP    arch/arm64/include/generated/uapi/asm/msgbuf.h
  WRAP    arch/arm64/include/generated/uapi/asm/poll.h
  WRAP    arch/arm64/include/generated/uapi/asm/resource.h
  WRAP    arch/arm64/include/generated/uapi/asm/sembuf.h
  WRAP    arch/arm64/include/generated/uapi/asm/shmbuf.h
  WRAP    arch/arm64/include/generated/uapi/asm/sockios.h
  WRAP    arch/arm64/include/generated/uapi/asm/socket.h
  WRAP    arch/arm64/include/generated/uapi/asm/swab.h
  WRAP    arch/arm64/include/generated/uapi/asm/termbits.h
  WRAP    arch/arm64/include/generated/uapi/asm/termios.h
  WRAP    arch/arm64/include/generated/uapi/asm/types.h
  CHK     include/generated/uapi/linux/version.h
  UPD     include/generated/uapi/linux/version.h
  HOSTCC  scripts/basic/bin2c
  WRAP    arch/arm64/include/generated/asm/bugs.h
  WRAP    arch/arm64/include/generated/asm/clkdev.h
  WRAP    arch/arm64/include/generated/asm/delay.h
  WRAP    arch/arm64/include/generated/asm/div64.h
  WRAP    arch/arm64/include/generated/asm/dma.h
  WRAP    arch/arm64/include/generated/asm/dma-contiguous.h
  WRAP    arch/arm64/include/generated/asm/early_ioremap.h
  WRAP    arch/arm64/include/generated/asm/emergency-restart.h
  WRAP    arch/arm64/include/generated/asm/hw_irq.h
  WRAP    arch/arm64/include/generated/asm/irq_regs.h
  WRAP    arch/arm64/include/generated/asm/kdebug.h
  WRAP    arch/arm64/include/generated/asm/kmap_types.h
  WRAP    arch/arm64/include/generated/asm/local.h
  WRAP    arch/arm64/include/generated/asm/mcs_spinlock.h
  WRAP    arch/arm64/include/generated/asm/local64.h
  WRAP    arch/arm64/include/generated/asm/mm-arch-hooks.h
  WRAP    arch/arm64/include/generated/asm/msi.h
  WRAP    arch/arm64/include/generated/asm/qrwlock.h
  WRAP    arch/arm64/include/generated/asm/preempt.h
  WRAP    arch/arm64/include/generated/asm/rwsem.h
  WRAP    arch/arm64/include/generated/asm/segment.h
  WRAP    arch/arm64/include/generated/asm/serial.h
  WRAP    arch/arm64/include/generated/asm/set_memory.h
  WRAP    arch/arm64/include/generated/asm/sizes.h
  WRAP    arch/arm64/include/generated/asm/switch_to.h
  WRAP    arch/arm64/include/generated/asm/trace_clock.h
  WRAP    arch/arm64/include/generated/asm/unaligned.h
  WRAP    arch/arm64/include/generated/asm/user.h
  WRAP    arch/arm64/include/generated/asm/vga.h
  WRAP    arch/arm64/include/generated/asm/xor.h
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/sortextable
  HOSTCC  scripts/asn1_compiler
  HOSTCC  scripts/extract-cert
  HOSTCC  scripts/genksyms/genksyms.o
  HOSTCC  scripts/dtc/dtc.o
  SHIPPED scripts/genksyms/parse.tab.c
  SHIPPED scripts/genksyms/lex.lex.c
  CC      scripts/mod/empty.o
  HOSTCC  scripts/dtc/flattree.o
  SHIPPED scripts/genksyms/parse.tab.h
  HOSTCC  scripts/mod/mk_elfconfig
  HOSTCC  scripts/dtc/fstree.o
  CC      scripts/mod/devicetable-offsets.s
  HOSTCC  scripts/dtc/data.o
  HOSTCC  scripts/dtc/livetree.o
  HOSTCC  scripts/dtc/treesource.o
  HOSTCC  scripts/genksyms/parse.tab.o
  HOSTCC  scripts/dtc/srcpos.o
  HOSTCC  scripts/dtc/checks.o
  HOSTCC  scripts/genksyms/lex.lex.o
  HOSTCC  scripts/dtc/util.o
  LEX     scripts/dtc/dtc-lexer.lex.c
  HOSTCC  scripts/selinux/genheaders/genheaders
  YACC    scripts/dtc/dtc-parser.tab.h
  HOSTCC  scripts/selinux/mdp/mdp
  YACC    scripts/dtc/dtc-parser.tab.c
/Volumes/Android/los17/kernel/sony/msm-4.14/kernel/scripts/sortextable.c:23:10: fatal error: 'elf.h' file not found
#include <elf.h>
         ^~~~~~~
/Volumes/Android/los17/kernel/sony/msm-4.14/kernel/scripts/extract-cert.c:21:10: fatal error: 'openssl/bio.h' file not found
#include <openssl/bio.h>
         ^~~~~~~~~~~~~~~
1 error generated.
1 error generated.
make[2]: *** [scripts/extract-cert] Error 1
make[2]: *** Waiting for unfinished jobs....
/Volumes/Android/los17/kernel/sony/msm-4.14/kernel/scripts/mod/mk_elfconfig.c:5:10: fatal error: 'elf.h' file not found
#include <elf.h>
         ^~~~~~~
make[2]: *** [scripts/sortextable] Error 1
1 error generated.
  HOSTCC  scripts/dtc/dtc-parser.tab.o
make[3]: *** [scripts/mod/mk_elfconfig] Error 1
make[3]: *** Waiting for unfinished jobs....
  HOSTCC  scripts/dtc/dtc-lexer.lex.o
In file included from /Volumes/Android/los17/kernel/sony/msm-4.14/kernel/scripts/selinux/genheaders/genheaders.c:18:
In file included from /Volumes/Android/los17/kernel/sony/msm-4.14/kernel/security/selinux/include/classmap.h:2:
In file included from /Volumes/Android/los17/kernel/sony/msm-4.14/kernel/include/uapi/linux/capability.h:17:
/Volumes/Android/los17/kernel/sony/msm-4.14/kernel/include/uapi/linux/types.h:5:10: fatal error: 'asm/types.h' file not found
#include <asm/types.h>
         ^~~~~~~~~~~~~
1 error generated.
make[4]: *** [scripts/selinux/genheaders/genheaders] Error 1
make[3]: *** [scripts/selinux/genheaders] Error 2
make[3]: *** Waiting for unfinished jobs....
In file included from /Volumes/Android/los17/kernel/sony/msm-4.14/kernel/scripts/selinux/mdp/mdp.c:48:
In file included from /Volumes/Android/los17/kernel/sony/msm-4.14/kernel/security/selinux/include/classmap.h:2:
In file included from /Volumes/Android/los17/kernel/sony/msm-4.14/kernel/include/uapi/linux/capability.h:17:
/Volumes/Android/los17/kernel/sony/msm-4.14/kernel/include/uapi/linux/types.h:5:10: fatal error: 'asm/types.h' file not found
#include <asm/types.h>
         ^~~~~~~~~~~~~
1 error generated.
make[4]: *** [scripts/selinux/mdp/mdp] Error 1
make[3]: *** [scripts/selinux/mdp] Error 2
make[2]: *** [scripts/selinux] Error 2
make[2]: *** [scripts/mod] Error 2
  HOSTLD  scripts/dtc/dtc
  HOSTLD  scripts/genksyms/genksyms
make[1]: *** [scripts] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by jerpelea** [comment]
please check your local repo and environment 
I just compiled succesfully all devices
