### ISSUE TITLE
[Q][kumano][Griffin]Can't Boot the Phone

### ISSUE THREAD

**Issue by m1omoe** [sonyxperiadev/bug_tracker#477]
I built the latest source code but the system could not be booted.
Is this because the kernel work is not done yet?

**Comment by jerpelea** [comment]
if you built everything correctly you should be able to use adb shell and connect to the device. 
All devices are under bringup and functionality may vary.

**Comment by m1omoe** [comment]
> if you built everything correctly you should be able to use adb shell and connect to the device.
> All devices are under bringup and functionality may vary.

Thanks,I will use it and get the log.

**Comment by m1omoe** [comment]
[logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/3692941/logcat.txt)
This is my  log @jerpelea

**Comment by m1omoe** [comment]
Kernel LOG @jerpelea 
[dmesg.txt](https://github.com/sonyxperiadev/bug_tracker/files/3693031/dmesg.txt)

**Comment by YuriyMosiychuk** [comment]
The same problem on suzu. Build from 4.10.2019, software binaries v1c, kernel 4.14, phone stucks on Sony logo.

**Comment by MartinX3** [comment]
@YuriyMosiychuk please open a second bug tracker entry with your logs :)

**Comment by jerpelea** [comment]
the phone boots to shell and we are working on display. Thanks for the log

**Comment by m1omoe** [comment]
> the phone boots to shell and we are working on display. Thanks for the log
Is the source code updated?

**Comment by jerpelea** [comment]
Yes

**Comment by m1omoe** [comment]
> Yes

Thanks I will build it and test it

**Comment by m1omoe** [comment]
> Yes

When I was building kernel something gone wrong this is my log
[log.txt](https://github.com/sonyxperiadev/bug_tracker/files/3824191/log.txt)
