### ISSUE TITLE
The build does not work for h4493

### ISSUE THREAD

**Issue by khebbie** [sonyxperiadev/bug_tracker#479]
**Platform:** Loire
**Device:** voyager
**Kernel version:** 4.9
**Android version:** 9.0

when following this guide:
https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0-2

and running `source build/envsetup.sh && lunch` I do not get h4493 as an option.

I didn't take a backup before installing sailfish on this device, since I thought I could always install AOSP.
But since that is not working my only option is sailfish...

**Comment by MarijnS95** [comment]
[It looks like](https://github.com/search?q=h4493+org%3Amer-hybris&type=Code) Sailfish doesn't treat the H4493 any different than the H4413: https://github.com/mer-hybris/droid-config-sony-nile/blob/dd8e0fe18c89871d6dab82c6228baab5b44e89c9/kickstart/pack/h4113/hybris#L167-L170

You should be able to use H4413 repos just fine for this device. The only differences [as far as I can see](https://jolla-devices.com/sony-xperia-xa2-plus/) are memory size and LTE bands. The amount of available RAM should be automatically detected, and so should the LTE bands (or baked into the firmware that is put on the device from factory or stock OTA, as I don't remember seeing this specified anywhere in the OSS repos - but I could be wrong of course).

**Comment by khebbie** [comment]
It does not detect my sim card when i use a h4413 build.
It does detect when I eject the sim card holder.

**Comment by jerpelea** [comment]
this device is not officially supported
