### ISSUE TITLE
[Suzu]Unable to transfer files via Bluetooth

### ISSUE THREAD

**Issue by LLJY** [sonyxperiadev/bug_tracker#48]
Loire
Suzu
Kernel version: 4.4
Android Version: 8.0 r30

Unable to transfer files via Bluetooth
**How to reproduce**
1. Pair two devices 
2. Attempt to transfer a file to suzu via share
3. Bam
(Log coming soon)

**Comment by jerpelea** [comment]
I just transfered a picture from suzu to both kugo and lilac and I can not replicate the bug 
are you using AOSP ?
are you following the build guide?
do you have other patches?

**Comment by kholk** [comment]
Sent picture from Maple to Kugo.

Cannot replicate.
