### ISSUE TITLE
[Q] poplar stuck at sony logo and keeps rebooting

### ISSUE THREAD

**Issue by yuezhengbaizhi** [sonyxperiadev/bug_tracker#480]
**Platform:yoshino** 
**Device:poplar** 
**Kernel version:4.14** 
**Android version:10** 
**Software binaries version:SW_binaries_for_Xperia_Android_10.0.7.1_r1_v1c_yoshino** 

**Description**
build from the latest source and is stuck at the sony screen and then reboot, unable to connect via adb to get logs

**Symptoms**
Write the symptoms here.

**How to reproduce**
flash these img to poplar to reproduce the bug: https://1drv.ms/f/s!AjJ0jXrlCoD0htN0hhjitSBa5hlkgw

**Additional context**
Add any other context, e.g. upload logs or screenshots about the bug here.

**Comment by Haxk20** [comment]
Hi. 4.14 is not ready for real use. It is very experimental and as you can see some devices cant even boot using 4.14.

**Comment by yuezhengbaizhi** [comment]
Is there an est on when will the 4.14 be usable?

**Comment by MartinX3** [comment]
maybe OEMv3, maybe OEMv5, maybe later
but always a volunteer work has no ETA
(Or someone starts employee the volunteers here for doing this work)
