### ISSUE TITLE
[tama][akari][9.0][4.9] AOSP install leads to bootloop

### ISSUE THREAD

**Issue by rinigus** [sonyxperiadev/bug_tracker#483]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9.182-g17cdb0a8bbe1-dirty
**Android version:** 9.0_r46
**Software binaries version:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_tama.img

**Description**
I flashed AOSP as provided by @MartinX3 on https://forum.xda-developers.com/xperia-xz2/development/aosp-aosp-8-1-h8266-t3843269. This resulted in bootloops that ended with "This device cannot be trusted, shutting down in 5 sec". After that all I can do is to reflash the stock image using newflasher.

Fortunately, I managed to get logs `console-ramoops-0` via TWRP after the first boot into AOSP.

**Symptoms**
New XZ2 with the updates into the latest firmware, as in Estonia, available via OTA was applied before unlocking the bootloader.

fastboot getvar version-baseband:
version-baseband: 1311-7915_52.0.A.8.131

**How to reproduce**

1. flash latest stock H8216_Customized CE1_1316-0773_52.0.A.8.131_R1B via newflasher.x64
2. boot into stock
3. proceed with setup
4. shutdown device
5. boot into fastboot using Vol+ and inserting USB
6. `fastboot --set-active=a`
7. `fastboot reboot-bootloader` wait for reboot
8. `fastboot flash boot boot.img` (went to boot_a)
9. `fastboot flash dtbo dtbo.img`
10. `fastboot flash system system.img` (went to system_a)
11. `fastboot flash vendor vendor.img`
12. `fastboot flash oem SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_tama.img`
13. `fastboot flash userdata userdata.img`
14. `fastboot boot twrp-xz2.img`
15. Boots into TWRP. While in TWRP, `adb push twrp-xz2.img /sdcard/TWRP`
16. In TWRP, under "Advanced -> "Install recovery ramdisk" -> Select TWRP/twrp-xz2.img and flash it
17. Reboot back into TWRP
18. In TWRP, reboot into system
19. Get first boot to AOSP (Sony appears, then reboots).
20. As soon as it reboots, press Vol- and Power, get Sony logo and get to TWRP
21. In TWRP, get logs at `/sys/fs/pstore/`. Single file - console-ramoops-0

Log file is attached and I am at present in TWRP. Let me know if any extra info is needed.

**Additional context**

Log attached.
[console-ramoops-0.log](https://github.com/sonyxperiadev/bug_tracker/files/3703339/console-ramoops-0.log)

**Comment by MarijnS95** [comment]
Apparently @MartinX3 bundles a working vbmeta, which you should be able to flash _with_ verification enabled:
```sh
fastboot flash vbmeta vbmeta.img
```
Can you report whether that works?

**Comment by MartinX3** [comment]
Aaaaarrrrgh O missed the flash vbmeta stuff in my XDA instructions

Thank you both!

**Comment by rinigus** [comment]
Yes, flashing `fastboot flash vbmeta vbmeta.img` works as well. Should we close the issue?

**Comment by MartinX3** [comment]
Yes :)
