### ISSUE TITLE
[poplar]battey stuck at 20% after flashing aosp 10.0 with 4.9 kernel

### ISSUE THREAD

**Issue by yuezhengbaizhi** [sonyxperiadev/bug_tracker#485]
**Platform:** Yoshino
**Device:** poplar
**Kernel version:** 4.9
**Android version:** 10.0
**Software binaries version:** v9

**Description**
battery stuck at 20% after flashing the v0.35 version of this rom:
https://forum.xda-developers.com/xperia-xz1/development/android-10-0-project-treble-xperia-xz1-t3971379
**Symptoms**
flash the v0.35 to poplar and if lucky it will be reproduced

**How to reproduce**
Write how to reproduce here.

**Additional context**
here is a log from adb logcat:
[xz1_id_6.txt](https://github.com/sonyxperiadev/bug_tracker/files/3721959/xz1_id_6.txt)

**Comment by jerpelea** [comment]
this is not a supported combination
