### ISSUE TITLE
[TAMA][AKARI] Android Car not working & kernel panic

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#486]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 9.0
**Software binaries version:** OEMv9

**Description**
The phone isn't aware of the car.
I don't see a message in the car, I don't see a message in the phone.
As there is no connection and they are completely isolated.
And a completely phone crash on the first try.

**Symptoms**
No recognizing of the phone (Bluetooth, wifi, usb cable).
A kernel panic on the first try.

**How to reproduce**
Connect the phone with the car (bluetooth, wifi, usb cable).
Start the app "Android Car"

**Additional context**
Logcat & dmesg of the connection trying:
[dmesg_android_car.log](https://github.com/sonyxperiadev/bug_tracker/files/3738908/dmesg_android_car.log)
[logcat_android_car.log](https://github.com/sonyxperiadev/bug_tracker/files/3738909/logcat_android_car.log)

Kernel panic PSTORE:
[console-ramoops-0.log](https://github.com/sonyxperiadev/bug_tracker/files/3738905/console-ramoops-0.log)
[dmesg-ramoops-0.log](https://github.com/sonyxperiadev/bug_tracker/files/3738906/dmesg-ramoops-0.log)
[dmesg-ramoops-1.log](https://github.com/sonyxperiadev/bug_tracker/files/3738907/dmesg-ramoops-1.log)

PS: Even if we don't support GAPPS, shouldn't be at least the car/device be aware of a connection between them?

**Comment by ix5** [comment]
Is this still present on 4.14? Else this should be closed.
