### ISSUE TITLE
[Q][TAMA][AKARI] Failure to boot custom boot image

### ISSUE THREAD

**Issue by rinigus** [sonyxperiadev/bug_tracker#488]
**Platform:** Tama
**Device:** Akari
**Kernel version:**  LE.UM.2.3.2.r1.4 + Sailfish patches
**Android version:** 9.0_r46
**Software binaries version:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_tama.img

**Description**

As I don't know which forum to use to ask for help with Sailfish port, I am asking here as it looks to be XZ2 boot specific.

I have issue with booting my images. Namely, after showing the unlocked bootloader warning, device immediately shows "This device is corrupted ... Will shutdown in 5 seconds" message. 
By keeping all other images (system, userdata, ...) and flashing AOSP boot.img, I can get to SONY logo and then device reboots (as other images are not AOSP). I am sure that the issue is with Sailfish adaptation, but the problem is I don't know where.

Hence the question: which inconsistencies are checked that early in the boot process?

Additional info: This is also after disabling vbmeta (fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img) and generation of dtbo image corresponding to kernel.

Project repos are at https://github.com/sailfishos-sony-tama ; 

Kernel config modified as in https://github.com/sailfishos-sony-tama/android_kernel_sony_msm/commit/0371c0f4aad250d0cba822ac385051e75e016ca5 and https://github.com/sailfishos-sony-tama/android_kernel_sony_msm/commit/d1a9c2b99a4a0a02c437df8c2052e49693406e6f

Kernel difference: https://github.com/sonyxperiadev/kernel/compare/aosp/LE.UM.2.3.2.r1.4...sailfishos-sony-tama:hybris-sony-aosp-9.0.0_r37_20190620-tama

**Comment by jerpelea** [comment]
you must flash boot, dtbo and vbmeta images

**Comment by rinigus** [comment]
@jerpelea : thanks! That what I have done. I generated DTBO and VBMETA images as well as others (system, vendor, userdata). As I can get further with AOSP boot.img together with "wrong" DTBO & vbmeta, I suspect that there is something else stopping bootloader.

Is there any way to check what caused bootloader "corrupted" flag?

As extra info: To my knowledge, Sailfish uses system_b, even while booting from boot_a. Maybe its something that is causing this error. But I will have to confirm it.

Thanks a lot for your help! I know that the details are rather scetchy and I need to check out details to make it into proper report (not a bug of AOSP).

**Comment by jerpelea** [comment]
please upload the 3 files in a zip and I will check what happens

**Comment by rinigus** [comment]
Here is one of the sets that I used:

dtbo.img  hybris-boot.img  vbmeta.img

Out of these, hybris-boot.img corresponds to boot.img.

For vbmeta.img I used the one that was generated for clean AOSP build (no Sailfish patches). vbmeta was flashed using 

```
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
```

So, maybe that is a mistake and I should generate it for Sailfish boot image. Corresponding ZIP is attached.

[hybris-boot1.zip](https://github.com/sonyxperiadev/bug_tracker/files/3742572/hybris-boot1.zip)

**Comment by rinigus** [comment]
I am going to rebuild everything with the latest patches and let me get back to you with the update. I will also look into how to make vbmeta against used hybris-boot and dtbo. There was an issue with the build that prevented me to do so, but I don't remember what exactly as it was done at the end of the last week.

**Comment by rinigus** [comment]
Rather bizarre situation with NFS support triggering the issue. Namely, after disabling NFS support (https://github.com/sailfishos-sony-tama/android_kernel_sony_msm/commit/a588949dd127cc118c60c47e1e6f50e630f31c30), I can bypass corrupted image warning. In this case, `CONFIG_NFS_FS=n` would be sufficient. This is a state with Sailfish kernel config.

If I add full config to AOSP kernel, it will trigger the same behavior. By just adding NFS options to AOSP kernel, all seemed to be OK. I will have to test with AOSP to get better understanding on how I can reproduce with a clean image and minimal config intervention.

I am closing this as an issue and if I can find the way to reproduce it with AOSP build, I will open a corresponding bug report.
