### ISSUE TITLE
[tama][akari][9.0][4.9] Kernel with extended filesystem support leads to corrupted image

### ISSUE THREAD

**Issue by rinigus** [sonyxperiadev/bug_tracker#489]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.9.194-gf6b931bb01ed-dirty
**Android version:** AOSP 9 r46
**Software binaries version:** 

**Description**

Originally started as https://github.com/sonyxperiadev/bug_tracker/issues/488

There are a set of options that would lead to images which would be considered corrupted by bootloader.

**Symptoms**

Select options as shown below, build kernel and AOSP images, flash them, and you will be greeted with "This device is corrupted ... Will shutdown in 5 seconds" message.

**How to reproduce**

I hope that I haven't forgotten anything (related to the tree of AOSP sources)

Remove pre-built kernels and add the following to `kernel/sony/msm-4.9/kernel/arch/arm64/configs/aosp_tama_akari_defconfig`:

```
CONFIG_BTRFS_FS=y
CONFIG_BLK_DEV_NBD=y
CONFIG_XFS_FS=y
CONFIG_ISO9660_FS=y
CONFIG_F2FS_FS=y
CONFIG_NFS_FS=y
CONFIG_NFS_V3=y
CONFIG_NFS_V3_ACL=y
CONFIG_NFS_V4=y
CONFIG_NFS_V4_1=y
CONFIG_NFS_USE_KERNEL_DNS=y
CONFIG_LOCKD=y
CONFIG_LOCKD_V4=y
CONFIG_NFS_ACL_SUPPORT=y
CONFIG_NFS_COMMON=y
CONFIG_SUNRPC=y
CONFIG_SUNRPC_GSS=y
CONFIG_CIFS=y
```

Follow AOSP build instructions until `make`. Instead follow with

```
rm -rf kernel/sony/msm-4.9/common-kernel
make bootimage
mkdir -p kernel/sony/msm-4.9/common-kernel
make
```

Flash made images: boot.img  dtbo.img  system.img  userdata.img  vbmeta.img  vendor.img . For vbmeta, use 

```
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
```

Boot the phone and you will get "corrupted" message right after unlocked bootloader warning (before SONY logo)

**Comment by jerpelea** [comment]
how big is the resulting image ?

**Comment by rinigus** [comment]
boot.img file is 64MB. But that's after running `out/host/linux-x86/bin/avbtool` in the build. Before that, if I use 

```
out/host/linux-x86/bin/mkbootimg  --kernel out/target/product/akari/kernel  --ramdisk out/target/product/akari/ramdisk-recovery.img --cmdline "lpm_levels.sleep_disabled=1 androidboot.bootdevice=1d84000.ufshc swiotlb=2048 service_locator.enable=1 androidboot.selinux=permissive msm_rtb.filter=0x3F ehci-hcd.park=3 coherent_pool=8M sched_enable_power_aware=1 user_debug=31 cgroup.memory=nokmem printk.devkmsg=on kpti=0 androidboot.hardware=akari buildvariant=userdebug" --base 0x00000000 --pagesize 4096 --os_version 9 --os_patch_level 2019-08-01 --ramdisk_offset 0x02000000 --tags_offset 0x01E00000 --output  out/target/product/akari/boot.img
```

it will be 26MB. I flashed with boot.img as produced in the build - 64MB

**Comment by jerpelea** [comment]
did you flash boot and dtbo ?

**Comment by rinigus** [comment]
Yes, I did. If memory serves me right though - was a while ago. You cannot reproduce it?

**Comment by jerpelea** [comment]
@rinigus no I can not.
 I buils the kernels with build-kernels-gcc.sh and then I followed the build guide

**Comment by rinigus** [comment]
Thanks! I will look into it and see if I can reproduce on my device.
