### ISSUE TITLE
[maple] Device encryption is broken

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/bug_tracker#49]
**Platform:** yoshino
**Device:** maple
**Kernel version:** 4.4
**Android version:** 7.1

**Description**
Device encryption does not work. 

**Symptoms**
After "encrypt phone" is selected in the Settings app, you are warned that device encryption will wipe your data and take a long time to complete.  However, the phone is not wiped; system-server simply restarts (i.e. the device does not reboot) and when the ui comes back up your files are still there and the device is not encrypted.

**How to reproduce**
From Settings \ Security, select "Encrypt phone".

**Comment by jamuir** [comment]
`BOARD_USERDATAIMAGE_PARTITION_SIZE` is 32 bytes too large.

Here is the fix:
```
$ git -C device/sony/maple/ diff
diff --git a/BoardConfig.mk b/BoardConfig.mk
index 921be47..632e4a9 100644
--- a/BoardConfig.mk
+++ b/BoardConfig.mk
@@ -32,9 +32,8 @@ BOARD_KERNEL_CMDLINE += androidboot.hardware=maple
 BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
 BOARD_CACHEIMAGE_PARTITION_SIZE := 398458880
 BOARD_SYSTEMIMAGE_PARTITION_SIZE := 7707033600
-# Reserve space for data encryption (54587760640-16384)
-BOARD_USERDATAIMAGE_PARTITION_SIZE := 54587744256
-
+# Reserve space for data encryption (54587760640-16384-32)
+BOARD_USERDATAIMAGE_PARTITION_SIZE := 54587744224
 # For split frame buffer in recovery
 TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
 TARGET_RECOVERY_OVERLAY_ENABLE := true
```


We have a fix for this:

**Comment by jamuir** [comment]
logs:

```
01-03 03:27:29.210 E/Cryptfs (  551): Bad magic for real block device /dev/block/bootdevice/by-name/userdata
01-03 03:27:29.211 E/Cryptfs (  551): JM fs_size_sec = 106616720
01-03 03:27:29.211 E/Cryptfs (  551): JM max_fs_size_sec = 106616688
01-03 03:27:29.211 E/Cryptfs (  551): Orig filesystem overlaps crypto footer region.  Cannot encrypt in place.```

**Comment by jamuir** [comment]
PR:

https://github.com/sonyxperiadev/device-sony-maple/pull/28

**Comment by jerpelea** [comment]
1.flash the latest sony sw
2.conect device in fastboot mode (blue led)
3.fastboot getvar all 
4.check the data partition size

**Comment by jerpelea** [comment]
if needed we can reserve 32768 for the data partiton

**Comment by jamuir** [comment]
reserving 32768 (0x8000) would be more future-proof.

```bash
$ fastboot getvar all |& grep partition
(bootloader) partition-type:cache:ext4
(bootloader) partition-size:cache: 0x17C00000
(bootloader) partition-type:userdata:ext4
(bootloader) partition-size:userdata: 0xCB5AF2000
(bootloader) partition-type:system:ext4
(bootloader) partition-size:system: 0x1CB600000
$ python -c 'print 0xCB5AF2000;'
54587760640
```

`54587760640` matches the commented value in the maple `BoardConfig.mk`.

**Comment by jerpelea** [comment]
fixed
