### ISSUE TITLE
[ALL] Flashing Instructions miss mentions dtbo.img

### ISSUE THREAD

**Issue by Thaodan** [sonyxperiadev/bug_tracker#491]
**Android version:**  any
**Description**
The current flashing instructions doesn't mention to flash dtbo.img

**Comment by ix5** [comment]
Something like this this should be added to the [Android 10 build guide](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-10-0-0#tutorial-step-6):

> In case your device needs a `dtbo` image, use
```
fastboot flash dtbo <aosp-tree>/kernel/sony/msm-4.14/common-kernel/dtbo-<device>.img
```

> In case your device uses a `vbmeta` partition because it has AVB, use
```
fastboot flash --disable-verification --disable-verity vbmeta out/target/product/<device>/vbmeta.img
```

**Comment by Thaodan** [comment]
>Something like this this should be added to the Android 10 build guide:
>In case your device needs a dtbo image, use
>fastboot flash dtbo <aosp-tree>/kernel/sony/msm-4.14/common-kernel/dtbo-
<device>.img
I aggree except that its out/target/product/<device>/dtbo.img
The image need get an header from avbtool.

Also there should be better instruction when the dtbo and the vbmeta image 
should be flashed.
For my device my kernel curently  crashes and without dmesg this is really 
painfull to checks this new stuff.

**Comment by jerpelea** [comment]
the build guide is updated to reflect the layout for the new devices
