### ISSUE TITLE
[Yoshino][Lilac] Android-10 build fails with undefined symbol: stpcpy_a9

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#492]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9 and 4.14
**Android version:** android-10.0.0_r1

**Description**
When trying to build a clean just synced repo from scratch with some adjustments from my buildscripts, I get following error (pasted the output from build-4.14.sh, the same happens with build-4.9.sh):
```
[ 66% 72657/109596] //bionic/libc:libc link libc.so [arm]
FAILED: out/soong/.intermediates/bionic/libc/libc/android_arm_armv8-a_cortex-a73_core_shared_com.android.runtime.debug/unstripped/libc.so
prebuilts/clang/host/linux-x86/clang-r353983c/bin/clang++  @out/soong/.intermediates/bionic/libc/libc/android_arm_armv8-a_cortex-a73_core_shared_com.android.runtime.debug/unstripped/libc.so.rsp -Wl,--whole-archive  out/soong/.intermediates/external/jemalloc_new/libjemalloc5/android_arm_armv8-a_cortex-a73_core_static_com.android.runtime.debug/libjemalloc5.a out/soong/.intermediates/bionic/libc/libc_init_dynamic/android_arm_armv8-a_cortex-a73_core_static_com.android.runtime.debug/libc_init_dynamic.a out/soong/.intermediates/bionic/libc/libc_common_shared/android_arm_armv8-a_cortex-a73_core_static_com.android.runtime.debug/libc_common_shared.a -Wl,--no-whole-archive  out/soong/.intermediates/bionic/libdl/libdl_android/android_arm_armv8-a_cortex-a73_core_static_com.android.runtime.debug/libdl_android.a prebuilts/clang/host/linux-x86/clang-r353983c/lib64/clang/9.0.3/lib/linux/libclang_rt.builtins-arm-android.a prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/lib/libatomic.a out/soong/.intermediates/build/soong/libgcc_stripped/android_arm_armv8-a_cortex-a73_core_static_com.android.runtime.debug/libgcc_stripped.a out/soong/.intermediates/bionic/linker/ld-android/android_arm_armv8-a_cortex-a73_core_shared_com.android.runtime.debug/ld-android.so out/soong/.intermediates/bionic/libdl/libdl/android_arm_armv8-a_cortex-a73_core_shared_com.android.runtime.debug/libdl.so  -o out/soong/.intermediates/bionic/libc/libc/android_arm_armv8-a_cortex-a73_core_shared_com.android.runtime.debug/unstripped/libc.so -nostdlib -Wl,--gc-sections -shared -Wl,-soname,libc.so -target armv7a-linux-androideabi -Bprebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--build-id=md5 -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined-version -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_stripped.a -fuse-ld=lld -Wl,--pack-dyn-relocs=none -Wl,--no-undefined -Wl,--icf=safe -Wl,--hash-style=gnu -Wl,-m,armelf -Wl,-z,muldefs -Wl,--hash-style=both  -Wl,--version-script,out/soong/.intermediates/bionic/libc/libc.arm.map/gen/libc.arm.map -Wl,--symbol-ordering-file,bionic/libc/symbol_ordering
ld.lld: error: undefined symbol: strcpy_a9
>>> referenced by dynamic_function_dispatch.cpp:0 (bionic/libc/arch-arm/dynamic_function_dispatch.cpp:0)
>>>               dynamic_function_dispatch.o:(strcpy) in archive out/soong/.intermediates/bionic/libc/libc_common_shared/android_arm_armv8-a_cortex-a73_core_static_com.android.runtime.debug/libc_common_shared.a

ld.lld: error: undefined symbol: stpcpy_a9
>>> referenced by dynamic_function_dispatch.cpp:0 (bionic/libc/arch-arm/dynamic_function_dispatch.cpp:0)
>>>               dynamic_function_dispatch.o:(stpcpy) in archive out/soong/.intermediates/bionic/libc/libc_common_shared/android_arm_armv8-a_cortex-a73_core_static_com.android.runtime.debug/libc_common_shared.a
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
06:59:15 ninja failed with: exit status 1
```
Links to the build-scripts:
https://github.com/stefanhh0/aosp-10/blob/master/build-4.14.sh
https://github.com/stefanhh0/aosp-10/blob/master/build-4.9.sh

**Comment by jerpelea** [comment]
This looks like you have issues with your host machine.
What linux distro are you using?

**Comment by stefanhh0** [comment]
Understand, I am using Debian testing could very well be that something was updated in the distro that breaks the build. Any idea what that could be? I used Debian testing in the past always and it just worked fine. Also https://source.android.com/setup/build/initializing mentions Debian testing as a system on that android builds are tested.

**Comment by stefanhh0** [comment]
Which distro and version are you using to build aosp?

**Comment by stefanhh0** [comment]
repeated the commands:
`sudo apt-get install git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip` from https://source.android.com/setup/build/initializing
and 
`sudo apt-get install bison g++-multilib git gperf libxml2-utils make zlib1g-dev:i386 zip liblz4-tool libncurses5 libssl-dev bc flex` from https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-10-0-0#tutorial-step-2

Some debs where indeed missing. Building afterwards did not fix the problem.

Now just cleared the ccache (`ccache -C`). Rerunning a clean build to see if that helps (will take some time).

**Comment by stefanhh0** [comment]
Doing a clean build with cleared ccache didn't help. Same error as before.

**Comment by MarijnS95** [comment]
First up, I don't think this is an issue with your host. Pretty much everything crosscompiled for the device is in the AOSP tree - in this case `strcpy` and friends [are provided by bionic](https://android.googlesource.com/platform/bionic/+/refs/tags/android-10.0.0_r14/libc/arch-arm/cortex-a9/bionic/string_copy.S); androids libc.

Can you check the status of that repository (checked out at the right branch, no modifications)? The compiler `prebuilts/clang/host/linux-x86/clang-r353983c` should be fine, I think.

Just for confirmation, you compiled Android 10 (r1) correctly before, right? Nothing changed when it comes to architecture configuration, and Bionic compiles [all cortex variants in anyway](https://android.googlesource.com/platform/bionic/+/refs/tags/android-10.0.0_r14/libc/Android.bp#790).

**Comment by chris42** [comment]
I just compiled on Xenial for Kugo/Loire and it worked fine. Can give you my docker file if you want to.

**Comment by stefanhh0** [comment]
@MarijnS95 The links you have provided show something with cortex-a9 however in the error message there is cortex-a73 mentioned. Just seeing the difference....

I've built android 10.r1last time successfully on 29.10.2019 together with kernel 4.9 and it runs just fine on my phone. 

The bionic repo seems to be in sync:
```
stefan@mars:~/android/source/bionic$ git status
HEAD detached at 290c0cb50
nothing to commit, working tree clean
stefan@mars:~/android/source/bionic$ git log
commit 290c0cb5044b643e5d6cbcb1a5b275541ca3a89e (HEAD, tag: android-vts-10.0_r1, tag: android-cts-10.0_r1, tag: android-10.0.0_r6, tag: android-10.0.0_r5, tag: android-10.0.0_r4, tag: android-10.0.0_r3, tag: android-10.0.0_r2, tag: android-10.0.0_r11, tag: android-10.0.0_r10, tag: android-10.0.0_r1, tag: m/android-10.0.0_r1, aosp/android10-security-release, aosp/android10-s2-release, aosp/android10-s1-release, aosp/android10-release, aosp/android10-gsi)
Merge: 0c8310d45 5cda74e06
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Wed Jul 10 03:42:37 2019 +0000

    Snap for 5716396 from 5cda74e065761bbeccf7ff61d7a3131bdf6490d0 to qt-release
    
    Change-Id: I330f95e46b252c10acb047f929a3e85cbdb7f32c
[...]
```

**Comment by stefanhh0** [comment]
```
nm -D  out/soong/.intermediates/bionic/libc/libc_common_shared/android_arm_armv8-a_cortex-a73_core_static_com.android.runtime.debug/libc_common_shared.a >/tmp/nm_D.txt 2>&1
```

[nm_D.txt](https://github.com/sonyxperiadev/bug_tracker/files/3825753/nm_D.txt)

**Comment by stefanhh0** [comment]
```
stefan@mars:~/android/source$ nm out/soong/.intermediates/bionic/libc/libc_common_shared/android_arm_armv8-a_cortex-a73_core_static_com.android.runtime.debug/libc_common_shared.a|grep stpcpy
stpcpy.o:
00000000 T stpcpy_generic
stpcpy.o:
00000000 T stpcpy_a15
stpcpy.o:
00000000 T stpcpy_a15
         U stpcpy
00000000 T __stpcpy_chk
00000000 i stpcpy
         U stpcpy_a15
         U stpcpy_a9
00000000 T stpcpy_resolver

```

**Comment by MarijnS95** [comment]
> The links you have provided show something with cortex-a9 however in the error message there is cortex-a73 mentioned. Just seeing the difference....

That is correct. As you can see from the linked source files, all implementations are compiled in. I haven't followed the rest of the codepath, perhaps the code is later optimized out again.

It is curious that the symbols are not defined in this static library. They should have been included from another static library, but it looks like something went wrong with linking. I'll try to confirm here whether this is the case, or whether the command in the  bug report is missing another static library that should have been recursively included and linked against.

You mentioned doing a clean build... Just `make clean`? I don't remember exactly if that only clears out the currently lunched target, or everything in the `out` folder. If not, you might try removing this `.intermediates` directory and try building libc again.

**Comment by stefanhh0** [comment]
Yes, I do a `make clean` it removes everything in the `out` directory, there is just a build_metrics file that is being created by the `make clean` command:
```
stefan@mars:~/android/source$ make clean
00:05:47 Entire build directory removed.

#### build completed successfully (8 seconds) ####

stefan@mars:~/android/source$ ls -la out
total 4
drwxr-xr-x 1 stefan stefan  26 Nov  9 00:05 .
drwxr-xr-x 1 stefan stefan 506 Sep 17 00:57 ..
-rwxr-xr-x 1 stefan stefan   6 Nov  9 00:05 build_metrics
```

**Comment by stefanhh0** [comment]
https://tracker.debian.org/pkg/ccache

The ccache package 3.7.5-1 was migrated 2019-10-29 to testing. My last successful build was from that day. Maybe there is problem with the ccache version. I have just disabled ccache for now to see if that helps. Currently doing a clean rebuild.

**Comment by stefanhh0** [comment]
Without ccache the build was successful. As a side note I have checked libc_common_shared.a again with nm -D and nm it looks basically the same as before.

I am closing this bug. And will open a bug in debian for ccache 3.7.5-1. I may going to try an earlier version from ccache, since now building takes more than 5h.

**Comment by stefanhh0** [comment]
Thanks for your Help again!

**Comment by stefanhh0** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944399

**Comment by stefanhh0** [comment]
ccache version 3.7.6 fixes the bug as expected, I have just verified it.
