### ISSUE TITLE
NILE-PIONEER AOSP9 CAMERA DON'T WORK

### ISSUE THREAD

**Issue by Ray-Alfy** [sonyxperiadev/bug_tracker#493]
Platform: **Nile**
Device: **Pioneer**
Kernel version: **4.9.194**
Android version: 9-**PQ3A.190801.02**
Software binaries version: **SW_BINARIES_FOR_XPERIA_ANDROID_9.0_2.3.2_V9_NILE**
Gapps: non
Root: non

Description: Same as Tone quote from the Sony Open Devices forum:
"**The Camera works after the reboot one time perfectly, if you close the camera app and restart it, everything does have a green tint. If you try it a third time, it just doesnt come up at all. So the camera works only one single time after the reboot and thats it :/**"

Symptoms: **Camera is going to green & can't  take a picture or save video**

How to reproduce: **Take a one picture (CAMERA WORKS FINE) and switch camera mode(photo to -> video) or switch camera (front to -> selfie)**

Additional context:
camera screenshot - https://photos.app.goo.gl/r3VonWepaaddioqg6
log - https://drive.google.com/file/d/1rdqN41N_BDwhxWqKn-B16B0PAeit3cWa/view
same problem on Tone - https://talk.sonymobile.com/t5/Android-9-x-Pie/Software-binaries-for-AOSP-Pie-Android-9-0-Tone-don-t-work/m-p/1382328#M252
my message in forum - https://talk.sonymobile.com/t5/Android-9-x-Pie/NILE-PIONEER-AOSP9-H4113-Camera/m-p/1394265#M274
sorry for bad english i used google translate.

**Comment by MarijnS95** [comment]
https://github.com/sonyxperiadev/bug_tracker/issues/469

**Comment by Ray-Alfy** [comment]
Yes. It's work. Thanks a lot =) 
The request can be closed.
