### ISSUE TITLE
[Loire] [Kugo] Android 10 build not booting, adb connection not possible

### ISSUE THREAD

**Issue by chris42** [sonyxperiadev/bug_tracker#494]
**Platform:** Loire
**Device:** Kugo
**Kernel version:** 4.14
**Android version:** 10
**Software binaries version:** v1

**Description**
Just build Android 10 for Kugo and flashed (boot, recovery, system, userdata, oem) to a test device. However device is stuck at the Sony logo and connection via adb is not possible (no device found).
Wanted to get you some logs.

Any way to get this forward?

**Comment by stefanhh0** [comment]
Hey @chris42, @jerpelea mentioned that 4.14 is not yet ready and bugs should not yet opened for 4.14. So I guess this issue should just be closed.

4.14 should be build and useable as soon as the Android 10 V2 software binaries and the first bunch of 4.14 prebuilt kernels are available.

I have running Android 10 together with kernel 4.9 and the 4.9 software binaries. I am maintaining a script that builds it together with opengapps, have a look here: https://github.com/stefanhh0/aosp-10. @MarijnS95 helped me to get that script running. However it is a configuration that is not supported by the sony devs. At least for me it works pretty good although not officially supported.

**Comment by chris42** [comment]
Yes, I understood that. 
The 4.9 Kernel was quite bad on kugo. My device is running with it in android 9 and I have crashes, broken wifi, etc. (Issues are in the bugtracker).
So I hope to help to get 4.14 up and running to move forward. As I understand that not many people are interested in the device, I can at least support with logs and testing.

**Comment by chris42** [comment]
So tried it with the new v2c, no change: device is stuck at Sony logo and no access to adb.
Am I missing something, should this work?

**Comment by rogora** [comment]
I have the same behavior with my f5321, software binaries v3a. 
version-baseband: 1302-7793_34.4.A.2.118, which is the newest released by Sony.

**Comment by chris42** [comment]
What I learned: Until there is a precompiled kernel, it won't work. Hence we need to wait.

**Comment by chris42** [comment]
Just saw in the kernel folder, that loire was removed from the build script and marked as legacy platform. Does that mean there will be no further updates for Android 10 for loire?

**Comment by jerpelea** [comment]
loire can use the legacy manifest to build Android 10 with kernel 4.9 and reuse the Android 9 vendor release

**Comment by chris42** [comment]
Ok, so basically the build @stefanhh0 and @MarijnS95 created? Will this be supported by Sony?
Sorry for asking all this questions, but I still have issues with the 4.9 which makes the device pretty much unusable as a daily driver. Last version fully working is 8.1.

**Comment by jerpelea** [comment]
@chris42 what issues do you have with 9.0?

**Comment by chris42** [comment]
#419 and #433. So far I could only verify #419 in the 10/4.9 build. To verify #433, I would need to put that firmware on my daily driver, as the crashes occurred back then only every few days. However with wifi dropping out in every idle, this is not very practical.
I also suspect a problem with bluetooth and pairing (as it was not working last time I tried in 9.0/4.9), however also need to look into this with decent logging.

**Comment by chris42** [comment]
Closing this in favour of #536
As Loire moved to legacy, it is probably better to streamline the infos and progress into one issue.
Also it means, that there will be no Kernel 4.14 version for Kugo/Loire
