### ISSUE TITLE
Nile-Pioneer AOSP9 Gapps bootloop

### ISSUE THREAD

**Issue by Ray-Alfy** [sonyxperiadev/bug_tracker#495]
**Platform: Nile** 
**Device: Pioneer** 
**Kernel version: 4.9.194** 
**Android version: 9-PQ3A.190801.02** 
**Software binaries version: SW_BINARIES_FOR_XPERIA_ANDROID_9.0_2.3.2_V9_NILE** 

**Description**
After installing GApps(any package) phone is stucking on(SONY!!! White-black) logo (non- bootanimation) and LED flashing red. System is not booting because it stucked on little-kernel and it reboot again and again. But if include GApps in build system boots up(in manifest for building). I dont know how to get log in this case. MICROG is works(prefectly) and I think that some GService may crash system
**Symptoms**
Android dosn't start after install any package of OpenGapps >.<
**How to reproduce**
Just install OpenGapps zip-packege from TWRP
**Additional context**
just try it

**Comment by MarijnS95** [comment]
It sounds like you have verity enabled. Installing OpenGApps through TWRP changes the system image, resulting in a wrong match with the verity signature.

I don't remember exactly if `adb disable-verity` was broken on Nile, or whether it was _just_ building an image without verity altogether. I suggest trying that first (boot to android, `adb root && adb disable-verity`, then install GApps). If that doesn't work I can look up and reference a commit that disables verity checking altogether in the kernel.

**Comment by jerpelea** [comment]
gapps are not part of the oss

**Comment by Ray-Alfy** [comment]
> It sounds like you have verity enabled. Installing OpenGApps through TWRP changes the system image, resulting in a wrong match with the verity signature.
> 
> I don't remember exactly if `adb disable-verity` was broken on Nile, or whether it was _just_ building an image without verity altogether. I suggest trying that first (boot to android, `adb root && adb disable-verity`, then install GApps). If that doesn't work I can look up and reference a commit that disables verity checking altogether in the kernel.

D:\_Flash-tools\Platform-tools>adb root && adb disable-verity
**verity cannot be disabled/enabled - USER build**

**Comment by MarijnS95** [comment]
> verity cannot be disabled/enabled - USER build

Either build `userdebug`, or apply https://github.com/MarijnS95/kernel/commit/9d863606bc6ebf2a33e75ae590f4c2327839035c.

**Comment by Ray-Alfy** [comment]
> Either build `userdebug`, or apply [MarijnS95/kernel@9d86360](https://github.com/MarijnS95/kernel/commit/9d863606bc6ebf2a33e75ae590f4c2327839035c).

Yes it works! Thanks so much for your help ^.^
