### ISSUE TITLE
[Yoshino][Lilac] Android-10 with Kernel 4.14 fails to boot to system

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#499]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14
**Android version:** android-10.0.0_r10
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v2a_yoshino.img
**Version baseband:** 1307-7511_47.2.A.11.228

**Description**
On a clean source tree building plain aosp/sodp works fine (without gapps or any other changes made to the source tree). However after flashing the phone is not booting to the system. It hangs in a reboot loop and does not get past the black Sony logo on white background screen. Reboot occurs before adb is able to connect, so unfortunately no logs available.

Is it expected to be bootable at the current stage of development? Or am I just too early?

Well compiled it using ccache. In case it should just work I will give it a try without ccache.

Played around with different basebands, any changes in what is working together with 4.14 and the v2a binaries, compared to android 9? Is it still the Android 8 baseband: 47.1.A.16.20 that should be used?

I have seen in emma that there is also a 47.2.A.10.107 available. Or would the most recently available one (47.2.A.11.228) also be okay?

**Comment by stefanhh0** [comment]
Building latest aosp/sodp source tree using android-10.0.0_r10 with kernel 4.9 + several adjustments in the source tree (https://github.com/stefanhh0/aosp-10/blob/master/build-4.9.sh) works. The system then boots successfully into system.

**Comment by MarijnS95** [comment]
@stefanhh0 Last I heard Yoshino is not fully ready for 4.14. We're working through the platforms now, tackling issues that should apply to all of them.

**Comment by stefanhh0** [comment]
Good to know, thanks for the update and wish you a good hand fixing the remaining issues preventing the boot.

**Comment by stefanhh0** [comment]
This one basically duplicates #508 resp. #512, closing this one.
