### ISSUE TITLE
[Griffin][kumano][Android10] Can't boot phone

### ISSUE THREAD

**Issue by m1omoe** [sonyxperiadev/bug_tracker#501]
I saw the startup screen but I can't enter the desktop.
This is my log 
[log.txt](https://github.com/sonyxperiadev/bug_tracker/files/3922712/log.txt)

**Comment by jerpelea** [comment]
please sync and build again 
The devices boots fine now

**Comment by chris42** [comment]
> The devices boots fine now

Like all, or this one? Still not getting Kugo to boot

**Comment by stefanhh0** [comment]
They are still working on kugo, it should be useable when a prebuilt kernel for it is available in: https://github.com/sonyxperiadev/kernel-sony-msm-4.14-common

**Comment by chris42** [comment]
Ah, ok thanks! That was the piece of info missing. Will then wait and see
