### ISSUE TITLE
Errors during build

### ISSUE THREAD

**Issue by andrwgldmn** [sonyxperiadev/bug_tracker#507]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14
**Android version:** 10.0.0_r17

**Description**
After repo sync && repo_update I have such errors. Provided in Additional context

**How to reproduce**
repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r17 && cd .repo && git clone https://github.com/sonyxperiadev/local_manifests && cd local_manifests && git checkout master && cd ../.. && repo sync -j12 && ./repo_update.sh
source build/envsetup.sh && lunch (enter 31)
make otapackage -j12

**Additional context**
`vendor/qcom/opensource/location/gnsspps/Android.mk: error: "libgnsspps (SHARED_LIBRARIES android-arm64) missing libgps.utils (SHARED_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/gnsspps/Android.mk: error: "libgnsspps (SHARED_LIBRARIES android-arm) missing libgps.utils (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/ds_api/Android.mk: error: "libloc_ds_api (SHARED_LIBRARIES android-arm64) missing libgps.utils (SHARED_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/ds_api/Android.mk: error: "libloc_ds_api (SHARED_LIBRARIES android-arm) missing libgps.utils (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/loc_api_v02/Android.mk: error: "libloc_api_v02 (SHARED_LIBRARIES android-arm64) missing libloc_core (SHARED_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/loc_api_v02/Android.mk: error: "libloc_api_v02 (SHARED_LIBRARIES android-arm64) missing libgps.utils (SHARED_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/loc_api_v02/Android.mk: error: "libloc_api_v02 (SHARED_LIBRARIES android-arm) missing libloc_core (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/loc_api_v02/Android.mk: error: "libloc_api_v02 (SHARED_LIBRARIES android-arm) missing libgps.utils (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:1006: error: exiting from previous errors.`

**Comment by stefanhh0** [comment]
You have to use: android-10.0.0_r15, android-10.0.0_r17 is not compatible with sodp.

Please be aware that Android 10 with Kernel-4.14 is not yet ready and won't boot successfully. See as well #499. Officially working and supported is only Android 9 with Kernel 4.9.

@jerpelea https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-10-0-0#tutorial-step-4 has not yet been updated accordingly.

**Comment by MarijnS95** [comment]
In fact, if you look at the [build numbers](https://source.android.com/setup/start/build-numbers#source-code-tags-and-builds), android-10.0.0_r17 is actually a one-off release for the OG Pixel, with a security patch level dating **two months ago**.
@andrwgldmn Any reason for not choosing r10 as indicated by the guide, or r15 in case you [noticed this branch pop up](https://github.com/sonyxperiadev/local_manifests/tree/android-10.0.0_r15) by accident?

**Comment by andrwgldmn** [comment]
@stefanhh0 @MarijnS95 thx for answers. I didn't look into local_manifest and downloaded the latest revision of 10, my bad :)

**Comment by MarijnS95** [comment]
@andrwgldmn yeah unfortunately tags are never really incremental. And the one for Pixel 4 is still absent... :no_mouth:

**Comment by jerpelea** [comment]
the build guide will be updated asap to use r15
