### ISSUE TITLE
[tone] [kagura] No in-call audio when connected to bluetooth headset (take two)

### ISSUE THREAD

**Issue by samoylenko** [sonyxperiadev/bug_tracker#509]
**Platform:** tone 
**Device:** kagura
**Kernel version:** 4.9 (built using gcc via script located in `kernel/sony/msm-4.9/common-kernel/`)
**Android version:** `9.0.0_r46` and `10.0.0_r15`
**Software binaries version:** `SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_tone.img`

**Description**
No sound during call when using bluetooth headset, both outdoing and incoming. Sounds generated by phone such as dial tones, media and music are all good, tray icon indicates in-call sounds - just can't hear or produce any.
Looks like continuation of https://github.com/sonyxperiadev/bug_tracker/issues/263
Affects both latest AOSP 9 and AOSP 10 (with kernel 4.9)

**How to reproduce**
Connect a bluetooth headset and dial any number (I used voicemail for testing since it conveniently pop ups dialpad for pin entry to indicate good connection). There will be no sound. Hangup and disconnect blluetooth headset, dial number again: sound is back (on AOSP9, reboot may be required to get sound back)

**Additional context**
Issue presents both at AOSP 9 (`android-9.0.0_r46`) and AOSP 10 (`android-10.0.0._r15` with 4.9 kernel built using @stefanhh0 script)

Attaching logcats from both aosp 9 and aosp 10, starting numbers is when I started to make calls: first call with no headset connected, followed with connecting a bluetooth headset (already paired) and making a call. Then disabling headset right during that call, hanging up and calling again without headset. I am still working on those logs, so attaching them in full.

`dmesg` content (would need instructions how to pull it if you need more):
```
[ 2794.043780] IRQ352: set affinity failed(-22).
[ 2794.044086] IRQ523: set affinity failed(-22).
[ 2794.046417] CPU2: update max cpu_capacity 667
[ 2794.047668] CPU0: update max cpu_capacity 851
[ 2794.157759] CPU2: update max cpu_capacity 667
[ 2794.158740] CPU0: update max cpu_capacity 851
[ 2795.848713] send_afe_cal_type cal_block not found!!
[ 2795.848821] afe_get_cal_hw_delay: invalid num entries: -226048056
[ 2795.897026] afe_get_cal_hw_delay: invalid num entries: -226048056
[ 2795.906105] qdsp_cvp_callback: cmd = 0x13199 returned error = 0x2
[ 2795.906218] voice_send_cvp_device_channels_cmd: DSP returned error[ADSP_EBADPARAM]
[ 2795.906320] voice_send_cvp_media_fmt_info_cmd: Set channel info failed err: -22
[ 2795.906416] voice_setup_vocproc: Set media format info failed err:-22
[ 2795.906470] setup voice failed
[ 2796.327219] afe_open: port_id 0x100a rate 8000
[ 2796.334178] afe_open: port_id 0x100b rate 8000
[ 2797.072471] init: processing action (sys.sysctl.tcp_def_init_rwnd=*) from (/init.rc:811)
[ 2800.045015] IRQ352: set affinity failed(-22).
[ 2800.045235] IRQ523: set affinity failed(-22).
[ 2800.048214] CPU3: update max cpu_capacity 667
[ 2800.049785] CPU1: update max cpu_capacity 851
```
Unfortunately this issue is the one that prevents me from using AOSP entirely.

**Comment by samoylenko** [comment]
**Log files**:  
[1629-aosp10-kernel49.txt](https://blog.samoylenko.me/wp-content/uploads/2019/12/1629-aosp10-kernel49.txt)  
[1603-aosp9-kernel49.txt](https://blog.samoylenko.me/wp-content/uploads/2019/12/1603-aosp9-kernel49.txt)

**Comment by ix5** [comment]
Can you try disabling the `SND_DEVICE_OUT_BT_SCO` channel [like we did here](https://github.com/sonyxperiadev/device-sony-tone/pull/163/files) with `SND_DEVICE_OUT_BT_SCO_WB` ?

**Comment by MarijnS95** [comment]
This looks very much like the issue linked, but I noticed one difference: In the logcat there are errors about `bt-sco-headset`, instead of `bt-sco-headset-wb` which would match what's in https://github.com/sonyxperiadev/device-sony-tone/pull/163/files.

Would you mind adding the non-WB variant to the same file and try again?
```xml
 <device name="SND_DEVICE_OUT_BT_SCO" acdb_id="-1"/>
```

**Comment by samoylenko** [comment]
Thank you both. Meanwhile I tried with OEM binaries v6 and it didn't help. I'll also try versions 7 and 8 with both AOSP 9 and AOSP 10. 

Do I assume correctly that I am trying all the instructions with AOSP 9?

> Can you try disabling the acdb data `SND_DEVICE_OUT_BT_SCO` channel [like we did here](https://github.com/sonyxperiadev/device-sony-tone/pull/163/files) with `SND_DEVICE_OUT_BT_SCO_WB` ?

This one is already in there. My bad I didn't mention that I checked the changes related to the previous time this issue was investigated, and only stopped on @ix5 advanced debugging article. Now I have lots of help from @MarijnS95 , so will be happy to try it all

> Would you mind adding the non-WB variant to the same file and try again?
> ```
>  <device name="SND_DEVICE_OUT_BT_SCO" acdb_id="-1"/>
> ```

Trying this one now...

**Comment by MarijnS95** [comment]
> Do I assume correctly that I am trying all the instructions with AOSP 9?

Shouldn't matter, this problem is in the hardware/device repositories and those are the same whether you build on 9 or 10. As long as you stick to one version for stability and consistency, either is fine.

> > Can you try disabling the acdb data `SND_DEVICE_OUT_BT_SCO` channel [like we did here](https://github.com/sonyxperiadev/device-sony-tone/pull/163/files) with `SND_DEVICE_OUT_BT_SCO_WB` ?
> 
> This one is already in there. My bad I didn't mention that I checked the changes related to the previous time this issue was investigated

Hence why we both asked to _add_ the _non_`_WB` variant, since it's taking a different route now. I checked again, and `SND_DEVICE_OUT_BT_SCO` is not there yet.

> **upd:** Didn't seem to work. I've verified, and the line is in there (in addition to the '_WB' one). Don't have new logs to share yet - still building the kernel with your patch @MarijnS95

I would love to see the log. The issue with acdb id `88` should be solved, now I expect only `89` to remain. After collecting logs, would you adding the following **too**?
```xml
<device name="SND_DEVICE_IN_VOICE_DMIC_TMUS" acdb_id="-1"/>
```

> Don't have new logs to share yet

Logs should be really easy to get, and you should make sure a log capture (piping the output to a file) is running every time you try something.

> I am still working on those logs

Referring back to what you wrote in the the issue, what's there to work on? In case you're afraid there's personal information and check it all line by line, we can give a grep command that filters out most of what we need. While not nearly as complete, I think we can work with that in this case.
Since this is related to bluetooth, acdb and audio, pipe it through `grep -ie acdb -e audio -e bt -e bluetooth -e msm8974`. That's pretty much what I do here to not have to look through almost 24000 lines of log :wink:

**Comment by samoylenko** [comment]
Thank you so much for helping me all the time @MarijnS95,
Some broken English on my side when I said I am working on logs. Just tried to find something useful and paste it like @ix5 did in his original issue instead of posting the entire raw log, but I definitely lack skill there.

The story so far: thanks to @MarijnS95 who sent me patch, we tested that the temp solution from @ix5 [post](https://sx.ix5.org/info/post/bluetooth-audio-debugging/) works: hardcoding `tx_num_channels` to `1` solves the issue.

My bad is that I started with applying the above mentioned patch first, so now sure how useful the logs I am attaching here. But I am already rebuilding it without the patch and preparing to collect logs again.

**Comment by samoylenko** [comment]
Sharing logs that I collected with `hardcoded tx_num_channels=1` in place. Not sure if they are useful at all. Sound did present of course. Sorry for raw logs again, it will take me a couple hours to process those into something useful (which I am still planning to do - just sharing what I have so far)

[patch and SND_DEVICE_OUT_BT_SCO line added](https://blog.samoylenko.me/wp-content/uploads/2019/12/test11-patchandnowb.txt)
[patch and all lines from above comments present](https://blog.samoylenko.me/wp-content/uploads/2019/12/test222-allscowithpatch.txt)
[just the patch](https://blog.samoylenko.me/wp-content/uploads/2019/12/test101-justpatch.txt)

**Comment by samoylenko** [comment]
Sorry for the delay - had to start from scratch and recheck my steps to ensure I am giving you the right information. Because it looks like @MarijnS95 was right in his first comment, and adding a non-WB version `<device name="SND_DEVICE_OUT_BT_SCO" acdb_id="-1"/>` works too. Without hardcoding `tx_num_channels=1`. I can't explain why it didn't work the first time, hence rebuilt everything from scratch again and tested again double-checking every step.

Logs:

1. Sound works: only added `<device name="SND_DEVICE_OUT_BT_SCO" acdb_id="-1"/>` and nothing else (**no** patch of `q6voice.c`)

[logcat](https://blog.samoylenko.me/wp-content/uploads/2019/12/lc-nosco.txt)  [dmesg](https://blog.samoylenko.me/wp-content/uploads/2019/12/dmesg-nosco.txt)

2. Sound works: both `<device name="SND_DEVICE_OUT_BT_SCO" acdb_id="-1"/>` and ` <device name="SND_DEVICE_IN_VOICE_DMIC_TMUS" acdb_id="-1"/>` added (**no** patch of `q6voice.c`)

[logcat](https://blog.samoylenko.me/wp-content/uploads/2019/12/lc-allthree.txt)  [dmesg](https://blog.samoylenko.me/wp-content/uploads/2019/12/dmesg-allthree.txt)

3. Just in case. The original condition when no  changes made and sound doesn't work:

[logcat](https://blog.samoylenko.me/wp-content/uploads/2019/12/logcat.txt)  [dmesg](https://blog.samoylenko.me/wp-content/uploads/2019/12/dmesg.txt)

**Comment by MarijnS95** [comment]
That's very good info. This basically means the acdb calibration for `bt-sco-headset` is borked (id 22). @richardtullberg is there anything you can do with that info? And @ix5, can you confirm on your Tone whether it takes the `-wb` path all the time? I presume this is headset-specific, wb means "wideband"  and that being a higher-quality audio stream (seeing samplerate ctl being the only addition to the non-`-wb` paths), but in reality I have no idea.

And the mention about the `SND_DEVICE_IN_VOICE_DMIC_TMUS` was bogus. These (resolved to the audiopath `dmic-endfire`) are the microphones (dmic stands for Digital Microphone, but the mixer_paths comment makes it look like "Dual MIC"...) which are located on the device. Looking at the old logs again it was switching back and forth between `bt-sco-{headset,mic}` and `voice-{handset,dmic-ef}-tmus`. The latter one must be regular calling through the earpiece after checking the paths, but then I have no idea what TMUS stands for (even though both paths resolve to regular handset calling, no extra ctls set).
But that said, would you mind confirming whether calling, both in handset mode as well as on the speaker still works?

**Comment by samoylenko** [comment]
Yes I confirm all calling modes work well: bluetooth, speaker, standard, with switching between them in any order during the call. Sound works in both directions.

Thank you

**Comment by samoylenko** [comment]
PS.

> I presume this depends on headphones/device/carrier/phone-signal: wb means "wideband" and that being a higher-quality audio stream (seeing samplerate ctl being the only addition to the non-`-wb` paths), but in reality I have no idea.

Just tested it with all my bluetooth devices. Indeed, found one that got `bt-sco-headset-wb` instead of just `bt-sco-headset`. That one is a fancy one, unlike the rest of my devices, so I guess it confirms your theory :) To be precise, that was `Plantronics M165 Marque 2` (wb) vs `OontZ Angle 3`, and `Mpow H7`-like devices

**Comment by samoylenko** [comment]
Thank you all for your help, closing this issue since https://github.com/sonyxperiadev/device-sony-tone/pull/189 has been merged
