### ISSUE TITLE
[kirin] White screen of death probably caused by "system_server" crash

### ISSUE THREAD

**Issue by AngryGami** [sonyxperiadev/bug_tracker#510]
**Platform:**
Ganges
**Device:** 
Kirin (hp4113)
**Kernel version:** 
4.9.149-gf6b...
**Android version:** 
9 (Pie)
**Software binaries version:** 
???

**Description**
Phone randomly (for unknown reason) stuck showing white screen and only reacts to reboot. Sometimes it starts heating, but not always. This is NOT singular appearance of this problem. It happens pretty often in production environment where almost all phones show this behavior from time to time.

**How to reproduce**
Unknown - nothing specific seems to be causing that.

**Additional context**
[logs.zip](https://github.com/sonyxperiadev/bug_tracker/files/3973705/logs.zip)
Attachment contains all logs that we managed to collect from crashed Xperia 10 device. Particularly interesting places are these (logcat.txt):

```
…
12-12 14:16:53.670  1218  1623 I UsbPortManager: ClientCallback: otg_default
12-12 14:16:59.658   746   817 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
12-12 14:17:01.038  1218  1438 I chatty  : uid=1000 system_server expire 28 lines
12-12 14:17:01.076   730   730 I adbd    : type=1400 audit(0.0:10443): avc: denied { connectto } for path=00776562766965775F646576746F6F6C735F72656D6F74655F33343731 scontext=u:r:adbd:s0 tcontext=u:r:zygote:s0 tclass=unix_stream_socket permissive=1

12-12 14:17:01.118   765   765 I /system/bin/tombstoned: registered intercept for pid 1218 and type kDebuggerdJavaBacktrace
12-12 14:17:01.118  1218  1223 I chatty  : uid=1000 system_server expire 3 lines
12-12 14:17:03.109   765   765 I /system/bin/tombstoned: received crash request for pid 1218
12-12 14:17:03.109   765   765 I /system/bin/tombstoned: found intercept fd 512 for pid 1218 and type kDebuggerdJavaBacktrace
12-12 14:17:03.113   765   765 I /system/bin/tombstoned: registered intercept for pid 752 and type kDebuggerdNativeBacktrace
12-12 14:17:03.114   765   765 I /system/bin/tombstoned: received crash request for pid 752
12-12 14:17:03.114   765   765 I /system/bin/tombstoned: found intercept fd 512 for pid 752 and type kDebuggerdNativeBacktrace
12-12 14:17:03.392   765   765 I /system/bin/tombstoned: registered intercept for pid 656 and type kDebuggerdNativeBacktrace
… killing continues
```

At that point in time system started to deliberately kill every service that is managed under pid 1218. There is another log that was generated at almost same time - anr_2019-12-12-14-17-01-115:
```
----- pid 1218 at 2019-12-12 14:17:01 -----
Cmd line: system_server
Build fingerprint: 'HospIT/aosp_hpi4113/kirin-hp:9/PQ3A.190705.003/hospitality07311406:userdebug/dev-keys'
ABI: 'arm64'
Build type: optimized
Zygote loaded classes=11540 post zygote classes=2924
Intern table: 78515 strong; 1012 weak
JNI: CheckJNI is off; globals=1513 (plus 102 weak)
…
```

Though this is not our application that crashed or any application for that matter – this is “system_server” crash, and this essentially means that most of system get down. I assume that state that phone ends up in after this event is somewhat random in a sense how far this killing spree system managed to progress. Sometimes it kills ‘adb’ daemon and then there is almost no way to get anything useful from the device. We noticed similar behavior at XA2 device but there it seems that system manage to recover causing only short-time hiccups – I’m not sure that this is exactly same problem, but in both cases there are android.os.DeadSystemException in the logs.
I can’t tell reason why system server got killed or stuck in UI thread from these logs and need someone that have more expertise in that.

**Comment by jerpelea** [comment]
Kirin is working fine after the last fixes

**Comment by AngryGami** [comment]
Does this mean there will be new binaries for Pie at "https://developer.sony.com/develop/open-devices/downloads/software-binaries ?

**Comment by jerpelea** [comment]
Please use the latest precompiled kernel. I am using Kirin as my DD and I can not replicate the bug on the latest patches.
Kernel fixes were backported from 4.14 kernel

**Comment by AngryGami** [comment]
I also can't replicate bug - but it replicate itself on production and test phones randomly. How can we be sure or at least confident to some degree that whatever had been done (actually what?) solved the problem? Deploying new kernel to hundreds of devices in production is not something I want to jump into without better confirmation.

**Comment by jerpelea** [comment]
let me run tests for a longer period of time and we will see if there is any chance of replicating the bug

**Comment by AngryGami** [comment]
Ok, Thank you. Do you have any ideas what was causing this?

**Comment by jerpelea** [comment]
I suspect a memory leak that has been fixed

**Comment by jerpelea** [comment]
another thing that you can try on this device is doubling the ram size to create more free ram 
please try this change in fstab 
+/dev/block/zram0                            none        swap    defaults                                                      zramsize=2147483648,max_comp_streams=8


I am running it locally and works better

**Comment by AngryGami** [comment]
I will. Thanks.

**Comment by MarijnS95** [comment]
@AngryGami Normally I'd say this is an issue in the hardware/kernel, and would request a `dmesg` to debug. However, everything in the logs point to the Android system. If RAM was the cause, I'd expect log messages indicating so, but anything related to the system is hidden behind `chatty  : uid=1000 system_server expire xxx lines`. The system will happily kill applications for other reasons, but the root cause does not immediately pop up from the logcat.

**Comment by ix5** [comment]
Is this issue still present on Android 10 and Kernel 4.14?

**Comment by AngryGami** [comment]
Unlikely, but I don't have way to check.

**Comment by MarijnS95** [comment]
These are likely the GPU crashes that occur on 4.14, too. But for now impossible to confirm without the requested dmesg...

**Comment by MarijnS95** [comment]
@AngryGami Any updates on this issue? I have just heard in https://github.com/sonyxperiadev/kernel/pull/2217 that that PR did not resolve the problem, but have also linked a new commit in the last comment that may do: https://github.com/MarijnS95/kernel/commit/d42ec19d9b2

Can you report your findings?

**Comment by AngryGami** [comment]
@MarijnS95 I didn't apply any of the changes since we discussed this last time (most of the phones has this issue are already in production and I can't update them easily), I'm sorry. I can't either confirm or debunk anything about that patch. I'm working right now on new ROM for next batch of phones (based on Q), so maybe later I can tell if these fixes worked. When your patch will be available under some tag in main tree?

**Comment by MarijnS95** [comment]
@AngryGami No worries, I was just curious if anything changed since March. This patch will likely only end up in master if it turns out to fix things, which are to be confirmed by the other Ganges users around here.

**Comment by AngryGami** [comment]
So the only way for me to test this is to apply it manually?

**Comment by MarijnS95** [comment]
@AngryGami Yes, like 99% of the other pieces of this open source project. This might make it into the prebuilts before that time though if it ends up fixing the issue.

**Comment by AngryGami** [comment]
Doesn't happen anymore on Android 10 (and probably higher)
