### ISSUE TITLE
Sony Xperia XZ sensors issues!

### ISSUE THREAD

**Issue by xelmasx** [sonyxperiadev/bug_tracker#514]
Hi!
I am not sure this is right place to report project Treble base issues!
Anyway;
Except fingerprint sensor, rest of sensors are not working "accelerometer, gyro, proximity, barometer, compass,".

First of all , I flashed "aosp_f8331_10.0_2019-12-24-TREBLE-NIGHTLY.zip" after that flashed "system-quack-arm64-ab-gapps.img.xz" on it.

Everything works fine, as I said above "except sensors".

**Comment by ix5** [comment]
This is most likely related to the GSI you are using.
Please keep discussion in the XDA thread and close this issue.

**Comment by xelmasx** [comment]
Thanks reply.
