### ISSUE TITLE
[kirin] [aosp 10] [kernel 4.14] Mobile data connection resets every few seconds

### ISSUE THREAD

**Issue by xperia10dev** [sonyxperiadev/bug_tracker#517]
**Platform:** ganges
**Device:** kirin (i4113)
**Kernel version:** 4.14.83
**Android version:** android-10.0.0_r21
**Software binaries version:** 10.0.7.1_r1_v3_ganges

**Description**
Mobile data connection resets every few seconds

**Symptoms**
Impossible to maintain a mobile data connection for more than a few seconds

**How to reproduce**
Try to enable mobile data in settings

**Additional context**
Attached radio logcat which shows SIM errors, please request any more info if needed.
[logcat_radio.log](https://github.com/sonyxperiadev/bug_tracker/files/4082552/logcat_radio.log)

**Comment by xperia10dev** [comment]
Attached dmesg snippet with "Fatal error on the modem" that occurs when enabling Mobile Data.
[dmesg_modem_fatal_error.log](https://github.com/sonyxperiadev/bug_tracker/files/4082816/dmesg_modem_fatal_error.log)

**Comment by xperia10dev** [comment]
No improvement with kernel 4.14.160: the mobile data connection resets still happen every few seconds.

**Comment by xperia10dev** [comment]
No improvement with kernel 4.14.167 either.

Does anyone know if it makes any sense to keep trying the more recent kernels as they appear, or is this more of an OEM binary blob issue?

**Comment by MarijnS95** [comment]
There is no need to keep trying; this is likely a blob issue and we'll notify this issue as soon as it is resolved.

**Comment by xperia10dev** [comment]
Is there any chance that this problem has been fixed in the updated AOSP binaries from 2020-02-27? (SW_binaries_for_Xperia_Android_10.0.7.1_r1_v4c_ganges.zip).
The "Latest updates" page only mentions "Adreno update" for all devices.

**Comment by Haxk20** [comment]
@jerpelea This used to happen on v3 and legacy RIL. As of v4 and legacy RIL it doesnt happen and works fine. No clue as to whether new RIL works the same. But as this is about legacy. It can be closed.

**Comment by ix5** [comment]
Ping @jerpelea

**Comment by MarijnS95** [comment]
> Is there any chance that this problem has been fixed in the updated AOSP binaries from 2020-02-27? (SW_binaries_for_Xperia_Android_10.0.7.1_r1_v4c_ganges.zip).
> The "Latest updates" page only mentions "Adreno update" for all devices.

@xperia10dev I'm not aware whether RIL changed, but a new QCRILD was added that might solve all issues, as @Haxk20 mentioned. If you feel like trying, set `TARGET_USE_QCRILD := true` in the Ganges platform repo just like it was done for Kumano, **make sure you run `make installclean`**, then build and flash the ROM as usual, together with v4c.

**Comment by xperia10dev** [comment]
I'm closing this issue because the AOSP binaries from 2020-02-27 (SW_binaries_for_Xperia_Android_10.0.7.1_r1_v4c_ganges.zip) fix the problem.

Therefore I have not tried the new QCRILD.
