### ISSUE TITLE
[maple] liblowi_wifihal.so missing from SW binaries image

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/bug_tracker#52]
**Platform:** yoshino
**Device:** maple
**Kernel version:** 4.4
**Android version:** 7.1

**Description**
the library `liblowi_wifihal.so` is missing from the SW binaries image.  There should be a 64-bit and 32-bit version of that lib; see the following logcat messages:

```
01-05 00:42:34.890 E/WifiHAL ( 1202): fetchLowiCbTableAndCapabilities: NULL lowi_handle, err: dlopen failed: library "/vendor/lib64/liblowi_wifihal.so" not found
01-05 00:42:34.890 E/WifiHAL ( 1202): getLowiCallbackTable: LOWI is not supported.
01-05 00:42:34.893 E/WifiHAL ( 1202): fetchLowiCbTableAndCapabilities: NULL lowi_handle, err: dlopen failed: library "/vendor/lib64/liblowi_wifihal.so" not found
01-05 00:42:34.893 E/WifiHAL ( 1202): getLowiCallbackTable: LOWI is not supported.
01-05 00:42:34.893 E/WifiHAL ( 1202): fetchLowiCbTableAndCapabilities: NULL lowi_handle, err: dlopen failed: library "/vendor/lib64/liblowi_wifihal.so" not found
01-05 00:42:34.893 E/WifiHAL ( 1202): getLowiCallbackTable: LOWI is not supported.
01-05 00:42:34.894 E/WifiHAL ( 1202): fetchLowiCbTableAndCapabilities: NULL lowi_handle, err: dlopen failed: library "/vendor/lib64/liblowi_wifihal.so" not found
01-05 00:42:34.894 E/WifiHAL ( 1202): getLowiCallbackTable: LOWI is not supported.
01-05 00:42:34.897 E/WifiHAL ( 1202): fetchLowiCbTableAndCapabilities: NULL lowi_handle, err: dlopen failed: library "/vendor/lib64/liblowi_wifihal.so" not found
```

**Symptoms**

**How to reproduce**
flash your device and connect to wifi, then grab logs:  `adb logcat -v time | grep wifihal`

**Comment by jerpelea** [comment]
https://android.googlesource.com/platform/hardware/qcom/wlan/+/e0d30a0%5E%21/

**Comment by jamuir** [comment]
@jerpelea :  thanks for the url, but could you spare a few words of explanation?

Is the reason you exclude those libs from the oem image because wifi is supposed to work fine without them?

**Comment by jerpelea** [comment]
from the commit message "If HAL<-->LOWI
interface is not supported, Wi-Fi HAL will then proceed the normal way
by sending commands to the driver.
-Moved the utility functions used to open LOWI shared library, retrieve
handler to LOWI APIs table, and initialize LOWI module out of RTT module
into the HAL common module.'

**Comment by jamuir** [comment]
Sigh... That isn't helpful.

It looks like maple supports lowi.

Is there some engineering related reason why those libs are being held back?

**Comment by jerpelea** [comment]
we opted to have as much OSS as possible and the libs are not available in OSS
