### ISSUE TITLE
[maple][Yoshino] Phone boots to a blank screen, no bootanimation played.

### ISSUE THREAD

**Issue by Meradoch** [sonyxperiadev/bug_tracker#521]
**Platform:** Yoshino
**Device:** maple (g8142)
**Kernel version:** 4.14.83
**Android version:** android-10.0.0_r21
**Software binaries version:** 10.0.7.1_r1_v3a_yoshino

**Description**
Boot animation doesn't play, phone stuck in blank screen then bootloops.

[log.log](https://github.com/sonyxperiadev/bug_tracker/files/4106954/log.log)

**How to reproduce**
Build and flash according to the sony guide.

**Comment by stefanhh0** [comment]
I think maple should just work now on the most recent version. Please make a new clean build and retry.

**Comment by Meradoch** [comment]
Ok. I'm compiling it right now and see how it goes

**Comment by Meradoch** [comment]
> Ok. I'm compiling it right now and see how it goes

It just restarted for me after Sony logo. I don't know how to get logs in that state

**Comment by stefanhh0** [comment]
On which kernel-commit  have you done the build? Without: 
sonyxperiadev/kernel/commit@82416d86d95fdc31d148d53203da7048ec9ba654 
yoshino is trapped in a bootloop and won't get past the sony logo, like you describe. 

If you are using prebuilt kernel ensure to have used commit:
sonyxperiadev/kernel-sony-msm-4.14-common/commit@5074f584979c10fb0ac649fd2658ea48811ef616  

Important as well is to flash `userdata.img`.

When I tried last time I could basically boot but the phone was not that much useable after all. See as well: #534 - however that is  lilac, so maybe on maple the results are better plus another few days have past that have seen some more additions in the aosp repos.

**Comment by Meradoch** [comment]
With the current sources, i.e. Kernel 4.14.167 after Sony logo the phone doesn't show any bootanimation. Charging LED comes on and even turns green when, I assume, battery reaches 90%. Double pressing the power button I can feel the phone vibrate, which should mean it has switched the camera on. I want to believe my phone is fully booted, But can't display anything.
Here are my logs:
[logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/4176903/logcat.txt)
[dmesg-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/4176905/dmesg-ramoops-0.txt)
[dmesg-ramoops-1.txt](https://github.com/sonyxperiadev/bug_tracker/files/4176906/dmesg-ramoops-1.txt)
[console-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/4176907/console-ramoops-0.txt)

**Comment by kholk** [comment]
Issue is solved.
This requires you to compile and run the newest kernel and wait for the next ODM release, or delete libdisplayqos.so from the current release.

**Comment by jerpelea** [comment]
fixed in the latest release
