### ISSUE TITLE
Broken HDR playback with black screen

### ISSUE THREAD

**Issue by KingArron** [sonyxperiadev/bug_tracker#523]
**Platform:** Tama
**Device:** XZ2 H8216
**Kernel version:** 4.14.150
**Android version:** 10
**Software binaries version:** 10.0.7.1_R1_V3A_TAMA

**Description**
When I playback any HDR video on any app it would result in a black screen with only audio playing, this happens on YouTube, Kodi and the rest.

**How to reproduce**
The issue happens on any Android 10 rom based on SODP like Pixel experience or any Sony based sources with kernel 4.1.4.

**Comment by MarijnS95** [comment]
We are aware of this being an issue with VIDC. Unfortunately no-one has stepped up with some time on their hands to debug and resolve the issues.

**Comment by KingArron** [comment]
> We are aware of this being an issue with VIDC. Unfortunately no-one has stepped up with some time on their hands to debug and resolve the issues.


![20e73198-0f6f-451b-9766-9fec3622f946 (1)](https://user-images.githubusercontent.com/60351492/73202877-e50a0c80-4133-11ea-8353-260048042f31.jpg)
Got a different version of Kodi and HDR now seems to work?

**Comment by jerpelea** [comment]
Discontinued Android version
