### ISSUE TITLE
Tama Sony XZ2 screen tearing and slow touch responsiveness 

### ISSUE THREAD

**Issue by KingArron** [sonyxperiadev/bug_tracker#525]
**Platform:** Tama
**Device:** XZ2 H8216
**Kernel version:** 4.14.150
**Android version:** 10 
**Software binaries version:** 10.0.7.1_R1_V3A_TAMA

**Description**
There is a fair amount of screen tearing when watching videos or navigating around the ui when scrolling, like the Android settings page or the navigation panel swiping in file explorer app on Pixel experience or and Android 10 based ROM on sonys latest 4.14 OEM.

**How to reproduce**
Flash any Android 10 based ROM like SODP or PE alongside OEM 10.0.7.1_R1_V3A_TAMA and navigate to the default File explorer and swipe the left navigation bar slowly and you can see screen tearing and slow response rate.

**Comment by jerpelea** [comment]
please try again with the latest vendor release

**Comment by jerpelea** [comment]
Discontinued Android version
