### ISSUE TITLE
[Tama] Dual sim cards issue

### ISSUE THREAD

**Issue by sjllls** [sonyxperiadev/bug_tracker#528]
**Platform:** Tama
**Device:** Akari (H8296)
**Kernel version:** 4.14
**Android version:** 10.0
**Software binaries version:** 10.0.7.1_R1_V3A_TAMA

**Description**
VoLTE works fine with single sim (China Mobile).

 But if I insert 2 sim card (SIM1: China Mobile, SIM2 China Unicom). SIM1 could only stay at 2G (EDGE), SIM2 could staty on LTE.  SIM1 is used for mobile data.
Force to LTE only in *#*#4636#*#* will cause no singal.

Note:  China Mobile is TD-LTE,  China Unicom is FDD-LTE.

I guess there is something wrong with IMS configuration.

**Additional context**
Log:
[xz2-dual.txt](https://github.com/sonyxperiadev/bug_tracker/files/4132815/xz2-dual.txt)

**Comment by kholk** [comment]
We have recently merged our shiny new ModemConfig implementation: can you please check if your issue is solved?

**Comment by sjllls** [comment]
> We have recently merged our shiny new ModemConfig implementation: can you please check if your issue is solved?

No problem, I will test it after my PC is fixed.
Thanks a lot! :P
