### ISSUE TITLE
NFC does not read extended length cards

### ISSUE THREAD

**Issue by jerpelea** [sonyxperiadev/bug_tracker#53]
Platform: ALL
Device: ALL
Kernel version: ALL
Android version: ALL

Description
the cards that use extended length are not read by NFC

Symptoms
The card is not read 

How to reproduce
Swipe a card 

https://www.openecard.org/en/ecard-api-framework/extended-length-problem/

**Comment by jerpelea** [comment]
description 
https://www.openecard.org/en/ecard-api-framework/extended-length-problem/

**Comment by jerpelea** [comment]
@myself5 please test on your card

**Comment by jerpelea** [comment]
possible fix 
https://review.lineageos.org/#/q/topic:extended-length-nfc+(status:open+OR+status:merged)

**Comment by Myself5** [comment]
Can confirm that maple fails to read my MiFare NFC Card. Was thinking its a me-issue though. I'll try the fixes next week and report.

**Comment by jerpelea** [comment]
thanks

**Comment by jerpelea** [comment]
https://android-review.googlesource.com/#/q/topic:%22max_transceive_length%22+(status:open%20OR%20status:merged)
merged in AOSP

**Comment by jerpelea** [comment]
AusweisApp2 app can be used for testing
