### ISSUE TITLE
[Yoshino][Lilac] Kernel 4.14 bootloops.

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#530]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14.167
**Android version:** android-10.0.0_r21
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v3_yoshino.img
**Version baseband:** 1307-7511_47.2.A.11.228
**Used Kernel-Compiler:** Clang

**Description**
With the most recent version my phone hangs in boot-loop. It is not possible to connect adb.
Tried two different kernels with the same result:

- Most recent kernel: https://github.com/sonyxperiadev/kernel/commit/b66e549327f0f06f2e248fec288902ed18904571
- Most recent kernel: https://github.com/sonyxperiadev/kernel/commit/b66e549327f0f06f2e248fec288902ed18904571 + reverted: https://github.com/sonyxperiadev/kernel/commit/b0ee9746150cd1590c58bf55a861f000c0f31482

Flashed a k4.9 recovery.img but the phone did not boot into recovery after crashing, but a double crash occurred. So I am unable to recover `/sys/fs/pstore` contents.

To build it, I have used following script:
https://github.com/stefanhh0/aosp-10/blob/master/build-4.14.sh

I have flashed following images from the 4.14 build:
```
stefan@mars:~/android/bin/current-4.14$ ls -l
insgesamt 28
lrwxrwxrwx 1 stefan stefan 33 Feb  1 16:46 boot.img -> ../2020.02.01-4.14/boot-clang.img
lrwxrwxrwx 1 stefan stefan 28 Feb  1 18:39 cache.img -> ../2020.02.01-4.14/cache.img
lrwxrwxrwx 1 stefan stefan 60 Feb  1 16:47 oem.img -> ../SW_binaries_for_Xperia_Android_10.0.7.1_r1_v3_yoshino.img
lrwxrwxrwx 1 stefan stefan 31 Feb  1 16:46 recovery.img -> ../2020.02.01-4.14/recovery.img
lrwxrwxrwx 1 stefan stefan 29 Feb  1 16:46 system.img -> ../2020.02.01-4.14/system.img
lrwxrwxrwx 1 stefan stefan 31 Feb  1 16:46 userdata.img -> ../2020.02.01-4.14/userdata.img
lrwxrwxrwx 1 stefan stefan 29 Feb  1 16:46 vendor.img -> ../2020.02.01-4.14/vendor.img
```

**Comment by andrwgldmn** [comment]
did you try to build a kernel with GCC?

**Comment by stblr** [comment]
`git bisect` gives sonyxperiadev/kernel@b5b8742 as the first bad commit.

**Comment by stefanhh0** [comment]
I bet it is upstream kernel commit:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-4.14.y&id=afe13dc9835a4ca5bd44f74fdc6e8b3a8b6dd402

Thanks for your finding @stblr - it made trouble as well on 4.9 kernel, see: https://github.com/sonyxperiadev/kernel/commit/da71b0d9d2a354f27df90567277632dfa4a6c0dd
