### ISSUE TITLE
[Maple][4.9] Wifi doesnt work properly, Usb tethering doesnt work

### ISSUE THREAD

**Issue by kgvarunkanth** [sonyxperiadev/bug_tracker#533]
**Platform: Yoshino
**Device: Maple_Dsds(G8142)
**Kernel version: 4.9
**Android version: 9.0
**Software binaries version: 2.3.2 _v9

**Description**

WiFi isn't working properly...
When device is booted , the WiFi works properly for few minutes till the screen goes off,then WiFi doesn't obtain IP address ....(DHCP assignment failure)

Also , When I turn on USB tethering mode , Phone just reboots itself
**Symptoms**
WiFi works well when I reboot the device 
The moment when the screen goes off and turned on , WiFi doesn't connect, REASON : DHCP ASSIGNMENT FAILURE

Tried USB tethering mode , which causes a freeze and reboots
**How to reproduce**
 Find a nice twrp 
Flash twrp 
Flash OEM software binary file 2.3.2 v9 for pie
Flash ZFSODP 
Issue 1:
Let it boot normally
Connect to a random WiFi (it should work well)
Now turn screen off...and turn back it again (Now turn off WiFi and turn back it on, Now you should see that WiFi only shows you "Obtaining IP address" and doesn't connect (DHCP FAILURE)

Issue 2: 
Connect your phone to the PC with USB 
Go to settings and turn on USB tethering 
Now the phone should freeze for 2-4secs and go for a reboot forcefully

**Comment by ix5** [comment]
Maybe don't "flash" something that describes itself as "The old Android Pie incomplete repos of ZestOS (formally ZfSODP)."
https://github.com/zfsodp

**Comment by kgvarunkanth** [comment]
> Maybe don't "flash" something that describes itself as "The old Android Pie incomplete repos of ZestOS (formally ZfSODP)."
> https://github.com/zfsodp

Ugh.  .OK....Will check out android 10 on 4.14 kernel...

**Comment by MarijnS95** [comment]
Keep in mind that kernel 4.14 is not fully ready for Yoshino yet. While we're working hard it may still take a couple more days.

Perhaps you have more luck using kernel 4.9 and Android 9 from the official sonyxperiadev repositories directly.

**Comment by kgvarunkanth** [comment]
Tq

**Comment by ix5** [comment]
Should be closed in favour of https://github.com/sonyxperiadev/bug_tracker/issues/299
K4.9 seems to have major tethering issues on legacy.

**Comment by kgvarunkanth** [comment]
> Should be closed in favour of #299
> K4.9 seems to have major tethering issues on legacy.

Yes....Also adb and mtp is detected after a very long time on PC...
Stock rom detects faster than usual

**Comment by ix5** [comment]
Please close the issue and follow #299

**Comment by kgvarunkanth** [comment]
Closing issue Following #299
