### ISSUE TITLE
[Yoshino] [Lilac] Panel doesn't wake up after sleep

### ISSUE THREAD

**Issue by stblr** [sonyxperiadev/bug_tracker#537]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14.167
**Android version:** 10 r21
**Software binaries version:** v3

**Previously working on**
Supposedly kernel 4.9

**Description**
When pressing the power button for the first time, the screen is correctly turned off. When pressing the power button again, the backlight turns on shortly (0.5 s or so), then turns off, then turns on again for the expected time (5 s I think). But the panel itself stays black.

**Additional context**
[dmesg](https://github.com/sonyxperiadev/bug_tracker/files/4187403/dmesg.txt)
[logcat](https://github.com/sonyxperiadev/bug_tracker/files/4187404/logcat.txt)

The relevant part of the dmesg is probably this:
```
[   70.221287] [drm:sde_crtc_atomic_begin:3765] [sde error]border fill only commit after ctlstart timeout
[   70.449153] msm-dsi-display:[dsi_display_status_check_te] TE check failed
[   70.449280] [drm:_sde_connector_report_panel_dead:1914] [sde error]esd check failed report PANEL_DEAD conn_id: 28 enc_id: 27
[   70.453515] dsi-ctrl:[dsi_ctrl_handle_error_status] dsi FIFO UNDERFLOW error: 0xf08000
[   70.455064] [drm:sde_encoder_phys_cmd_prepare_for_kickoff:1390] [sde error]failed wait_for_idle: -110
```

Similar issues are #449 and #534.

**Comment by stefanhh0** [comment]
Pretty sure that this is a duplicate report to: #534. Can confirm the behavior.

**Comment by stblr** [comment]
I'm closing this one then.
