### ISSUE TITLE
[4.14][10.0][TAMA] Battery levels are wrong

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#539]
**Platform:** TAMA
**Device:** akari, apollo, maybe akatsuki
**Kernel version:** 4.14
**Android version:** 10.0
**Software binaries version:** OEMv3

**Previously working on**
Kernel 4.9 and android 9.0

**Description**
It seems that the battery level is wrong.
Problem maybe in fuel gauge, healthd, kernel.

**Symptoms**
The battery level raises or lowers too fast or slow.
It can also jump like from 73% to 98%
Or from 22% to 3%.
Or slow charging from USB may fill the battery up to 100% fast

**How to reproduce**
Just use the phone.

**Additional context**
[battery_logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/4209843/battery_logcat.log)
[battery_dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/4209844/battery_dmesg.log)
[adb bugreport batteryissues.zip](https://github.com/sonyxperiadev/bug_tracker/files/4209870/batteryissues.zip)

For an example battery level jump:
Battery logging started at
`0 (24) RESET:TIME: 2020-02-16-10-24-58`
Jump from 74% to 98% happened between `2:03:34 PM` and `2:17:14 PM`
It happens exactly at `+3h43m51s816ms`

Edit 2020-02-27:
Here the battery level crashed from 71% to 0% and lead to a device shutdown at night.
Timestamp: `+5h17m02s445ms`
[battery_crash_night.zip](https://github.com/sonyxperiadev/bug_tracker/files/4260419/battery_crash_night.zip)

**Comment by nikdib** [comment]
i also have this bug. i have xz2 compact (h8314) and the battery seems to go down normally but when it reaches a random % the phone turns off believing that it has run out of battery but it is not finished because then it turns on again but at a different % and if i put it on charge the % of battery goes up very fast and I don't have a quick charger but at 7.5 watt. I have the dmesg which in the end shows the battery charging too fast.

[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/4210600/dmesg.log)

**Comment by nickholtus** [comment]
Bug also present on akatsuki.
Battery apps say that battery capacity is 3060MAH but it also should be 3300MAH for XZ3

**Comment by MarijnS95** [comment]
@nickholtus Note that there is a difference between the maximum design capacity and the maximum capacity after wear. The battery app you are using may or may not represent the appropriate value.

For correctness, check the output of the battery driver in sysfs:
```sh
adb shell awk '{print $1/10**3 "mAh"}' /sys/class/power_supply/battery/charge_full*
```

**Comment by MartinX3** [comment]
Updated my kernel on akari XZ2 to updated my kernel to commit https://github.com/sonyxperiadev/kernel/commit/1aaf380ed91b99fd8816a6924fc083ccba43d446
Then I fully depleted the battery until my phone did shutdown and charged it up to 100% via my computer USB.

~29h later i don't see ah battery jump on (dis)charging anymore.
Maybe coincidence or maybe fixed now.

Will observe further my battery percentage graph.

**Comment by MartinX3** [comment]
Seems to be fixed by https://github.com/sonyxperiadev/kernel/pull/2273
