### ISSUE TITLE
[POPLAR] Recorded videos have visible 60Hz flicker

### ISSUE THREAD

**Issue by AdFad666** [sonyxperiadev/bug_tracker#54]
**Platform:** Yoshino
**Device:** Poplar
**Kernel version:** 4.4
**Android version:** 8.0

**Description**
Recorded videos have visible 60Hz flicker

**How to reproduce**
Record a video in artificial lighting.

![giphy](https://user-images.githubusercontent.com/1012095/33236351-ed158c96-d250-11e7-815d-2289c5467c8f.gif)

**Comment by oshmoun** [comment]
also happens on kugo, so it's probably a general issue affecting all platforms.

**Comment by oshmoun** [comment]
Can't seem to replicate this anymore on v6.
