### ISSUE TITLE
[4.14][10.0][TAMA] Mobile & wifi sometimes unstable

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#540]
**Platform:** TAMA
**Device:** akari, apollo, maybe akatsuki
**Kernel version:** 4.14
**Android version:** 10.0
**Software binaries version:** OEMv3

**Previously working on**
Kernel 4.9 and android 9.0

**Description**
It seems that waking up the phone and using mobile/wifi leads into a mobile/wifi crash.
But then it is usable.

**Symptoms**
The wifi/mobile lost their signal and reconnect.

**How to reproduce**
Flash & boot stock 10 first.
Then flash SODP.
Pull the phone from standby and use your mobile data.

**Additional context**
[mobile_wifi_logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/4209993/mobile_wifi_logcat.log)
[mobile_wifi_dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/4209994/mobile_wifi_dmesg.log)
[mobile_wifi_issues.zip](https://github.com/sonyxperiadev/bug_tracker/files/4209995/mobile_wifi_issues.zip)

**Comment by nikdib** [comment]
i also have this bug for the wifi. sometimes the wifi it disconnect and reconnect. i have xz2 compact (H8314) and i noticed this bug also in sony stock android 10 firmware .532. I take a logcat with alogcat root.
[alogcat.2020-02-04-11-36-51+0100.txt](https://github.com/sonyxperiadev/bug_tracker/files/4210206/alogcat.2020-02-04-11-36-51%2B0100.txt)

**Comment by oshmoun** [comment]
is this still valid?

**Comment by MartinX3** [comment]
Yes
But since my mobile is dead (https://github.com/sonyxperiadev/bug_tracker/issues/554) the wifi seems to be much more stable.
I don't recognize a single crash anymore.
Maybe coincidence.

**Comment by MartinX3** [comment]
Yes, the wifi problem still happens since I've got back my mobile network access.
