### ISSUE TITLE
[Yoshino][Poplar] Battery stuck at 20% when flash sodp 9 / 10

### ISSUE THREAD

**Issue by yuezhengbaizhi** [sonyxperiadev/bug_tracker#542]
**Platform:** Yoshino
**Device:** Poplar
**Kernel version:** 4.14 / 4.9
**Android version:** 10 / 9
**Software binaries version:** v3a / v9

**Previously working on** 
it work the first time i flash sodp build ( the battery display was normal)

**Description**
when i flash back to stock with newflasher and flash back to sodp the battery stuck at 20%

**Symptoms**
Write the symptoms here.

**How to reproduce**
flash sodp build, then flash stock with newflasher with presist partition flashed, then flash sodp again

**Additional context**
when i run logcat i found this:
11-29 14:45:13.168   621   621 E /vendor/bin/hw/android.hardware.health@2.0-service.sony: Cannot read battery capacity persist file from /mnt/vendor/persist/battery/battery_charge_full: No such file or directory

**Comment by ix5** [comment]
Please give full logs and dmesg. Write down the version of the stock firmware you flashed.

And do you mean to save you switched between stock and SODP without clearing /data in-between? That's just asking for trouble.

And I'm not clear on what you mean by
> then flash stock with newflasher with presist partition flashed

Do you mean you excluded the stock `persist.sin` from the bundle, or do you mean you *did* include it when you flashed "stock" with the newflasher tool?

Then give us the values of:
```
/sys/class/power_supply/bms/cycle_count
/mnt/vendor/persist/battery/battery_cycle_count
/sys/class/power_supply/bms/charge_full
/mnt/vendor/persist/battery/battery_charge_full
```
And `ls -laZ /sys/class/power_supply/*`

**Comment by yuezhengbaizhi** [comment]
> Please give full logs and dmesg. Write down the version of the stock firmware you flashed.
> 
> And do you mean to save you switched between stock and SODP without clearing /data in-between? That's just asking for trouble.
> 
> And I'm not clear on what you mean by
> 
> > then flash stock with newflasher with presist partition flashed
> 
> Do you mean you excluded the stock `persist.sin` from the bundle, or do you mean you _did_ include it when you flashed "stock" with the newflasher tool?
> 
> Then give us the values of:
> 
> ```
> /sys/class/power_supply/bms/cycle_count
> /mnt/vendor/persist/battery/battery_cycle_count
> /sys/class/power_supply/bms/charge_full
> /mnt/vendor/persist/battery/battery_charge_full
> ```
> 
> And `ls -laZ /sys/class/power_supply/*`

I did a clean flash with everything included except .ta file flashed with newflasher and the firmware is the latest firmware and when I checked my presist folder there is no folder called battery.

Can you send me the mnt/vendor/persist/battery folder so I can try and place it under my presist folder to see if that fixes the problem?

**Comment by ix5** [comment]
Do what I asked you to above. What's so hard about following instructions?

Ain't gonna do your debugging for you...

---

In any case, just don't switch between stock and SODP willy-nilly while forgetting to clear data.
I'm pretty sure you are dirty-flashing and not telling us.

Also, the persist folder is created by init automaticlly, see [the init file](https://github.com/sonyxperiadev/device-sony-common/blob/master/hardware/health/android.hardware.health%402.0-service.sony.rc#L3)

And why would giving you a dump of my persist folder fix anything? You'd get wrong battery calibration values...

Questions over questions...
