### ISSUE TITLE
[4.14][10.0][TAMA][AKARI] Broken ADB shell in recovery

### ISSUE THREAD

**Issue by Gouster4** [sonyxperiadev/bug_tracker#545]
**Platform:Tama** 
**Device:Akari** 
**Kernel version:4.14.168-gf40989ad52e0-dirty** 
**Android version:10** 
**Software binaries version:v3** 

**Previously working on**
Idk.

**Description**
Since im in sideload, adb found my phone.
Once i exit sideload, no device found.
Also no device after booting recovery until i enter sidload

**Symptoms**
adb shell
error: no devices/emulators found

**How to reproduce**
Boot to recovery and run adb devices

**Additional context**
For Martin it works after reboot to recovery, but he has same issue after entering and exiting sideload.

**Comment by MartinX3** [comment]
I can confirm it.
ADB works in recovery mode until I start the sideload mode.
If I go back into the normal recovery menu the ADB recovery mode refuses to work until I reboot into recovery.
The sideload mode works always.

**Comment by Gouster4** [comment]
for me is adb killed since i enter recovery. But adb shell works also fine here.

**Comment by Gouster4** [comment]
[pstore](http://techax.sk/recovery_pstore.zip)

**Comment by MartinX3** [comment]
I see in a loop
```
[    6.769645] read descriptors
[    6.769804] read strings
[    6.770241] init: processing action (sys.usb.config=adb && sys.usb.configfs=1 && sys.usb.ffs.ready=1) from (/init.rc:182)
[    6.771743] android_work: did not send uevent (0 0 0000000000000000)
[    6.772106] init: processing action (sys.usb.config=adb && sys.usb.ffs.ready=1) from (/init.recovery.akari.rc:25)
[    6.773648] android_work: did not send uevent (0 0 0000000000000000)
```

**Comment by ix5** [comment]
Looks indeed like the kernel usb gadget driver is failing to send the "Connected"/"Configuring" uevent

**Comment by ix5** [comment]
Oh also Angelo might've messed about with the recovery scripts and introduced a duplication in the recovery inits.
Please try https://github.com/sonyxperiadev/device-sony-common/pull/695#event-3086962769

**Comment by MartinX3** [comment]
thank you!

@Gouster4 fixed! Please close it.
