### ISSUE TITLE
[Yoshino] [Poplar] XZ1 can't boot any gsi with sodp vendor and boot from Android 9 and 10

### ISSUE THREAD

**Issue by yuezhengbaizhi** [sonyxperiadev/bug_tracker#547]
**Platform:** yoshino
**Device:** poplar
**Kernel version:** 4.9 /4.14
**Android version:** 9 / 10
**Software binaries version:** v9 / v3a

**Is your feature request related to a problem? Please describe.**
when flashed a GSI system image (like the Erfan or Phh GSI) the device would not pass the Sony screen and would bootloop.

**Describe the solution you'd like**
hope i can boot into the GSI system

**Additional context**
also i can't boot any GSI with the stock vendor and boot too.

**Comment by ix5** [comment]
Needs more information or this needs to be closed.

Does your device boot when you flash your regular compiled SODP build?
Which *exact* GSIs did you try? And are you sure you picked the correct ones? I am fairly certain that you need use use 64bit, A/B system-as-root GSIs with Android 10 and onward.

**Comment by MarijnS95** [comment]
Keymaster issues as described in https://github.com/sonyxperiadev/bug_tracker/issues/543 might be at play here too.

**Comment by yuezhengbaizhi** [comment]
> Needs more information or this needs to be closed.
> 
> Does your device boot when you flash your regular compiled SODP build?
> Which _exact_ GSIs did you try? And are you sure you picked the correct ones? I am fairly certain that you need use use 64bit, A/B system-as-root GSIs with Android 10 and onward.

It boots find with sodp builds if I don't flash GSI.
I tried the Phh Pie GSI ( aonly/arm64) and Erfan GSI (AONLY/arm64) and the RR PIE GSI (AONLY /ARM64)

**Comment by yuezhengbaizhi** [comment]
> Well there's your issue I guess. Since Android 10, all devices have been moved to a kind of system-as-root, which means you should use an A/B build.

but all the Gsi builds i try are based on Pie / 9

**Comment by ix5** [comment]
So you are using a Pie SODP build as your treble base?

**Comment by yuezhengbaizhi** [comment]
> So you are using a Pie SODP build as your treble base?

Yes

**Comment by ix5** [comment]
Please close this and continue discussion in https://github.com/sonyxperiadev/bug_tracker/issues/543

**Comment by yuezhengbaizhi** [comment]
> Please close this and continue discussion in #543

ok
