### ISSUE TITLE
[4.14][10.0][TAMA] Bottom speaker doesn't work if call switched to speaker mode (ACDB?)

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#549]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.14
**Android version:** 10.0
**Software binaries version:** OEMv3 & OEMv4b

**Previously working on**
4.9 with 9.0

**Description**
While using the phone in call speaker mode, only the ear speaker works.
I heard a similar bug got fixed on the XZ3 by fixing ACDB.

**Symptoms**
The Ear Speaker is fine.
The bottom speaker is offline?

**How to reproduce**
Call someone, turn the call into the speaker mode.

**Additional context**
[speaker.txt](https://github.com/sonyxperiadev/bug_tracker/files/4264328/speaker.txt)

**Comment by oshmoun** [comment]
is the bottom speaker completely dead after this, and needs a reboot to work again? or does it still work for normal audio playback?

**Comment by MartinX3** [comment]
Youtube is fine, both speakers are equal loud.
Only while doing phone calls and switching to speaker mode as far as I was able to test it.

**Comment by oshmoun** [comment]
but are you starting youtube before or after the phone call?

**Comment by MartinX3** [comment]
I don't hear a difference if I start youtube before or after a phone call.

Ah, maybe the bottom speaker is very silent. It is a bit hard for my ears to distinguish if I hear a quiet bottom speaker or just the sound of the loud top speaker.
But definitely only in calls there is a big difference.

**Comment by MartinX3** [comment]
[phoneCallSpeaker_logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/4274320/phoneCallSpeaker_logcat.log)
And as requested a new log :)

**Comment by oshmoun** [comment]
after comparing with 4.9, the bottom speaker never was active for incall. it should be worth it to enable stereo for incall speaker, and does seem pretty straightforward. the only issue left to figure out is the inability to change volume.
