### ISSUE TITLE
[Yoshino] [All] v4 binaries can't be downloaded

### ISSUE THREAD

**Issue by stblr** [sonyxperiadev/bug_tracker#550]
When trying to download from https://developer.sony.com/file/download/software-binaries-for-aosp-android-10-0-kernel-4-14-yoshino/ an "access denied" error is returned.

**Comment by shank03** [comment]
Yeah, it does the same. Even the size shows "Nan B". Don't know what's going on.

I need those binaries to test my AOSP build :((

Do Something Sony !!

**Comment by Dzanar** [comment]
Sony please upload the correct file.

**Comment by stblr** [comment]
Fixed, thanks!
