### ISSUE TITLE
[4.14][10.0][TAMA][Akatsuki] Screen sometimes doesn't turn on

### ISSUE THREAD

**Issue by nickholtus** [sonyxperiadev/bug_tracker#552]
**Platform:** Tama 
**Device:** Akatsuki (XZ3)
**Kernel version:** 4.14
**Android version:** 10.0
**Software binaries version:** v4 (also on v3 and earlier)

**Previously working on**
Problem since first version of 10.0, issue not present on stock rom

**Description**
Sometimes screen doesn't wake from sleep. Only force reboot fixes this

**Symptoms**
Screen keeps black, sound works, fingerprint works

**How to reproduce**
Put device in sleep, sometimes it happens sometimes not

**Additional context**
See attachment for logcat. Logcat made with lineageos, but same issue present on SODP. see end of logcat 
[logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/4282066/logcat.txt)

**Comment by strangeowl** [comment]
Same issue here with Akatsuki with android version 11 and binaries 11_4.14_V3A
If booting start with snowy screen. High chance to have this issue.

**Comment by jerpelea** [comment]
can you still replicate the issue with the latest binaries?

**Comment by jerpelea** [comment]
Discontinued Android version
