### ISSUE TITLE
[10][4.14][Yoshino] [Poplar] The kernel auditor showing all core offline and soc temp up to 4400 degree

### ISSUE THREAD

**Issue by yuezhengbaizhi** [sonyxperiadev/bug_tracker#553]
**Platform:** Yoshino
**Device:** Poplar
**Kernel version:** 4.14
**Android version:** 10
**Software binaries version:**  v4c

**Previously working on**
i think it's a new issue with the 4.14 kernel or the driver
**Description**
i flashed the sodp image i build for xz1 following the official build guide and when it boots up i found the device is very laggy, so i download a kernel auditor trying to tweak the kernel settings, but i see this :
![image](https://user-images.githubusercontent.com/42693943/75948260-fbad2d00-5e70-11ea-80c8-ed4ea9b95cab.png)

i feel that something isn't right so i open this issue
**Symptoms**
core all showing offline in kernel auditor, soc temp reaching 4400 degree +

**How to reproduce**
build and flash the latest sodp 10 following the guide on sodp website.

**Additional context**
here is logcat : [xz1.txt](https://github.com/sonyxperiadev/bug_tracker/files/4290989/xz1.txt)

more logcat : 
[xz1_2.txt](https://github.com/sonyxperiadev/bug_tracker/files/4290992/xz1_2.txt)

**Comment by ix5** [comment]
Most likely the sysfs paths changed and kernel audiutor doesn't know about them yet.
The temp might be a unit conversion error.

The lag is indeed a different issue.

Those logcats don't show anything related to KA afaics, but you seem to be using a `Hentai` OS and having constant audio crashes... Maybe try plain AOSP and see if the issue persists.

**Comment by Dzanar** [comment]
The device XZ Premium (maple) is so laagyy too.

**Comment by kgvarunkanth** [comment]
@Dzanar Dude Maple boots on 4.14????
Aosp10???

**Comment by ix5** [comment]
Please build plain AOSP and rely on the values in sysfs. KA might be inaccurate since it seems to have the wrong conversion factor.

If you have nothing further to add, this issue should be closed since it's not part of the scope of SODP.

**Comment by yuezhengbaizhi** [comment]
> Please build plain AOSP and rely on the values in sysfs. KA might be inaccurate since it seems to have the wrong conversion factor.
> 
> If you have nothing further to add, this issue should be closed since it's not part of the scope of SODP.

okay
