### ISSUE TITLE
[4.14][10.0][TAMA][AKARI] Radio dead after flashed persist, bluetooth, dsp, modem, rdimage from 52.1.A.0.618

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#554]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.14
**Android version:** 10.0
**Software binaries version:** OEMv4c with new QCRILD

**Previously working on**
Before I flashed the stock stuff

**Description**
QCRILD (as mentioned above) enabled via `TARGET_USE_QCRILD=true` and was working before flashing the stock firmware partitions.
The radio is dead

Forgot to add logs with the old ril.
And sadly it gives me the same result.
(Empty signal bar, no internet and the message "only emergency calls")

**Symptoms**
No RIL.
It just say "only emergency calls"
The logcat shows a loop of `Service not connected.`

**How to reproduce**
Flashing persist, bluetooth, dsp, modem, rdimage from 52.1.A.0.618

**Additional context**
[QCRILD_logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/4292962/QCRILD_logcat.log) (logcat -b radio)
[QCRILD_dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/4292963/QCRILD_dmesg.log)
[radio_on_boot.log](https://github.com/sonyxperiadev/bug_tracker/files/4293023/radio_on_boot.log) (logcat -b all)
[radio_after_boot.log](https://github.com/sonyxperiadev/bug_tracker/files/4293025/radio_after_boot.log) (logcat -b all)

Forgot to add logs with the old ril
[old_ril_radio_after_boot.log](https://github.com/sonyxperiadev/bug_tracker/files/4300121/old_ril_radio_after_boot.log) (logcat -b all)
[old_ril_radio_on_boot.log](https://github.com/sonyxperiadev/bug_tracker/files/4300122/old_ril_radio_on_boot.log) (logcat -b all)

**Comment by MartinX3** [comment]
Fixed by booting the stock firmware once, letting it update the modem at the end of the introduction assistant and switching back to SODP.

So something is missing in SODP to get triggered on an update of these partitions.

**Comment by ix5** [comment]
This is expected behaviour. We expect users to boot up stock at least once before flashing SODP.

You can hate it all you want, but we cannot (easily) do the initialization ourselves because lots of that stuff is proprietary.

Please close.
