### ISSUE TITLE
[4.14][10.0][TAMA][AKARI] Rare device crash (because wlan?)

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#555]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.14
**Android version:** 10.0
**Software binaries version:** OEMv4c

**Previously working on**
4.9 & OEMv9
4.14 & OEMv3 & before https://github.com/sonyxperiadev/vendor-qcom-opensource-wlan-qcacld-3.0/pull/22 (Maybe the problem existed before)

**Description**
It seems that the phone got a kernel panic during sleep & while only wifi connected.

**Symptoms**
Kernel panic.
A restarted phone.
A pstore.

**How to reproduce**
Rarely happen.
This time the phone was in planemode + wifi activated.
It lie around and suddenly restarted. (Was not using it at this time).

**Additional context**
PStore:
[console-ramoops-0.log](https://github.com/sonyxperiadev/bug_tracker/files/4300462/console-ramoops-0.log)
[dmesg-ramoops-0.log](https://github.com/sonyxperiadev/bug_tracker/files/4300463/dmesg-ramoops-0.log)
[pmsg-ramoops-0.log](https://github.com/sonyxperiadev/bug_tracker/files/4300464/pmsg-ramoops-0.log)

I saw in the dmesg-ramoops-0.log a loop of wlan error messages.
(It would be too long to be copy pasted into this issue ticket)

**Comment by ix5** [comment]
Is this still occurring? If else, please close.
