### ISSUE TITLE
Outdated UART guide

### ISSUE THREAD

**Issue by Gouster4** [sonyxperiadev/bug_tracker#560]
Hello. I was searching for uart location and pinout for XZ and XZ2.
Found this guide: https://developer.sony.com/develop/open-devices/guides/access-uart-ports/
But its outdated. Its just for Z series and XA2.

Is there planned any guide update?

**Comment by jerpelea** [comment]
the new phones use the same connector
we will update the guide as soon

**Comment by jerpelea** [comment]
The new devices use different UART connector that will be disclosed at a later time

**Comment by jerpelea** [comment]
The pinout is the same but I cant remember if the location is the same.
it is easy to look for the connector on the board.

**Comment by bartcubbins** [comment]
@rhjdvsgsgks XZP/XZ1 has UART pins directly on the board, the pinout for Z3 is more suitable for you

**Comment by jerpelea** [comment]
I will try to do it but will take some time

Best regards
Alin
