### ISSUE TITLE
Xperia 5 loud noise on recorded video in quiet enviroment

### ISSUE THREAD

**Issue by WolfEyeX** [sonyxperiadev/bug_tracker#561]
**Platform:** Kumano
**Device:** Xperia 5 ......................... Bahamut
**Kernel version:** 
**Android version:** Android 10
**Software binaries version:** 

**Previously working on**

**It was always a problem**

Has this always been a problem, or is it a new issue?

**Description**
Hello, I'm writing here because maybe someone will report the problem to someone responsible for Xperia Software :). I've the newest software with securiy update for march 2020. I have Xperia 5. My phone was on warranty repair. But from the first day I've bought the phone the problem was still occure. What is the problem? On videos recorded in quiet enviroment there is a lot of loud noice like the video was recorded in some factory. The noise is linear and none of warranty repair and none of software repair and none of the software updates didn't repair that. Other users have the same issue because i was talking to few people on forums.

 This bug is on default camera app and also on cinema pro app. The problems are also on third party apps. In some apps noise is even more disturbing and sounds like trrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr, instantly farting video.....

I'm sending sorry video from default camera app. It was totally quiet in my room - [https://drive.google.com/open?id=1HrLSljRbgzBuP9IF-2nk2H68x2RlkB8e](url)

**Symptoms**
Write the symptoms here.

While recording video in quiet enviroment

**How to reproduce**
Write how to reproduce here.

Record a video in quiet enviroment

**Additional context**
Add any other context, e.g. upload logs or screenshots about the bug here.

**Comment by jerpelea** [comment]
I am sorry but this bug is refering to another project
