### ISSUE TITLE
Whole Xperiassecurity problem - "find your phone" function

### ISSUE THREAD

**Issue by WolfEyeX** [sonyxperiadev/bug_tracker#562]
**Platform:** 
**Device:** 
**Kernel version:** 
**Android version:** 
**Software binaries version:** 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Ok I don't know where to report this so I put it here. I want to report missing an important important feature and lack of security tools - it's about "find your phone" function. When someone would take my locked phone (I use fingerprint and PIN code) he can easily turn off wifi and mobile data transfer and he can easily turn off the phone - in that case function "find my phone" is not usable. For example Samsung did it much better - when you lock your phone and if you want to turn off the wifi or mobile data transfer you need to put the PIN code, the same if someone would like to turn off the phone. So you have plently of time to track or erase your phone - if you have samsung. But you can't do that on most android phones because till now functionality is lack of additional functions.

I think it's very important function which should ba basic function to protect our phones or data and for now is totaly not usable. - Please report that to someone.

**Describe alternatives you've considered**

**Additional context**

**Comment by jerpelea** [comment]
I am sorry but this issue is not releated to this project
