### ISSUE TITLE
Lets translate Extended Settings

### ISSUE THREAD

**Issue by Gouster4** [sonyxperiadev/bug_tracker#565]
Extended Settings are displayed in english language even if my system is set to different language.
I translated it to my language , and i hope that other people here can do same thing for theyr languages.

original values-(language)/strings.xml
https://github.com/sonyxperiadev/packages_apps_ExtendedSettings/tree/master/res

sk (Slovak)
https://github.com/Gouster4/packages_apps_ExtendedSettings/blob/master/res/values-sk/strings.xml

**Comment by ix5** [comment]
But why did you create an issue here? If you know any people that speak the missing languages, just ask them to contribute, or send you the strings for you to format them correclty...

Can be closed in favour of https://github.com/sonyxperiadev/packages_apps_ExtendedSettings/pull/58

**Comment by ix5** [comment]
Please close this @Gouster4, the fix has been submitted already.

**Comment by Gouster4** [comment]
Sorry
