### ISSUE TITLE
[Tama\Tone] Emergency call is broken

### ISSUE THREAD

**Issue by sjllls** [sonyxperiadev/bug_tracker#566]
**Platform:**  Tone
**Device:**  dora
**Kernel version:** 4.9 
**Android version:**  9.0
**Software binaries version:** V9

**Platform:**  Tama
**Device:**  akari
**Kernel version:** 4.14 
**Android version:**  10.0
**Software binaries version:** V5

**Description**
This a serious problem, I'm not joking. Emergency call is broken in some( Maybe all ?) countries.
I tested it on dora (SODP) in China.
MartinX3 tested it on akari(SODP) in Germany.

**Symptoms**
 Emergency call should be fine even without SIM card. But after we tested we found it is broken with/without SIM card.

**How to reproduce**
On my XZ2 (52.1.A.0.618), I called 911 **Without** sim card, it connect to robot and tell me to call 110.
 Emergency call is fine without SIM card.

On my dora( SODP ), **Without** sim card, the phone cannot be connected to 110/120/119/911. it show "no mobile network".

MartinX3 tested akari(SODP) **With** SIM card on lock screen in Germany. 
Result:
110 (police) -> no emergency number
112 (firefighter and ambulance) -> please insert valid simcard
991 (both) -> please insert valid simcard

Imagine if you went to a war zone, You're surrounded by terrorists, they took your phone, but you are very lucky,you had two phones. you still have a nice Xperia phone run on SODP in bag.  After the terrorists leave, you calm down and call 911. You may find that your mobile phone is unable to make emergency calls...

**Comment by kholk** [comment]
This is... sick..........est.

Can you please post some logs? At least we have something to start with.
Thanks!

**Comment by sjllls** [comment]
> This is... sick..........est.
> 
> Can you please post some logs? At least we have something to start with.
> Thanks!

@kholk  Log is here. Thank you! 
Tested without Sim card, our country allows emergency call without sim, from log we can see AOSP recognized our area code. I tried 110/911/119/120.
BTW, I can't tested with sim card, or police would arrest me. XD
[pioneer-emg_call.txt](https://github.com/sonyxperiadev/bug_tracker/files/4602816/pioneer-emg_call.txt)

**Comment by kholk** [comment]
That's actually the reason why noone really tested this... Calling emergency services without a reason is forbidden everywhere around the world :p

**Comment by sjllls** [comment]
Close this issue, Emergency call is fine with a sim card plug in, even without singnal, but you must plug-in a card!

So DON'T forget insert a sim card when you go to Afghanistan and Iraq.

**Comment by MartinX3** [comment]
@sjllls in Europe oust must work without a sim card.

**Comment by sjllls** [comment]
> @sjllls in europe it needs to work without a sim card.

Oh, damn, open it again.

**Comment by jerpelea** [comment]
Discontinued Android version
