### ISSUE TITLE
Dynamic vibration

### ISSUE THREAD

**Issue by Gouster4** [sonyxperiadev/bug_tracker#567]
Is it possible to implement dynamic vibrations to supported devices (like xz2)?
That feature which vibrates phone based on audio playback.

Even if trought extended settings.

**Comment by MarijnS95** [comment]
@Gouster4 It is definitely possible, just a matter of how much time we have left over. The system in itself isn't all too complex, just bloated which requires a bit of careful investigation and coding. I have this on my list and already looked into it a little, but deemed it not worth the little time I had at that moment to really focus and finish it.

**Comment by jerpelea** [comment]
unfortunately there is no time for this feature
