### ISSUE TITLE
Dora macaddress not set up ok in Android 10 with android 9 binaries

### ISSUE THREAD

**Issue by ext32** [sonyxperiadev/bug_tracker#568]
Testing with android 9 , everything fine.\
Wifi Mac address set up with sony vendor mac.
Upgrade to android 10 without flashing 10 binaries,mac address came up correctly on boot.
The time that wifi tries to connect mac address change to murata mac.

Any help to solve this is highly appreciated.
Thanx

**Comment by mehakimz** [comment]
As I can see your device use new brcmfmac as WiFi driver like loire platform.
You have to change the [WiFi MAC address old path](https://github.com/sonyxperiadev/device-sony-tone/blob/870722ccb6b46725ef7885a6a0fbc9b45754686b/platform.mk#L168) to new one. yours is on pcie bus and [here](https://github.com/sonyxperiadev/device-sony-tone/blob/870722ccb6b46725ef7885a6a0fbc9b45754686b/sepolicy_platform/genfs_contexts#L1).

**Comment by ext32** [comment]
Everything setup like this.
The problem is that the device gets the correct mac on first boot.
If you never try to connect to wifi,the wifi remains proper.
After the first connection attempt to wifi mac address change to the a4 famiy.
I will do some experiments with paths and sepolicy .
If someone has any idea why this happen or can point me to the correct direction, i will be gratefull

**Comment by ext32** [comment]
few dmesg outpout

 5.795875] ueventd: firmware: loading 'brcm/brcmfmac4359-pcie.bin' for '/devices/platform/soc/600000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/firmware/brcm!brcmfmac4359-pcie.bin'
[    5.816332] ueventd: loading /devices/platform/soc/600000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/firmware/brcm!brcmfmac4359-pcie.bin took 20ms
[    6.178878] ueventd: firmware: loading 'brcm/brcmfmac4359-pcie.somc,dora-row.txt' for '/devices/platform/soc/600000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/firmware/brcm!brcmfmac4359-pcie.somc,dora-row.txt'
[    7.642753] init: processing action (post-fs-data) from (/vendor/etc/init/macaddrsetup.rc:1)
[    7.792817] ueventd: firmware: could not find firmware for brcm/brcmfmac4359-pcie.somc,dora-row.txt
[    7.793565] ueventd: loading /devices/platform/soc/600000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/firmware/brcm!brcmfmac4359-pcie.somc,dora-row.txt took 1616ms
[    7.804266] ueventd: firmware: loading 'brcm/brcmfmac4359-pcie.txt' for '/devices/platform/soc/600000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/firmware/brcm!brcmfmac4359-pcie.txt'
[    7.811624] ueventd: loading /devices/platform/soc/600000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/firmware/brcm!brcmfmac4359-pcie.txt took 5ms
[   11.784747] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac4359-pcie for chip BCM43596/0
[   11.797586] ueventd: firmware: loading 'brcm/brcmfmac4359-pcie.clm_blob' for '/devices/platform/soc/600000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/firmware/brcm!brcmfmac4359-pcie.clm_blob'
[   11.798164] ueventd: firmware: could not find firmware for brcm/brcmfmac4359-pcie.clm_blob
[   11.798398] ueventd: loading /devices/platform/soc/600000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/firmware/brcm!brcmfmac4359-pcie.clm_blob took 1ms
[   11.798431] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-11), device may have limited channels available
[   11.798988] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43596/0 wl0: Mar 24 2017 13:21:29 version 9.75.119.15 (r691661) FWID 01-a0d2ee7a
[   19.412214] init: processing action (post-fs-data) from (/vendor/etc/init/macaddrsetup.rc:1)
[   19.650356] init: starting service 'macaddrsetup'...

**Comment by oshmoun** [comment]
that might actually be intended. Android 10 enables mac randomization iirc

**Comment by ext32** [comment]
first i have disabled mac randomization with an overlay
second if that was the issue i should have a different mac address every time i try to connect to wifi
i get always the same which is not the sony one

**Comment by ix5** [comment]
Your report is almost incomprehensible as of now.
Please fill out the [Issue Template](https://github.com/sonyxperiadev/bug_tracker/blob/ea9c12b9a26ef476cbe1941fa4e100cca77a480a/.github/ISSUE_TEMPLATE/bug_report.md) the next time you open a bug. It's ok if English is not your first language, but you don't have to make it even harder for everyone.

---


Please post a full logcat & dmesg. Snippets are almost always too little information.

> After the first connection attempt to wifi mac address change to the a4 famiy.

What do you mean by that? Where are you getting the MAC address from? The UI? And what do you mean by `a4 family`? Could you please post both addresses?

Here are a few pointers that might affect Wi-Fi related things:
- `ro.vendor.wifi.addr_path`
- SELinux status (it should be in permissive by default, please keep it in permissive to exclude missing permissions as a reason for the failure)
- Wi-Fi overlay changes: `config_wifi_softap_acs_supported`, `config_wifi_softap_acs_supported_channel_list`, `config_wifi_connected_mac_randomization_supported`. As far as I can tell, `config_wifi_connected_mac_randomization_supported` is not enabled for SODP.
- `WIFI_HIDL_FEATURE_DUAL_INTERFACE` might mess up things with the old ´brcmfmac` driver
- Try setting `WIFI_HIDL_FEATURE_DISABLE_AP_MAC_RANDOMIZATION` to false as instructed in the Android docs

**Comment by ext32** [comment]
Device : Dora  
Android Version : ten  
Kernel Version : 4.9.221 Software 
Binaries : Android 9 latest
Its a new issue on Android 10
Description: Wifi Mac address not setup correctly .Sony devices has two mac addresses ,The sony one and the fake one.Device use the fake one and not the sony one.The very first time the device boots(e,g after format) the mac address the operating system use is the sony mac address.If u leave the wifi alone(e.g not trying to connect to some wifi network) , the operating system still use the sony one mac address).
If you try to connect to some wifi , mac address change to the fake one mac address and the issue persists even after a reboot or shutdown .
Issue is not related to mac address randomization,because the new mac address is always the same,its not even related to mac oui attached to randomized mac addresses.
Its more likely a permission issue or even more a firmware issue.
Please see attached logcat and dmesg files of a new device after formatting it , flashing it with latest aosp legacy for dora, without any customization.
[dmesg.txt](https://github.com/sonyxperiadev/bug_tracker/files/4614359/dmesg.txt)
[logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/4614360/logcat.txt)

**Comment by ix5** [comment]
Good job filling out the template. The logs certainly are helpful.

I asked you to provide the addresses, because I only see this in the logs:
`WifiClientModeImpl: Connecting with a4:08:ea:[censored] as the mac address`
Is that the "real" or fake one?

And please give me `/sys/devices/platform/soc/soc:bcmdhd_wlan/macaddr`.

Did you try `WIFI_HIDL_FEATURE_DISABLE_AP_MAC_RANDOMIZATION` ?

**Comment by ext32** [comment]
the a4 is the fake one,the sony is the 9c:5c.

i have put in device/common/CommonConfig.mk the following line :
WIFI_HIDL_FEATURE_DISABLE_AP_MAC_RANDOMIZATION  := false
after the line 
WIFI_HIDL_FEATURE_DUAL_INTERFACE := false
I think it should be ok

dora:/ # cat /sys/devices/platform/soc/soc:bcmdhd_wlan/macaddr
cat: /sys/devices/platform/soc/soc:bcmdhd_wlan/macaddr: No such file or directory

maybe this is the problem?

**Comment by oshmoun** [comment]
did the tone platform also switch to brcmfmac? that would explain why that path does not exist.
it's probable this is failing somehow https://github.com/sonyxperiadev/macaddrsetup/blob/master/macaddrsetup.c#L140

**Comment by ix5** [comment]
Please give this a try. Verify the changed sysfs nodes are correct.
[device-sony-tone: Change remaining bcmdhd refs to brcmfmac](https://github.com/sonyxperiadev/device-sony-tone/pull/195)

**Comment by ext32** [comment]
tried it.
Still fake mac address.
I will try to format system partition just in case there is a change.

**Comment by ix5** [comment]
Well, starting over cleanly is always a good idea when debugging.
But I'd still like to know whether the sysfs nodes are actually correct. I'll try to verify on my own device later.

**Comment by ext32** [comment]
Formatting boot.recovery,system,userdata,cache and oem partitions.
Flashing boot recovery system and oem .
Reboot device,
[dmesg.txt](https://github.com/sonyxperiadev/bug_tracker/files/4626527/dmesg.txt)
[logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/4626529/logcat.txt)

**Comment by ext32** [comment]
I noticed this in dmesg.txt 
[   34.427994] init: Service 'macaddrsetup' (pid 910) exited with status 0
Is this normal?

**Comment by oshmoun** [comment]
that indicates successful execution.
can you check `ifconfig` and see which mac address is shown there for the wifi interface?

**Comment by oshmoun** [comment]
well I have no clue what could be changing your mac address like that, since you are clearly able to set it manually, but then it gets changed anyway.

**Comment by ix5** [comment]
I added some logging and it turns out that `macaddrsetup` indeed gets the correct MAC address from TA, `9c:5c:f9[...]` in my case.
After I turn Wi-Fi on, it switches to `d8:c4:6a[...]` as visible in settings.

There is no sysfs node for the address with the `brcmfmac` driver, as obi has pointed out.

@ext32 you can use single backticks ` or triple backticks ``` in your markdown so that people can read your comments better, see https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by ix5** [comment]
I've added some logging for you to confirm https://github.com/ix5/macaddrsetup/tree/fmac-log

**Comment by oshmoun** [comment]
so here's something interesting, though not sure if in any way relevant, but both your "fake" addresses have OUIs that belong to the same manufacturer.

**Comment by ext32** [comment]
i have another dora device with real mac address started from 84:.
Same issue happen,so i dont think is relevant to mac oui vendor.

**Comment by ext32** [comment]
After the tests ix5 posted and tested in his device too , the conclusion is that initially the macaddrsetup service set the wifi mac address up correctly,but after the first connection attempt to a saved or new wifi network , something change it back to a non sony(fake as non vendor) mac address.
It is definitely a bug somewhere but still i can't find what changing the mac address.
Should i close and reopen an issue with different title more related to the issue or leave it open for reference;

**Comment by ext32** [comment]
There is a long time without news about this issue.Does someone know a way to fix this or even better debug it more effeciently?
