### ISSUE TITLE
[4.14][4.9?] [Tama (and probably all new platforms as well)] Improving camera's shutter speed

### ISSUE THREAD

**Issue by Gray47Maxx** [sonyxperiadev/bug_tracker#570]
**Platform:** tone (confirmed), kumano/ganges (not confirmed)
**Device:** Apollo (confirmed)
**Kernel version:** 4.14 (but also presented on 4.9, OEM related)
**Android version:** 10 (also 9)
**Software binaries version:** v5 and all versions before it

So, since the Tama devices and all above them using the new camera framework, it's not been pushed to the limits _yet_. This feature request is to make us one step closer to getting the max from our hardware. 

Currently our framework is limited to 1/9s, which is significantly less than stock has (1s in manual mode in Sony camera app and 1/2s in OpenCamera (because of a crippled C2API implementation in stock?)), so that's one of the crucial things that needs to be fixed in the first place to improve the performance of the camera.

It's important (more manual controls == more good shots), but it's definitely not urgent though.

**Comment by der-lange** [comment]
device: XZ2c-dualsim (H8324)
OS: lineage-17.1-20200511-UNOFFICIAL-apollo_RoW
SW: v6-binaries,dual-sim,microg,magisk,camera2-api
cam-app: FreeDCam
problem: focussing
tested: standard-mode and enabled focuspeak (zoom-factor: 8, distance: about 3m)
result: focuspeak working nearly perfect!

photo shot with focuspeak: 
![2020_05_25_12_27_09](https://user-images.githubusercontent.com/66067519/83230714-88266d80-a18a-11ea-8440-33885fc0f300.jpg)

logfile: 1. photo (standard), 2. photo (focuspeak)
logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/4700057/logcat.txt)

**Comment by sraase** [comment]
Open Devices only provides basic camera functionality, so limitations are expected. That being said, specific issues can be looked into, and if they are reasonably easy to implement, they may happen. However, a generic "please support more functionality" is beyond my capabilities.

@Gray47Maxx: What specifically are you looking at? Extending the exposure time on Tama's IMX400 is tricky.

@der-lange: I don't understand. Also, your comment seems to be about a different topic.

**Comment by Gray47Maxx** [comment]
@sraase 
> _What specifically are you looking at? Extending the exposure time on Tama's IMX400 is tricky._
Yep, I'm actually looking for extending the exposure time, as it's a standart-ish thing among any 2017+ smartphone with manual controls over cam's behaviour and _it'd be nice_ to have it. But, again, it's purely a suggestion I (and any other photography enthusiast out there) would benefit from and it's not critical for the project in general. So, I guess it's up to you now to consider implementing it or not.

**Comment by sraase** [comment]
After taking a small look, I can confirm that the exposure time in OpenCamera is indeed limited. However, it is not limited by the sensor driver and manually setting the sensor exposure time seems possible using vendor tags. (If you know what you are doing, they are listed in "dumpsys media.camera", as org.quic.camera.manualExposure.*)

That being said, for photography enthusiasts I would not recommend the Open Devices implementation due to its extremely limited image tuning. For example, I just noticed that even the ISO values shown are probably somewhat incorrect. I don't know much about photography, so I wouldn't know the difference.

**Comment by Gray47Maxx** [comment]
> That being said, for photography enthusiasts I would not recommend the Open Devices implementation due to its extremely limited image tuning. For example, I just noticed that even the ISO values shown are probably somewhat incorrect.

The thing is... since SODP gives us alternative set of binaries to work with our hardware (especially our cam sensors), it is the only way for anyone with 2016-2019 Sony phones to get RAW support on their devices, and that's a great benefit to have (since raw image file basically contains minimally processed data from the sensor itself, allowing us to manually reduce the noise, do white balance, sharpen etc). Even though it's limited, it gives us more freedom in terms of photo editing. 

So, we can live with some minor problems (like noise from incorrect ISO values, that can be easily fixed using any semiprofessional "raw developer" like darktable or RawTherapee), but having a manual control over critical hardware things like shutter speed or focus is definitely more important for us.

**Comment by sraase** [comment]
I've looked some more into this, and I don't know know a good solution.

The exposure time range is available in the android.sensor.info.exposureTimeRange tag. This tag does not consider sensor modes; it shows the guaranteed range across all modes. If I remember correctly, the driver supports three different sensor modes: full resolution (low fps), FullHD (regular fps) and HD (high-speed). I did some testing on a different sensor and it appears that removing support for high-speed modes extends the legal exposure time (in my test case, from 0.15s to 0.57s).

If my analysis is correct, then it is not possible to have longer exposures without sacrificing high-speed video, changes to the camera framework, or a vendor-specific extension. Neither of those options look appealing.

I am open for ideas.

**Comment by Gray47Maxx** [comment]
Just curious: can't we add a switch to ExtendedSettings to, uh, "choose" between high speed video and longer exposure time? It seems like the only solution available for both photographers and videographers out there (but I don't think video guys/gals would benefit from it since they don't have that much freedom in editing raws)

**Comment by sraase** [comment]
Nope. Changing the drivers at runtime is not an option.

**Comment by Gray47Maxx** [comment]
Well, I am also out of ideas then. And I also can't say for everyone which way we should choose and what we should sacrifice in this situation. 

If anyone else has any other ideas or suggestions about what we can do - this issue is a great way to discuss this, I think.

P.S. Ironically, I knew a guy that wanted to make 60FPS/1080P videos on loire but never actually used it until he moved to smth else.

**Comment by sraase** [comment]
According to https://stackoverflow.com/a/32896927, long exposures require vendor extensions. From what I can tell, vendor tags are already there - but obviously third-party apps support that. We can't implement long exposures in a standard way.
