### ISSUE TITLE
[4.14][10.0][maple] Build result not containing vbmeta.img and dtbo.img

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [sonyxperiadev/bug_tracker#571]
**Platform:** Yoshino
**Device:** maple (g8142)
**Kernel version:** 4.14
**Android version:** android-10.0.0_r33
**Software binaries version:** 10.0.7.1_r1_v6

**Previously working on**
Never got a working build that can normal boot.

**Symptoms**
Xperia XZ Premium Dual  
The build result, `out/target/product/maple/`   
folder doesn't generating `dtbo.img` and `vbmeta.img`.

**How to reproduce**
```
mkdir ~/android
cd ~/android
repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r33

cd .repo
git clone https://github.com/sonyxperiadev/local_manifests
cd local_manifests
git checkout android-10.0.0_r33
cd ~/android

repo sync
./repo_update.sh

source build/envsetup.sh && lunch

# Choose "aosp_g8142-userdebug"

make -j4
```
The build is success however, no `dtbo.img` and `vbmeta.img` in  
`out/target/product/maple/` folder.
Just flash the `boot.img`, `recovery.img`, `system.img`, `userdata.img`, `cache.img`  
result in device not booting. No Android boot animation shows  
and just black screen after SONY logo.

The Andoird 9.0 r46 and msm4.9 build also success, but can boot.  
`dtbo.img` and `vbmeta.img` **still not present**, but can boot by  
flashing device official ROM first, which is  
`G8142_Customized US_1308-6041_47.2.A.10.107_R3C)`

I believe these two are required because https://github.com/sonyxperiadev/bug_tracker/issues/491

**Comment by Paulbouchara** [comment]
The xz premium only needs system, boot and oem to boot
You can flash userdata to wipe the data partition... And that's all

Ah also, the reason you see a black screen is because of a kernel issue and not because you don't have dtbo or vbmeta on the build

**Comment by mhtvsSFrpHdE** [comment]
@Paulbouchara So right now I should just stay at Android 9 Pie and not going to 10?  
It is very confusing that **"Which version or branch can actually run"**.

I've compiled **six different branch** and non of them boot successfully.  
That was **a vast amount of time-wasting**.  
Last night I compiled Android 9 r46 it can boot but I chose the build type wrongly.  
Perhaps `userdebug`, and I did `eng`.  
So now I'm going back to Android 9 r46 and build again.

Could we provide some helpful information something like  
**"This combination are confirmed to run(recently tested)":**
`Android 9 r46 + msm4.9 + SW_binaries_Android_9.0_2.3.2_v9_yoshino`

So we can know, oh, my device is messed up, it won't run Android 10 right now.  
Without to compile it and getting frustrated.

**Comment by Paulbouchara** [comment]
The best combo is indeed Android 9 + msm4.9 + oem 2.3.2_v9

You can use kernel 4.9 on Android 10 with Android 9 oem (because it's suited for 4.9) check @ix5 git and his branches/documentation

Or 3rd solution, you can try to help us fixing yoshino if you have kernel working fine and cutting some debug time for us !

Cheers

**Comment by mhtvsSFrpHdE** [comment]
@Paulbouchara I go for his git but not pretty sure where are the documentation.  
These repository often come with a simple readme.md says it suite for some devices,  
and magic.  
I wish to have some... more specific like...

As far as I remember, the way to tell repo tool to download which version kernel is  
`.repo/local_manifests/`, `cd` into that directory then `git checkout android-9.0.0_r46`

This will download and use `msm4.9`. So I init repo with `android-10.0.0_r33`  
and checkout `local_manifests` with `android-9.0.0_r46`?

Sounds it makes sense.

**Comment by Paulbouchara** [comment]
You have a nice android-10_legacy branch for local manifest for that stuff, you would have to fix a few things but that's not very complicated

**Comment by mhtvsSFrpHdE** [comment]
@Paulbouchara I see that! Thank you!  
Back after few hours, that old guy compiles not very fast.

**Comment by Paulbouchara** [comment]
The compile time only depends on your machine specs, on my TR machine it compiles in 40 minutes from clean, where on my laptop it takes.... 9 hours ;)

**Comment by mhtvsSFrpHdE** [comment]
@Paulbouchara It reports that this combination has missing dependencies.  
`repo Android 10 r33 + local_manifests git checkout android-10_legacy`

By doing a `cd` into  `kernel/sony/msm-4.9/common-kernel/` and  
`./build-kernels-clang.sh`, the error is still there.

```
FAILED: ninja: 'out/target/product/maple/kernel', needed by 'out/target/product/maple/boot.img', missing and no known rule to make it
08:18:22 ninja failed with: exit status 1

#### failed to build some targets (10:57 (mm:ss)) ####
```

**Comment by Paulbouchara** [comment]
Which error you get ? Except that bootimage ?

**Comment by mhtvsSFrpHdE** [comment]
@Paulbouchara No, that's the only error produced.

**Comment by ix5** [comment]
Ugh that's because the yoshino devices are *all* set to kernel 4.14
https://github.com/sonyxperiadev/device-sony-yoshino/blob/d74371210c62735a4f8a449f7c4736ee2c372f13/platform.mk#L19

@mhtvsSFrpHdE you need to monkey-patch that line for maple, sadly, or else the 4.14 prebuilt kernel will be picked up.

I don't know what else is required to keep yoshino on 4.9, you might take a look at @stefanhh0 and his work https://github.com/stefanhh0/aosp-10

And I agree with you that it's a massive documentation failure right now, it's totally unclear what versions are expected to build. I hope the website team can clear this mess up soon.

**Comment by stefanhh0** [comment]
Hey @mhtvsSFrpHdE, I have just updated several things on https://github.com/stefanhh0/aosp-10, also added some documentation. Hope that helps.

Best regards,
Stefan

**Comment by mhtvsSFrpHdE** [comment]
@stefanhh0 I'm moving on, thank you!
