### ISSUE TITLE
All about fail to get AOSP running on Xperia XZ Premium

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [sonyxperiadev/bug_tracker#573]
**Platform:** Yoshino
**Device:** maple (g8142)
**Kernel version:** 4.9
**Android version:** android-10.0.0_r33(Legacy)
**Software binaries version:** 9.0_2.3.2_v9_yoshino

**Is your feature request related to a problem? Please describe.**
https://github.com/sonyxperiadev/bug_tracker/issues/571  
https://github.com/sonyxperiadev/bug_tracker/issues/536  
https://github.com/sonyxperiadev/bug_tracker/issues/533

These three are the days all I'm ever meet.  
The thing is pretty simple when I first time ever heard about **SONY OPEN DEVICE**  
Make me thought that is a device as friendly as **Google Nexus/Pixel** for us.  
I have Nexus 4 and Nexus 5X before, I know the kind of feeling,  
just grab the Android source and `source build/envsetup.sh && lunch`, then whoa!  
But **SADLY NO**.

As you can see the Android 9 Pie is already at the end of the lifecycle,  
and we're moving to 10.  
EVEN AT THE TIME, SONY's AOSP Android 9 implementation **can't use Wi-Fi**.

**ARE YOU SERIOUSLY???**  
Hey, you see, I've already submitted, I give up to get 10 on my "legacy" device,  
OK? But the Android 9, man, the latest official SONY system does update to Android 9,  
I don't say those DRM-feature and Super Camera Algorithm are erased after unlock,  
I mean, they are erased after unlock and not just disabled if you're not using official ROM.

I CAN ACCEPT THAT, ALL OF THAT PAINS.

But what do I get in finally? A bootable, running AOSP 9, not even 10 you see!  
But for unknown reasons, Wi-Fi not works on the device. Thus, unusable.  
Let's make clear, certainly, I will not get a refund in my local store and SONY policy,  
with an "unlocked" device.

Luckily there is something called "Pixel experience" open source project,  
that brings the latest AOSP-near system to Xperia XZ Premium.  
I have to rely on people in the open-source community, instead of the one  
who writing something like **OPEN DEVICE** on their website.  
I'm worring about when next Android release come,  
once "Pixel experience" will not keep supporting maple, it's dead.  
Can I say this is telling lies? No, because of the source code just out there,  
but seems far away from the out-of-box.  
The "Pixel experience" team does make the Wi-Fi useable with Android 10,  
The nine ROM I build from source code just can't use Wi-Fi.  
Most of them not booting at all.

https://github.com/stefanhh0/aosp-10  
stefanhh0's aosp-10 use 4.9 kernel are also can't turn on Wi-Fi.

I'm tired, I need to go back to my normal life and rethink my life decision for a while.

**Describe the solution you'd like**
AOSP 9 or 10 support for SONY Xperia XZ Premium, with working
Wi-Fi, Camera, fingerprint, NFC, Android Beam wireless file transfer

Should be able to compile directly from source, like the description on website,  
clean and sharp.

**Describe alternatives you've considered**
Android Project Treble, this new mechanism allow us to install  
compiled binary ROM directly from Google,  
so compile will not a nightmare anymore.  

Another good is with treble, can get system update from Google directly,  
without to wait a monkey-patch for specified device.

The Nexus 4, a 2011 smartphone bundle with 4.0.3,  
today can run AOSP Android 10 without any problems,  
that was 9 years since that, you won't see any other Android manufacturers providing  
update service at that long.  
Can SONY be the one? I'm not sure, please add me some confidence.

Compare to this new generation Wi-Fi-less Xperia XZ Premium,  
am I able to say "さいてい"?(笑)

After all I'm not to blame you guys, I can see the device support hard work  
I may just the one go with no luck, selected a bad luck compile combination.  
Thank you, all of you, I love open source.

**Additional context**

**Comment by stefanhh0** [comment]
I am sorry that you had bad days, hopefully it will get better!
 
> Wi-Fi not works on the device

Open a bug report. 

Yes, the overall situation is far from being ideal or perfect. That is live, learn to live with it and if something is no fun to do, but only frustration, leave it behind and do something that is more fun.

This is more a general complaint out of frustration and not a serious enhancement request, while this is understandable and provides feedback for the volunteers involved in this project which has a value by itself, this should nevertheless just be closed.

Cheers
Stefan

**Comment by Paulbouchara** [comment]
Hey there, 

I'm the PixelExperience Maintainer, if I understood correctly, you made a maple build on PE based on A10 with the trees I pushed ?

If that's correct, then how did you had display to check if wifi was working ? Because, at the last time I could try / get user feedback (@PixelExperienceSony on telegram btw) the device displayed a nice black screen.

Also, keep in mind that our team on based on free time people working on that project, there's only a small team of sony employees working separately from Sony Stock Team.
That means that we have ONE guy doing all the kernel work for : yoshino, nile, ganges, tama, kumano (current dev), tone and loire (mainline work) and upcoming sdm865 platform when it'll come out
And that's a LOT even for a skilled guy that is doing that by passion.

Regarding the Android 9 branch, it is indeed weird that this branch doesn't have the exact same features as we had before, if you have time to give us a lil hand on that, it would be greatly appreciated.

If you have any questions, I'm available on git or on the telegram @ I gave upper.

Cheers

**Comment by Haxk20** [comment]
Hello,

If you could. Could you provide us with logs ?
We are a small team sadly that has a lot of stuff to do.
And we have been slowed down even more then usual with the current world situation.
We are working very hard to get every device working.
Thank you for understanding

**Comment by mhtvsSFrpHdE** [comment]
@Paulbouchara I use this one  
https://forum.xda-developers.com/xz-premium/development/rom-pixel-experience-plus-edition-t4088483

I keep digging it in next few days, it's fun that although this one is AOSP,  
but without Camera2API / RAW capture support.

**Comment by Paulbouchara** [comment]
Hi,
This version is an unofficial one which is not supported by me.

Furthermore, this rom (the unofficial version) is based on stock libraries, which have nothing to do with the sodp project.

Hoping it clears some things in your mind,
Paul

**Comment by mhtvsSFrpHdE** [comment]
> 
> 
> Hi,
> This version is an unofficial one which is not supported by me.
> 
> Furthermore, this rom (the unofficial version) is based on stock libraries, which have nothing to do with the sodp project.
> 
> Hoping it clears some things in your mind,
> Paul

@Paulbouchara Sure that's nothing to do with official PixelExperience!  
For me, that's a method to test things on Android version 10 right now.

I'm looking for how did they fix the Wi-Fi problem.  
It seems the kernel is come from LineageOS,  
now SODP kernel have a Wi-Fi problem,  
but the LineageOS one doesn't.

These in my mind:  
if LineageOS kernel based on SODP kernel(if open source, why not)  
&nbsp;&nbsp;&nbsp;&nbsp;they fixed Wi-Fi problem on SODP kernel  
&nbsp;&nbsp;&nbsp;&nbsp;use that fixed kernel to compile unofficial PixelExperience
but SODP still have a Wi-Fi problem, fantastic

I'm going to:
try use LineageOS kernel to build AOSP, just like they use it to build PixelExperience  
(very likely will be failed for tons of reasons)
keep waiting for next SODP kernel patch to see if Wi-fi can work, or sumbit a issue
grab some book to see if I can get more understand about Android system dev

Before I just use python and javascript to do some lightweight things out there,  
can't really say I'm ready to actually "code" on these things instead of   
just playing with some magical command line commands.

**Comment by Paulbouchara** [comment]
Hey there, the unofficial LineageOS build your tried is NOT based on sodp work and will NOT work with SODP build trees whatsoever.

You'll be just using a stock 4.4 kernel over a 4.14 kernel userspace and that won't work at all.

Furthermore, if you compile the latest sodp kernel, I'm pretty sure the wifi works, which is odd because you don't have it working, could you provide some logs for that ?

I also have some builds based on sodp trees that you could try out and report issues

**Comment by mhtvsSFrpHdE** [comment]
@Paulbouchara So they are different, very different...

The 4.14 kernel are run across many devices,  
in my case (Xperia XZ Premium/maple/G8142) can't boot right now,  
so I need to back and looking for 4.9.  
That's may be why I'm not getting the latest patch.

Other information  
When I doing my compile, that was

- Android 9 r46 with SW_binaries 9.0_2.3.2_v9_yoshino and kernel 4.9
- Android 10 r33 with SW_binaries 10.0.7.1_r1_v4c_yoshino and kernel 4.9
- Android 10 r33 with SW_binaries 10.0.7.1_r1_v4c_yoshino and kernel 4.14

All SW_binaries downloaded and try flash to device on my computer are  

- 9.0_2.3.2_v9
- 10.0.7.1_r1_v1c
- 10.0.7.1_r1_v4c
- 10.0.7.1_r1_v5a
- 10.0.7.1_r1_v6a

The build date are

- 10r33 kernel 4.14 `2020/05/01`
- 9r46 `2020/05/02`
- 10r33 kernel 4.9 (legacy branch) `2020/05/03`

These build are use guide on this website:
https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-10-0-0

No any 3rd plugin or patch included, just pure type-and-compile.  
It has been 15 days past, it may already fixed in some new commit,  
or my compile combination are bad luck, for example,  
you will choose an Android branch, a local_manifest branch, then a SW_binaries  

Just one failed can lead to the bad results.

I do a compile later to see if I can reproduce same results.  
Or I can zip them together to Google Drive for further digging.  
Android 10+4.14 build are not boot at all,  
9 and 10+4.9 build boot but have Wi-Fi problems.

**Comment by Paulbouchara** [comment]
If you try the latest head of sod for kernel 4.14, ALWAYS take the latest oem release (as time of writing, v6).
The v6 + latest head is still alpha/beta material but it should boot and give you the ability to test few things here and there.

Imma ping @kholk because he's way more knowing what's happening precisely and what works and what doesn't.

**Comment by mhtvsSFrpHdE** [comment]
@Paulbouchara 

https://github.com/sonyxperiadev/bug_tracker/issues/533

> Keep in mind that kernel 4.14 is not fully ready for Yoshino yet. While we're working hard it may still take a couple more days.
> 
> Perhaps you have more luck using kernel 4.9 and Android 9 from the official sonyxperiadev repositories directly.

This says the kernel still require time to work...

https://github.com/sonyxperiadev/bug_tracker/issues/299

> This issue is still present, please reopen

This says it's a "legacy" problem and related issue are closed for unknown reason

> The v6 + latest head is still alpha/beta material but it should boot and give you the ability to test few things here and there.

When the day I build, v6a suddenly available after my compile.  
But my build is based on v5x, I flash v5 first, not work then v6 directly with v5,  
the certain period head of system.  
Didn't  rebuild with the latest head, that may the reason still not booting.

**Comment by Paulbouchara** [comment]
Last 2 weeks have been productive for yoshino and especially maple, so you should definitely try out that

**Comment by MarijnS95** [comment]
> #533
> 
> > Keep in mind that kernel 4.14 is not fully ready for Yoshino yet. While we're working hard it may still take a couple more days.
> > Perhaps you have more luck using kernel 4.9 and Android 9 from the official sonyxperiadev repositories directly.
> 
> This says the kernel still require time to work...

Hmm, February 3, its now May 15th.
 
> #299
> 
> > This issue is still present, please reopen
> 
> This says it's a "legacy" problem and related issue are closed for unknown reason
> 
> > The v6 + latest head is still alpha/beta material but it should boot and give you the ability to test few things here and there.

It's a different "legacy" issue, Loire and Tone use brcmfmac, Yoshino is on qcacld.

**Comment by mhtvsSFrpHdE** [comment]
> 
> 
> Last 2 weeks have been productive for yoshino and especially maple, so you should definitely try out that

@Paulbouchara I feel... DEJAVU!!  
That was Fast a lot than I can ever imagine,  
I was just think that maybe I'll wait for eight months that long or something.

Hopefully one day I can also do that kind of amazing programming instead of just ask help...  
Contributors defineally more love a pull request!

**Comment by mhtvsSFrpHdE** [comment]
@MarijnS95 I often list the two issue together because 533 is for maple,  
but in the post people tells to following 299, that's not maple.  
I can't have more deep understand, but it seems they are finally past.

> kgvarunkanth commented on Mar 10
>
> Closing issue Following #299

**Comment by MarijnS95** [comment]
Right... That shouldn't be the case though, they are likely distinct problems. We'll get it looked after at some point!

**Comment by mhtvsSFrpHdE** [comment]
@Paulbouchara I did a successful build, the current problem is,  
after boot for a while (after showing launcher or unlock screen), 5 second or 60 second later,  
the display will crash and keep black. More time over, every hardware button freeze.

The Wi-Fi did work at that moment. It may be still "work in progress",  
I feel not inappropriate to start a new issue, this look like "Urge/Hasten" and be very rude.

I'll keep waiting for new patch and do weekly build as possible as I can,  
then report new issue if I can feel something new happens.

**Comment by kholk** [comment]
Don't worry, I don't see having an open issue on the bug tracker as being rude in any way, as long as they're not "just a rant", but describing a problem as per the guidelines.

Yoshino is still a work in progress, I've been bashing my head on it for some days and that's the point that we've reached now: there are still a few issues to solve and I hope to be able to get back to that asap.

The sleep crash issues are related to either a power domain going down and never getting back up or a clock going "a lil crazy"... We will see...... :)))

**Comment by stefanhh0** [comment]
> after boot for a while (after showing launcher or unlock screen), 5 second or 60 second later,
the display will crash and keep black. After more time, every hardware button freeze,
it may reboot itself or not in finally.

I can confirm that behavior, there is already an issue open for it: #580:

> Other possibly related symptoms I see with k4.14:
>
> - Waking up the phone from sleep takes sometimes quite some time, I have to push the button several times to get the display up, sometimes I even have to reboot or the phone reboots itself

Not unlikely that the root cause for lilac and maple is the very same.

My workaround is to set the device active in the developer settings, keep the device plugged in and activate screen saver to not let the device fall asleep :-)

**Comment by mhtvsSFrpHdE** [comment]
`SW_binaries_for_Xperia_Android_10.0.7.1_r1_v7a_yoshino` are released!

After my weekly build, it seems everything work and stable in the first impression  
Wi-Fi available and no crash! Thank you guys!

**Comment by Paulbouchara** [comment]
Glad you got your device booting correctly 😄
