### ISSUE TITLE
[Pioneer][Nile][10] Can't screen on after screen off

### ISSUE THREAD

**Issue by sjllls** [sonyxperiadev/bug_tracker#575]
**Platform:**  Nile
**Device:**  Pioneer
**Kernel version:** 4.14 (Prebuilt)
**Android version:** 10
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v6a_nile.img

**Previously working on**
Has this always been a problem, or is it a new issue?
New issue,  This problem should not appear on V5.
Clean and new build on 2020.5.5 with latest sources.

**Description**
Can't screen on after screen off

**Symptoms**
We could hear the unlocked sound but screen is still dark, no display.

**How to reproduce**
Build with V6.

**Log**
```
05-04 14:22:11.496     0     0 E i2c-msm-v2 c1b6000.i2c: NACK: slave not responding, ensure its powered: msgs(n:1 cur:0 tx) bc(rx:0 tx:4) mode:FIFO slv_addr:0x28 MSTR_STS:0x0d1300c8 OPER:0x00000090
05-04 14:22:11.497  2787  2787 D DCT-C   : screen off
```

**Additional context**
[dmesg-pioneer-screen.txt](https://github.com/sonyxperiadev/bug_tracker/files/4578327/dmesg-pioneer-screen.txt)
[pioneer-screen.txt](https://github.com/sonyxperiadev/bug_tracker/files/4578331/pioneer-screen.txt)

**Comment by kholk** [comment]
This issue has been solved weeks ago with a kernel patchset.

**Comment by sjllls** [comment]
> This issue has been solved weeks ago with a kernel patchset.

Cool, working!
