### ISSUE TITLE
Broken Tether

### ISSUE THREAD

**Issue by yehonatan2020** [sonyxperiadev/bug_tracker#579]
**Griffin** 
**Kumano** 
**4.14** 
**Android 10** 
**Software binaries v6** 

**Description**
Broken Tether

**Symptoms**
No USB tethering

**How to reproduce**
Upon connecting the USB cable to say a laptop, and trying to select USB tethering option on device, the option just deselects itself. Charging and file transfer both are working though

**Comment by ix5** [comment]
The whole USB configfs/functionfs seems a bit wonky right now, at least on tama and possibly kumano.

We should investigate whether the nodes are still correct.

And what about our old pipe dream, a proper USB HAL, kanged from the Pixels, @MarijnS95 ...

**Comment by MarijnS95** [comment]
@ix5 I have been told to keep the init way as it already exists and "just works™".

The Pixel one seems to be hidden away for no good reason. Google should have moved that to a `default` USB configuration as it uses exclusively standardized USB FFS iirc. Guess we'll never know.

**Comment by MartinX3** [comment]
I can confirm it on tama/akari, too.
[logcat_-b_all.log](https://github.com/sonyxperiadev/bug_tracker/files/4898279/logcat_-b_all.log)

**Comment by stefanhh0** [comment]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14.188-24329-g4a5c50437f7c¹
**Android version:** android-10.0.0_r40
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v9c_yoshino.img
**Version baseband:** 1307-7511_47.2.A.11.228
**Build:** aosp_g8441-userdebug 10 QQ3A.200705.002 eng.stefan.20200707.220459²

**Previously working on**
Didn't try in a long time. Can't say when it was working the last time.
 
**Description**
Also yoshino is affected by this problem. After choosing "USB tethering" from "USB Preferences" it remains some 100ms on the "USB tethering" option before it jumps back to "No data transfer" 

The kernel log looks a little different in what happens in comparison to the one @MartinX3 posted. But some parts are the same (e.g. `E msm-dwc3 a800000.ssusb: ep`).

```
07-11 07:47:53.667     0     0 I init    : processing action (sys.usb.config=none && sys.usb.configfs=1) from (/init.usb.configfs.rc:1)
07-11 07:47:53.668     0     0 I init    : Sending signal 9 to service 'adbd' (pid 26615) process group...
07-11 07:47:53.695     0     0 I libprocessgroup: Successfully killed process cgroup uid 0 pid 26615 in 26ms
07-11 07:47:53.695     0     0 I init    : Service 'adbd' (pid 26615) received signal 9
07-11 07:47:53.699     0     0 I init    : processing action (init.svc.adbd=stopped) from (/init.usb.configfs.rc:14)
07-11 07:47:53.720     0     0 I init    : processing action (sys.usb.config=rndis,adb && sys.usb.configfs=1) from (/init.usb.configfs.rc:131)
07-11 07:47:53.720     0     0 I init    : starting service 'adbd'...
07-11 07:47:53.726     0     0 I init    : Created socket '/dev/socket/adbd', mode 660, user 1000, group 1000
07-11 07:47:53.767     0     0 I         : read descriptors
07-11 07:47:53.767     0     0 I         : read strings
07-11 07:47:53.768     0     0 I init    : processing action (sys.usb.config=rndis,adb && sys.usb.configfs=1 && sys.usb.ffs.ready=1) from (/init.usb.configfs.rc:134)
07-11 07:47:53.769     0     0 I init    : Command 'mkdir /config/usb_gadget/g1/functions/rndis.gs4' action=sys.usb.config=rndis,adb && sys.usb.configfs=1 && sys.usb.ffs.ready=1 (/init.usb.configfs.rc:135) took 0ms and failed: mkdir() failed: Permission denied
07-11 07:47:53.773     0     0 I android_work: sent uevent USB_STATE=DISCONNECTED
07-11 07:47:53.774     0     0 I init    : processing action (sys.usb.config=rndis,adb && sys.usb.configfs=1 && sys.usb.ffs.ready=1) from (/vendor/etc/init/init.usb.rc:109)
07-11 07:47:53.824     0     0 E msm-dwc3 a800000.ssusb: ep [gsi-epin14,29] already configured as msm endpoint
07-11 07:47:53.824     0     0 E msm-dwc3 a800000.ssusb: ep [gsi-epout15,30] already configured as msm endpoint
07-11 07:47:53.835     0     0 I         : RNDIS_IPA NetDev was initialized
07-11 07:47:53.874     0     0 I android_work: did not send uevent (0 0 0000000000000000)
07-11 07:47:53.876     0     0 I init    : Command 'write /config/usb_gadget/g1/UDC ${sys.usb.controller}' action=sys.usb.config=rndis,adb && sys.usb.configfs=1 && sys.usb.ffs.ready=1 (/vendor/etc/init/init.usb.rc:116) took 51ms and succeeded
07-11 07:47:53.929     0     0 E [RMNET:HI] rmnet_config_notify_cb(): Kernel is trying to unregister rndis0
07-11 07:47:53.939     0     0 E [RMNET:HI] rmnet_config_notify_cb(): Kernel is trying to unregister rndis0
07-11 07:47:53.939     0     0 I         : RNDIS_IPA NetDev was cleaned
07-11 07:47:53.940     0     0 I         : read descriptors
07-11 07:47:53.940     0     0 I         : read strings
```

**Additional context**
[kernel.log](https://github.com/sonyxperiadev/bug_tracker/files/4906372/kernel.log)

---
¹) Commit: 8a84f57dd0e5 can't be found on github.
- Base commit is: https://github.com/sonyxperiadev/kernel/commit/573ecd6b8038
- Included PRs: 2303, 2312

²) SELinux: enforcing

**Comment by bartcubbins** [comment]
Better late than never. Please try with this https://github.com/sonyxperiadev/device-sony-common/pull/859, the issue should disappear.
