### ISSUE TITLE
[4.14][10.0][Tama] Battery drain (no deep sleep)

### ISSUE THREAD

**Issue by maricn** [sonyxperiadev/bug_tracker#581]
**Platform:** TAMA
**Device:** Apollo
**Kernel version:** 4.14
**Android version:** 10.0
**Software binaries version:** OEMv6

**Previously working on**
Kernel 4.9 and Android 9

**Description**
The CPU seems to never enter deep sleep. Or at least doesn't stick long enough. 

**Symptoms**
My phone gets drained over night, and also during the day, using it or not, it drains really fast.

**How to reproduce**
Just let it be.

**Additional context**
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/4624880/dmesg.log)
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/4624881/logcat.log)
[logcat_radio.log](https://github.com/sonyxperiadev/bug_tracker/files/4624882/logcat_radio.log)

**Comment by Haxk20** [comment]
Hello. Thank you for the bug report first of all.
Yes we are aware of this issue.

The current situation is about 2-4%/h even when not using it which is very bad but at the moment most of the team is working on different issues
What is happening is that it does sleep. But not even for a whole second. milliseconds.

I have not looked into this issue personally and @MarijnS95 may be able to answer or explain it better then i can.

**Comment by MartinX3** [comment]
Fixed by https://github.com/sonyxperiadev/kernel/pull/2273 @maricn

**Comment by kholk** [comment]
Please close this issue.

**Comment by maricn** [comment]
@kholk I'm cool with any of you maintainers closing the issue. I'm not available to verify the reported issue yet, so don't feel I should be closing it, but if you need me to click that button, sure..

**Comment by kholk** [comment]
I can't click it on my own, otherwise I would've done that... Yeah, please, click it :D
