### ISSUE TITLE
[4.14][10][yoshino][maple]Camera2 API cause system freeze and reboot

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [sonyxperiadev/bug_tracker#586]
**Platform:** yoshino
**Device:** maple
**Kernel version:** 4.14
**Android version:** 10
**Software binaries version:** 10.0.7.1_r1_v7a_yoshino

**Previously working on**
Has this always been a problem, or is it a new issue?

`repo_update.sh` at around 2020/05/27 PM 3:00  

**Description**
When try to take photo in DNG(raw) format, the system will freeze,  
after few seconds it will reboot. After reboot, everything will be fine,  
no other error happens.

Check the gallery, there is no photo saved.

Can take photo in JPG format with no problem.

**Symptoms**
DNG(raw) photo format not available

**How to reproduce**
One of the open source camera app  
https://f-droid.org/repo/net.sourceforge.opencamera_77.apk  
Open it, click on `Settings` -> `Scroll to the bottom` -> `Camera API`  
-> `Camera2 API` -> `Scroll to the top` -> `Photo settings...`  
-> `RAW` -> `DNG (RAW) only`

Then back to photo main interface and  
take any photo to see the system freeze and reboot.

The same camera app can take photo with jpg format and no error.  
(By turn off RAW option)

When import photo to Adobe Lightroom,  
DNG format can provide wider paint creation space  
without expose the jpg compress side effect.

**Additional context**
Add any other context, e.g. upload logs or screenshots about the bug here.

**Comment by mhtvsSFrpHdE** [comment]
Plus, take HDR photo at Maximum resolution(5504x3104 & 17.08 MP) would also  
cause the system to reboot but that's pretty not important.

In fact, any HDR resolution greater than 3840x2160  
would all have chance to trigger a reboot.  
Because in Sony official system, for open camera (a third party),  
the HDR maximum resolution available is 3840x2160.

I prefer to mark this `HDR problem` as `wontfix`,  
nobody will utilize a HDR photo properly at that high resolution.

**Comment by stefanhh0** [comment]
Please provide the required logs as I have described it here:
https://github.com/sonyxperiadev/bug_tracker/issues/587#issuecomment-635074612

**Comment by mhtvsSFrpHdE** [comment]
@stefanhh0 Coronavirus COVID-19 raging, I lost my job due to side effect(Company closures)  
I need to work hard to do something manual labor, 11 hours a day.

I will try to catch the logs after my next build...  
I think is the next software binaries release after `10.0.7.1_r1_v7a_yoshino`

Will be fine, there are tons of N95 masks around me.

**Comment by stefanhh0** [comment]
@mhtvsSFrpHdE I am very sorry to hear that, hope it will get better for you soon!

Kind regards
Stefan

**Comment by Haxk20** [comment]
Can we get report if this is fixed by v7 ?
Lot of issues of camera has been fixed by v7

**Comment by mhtvsSFrpHdE** [comment]
> 
> 
> Can we get report if this is fixed by v7 ?
> Lot of issues of camera has been fixed by v7

@Haxk20 I am using v7, v7a. But the day were 2020/05/27  
(YYYY MM DD time)

Today 2020/06/08  
I just made a weekly build half hour ago, and did the same test,  
it seems now RAW(DNG) format photo can take and save normally with no crash!

Thank you!

Can I know if there is a place to store the update history?  
I mean, what has been fixed these days,   
I then can read the update history and confirm if my issue is fixed and do test,  
finally can close some issue written by me.

**Comment by mhtvsSFrpHdE** [comment]
There are a potential problem... When I shot too many photo at a short period of time the phone still freeze and crash.

The XZP camera hardware may not design to use at that heavy usage, phone is very heat.

**Comment by mhtvsSFrpHdE** [comment]
I always feel the sony AOSP have heat control problem.

This is strange, because can't just grab same thermal profile from official system?  
Or that one is actually "DRM-protected" we can only tune the heat profile via clean room development or something

**Comment by mhtvsSFrpHdE** [comment]
If I have root permission, then I able to use root to manual set maximum CPU clock speed

this can help the device not to run hot. But didn't find a way to get root right now

**Comment by stefanhh0** [comment]
`adb root && adb shell` for that you need a userdebug build.

**Comment by mhtvsSFrpHdE** [comment]
After `SW_binaries_for_Xperia_Android_10.0.7.1_r1_v9c_yoshino`, take RAW photo will not crash the system
