### ISSUE TITLE
[10][4.14][poplar]Error when building aosp image

### ISSUE THREAD

**Issue by yuezhengbaizhi** [sonyxperiadev/bug_tracker#588]
**Platform:** Yoshino
**Device:** Poplar
**Kernel version:**4.14 
**Android version:** 10
**Software binaries version:** 

**Previously working on**
it's a new issue, did not encounter this error when building 5/24/2020

**Description**
when running make, gives me error

FAILED: ninja: 'device/sony/common/hardware/tftp/init.recovery.common.rc', needed by 'out/target/product/poplar/obj/ETC/init.recovery.poplar_intermediates/init.recovery.poplar.rc', missing and no known rule to make it
13:55:28 ninja failed with: exit status 1

#### failed to build some targets (03:07 (mm:ss)) ####
![image](https://user-images.githubusercontent.com/42693943/83176405-632eed80-a0eb-11ea-847b-6a78c975cd19.png)

**How to reproduce**
follow the guide of sodp here: https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-10-0-0#tutorial-step-1 to make the image 

**Additional context**
Add any other context, e.g. upload logs or screenshots about the bug here.

**Comment by rantpalas** [comment]
Sorry to hijack the bug, but same error happens for XZ3: ninja: 'device/sony/common/hardware/tftp/init.recovery.common.rc', needed by 'out/target/product/akatsuki/obj/ETC/init.recovery.akatsuki_intermediates/init.recovery.akatsuki.rc', missing and no known rule to make it
![Screenshot from 2020-05-29 09-18-35](https://user-images.githubusercontent.com/60635362/83227684-72667780-a18d-11ea-9433-d30f3593b655.png)

**Comment by ix5** [comment]
https://github.com/sonyxperiadev/device-sony-common/pull/741

Please pull this in locally until it is merged

Issue can be closed
