### ISSUE TITLE
[maple][kagura] No voice on VoIP audio call

### ISSUE THREAD

**Issue by abioteau** [sonyxperiadev/bug_tracker#59]
**Platform:** Yoshino|Tone
**Device:** Maple|Kagura
**Kernel version:** 4.4 (afabc23)
**Android version:** 7.1.1

**Description**
When I try to make an audio call with Linphone (VoIP application), there is no voice on both side.
It works with Android 8.0 on same devices. It also works on suzu (loire) devices with Android 7.1 and 8.0.
Not tested on others yoshino|tone|loire devices.

**Symptoms**
No voice on both side.

**How to reproduce**
1) Install Linphone (https://play.google.com/store/apps/details?id=org.linphone) and create or configure your Linphone account.
2) Idem on another device with official Sony ROM
3) Make a audio call

**Comment by jerpelea** [comment]
since both android versions use the same kernel and device configuration the only difference is in android 

please check the hardware/qcom/audio for differences

**Comment by abioteau** [comment]
Log during an audio call:

--------- beginning of main
12-14 10:27:06.549   649   934 D audio_hw_primary: disable_audio_route: usecase(1) reset and update mixer path: low-latency-playback
12-14 10:27:06.554   649   934 D hardware_info: hw_info_append_hw_type : device_name = speaker
12-14 10:27:06.556   649   934 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
12-14 10:27:06.816   649   934 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
12-14 10:27:06.818  1077  2730 E rqbalance_halext: Unexpected argument. Bailing out.
12-14 10:27:06.818  1077  2730 D rqbalance_halext: Arguments: 3
12-14 10:27:06.818  1077  2730 D rqbalance_halext: Arg[0]: 0x101
12-14 10:27:06.819  1077  2730 D rqbalance_halext: Arg[1]: 0x20e
12-14 10:27:06.819  1077  2730 D rqbalance_halext: Arg[2]: 0x30e
12-14 10:27:06.820  1077  2730 D rqbalance_halext: Arg[3]: 0xffffffff
12-14 10:27:06.820   649   934 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 15, path = 0, app id = 0x11130, sample rate = 48000
12-14 10:27:06.821   649   934 D ACDB-LOADER: ACDB -> send_asm_topology
12-14 10:27:06.821   649   934 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
12-14 10:27:06.821   649   934 D ACDB-LOADER: ACDB -> send_adm_topology
12-14 10:27:06.822   649   934 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
12-14 10:27:06.822   649   934 D ACDB-LOADER: ACDB -> send_audtable
12-14 10:27:06.822   649   934 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE_SIZE
12-14 10:27:06.823   649   934 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
12-14 10:27:06.823   649   934 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
12-14 10:27:06.824   649   934 D ACDB-LOADER: ACDB -> send_audvoltable
12-14 10:27:06.824   649   934 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
12-14 10:27:06.824   649   934 D ACDB-LOADER: ACDB -> AUDIO_SET_VOL_CAL cal type = 12
12-14 10:27:06.825   649   934 D ACDB-LOADER: ACDB -> send_audstrmtable
12-14 10:27:06.825   649   934 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_V2
12-14 10:27:06.826   649   934 D ACDB-LOADER: ACDB -> audstrm_cal->cal_type.cal_data.cal_size = 40
12-14 10:27:06.827   649   934 D ACDB-LOADER: ACDB -> send_afe_topology
12-14 10:27:06.828   649   934 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_TOPOLOGY_ID
12-14 10:27:06.828   649   934 D ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 15, Topology Id 112fc
12-14 10:27:06.829   649   934 D ACDB-LOADER: ACDB -> send_afe_cal
12-14 10:27:06.829   649   934 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
12-14 10:27:06.830   649   934 D         : Failed to fetch the lookup information of the device 0000000F 
12-14 10:27:06.830   649   934 E ACDB-LOADER: Error: ACDB AFE returned = -19
12-14 10:27:06.831   649   934 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
12-14 10:27:06.831   649   934 D ACDB-LOADER: ACDB -> send_hw_delay : acdb_id = 15 path = 0
12-14 10:27:06.832   649   934 D ACDB-LOADER: ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
12-14 10:27:06.833   649   934 D hardware_info: hw_info_append_hw_type : device_name = speaker
12-14 10:27:06.833   649   934 D audio_hw_primary: enable_snd_device: snd_device(2: speaker)
12-14 10:27:06.846   649   934 D audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback
12-14 10:27:06.900   649  2562 D audio_hw_primary: adev_set_mode: mode 3
12-14 10:27:07.021   649   934 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=1
12-14 10:27:07.027   649   934 D audio_hw_primary: select_devices: changing use case low-latency-playback output device from(2: speaker, acdb 15) to (1: handset, acdb 7)
12-14 10:27:07.029   649   934 D audio_hw_primary: disable_audio_route: usecase(1) reset and update mixer path: low-latency-playback
12-14 10:27:07.106   649   934 D hardware_info: hw_info_append_hw_type : device_name = speaker
12-14 10:27:07.108   649   934 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
12-14 10:27:07.140   649   934 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 7, path = 0, app id = 0x11130, sample rate = 48000
12-14 10:27:07.141   649   934 D ACDB-LOADER: ACDB -> send_asm_topology
12-14 10:27:07.141   649   934 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
12-14 10:27:07.142   649   934 D ACDB-LOADER: ACDB -> send_adm_topology
12-14 10:27:07.143   649   934 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
12-14 10:27:07.143   649   934 D ACDB-LOADER: ACDB -> send_audtable
12-14 10:27:07.144   649   934 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE_SIZE
12-14 10:27:07.145   649   934 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
12-14 10:27:07.147   649   934 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
12-14 10:27:07.147   649   934 D ACDB-LOADER: ACDB -> send_audvoltable
12-14 10:27:07.148   649   934 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
12-14 10:27:07.148   649   934 D ACDB-LOADER: ACDB -> AUDIO_SET_VOL_CAL cal type = 12
12-14 10:27:07.149   649   934 D ACDB-LOADER: ACDB -> send_audstrmtable
12-14 10:27:07.149   649   934 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_V2
12-14 10:27:07.149   649   934 D ACDB-LOADER: ACDB -> audstrm_cal->cal_type.cal_data.cal_size = 40
12-14 10:27:07.150   649   934 D ACDB-LOADER: ACDB -> send_afe_topology
12-14 10:27:07.150   649   934 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_TOPOLOGY_ID
12-14 10:27:07.150   649   934 D ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 7, Topology Id 112fc
12-14 10:27:07.151   649   934 D ACDB-LOADER: ACDB -> send_afe_cal
12-14 10:27:07.151   649   934 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
12-14 10:27:07.152   649   934 D         : Failed to fetch the lookup information of the device 00000007 
12-14 10:27:07.152   649   934 E ACDB-LOADER: Error: ACDB AFE returned = -19
12-14 10:27:07.153   649   934 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
12-14 10:27:07.153   649   934 D ACDB-LOADER: ACDB -> send_hw_delay : acdb_id = 7 path = 0
12-14 10:27:07.154   649   934 D ACDB-LOADER: ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
12-14 10:27:07.154   649   934 D hardware_info: hw_info_append_hw_type : device_name = handset
12-14 10:27:07.154   649   934 D audio_hw_primary: enable_snd_device: snd_device(1: handset)
12-14 10:27:07.160   649   934 D audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback
12-14 10:27:07.263  1077  2042 I MediaFocusControl:  AudioFocus  requestAudioFocus() from uid/pid 10057/2413 clientId=android.media.AudioManager@944d9bb req=2 flags=0x0
--------- beginning of system
12-14 10:27:07.345  1077  2042 I ActivityManager: START u0 {cmp=org.linphone/.CallOutgoingActivity} from uid 10057 on display 0
12-14 10:27:07.369  2413  2413 I Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
12-14 10:27:07.525  1446  1458 I art     : Background partial concurrent mark sweep GC freed 30323(1481KB) AllocSpace objects, 1(24KB) LOS objects, 39% free, 17MB/28MB, paused 856us total 162.593ms
12-14 10:27:07.557  1077  1087 I art     : Background partial concurrent mark sweep GC freed 16302(865KB) AllocSpace objects, 1(20KB) LOS objects, 33% free, 10MB/16MB, paused 11.002ms total 218.224ms
12-14 10:27:07.598  1077  1119 I ActivityManager: Displayed org.linphone/.CallOutgoingActivity: +222ms (total +2m1s881ms)
12-14 10:27:07.767  2413  2418 I art     : Compiler allocated 7MB to compile void com.google.android.gms.internal.zzchj.zzc(com.google.android.gms.internal.zzcfx, com.google.android.gms.internal.zzcff)
12-14 10:27:07.811   611   611 I MSM-irqbalance: Decided to move IRQ3 from CPU4 [P:0] to CPU0 [P:1] (banned)
12-14 10:27:09.098  2413  2413 I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x1 based on channel count of 1)
12-14 10:27:09.101  2413  2413 D AudioTrack: Client defaulted notificationFrames to 240 for frameCount 480
12-14 10:27:09.204   649   942 D audio_hw_primary: out_set_parameters: enter: usecase(5: audio-ull-playback) kvpairs: routing=1
12-14 10:27:09.211  1077  2730 E rqbalance_halext: Unexpected argument. Bailing out.
12-14 10:27:09.213  1077  2730 D rqbalance_halext: Arguments: 3
12-14 10:27:09.214  1077  2730 D rqbalance_halext: Arg[0]: 0x101
12-14 10:27:09.217  1077  2730 D rqbalance_halext: Arg[1]: 0x20e
12-14 10:27:09.224  1077  2730 D rqbalance_halext: Arg[2]: 0x30e
12-14 10:27:09.229  1077  2730 D rqbalance_halext: Arg[3]: 0xffffffff
12-14 10:27:09.231   649   942 D audio_hw_primary: select_devices: changing use case audio-ull-playback output device from(2: speaker, acdb 15) to (1: handset, acdb 7)
12-14 10:27:09.232   649   942 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 7, path = 0, app id = 0x11130, sample rate = 48000
12-14 10:27:09.233   649   942 D ACDB-LOADER: ACDB -> send_asm_topology
12-14 10:27:09.234   649   942 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
12-14 10:27:09.235   649   942 D ACDB-LOADER: ACDB -> send_adm_topology
12-14 10:27:09.236   649   942 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
12-14 10:27:09.236   649   942 D ACDB-LOADER: ACDB -> send_audtable
12-14 10:27:09.237   649   942 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE_SIZE
12-14 10:27:09.238   649   942 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
12-14 10:27:09.238   649   942 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
12-14 10:27:09.239   649   942 D ACDB-LOADER: ACDB -> send_audvoltable
12-14 10:27:09.239   649   942 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
12-14 10:27:09.240   649   942 D ACDB-LOADER: ACDB -> AUDIO_SET_VOL_CAL cal type = 12
12-14 10:27:09.240   649   942 D ACDB-LOADER: ACDB -> send_audstrmtable
12-14 10:27:09.241   649   942 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_V2
12-14 10:27:09.241   649   942 D ACDB-LOADER: ACDB -> audstrm_cal->cal_type.cal_data.cal_size = 40
12-14 10:27:09.241   649   942 D ACDB-LOADER: ACDB -> send_afe_topology
12-14 10:27:09.242   649   942 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_TOPOLOGY_ID
12-14 10:27:09.242   649   942 D ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 7, Topology Id 112fc
12-14 10:27:09.243   649   942 D ACDB-LOADER: ACDB -> send_afe_cal
12-14 10:27:09.243   649   942 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
12-14 10:27:09.243   649   942 D         : Failed to fetch the lookup information of the device 00000007 
12-14 10:27:09.244   649   942 E ACDB-LOADER: Error: ACDB AFE returned = -19
12-14 10:27:09.244   649   942 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
12-14 10:27:09.244   649   942 D ACDB-LOADER: ACDB -> send_hw_delay : acdb_id = 7 path = 0
12-14 10:27:09.245   649   942 D ACDB-LOADER: ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
12-14 10:27:09.245   649   942 D audio_hw_primary: enable_audio_route: usecase(5) apply and update mixer path: audio-ull-playback
12-14 10:27:09.256   649   942 E audio_hw_primary: start_output_stream: pcm_prepare returned -1
12-14 10:27:09.266   649   942 D audio_hw_primary: disable_audio_route: usecase(5) reset and update mixer path: audio-ull-playback

**Comment by jerpelea** [comment]
please retest on vendor v8
i have merged the needed commits

**Comment by abioteau** [comment]
@jerpelea : Should i use O-MR0 vendor v8 for N-MR1 4.4?

**Comment by jerpelea** [comment]
there is a v8 for 7.1

**Comment by Bitti09** [comment]
There are only v8 for 8.0 here https://developer.sony.com/develop/open-devices/downloads/software-binaries/

Last one for 7.1  is  v7 from October'17 

_Sent from my Xperia XZ (AOSP) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Bitti09** [comment]
There are only v8 for 8.0 here https://developer.sony.com/develop/open-devices/downloads/software-binaries/

Last one for 7.1  is  v7 from October'17 

_Sent from my Xperia XZ (AOSP) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by abioteau** [comment]
Hi @jerpelea, when do you expect to deliver v8 for 7.1?

PS: For me, the last one for 7.1 is v5 from October'17

**Comment by jerpelea** [comment]
i will recheck with my coleagues

**Comment by jerpelea** [comment]
unfortunately it was delayed and will be published ASAP

**Comment by jerpelea** [comment]
the bug has been fixed and v8 is released 
https://developer.sony.com/develop/open-devices/get-started/supported-devices-and-functionality/supported-devices-maintained/

**Comment by abioteau** [comment]
It still does not works on 7.1 with vendor v8.

**Comment by jerpelea** [comment]
my coleague is investigating the issue

**Comment by jerpelea** [comment]
the fix has been uploaded 
please test @abioteau

**Comment by abioteau** [comment]
which fix, i do not see anything about audio for 7.1 ?

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/device-sony-tone/commit/ce7c7628a76a87b400a8c24eb4b9a2e973fc0118

**Comment by jerpelea** [comment]
@richardtullberg please check maple

**Comment by abioteau** [comment]
I have tested on maple and kagura, issue is still not solved.

**Comment by jerpelea** [comment]
thanks

**Comment by richardtullberg** [comment]
@abioteau Hi, I have been trying to fix this issue. Could you clarify the usecases for me? I am doing an echo test using Voip by Antisip and I get it to work but there is a delay and its very low, especially on "Speaker Phone".

Are you getting complete silence? Have you touched any of the fluence settings?

Best Regards Richard

**Comment by abioteau** [comment]
@richardtullberg Hi, I use Linphone VoIP application. Even if i do an echo test or a voice call, there is a complete silence. I do not touch to fluence settings.

**Comment by abioteau** [comment]
Here is logs when i am doing an echo test with Linphone VoIP app on :
- Kagura [log_test_echo_kagura.txt](https://github.com/sonyxperiadev/bug_tracker/files/1686015/log_test_echo_kagura.txt)
- Maple [log_test_echo_yoshino.txt](https://github.com/sonyxperiadev/bug_tracker/files/1686016/log_test_echo_yoshino.txt)

**Comment by abioteau** [comment]
This commits https://github.com/abioteau/repo_update/commit/d0dc342122d8bf4ddbb669a2ab7ddb8e227df87d fix PCM ID overwrite errors at startup :

> 01-31 17:01:54.771: I/audio_hw_extn(655): audio_extn_set_snd_card_split: snd_card_name(msm8998-tasha-snd-card) device(msm8998) snd_card(tasha) form_factor(snd)
> 01-31 17:01:54.775: E/platform_info(655): process_acdb_id: Device SND_DEVICE_OUT_VOICE_SPEAKER_2 in /system/etc/audio_platform_info.xml not found, no ACDB ID set!
> 01-31 17:01:54.775: E/platform_info(655): process_acdb_id: Device SND_DEVICE_IN_VOICE_SPEAKER_QMIC in /system/etc/audio_platform_info.xml not found, no ACDB ID set!
**> 01-31 17:01:54.776: E/platform_info(655): process_pcm_id: usecase USECASE_VOICEMMODE1_CALL in /system/etc/audio_platform_info.xml not found!
> 01-31 17:01:54.777: E/platform_info(655): process_pcm_id: usecase USECASE_VOICEMMODE1_CALL in /system/etc/audio_platform_info.xml not found!
> 01-31 17:01:54.777: E/platform_info(655): process_pcm_id: usecase USECASE_VOICEMMODE2_CALL in /system/etc/audio_platform_info.xml not found!
> 01-31 17:01:54.778: E/platform_info(655): process_pcm_id: usecase USECASE_VOICEMMODE2_CALL in /system/etc/audio_platform_info.xml not found!
> 01-31 17:01:54.778: E/msm8974_platform(655): find_index: Could not find index for name = USECASE_AUDIO_SPKR_CALIB_RX
> 01-31 17:01:54.779: E/platform_info(655): process_pcm_id: usecase USECASE_AUDIO_SPKR_CALIB_RX in /system/etc/audio_platform_info.xml not found!
> 01-31 17:01:54.779: E/msm8974_platform(655): find_index: Could not find index for name = USECASE_AUDIO_SPKR_CALIB_TX
> 01-31 17:01:54.779: E/platform_info(655): process_pcm_id: usecase USECASE_AUDIO_SPKR_CALIB_TX in /system/etc/audio_platform_info.xml not found!
> 01-31 17:01:54.779: E/msm8974_platform(655): find_index: Could not find index for name = USECASE_AUDIO_PLAYBACK_AFE_PROXY
> 01-31 17:01:54.780: E/platform_info(655): process_pcm_id: usecase USECASE_AUDIO_PLAYBACK_AFE_PROXY in /system/etc/audio_platform_info.xml not found!
> 01-31 17:01:54.780: E/msm8974_platform(655): find_index: Could not find index for name = USECASE_AUDIO_RECORD_AFE_PROXY
> 01-31 17:01:54.780: E/platform_info(655): process_pcm_id: usecase USECASE_AUDIO_RECORD_AFE_PROXY in /system/etc/audio_platform_info.xml not found!**
> 01-31 17:01:54.781: E/platform_info(655): process_backend_name: Device SND_DEVICE_IN_CAMCORDER_MIC in /system/etc/audio_platform_info.xml has no backed set!
> 01-31 17:01:55.044: E/audio_route(655): Control 'SLIMBUS_0_RX Audio Mixer MultiMedia1' already exists in path 'deep-buffer-playback speaker-and-headphones'
> 01-31 17:01:55.045: E/audio_route(655): Control 'SLIMBUS_0_RX Audio Mixer MultiMedia5' already exists in path 'low-latency-playback speaker-and-headphones'
> 01-31 17:01:55.046: E/audio_route(655): Control 'SLIMBUS_0_RX Audio Mixer MultiMedia3' already exists in path 'audio-ull-playback speaker-and-headphones'
> 01-31 17:01:55.048: E/audio_route(655): Control 'SLIMBUS_0_RX Audio Mixer MultiMedia7' already exists in path 'compress-offload-playback2 speaker-and-headphones'
> 01-31 17:01:55.050: E/audio_route(655): Control 'SLIMBUS_0_RX Audio Mixer MultiMedia11' already exists in path 'compress-offload-playback4 speaker-and-headphones'
> 01-31 17:01:55.051: E/audio_route(655): Control 'SLIMBUS_0_RX Audio Mixer MultiMedia12' already exists in path 'compress-offload-playback5 speaker-and-headphones'
> 01-31 17:01:55.052: E/audio_route(655): Control 'SLIMBUS_0_RX Audio Mixer MultiMedia13' already exists in path 'compress-offload-playback6 speaker-and-headphones'
> 01-31 17:01:55.053: E/audio_route(655): Control 'SLIMBUS_0_RX Audio Mixer MultiMedia14' already exists in path 'compress-offload-playback7 speaker-and-headphones'
> 01-31 17:01:55.054: E/audio_route(655): Control 'SLIMBUS_0_RX Audio Mixer MultiMedia15' already exists in path 'compress-offload-playback8 speaker-and-headphones'
> 01-31 17:01:55.056: E/audio_route(655): Control 'SLIMBUS_0_RX Audio Mixer MultiMedia16' already exists in path 'compress-offload-playback9 speaker-and-headphones'

But it does not have effect on this issue.

**Comment by richardtullberg** [comment]
@abioteau the audio_effects.conf on your device, does it have the updated UUIDs for aec and ns?

In the logs you sent me I see this
02-01 16:12:31.076: I/AudioFlinger(658): AudioFlinger's thread 0xeba83ec0 ready to run
02-01 16:12:31.076: W/AudioFlinger(658): createEffect() error -2 from EffectGetDescriptor
02-01 16:12:31.077: E/AudioEffect(658): set(): AudioFlinger could not create effect, status: -2
02-01 16:12:31.077: W/AudioPolicyEffects(658): addInputEffects(): failed to create Fx aec on source 7
02-01 16:12:31.078: W/AudioFlinger(658): createEffect() error -2 from EffectGetDescriptor
02-01 16:12:31.078: E/AudioEffect(658): set(): AudioFlinger could not create effect, status: -2
02-01 16:12:31.079: W/AudioPolicyEffects(658): addInputEffects(): failed to create Fx ns on source 7

that will prevent the fluence additions we made. I merges a patch in n-mr1 in sony/common git to fix this https://github.com/sonyxperiadev/device-sony-common/pull/420

Do you have these fixes?

**Comment by abioteau** [comment]
@richardtullberg Currently, i have not these fixes.

**Comment by abioteau** [comment]
I have tested on maple and kagura with these fixes and it works now. ;-)

**Comment by richardtullberg** [comment]
@abioteau can you tell me how the volume is on Voip Speaker?

**Comment by abioteau** [comment]
@richardtullberg The volume is good on both devices

**Comment by abioteau** [comment]
Solved with PR https://github.com/sonyxperiadev/device-sony-common/pull/426
