### ISSUE TITLE
[TAMA][APOLLO] H8324 camera-focus 

### ISSUE THREAD

**Issue by der-lange** [sonyxperiadev/bug_tracker#592]
device: XZ2c-dualsim (H8324)
OS: lineage-17.1-20200511-UNOFFICIAL-apollo_RoW
SW: v6-binaries,dual-sim,microg,magisk,camera2-api
cam-app: FreeDCam
problem: focussing
tested: standard-mode and enabled focuspeak (zoom-factor: 8, distance: about 3m)
result: standard not sufficient; but focuspeak working nearly perfect!

photo shot with focuspeak: 
![2020_05_25_12_27_09](https://user-images.githubusercontent.com/66067519/83230714-88266d80-a18a-11ea-8440-33885fc0f300.jpg)

logfile: 1. photo (standard), 2. photo (focuspeak)
logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/4700057/logcat.txt)

_Originally posted by @der-lange in https://github.com/sonyxperiadev/bug_tracker/issues/570#issuecomment-635805571_

**Comment by Haxk20** [comment]
@martinX3 Can you confirm that same happens for you and it isnt just LineageOS issue on that platform ?

**Comment by MartinX3** [comment]
@Haxk20 the camera stuff is from OEM/SODP.
I don't know how LineageOS could change the camera quality.

**Comment by Haxk20** [comment]
Anyways. That means its SODP issue then. I dont own the device so i cant exactly test it.
@der-lange Please try OEM v7

**Comment by MartinX3** [comment]
I wonder if that helps.
According to the changelog the only camera improvements in OEMv7 are in Yoshino.

**Comment by der-lange** [comment]
Up to now  I didn‘t see the focuspeak-feature  in the OpenCamera app. It works fine too. It seems to be a feature of camera2-api.

**Comment by sraase** [comment]
Is this issue still relevant?

**Comment by der-lange** [comment]
I´m not sure. While testing LOS18.1, I got good results with SNAP and OPENCAMERA in conjunction with CAMERA2-api; but there is no experience with the new SODP-Rom. At the moment I use the Sony latest stock A10 (original camera and working banking-app) - waiting for the next upgrade by  MartinX3...

**Comment by MartinX3** [comment]
@der-lange LOS18.1 from XDA? It's stock based so you can't test this issue with it.

My last try was on AOSP 11 and the camera-focus was problematic with my XZ2.
After the OEM 4.19 for A12 tama is ready I try it again.
Currently I have no time to backup and restore my phone. I moved to stock LOS last year because of the battery drain in 4.14.

**Comment by sraase** [comment]
In that case, I would recommend closing the issue. You can always create a new one if the issue persists.
