### ISSUE TITLE
[Yoshino] Sound trigger support

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#595]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14.182-gd9e0f9bacfe9¹
**Android version:** android-10.0.0_r36
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v7a_yoshino.img
**Version baseband:** 1307-7511_47.2.A.11.228
**Build:** aosp_g8441-userdebug 10 QQ2A.200501.001.B3 eng.stefan.20200601.131643

@ix5 asked me to do a test for the sound trigger on yoshino, this "feature request" has been opened to track the progress and outcome if the test / investigation.
 
---
¹)
Commit: d9e0f9bacfe9 can't be found on github.
- Base commit is: https://github.com/sonyxperiadev/kernel/commit/cdca9491471b41aa069d710caa53ba95b2ac07bb
- git revert: https://github.com/sonyxperiadev/kernel/commit/b71379c4717912dd945637291217aa438d5b71d2

**Comment by stefanhh0** [comment]
Following done:
```
make installclean && make -j4 vendorimage
simg2img vendor.img vendor.raw
mount -o loop,rw vendor.raw /mnt/
cp sony_lilac_dump/vendor/etc/sound_trigger*.xml /mnt/vendor/etc
umount /mnt
img2simg vendor.raw vendor.img
```
@ix5 I have flashed that vendor, please confirm that my steps are correct. 

Functional test needs still to be done, will try it using Google Assistant.

**Comment by stefanhh0** [comment]
Google Assistant seems to work fine, tried Ok google... do you want me to grab some logs?

**Comment by stefanhh0** [comment]
So to use the assistant I have to start it when it is not started saying "Ok google" won't start the assistant... however I would have guessed that is the functionality of the soundtrigger, maybe I have to configure something else in the assistant which I haven't?

**Comment by stefanhh0** [comment]
Although I trained my voice with 'Ok Google' and 'Hey Google', I can't activate the voice match function, see as well screenshot: 

![Screenshot_20200604-065253](https://user-images.githubusercontent.com/28729344/83716478-50a73d80-a630-11ea-85c9-29270fb6f3d1.png)

**Comment by stefanhh0** [comment]
Also in the App 'Google' I can't activate voice match...


[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/4727623/logcat.log)

I see:
```
stefan@mars:~/android/sony_lilac_dump$ grep soundtrigger logcat.log 
06-04 06:56:46.383   643 11196 I soundtrigger: audio_extn_sound_trigger_update_stream_status: send event 13: usecase id 10, type 1
06-04 06:56:50.370   643   643 I soundtrigger: audio_extn_sound_trigger_update_stream_status: send event 12: usecase id 10, type 1
06-04 06:56:50.625   643  8619 I soundtrigger: audio_extn_sound_trigger_update_stream_status: send event 3: usecase id 0, type 0
06-04 06:56:53.225   643 11242 I soundtrigger: audio_extn_sound_trigger_update_stream_status: send event 13: usecase id 10, type 1
06-04 06:56:56.281   643   643 I soundtrigger: audio_extn_sound_trigger_update_stream_status: send event 2: usecase id 0, type 0
06-04 06:56:56.476   643   643 I soundtrigger: audio_extn_sound_trigger_update_stream_status: send event 12: usecase id 10, type 1
06-04 06:56:57.597   643  8619 I soundtrigger: audio_extn_sound_trigger_update_stream_status: send event 3: usecase id 0, type 0
06-04 06:57:05.678   643   643 I soundtrigger: audio_extn_sound_trigger_update_stream_status: send event 2: usecase id 0, type 0
06-04 06:57:10.715   643 11507 I soundtrigger: audio_extn_sound_trigger_update_stream_status: send event 13: usecase id 10, type 1
06-04 06:57:13.000   643   643 I soundtrigger: audio_extn_sound_trigger_update_stream_status: send event 12: usecase id 10, type 1
```

That looks good right? Please say if that is enough, I'd like to uninstall that Google stuff from my phone it is just too much Google on my phone now ;-)

**Comment by stefanhh0** [comment]
The option is `Hey Google` is greyed out, no way found to get that enabled, we (Felix and me) tried following properties:
`setprop ro.opa.eligible_device true`
`setprop ro.com.google.clientidbase android-google`

Felix spotted a `HotwordHelper: hasHotwordEverywhere-false` not sure if that is the reason.

I will stop for now the investigation.

**Comment by stefanhh0** [comment]
Hello @oshmoun, 

I believe I opened this one for you, since @ix5 asked me to do so. Not 100 % sure if it was for you.

Any news on that?

Specifically, should it remain open? 

I am personally not interested in having sound trigger support available on yoshino.

So in case no one is working on it and no one is really interested in it, I'd prefer to close this one. We have enough other stuff laying around, so it won't get boring anyway :-)

Not to be misunderstood, in case this will make progress or someone wants me to test something specifically I'd be available to assist and give feedback.

Please comment on this issue or I'll close it.

Thanks & Cheers
Stefan

**Comment by oshmoun** [comment]
but does sound trigger work on any other device? Does any other device have these options not greyed out like you have?

**Comment by stefanhh0** [comment]
I can't tell, I have no other device to test it.

**Comment by stefanhh0** [comment]
Closing this one for now. In case there is something to test send me a message on slack and I can do so. I don't want to have this issue on my open list anymore when there is no progress to be expected.
