### ISSUE TITLE
[nile,ganges] fastboot stops working after updating Windows 10 to v2004

### ISSUE THREAD

**Issue by sledges** [sonyxperiadev/bug_tracker#598]
**Platform:** All that use Xperia X fastboot driver for Windows
**Device:** Seen with Xperia 10 and XA2

**Previously working on**
Windows 10 v19xx

**Description**
After updating Windows 10 to v2004, device manager shows Other devices/Android with a question mark to it, and device can no longer be listed via `fastboot.exe devices`
If the Sony sa0114 driver has not been installed previously, its installation succeeds, but in device manager it appears also as "Other devices/Android".

**How to reproduce**
Have the [Sony Xperia X driver](https://developer.sony.com/file/download/xperia-x-driver/) working on Windows 10 v19xx, then update to v2004 and attempt to list devices with `fastboot.exe`.

**Additional context**
This has been reported by [Sailfish OS users](https://together.jolla.com/question/227831/unable-to-install-fastboot-driver-in-windows-10-v2004/) and also on [XDA](https://forum.xda-developers.com/showpost.php?p=82489019&postcount=420).

As a workaround, it's been shown that drivers provided by Xperia Companion or by unofficial FlashTool or even Zadig utility should work (install correctly), but each of those have not been confirmed by more than one person.

**Comment by MarijnS95** [comment]
@sledges As far as I'm aware that thing is ancient (2016) and Google fastboot drivers work just fine. Can you try those?

**Comment by badmaan** [comment]
I use FlashTool's setup app for installing drivers and for some reason no other driver or something is working and I lose the driver on every reboot, I need to reinstall the driver every time :/ tried multiple official fastboot drivers but it isn't working for me. I use windows insider fast ring but I also tried on stable windows build too, same issue persists. Yoshino/poplar.

**Comment by sledges** [comment]
@MarijnS95, we currently have two confirmations that Google fastboot drivers also stop working after updating Windows 10 to v2004 (it works on older updates).

It incorrectly reports as installed successfully, however still appears with a question mark in Device Manager, and fastboot.exe cannot list the device -- https://imgur.com/a/ySrpvKw.

**Comment by MarijnS95** [comment]
@sledges That's odd, I wonder if other devices (from different manufacturers) are affected too.

I don't boot into Windows all that often but will try to remember to validate Windows version and test multiple devices when I eventually end up there...

**Comment by AngryGami** [comment]
I got this issue just today (or noticed it today to be precise). Main problem for me was that device could be detected by fastboot while it is in "blue light" mode, but later, when I reboot it into `fastbootd` mode it no longer could be seen by fastboot tool. Windows device manager sees this device under "Other devices" as "Sony Xperia 10 II (AOSP)" without any drivers and no drivers could be applied (even after I select driver manually and Window says that install was successful - it stays in the list of "Other devices" and fastboot can't see it). I uninstalled 2004 update and this didn't help.
What helped so far:
1) disable secure boot in bios
2) disable driver signature verification (first via advanced boot options and then via command line)
3) manually install driver for this "Sony Xperia 10 II (AOSP)"  as 'Sony Ericsson sa0102 ADB Interface Driver' from set of drivers coming with FlashTool.

I can't explain why this worked and I can't guarantee it will persist - something fishy is happening here, but it did allow me to flash my device without any issues.

**Comment by seilexta** [comment]
you can also just use zadig to install the fastboot driver (winusb) without disabling signature

**Comment by jerpelea** [comment]
this is not a project bug

**Comment by sledges** [comment]
This problem vanished from Windows 10 by taking the **2H20** Windows update and the cumulative updates of Nov-Dec 2020.
