### ISSUE TITLE
[TAMA] ninja failed building latest android-10.0.0_r37

### ISSUE THREAD

**Issue by jevgenp** [sonyxperiadev/bug_tracker#599]
**Platform:** Tama
**Device:** H8324
**Kernel version:** 4.14
**Android version:** 10

**Description**
ninja failed with: exit status 1 on system.img creation tryng to build Build AOSP Android 10.0 using guide.

**Symptoms**
`[ 99% 931/933] Target system fs image: out/target/product/apollo/obj/PACKAGING/systemimage_intermediates/system.img
FAILED: out/target/product/apollo/obj/PACKAGING/systemimage_intermediates/system.img`

[**error.txt**](https://github.com/sonyxperiadev/bug_tracker/files/4782493/error.txt)

**How to reproduce**
source build/envsetup.sh && lunch >> 32
make

**Comment by MarijnS95** [comment]
```
22:04:40 mkuserimg_mke2fs.py ERROR: Failed to run e2fsdroid_cmd: set_selinux_xattr: No such file or directory searching for label "/bt_firmware"
```
Please make sure all repositories are synced properly.

**Comment by jevgenp** [comment]
Noted (installclean). It's ok now. Thanks for the fast response :)
