### ISSUE TITLE
[LOIRE] [ALL] Camera has a green tint

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#6]
**Platform:** SoMC Loire
**Device:** ALL
**Kernel version:** 4.4.xx
**Android version:** 8.0 (/ALL)

**Description**
Everything coming from the camera has a green tint.

**Symptoms**
Preview, snapshot and video in any camera app has the green tint.

**How to reproduce**
Open any camera app, the preview will have a green tint. Also any photo or video taken will be green.

**Comment by jerpelea** [comment]
cameras are working now but we get the wrong color format

**Comment by oshmoun** [comment]
yes, great progress has been made! Will update the description.

**Comment by jerpelea** [comment]
Camera has been fixed!
The fix will come in vendor v5 for both Android 7.1 and Android 8.0
