### ISSUE TITLE
[maple] incorrect selinux labels on /odm/firmware

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/bug_tracker#60]
**Platform:** yoshino
**Device:** maple
**Kernel version:** 4.4
**Android version:** 7.1.1

**Description**
The firmware files under `/odm/firmware` do not appear to be labelled correctly:

```
maple:/ # ls -dlZ /firmware
dr-xr-x--- 3 system system u:object_r:firmware_file:s0 16384 1970-01-01 00:00 /firmware
maple:/ # ls -dlZ /odm/firmware
drwxr-xr-x 3 root shell u:object_r:system_file:s0 4096 2017-11-03 10:29 /odm/firmware
```
**Symptoms**

**How to reproduce**
`ls -dlZ /odm/firmware`

**Comment by jamuir** [comment]
I can fix this, but I'm not sure what would be the preferred project to update.

`device-sony-sepolicy` or `device-sony-yoshino`?

my guess is `device-sony-sepolicy`.

**Comment by jerpelea** [comment]
yoshino tone and loire

**Comment by jamuir** [comment]
Note that the only project where there already exists odm security context is `device-sony-sepolicy`; that's why it seemed appropriate to fix it there.

My thought was to just update `file_contexts`, but that won't help unless `restorecon_recursive /odm` is added to an rc file.

**Comment by jamuir** [comment]
also, `/odm` is mounted `ro`.  We would need to mount it `rw` before we can do a restorecon.

**Comment by jerpelea** [comment]
we can fix the policy and on next odm release policy will be correctly set. we should not mont orm rw

**Comment by jerpelea** [comment]
lilac:/odm # ls -Z
u:object_r:system_file:s0          bin
u:object_r:vendor_firmware_file:s0 firmware
u:object_r:system_file:s0          lib
u:object_r:system_file:s0          lib64
u:object_r:system_file:s0          lost+found
u:object_r:system_file:s0          odm_version.prop

**Comment by jerpelea** [comment]
on android 8.0

**Comment by jamuir** [comment]
ok.  I will update `device-sony-sepolicy` using oreo context rules.

this is the one for odm firmware:
```
/odm/firmware(/.*)?                   u:object_r:vendor_firmware_file:s0
```
The label will need to be updated.

**Comment by jerpelea** [comment]
sepolicy has to be updated a bit

**Comment by jamuir** [comment]
PR:

https://github.com/sonyxperiadev/device-sony-sepolicy/pull/307

**Comment by jamuir** [comment]
PR has been merged.

closing.
