### ISSUE TITLE
i think battery levels are still wrong 

### ISSUE THREAD

**Issue by Tarrun1234** [sonyxperiadev/bug_tracker#601]
**Platform:** Tama
**Device:** XZ2 compact
**Kernel version:** 4.14
**Android version:** 10
**Software binaries version:** v8

**Description**
  Standby drain is 10 percent at night

**Comment by leeoniya** [comment]
wasn't this resolved in https://github.com/sonyxperiadev/bug_tracker/issues/581?

> Standby drain is 10 percent at night

is this a lot?

tonight i'm gonna flash my XZ2 Compact with oemv8 and the lineage build from [1] and see how it does. i personally would not find it alarming if it drained 10% overnight (~1% an hour seems reasonable to me).

[1] https://forum.xda-developers.com/xperia-xz2/development/rom-lineageos-17-1-t4044653/page42

**Comment by ix5** [comment]
The uncertainty around battery levels has already been reported and is being investigated.

Since you failed to fill in the template, and unless you can provide any additional information, please close this issue.

**Comment by MarijnS95** [comment]
> ~1%/hr seems quite reasonable to me

FYI this is far, FAR from reasonable. We are working to improve it over time, but progress is slow and complicated :wink:

**Comment by leeoniya** [comment]
well, that will be nice then :)

what's the depletion rate on sony's stock roms? and is that the target?

what's a reasonable amount to expect given that most people at night will have connected wifi, enabled cell data/lte and bluetooth.

**Comment by MarijnS95** [comment]
That depends heavily on the device and apps installed, but I assume about a week or two should be a proper average. For comparison a PDX201 (Xperia 10 mark 2) - which has an incredibly efficient soc - has a month of standby time without SIM nor WiFi connected. I assume that drops back to about 3 weeks when connectivity is enabled and some apps are polling/receiving stuff in the background, and a couple days to a single day depending on system/screen on time.

4 days on SODP without any foreground use is insane, given that this idle drain persists when the device is gutted of any apps and connectivity. The SoCs on most if not all supported devices sleep properly, meaning that we seem to leave an external processor in some heavy working state, leak current through some pins somewhere or some other magic entirely :grinning: 

There's no goal set in stone, but something close to stock or even beyond is where we would really like to be. We don't have nearly as many preinstalled apps (plain SODP, no derived ROM) nor their "advanced battery care" or whatever the invention is (killing BG apps and that sort of stuff), but at least the case without connectivity should be on-par.
