### ISSUE TITLE
repo sync failure branch android-8.0.0_r30

### ISSUE THREAD

**Issue by MinorThreat1** [sonyxperiadev/bug_tracker#606]
transpower repository is missing o-mr1 branch

Error messages:
Fetching projects: 32% (186/575) platform/packages/apps/CellBroadcastReceiverfatal: couldn't find remote ref refs/heads/o-mr1
vendor-nxp:
fatal: couldn't find remote ref refs/heads/o-mr1

Fetching projects: 45% (264/575) platform/packages/apps/Car/Overviewerror: Cannot fetch transpower from https://github.com/sonyxperiadev/transpower

Fetching projects: 49% (285/575) platform/packages/providers/DownloadProvidererror: Cannot fetch vendor-nxp from https://github.com/sonyxperiadev/vendor-nxp

Checking out projects: 97% (560/574) vendor-broadcom-wlanerror: Cannot checkout vendor-nxp: ManifestInvalidRevisionError: revision o-mr1 in vendor-nxp not found
error: in sync: revision o-mr1 in vendor-nxp not found

**Comment by jerpelea** [comment]
the issue was fixed 
thanks for repoting it
