### ISSUE TITLE
Errors during build

### ISSUE THREAD

**Issue by Kenzo-10** [sonyxperiadev/bug_tracker#609]
**Platform:** loire
**Device:** suzu
**Kernel version:** 4.9
**Android version:** 10.0.0_r15

**How to reproduce**
repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r15 && cd .repo && git clone https://github.com/sonyxperiadev/local_manifests && cd local_manifests && git checkout master && cd ../.. && repo sync -j4 && ./repo_update.sh
source build/envsetup.sh && lunch aosp_f5121-userdebug
make otapackage -j4

**Additional context**
wildcard(out/target/product/suzu/clean_steps.mk) was changed, regenerating...
[ 99% 12348/12349] finishing build rules ...
FAILED: 
vendor/qcom/opensource/location/gnsspps/Android.mk: error: "libgnsspps (SHARED_LIBRARIES android-arm64) missing libgps.utils (SHARED_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/gnsspps/Android.mk: error: "libgnsspps (SHARED_LIBRARIES android-arm) missing libgps.utils (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/ds_api/Android.mk: error: "libloc_ds_api (SHARED_LIBRARIES android-arm64) missing libgps.utils (SHARED_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/ds_api/Android.mk: error: "libloc_ds_api (SHARED_LIBRARIES android-arm) missing libgps.utils (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/loc_api_v02/Android.mk: error: "libloc_api_v02 (SHARED_LIBRARIES android-arm64) missing libloc_core (SHARED_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/loc_api_v02/Android.mk: error: "libloc_api_v02 (SHARED_LIBRARIES android-arm64) missing libgps.utils (SHARED_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/loc_api_v02/Android.mk: error: "libloc_api_v02 (SHARED_LIBRARIES android-arm) missing libloc_core (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/loc_api_v02/Android.mk: error: "libloc_api_v02 (SHARED_LIBRARIES android-arm) missing libgps.utils (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:1017: error: exiting from previous errors.
17:07:52 ckati failed with: exit status 1

**Comment by MarijnS95** [comment]
The [`android-10_legacy`](https://github.com/sonyxperiadev/local_manifests/tree/android-10_legacy) branch should be used for Loire and Tone.

Then, I hope it works for you because we don't fully support nor maintain these devices anymore. They are only built ever so often so any recent changes might have an effect. Worth a try though, feel free to report any other issues along the way!

@jerpelea Can the build guide be updated to reflect this branch choice?

**Comment by MarijnS95** [comment]
@ix5 Looks like `android-10_legacy` is still [stuck at the `q-mr0` branch](https://github.com/sonyxperiadev/local_manifests/blob/android-10_legacy/qcom.xml#L19) for location, yet https://github.com/sonyxperiadev/vendor-qcom-opensource-location/pull/28 was merged to 8.1. We should be able to update that now?

**Comment by jerpelea** [comment]
@MarijnS95 PR please

**Comment by Kenzo-10** [comment]
@MarijnS95 thanks for your Solution and It worked, but sir I don't want to use prebuilt kernel. I am willing to build kernel along with building rom. I followed this Guide -https://developer.sony.com/develop/open-devices/guides/kernel-compilation-guides/how-to-build-and-flash-a-linux-kernel-for-aosp-supported-devices but didn't worked can i get any help Sir.

**Comment by chris42** [comment]
In ```kernel/sony/msm-4.9/common-kernel``` you'll find ```build-kernels-gcc.sh``` to build the kernels. You should edit it before running it and only limit it to loire/suzu, as otherwise it will build all kernels for all devices, which takes time.

**Comment by Kenzo-10** [comment]
@chris42 i don't want to build separately, wanting to build automatic during make otapackage.

**Comment by chris42** [comment]
This is the only supported way here. Just one more command.

**Comment by MarijnS95** [comment]
To be more specific...

https://android.googlesource.com/platform/build/+/master/Changes.md#and-calling-other-build-systems

> when building with external build systems ([...], kernel, [...])
> [...]
> We recommend to build these outside of Android, and deliver prebuilts into the Android tree instead of decreasing the speed and reliability of the incremental Android build.

That, together with https://android.googlesource.com/platform/build/+/master/Changes.md#PATH_Tools makes it so that we _can't_ properly support inline building anymore since Q. @ix5 made it possible with a ton overriding and it's still not smooth; this will only get worse with android R/11.

Iirc AOSP has more definitive documentation on not supporting inline building of the kernel anymore, but I can't find it.

**Comment by MrJarvis698** [comment]
@MarijnS95 ok i want to choose andriod 9 so which branch is recommended sir

**Comment by Kenzo-10** [comment]
@MarijnS95 Ok i want to choose andriod 9, so which branch is recommended Sir.

**Comment by stefanhh0** [comment]
For building android 9, check the official documentation  here:
https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0-2

**Comment by MrJarvis698** [comment]
Thanks For Giving your Valuable Time Sir, I Hope i will help again if any problem Encounter. @MarijnS95 , @jerpelea , @chris42 , @stefanhh0 .

**Comment by MrJarvis698** [comment]
Thanks For Giving your Valuable Time Sir, I Hope i will help again if any problem Encounter. @MarijnS95 , @jerpelea , @chris42 , @stefanhh0 .

**Comment by Kenzo-10** [comment]
Thanks For Giving your Valuable Time Sir, I Hope i will help again if any problem Encounter. @MarijnS95 , @jerpelea , @chris42 , @stefanhh0 .
