### ISSUE TITLE
Missing Intermediates

### ISSUE THREAD

**Issue by Kenzo-10** [sonyxperiadev/bug_tracker#610]
**Platform:** loire
**Device:** suzu
**Kernel version:** 4.9
**Android version:** 10.0.0_r15

**Description**
repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r15 && cd .repo && git clone https://github.com/sonyxperiadev/local_manifests -b android-10_legacy && cd ../.. && repo sync -j4 && ./repo_update.sh
source build/envsetup.sh && lunch aosp_f5121-userdebug
make otapackage

**Problem**
FAILED: ninja: 'out/target/product/suzu/obj/KERNEL_OBJ/usr', needed by 'out/target/product/suzu/obj/EXECUTABLES/ipacm_intermediates/IPACM_Main.o', missing and no known rule to make it
11:50:58 ninja failed with: exit status 1

**Using Prebuild Kernel**

**Comment by Kenzo-10** [comment]
Solved This issue by adding manual directory **KERNEL_OBJ/usr** in **out/target/product/suzu/obj/**. And Now its Started Building.

**Comment by MarijnS95** [comment]
That's completely wrong, all uses of that folder by ipacm are guarded by
```make
ifeq ($(TARGET_COMPILE_WITH_MSM_KERNEL),true)
```
Which'll be false when using prebuilts:
```make
device/sony/common/CommonConfig.mk
152:BUILD_KERNEL ?= false
153:TARGET_COMPILE_WITH_MSM_KERNEL := $(BUILD_KERNEL)
```

Are you sure `repo_update` completed successfully? In particular, check if `vendor/oss/repo_update` is properly checked out at `android-10_legacy` and has the following:

https://github.com/sonyxperiadev/repo_update/blob/android-10_legacy/repo_update.sh#L51-L56

Make sure that patch is applied in `hardware/qcom/data/ipacfg-mgr/sdm845`.
