### ISSUE TITLE
[kirin] [aosp 10] [kernel 4.14] Device does not boot with latest 4.14.187 kernel

### ISSUE THREAD

**Issue by xperia10dev** [sonyxperiadev/bug_tracker#612]
**Platform:** ganges
**Device:** kirin (i4113)
**Kernel version:** 4.14.187-gfa90c2aab050
**Android version:** android-10.0.0_r37
**Software binaries version:** 10.0.7.1_r1_v9b_ganges

**Previously working on**
4.14.186-ge979699d59130-dirty (prebuilt)

**Description**
Device does not boot with the latest kernel.

**Symptoms**
Android logo is not shown, the panel seems to remain off after the Sony logo disappears.

**How to reproduce**
Try to boot the latest kernel using 'fastboot boot boot.img'.

**Additional context**
Attached console-ramoops for 4.14.187-gfa90c2aab050 and initial dmesg for 4.14.186-ge979699d59130-dirty (which boots normally) for reference.
In the console-ramoops, unfortunately there does not seem to be much useful information after "@@@@ panel power off @@@@".
If anyone knows how to extract more meaningful logs from the early boot stage please let me know.
[console-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/4892951/console-ramoops-0.txt)
[dmesg.txt](https://github.com/sonyxperiadev/bug_tracker/files/4892952/dmesg.txt)

**Comment by stefanhh0** [comment]
Hello @xperia10dev 

thanks for the report, to identify the commit that causes the problem can you do a git bisect (`man git-bisect`), there are several commits that could have introduced that regression, see as well:

`kernel/sony/msm-4.14/kernel$ git log --oneline e979699d59130^..fa90c2aab050`. Then we would know with which commit exactly it is broken.

**Comment by MarijnS95** [comment]
> there does not seem to be much useful information after

There is **a lot** of useful information there:

```
[   48.150438] charger: [48150] device unplugged: shutting down in 10000 (@ 58150)
[...]
[   54.107844] charger: [54107] rebooting
[   55.108465] Disabling non-boot CPUs ...
[   55.108671] firmware SM13_KM_08_PID5403.bin: _request_firmware_load: firmware state wait timeout: rc = -2
[   55.109005] nt36xxx-fwupd: firmware load failed, ret=-11
[   55.109129] nt36xxx-fwupd: update_firmware_request failed. (-11)
[   55.114117] i2c-msm-v2 c175000.i2c: NACK: slave not responding, ensure its powered: msgs(n:2 cur:1 rx) bc(rx:65 tx:1) mode:DMA slv_addr:0x1 MSTR_STS:0x0d1300c8 OPER:0x00008010
[   55.114301] i2c-msm-v2 c175000.i2c: error i2c_msm_dma_xfer_process(n_bufs:2):-1
[   55.319368] dsi_panel_driver_touch_pinctrl_set_state: invalid 'sde_touch_suspend' pinstate
[   55.319480] @@@@ panel power off @@@@
[   55.323319] [sde error]Unsupported UBWC version 0x00000000
[   55.326092] reboot: Restarting system
[   55.326270] Going down for restart now
[   55.326963] qcom,qpnp-power-on 800f000.qcom,spmi:qcom,pm660l@2:qcom,power-on@800: PMIC@SID2: configuring PON for reset
```

- The device is in charger mode
- The charger is unplugged and hence reboots
- It reboots gracefully
- During that reboot there are some firmware warningsl those must be harmless.

First up it should display the battery charging icon, this was fixed with 
https://github.com/sonyxperiadev/kernel/pull/2308/commits/597ca5589a22de62ee72782ccad1dd6315b9c618. I didn't check if the mentioned commit hash includes this commit, but it's likely with 187 only merged recently.

Try to boot the device without charger inserted. Sometimes these devices like to boot with
```
[    0.232082] qcom,qpnp-power-on 800f000.qcom,spmi:qcom,pm660@0:qcom,power-on@800: PMIC@SID0 Power-on reason: Triggered from USB (USB Charger Insertion) and 'cold' boot
```
Even if started by a `fastboot boot`, `fastboot reboot`, or manual button presses.

**Comment by stefanhh0** [comment]
@MarijnS95 cheked it, https://github.com/sonyxperiadev/kernel/commit/597ca5589a22de62ee72782ccad1dd6315b9c618 is part https://github.com/sonyxperiadev/kernel/commit/fa90c2aab050

**Comment by stefanhh0** [comment]
We believe that the phone should boot up with the latest kernel without any problems when you disconnect it from USB. To be sure to do a clean boot, please force a power cycle and not just a warm boot.

Please report back if that fixes your problem.

**Comment by xperia10dev** [comment]
@MarijnS95 @stefanhh0 the device boots fine with the latest kernel when disconnected from USB. I'm closing the bug report, thanks for your help!

**Comment by MarijnS95** [comment]
The bootloader is drunk, as we expected. See whether `fastboot reboot` and friends work fine again now that it had one proper boot into Android. Should work fine, it does here too.
