### ISSUE TITLE
[Tama] [Apollo] Device does not boot with latest binaries

### ISSUE THREAD

**Issue by AntonioBiscuit** [sonyxperiadev/bug_tracker#613]
**Platform:** Tama
**Device:** Apollo (H8324)
**Kernel version:** 4.14
**Android version:** PixelExperience_h8324-10.0-20200615-1020-OFFICIAL
**Software binaries version:** r1_v9b_tama

**Previously working on**
v8 binaries

**Description**
The device will load forever in the boot process. Infinite Google Logo with loading animation in my case. It is possible to rollback and reflash v8 binaries to make the device boot again.

**How to reproduce**
Flash v9B binaries and try boot

**Comment by Paulbouchara** [comment]
Hey there, you have to wait for July build to be able to use v9
Use v8 for now until you see an ota

**Comment by AntonioBiscuit** [comment]
Heard that ! Thanks for the quick response ! 👍
