### ISSUE TITLE
[Documentation] Branch `android-10.0.0_r40` doesn't exist in local_manifests repository

### ISSUE THREAD

**Issue by AngryGami** [sonyxperiadev/bug_tracker#614]
This is documentation problem. 

AOSP 10 build guide [here (step 4)](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-10-0-0#tutorial-step-4) is suggesting to use `git checkout <branch>` where `<branch>` is `android-10.0.0_r40` which doesn't exists in `local_manifests` repo. 

Should I use `android-10.0.0_r37` instead?

**Comment by stefanhh0** [comment]
Hello @AngryGami 

Probably the `android-10.0.0_r40`  will be made available the next days.

You have two options.
1. as you say using `android-10.0.0_r37` instead.
2. using `android-10.0.0_r37` for `local_manifests` only and switching the rest via `repo init -b android-10.0.0_r40` to r40 that should work out of the box.

Best regards
Stefan

**Comment by AngryGami** [comment]
Thanks. I'll choose option 2.

**Comment by jerpelea** [comment]
@AngryGami _r40 is added to the local manifest
