### ISSUE TITLE
[maple] nougat build is broken

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/bug_tracker#62]
**Platform:** yoshino
**Device:** maple
**Kernel version:** 4.4
**Android version:** 7.1.1

**Description**
the build is broken:

```
[ 95% 42159/44311] Install: out/target/product/maple/system/vendor/firmware//libpn553_fw.so
FAILED: /bin/bash -c "out/host/linux-x86/bin/acp -fp out/target/product/maple/obj/ETC/libpn553_fw_intermediates/libpn553_fw.so out/target/product/maple/system/vendor/firmware//libpn553_fw.so"
acp: cannot create 'out/target/product/maple/system/vendor/firmware//libpn553_fw.so': No such file or directory
```

**Symptoms**

**How to reproduce**
```bash
$ repo sync -d -c
$ ./repo_update.sh
$ make -j16 &> make.log
```

**Comment by jamuir** [comment]
failure seems to be caused by the following commit:

https://github.com/sonyxperiadev/vendor-nxp/commit/b4453166

**Comment by jamuir** [comment]
I think we just need `TARGET_COPY_OUT_VENDOR := system/vendor` defined in the appropriate place.

**Comment by jamuir** [comment]
`TARGET_COPY_OUT_VENDOR := system/vendor` should happen automatically in `build/core/envsetup.mk` there must be something else wrong.

@jerpelea :  It may not be valid to reference `TARGET_COPY_OUT_VENDOR` inside `Android.mk` files.

**Comment by jamuir** [comment]
is it just a typo :-)

`TARGET_OUT_VENDOR` rather than `TARGET_COPY_OUT_VENDOR`

**Comment by jamuir** [comment]
build working now with the following change:

https://github.com/sonyxperiadev/vendor-nxp/pull/4

**Comment by jerpelea** [comment]
https://android.googlesource.com/platform/build/+/android-7.1.1_r58/core/envsetup.mk#377

**Comment by jamuir** [comment]
yes, `TARGET_OUT_VENDOR` seems to be defined and should work, but it doesn't.

**Comment by jamuir** [comment]
I think the real issue might be that `out/target/product/maple/system/vendor/firmware` is a symlink to something that doesn't exist.  That may be why the `acp` command failed.

```bash
sony-7$ ls -l out/target/product/maple/system/vendor/firmware 
lrwxrwxrwx 1 jamuir jamuir 13 Dec 20 22:15 out/target/product/maple/system/vendor/firmware -> /odm/firmware
```

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/device-sony-common/commit/4af35bdcc1a9e0e30130ee7a4a11461041f31d67

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/vendor-nxp/commit/812f37301d94b9cb607f1382117b2fb00d236507

**Comment by jamuir** [comment]
argh... it's just me.  I was missing your last commit to `device-sony-common`.

sorry for the distraction.

closing.
