### ISSUE TITLE
3-dimension white balance display color calibrate?

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [sonyxperiadev/bug_tracker#623]
**Platform:** yoshino
**Device:** maple
**Kernel version:** 4.14
**Android version:** 10.0 r40
**Software binaries version:** 10.0.7.1_r1_v9c_yoshino

**Is your feature request related to a problem? Please describe.**
Lack color consistency between different devices  
I'm glad to see sRGB color space in the sony official system and it's 3-dimension color calibrate feature.  
I can take a photo and get exact the same final result on mobile and PC, via calibrate the color.  
With AOSP, now this can't be implemented.

**Describe the solution you'd like**
No... I'm unsure. So the color calibrate is actually not a part of Google AOSP project?  
I used to see similar feature on some custom kernel, for example some Nexus 4 3rd party kernel.  
The Android system were not support color calibrate, and we set kernel argument to calibrate overall color.

That's how we achieve this in the ancient.  
If that was indeed, AOSP have no support to calibrate colors,  
then Sony Open Device have nothing to do on this topic.

Besides, Sony may have patented technology on color calibrate,
if that was true then merge them into AOSP will be impossible.

**Describe alternatives you've considered**
We now have "Glove mode", "ADB over network", "Display white point calibration"  
the three under "Extended settings".  
Are these belong to AOSP or some OEM private feature?  
We now have 6000K, F6: 4150K, D50: 5000K, D65: 6500K, but none of them I would say a correct color.

Under Display\Advanced\Colors, here have a color demo, but no any options to tune exists.

That's how I confused with AOSP, sRGB and color calibration.

**Comment by MarijnS95** [comment]
https://github.com/sonyxperiadev/kernel/blob/aosp/LA.UM.7.1.r1/arch/arm64/boot/dts/qcom/dsi-panel-somc-synaptics-sharp-4k-sde-cmd-ID6.dtsi#L146

**Comment by mhtvsSFrpHdE** [comment]
Currently on Android r41 & v11a SW_bin, still no 3 dimension white balance calibrate exist.  
But I found an app that can utilize Android system accessibility feature to provide this for who are interested in.

https://play.google.com/store/apps/details?id=com.neptunecloud.mistify

This app is different than SONY stock ROM calibrate, it will not "remove" color, instead, add color.  
So if you are too green, you should add more Red and Blue then also drag Filter Strength bar.  
This one will also affect notification area and nav bar, too. Just like CF.Lumen on the past.
