### ISSUE TITLE
[Seine][pdx201] Camera display is shifted down

### ISSUE THREAD

**Issue by AngryGami** [sonyxperiadev/bug_tracker#628]
**Platform:** Seine
**Device:** pdx201
**Kernel version:** 4.14
**Android version:** 10
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v9c_seine.img

**Description**
Camera application field of view is shifted down not occupying entire screen of the phone.
![screen2](https://user-images.githubusercontent.com/2470910/92892492-17dde800-f419-11ea-9d98-4a58dfeaca96.png

**How to reproduce**
Start camera application.

**Additional context**
This is build from 10 September 2020, all changes up to that date included.

**Comment by MarijnS95** [comment]
Nothing is shifted; that's just the cheap, unmaintained AOSP camera app not understanding how to deal with previews not matching the size of the screen; these are anchored to the bottom. The effect is particularly amplified on 21:9 screens though.

If this is a dealbreaker for you feel free to fix this camera and submit fixes over at AOSP's gerrit.
