### ISSUE TITLE
[Seine][pdx201] Microphone doesn't work

### ISSUE THREAD

**Issue by AngryGami** [sonyxperiadev/bug_tracker#629]
**Platform:** Seine
**Device:** pdx201
**Kernel version:** 4.14
**Android version:** 10
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v9c_seine.img

**Description**/**Symptoms**
When trying to make a call or record a video no sound actually transmitted/recorded. Also sound from the phone when calling seems to be emitted via loud speaker even for phone calls (probably should go through regular speaker by default). 

**How to reproduce**
Try to make a call or record a video and then try to hear any sound on either other end of the call or during playing video back.

**Comment by MarijnS95** [comment]
Without logs we can't do anything... You must be glad that we have found _some_ of these issues locally and have our own.

Normal recording should work. Calls are indeed broken (in voip too):
- In speaker mode:
  - Sound comes from the bottom speaker;
  - Input is recorded on the bottom mic.
- In earpiece/phone mode:
  - Sound still comes from the bottom speaker, at the same volume;
  - Audio input is not captured anywhere, not on the top nor bottom.

Mixer paths can tell us whether speaker mode is supposed to use stereo recording and stereo playback; on Akatsuki speaker mode used to run on opposite sides: playback on the bottom speaker, recording on the top mic. Nowadays (in stock, I have yet to import that config) it should record on both and play back on both, using cancellation algorithms to filter out speaker feedback into the mics.

The funny thing is that before getting cirrus to work all audio was coming from the top speaker... Now I have never managed to get anything coming from there: not with forced stereo playback, nor with calls.
We definitely have some debugging to do here but there are no obvious DSP errors; audio just isn't flowing where it's supposed to go.

**Comment by AngryGami** [comment]
> Normal recording should work

And yet it doesn't for me... :(

> Without logs we can't do anything...

Do you want logs from device start or just for period when video recorded/call made? Dmesg logs and/or logcat?

**Comment by MarijnS95** [comment]
@AngryGami I might have fixed this, including handset/earpiece during (voip) calls. Please let me know!

**Comment by AngryGami** [comment]
It works now :) thank you. Though only in voip calls - during recording video it still doesn't seem to work... maybe this is because of camera app so I don't care about that for now.

**Comment by MarijnS95** [comment]
@AngryGami I tested it in AOSP camera and it seems to work fine. What app are you using? Did audio and mic still work after that recording session?

**Comment by AngryGami** [comment]
I also tested it with AOSP camera app. Audio and mic still work after recording session. Recorded video doesnt have any sound though.

**Comment by MarijnS95** [comment]
Alllright, I'll try to revisit that case tonight and check again. Either audio recording or that specific case of media playback is borked :grin:

**Comment by MarijnS95** [comment]
@AngryGami There's definitely sound when recording with AOSP camera and playing back through VLC, though the volume is way too low. As it turns out the ["calibration"](https://github.com/MarijnS95/device-sony-pdx201/blob/00a5a65c45b90293987c403e4ef7a5ca557e252e/rootdir/vendor/etc/mixer_paths.xml#L2751-L2758) pulls down microphone gain _significantly_ in certain cases (routes/paths) but not others. We're confirming with stock what's going on because volume is significantly better, or rather normal on the default value of `102`.
