### ISSUE TITLE
[Yoshino][Lilac]Cannot receive sms messages

### ISSUE THREAD

**Issue by ergoen** [sonyxperiadev/bug_tracker#630]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14.194
**Android version:** 10
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v9c_yoshino

**Previously working on**
This is the my first attempt at building and flashing AOSP. SMS reception of course worked in the (one year old) stock rom.

**Description**
SMS messages can be sent from the device, but not received.

**Symptoms**
No SMS messages sent to my phone number arrive.

**How to reproduce**
1. Flash clean rom (no gapps, no anything, just the img files generated from the build).
2. Send a text message to a third party, ask for a reply.
3. Wait...
4. No reply arrives.

**Additional context**
PIN entry after boot is also a little bit sketchy as it asks for the PIN several times if I'm too fast with answering the prompt. If I wait for ~30 seconds before entering it it is accepted though.

I am not certain what sort of logs would be useful to debug this, I have attached both a logcat and a logcat -b radio here though from right after boot to scan through. I guess some sort of radio-error should probably be seen there already.
[logs.zip](https://github.com/sonyxperiadev/bug_tracker/files/5213010/logs.zip)

**Comment by Haxk20** [comment]
Could you please post logcat logcat of radio and dmesg after sending SMS message and waiting few seconds for response ?

**Comment by ergoen** [comment]
Ah, so the boot logs don't show anything useful? :/ I ended up re-flashing the stock rom for now. Will give it a new try next weekend (or the one after that), I will then try to capture logs around an sms conversation. If I'm alone in seeing this bug (I tried googling without any success), it might just be an edge-case with my operator or sim card version I suppose.

**Comment by Haxk20** [comment]
> Ah, so the boot logs don't show anything useful? :/ I ended up re-flashing the stock rom for now. Will give it a new try next weekend (or the one after that), I will then try to capture logs around an sms conversation. If I'm alone in seeing this bug (I tried googling without any success), it might just be an edge-case with my operator or sim card version I suppose.

Calling works ? But Im sure it does
Try to get those logs.
Also if you are up for some experimenting (don't capture log of this) try to get someone or some bot send you few SMS messages. We had one weird issue where I would not receive any sms messages until I got second sms message. Then both showed up.

**Comment by MarijnS95** [comment]
It's pretty clear that there are _a lot_ of problems occurring on this phone. Sensors are missing causing radio to die, either resulting in a waterfall killing the rest of the modem/telephony userspace system or those services dying due to other reasons.

@stefanhh0 What final sensor situation did we end up in on #580? Does resetting `/persist/sensors` with "the script" (:ghost:) resolve it fully now that modem has been "stabilized"?

There's no matching _nor default_ modem firmware either:

<details>
<summary>ModemSwitcher missing default configuration</summary>

```
09-12 18:59:15.604  4001  4001 I /odm/bin/hw/vendor.somc.hardware.modemswitcher@1.0-service: Registering HAL: vendor.somc.hardware.modemswitcher@1.0::IModemSwitcher with name: default
09-12 18:59:15.605  4001  4001 I ServiceManagement: Registered vendor.somc.hardware.modemswitcher@1.0::IModemSwitcher/default (start delay of 245ms)
09-12 18:59:15.605  4001  4001 I ServiceManagement: Removing namespace from process name vendor.somc.hardware.modemswitcher@1.0-service to modemswitcher@1.0-service.
09-12 18:59:15.606  3995  3995 I         : ModemSwitcherWrapper: find_matching_mbn:Link to death notification successful!
09-12 18:59:15.606  4001  4001 V modem-switcher: [ms_file_stat:23] Failed to stat: path = /vendor/firmware_mnt/image/modem_pr/mcfg/configs/mcfg_sw/mapping.txt, errno = 2 (No such file or directory)
09-12 18:59:15.607  4001  4001 V modem-switcher: [ms_file_stat:23] Failed to stat: path = /firmware/image/modem_pr/mcfg/configs/mcfg_sw/mapping.txt, errno = 2 (No such file or directory)
09-12 18:59:15.607  4001  4001 D modem-switcher: [ms_mcfg_find_matching_mbn:959] No mapping file exist
09-12 18:59:15.607  4001  4001 E         : ModemSwitcher::ModemSwitcherFindMatchingMbn: Failed to find matching modem
09-12 18:59:15.607  3995  3995 E         : ModemSwitcherWrapper: find_matching_mbn: ModemSwitcherFindMatchingMbn failed.
09-12 18:59:15.608  3995  3995 D modem-switcher: [ms_ta_read_default_modem:98] Failed to find matching default mbn
09-12 18:59:15.608  3995  3995 D modem-switcher: [main:194] Unable to find out the default modem mbn from TA to use
09-12 18:59:15.608  3995  3995 V modem-switcher: [ms_file_stat:28] Failed to stat: path = /oem/modem-config/modem.conf, errno = 2 (No such file or directory)
09-12 18:59:15.609  3995  3995 D modem-switcher: [ms_prop_read_default_modem:575] Default modem conf not found: /oem/modem-config/modem.conf
09-12 18:59:15.609  3995  3995 D modem-switcher: [main:199] Unable to find default modem in oem, checking ta
09-12 18:59:15.609  3995  3995 V modem-switcher: [ms_ta_read_default_modem:74] Read default modem
09-12 18:59:15.611  3995  3995 V modem-switcher: [read_bandconfig_unit:33] Read bandconfig unit
09-12 18:59:15.613  3850  3850 D TelephonyProvider: subIdString = 1 subId = 1
09-12 18:59:15.614  3995  3995 V modem-switcher: [read_bandconfig_unit:63] Read bandconfig unit ok
09-12 18:59:15.615  3995  3995 D modem-switcher: [ms_ta_read_default_modem:92] Default TA band configuration: L1234578_12_13_17_19_20_26_28_29_32_38_39_40_41_42_66LCA1234578_12_13_17_19_20_28_29_32_38_40_41_42_66W124568_19
09-12 18:59:15.616  4001  4001 V modem-switcher: [ms_file_stat:23] Failed to stat: path = /vendor/firmware_mnt/image/modem_pr/mcfg/configs/mcfg_sw/mapping.txt, errno = 2 (No such file or directory)
09-12 18:59:15.617  4001  4001 V modem-switcher: [ms_file_stat:23] Failed to stat: path = /firmware/image/modem_pr/mcfg/configs/mcfg_sw/mapping.txt, errno = 2 (No such file or directory)
09-12 18:59:15.617  4001  4001 D modem-switcher: [ms_mcfg_find_matching_mbn:959] No mapping file exist
09-12 18:59:15.617  4001  4001 E         : ModemSwitcher::ModemSwitcherFindMatchingMbn: Failed to find matching modem
09-12 18:59:15.618  3995  3995 E         : ModemSwitcherWrapper: find_matching_mbn: ModemSwitcherFindMatchingMbn failed.
09-12 18:59:15.618  3995  3995 D modem-switcher: [ms_ta_read_default_modem:98] Failed to find matching default mbn
09-12 18:59:15.618  3995  3995 D modem-switcher: [main:202] Unable to find out the default modem mbn to use
09-12 18:59:15.619  3995  3995 D modem-switcher: [ms_prop_ensure_executed:691] Setting: sony.modemswitcher.executed to 1
09-12 18:59:15.620  1016  1016 W NotificationService: Removed summary didn't match old notification: old=0|com.sony.opentelephony.modemconfig|1|null|10079, removed=0|com.sony.opentelephony.modemconfig|1|null|10079
09-12 18:59:15.621  3995  3995 D modem-switcher: [main:256] Modem switcher exiting, status: 1
```

</details>

This may not be fatal as the modem retains firmware from stock, but might be problematic when switching to a different provider while on stock, or having never booted stock with SIM inserted at all.

For now we should probably figure out sensors or disable `TransPower` in your build so that telephony stays alive, then try again.

**Comment by ergoen** [comment]
As an extra detail, after re-flashing the stock rom I received all the text messages that had been sent to me while being on the AOSP build :p.

**Comment by MarijnS95** [comment]
@ergoen At least that's kinda nice...

How'd you flash stock? I've been told you need to have the absolute latest version, and we're not sure if the one on [emma](https://developer.sony.com/develop/open-devices/get-started/flash-tool/download-flash-tool/) adheres to that.
Furthermore sensors seem to work about every other boot. If it doesn't, simply rebooting the phone should kick them off again. We're not sure what causes this very strange behaviour yet; likely a race condition with the SSC.

If you're attempting SODP again be sure to remove [transpower](https://github.com/sonyxperiadev/transpower) from the build and see whether things magically start to work, even when sensors are broken. This is a dependency we might want to relax some time in the future anyway.

**Comment by stefanhh0** [comment]
I checked it on my yoshino, required previously flashed stock has to be: `47.2.A.11.228`.
Please check with `fastboot getvar version-baseband` command if that is the case, if not flash that version (I hope it is available in emma). Boot up the stock with inserted SIM card, verify that fastboot shows the expected version-baseband, afterwards flash aosp.

**Comment by stefanhh0** [comment]
> @stefanhh0 What final sensor situation did we end up in on #580? Does resetting /persist/sensors with "the script" (ghost) resolve it fully now that modem has been "stabilized"?

@MarijnS95 the sensors problem has not been solved fully, however it has been mitigated by Angelos changes a lot, so if the sensor crashes then the modem normally always recovers, however when the sensors are crashing another reboot is required.

I never had problems to receive SMS or getting phone calls when the telco signal was there and modem was up. So my only idea is, that it is related with version-baseband that is used here.

Btw. with the currently in testing v11 SW binaries, my modem didn't came up. Alin said, there was no change in that area so maybe some copy/extract error? I haven't looked into it. Alin suggested to diff the files contained in v9c (resp. v10) and v11.

**Comment by ergoen** [comment]
@stefanhh0 The stock build number before flashing AOSP was 47.2.A.11.228, it is now again. 

@MarijnS95 Re-flashing stock was indeed a bit more tricky than I expected. I first tried Emma, but when I selected the correct region (nordic), I ended up with a two-year old Android 8 version (47.1.something) instead of the one I had earlier. After that I instead opted to use Xperifirm to download the image files  (same region) and flash them using a third-party tool. Now I'm back on the same build version as before.

I will make an attempt at building an AOSP without transpower before the weekend. I will need some googling first though to figure out how to disable that. I imagine that the reason for having to enter the PIN multiple times if I'm too quick at boot was related to the crashes and restarts of some radio items that you mentioned above.

An added note that I didn't think was related before (therefore I didn't mention it in the original bug report):
My first test of flashing the AOSP rom was actually with a custom recovery with which I installed gapps. This resulted in a seemingly working device (still without sms reception abilities). Rebooting it however caused bootloops. I didn't really have any abilities to figure out what was going on here, that's why I tried just the pure AOSP next (without the custom recovery or gapps). In this case rebooting worked, but the sms reception still didn't. That's the story behind the bug report :p

**Comment by MarijnS95** [comment]
@stefanhh0 Do you remember if resetting `/persist/sensors` improved/changed the situation or just broke the entire thing? (Some platforms can't restore it so the cleanup method doesn't work :/)

@ergoen Let's wait disabling TransPower for now; I'm sure you'd like working sensors as well :wink:

Start flashing a normal AOSP build and see in the logs whether radio is still crashing repeatedly due to sensors (`AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.sony.transmitpower.sensor.FeatureIntentReceiver: java.lang.IllegalStateException: Sensor is null.`). Then we can work our way from there:

1. Reset `/persist/sensors` and see if sensors come up every odd boot;
2. [if 1. fails] Disable sensors (`TransPower`) and see if modem and sms capabilities return; you won't find this on google but I'll explain in due time, there are about 10 different ways to do this :stuck_out_tongue:.

**Comment by stefanhh0** [comment]
Cleaning `/persist/sensors` does not change a lot from my experience. Howeve given it a try might be worth. It would be best to find the root cause for the failing sensors. In case it is a timing sensitive race problem, I may not run into it that often because my phone has a little different timing behaviour. 

@ergoen How often do you run into the "Sensor is null." problem when booting? Is it occurring on every boot or just once in a while? Additionally, you write you don't receive SMS messages, so phone calls are working while you don't get SMS messages? Or are phone calls as well not possible then (which means modem is fully down)? I didn't had any issue yet of just not being able to receive SMS messages while phone calls were working without problems (or I didn't notice it yet). I only get relatively seldom an SMS message, only one or two per month...

**Comment by ergoen** [comment]
@stefanhh0 I will re-flash the AOSP rom in the weekend and check the sensor logs. I could send sms messages so the radio was not fully down. I did not attempt any phone calls, I will try that too (both incoming and outgoing) this weekend if it helps debug the issue.

**Comment by MarijnS95** [comment]
. Cleaning /persist/sensors does not change a lot from my experience. However giving it a try might be worth.

**Comment by haldi4803** [comment]
**Platform:** Tama
 **Device:** Akari
 **Kernel version:** 4.14.217
 **Android version:** 11
 **Software binaries version:**  SW_binaries_for_Xperia_Android_11_4.14_v4b_tama

Same thing happening here: Can't send or receive SMS.
Logcat: https://drive.google.com/file/d/1jibI3-S_-H1Ox00SBe-mO7qDJIJ4mwzy/view?usp=sharing

So i thought me be a bug in the binaries and tried the old version for Android 10: SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_tama
And for whatever reason i was able to receive 1-2 SMS, but then few minutes later it broke down again.
https://drive.google.com/file/d/15CNHQ5aglk4JAopSrUXeML1mw8DccvO8/view?usp=sharing
https://drive.google.com/file/d/13V9KWSc3UhTK6_J0QGxipqhc-Q0Qe3Wc/view?usp=sharing

So i did a clean install without much other stuff and no gapps. Sent one sms and should have received two but didn't get anything.
https://drive.google.com/file/d/1YETrcinsN56EqqB7JM8HVxV-hDjbq4St/view?usp=sharing

**Comment by jerpelea** [comment]
Discontinued Android version
