### ISSUE TITLE
[Yoshino] [Poplar] unable to build android-11.0.0_r1

### ISSUE THREAD

**Issue by NextGeneration9501** [sonyxperiadev/bug_tracker#631]
This is my first time attempting to build android 11 for xz1. I've followed android 10 sony aosp building guide except that i used android 11 branch as i saw there is android-11.0.0_r1 present in sony local_manifest on github. but i got errors instead.

how to produce the error?
- follow aosp 10 building guide from Sony except use android-11.0.0_r1 instead
- at lunch, select aosp_g8341-userdebug (number 13)

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=11
TARGET_PRODUCT=aosp_g8341
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a73
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=cortex-a73
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.4.0-1021-gcp-x86_64-Ubuntu-20.04.1-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=RP1A.200720.009
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/sony/yoshino vendor/qcom/opensource/core-utils
============================================
[100% 1/1] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b 
out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build
-globs.ninja -o out/soong/build.ninja Android.bp
error: vendor/qcom/opensource/vibrator/Android.bp:1:1: module "vendor.qti.hardwa
re.vibrator@1.2-service" variant "android_vendor.30_arm64_armv8-a_cortex-a73": d
epends on //system/libhidl:libhidltransport which is not visible to this module
error: vendor/qcom/opensource/vibrator/Android.bp:1:1: module "vendor.qti.hardwa
re.vibrator@1.2-service" variant "android_vendor.30_arm64_armv8-a_cortex-a73": d
epends on //system/libhwbinder:libhwbinder which is not visible to this module
12:56:33 soong bootstrap failed with: exit status 1

#### failed to build some targets (23 seconds) ####

**Comment by MarijnS95** [comment]
Android 11 is far from ready; even though we have it booting there are still quite a few kinks to iron out.

As a matter of fact the changes to resolve these errors were merged yesterday, you should sync again.

Unless you're willing to run into more issues, resolve these (and submit the fix upstream), I can only advise to wait at least a month or 2 before this is properly tested and ready for daily usage.
