### ISSUE TITLE
[ganges][kirin] Bootloop with "Your device is corrupt" message after flashing android 10

### ISSUE THREAD

**Issue by AngryGami** [sonyxperiadev/bug_tracker#632]
**Platform:** Ganges
**Device:** kirin (i4113)
**Kernel version:** 4.14 (at least from what I can see in the platform config)
**Android version:** 10
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v9c_ganges.img

**Previously working on**
Android 9 worked.

**Description**
After making following:
```
> lunch aosp_i4113-userdebug
> make -j24
> cd out/target/product/kirin
> fastboot flash oem SW_binaries_for_Xperia_Android_10.0.7.1_r1_v9c_ganges.img
Sending 'oem' (252444 KB)                          OKAY [  9.940s]
Writing 'oem'                                      OKAY [ 23.497s]
Finished. Total time: 33.440s
> fastboot flashall
--------------------------------------------
Bootloader Version...: 1310-0301_X_Boot_SDM630_LA3.0_P_32
Baseband Version.....: 1318-6120_53.0.A.4.74
Serial Number........: CQ3001J0ZK
--------------------------------------------
Checking 'product'                                 OKAY [  0.001s]
Setting current slot to 'a'                        OKAY [  0.008s]
Sending 'boot_a' (22661 KB)                        OKAY [  0.897s]
Writing 'boot_a'                                   OKAY [  0.161s]
Sending sparse 'system_a' 1/3 (515236 KB)          OKAY [ 20.643s]
Writing 'system_a'                                 OKAY [  0.000s]
Sending sparse 'system_a' 2/3 (514408 KB)          OKAY [ 20.830s]
Writing 'system_a'                                 OKAY [  0.000s]
Sending sparse 'system_a' 3/3 (209988 KB)          OKAY [  8.600s]
Writing 'system_a'                                 OKAY [  0.000s]
Sending 'vendor' (57144 KB)                        OKAY [  2.298s]
Writing 'vendor'                                   OKAY [  0.000s]
Rebooting                                          OKAY [  0.430s]
Finished. Total time: 55.813s
```

**Symptoms**
Device refuse to boot. It shows following message:
![20200916_1248112](https://user-images.githubusercontent.com/2470910/93330546-3da32c80-f81f-11ea-904c-e9bf7fa000ae.jpg)
I seems that build is lacking some important images like dtbo.img and vbmeta.img. At least I can't see these in output directory.

**How to reproduce**
Build latest state of sources and flash image to a device.

**Comment by MarijnS95** [comment]
Ganges is pretty much identical to Nile and doesn't have dtbo (everything is appended to the kernel) nor vbmeta (AVB 2.0), it still uses verity.

Did you wipe userdata? The encryption mechanism/scheme changed iirc.

**Comment by AngryGami** [comment]
No, I didn't wipe userdata. To do that do I need to flash userdata.img from output dir?

**Comment by MarijnS95** [comment]
Flash `userdata` or use `fastboot -w`, either works.

**Comment by AngryGami** [comment]
Ok.. wiping userdata helps. Thanks :)

**Comment by MarijnS95** [comment]
@AngryGami Nice!

It's a bit unfortunate users can't keep their data between 4.9 -> 4.14, but that's just how it is :(
