### ISSUE TITLE
[TAMA] Latest AOSP 11 builds r1/r4 and SW for Android 11 incompatibles

### ISSUE THREAD

**Issue by jevgenp** [sonyxperiadev/bug_tracker#635]
**Platform:** TAMA
**Device:** H8324
**Kernel version:** 4.14
**Android version:** 11
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.14_v1a_tama.img

**Previously working on** -

**Description**
AOSP 11 builds r1/r4 only works with Latest SW for Android 10 (ANDROID_10.0.7.1_R1_V11A_TAMA).
With Latest SW for Android 11 (ANDROID_11_4.14_V1A_TAMA) - booting stucks on Android logo.

**How to reproduce**
Flash AOSP 11 r1/r4 build, flash SW ANDROID_11_4.14_V1A_TAMA.

**Comment by jerpelea** [comment]
@jevgenp I tested tama and it boots fine 
please update your firmware with EMMA

**Comment by jevgenp** [comment]
I was on latest stock FW (52.1.A.3.49) before flashing AOSP , but ok I'l try EMMA.

**Comment by jerpelea** [comment]
can you please try 52.0.A.x.x

**Comment by MarijnS95** [comment]
Is there a particular reason the log request from the issue template has been explicitly removed?

Booting into the android boot animation (as opposed to the Sony logo) means `adb` is likely up with easy access to logs. In this state the phone is likely hanging for one or more mandatory services that refuse to start or crash, but without logs we cannot guess what it is.

**Comment by jevgenp** [comment]
Same here flashing over 52.0.A.11.32 fw.
What about log, when I connect phone with stucked Android logo:

```
C:\adb>adb logcat > log.txt
- waiting for device -
```
Or am I doing something wrong?

**Comment by MarijnS95** [comment]
@jevgenp Did you grant adb access through the UI when the device started on 10 blobs or through `PRODUCT_ADB_KEYS := $(HOME)/.android/adbkey.pub` in the build? I don't recall if this is a case where `adb` should immediately show a key mismatch rather than waiting for the device to accept.

**Comment by jevgenp** [comment]
With 10 blobs flashed over 11 blobs (after booting stucked on logo):
I didn't change anything after system booted.
```
C:\adb>adb devices -l
List of devices attached
BH904N20BZ             device product:aosp_h8324 model:Xperia_XZ2_Compact_Dual__AOSP_ device:apollo transport_id:10
```
`C:\adb>adb logcat > log.txt`
[log.txt](https://github.com/sonyxperiadev/bug_tracker/files/5340631/log.txt)

So, as I understand - access granted.

**Comment by MarijnS95** [comment]
@jevgenp I didn't mean to grab them with 10 blobs as that won't show us the issue, but to accept (and remember!) `adb` debugging here, before flashing and booting into 11 blobs again.

If the device still doesn't present itself to `adb` we know the blob and ROM combination break init very early, before `adbd` is started.

**Comment by jevgenp** [comment]
Ok, I flashed again 11 blobs - and still waiting for devices.
