### ISSUE TITLE
[Ganges][Kirin] Speaker and microphone are messed up in VoIP call on Android 10

### ISSUE THREAD

**Issue by AngryGami** [sonyxperiadev/bug_tracker#638]
**Platform:** Ganges
**Device:** Kirin
**Kernel version:** 4.14
**Android version:** 10
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v11a_ganges.img 

**Previously working on**
Android 9 build for this device doesn't have this problem.

**Description**
When making VoIP call speaker and microphone that are activated by default (i.e. normal configuration NOT a loud speaker mode) are mixed up from expected. Instead of bottom microphone and top speaker - bottom speaker and top microphone are activated.

**How to reproduce**
Install any Sip application (e.g. Linphone for android) and make a sip call using it (incoming or outgoing).

**Additional context**
I have Android 9 imaged kirin device that doesn't have this issue so I've compared relevant xml files from that device and my current Android 10 build. Differences that I've found are in two files: mixer_paths.xml and audio_policy_configuration.xml. Most of the changes in audio_policy_configuration.xml file are cosmetic - configuration elements are extracted into separate files (e.g. common_primary_audio_policy_configuration.xml) or split into two different files (e.g. a2dp_in_audio_policy_configuration.xml and bluetooth_audio_policy_configuration.xml), overall content though is more or less identical.
mixer_path.xml is changed slightly:
1) MultiMedia8 in some paths is replaced with either MultiMedia3 or MultiMedia5.
2) new path is added in Android 10:
```
    <path name="voice-headset">
        <path name="voice-headphones" />
    </path>
```
I don't know what does this mean, but after I've commented out this path - everything (so far) get back to normal. 
I see that this change was introduced by [this commit](https://github.com/sonyxperiadev/device-sony-kirin/commit/f05bc48515c68f4bf98f68d76f4b248356b126f3) and should fix wired headsets, but it has side-effect apparently.

**Comment by MarijnS95** [comment]
Without logs all we can do is guess about this issue and the route it is trying to take. If the HAL is selecting `voice-headset` when it tries to make a HANDset call something is seriously messed up elsewhere.

**Comment by AngryGami** [comment]
I restored this path, rebuild image and can't reproduce this issue anymore... something else got it fixed, not this change. Maybe it will show up again later then I'll make a new issue for that.

**Comment by MarijnS95** [comment]
Feel free to reopen this in that case, to retain context. Though I heavily doubt there's any relation to `voice-handset`; I checked this yesterday on Mermaid (as promised in the other issue) and could not reproduce either.

**Comment by AngryGami** [comment]
As for this bug - I have to rely on user reports about that since I don't have Kirin device myself. Now they report - everything is fine... :) who knows what was that previously...
