### ISSUE TITLE
[Seine/Ganges][pdx201/kirin] Exception "vendor.qti.iwlan package not found"

### ISSUE THREAD

**Issue by AngryGami** [sonyxperiadev/bug_tracker#640]
**Platform:** Seine and Ganges
**Device:** pdx201 and kirin
**Kernel version:** 4.14
**Android version:** 10
**Software binaries version:**  latest available for both devices

**Previously working on**
Maybe on Android 9, but I'm not sure.

**Symptoms**
```
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: PackageNot found: vendor.qti.iwlan
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: android.content.pm.PackageManager$NameNotFoundException: vendor.qti.iwlan
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:190)
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:159)
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.getPackageInfo(DefaultPermissionGrantPolicy.java:1317)
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.getPackageInfo(DefaultPermissionGrantPolicy.java:1308)
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.isSystemPackage(DefaultPermissionGrantPolicy.java:963)
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantPermissionsToSystemPackage(DefaultPermissionGrantPolicy.java:364)
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantSystemFixedPermissionsToSystemPackage(DefaultPermissionGrantPolicy.java:350)
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: 	at com.android.server.pm.permission.DefaultPermissionGrantPolicy.grantDefaultPermissionsToEnabledTelephonyDataServices(DefaultPermissionGrantPolicy.java:848)
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: 	at com.android.server.pm.PackageManagerService.lambda$grantDefaultPermissionsToEnabledTelephonyDataServices$36$PackageManagerService(PackageManagerService.java:25256)
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: 	at com.android.server.pm.-$$Lambda$PackageManagerService$Jk56TooKBJVbCXzf9mkL2I94Ey0.runOrThrow(Unknown Source:6)
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: 	at android.os.Binder.withCleanCallingIdentity(Binder.java:357)
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: 	at com.android.server.pm.PackageManagerService.grantDefaultPermissionsToEnabledTelephonyDataServices(PackageManagerService.java:25255)
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4346)
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4059)
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
10-26 08:58:18.962  1265  1850 E DefaultPermGrantPolicy: 	at android.os.Binder.execTransact(Binder.java:994)
```

**How to reproduce**
This happens during boot - so just need a reboot.

**Additional context**
I've found which apk file actually implements this package:
`/odm/system_ext/app/IWlanService/IWlanService.apk`
But even that this apk is there - it never get installed on the device:
```
> pm list packages -a -f -l vendor.qti
```
This might be how it intended to be, but this exception bothers me and I have some strange issues (which I need to confirm first) with data connection over cellular network that seems to be related to this exception.

**Comment by sjllls** [comment]
@AngryGami  Hi, Is VoLTE fine for you? On Android 10.0 or 11.0 ?

**Comment by AngryGami** [comment]
VoLTE doesn't work on these devices as far as I understand because cell network provider must somehow recognize them... I assume that Sony provide support for VoLTE in their binaries, but I can't be 100% sure and have no means to test that.

**Comment by jerpelea** [comment]
@MarijnS95

**Comment by MarijnS95** [comment]
@jerpelea I have no idea about VoLTE in its entirety, but this error is an easy fix for a small oversight.

**Comment by AngryGami** [comment]
Hm... I've tried to install one of these apps just manually and got a failure:
```
Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Reconciliation failed...: Reconcile failed: Package org.codeaurora.ims has no signatures that match those in shared user android.uid.phone; ignoring!]
```
Which make me realize that these applications are signed with some key that is not part of AOSP build. I'm not using default keys for my image because I need my own system applications installed there (some of which are already in production and I can't change how they are signed).
I can pull apk files for these apps from odm partition on the device and re-sign them with my key, though I can't put them on odm partition back obviously. The question is - will that work?

**Comment by MarijnS95** [comment]
@AngryGami Yeah, shared user is the problem!

Our initial attempt was to allow the signature Sony signs these apps with (since they have to be provided in odm instead of on GH as blobs to be resigned in a build, _for some reason_). Attempt here: https://github.com/MarijnS95/device-sony-sepolicy/commit/565d0f9f6e743791345482a3c20b932991e86155 and https://github.com/MarijnS95/device-sony-sepolicy/commit/c797af54e0788aeae0a41f8ec3488fb43f5e3579.

While that allows these apps to run as `domain=platform_app`... the signature should still be identical to other apps with shared user `android.uid.phone` :(

Custom roms [solve this](https://github.com/PixelExperience-Devices/device_sony_customization/blob/ten/ims/Android.mk) by including these apks in their build and re-sign them. But we never continued to figure out how to solve this for SODP. The main problem being these apps completely stomping over system<->vendor boundaries set up by AOSP. They are vendor-specific yet "belong" in system to integrate with all the private APIs. Even if we solve this it's going to break on GSIs.

**Comment by AngryGami** [comment]
I don't mind re-signing them. The problem as I see it is that I can only put them either under either system, product or vendor "roots". Which one to choose?
Does having these apps not under `/odm/<whatever>` make any difference?

**Comment by AngryGami** [comment]
I've tested this approach from [here](https://github.com/PixelExperience-Devices/device_sony_customization/blob/ten/ims/Android.mk) and even that applications get installed some of them are failing with error like this:
```
...
11-19 11:25:53.003 13068 13068 E linker  : library "/odm/lib64/libimsmedia_jni.so" ("/odm/lib64/libimsmedia_jni.so") needed or dlopened by "/apex/com.android.runtime/lib64/libnativeloader.so" is not accessible for the namespace: [name="vendor-classloader-namespace", ld_library_paths="", default_library_paths="/vendor/lib64", permitted_paths="/data:/mnt/expand:/data/data/org.codeaurora.ims:/vendor/lib64"]
11-19 11:25:53.003 13068 13068 D AndroidRuntime: Shutting down VM
11-19 11:25:53.003 13068 13101 I QImsService: ImsRadioResponse : queryServiceStatusResponse()
11-19 11:25:53.003 13068 13101 I QImsService: ImsRadioResponse : queryServiceStatusResponse_1_6()
11-19 11:25:53.003 13068 13101 I QImsService: IFRequest : [0001]< REQUEST_QUERY_SERVICE_STATUS error: 2
11-19 11:25:53.003 13068 13068 E AndroidRuntime: FATAL EXCEPTION: main
11-19 11:25:53.003 13068 13068 E AndroidRuntime: Process: com.android.phone, PID: 13068
11-19 11:25:53.003 13068 13068 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "/odm/lib64/libimsmedia_jni.so" needed or dlopened by "/apex/com.android.runtime/lib64/libnativeloader.so" is not accessible for the namespace "vendor-classloader-namespace"
11-19 11:25:53.003 13068 13068 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
...
```
As I was afraid... Any ideas how to fix that?

**Comment by AngryGami** [comment]
Ok. I managed to apply strategy that PixelExperience-Devices uses properly and now VoLTE works. Key part was to put these application into product partition (not vendor and not system) and mount `/odm/lib64` to `/product/priv-app/ims/lib/arm64`.

**Comment by sjllls** [comment]
> Ok. I managed to apply strategy that PixelExperience-Devices uses properly and now VoLTE works. Key part was to put these application into product partition (not vendor and not system) and mount `/odm/lib64` to `/product/priv-app/ims/lib/arm64`.

Glad to hear that, could you plz share your build to me, I could not use PC these days, so I can't build myself.

**Comment by MarijnS95** [comment]
> I don't mind re-signing them. The problem as I see it is that I can only put them either under system, product or vendor "roots". Which one to choose?
> Does having these apps not under `/odm/<whatever>` make any difference?
> 
> There is bunch of jar files in `/odm/system_ext/framework` that seem related to these applications - can new location of apk files make these jars inaccessible to them?

It definitely matters where they are, and because they "can" only be redistributed through the oem image they are bind-mounted into place (product or system, not vendor). Though the PE build script should turn that off (`TARGET_USES_ODM_APPS_BINDMOUNT`) in favour of emitting resigned apks to `product` directly.

Unfortunately the shared user signing issue means these efforts were futile (for SODP, not custom builds that re-sign the apps).

> I also can't find any related permissions xml files in odm partition and as far as I know android explicitly require that these files must be on same partition where apk files are installed from.

None of these apps (except `dpmserviceapp`, see `privapp-permissions-ims` in common) are `priv-app` :)

**Comment by AngryGami** [comment]
> Unfortunately the shared user signing issue means these efforts were futile (for SODP, not custom builds that re-sign the apps).

Are you saying that SODP build cannot produce functional image? :) Technically I don't use SODP directly, I use it as a baseline for custom ROM. 

> Though the PE build script should turn that off (TARGET_USES_ODM_APPS_BINDMOUNT) in favour of emitting resigned apks to product directly.

It is very hard for me to understand these configuration parameters so I only adopted parts of PE build that I understand.

**Comment by MarijnS95** [comment]
> Are you saying that SODP build cannot produce functional image? :) Technically I don't use SODP directly, I use it as a baseline for custom ROM.

If by "cannot produce functional image" you mean "cannot provide working VoLTE given the constraints applied to the official repos" specifically, then yes.

> It is very hard for me to understand these configuration parameters so I only adopted parts of PE build that I understand.

Since it's working you have understood what to do just fine :+1:

**Comment by AngryGami** [comment]
Ok, I think this can be closed. Thanks everybody.
