### ISSUE TITLE
tama  AKATSUKI /aosp11/ problem sound in call, video.

### ISSUE THREAD

**Issue by NYGGAZ** [sonyxperiadev/bug_tracker#642]
**Platform:** tama
**Device:** h9436
**Kernel version:** 4.14.196-g7aaaf731280bc-dirty
#1 Thu Oct 8 12:51:35 CEST 2020
**Android version:** 11
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.14_v1a_tama.

**Description** 1 
During a phone call, it is not possible to change the volume of the speaking staff.  the volume level of the voice remains very loud and always at the same level.  impossible to lower this volume during a call.

**Description** 2 
videos have white lines during playback.  like frying.

**Comment by mumiby** [comment]
I happen to have the description 2 issue in video playback, some games, locking screen dim animation, scrolling images. But I have AOSP 10 and the lastet android 10 sony binaries. Force MSAA 4x may reduce the effect by a little. But if you disable HW overlays it get worse and all over the UI. My thoughts on this is that there is HW acceleration bug...

**Comment by NYGGAZ** [comment]
> I happen to have the description 2 issue in video playback, some games, locking screen dim animation, scrolling images. But I have AOSP 10 and the lastet android 10 sony binaries. Force MSAA 4x may reduce the effect by a little. But if you disable HW overlays it get worse and all over the UI. My thoughts on this is that there is HW acceleration bug... 

thank you.  you are right .  i enabled msAA and it looks better.  thanks bro😉

**Comment by mumiby** [comment]
> thank you. you are right . i enabled msAA and it looks better. thanks bro😉

Unfortunately it will drain your battery fast... The LOS 17.1 rom seems to be less glitchy... It is sad the project was stopped

**Comment by MartinX3** [comment]
> > thank you. you are right . i enabled msAA and it looks better. thanks bro😉
> 
> Unfortunately it will drain your battery fast... The LOS 17.1 rom seems to be less glitchy... It is sad the project was stopped

I'm sorry but with the appearing stock based official LOS I lost my motivation to do "double work".
But after I got more free time, I want to make an Android 11 ArrowOS port based in SODP :)

**Comment by jerpelea** [comment]
Discontinued Android version
