### ISSUE TITLE
TAMA/AKATSUKI/AOSP11 /problem video

### ISSUE THREAD

**Issue by NYGGAZ** [sonyxperiadev/bug_tracker#643]
Platform: tama
Device: h9436
Kernel version: 4.14.196-g7aaaf731280bc-dirty
#1 Thu Oct 8 12:51:35 CEST 2020
Android version: 11
Software binaries version: SW_binaries_for_Xperia_Android_11_4.14_v1a_tama.

**Description**

videos have white lines during playback. like frying.

**Comment by mumiby** [comment]
Hello
I have the same issue with aosp 10 with the latest android 10 sw binaries while scrolling pictures on G photo, fullscreen and landscape video playback especially on streaming, locking screen and some . It's as some stripes of screen noise appearing randomly, when you disable HW overlays in dev options it is getting worse and all over the UI

**Comment by NYGGAZ** [comment]
> Hello
> I have the same issue with aosp 10 with the latest android 10 sw binaries while scrolling pictures on G photo, fullscreen and landscape video playback especially on streaming, locking screen and some . It's as some stripes of screen noise appearing randomly, when you disable HW overlays in dev options it is getting worse and all over the UI

ho ok.  so on aosp 10 too.  hope this will be fixed.  because it is painful.
