### ISSUE TITLE
AOSP11 / pioneer camera only works once

### ISSUE THREAD

**Issue by sbourdeauducq** [sonyxperiadev/bug_tracker#646]
**Device:** Xperia XA2 dual (pioneer)
**Kernel version:** 4.14.196
**Android version:** 11
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.14_v2a_nile.img

**Description**
The back camera can only be used once per device boot.

**Symptoms**
Error "failed to connect to camera"; picture corrupted (only the green channel, out of focus and with other artifacts), or no (black) picture.

**How to reproduce**
Open any camera app, close it, open it again. It won't work the second time and until you reboot the device.

**Comment by sbourdeauducq** [comment]
Errors logged:
```
11-05 16:27:43.256   667  5546 I mm-camera: <MCT   >< INFO> 1373: mct_controller_handle_SOF_proc: Remap pending request by 1, l=0, c=0, reg_update_fail=1
11-05 16:27:43.256   667  5546 I mm-camera: <MCT   >< INFO> 1273: mct_stream_update_all_frame_id_by: Delay all frame by 1
11-05 16:27:43.256   667  5546 I mm-camera: <MCT   >< INFO> 1264: mct_stream_update_frame_id_by: (fr_num, fr_id) = (1049, 265)
11-05 16:27:43.257   667  5546 I mm-camera: <MCT   >< INFO> 1264: mct_stream_update_frame_id_by: (fr_num, fr_id) = (1050, 266)
11-05 16:27:43.258   667  5546 I mm-camera: <IFACE >< INFO> 3451: iface_handle_control_sof: skip sent by MCT: 1 skip_frame_id: 263         q_idx: 0 max_apply_delay: 2 
11-05 16:27:43.258   667  5546 I mm-camera: <IFACE >< INFO> 12501: iface_util_adjust_paramq: 4. Swap q_idx[1] <--> q_idx[0]
11-05 16:27:43.292   667  5595 E mm-camera: <IFACE ><ERROR> 2423: iface_axi_handle_sof_event: Event SOF session 3 VFE0, src 0 with frame_id 264 ts: 1701427229000
11-05 16:27:43.292   667  5597 E mm-camera: <IFACE ><ERROR> 2423: iface_axi_handle_sof_event: Event SOF session 3 VFE1, src 0 with frame_id 264 ts: 1701427245000
11-05 16:27:43.331   667  5595 E mm-camera: <IFACE ><ERROR> 2423: iface_axi_handle_sof_event: Event SOF session 3 VFE0, src 0 with frame_id 265 ts: 1701465923000
11-05 16:27:43.331   667  5597 E mm-camera: <IFACE ><ERROR> 2423: iface_axi_handle_sof_event: Event SOF session 3 VFE1, src 0 with frame_id 265 ts: 1701465936000
11-05 16:27:43.335   667  5546 E mm-camera: <IMGLIB><ERROR> 5398: module_faceproc_client_send_info: Both processing and reporting streams are same or it is hal3
11-05 16:27:43.369   667  5597 E mm-camera: <IFACE ><ERROR> 2423: iface_axi_handle_sof_event: Event SOF session 3 VFE1, src 0 with frame_id 266 ts: 1701504633000
11-05 16:27:43.369   667  5595 E mm-camera: <IFACE ><ERROR> 2423: iface_axi_handle_sof_event: Event SOF session 3 VFE0, src 0 with frame_id 266 ts: 1701504619000
11-05 16:27:43.408   667  5597 E mm-camera: <IFACE ><ERROR> 2423: iface_axi_handle_sof_event: Event SOF session 3 VFE1, src 0 with frame_id 267 ts: 1701543327000
11-05 16:27:43.408   667  5595 E mm-camera: <IFACE ><ERROR> 2423: iface_axi_handle_sof_event: Event SOF session 3 VFE0, src 0 with frame_id 267 ts: 1701543315000
11-05 16:27:43.412   667  5546 E mm-camera: <IMGLIB><ERROR> 5398: module_faceproc_client_send_info: Both processing and reporting streams are same or it is hal3
11-05 16:27:43.447   667  5595 E mm-camera: <IFACE ><ERROR> 2423: iface_axi_handle_sof_event: Event SOF session 3 VFE0, src 0 with frame_id 268 ts: 1701582012000
11-05 16:27:43.447   667  5597 E mm-camera: <IFACE ><ERROR> 2423: iface_axi_handle_sof_event: Event SOF session 3 VFE1, src 0 with frame_id 268 ts: 1701582025000
```

**Comment by MarijnS95** [comment]
Green picture? I wonder if https://github.com/sonyxperiadev/bug_tracker/issues/469 is rearing its head on k4.14  as well.

**Comment by jerpelea** [comment]
@MarijnS95 that bug appers only on nile and when the kernel is not compiled with gcc. Ganges is not affected by it.

**Comment by sbourdeauducq** [comment]
I am using nile and the kernel was indeed compiled with clang (this is the prebuilt one):

Linux version 4.14.196-g7aaaf731280bc-dirty (root@seldlx21330.corpusers.net) (Android (5484270 based on r353983c) clang version 9.0.3 (https://android.googlesource.com/toolchain/clang 745b335211bb9eadfa6aa6301f84715cee4b37c5) (https://android.googlesource.com/toolchain/llvm 60cf23e54e46c807513f7a36d0a7b777920b5881) (based on LLVM 9.0.3svn)) #1 SMP PREEMPT Thu Oct 8 12:34:29 CEST 2020

**Comment by sbourdeauducq** [comment]
Is there a simple way to compile this one with GCC? It appears the build-kernels-gcc.sh script mentioned in #469 has been removed, and I am afraid to use the 4.9 kernel because I expect compatibility problems with the vendor images and the userspace.

**Comment by jerpelea** [comment]
@sbourdeauducq please use the build-kernels-gcc.sh  fom 4.9. The gcc compiler was deprecated by Google in AOSP but it should work ok.

**Comment by bartcubbins** [comment]
they removed it
https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+/fc97ce6abfe822403eb219dcbd1067a53c49e4f1

**Comment by sbourdeauducq** [comment]
I guess this should still work?
https://developer.sony.com/develop/open-devices/guides/kernel-compilation-guides/how-to-build-and-flash-a-linux-kernel-for-aosp-supported-devices

(Except I'd need to use repo to get the kernel sources, a simple git clone as suggested lacks some files - this doc probably needs an update)

**Comment by sbourdeauducq** [comment]
The doc also says:
"For building a new boot image with the compiled kernel, the kernel binary “arch/arm64/boot/Image.gz-dtb” has to be renamed “kernel-” and placed in the device/sony/common-kernel folder."

There is no device/sony/common-kernel folder.

**Comment by sbourdeauducq** [comment]
I assume it is kernel/sony/msm-4.14/common-kernel/kernel-dtb-pioneer now...

**Comment by sbourdeauducq** [comment]
Why can't I boot with ``fastboot boot boot.img`` to test changes, and actually need to flash the kernel...? When doing the former, the device freezes at the white "SONY" screen.

Anyway, the camera problem is not present with the kernel I compiled with GCC :) Thanks for the help!

**Comment by phpbg** [comment]
Hi
I experience this too on a XA2 (H3113).
Please let me know if I can help with testing.

Also can we have some clarifications on the [kernel compilation guide](https://developer.sony.com/develop/open-devices/guides/kernel-compilation-guides/how-to-build-and-flash-a-linux-kernel-for-aosp-supported-devices): there are multiple references to inexisting `device/sony/common-kernel`, both in manual and auto build of the kernel.

**Comment by sbourdeauducq** [comment]
It's been moved to ``kernel/sony/msm-4.14/common-kernel``.

**Comment by phpbg** [comment]
> Anyway, the camera problem is not present with the kernel I compiled with GCC :) Thanks for the help!

After a painful rebuild with gcc I too confirm the bug cannot be reproduced (doc is a bit outdated, and gcc removal from android repo does not help).

Anyway this should remain a temporary workaround. Please let us know when you figure the issue with clang

**Comment by phpbg** [comment]
> > Anyway, the camera problem is not present with the kernel I compiled with GCC :) Thanks for the help!

After a few hours on gcc built kernel, the bug appears from time to time randomly (while with clang, it is 100% reproducible).
It seems to be something wrong during camera initialization...

**Comment by Neo75T** [comment]
Please, is this camera bug fixed already?

**Comment by Neo75T** [comment]
So I reinstalled today AOSP 11 to XperiaXA2 (h4113) based on latest binaries SW_binaries_for_Xperia_Android_11_4.14_v3a_nile.img, but the issue with camera is still the same.
I used instructions here:
[https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-11-0-0#tutorial-step-6](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-11-0-0#tutorial-step-6)
I had to reflash the "userdata" partition also, since it stuck on android logo during boot. After this reflash everything is running good and it shows in settings Android security update January 5, 2021.
But it is a pitty, without camera working the phone is for me not usable (even rebooting after each use of camera app is not acceptable solution).

**Comment by sbourdeauducq** [comment]
> I had to reflash the "userdata" partition also, since it stuck on android logo during boot.

Yes, it's pretty amazing how buggy Android is.

> without camera working the phone is for me not usable

Recompile the kernel with gcc?

**Comment by sraase** [comment]
> Please, is this camera bug fixed already?

No, since it only affects Nile and a workaround (gcc-compiled kernel) is available. But feel free to dig into this, I would like to see this issue fixed as well.

**Comment by sbourdeauducq** [comment]
@Neo75T Are you also experiencing lousy GPS performance (https://github.com/sonyxperiadev/bug_tracker/issues/666)?

**Comment by phpbg** [comment]
> No, since it only affects Nile and a workaround (gcc-compiled kernel) is available. But feel free to dig into this, I would like to see this issue fixed as well.

So we can't expect support from Sony? I bought this phone because it was part of the open devices program, and i thought there would be better support...

Even if there is a workaround, it is far from perfect. As mentioned earlier, the camera still fails to load from time to time (at least a few times per day)

**Comment by sraase** [comment]
I know, and it bugs me too. But I have neither the time nor the knowledge to fix this, so my hope is that someone from the community can tackle this. It is a (subtle) kernel/compiler issue, so all necessary information is publicly available.

> So we can't expect support from Sony?

I cannot and do not speak for Sony.

**Comment by chris42** [comment]
> > No, since it only affects Nile and a workaround (gcc-compiled kernel) is available. But feel free to dig into this, I would like to see this issue fixed as well.
> 
> So we can't expect support from Sony? I bought this phone because it was part of the open devices program, and i thought there would be better support...
>
 
As talked about in the other thread, it is worthwhile mentioning here as well. It is an open device program, meaning, that Sony allows you to install non stock ROMs and also provides binaries and some organizational parts. The device upbringing, maintenance and the ROM you put on then, may it be pure AOSP or another flavour is completely up to the community. There are no Sony developers doing that.

If you feel that is not enough, you should see that Sony and Google (to my knowledge) are the only big manufacturers that support such thing: Offer AOSP compatible binaries and help on problems. For most other manufacturers all you get is an unlockable bootloader and everything else is up to the community.

**Comment by sbourdeauducq** [comment]
> ROM you put on then, may it be pure AOSP or another flavour is completely up to the community

This speaks volumes to how terribly managed Android is.

On non-phone computers, whether the camera works correctly or not does not depend on the Linux distribution (note: absence of silly "ROM" terminology) it is running. The component responsible for this is the Linux kernel, which is properly versioned, and the same version will give the same results whether it's running Debian, RedHat, Arch, NixOS, or whatever. Userspace may be broken or not, but that's cleanly separated and rather straightforward to debug.

Why can't Android do the same?

**Comment by MartinX3** [comment]
> Why can't Android do the same?

Because the phone vendors don't want to share and only want to use.
Like greedy leechers in P2P networks.
The want to be better than the others, they don't want to share and they want to make their products quickly obsolete, if you can buy the next generation of their products.

Luckily Sony and Google are a bit different with providing closed source drivers always compatible with the newest android version on supported devices. (As example the Xperia XZ2 got A11 compatible drivers, while on stock A10 is the last version; Custom ROM maintainers of other devices need to workaround old  drivers in newer Android versions if problems happen, or the can't fix it)

**Comment by sraase** [comment]
I would rather prefer this topic not to be discussed here. If there is a problem with the way Android is managed, it should be brought up with the people responsible for managing Android. Be assured that there are some good reasons for the current situation, but this is not an SODP discussion.

From my point of view, it would be much preferable to actually inspect the kernels build by both gcc and clang, and try to figure out the difference causing the camera to appear green and/or fail on Nile.

**Comment by phpbg** [comment]
Thank you guys for the clarifications.

Does anyone have a starting point where to look for?

I looked into [device platform configuration](https://github.com/sonyxperiadev/kernel/blob/aosp/LA.UM.7.1.r1/arch/arm64/configs/aosp_nile_pioneer_defconfig) but I don't even know the name of the driver responsible for the rear camera.

Do you know which driver is it and where is it's code?

Regards

**Comment by sbourdeauducq** [comment]
These I guess?
https://github.com/sonyxperiadev/kernel/blob/82f86c6b1182fdc948ef0d1132d82ad58a786af8/drivers/media/platform/msm/Kconfig

**Comment by sbourdeauducq** [comment]
BTW is this supposed to work on this phone or are there additional steps? https://source.android.com/setup/build/building-kernels#flashing-fastboot
When I tried it, it didn't work and the boot got stuck.

**Comment by sraase** [comment]
> Does anyone have a starting point where to look for?

The kernel drivers for devices using mm-camera live in sony/msm-4.14/kernel/drivers/media/platform/msm/camera_v2. If I remember correctly, the drivers in "camera" are used for CamX-based devices instead.

Most of the camera system is implemented in userspace and the public parts live in vendor/qcom/opensource/camera. The actual sensor drivers (e.g. imx300) are part of the vendor binary package, and their source code is not public. We already know that they are not causing the issue, though.

I have never looked too deeply into mm-camera, so I don't know which parts of the userspace implementation are public and which are not. Anyway, the interface to the kernel drivers is through the V4L2 API (i.e. /dev/media* and /dev/video* devices), and the initialization sequence can be found in vendor/qcom/opensource/QCamera2/QCamera2Factory.cpp and vendor/qcom/opensource/camera/QCamera2/stack/mm-camera-interface/src/mm_camera_interface.c.

> BTW is this supposed to work on this phone or are there additional steps? https://source.android.com/setup/build/building-kernels#flashing-fastboot

Please take a look at https://developer.sony.com/develop/open-devices/guides/kernel-compilation-guides/, but I don't know if they work well. The Android build system does not really allow other build systems (such as the kernel Makefile) to be integrated, so the kernels are prebuilt. When building your own, you basically replace the prebuilt kernel and then build the Android system.

I just change the kernel code and/or configuration, then rebuild the kernels using the provided script (kernel/sony/msm-4.14/common-kernel/build-kernel-clang.sh). In the top folder, I then issue "make out/target/product/DEVICE/boot.img" and in fastboot mode (blue LED), simply run "fastboot flash boot out/target/product/DEVICE/boot.img" to update. If the device uses DTBO, then you also need dtbo.img. That has worked for me in the past.

**Comment by sbourdeauducq** [comment]
> The Android build system does not really allow other build systems (such as the kernel Makefile) to be integrated,

...And I have a Core i9 machine with a recent NVMe SSD and it still takes a ridiculous amount of time to figure out that I have not modified the other sources. Typical Android™ quality...

**Comment by sbourdeauducq** [comment]
@Neo75T By the way, even with a GCC kernel the camera is still buggy, e.g. it often takes ~30 seconds to open the camera in any app, and about half of the time starting the camera fails with a message "Failed to connect to camera". That's Android for you!

**Comment by sraase** [comment]
Without any additional information, I would just like to point out that "it often takes 30 seconds to open the camera in any app" is not an Android issue per se. Such reports should follow enough research so that the accusations point at least in the right direction to provide some chance of improvement.

Relevant information or working code are also appreciated, if not preferred.

**Comment by sbourdeauducq** [comment]
Or maybe there should be sufficient error reporting in the camera app?
![image](https://user-images.githubusercontent.com/720864/109007110-bd92c400-76e6-11eb-9324-07419c4d4217.png)

**Comment by ddvarpdd** [comment]
Can confirm the same bug is present on AOSP 10, which isn't that surprising as it uses the same prebuilt kernel.

**Comment by sraase** [comment]
I can at least confirm that the "green picture" issue is not caused by compiler optimization levels. Generally, gcc-built kernels appear to work, while clang-built kernels fail. All optimization levels resulting in a working kernel behave like that (Linux cannot be built without any optimization). White possible that I made a mistake, I think we can rule that one out.

**Comment by jerpelea** [comment]
Discontinued Android version
