### ISSUE TITLE
AOSP11 / pioneer no fingerprint reader

### ISSUE THREAD

**Issue by sbourdeauducq** [sonyxperiadev/bug_tracker#647]
**Device:** Xperia XA2 dual (pioneer)
**Kernel version:** 4.14.196
**Android version:** 11
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.14_v2a_nile.img

**Description**
Fingerprint reader does not work.

**Symptoms**
No response to the fingerprint reader being touched.

**How to reproduce**
Try to set a fingerprint in the device settings. There will be no response and no error message printed.

**Comment by MarijnS95** [comment]
As the main developer/maintainer of the fingerprint HAL, would you mind pasting the output of `adb logcat -v kernel,default` after trying this?

**Comment by sbourdeauducq** [comment]
Not sure if it's a coincidence, but running ``adb logcat`` in the background made it work...

**Comment by MarijnS95** [comment]
Odd. Did you reboot in the meanwhile?

Can this issue be considered fixed and closed?

**Comment by sbourdeauducq** [comment]
No, I did not reboot it, and reboots do not seem to affect the issue either way.
I guess it can be closed since I cannot reproduce it anymore (except maybe by wiping the phone and reinstalling AOSP completely, but it's a bit unwieldy).

**Comment by MarijnS95** [comment]
> No, I did not reboot it, and reboots do not seem to affect the issue either way.

We had this problem where the sensor would become unresponsive after sitting idle for some time without a fingerprint enrolled. If I'm not mistaken that's implicitly resolved now with the introduction of fingerprint gestures. But that only works if you have an Egistec sensor or updated firmware (recent/latest Stock flash) on FPC.
