### ISSUE TITLE
AOSP11 multiuser storage is broken

### ISSUE THREAD

**Issue by sbourdeauducq** [sonyxperiadev/bug_tracker#648]
**Device:** Xperia XA2 dual (pioneer)
**Kernel version:** 4.14.196
**Android version:** 11
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.14_v2a_nile.img

**Description**
Storage for media is broken for non-primary users.

**Symptoms**
On secondary user accounts
* Whatsapp cannot use photos or videos with a message "Download failed: Can't download because no internal storage is available"
* File manager shows only the "Downloads" folder in the left bar and no "Images", "Videos", etc. as it does for the primary user. When the "Downloads" folder is selected, it says "Can't load content at the moment".

**How to reproduce**
Create an additional user account, switch to it, and use one of the above apps.

**Comment by sbourdeauducq** [comment]
Also, I don't know if this is expected behavior, but it looks slightly suspicious to me (with adb root shell):
```text
pioneer:/ # ls /storage/emulated/0                                                                                                                                                       
Alarms  Android  Audiobooks  Aurora  DCIM  Documents  Download  Movies  Music  Notifications  Pictures  Podcasts  Ringtones  Telegram  WhatsApp
pioneer:/ # ls /storage/emulated/10                                                                                                                                                        
ls: /storage/emulated/10: Operation not permitted
```

The original files in ``/data/media`` look OK:
```text
pioneer:/ # ls /data/media/0                                                                                                                                                               
Alarms  Android  Audiobooks  Aurora  DCIM  Documents  Download  Movies  Music  Notifications  Pictures  Podcasts  Ringtones  Telegram  WhatsApp
pioneer:/ # ls /data/media/10                                                                                                                                                              
Alarms  Android  Audiobooks  DCIM  Documents  Download  Movies  Music  Notifications  Pictures  Podcasts  Ringtones  WhatsApp
```

**Comment by sbourdeauducq** [comment]
Worked around by:
* inserting a SD card and moving storage there (using the owner account)
* removing the SD card
* selecting "Forget SD card" in the storage settings (this button only seems to appear after an unsafe SD card removal)

This somehow reinitialized storage and created the correct setup for the secondary user account.

There is probably a cleaner way to do this but I have no idea... Is there good documentation or straightforward source code about this Android storage business?

**Comment by sbourdeauducq** [comment]
Unfortunately that did not survive a phone reboot :( Very annoying...

**Comment by sbourdeauducq** [comment]
Any ideas?

**Comment by jerpelea** [comment]
Discontinued Android version
