### ISSUE TITLE
[Yoshino][Poplar] Touch not working on Android 11 

### ISSUE THREAD

**Issue by yuezhenglingluan** [sonyxperiadev/bug_tracker#649]
**Platform:** Yoshino
**Device:** Poplar
**Kernel version:** 4.14
**Android version:** android-11.0.0_r17
**Software binaries version:** v2a

**Description**
Touch screen does not work, cannot get past lock screen, as i cannot unlock the phone.

**Symptoms**
Touch screen don't work, and the device is getting very hot after sitting it there for a while

**How to reproduce**
Build Android follow the instruction here: https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-11-0-0 . use branch android-11.0.0_r17.

please attach a logcat and dmesg for us here! -->
here is logcat: 
[logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/5503999/logcat.txt)
here is dmesg:
[dmesg.txt](https://github.com/sonyxperiadev/bug_tracker/files/5504000/dmesg.txt)

**Comment by yuezhenglingluan** [comment]
Update: I tried OEM v3a but the issue is still not fixed, my poplar's panel id is 9

**Comment by ShujathMohd** [comment]
On maple and everything seems to be working fine.

Can you confirm if the issue is resolved/still persist on poplar?

**Comment by MarijnS95** [comment]
This reminds me of https://github.com/sonyxperiadev/kernel/pull/2125, perhaps the full in-cell panel should have had this power supply after all (extremely unlikely)? Unfortunately that PR does not link to the porting commit where this was originally flipped/messed-up.

**Comment by jerpelea** [comment]
Discontinued Android version
