### ISSUE TITLE
[lilac] UFS fails to initialize due to conflicting gcc_aggre1_ufs_axi_hw_ctl_clk

### ISSUE THREAD

**Issue by tootea** [sonyxperiadev/bug_tracker#654]
**Platform:** yoshino
**Device:** lilac
**Kernel version:** 4.14.196-g7aaaf731280b
**Android version:** android-10.0.0_r41
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v11a_yoshino.img

**Previously working on**
Not sure. Works on stock FW 47.2.A.11.228. Judging from git log, the bug has always been there on 4.14.

**Description**
My lilac typically fails to boot Android 10 due to a race condition between UFS initialization and `clk_disable_unused()`. This race causes one of the UFS clocks to get disabled halfway through waiting for the flash to come up, so none of the sda* block devices ever appear and the system has nowhere to boot from. The same issue occurs when booting to recovery, which comes up but fails to find any partitions.

> [    5.385615] ufshcd-qcom 1da4000.ufshc: ufshcd_query_flag: Sending flag query for idn 1 failed, err = -110
> [    7.945604] ufshcd-qcom 1da4000.ufshc: ufshcd_query_flag: Sending flag query for idn 1 failed, err = -110
> [   10.505593] ufshcd-qcom 1da4000.ufshc: ufshcd_query_flag: Sending flag query for idn 1 failed, err = -110
> [   10.505680] ufshcd-qcom 1da4000.ufshc: ufshcd_query_flag_retry: query attribute, opcode 5, idn 1, failed with error -110 after 3 retires
> [   10.505765] ufshcd-qcom 1da4000.ufshc: ufshcd_complete_dev_init reading fDeviceInit flag failed with error -110
> [   10.510488] ufshcd_init: 1da4000.ufshc: took 8322054 usecs, dev_state: UFS_POWERDOWN_PWR_MODE, link_state: UIC_LINK_OFF_STATE, err -110

The race stems from the following two clocks defined in `drivers/clk/qcom/gcc-msm8998.c`:

```c
static struct clk_branch gcc_aggre1_ufs_axi_clk = {
	.halt_reg = 0x82028,
	.halt_check = BRANCH_HALT,
	.hwcg_reg = 0x82028,
	.hwcg_bit = 1,
	.clkr = {
		.enable_reg = 0x82028,
		.enable_mask = BIT(0),
		.hw.init = &(struct clk_init_data) {
			.name = "gcc_aggre1_ufs_axi_clk",
			.parent_names = (const char*[]) {
				"ufs_axi_clk_src"
			},
			.num_parents = 1,
			.flags = CLK_SET_RATE_PARENT | CLK_ENABLE_HAND_OFF,
			.ops = &clk_branch2_ops,
		},
	},
};

static struct clk_branch gcc_aggre1_ufs_axi_hw_ctl_clk = {
	.halt_reg = 0x82028,
	.clkr = {
		.enable_reg = 0x82028,
		.enable_mask = BIT(0),
		.hw.init = &(struct clk_init_data) {
			.name = "gcc_aggre1_ufs_axi_hw_ctl_clk",
			.parent_names = (const char*[]) {
				"gcc_aggre1_ufs_axi_clk"
			},
			.num_parents = 1,
			.flags = CLK_SET_RATE_PARENT,
			.ops = &clk_branch2_hw_ctl_ops,
		},
	},
};
```

Given that both clocks have the same `enable_reg` and `enable_mask`, they alias each other. The ufshcd driver only uses the former (`gcc_aggre1_ufs_axi_clk`) because that's what `msm-8998-v2.dtsi` points to: `<&clock_gcc GCC_AGGRE1_UFS_AXI_CLK>`. This clock is properly enabled by clk init due to `CLK_ENABLE_HAND_OFF` and then taken over by the ufshcd driver. However, if `clk_disable_unused()` runs while UFS is doing something, it sees `gcc_aggre1_ufs_axi_hw_ctl_clk` also enabled (due to the aliasing) and proceeds to gate it, thus simultaneously gating the real clock being used by ufshcd.

The bug can be fixed by adding `CLK_IGNORE_UNUSED` to the `flags` of `gcc_aggre1_ufs_axi_hw_ctl_clk`.

(Perhaps the two clocks shouldn't actually alias each other, so maybe `gcc_aggre1_ufs_axi_hw_ctl_clk` should just be deleted (mainline kernel tree doesn't have it at all), but it is referenced by `msm8998.dtsi`. However, using the same registers for `hw_ctl` clks seems to be the norm, so I just have to admit I have no idea how this is supposed to work. Someone actually familiar with qcom clks is definitely needed.)

Given the racy nature of the bug, adding too many debug prints (such as enabling `clk:*` tracepoints with `tp_printk`) makes the issue disappear. I have thus added a few debug printks to `clk_*_unused_subtree` to confirm the root cause (this is with CLK_IGNORE_UNUSED):

> [    2.846401] clk: enable count for gcc_aggre1_ufs_axi_hw_ctl_clk is 0
> [    2.846487] clk: not disabling unused gcc_aggre1_ufs_axi_hw_ctl_clk
> [    2.846533] clk: finishing enable handoff gcc_aggre1_ufs_axi_clk
> [    2.846580] clk: enable count for gcc_aggre1_ufs_axi_clk is 1
> [    2.848956] clk: prepare count for gcc_aggre1_ufs_axi_hw_ctl_clk is 0
> [    2.849050] clk: not unpreparing unused gcc_aggre1_ufs_axi_hw_ctl_clk
> [    2.849096] clk: finishing prepare handoff gcc_aggre1_ufs_axi_clk
> [    2.849182] clk: prepare count for gcc_aggre1_ufs_axi_clk is 1

**Symptoms**
Boot loop because the flash never comes up.

**How to reproduce**
Happens on pretty much every boot on my device with Android 10.

It seems that connecting USB during early boot throws the timing off enough to avoid the race and make the system boot normally. Of course, booting with the `clk_ignore_unused` also works around the issue, but leaves many other clocks unnecessarily enabled.

**Additional context**
[dmesg-bad.log](https://github.com/sonyxperiadev/bug_tracker/files/5543212/dmesg-bad.log)
[dmesg-ignore-unused.log](https://github.com/sonyxperiadev/bug_tracker/files/5543213/dmesg-ignore-unused.log)
There's a WARNING for "mmss_mnoc_ahb_clk: status stuck at 'on'" in `clk_disable_unused()` in there as well, but I don't think it's directly related. Might indicate some general discrepancy between the DT and the `clk/qcom` code though.

**Comment by Haxk20** [comment]
Tootea i must firstly say. Absolutely excellent bug report. I have never seen such detailed report TBH. But im very happy you did it.

I have created the PR with the fix you mentioned for now. This may not be perfect solution but will do for now.

Again thank you for the report.

Oh yeah when you have time could you please test the PR and see if it works as it should ? It most likely will work but we need confirmation.

**Comment by tootea** [comment]
You're welcome. I'm trying to help as much as I can, but I know exactly nothing about qcom platforms, so I'm fairly certain I'm missing something crucial here about how the hw_ctl clks are meant to work. As I said, all them seem to alias non-hw_ctl clks and this is the only case where stuff doesn't seem to work well. That's why I'm pretty convinced that just slapping CLK_IGNORE_UNUSED on isn't the right "fix", so I haven't just sent a patch myself.

I've been running with CLK_IGNORE_UNUSED for several weeks now, but I'll rebuild with the PR tonight and re-test.

**Comment by tootea** [comment]
The PR fixes the issue for me (as expected).

Alternatively, I have tried modifying the DT to use the HW_CTL clk directly, just like it is done for all the other HW_CTL clocks that alias their non-HW_CTL counterparts. This is also how it is done in msm8998.dtsi:

```diff
--- a/arch/arm64/boot/dts/qcom/msm8998-v2.dtsi
+++ b/arch/arm64/boot/dts/qcom/msm8998-v2.dtsi
@@ -1267,7 +1267,7 @@
                "rx_lane1_sync_clk";
        clocks =
                <&clock_gcc GCC_UFS_AXI_HW_CTL_CLK>,
-               <&clock_gcc GCC_AGGRE1_UFS_AXI_CLK>,
+               <&clock_gcc GCC_AGGRE1_UFS_AXI_HW_CTL_CLK>,
                <&clock_gcc GCC_UFS_AHB_CLK>,
                <&clock_gcc GCC_UFS_UNIPRO_CORE_HW_CTL_CLK>,
                <&clock_gcc GCC_UFS_ICE_CORE_HW_CTL_CLK>,
```

This also fixes the issue. Whether either of these two "fixes" is the right one is something that I really cannot answer. I assume someone must have had a good reason to override the clks in msm8998-v2 to use GCC_AGGRE1_UFS_AXI_CLK. Unfortunately, git isn't very helpful here, as the entire file was added at once in the following commit on LE.UM.2.3.2.r1.4:
```
Author: Angelo G. Del Regno <kholk11@gmail.com>
Date:   Fri Jun 8 15:14:39 2018 +0200

    arm64: Add support for QC MSM8998 SoC
    
    This adds support and DTs for QC MSM8998.
```

**Comment by jerpelea** [comment]
Discontinued Android version
