### ISSUE TITLE
[pdx201[10.0]] Battery value won't refresh

### ISSUE THREAD

**Issue by sjllls** [sonyxperiadev/bug_tracker#655]
**Platform:**  Seine
**Device:**  pdx201
**Kernel version:**  4.14
**Android version:**  10
**Software binaries version:**  SW_binaries_for_Xperia_Android_10.0.7.1_r1_v11a_seine.img

**Symptoms**
Battery value won't refresh until reboot.

**How to reproduce**
Write how to reproduce here.

**Additional context**
I checked log, 
```
healthd : battery l=95 v=4296 t=20.4 h=2 st=2 c=-98 fc=3522000 cc=11 chg=u
healthd : battery l=95 v=4301 t=20.6 h=2 st=2 c=159 fc=3522000 cc=11 chg=u
healthd : battery l=95 v=4302 t=20.8 h=2 st=2 c=-113 fc=3522000 cc=11 chg=u`
```
`battery l=95` never changed.

There only are two errors about healthd:
```
01-02 02:30:40.208     0     0 W healthd : Unknown power supply type 'BMS'
01-02 02:30:40.208     0     0 W healthd : Unknown power supply type 'Main'
```
[battery.txt](https://github.com/sonyxperiadev/bug_tracker/files/5543400/battery.txt)

**Comment by MarijnS95** [comment]
Is `hvdcp_opti` running?

**Comment by sjllls** [comment]
> Is `hvdcp_opti` running?
> 
> I don't remember but we might have only introduced it in v11, any reason to run v10?

I don't why I download the V10a. I remember I choose latest. XD
Sorry, let me check battery on V11 again.
BTW, I have a question. We mounted `oem_a` as `oem`. And there is no `slotselect` flag.
https://github.com/sonyxperiadev/device-sony-seine/blob/master/rootdir/vendor/etc/fstab.seine#L12

If my phone runs AOSP on slot b, following guidance 
`fastboot flash oem SW_binaries_for_Xperia_AOSP_O_MR0_4.4_<release version>_<platform>.img`
fastboot flash flash image to oem_b. So will AOSP use oem_a or oem_b?

**Comment by MarijnS95** [comment]
> BTW, I have a question. We mounted `oem_a` as `oem`. And there is no `slotselect` flag.
> https://github.com/sonyxperiadev/device-sony-seine/blob/master/rootdir/vendor/etc/fstab.seine#L12

I guess you have to ask @kholk why [he did that](https://github.com/sonyxperiadev/device-sony-seine/commit/ef8a893b13ce20c5e9468e392213e7d376b802a0) for Seine but not any other A/B platform. I personally only ever flash A so can't really vouch for either.

> 
> If my phone runs AOSP on slot b, following guidance
> `fastboot flash oem SW_binaries_for_Xperia_AOSP_O_MR0_4.4_<release version>_<platform>.img`
> fastboot flash flash image to oem_b. So will AOSP use oem_a or oem_b?
> 
> @MarijnS95 It still mounted oem_a, although I am using slot b.
> So if users flashed following the guidance, they will flash oem image to oem_b, but AOSP will mount oem_a, they will get bootloop.

I agree that's inconvenient, `fastboot flash oem` will perform slotselect in the bootloader/fastbootd while fstab doesn't.

**Comment by sjllls** [comment]
> > BTW, I have a question. We mounted `oem_a` as `oem`. And there is no `slotselect` flag.
> > https://github.com/sonyxperiadev/device-sony-seine/blob/master/rootdir/vendor/etc/fstab.seine#L12
> 
> I guess you have to ask @kholk why [he did that](https://github.com/sonyxperiadev/device-sony-seine/commit/ef8a893b13ce20c5e9468e392213e7d376b802a0) for Seine but not any other A/B platform. I personally only ever flash A so can't really vouch for either.
> 
> > If my phone runs AOSP on slot b, following guidance
> > `fastboot flash oem SW_binaries_for_Xperia_AOSP_O_MR0_4.4_<release version>_<platform>.img`
> > fastboot flash flash image to oem_b. So will AOSP use oem_a or oem_b?
> > @MarijnS95 It still mounted oem_a, although I am using slot b.
> > So if users flashed following the guidance, they will flash oem image to oem_b, but AOSP will mount oem_a, they will get bootloop.
> 
> I agree that's inconvenient, `fastboot flash oem` will perform slotselect in the bootloader/fastbootd while fstab doesn't.

I tried to add `slotselect` flag in fstab, but system still uses `oem_a`, I guess this why you mounted `oem_a` directly.

**Comment by MarijnS95** [comment]
> I tried to add `slotselect` flag in fstab, but system still uses `oem_a`, 

Odd, did you add it to the _rightmost_ column and remove `_a`? Perhaps dmesg on early `init` can show what's up here.

> I guess this why you mounted `oem_a` directly.

I did not, Angelo made this change, and if the commit message is to be believed for a completely different reason.

**Comment by sjllls** [comment]
> > I tried to add `slotselect` flag in fstab, but system still uses `oem_a`,
> 
> Odd, did you add it to the _rightmost_ column and remove `_a`? Perhaps dmesg on early `init` can show what's up here.
> 
> > I guess this why you mounted `oem_a` directly.
> 
> I did not, Angelo made this change, and if the commit message is to be believed for a completely different reason.

`/dev/block/by-name/oem                   /odm                  ext4     ro,barrier=1                                                         wait,slotselect,first_stage_mount`

I will check it again.

**Comment by sjllls** [comment]
> init

@MarijnS95  I'm 100% sure it is using oem_a, although system is on slot b.

Full dmesg:
[dmesg.txt](https://github.com/sonyxperiadev/bug_tracker/files/5546217/dmesg.txt)


```
[    2.476046] init: [libfs_mgr]__mount(source=/dev/block/dm-5,target=/vendor,type=ext4)=0: Success
[    2.476469] init: [libfs_mgr]superblock s_max_mnt_count:65535,/dev/block/by-name/oem_a
[    2.478947] EXT4-fs (mmcblk0p83): mounted filesystem without journal. Opts: barrier=1
[    2.479042] init: [libfs_mgr]__mount(source=/dev/block/by-name/oem_a,target=/odm,type=ext4)=0: Success
[    2.481095] init: Skipped setting INIT_AVB_VERSION (not in recovery mode)
```

```
sjll@sjll:~/desktop$ adb shell cat /vendor/etc/fstab.pdx201
# Android fstab file.
# The filesystem that contains the filesystem checker binary (typically /system) cannot
# specify MF_CHECK, and must come before any filesystems that do specify MF_CHECK

# Logical partitions
system                                     /system               ext4     ro,barrier=1,discard                                                 wait,slotselect,avb=vbmeta_system,logical,first_stage_mount,avb_keys=/avb/q-gsi.avbpubkey
product                                    /product              ext4     ro,barrier=1,discard                                                 wait,slotselect,avb=vbmeta_system,logical,first_stage_mount
vendor                                     /vendor               ext4     ro,barrier=1,discard                                                 wait,slotselect,avb,logical,first_stage_mount

# Real first stage mount partitions
/dev/block/by-name/metadata                /metadata             ext4     noatime,nosuid,nodev,discard                                         wait,formattable,first_stage_mount
/dev/block/by-name/oem                     /odm                  ext4     ro,barrier=1                                                         wait,slotselect,first_stage_mount

# Other partitions
...
```

**Comment by MarijnS95** [comment]
> ```
> sjll@sjll:~/desktop$ adb shell cat /vendor/etc/fstab.pdx201
> ```

Keep in mind that this is read from fstab in the ramdisk, not on the vendor partition.
