### ISSUE TITLE
[Seine][pdx201] VoLTE is broken

### ISSUE THREAD

**Issue by sjllls** [sonyxperiadev/bug_tracker#657]
**Platform:** Seine
**Device:** pdx201
**Kernel version:** 4.14
**Android version:** 10.0
**Software binaries version:**  SW_binaries_for_Xperia_Android_10.0.7.1_r1_v11a_seine.img

**Symptoms**
VoLTE is broken on this device. Other user also met this problem.

**Additional context**

`TelecomFramework: AccountEntry: registerMmTelCapabilityCallback: registration failed, no ImsService available. Exception: CapabilityCallbackManager - MmTelFeature binder is dead. (code: 1)`

Full Log: 
[volte.txt](https://github.com/sonyxperiadev/bug_tracker/files/5550337/volte.txt)

**Comment by sjllls** [comment]
#640

**Comment by AngryGami** [comment]
I see  same errors in my devices (pdx201 and kirin).

**Comment by sjllls** [comment]
> I see same errors in my devices (pdx201 and kirin).

If you want to use VoLTE on AOSP, you need to enable it on stock at fist. Can you test it again a new commit merged in common repo?

IMS is more and more important for users, most carriers didn't support 2G now, and 3G will be expired in future, without VoLTE/VoWifi, users could not make a phone call.

**Comment by AngryGami** [comment]
Sure I will.

**Comment by sjllls** [comment]
Solved by including https://github.com/PixelExperience-Devices/device_sony_customization/

**Comment by sjllls** [comment]
Close this issue, I guess SODP doesn't include qcom blobs in device tree because of copyright.

**Comment by sjllls** [comment]
Mark a commit.
https://github.com/Havoc-OS/android_build/commit/4a93012f351edeaa1140875157f5d1697ade3378#diff-c3e87a7526d039953580e4c6d2d26fbca9426e39d7bf4be73b78a212a77bd6e3
