### ISSUE TITLE
[kirin] [aosp 11] [kernel 4.14] Question about AOSP 11 current status

### ISSUE THREAD

**Issue by xperia10dev** [sonyxperiadev/bug_tracker#658]
First of all, apologies for opening an issue that is not a bug report or feature request, but afaik there are no longer any forums dedicated to this project where I could ask this kind of question.

I'm planning on updating my daily driver device (kirin i4113) to AOSP 11. The build worked fine with the latest branch indicated in the guide (android-11.0.0_r4) and binaries for my device seem to be already available (latest ones from 2020-11-04).

Has anyone else tried flashing this yet? Are there any outstanding issues / missing functionality that I should know about before updating? So far I know of the WiFi issue at https://github.com/sonyxperiadev/bug_tracker/issues/627, but I'm not sure if it also applies to AOSP 11, and in any case it seems possible to work around it by e.g., flashing a stock Android 9 service with EMMA first.

Thanks a lot for your help.

**Comment by jerpelea** [comment]
The device is stable and waits for the minor bugs to be discovered and reported
