### ISSUE TITLE
[Kagura]Microphone recording very low or inexistant

### ISSUE THREAD

**Issue by Paulbouchara** [sonyxperiadev/bug_tracker#66]
Platform:Tone
Device:Kagura
Kernel version:4.4
Android version:8.0 

Description:
Microphone issue in media app

Symptoms:
The microphone sensitivity is too low, obliged to yell to hear something at max speaker volume after recording a video or audio file.
Voice on call is fine tho.

How to reproduce:
Record a media file with the mic (eg; Snapchat, Video with camera app, voice recorder)

**Comment by LLJY** [comment]
confirmed, here on whatsapp call.

**Comment by Paulbouchara** [comment]
Seems like any VoIP is affected too, Skype, and any other VoIP app affected

**Comment by jerpelea** [comment]
pleade cherry-pick the latest pr

**Comment by jerpelea** [comment]
pr merged 
please test

**Comment by Paulbouchara** [comment]
Lastest merge, fixies the issue, closing issue
