### ISSUE TITLE
[Akari] Dual sim cards causes force reboot

### ISSUE THREAD

**Issue by EzawaTami** [sonyxperiadev/bug_tracker#660]
**Platform:** Tama
**Device:** Akari
**Kernel version:** 4.9
**Android version:** lineage-17.1-20201118-nightly-akari-signed

**Previously working on**
On stock 10.0 firwmare 52.1.A.2.1

**Description**
When I boot the system with 2 sim cards (SIM1: China Telecom, LTE only; SIM2: China Mobile, GSM/LTE)
none of them gets connected. After a while the system freezes and reboots itself.

**Additional context**
Log:
[logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/5584000/logcat.txt)

**Comment by MartinX3** [comment]
I'm sorry but stock based ROMs aren't supported here.
Please close your ticket.
