### ISSUE TITLE
Xperia X Wi-Fi not working on AOSP Pie (Android 9.0) 

### ISSUE THREAD

**Issue by Neo75T** [sonyxperiadev/bug_tracker#663]
**Device:** Xperia X (F5121)
**Kernel version:** Kernel 4.9.213
**Android version:** AOSP Pie (Android 9.0) 
**Software binaries version:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_loire.zip

**Description**
Wi-Fi not working

**Symptoms**
When trying to switch on Wi-Fi, it shows just "Turning on..." and nothing happens.

**How to reproduce**
I have compiled and flashed AOSP 9.0 to Xperia X based on instructions here: 
[https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0-2](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0-2)

[https://developer.sony.com/file/download/software-binaries-for-aosp-pie-android-9-0-kernel-4-9-loire/](https://developer.sony.com/file/download/software-binaries-for-aosp-pie-android-9-0-kernel-4-9-loire/)

I have used branch: android-9.0.0_r46

**Comment by ix5** [comment]
Please attach logs or try to reproduce the issue again. I am quite certain that wifi was working perfectly on loire for Android 9.
