### ISSUE TITLE
[Pioneer][AOSP11][4.14] Won't boot if usb charger plugged in

### ISSUE THREAD

**Issue by phpbg** [sonyxperiadev/bug_tracker#664]
**Device:** Sony Xperia XA2
**Kernel version:** 4.14 (rebuild with GCC because of #646 )
**Android version:** android-11.0.0_r17
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.14_v3a_nile.zip

**Previously working on**
I cannot tell if this is a new issue or if it was there before.

**Description**
When the phone is powered on with the usb charger plugged in, it hangs at boot on white screen with sony logo.
If I reset and unplug the charger, it will boot correctly.

**How to reproduce**
1. Power off the phone.
2. Plug in the USB-C charger
3. Wait
    a. First, the notification led will become red.
    b. Then the screen will power on and warn about unlocked bootloader
    c. Then the screen will become white with Sony's logo
    d. After a few second, the notification led will turn off (Sony logo remain)
    e. Then the phone will remain stuck at this screen (you'll have to vol up + power to reset)

**Comment by jerpelea** [comment]
The phone is in charger mode when it appears to be stuck at boot 

This is a "cosmetic bug" that appears because the charging animation is not displayed

**Comment by phpbg** [comment]
> The phone is in charger mode when it appears to be stuck at boot

Even if the notification led is off?

**Comment by Gouster4** [comment]
Same problem on akari.

**Comment by Tsuyo1003** [comment]
Same problem on Geffin.

**Comment by jerpelea** [comment]
can not replicate on the latest release
