### ISSUE TITLE
[kirin] [aosp 11] [kernel 4.14] WiFi does not start

### ISSUE THREAD

**Issue by xperia10dev** [sonyxperiadev/bug_tracker#665]
**Platform:** ganges
**Device:** kirin (i4113)
**Kernel version:** 4.14.203-g3b690d23673d-dirty
**Android version:** android-11.0.0_r18
**Software binaries version:** 11_4.14_v3a_ganges

**Previously working on**
Kernel version: 4.14.203-gc5368064ad0f-dirty
Android version: android-11.0.0_r4
Software binaries version: 11_4.14_v3a_ganges

**Description**
WiFi does not start

**Symptoms**

**How to reproduce**
Try to start WiFi in Settings

**Additional context**
Relevant logcat output:
481  3468 I WifiService: setWifiEnabled package=com.android.systemui uid=10099 enable=true
1481  2338 D WifiActiveModeWarden: Starting ClientModeManager
1481  2338 D WifiController: DisabledState.exit()
1481  2338 D WifiController: EnabledState.enter()
1481  2338 D WifiClientModeManager: entering IdleState
1481  2338 I WifiVendorHal: Vendor Hal started successfully
1481  2339 I WifiP2pNative: Registering for interface available listener
 697   697 E WifiHAL : Failed to access driver state control param Permission denied, 13 at /sys/kernel/boot_wlan/boot_wlan
 697   697 E android.hardware.wifi@1.0-service: Failed or timed out awaiting driver ready
 697   697 E android.hardware.wifi@1.0-service: Failed to start legacy HAL: UNKNOWN
1481  2338 D HalDevMgr: updateRttController: no one is interested in RTT controllers
1481  2338 E HalDevMgr: executeChipReconfiguration: configureChip error: 9 (unknown)
1481  2338 E WifiVendorHal: Failed to create STA iface
1481  2339 W system_server: Long monitor contention with owner WifiHandlerThread (2338) at com.android.server.wifi.HalDeviceManager$WifiChipInfo[] com.android.server.wifi.HalDeviceManager.getAllChipInfo()(HalDeviceManager.java:1160) waiters=0 in void com.android.server.wifi.HalDeviceManager.registerInterfaceAvailableForRequestListener(int, com.android.server.wifi.HalDeviceManager$InterfaceAvailableForRequestListener, android.os.Handler) for 1.011s
1481  2338 E WifiNative: Failed to create iface in vendor HAL
1481  2338 E WifiClientModeManager: Failed to create ClientInterface. Sit in Idle
1481  2338 D WifiScanRequestProxy: Sending scan available broadcast: false
1481  2341 I WifiScanningService: Received a request to disable scanning, UID = 1000
1481  2338 I WifiScanRequestProxy: Scanning is disabled
1481  2341 I WifiScanningService: wifi driver unloaded
1481  2338 D WifiClientModeManager: received an invalid message: { when=-1s21ms what=2 arg1=2 target=com.android.wifi.x.com.android.internal.util.StateMachine$SmHandler }
1481  2338 D WifiController: STA disabled, return to DisabledState.
1481  2338 D WifiController: EnabledState.exit()
1481  2338 D WifiController: DisabledState.enter()

**Comment by phpbg** [comment]
Same on pioneer, only since `android-11.0.0_r18`, it used to work on `android-11.0.0_r17`

**Comment by pablomh** [comment]
It's a known issue and we're working on identifying the culprit.

**Comment by xperia10dev** [comment]
Confirming that the changes in https://github.com/sonyxperiadev/device-sony-ganges/pull/41 fix this issue.

**Comment by phpbg** [comment]
Can we have the fix on device-sony-pioneer too?
Regards

**Comment by pablomh** [comment]
The one for pioneer should be https://github.com/sonyxperiadev/device-sony-nile/pull/119, but we're thinking in taking another approach (it'll work on pioneer for the time being, as it's the device I did my testing on).

**Comment by pablomh** [comment]
The approach we've taken is to send a proper patch to upstream AOSP:

https://android-review.googlesource.com/c/platform/hardware/qcom/wlan/+/1532349

and included it in our list of local patches:

https://github.com/sonyxperiadev/repo_update/pull/138
