### ISSUE TITLE
AOSP11 / pioneer poor GPS reception

### ISSUE THREAD

**Issue by sbourdeauducq** [sonyxperiadev/bug_tracker#666]
**Device:** Xperia XA2 dual (pioneer)
**Kernel version:** 4.14.196
**Android version:** 11
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.14_v2a_nile.img

**Description**
GPS reception is very poor.

The issue appeared after installing LOS 17.1 (with this patch to fix video playback: https://androidfilehost.com/?fid=1899786940962602524 - why is flashing android phones such a terrible mess? I've worked with all sorts of shitty embedded systems but android really takes the cake). It has persisted since.

**Symptoms**
No GPS lock at all unless signal is exceptionally good (e.g. outside and without any obstructions), and then it barely works: takes 5-10 minutes to lock and sometimes up to one hour (!), only a few satellites are visible, and it frequently loses lock.

**How to reproduce**
Open any GPS app.

**Comment by phpbg** [comment]
I'm generally getting a lock within a few minutes (NB i'm on single SIM XA2).

It is slow, but i think it is expected when you don't have google services.

**Comment by sbourdeauducq** [comment]
Is there a way to get diagnostics/logs?

**Comment by jerpelea** [comment]
the GPS HAL has been updated and the new one seems to have better signal
