### ISSUE TITLE
Nile (Pioneer)(11) : Brightness

### ISSUE THREAD

**Issue by Arbaazhussain829** [sonyxperiadev/bug_tracker#667]
**Platform:** Nile
**Device:** Pioneer
**Kernel version:** 4.14
**Android version:** 11
**Software binaries version:** SW_BINARIES_FOR_XPERIA_ANDROID_11_4.14_V3A_NILE.ZIP

**Description**
Brightness is too high even though set to 0

**How to reproduce**
Slide brightness slider in quick settings

**Comment by jerpelea** [comment]
Discontinued Android version
