### ISSUE TITLE
Pioneer [Nile][11] Scrolling lags

### ISSUE THREAD

**Issue by Arbaazhussain829** [sonyxperiadev/bug_tracker#669]
**Platform:** Nile
**Device:** Pioneer
**Kernel version:** 4.14
**Android version:** 11
**Software binaries version:** SW_BINARIES_FOR_XPERIA_ANDROID_11_4.14_V3A_NILE.ZIP

**Previously working on**
It's has always been a issue.
Scrolling lags by a lot. Can see it very clearly when medium speed scrolling through settings.
It was on android 10 now it's on android 11 too.

**Description**
Scrolling lags very much. If we scroll by fast speed the it almost shows as if it's 2 images scrolled vertically.
Maybe values but it feels so choppy in general

**How to reproduce**
Simple way is to scroll through the settings page.

**Comment by jerpelea** [comment]
Discontinued Android version
