### ISSUE TITLE
Xperia XZ2 Dual (H8266) does not boot with A11 binaries but with A10 binaries

### ISSUE THREAD

**Issue by aleksche93** [sonyxperiadev/bug_tracker#672]
**Platform:** Tama akari
**Device:** Xperia XZ2 Dual (H8266)
**Kernel version:** 4.14.208
**Android version:** 11 (Pixel Expirience)
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.14_v3a_tama.img

**Previously working on** 
working with SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_tama.img

**Description**
doesn't boot, hangs on "google"

**Symptoms**
dosn't boot

**How to reproduce**
try to boot

**Additional context**
Just 1 way to boot PE11 - its with A10 binaries. 
BUT, after boot not working baseband (if correctly cant calling, sms, havent mobile network). So i flashed additional .sin's for modem (4 files) from stock firmware. Now modem working.

**Comment by MarijnS95** [comment]
@aleksche93 That's an identical title - and identical `dosn't` typo even - to #661.

Note that creating duplicate issues (it _really_, **really** doesn't matter here that these are _slightly_ different devices) is only going to diverge knowledge, information and debugging attempts, not helping resolve the issue any quicker. Please close this in favour of using #661.

(I'll see if we can get the title update to mention _all_ KM3 tama deviecs).
