### ISSUE TITLE
(Work) Profiles do not work: Internal Memory is accessable

### ISSUE THREAD

**Issue by DoPeRaSo** [sonyxperiadev/bug_tracker#674]
**Platform:** Tama
**Device:** XZ2 H8266
**Kernel version:** 4.14
**Android version:** 11
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_tama

**Description**
Profiles (or work profiles) can be installed but do not work properly. 
 
**Symptoms**
Working with WhatsApp in a seperated environment is only partly usable: you can it install but not download anyhting.
While accessing the internal memory (e.g. /storage/emulated/[UserID] theres an java.IO.Excpetion occuring in Tools like Total Commander)

**How to reproduce**
Create a (Work) Profile, Install an App to browser the internal memory

**Additional context**
I'm using a ROM from [XDA](https://forum.xda-developers.com/t/sodp-rom-aosp-xz2-xz2c-xz3-sonyaosp-11-beta.4180835/) but this implementation should not affect this issue

**Comment by MarijnS95** [comment]
Looks like https://github.com/sonyxperiadev/bug_tracker/issues/648?

**Comment by DoPeRaSo** [comment]
Seems to be the same issue.
Weird that did not find it while searching for open bugs (iirc I looked for profile, work profile)

**Comment by jerpelea** [comment]
Discontinued Android version
