### ISSUE TITLE
[Kirin][ganges][AOSP11] 

### ISSUE THREAD

**Issue by bjbole** [sonyxperiadev/bug_tracker#677]
**Platform:kirin, ganges 
**Device:Sony Xperia 10
**Kernel version: 4.9
**Android version: android-11.0.0_r27
**Software binaries version:RQ1A.210105.003 

I download and compile android-11.0.0_r27 and after flashing my Sony Xperia 10 wifi on this device did not work.

**Comment by ix5** [comment]
Are you sure you're on kernel 4.9? The software binaries for Android 11 are compiled against kernel 4.14.

By "Software Binaries", the issue template asks you to paste the version you obtained from [developer.sony.com](https://developer.sony.com/develop/open-devices/downloads/software-binaries), not the AOSP build fingerprint.

After clearing those issues, what exactly is happening in your logs that wifi is not working?

**Comment by ix5** [comment]
@jerpelea I don't think this is a valid issue

**Comment by jerpelea** [comment]
I could not replicate the issue
