### ISSUE TITLE
[4.14][11.0][TAMA] Broken mobile and wifi

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#679]
**Platform:** tama
**Device:** akari, akatsuki
**Kernel version:** 4.14
**Android version:** 11
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.14_v3a_tama
and
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_tama

**Previously working on**
Android 10.

**Description**
No Wifi / mobile connection.

**Symptoms**
No Wifi.
No mobile.
No simcard detection.
No IMEI.

**How to reproduce**
Flash AOSP 11
Use OEM A10.
OR use OEM A11 but with the workaround to use the following files from A10 to get it to boot:
`lib64/hw/android.hardware.keymaster@3.0-impl-qti.so`
`lib64/hw/libkeymasterdeviceutils.so`

**Additional context**
[logcat_-b_radio_OEM12a.log](https://github.com/sonyxperiadev/bug_tracker/files/6048531/logcat_-b_radio_A10.log)
[logcat_-b_radio_OEM3a.log](https://github.com/sonyxperiadev/bug_tracker/files/6048532/logcat_-b_radio_A11.log)
[logcat_-b_all_OEM3a.log](https://github.com/sonyxperiadev/bug_tracker/files/6048554/logcat_-b_all_OEM3a.log)

**Comment by rantpalas** [comment]
Same issue on Akatsuki H8416 February 2021 patch.

**Comment by MarijnS95** [comment]
> Same issue on Akatsuki H8416 February 2021 patch.

@rantpalas more importantly, did it work on an older _Android 11_ patch release, and/or an older _Android 11_ OEM release?

@MartinX3 Can you check if v2 or v1 works? Looks like we have a dying modem...:

```
02-25 11:49:51.904     0     0 E         : Fatal error on the modem.
02-25 11:49:51.905     0     0 E         : modem subsystem failure reason: (unknown, smem_get_entry_no_rlock failed).
02-25 11:49:51.905     0     0 I subsys-restart: subsystem_restart_dev(): Restart sequence requested for modem, restart_level = RELATED.
```

**Comment by rantpalas** [comment]
@MarijnS95 worked on the December 2020 patch with the A11 and A10 binaries. Due to some PC issues, I did not get to build AOSP during January, so I cannot attest to that build.

**Comment by MarijnS95** [comment]
@rantpalas Do you recall if those were v1, v2 or v3 blobs? They should be backwards compatible bar some fixes, meaning you should be able to try them now on the current Android patch/kernel. If going back fixes it we drastically reduce the search scope.

**Comment by rantpalas** [comment]
I used v3 blobs first and then I used the A10 v12 blobs. Both used to work. I am flashing now the v2 and v1 blobs to see if those kickstart anything

**Comment by MarijnS95** [comment]
I wonder if something changed WRT IPA in AOSP, or in the kernel. Perhaps going back to an earlier kernel prebuilt solves the issue. Fortunately there haven't been many: https://github.com/sonyxperiadev/kernel-sony-msm-4.14-common/commits/aosp/LA.UM.7.1.r1. Don't mind testing changes to the build script, only `update prebuilt kernel` revisions are interesting. Check out such a commit and build+flash the kernel and dtbo.

Unfortunately... That means there's quite a large window to bisect from source after identifying what prebuilt broke it.

**Comment by egorovandreyrm** [comment]
Any updates on the isssue? 

I'm wondering if someone fixed the issue and can provide a temporary solution.

**Comment by rantpalas** [comment]
I have no idea how to test this, but I think the problem might be with the change in net/mac80211/rx.c brought by this commit [https://github.com/sonyxperiadev/kernel/commit/409132320fe5e08d558e979ce92f39208e885010](url)
@MartinX3, have you found any solution/would you be able to test this?

**Comment by MartinX3** [comment]
@rantpalas sadly I am out of order with maths exams until the end of the month. :)

**Comment by rantpalas** [comment]
@MartinX3 damn, sorry, I was just going through the xda forum right now and read that you were going through the dreaded experience of exams. Good luck on that. I'll try and get on some tutorials and see if I can test this week or next week.

**Comment by MarijnS95** [comment]
> I have no idea how to test this

After syncing and building your ROM, navigate to `kernel/sony/msm-4.14/common-kernel`, check out on an older `update prebuilt kernel` commit, build and flash the bootimage, then see if WiFi is working. In the end you should be able to tell since what prebuilt commit (hash) WiFi broke; from there we have a range to bisect in the kernel source.

**Comment by rantpalas** [comment]
Ok, I will try these steps during this weekend, see if I can get this working and I will come back to you with the results :)

**Comment by egorovandreyrm** [comment]
Unless I missed something, an older version of the kernel is also not working. 

`pdx201:/ $ uname -a
Linux localhost 4.14.196+ #1 SMP PREEMPT Thu Oct 8 13:00:08 CEST 2020 aarch64`

I have a device that is running that kernel and wifi and mobile data is working on it.

**Comment by egorovandreyrm** [comment]
I also downgraded device-sony-seine, device-sony-common, device-sony-pdx201 projects and it worked.
Commit date <= 25.12.2020 (I had a working ROM from that date.).

**Comment by MarijnS95** [comment]
@egorovandreyrm This could possibly be https://github.com/sonyxperiadev/device-sony-pdx201/commit/7d74abea8a4694ea064d8009ba7acaa08daa8c34. Can you resync your tree and revert just that commit, then try again?

You can also move the file around on-device.

**Comment by egorovandreyrm** [comment]
Log:

[pdx201_wifi_and_mobile_data_issue.txt](https://github.com/sonyxperiadev/bug_tracker/files/6096942/pdx201_wifi_and_mobile_data_issue.txt)

Wifi and mobile data is working file with the latest kernel. So the problem is with one of these projects: device-sony-seine, device-sony-common, device-sony-pdx201

I will try to identify the issue.

**Comment by MarijnS95** [comment]
> I will try to identify the issue.

If you can bisect this, please, thank you :). Probably easiest to start with PDX201, then Seine, then common. Some commits might have inter-dependencies on other repos though.

**Comment by ShujathMohd** [comment]
Well, I too experienced the same issue on maple(yoshino) and I suspect its due to the external modem commits in the common tree.(Didnt dig into it further)
I did reset the git head till here https://github.com/sonyxperiadev/device-sony-common/commit/9c905f849cace14fef7ff3c4972a91f4d2022d13 and mobile network,data and wifi are working fine.

**Comment by MarijnS95** [comment]
@ShujathMohd As per https://github.com/sonyxperiadev/local_manifests/commit/360c9e3c09e09b44761af666bd9494bc4edc2154 you should only use `r-mr1` branches. `master` is reserved for changes that require a newer - yet-unreleased - odm binary.

**Comment by MarijnS95** [comment]
However, anyone wishing to bisect this is welcome, that could potentially save us some time later on.

**Comment by ShujathMohd** [comment]
Yes I am on the r-mr1 branch and getting the subject issue.
And if I delete the last 50 commits from r-mr1(git reset --hard HEAD~50), everything works fine.
So something in the last 50 commits is causing the issue(external modem commits maybe).

**Comment by egorovandreyrm** [comment]
I'm trying to find the commit that breaks it.
Up to `hw/tftp: Enable symlinks for SM8250 (KONA)` seems to be working fine. Testing more.

**Comment by MarijnS95** [comment]
@ShujathMohd Right, github derp - they did not say https://github.com/sonyxperiadev/device-sony-common/commit/9c905f849cace14fef7ff3c4972a91f4d2022d13 is reachable by `r-mr1`, and that commit shouldn't be there anyway.

@egorovandreyrm Note that `git bisect` performs a binary search; I hope you're not checking every commit one-by-one :)

**Comment by egorovandreyrm** [comment]
@MarijnS95 I'm trying to test suspicious commits :)

**Comment by egorovandreyrm** [comment]
![image](https://user-images.githubusercontent.com/2622635/110244084-92299800-7f76-11eb-9ac5-54b87e61779e.png)

The issue is in these commits.

**Comment by MarijnS95** [comment]
@egorovandreyrm I think I know what it is. Give me a second.

**Comment by MarijnS95** [comment]
Try https://github.com/sonyxperiadev/device-sony-common/pull/833.

**Comment by egorovandreyrm** [comment]
Unfortunately, it did not help.

**Comment by MarijnS95** [comment]
@egorovandreyrm Continue bisecting, keeping in mind to pick that commit whenever https://github.com/sonyxperiadev/device-sony-common/commit/28921cff5a25e297f272dc9981c3ae0d36650db6 is also in your tree.

**Comment by egorovandreyrm** [comment]
Sorry. It appears to be working.
My bad. I added a space char after `on property:`. i.e. `on property: ro.baseband=sdm`. It must not be allowed. 

I will test more to confirm.

**Comment by egorovandreyrm** [comment]
It's working. Thank you!

**Comment by MarijnS95** [comment]
Never try to remake patches, always fetch/download/pick/merge/apply them locally. GitHub has a `cli` tool for that and they show in the top-right how to use it:

![image](https://user-images.githubusercontent.com/2325264/110245473-8ed8e100-7f63-11eb-8fb1-6ec4f04382a8.png)


Otherwise you can `git fetch sony pull/933/head && git merge FETCH_HEAD`. Or add `.patch` after the URL like so: `https://github.com/sonyxperiadev/device-sony-common/pull/833.patch` resulting in a raw file containing all commits from that PR, you can easily download this and apply it with `git am path/to/pr-833.patch`.

**Comment by MarijnS95** [comment]
@MarijnS95 @rantpalas Can you also confirm that https://github.com/sonyxperiadev/device-sony-common/pull/833 solves the issue?

**Comment by rantpalas** [comment]
> @MartinX3 @rantpalas Can you also confirm that [sonyxperiadev/device-sony-common#833](https://github.com/sonyxperiadev/device-sony-common/pull/833) solves the issue?

Hi @MarijnS95 Sorry for not replying until now. It seems that your comit fixed the issue. I've been running a rebuilt for the past three days and both mobile and wifi seems to function properly. Thank you very much for the help!
