### ISSUE TITLE
[tone] devices fail to boot on 6.4 kernel

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#68]
**Platform:** tone
**Device:** dora, kagura, keyaki
**Kernel version:** 6.4
**Android version:** 8.1

**Description**
When building android with inline built kernel (6.4 branch). The device fails to boot with a message saying that verification has failed. 

**Symptoms**
Device shows an error message about failing verification. 

**How to reproduce**
1. build with 6.4 kernel
2. flash build
3. boot device

**Comment by Paulbouchara** [comment]
I could make it to boot, but the display draws a heavy image corruption, touch work fine, it's just image display broken

**Comment by oshmoun** [comment]
dmesg: https://hastebin.com/uhebihopak.vbs
logcat: https://hastebin.com/yedewemebo.pl
