### ISSUE TITLE
LOW FPS BUG

### ISSUE THREAD

**Issue by yehonatan2020** [sonyxperiadev/bug_tracker#681]
[low_fps_ganges.txt](https://github.com/sonyxperiadev/bug_tracker/files/6097492/low_fps_ganges.txt)
**Platform:** 
AOSP/SODP
**Device:** 
GANGES
**Kernel version:** 
4.14
**Android version:** 
11
**Software binaries version:** 
OEM10 and OEM11

**Description**
After Building AOSP 11 and flashing it to both kirin and mermaid devices, there is a really low fps of 36

![low_fps](https://user-images.githubusercontent.com/65138695/110242172-c4be9b00-7f4c-11eb-9d40-67647ebd062d.jpg)
[bugreport-lineage_kirin-RQ1A.210205.004-2021-03-07-14-00-46.zip](https://github.com/sonyxperiadev/bug_tracker/files/6097249/bugreport-lineage_kirin-RQ1A.210205.004-2021-03-07-14-00-46.zip)

**Comment by yehonatan2020** [comment]
[low_fps_ganges.txt](https://github.com/sonyxperiadev/bug_tracker/files/6097496/low_fps_ganges.txt)

**Comment by jerpelea** [comment]
Discontinued Android version
