### ISSUE TITLE
[4.14][AOSP11][pdx201/Seine] update_engine: [ERROR:cached_file_descriptor.cc(89)] Failed to flush cached data!: No space left on device (28)

### ISSUE THREAD

**Issue by sony-seine-mirror** [sonyxperiadev/bug_tracker#685]
Platform: AOSP
Device: Xperia 10 II
Kernel version: 4.14
Android version: 11
Software binaries version: SW_binaries_for_Xperia_Android_11_4.14_v4b_seine.img

I'm getting 
`[INFO:delta_performer.cc(209)] Resuming after 692/752 operations (92%), 438875715/462207810 bytes downloaded (94%), overall progress 93%`
`update_engine: [ERROR:cached_file_descriptor.cc(89)] Failed to flush cached data!: No space left on device (28)`

When trying to install full OTA. It's 462MB.

Sideloading the OTA from recovery works well.

**Comment by sjllls** [comment]
Can you try to add `PRODUCT_BUILD_SUPER_PARTITION := false` in `device.mk` ? Maybe resizing paritions failed.

**Comment by sony-seine-mirror** [comment]
> BTW, did you enable delta update? 462MB is too large for a delta package.

Do you mean incremental updates? if so, no, I'm currently trying to flash the full OTA. 

If you mean something else, I guess the answer is no, I'm just using the default configuration.

**Comment by sony-seine-mirror** [comment]
`2021-04-02 16:01:42.922 7101-7101/? W/otapreopt_chroo: type=1400 audit(0.0:196): avc: denied { ioctl } for path="/dev/block/loop27" dev="tmpfs" ino=55772 ioctlcmd=0x4c0a scontext=u:r:otapreopt_chroot:s0 tcontext=u:object_r:loop_device:s0 tclass=blk_file permissive=0
`

Also, I'm having errors like this in the log.
