### ISSUE TITLE
[4.14][AOSP11][Akari/Tama] Auto Brightness not working.

### ISSUE THREAD

**Issue by NextGeneration9501** [sonyxperiadev/bug_tracker#687]
**Platform: Android Open Source Project (AOSP)** 
**Device: Sony Xperia XZ2 SoftBank (702SO)** 
**Kernel version: 4.14** 
**Android version: 11 (March 2021)** 
**Software binaries version: SW_binaries_for_Xperia_Android_11_4.14_v4b_tama.img** 

**Description**
Auto-Brightness doesn't do anything.

Built the ROM following official Sony instructions.

Device Info HW app shows the light sensor with "No data from sensor"

**Additional context**

![Screenshot_20210405-212125](https://user-images.githubusercontent.com/63903653/113578389-4fcaa800-9655-11eb-91c2-0efaf0d8c690.png)

**Comment by MartinX3** [comment]
I can confirm that the light sensor isn't working on OEMv5

I don't see a `android.sensor.light` by the `sensors-hal` in my logs.
Only the hardware name `AMS TMD2725 AMBIENT` with a resolution of `0.0 lx` can be collected by the  `DevCheck` app.

(The qcom step sensor as well, but I don't know if that is normal or if it ever worked.)

**Comment by MarijnS95** [comment]
> (The qcom step sensor as well, but I don't know if that is normal or if it ever worked.)

The step sensor always displays `0` steps unless an app explicitly turns it on (like a step counter or sports tracking app).

**Comment by MartinX3** [comment]
> > (The qcom step sensor as well, but I don't know if that is normal or if it ever worked.)
> 
> The step sensor always displays `0` steps unless an app explicitly turns it on (like a step counter or sports tracking app).

Ah, then the sensors app probably doesn't turn it on.

**Comment by MarijnS95** [comment]
> I can confirm that the light sensor isn't working on OEMv5 with my Xperia XZ2.

@MartinX3 Can you check whether this is an OEMv5 problem (ie. downgrading to v4 fixes the issue) or a `/vendor` problem (ie. something got messed up with the sensors json files in `device-sony-common`)?

**Comment by MartinX3** [comment]
The `device-sony-common` json is identical to the previously used
`https://github.com/sonyxperiadev/device-sony-akari/blob/23f7d052e7008656a1b587267b526f04347f8ec9/rootdir/vendor/etc/sensors/config/tmd2725.json`

and OEMv4 does not fix it.

**Comment by MarijnS95** [comment]
> The `device-sony-common` json is identical to the previously used
> `https://github.com/sonyxperiadev/device-sony-akari/blob/23f7d052e7008656a1b587267b526f04347f8ec9/rootdir/vendor/etc/sensors/config/tmd2725.json`

Any of the other files? Maybe some files went missing or were erroneously added?

> and OEMv4 does not fix it.

Was it working on v3 then? Or v2? Or Android 10?

**Comment by jerpelea** [comment]
Discontinued Android version
