### ISSUE TITLE
[4.14][AOSP10][Apollo/Tama] Echo during phone calls in handset mode

### ISSUE THREAD

**Issue by rinigus** [sonyxperiadev/bug_tracker#688]
**Platform:** Tama
**Device:** Apollo; h8324
**Kernel version:** 4.14
**Android version:** 10
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_tama.img

**Previously working on**

Worked fine on AOSP9. Mainly tested via Sailfish OS port on Tama platform devices (akari and apollo).

**Description**

When calling someone on Apollo/AOSP10, the caller can hear him/herself via echo. Issue is absent in AOSP9 and stock Android 10. 

Looks like noise cancellation is not kicking in, while the mic with the same name is used in AOSP9, AOSP10 & stock 10: voice-dmic-ef.

Echo observed with PixelExperience 20200818; my own AOSP10 build (Feb 2021 state); Sailfish AOSP10/aarch64 based port.

Echo absent: Stock Android 10; Sailfish AOSP9 based port.

**Symptoms**

See above

**How to reproduce**

See above

**Additional context**

Please let me know if something is missing in the logs - tried to start from the relevant bits.

Logcat for AOSP10 PixelExperience 20200818, with echo: 
[logcat_pe_echo.txt](https://github.com/sonyxperiadev/bug_tracker/files/6260390/logcat_pe_echo.txt)

dmesg pulled from Sailfish AOSP10 based port during call (similar echo to PE):
```
Apr 06 21:42:21 XperiaXZ2Compact kernel: qdsp_cvp_callback: cmd = 0x112c2 returned error = 0x9
Apr 06 21:42:21 XperiaXZ2Compact kernel: voice_send_vol_step_cmd: DSP returned error[ADSP_EALREADY]
Apr 06 21:42:21 XperiaXZ2Compact kernel: qdsp_cvp_callback: cmd = 0x112c2 returned error = 0x1
Apr 06 21:42:21 XperiaXZ2Compact kernel: voice_send_vol_step_cmd: DSP returned error[ADSP_EFAILED]
```

Logcat for stock Android 10, no echo: 
[logcat_stock_no_echo.txt](https://github.com/sonyxperiadev/bug_tracker/files/6260395/logcat_stock_no_echo.txt)

Logcat for Sailfish-based AOSP9 port, no echo:
[logcat_sailfish_aosp9.txt](https://github.com/sonyxperiadev/bug_tracker/files/6269632/logcat_sailfish_aosp9.txt)

dmesg during a call from Sailfish-based AOSP9 port:
```
Apr 06 20:10:25 XperiaXZ2Compact kernel: msm_pcm_routing_get_app_type_idx: App type not available, fallback to default
Apr 06 20:10:28 XperiaXZ2Compact kernel: msm_pcm_routing_get_app_type_idx: App type not available, fallback to default
Apr 06 20:10:28 XperiaXZ2Compact kernel: send_afe_cal_type cal_block not found!!
Apr 06 20:10:28 XperiaXZ2Compact kernel: qdsp_cvp_callback: cmd = 0x112c2 returned error = 0x9
Apr 06 20:10:28 XperiaXZ2Compact kernel: voice_send_vol_step_cmd: DSP returned error[ADSP_EALREADY]
Apr 06 20:10:28 XperiaXZ2Compact kernel: msm_pcm_routing_get_app_type_idx: App type not available, fallback to default
Apr 06 20:10:59 XperiaXZ2Compact kernel: lab_vreg_handler: lab_vreg_handler: LAB VREG_NG interrupt!
Apr 06 20:10:59 XperiaXZ2Compact kernel: lab_vreg_handler: lab_vreg_handler: false detection display is off
```

_Edit Apr 7 2021_: added AOSP9 call log without echo; dmesg during calls from Sailfish AOSP{9,10} based ports

**Comment by rinigus** [comment]
Have done some experiments with the different versions, would have to look into the logs still have to compare AOSP9 vs AOSP10.

However, few notes already:

- when using mixer_path before https://github.com/sonyxperiadev/device-sony-apollo/commit/ee4982625e2720669eb3e513f9cb4f02618b8df9#diff-2a5b43b1528b0056cfdf62d123e00088654d707c907e8e43df3349499d23aa73 , sound levels are fine and echo seems to be reduced. However, it is still there. Although, it seems like mic levels are more sane than after that commit.

- swapping to older ACDB didn't help on AOSP10 either.

**Comment by MarijnS95** [comment]
@rinigus That commit fixes volume levels on at least Akatsuki, but iirc @kholk found it applicable on Apollo, too. Not exactly sure what the deal is there...

**Comment by rinigus** [comment]
@MarijnS95: hard to say regarding mic levels. For handset mode, I think they were too large with that commit.

Can you tell me where I can check for ACDB IDs in the logs? From what I have seen, lines like 

```
04-06 18:42:21.231  4465  4465 D audio_route: Apply path: voice-dmic-ef
04-06 18:42:21.241  4465  4465 D ACDB-LOADER: ACDB -> send_voice_cal, acdb_rx = 7, acdb_tx = 6, feature_set = 0
```

list the same IDs (acdb_rx / acdb_tx) for AOSP9, AOSP10, and stock Android 10. If correct, IDs are the same for all these variants and ACDB update has not changed IDs.

Now the logs are diverging bit later in applying dmic path:

For echo case (PE AOSP10, SFOS AOSP10) use ACDB_CHANNEL_MAPPING_CONFIG_V2 and fail
```
04-05 18:46:02.987   688   688 D ACDB-LOADER: ACDB -> ACDB_CHANNEL_MAPPING_CONFIG_V2: GET_DEVICE_PROPERTY
04-05 18:46:02.988   688   688 D         : ACDBFILE_MGR: CmnDevinfo for the devid 00000007 not found
04-05 18:46:02.988   688   688 D         : [ACDB Command]->[AcdbCmdGetDeviceProperty]->Failed to fetch the device property of the device 00000007
04-05 18:46:02.988   688   688 E ACDB-LOADER: Error: ACDB ACDB_CMD_GET_DEVICE_PROPERTY error = -1
04-05 18:46:02.989   688   688 D ACDB-LOADER: ACDB -> send_voice_tx_topology
```

For stock Android 10, ACDB_CHANNEL_MAPPING_CONFIG was used:
```
04-05 20:10:49.905   959  1324 D ACDB-LOADER: ACDB -> ACDB_CHANNEL_MAPPING_CONFIG: GET_DEVICE_PROPERTY
04-05 20:10:49.905   959  1324 D ACDB-LOADER: ACDB -> send_voice_tx_topology
```

AOSP9 seems to send voice topology without mapping config.

But I am out of my depth and don't know what to look for, unfortunately.

**Comment by MarijnS95** [comment]
6/7 is the acdb ID, it's also shown in these lines:

```
03-06 07:46:28.939  4429  4429 D audio_hw_primary: select_devices: changing use case voicemmode1-call output device from(0: , acdb -1) to (20: voice-handset, acdb 7)
03-06 07:46:28.939  4429  4429 D audio_hw_primary: select_devices: changing use case voicemmode1-call input device from(0: , acdb -1) to (151: voice-dmic-ef, acdb 6)
```

Perhaps `ACDB_CHANNEL_MAPPING_CONFIG_V2` comes from a newer `libacdb`, maybe downgrading that helps. I'm unfortunately not too sure either, besides SDE (Snapdragon Display Engine), Adreno GPU, camera, modem, and everything else, audio calibration is a horrible unworkable and undocumented black box :angry:.

Otherwise, grabbing newer ACDB files from the latest stock release _might_ help as well - if possible try to keep them in sync with the same `libacdb` I guess.

**Comment by kholk** [comment]
The mapping config V2 is for SM8150 and later... SDM845 doesn't support that.
Maybe there's some property on the HAL to force v1?

Probably though the only way would be to downgrade the ACDB libraries back to a version that supports SDM845...

**Comment by rinigus** [comment]
I will look into how to downgrade ACDB libs to earlier version, try that on device and report back. Hopefully, these libs are easy to find in repo. If I fail to find them, I will ping you again.

**Comment by MarijnS95** [comment]
@rinigus They are blobs and sit on the odm partition, you can scavenge them from your AOSP 9 release/image.

**Comment by MarijnS95** [comment]
> Maybe there's some property on the HAL to force v1?

That'd be nice, it doesn't seem to be using v1 first or falling back to it afterwards.

**Comment by rinigus** [comment]
With old ACDB, I am getting `E ACDB-LOADER: ACDB -> Not correctly initialized!` messages. Haven't done calls with it.

After bit longer testing, seems like older mixer_path removes most of the echo on Apollo. In practice, no complains on the other side and echo was not detected in regular call even when the other party tried to hear it. This while using new ACDB config files /vendor/etc/acdbdata/. 

Based on artificial testing (call in quiet environment and trying to talk on the other device in separate room from Apollo), echo cancellation is not as good as for AOSP9 or stock. So maybe I should try to tune the headset mic to lower gains and see what will happen.

We still have ACDB_CHANNEL_MAPPING_CONFIG_V2 loading in the logs. Tried to go down to older versions of software binaries, but the same was true for V8a.

As for where V2 is triggered, no idea.

**Comment by rinigus** [comment]
I have a  feeling that mixer_paths adjustments should fix it in practice.

Can someone take a time and explain what should I tune to reduce the mic sensitivity, please? From the look into mixer_paths.xml and following changes by @kholk , we seem to have

- Volume controls: DEC7 & DEC8 Volumes, lines 347

- Gain offset targets for dmic1 & dmic2, lines 1799--1806. Note that the commit set the targets to be different. Maybe this is something that could lead to echo? If I reduce the targets to 84 (so, instead of increasing, will bring them down), sounds like echo disappears. Although, mic seems to reduce in volume somewhat - but it is still fine to talk to people while they use this setting.

- host of mics with DEC7 and/or DEC8 Volumes set. In some locations (headset-mic), ADC2 was adjusted as well.

**Comment by rinigus** [comment]
I think I figured mixer_paths syntax more or less out, no need to explain. Not sure what is ADC for, but that's OK.

From comparing Apollo/Akari/Akatsuki, mixer_paths.xml is the same with the following exceptions:

- apollo has "mixer_paths: Add voice-headset alias for voice-headphones" by @MarijnS95 reverted, others have kept it
- there was a small space (mis-)formatting difference between one of the three

I don't know what was measured while changing mic volume by @kholk, but it was certainly off for Apollo. I haven't tested mic performance for Akari and will not have a chance to do it in the very near future. But would be interesting to hear whether reverting that commit would be detrimental in the opinion of others.

Commits in question:

- apollo: https://github.com/sonyxperiadev/device-sony-apollo/commit/ee4982625e2720669eb3e513f9cb4f02618b8df9
- akari: https://github.com/sonyxperiadev/device-sony-akari/commit/d12f2f4453fd296e33c60462ede4bed76ad8eb15
- akatsuki: https://github.com/sonyxperiadev/device-sony-akatsuki/commit/1313e299cd5c60a54f274354866b2a6a2da8c241

**Comment by MarijnS95** [comment]
@rinigus Unfortunately I haven't gotten to look into this at all over the past 1.5 month :/. It seems handset calls on Akatsuki are "fine", but (voip) speakerphone calls have far too much echo.

Regarding reverting those commits: is the voice still clearly audible on the other side?

> apollo has "mixer_paths: Add voice-headset alias for voice-headphones" by @MarijnS95 reverted, others have kept it

That's strange, was the node already defined elsewhere in this file?

> _Edit_: apollo also has `mixer_paths.xml.orig` `mixer_paths.xml.rej` files in https://github.com/sonyxperiadev/device-sony-apollo/tree/master/rootdir/vendor/etc

Those must have sneaked in during a `patch -p1` with conlicts and shouldn't have ended up in the repo.

**Comment by kholk** [comment]
Me raising the ADC volumes was a workaround to get slightly better mic volume, but the real issue on all devices is that Sony uses custom "openopology" DSP paths (name reference from their kernel side custom implementation), which we cannot use, as they're managed in the proprietary Audio HAL from stock.

The ACDB files that we use here - also - are from stock, so these are (I'm 98% sure) selecting the Sony specific DSP paths and that should be happening mostly because we are "relegated" to use ACDB IDs that come from stock, as the "standard" ones don't seem to work (and what works without errors results in even worst audio anyway) - the ACDB database is what contains the adsp context (path) selection... and that should be a sufficient explaination for you to understand what's going on......... mostly.

Regarding the ADC volumes specifically on Apollo - that's a different form factor compared to Akatsuki/Akari, which is probably why you're experiencing some badness... that was an overlook, the values for Apollo should be lower than the other two smartphones to "achieve something"... anyway, the spirit there was "at least something is better than nothing".... :))

**Comment by rinigus** [comment]
Thank you very much for getting back to it!

I will restart my work on the port soon and will then ask users with the different devices to test. Myself I can test on Akari - different form factor. Just couldn't do it before for different reasons. 

It could easily be due to the differences in the form factor. However, default values were set the same for all devices before the increase in the volumes. Although, it could be an oversight as well.

At least we have some knobs to change to get the best in this situation.

> @MarijnS95 Regarding reverting those commits: is the voice still clearly audible on the other side?

it boils down to definition of "clearly audible". Let's say that this is something which gets noticed fast and is disturbing to the other parties.

> @MarijnS95 was the node already defined elsewhere in this file?

Haven't checked it, sorry.

**Comment by MarijnS95** [comment]
The main problem appears to be loudness as well. Usually people on the other end complain about echo (indeed, handset mode). Other times, in speaker mode (VOIP) the other party cannot hear me unless I tilt the phone to speak right into the _top_ speaker (Akatsuki).

I wonder if echo in handset calls really is echo (why are the mics that sensitive when speaker volume is relatively low??) or if the hardware routing is feeding back data the wrong way (normally used for cancellation).

**Comment by rinigus** [comment]
Just tested on Akari with the reverted mixer_paths.xml - without boosting microphone levels. It works fine, audio is good (mic catches what is said) and there is no echo. I can hopefully make SFOS beta release using AOSP10 as a base and then will hear from Akatsuki owners as well.

**Comment by rinigus** [comment]
Got feedback from Sailfish XZ3 user - no echo and mic levels are OK after reverting mixer_paths.xml patch boosting the microphone levels. Not sure what is different between AOSP10 builds and SFOS in this respect. Maybe something changed on AOSP10 side from introducing the patch and currently used base. However, on SFOS port, boosting microphone levels has not been needed for all devices of Tama platform.

**Comment by MarijnS95** [comment]
I've had quite a few cases where the other end could not hear me properly, especially in speakerphone mode (only the top mic pics up voice, and I had to speak straight into it). This still happens (albeit it seems less often) with the mic boosting patch. Handset calls appear "acceptable", but I don't call enough to say anything conclusive (and have since switched to 1II stock DD, where sound is simply phenomenal).

Perhaps my phone and Angelos have seen too much water in the mic (and speakers :wink::wink:) causing degradation of its overall performance. I regularly rinse the device after sports.

**Comment by rinigus** [comment]
So far, for me _n=1_ in terms of XZ3 users. I will keep the mic levels unboosted on all Tama devices and let's see whether I will get complaints regarding it when more will update to AOSP10 based releases.

**Comment by jerpelea** [comment]
Discontinued Android version
