### ISSUE TITLE
[3.18][XPERIA L1] Missing vendor/cci folder at open source zip

### ISSUE THREAD

**Issue by jmpfbmx** [sonyxperiadev/bug_tracker#690]
**Platform:** MT6735 
**Device:** XPERIA L1 (aka Pine)
**Kernel version:** 3.18.35
**Android version:** 7.0
**Software binaries version:** 43.0.A.7.106

**Is your feature request related to a problem? Please describe.**
Yes, it is, it seems that sony modified updatemiscta of Xperia L1, and without vendor/cci folder where TA*  requested values are defined we can't make RIL works.
Here you have a [strings of updatemiscta](https://gist.github.com/jmpfbmx/8cb1b157f031d4caddeee640aaa88a4a) where you can see the requested values.

**Describe the solution you'd like**
I would like to get that missing needed folder, bcuz if not RIL won't work.

**Describe alternatives you've considered**
The only alternative I can see is have your help on making RIL works.

**Additional context**
At XPERIA XA1 / XA1 Plus (teak) MT6757 platform, you gave that folder, and i saw that at least they have those values requested by updatemiscta, so i don't understand why wasn't included at XPERIA L1 (pine) kernel.

@jerpelea 

Thanks!
I wait your answer.
Regards Jose!
Have a nice day!

**Comment by jerpelea** [comment]
@jmpfbmx the folder that you are asking is proprietary

**Comment by jmpfbmx** [comment]
@jerpelea, Okay, I understand that, but why did u provided that folder at xperia xa1/xa1 plus kernel source?
I just want at least vendor/cci/tools or vendor/cci/tools/g_read_miscta/, for get those needed missing values i don't have for making RIL works.
You provided that folder at 48.1.A.2.73_copyleft

**Comment by jerpelea** [comment]
@jmpfbmx cant you use the folder from xa1?

**Comment by jmpfbmx** [comment]
@jerpelea, i don't think so since that missing values are proprietary for every device. For example TA_SW_VERSION at XA1 / XA1 Plus is 2202 and at L1 can be 2215.
So that's the thing.
For that i made the issue, Could you just gave vendor/cci/tools/g_read_miscta/ folder pls?, if not i don't see any form for fix RIL at L1 and that makes me thinks that i failed as developer, since i has been fighting 1 year with RIL.
Plus if you want i can try to use XA1 / XA1 Plus g_read_miscta and tell you if worked or not.

**Comment by jerpelea** [comment]
I am sorry but i cant share the value as it is 
I will open an internal ticket

**Comment by jmpfbmx** [comment]
Okay, thanks.
I will wait your answer.

**Comment by jmpfbmx** [comment]
Hi @jerpelea 
How are you?
Any news?
Thanks,
Regards Jose

**Comment by jmpfbmx** [comment]
Hey @jerpelea 
Any news?

**Comment by jerpelea** [comment]
I will ping my colleague to check for the status
Regards
Alin

**Comment by jmpfbmx** [comment]
Thanks for your help @jerpelea 
I close this issue as my L1 died.
