### ISSUE TITLE
[Yoshino][Maple] Device gets crazy hot

### ISSUE THREAD

**Issue by kgvarunkanth** [sonyxperiadev/bug_tracker#691]
Platform:Yoshino
Device:Maple
Kernel version:4.14
Android version:11.0 (Happens the same even in 10.0,9.0)
Software binaries version:11.0 v3 , 10.0 v11  

Description:
This is a very SERIOUS ISSUE , Please do check them 

Device gets too hot even for normal usage like scrolling or simply using it for few minutes ...
And taking it outside feels like having a bomb with you, sometimes I'm afraid it would burst ..

How to reproduce
1.Simply turn on internet and Open chrome and browse ur favorite site -> device heats up
2.Put ur brightness to high and device should touch 45 degrees easily.
3.Watch some video in apps -> heats up
4.Turn on camera and click a single pic (Open Camera, Hedge ,etc) device will go hot instantly within secs -> Heats up 

Logs won't be a deal...but will upload if requested by anyone :-)
I have attached proof 
![200179800468_2239](https://user-images.githubusercontent.com/26020564/115754782-326a3d80-a3ba-11eb-8793-c1c3a48b78f8.jpg)

![200292300309_89159](https://user-images.githubusercontent.com/26020564/115754869-4a41c180-a3ba-11eb-9625-13292e5c4ec9.jpg)

![IMG_20210422_221456_535](https://user-images.githubusercontent.com/26020564/115755170-ac9ac200-a3ba-11eb-84a5-2f763d86e149.jpg)

**Comment by Haxk20** [comment]
You have attached screenshots of an app in what is i presume a russian language. Could you reupload the screenshots with the language switched to english so we can see what the app is actually saying ?

**Comment by kgvarunkanth** [comment]
> You have attached screenshots of an app in what is i presume a russian language. Could you reupload the screenshots with the language switched to english so we can see what the app is actually saying ?

Hey.....its not the words....there is arrow pointed towards it ,...
But no prob lemme scroll something and take a screenshot again 😅
Gimme a moment

**Comment by kgvarunkanth** [comment]
> You have attached screenshots of an app in what is i presume a russian language. Could you reupload the screenshots with the language switched to english so we can see what the app is actually saying ?

Literally night here....24degrees outside 
![Screenshot_20210422-225904_DevCheck](https://user-images.githubusercontent.com/26020564/115759981-7d864f80-a3be-11eb-8a8d-e8ea11004ed0.png)

**Comment by Haxk20** [comment]
Thanks for the screenshots

**Comment by kgvarunkanth** [comment]
> Thanks for the screenshots

No mention

**Comment by kgvarunkanth** [comment]
> Thanks for the screenshots

While using on heavy task ...
![IMG_20210423_222152_907](https://user-images.githubusercontent.com/26020564/115904854-ecc57780-a482-11eb-8d40-7cbc0cb2136f.jpg)

**Comment by jerpelea** [comment]
Discontinued Android version
