### ISSUE TITLE
[apollo][AOSP11] make exit status 2 on last step "soong bootstrap"

### ISSUE THREAD

**Issue by MCBuhl** [sonyxperiadev/bug_tracker#692]
**Platform:** 
**Device:** Apollo
**Kernel version:** 
**Android version:** 11
**Software binaries version:** 

**Previously working on**
I checked, but my issue is not filed, it seems. I wrote you an email and got request to file a bug 

**Description**
trying to build aosp 11 on my fedora 33 machine. make fails in very last step. exit status 2 (make file incorrect)

**Symptoms**

[root@fedora33 android]# make -j$(nproc)
15:02:16 ************************************************************
15:02:16 You are building on a machine with 7.66GB of RAM
15:02:16 
15:02:16 The minimum required amount of free memory is around 16GB,
15:02:16 and even with that, some configurations may not work.
15:02:16 
15:02:16 If you run into segfaults or other errors, try reducing your
15:02:16 -j value.
15:02:16 ************************************************************
[W][2021-04-30T15:02:18+0200][30095] void cmdline::logParams(nsjconf_t *)():250 Pro
cess will be UID/EUID=0 in the global user namespace, and will have user root-level
 access to files
[W][2021-04-30T15:02:18+0200][30095] void cmdline::logParams(nsjconf_t *)():260 Pro
cess will be GID/EGID=0 in the global user namespace, and will have group root-leve
l access to files
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=11
TARGET_PRODUCT=aosp_h8324
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-2a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-2a
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.11.14-200.fc33.x86_64-x86_64-Fedora-33-(Workstation-Edition)
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=RQ2A.210305.006
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/sony/common device/sony/tama vendor/qcom/opensource
/core-utils
============================================
[W][2021-04-30T15:02:19+0200][30123] void cmdline::logParams(nsjconf_t *)():250 Pro
cess will be UID/EUID=0 in the global user namespace, and will have user root-level
 access to files
[W][2021-04-30T15:02:19+0200][30123] void cmdline::logParams(nsjconf_t *)():260 Pro
cess will be GID/EGID=0 in the global user namespace, and will have group root-leve
l access to files
[W][2021-04-30T15:02:19+0200][30127] void cmdline::logParams(nsjconf_t *)():250 Pro
cess will be UID/EUID=0 in the global user namespace, and will have user root-level
 access to files
[W][2021-04-30T15:02:19+0200][30127] void cmdline::logParams(nsjconf_t *)():260 Pro
cess will be GID/EGID=0 in the global user namespace, and will have group root-leve
l access to files
[W][2021-04-30T15:02:20+0200][30145] void cmdline::logParams(nsjconf_t *)():250 Pro
cess will be UID/EUID=0 in the global user namespace, and will have user root-level
 access to files
[W][2021-04-30T15:02:20+0200][30145] void cmdline::logParams(nsjconf_t *)():260 Pro
cess will be GID/EGID=0 in the global user namespace, and will have group root-leve
l access to files
15:10:11 soong bootstrap failed with: exit status 2

#### failed to build some targets (08:08 (mm:ss)) ####

**How to reproduce**
Just reproduced it today. Followed guideline on https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-11-0-0/

**Additional context**
If you need more info like log or so, pls. lemme know - but I'd need assistance how to retrieve log.

**Comment by jerpelea** [comment]
please try make -j2

**Comment by MCBuhl** [comment]
Sorry for comming back this late. I have serious trouble downloading the repo data. It now fails at this stage.

**Comment by MCBuhl** [comment]
Hello, today I downloaded android-11.0.0_r39 and used "make -j2" - ninja failed with: exit status 1

**Comment by MartinX3** [comment]
@MCBuhl your previous `exit status 2` probably occurred because you tried to build as root / with administrative rights.
That's not good.

Is your new error similar to this?
https://github.com/sonyxperiadev/bug_tracker/issues/708

**Comment by MCBuhl** [comment]
Ah. didn't know that root can't do make... So tried again w/o administrative rights. Know getting error while doing repo sync

[xxx@xxx-lappy android]$ repo sync
Traceback (most recent call last):
  File "/home/xxx/android/.repo/repo/git_config.py", line 336, in _SaveJson
    with open(self._json, 'w') as fd:
PermissionError: [Errno 13] Permission denied: '/etc/.repo_gitconfig.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxx/android/.repo/repo/main.py", line 630, in <module>
    _Main(sys.argv[1:])
  File "/home/xxx/android/.repo/repo/main.py", line 606, in _Main
    result = run()
  File "/home/xxx/android/.repo/repo/main.py", line 599, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/home/xxx/android/.repo/repo/main.py", line 265, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/xxx/android/.repo/repo/subcmds/sync.py", line 958, in Execute
    self._UpdateManifestProject(opt, mp, manifest_name)
  File "/home/xxx/android/.repo/repo/subcmds/sync.py", line 867, in _UpdateManifestProject
    current_branch_only=self._GetCurrentBranchOnly(opt),
  File "/home/xxx/android/.repo/repo/subcmds/sync.py", line 283, in _GetCurrentBranchOnly
    return opt.current_branch_only or git_superproject.UseSuperproject(opt, self.manifest)
  File "/home/xxx/android/.repo/repo/git_superproject.py", line 421, in UseSuperproject
    return _UseSuperprojectFromConfiguration()
  File "/home/xxx/android/.repo/repo/git_superproject.py", line 365, in _UseSuperprojectFromConfiguration
    system_value = system_cfg.GetBoolean('repo.superprojectChoice')
  File "/home/xxx/android/.repo/repo/git_config.py", line 169, in GetBoolean
    v = self.GetString(name)
  File "/home/xxx/android/.repo/repo/git_config.py", line 192, in GetString
    v = self._cache[_key(name)]
  File "/home/xxx/android/.repo/repo/git_config.py", line 309, in _cache
    self._cache_dict = self._Read()
  File "/home/xxx/android/.repo/repo/git_config.py", line 316, in _Read
    self._SaveJson(d)
  File "/home/xxx/android/.repo/repo/git_config.py", line 340, in _SaveJson
    platform_utils.remove(self._json)
  File "/home/xxx/android/.repo/repo/platform_utils.py", line 151, in remove
    os.remove(path)
PermissionError: [Errno 13] Permission denied: '/etc/.repo_gitconfig.json'

**Comment by MartinX3** [comment]
@MCBuhl Either you fix the ownership of the folders/files owned by root because of your little accident or your sadly need to remove and redownload everything.

**Comment by MCBuhl** [comment]
I started from scratch following the receipe on the sony pages and got to the permission errors.

**Comment by MartinX3** [comment]
> I started from scratch following the receipe on the sony pages and got to the permission errors. But ok, I'm gonna delete all folders "android" and restart again from scratch. 
> 
>   @MartinX3 Anything else to delete?

Did the error message differ now?

Probably you need to remove repo, remove the repo config in etc and install repo again.

**Comment by MCBuhl** [comment]
What a journey... I had to reinstall my computer, but finally come to download everything. But the make-process just crashes: the terminal closes w/o further notice. I'm giving up.
