### ISSUE TITLE
[TAMA][4.9][AOSP10] Hall sensor does not work.

### ISSUE THREAD

**Issue by VZuyev** [sonyxperiadev/bug_tracker#693]
**Platform:** AOSP10
**Device:**  Sony Xperia XZ2 Dual H8266
**Kernel version:** 4.9
**Android version:** 10
**Software binaries version:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_tama.img

**Description**
Hall sensor does not work.

**Symptoms**
Original Sony Style Cover Stand SCSH40 does not control whether the display is turned on or off when opening and closing.

**Comment by rinigus** [comment]
Was the kernel 4.9 or 4.14? Also OEM binaries need to be updated to corresponding version

**Comment by VZuyev** [comment]
Kernel 4.9. OEM binaries updated to version SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_tama.zip. Hanging logo Sony.

**Comment by VZuyev** [comment]
Returned the version SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_tama.img

**Comment by rinigus** [comment]
What build of AOSP10 did you use then? AOSP10 was usually with kernel 4.14

**Comment by VZuyev** [comment]
[https://forum.xda-developers.com/t/android-10-0-aosp-for-xperia-xz2-2019-10-01.3971927/](https://forum.xda-developers.com/t/android-10-0-aosp-for-xperia-xz2-2019-10-01.3971927/)
[https://www.androidfilehost.com/?w=files&flid=299492](https://www.androidfilehost.com/?w=files&flid=299492)

**Comment by rinigus** [comment]
I see, thanks!

**Comment by VZuyev** [comment]
I tried to install a [build with kernel 4.14](https://androidfilehost.com/?w=files&flid=299590), but the system does not start, hangs on the Sony logo.

**Comment by rinigus** [comment]
Was it with the matching SW binaries for 4.14?

**Comment by zuyev** [comment]
Yes, SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_tama.zip

**Comment by rinigus** [comment]
Well, let's hear whether Hall sensor is expected to work on AOSP9/10 and then proceed from that. For bg, the issue was originally filed for Sailfish Tama port and ended up here as AOSP seems not to support it.

**Comment by mlehtima** [comment]
There was the Hall sensor fix done for 4.14 defconfigs at https://github.com/sonyxperiadev/kernel-defconfig/pull/98 and the same issue was in some other kernel versions also. Maybe any other supported kernel versions with missing drivers should be fixed.

**Comment by jerpelea** [comment]
Discontinued Android version
