### ISSUE TITLE
[LOIRE] [ALL] Offline charging is broken

### ISSUE THREAD

**Issue by jerpelea** [sonyxperiadev/bug_tracker#7]
Platform: SoMC Loire
Device: ALL
Kernel version: 4.4.xx
Android version: 8.0 (/ALL)

Description:
Offline charging starts and device reboots after a fiew seconds

Symptoms
Offline charging starts and device reboots after a fiew seconds

How to reproduce:
- conect device to a wall charger or PC USB. 
- the device will boot and enter offline charging
- after a fiew seconds device will reboot

**Comment by jerpelea** [comment]
After the latest patches:
- offline charging works when device is conected to a PC
- offline charging does not work when device is conected to a wall charger

**Comment by oshmoun** [comment]
The issue seems resolved now with https://github.com/sonyxperiadev/device-sony-common/pull/339

**Comment by dimitar10** [comment]
On a Suzu running the following:

**Kernel version**: 4.4.114-gb24fbb8-dirty (manually built on 13 Feb)
**Android version**: 8.1.0
**Firmware version**: v10

the device seems to boot into Flash mode when the user attempts to offline charge it on a PC.

**Comment by oshmoun** [comment]
@dimitar10 please create a new issue for the problem you described
