### ISSUE TITLE
[maple] Wifi does not work after full disk encryption

### ISSUE THREAD

**Issue by abioteau** [sonyxperiadev/bug_tracker#70]
**Platform:** Yoshino
**Device:** Maple
**Kernel version:** 4.4 (5.7_r1)
**Android version:** 7.1.1

**Description**
On maple device with FDE activated, Wifi cannot be enabled. This is like issue https://github.com/sonyxperiadev/bug_tracker/issues/63

Here are logcats at device start-up before disk decrypt [wifi_fde_first_boot.txt](https://github.com/sonyxperiadev/bug_tracker/files/1634775/wifi_fde_first_boot.txt) and after disk decrypt [wifi_fde_second_boot.txt](https://github.com/sonyxperiadev/bug_tracker/files/1634784/wifi_fde_second_boot.txt)

**Symptoms**
Wifi driver is not loaded. The symbolic links /sys/class/net/p2p0 and /sys/class/net/wlan0 are missing.

> maple:/ $ ls -l /sys/class/net/
> total 0
> lrwxrwxrwx 1 root root    0 2018-01-25 13:27 bond0 -> ../../devices/virtual/net/bond0
> -rw-r--r-- 1 root root 4096 2018-01-25 13:27 bonding_masters
> lrwxrwxrwx 1 root root    0 2018-01-25 13:27 dummy0 -> ../../devices/virtual/net/dummy0
> lrwxrwxrwx 1 root root    0 2018-01-25 13:27 lo -> ../../devices/virtual/net/lo
> **lrwxrwxrwx 1 root root    0 2018-01-25 13:27 p2p0 -> ../../devices/soc/18800000.qcom,icnss/net/p2p0**
> lrwxrwxrwx 1 root root    0 2018-01-25 13:26 rmnet_data0 -> ../../devices/virtual/net/rmnet_data0
> lrwxrwxrwx 1 root root    0 2018-01-25 13:26 rmnet_data1 -> ../../devices/virtual/net/rmnet_data1
> lrwxrwxrwx 1 root root    0 2018-01-25 13:26 rmnet_data2 -> ../../devices/virtual/net/rmnet_data2
> lrwxrwxrwx 1 root root    0 2018-01-25 13:26 rmnet_data3 -> ../../devices/virtual/net/rmnet_data3
> lrwxrwxrwx 1 root root    0 2018-01-25 13:26 rmnet_data4 -> ../../devices/virtual/net/rmnet_data4
> lrwxrwxrwx 1 root root    0 2018-01-25 13:26 rmnet_data5 -> ../../devices/virtual/net/rmnet_data5
> lrwxrwxrwx 1 root root    0 2018-01-25 13:26 rmnet_data6 -> ../../devices/virtual/net/rmnet_data6
> lrwxrwxrwx 1 root root    0 2018-01-25 13:26 rmnet_data7 -> ../../devices/virtual/net/rmnet_data7
> lrwxrwxrwx 1 root root    0 2018-01-25 13:26 rmnet_ipa0 -> ../../devices/virtual/net/rmnet_ipa0
> lrwxrwxrwx 1 root root    0 2018-01-25 13:27 sit0 -> ../../devices/virtual/net/sit0
> **lrwxrwxrwx 1 root root    0 2018-01-25 13:27 wlan0 -> ../../devices/soc/18800000.qcom,icnss/net/wlan0**

**How to reproduce**
1) Activate FDE
2) Try to enable Wifi

**Comment by jerpelea** [comment]
due to technical issues the upload of v8 Android 7.1.1 was incomplete and we hope to fix the release ASAP

**Comment by jerpelea** [comment]
The reason that Wifi is broken on your build is that the configuration files have been pushed to github  for the v8 release
https://github.com/sonyxperiadev/device-sony-yoshino/commit/b150ed7330252d8764b4ca980c3c616c308d51bd

while the v7 loads them from a symlink to the odm partiton
https://github.com/sonyxperiadev/device-sony-yoshino/commit/2ab89500246a47e7cf822ac1c8fec7cfbc8a0043#diff-517ddbf954b0717917a1aac0cbd8ae8a

If you check both commits you can see that on the old release fw is expected to be loaded from the "/system/etc/firmware/wlan/qca_cld" path while the new v8 release uses  "/vendor/firmware/wlan/qca_cld" path 

This bug will be solved as soon as v8 is published

**Comment by abioteau** [comment]
@jerpelea Could you reopen issue because vendor v8 for 7.1 does not solve it.

**Comment by abioteau** [comment]
There is no issue on suzu (loire) and kagura (tone) with vendor v8 for 7.1.

**Comment by abioteau** [comment]
It seems that issue is related to "macaddrsetup" service which cannot grant access to "/data/misc/wifi/wlan_mac.bin".

**Comment by jerpelea** [comment]
macaddrsetup is started after we have vold.post_fs_data_done=1
https://github.com/sonyxperiadev/device-sony-common/blob/n-mr1/rootdir/init.common.rc#L295

wifi is started after we have sys.boot_completed=1 
https://github.com/sonyxperiadev/device-sony-yoshino/blob/n-mr1/rootdir/init.yoshino.rc#L97

on a quick look everything is done is the right order and it works fine on 8.1

**Comment by jerpelea** [comment]
i will redo a test on 7.1

**Comment by abioteau** [comment]
I have partially solved issue with those commits https://github.com/abioteau/device-sony-yoshino/commit/af4af7284cae721b9886d4309daa026c58e6102a and https://github.com/abioteau/device-sony-sepolicy/commit/6f39b5c87f9ffcd9cecbcb6dca07cde032161276. 

Now, it works when there is no pin/password set and only after an initial reboot.

**Comment by jerpelea** [comment]
please push the permissions to selinux 
I have cherry-picked a6267a63cfa0661f6a3b74548b45769e2234a313

**Comment by jerpelea** [comment]
unfortunately i was wrong 
the permisison patch was prezent upstream and I cherry-picked it

**Comment by jerpelea** [comment]
may I close the issue?

**Comment by jerpelea** [comment]
i would suggest that you check this service 
https://github.com/sonyxperiadev/device-sony-yoshino/blob/n-mr1/rootdir/init.yoshino.rc#L92
it should start after macaddrsetup / maybe even manual start on sys.boot_completed=1

**Comment by abioteau** [comment]
I will check your suggest. Do not close the issue, it is still present when pin/password is set and on enabling encryption.

**Comment by abioteau** [comment]
When i add "-dd" option on **p2p_supplicant** service, i have the following logs : 

01-25 10:31:28.314  3681  3681 D wpa_supplicant: wpa_supplicant v2.6-devel-7.1.1
01-25 10:31:28.315  3681  3681 D wpa_supplicant: random: Added entropy from /data/misc/wifi/entropy.bin (own_pool_ready=2)
01-25 10:31:28.315  3681  3681 D wpa_supplicant: random: Trying to read entropy from /dev/random
01-25 10:31:28.315  3681  3681 D wpa_supplicant: Get randomness: len=20 entropy=1
01-25 10:31:28.317  3681  3681 D wpa_supplicant: random: Updated entropy file /data/misc/wifi/entropy.bin (own_pool_ready=2)
01-25 10:31:28.317  3681  3681 D wpa_supplicant: Global control interface '@android:wpa_wlan0'
01-25 10:31:28.317  3681  3681 D wpa_supplicant: Using Android control socket 'wpa_wlan0'
01-25 10:31:28.318  3681  3681 I wpa_supplicant: Successfully initialized wpa_supplicant
01-25 10:31:28.318  3681  3681 D wpa_supplicant: Override interface parameter: ctrl_interface ('(null)' -> '/data/misc/wifi/sockets')
01-25 10:31:28.318  3681  3681 D wpa_supplicant: Initializing interface 'p2p0' conf '/data/misc/wifi/p2p_supplicant.conf' driver 'nl80211' ctrl_interface '/data/misc/wifi/sockets' bridge 'N/A'
01-25 10:31:28.318  3681  3681 D wpa_supplicant: Configuration file '/data/misc/wifi/p2p_supplicant.conf' -> '/data/misc/wifi/p2p_supplicant.conf'
01-25 10:31:28.319  3681  3681 D wpa_supplicant: Reading configuration file '/data/misc/wifi/p2p_supplicant.conf'
01-25 10:31:28.319  3681  3681 D wpa_supplicant: ctrl_interface='/data/misc/wifi/sockets'
01-25 10:31:28.319  3681  3681 D wpa_supplicant: disable_scan_offload=1
01-25 10:31:28.320  3681  3681 D wpa_supplicant: update_config=1
01-25 10:31:28.320  3681  3681 D wpa_supplicant: device_name='Android_80a8'
01-25 10:31:28.320  3681  3681 D wpa_supplicant: config_methods='virtual_push_button physical_display keypad'
01-25 10:31:28.320  3681  3681 D wpa_supplicant: p2p_ssid_postfix='-Android_80a8'
01-25 10:31:28.321  3681  3681 D wpa_supplicant: persistent_reconnect=1
01-25 10:31:28.321  3681  3681 D wpa_supplicant: p2p_no_group_iface=1
01-25 10:31:28.321  3681  3681 D wpa_supplicant: pmf=1
01-25 10:31:28.322  3681  3681 D wpa_supplicant: Reading configuration file '/system/etc/wifi/p2p_supplicant_overlay.conf'
01-25 10:31:28.322  3681  3681 D wpa_supplicant: disable_scan_offload=1
01-25 10:31:28.322  3681  3681 D wpa_supplicant: p2p_no_group_iface=1
**01-25 10:31:28.324  3681  3681 E wpa_supplicant: Could not read interface p2p0 flags: No such device**
01-25 10:31:28.324  3681  3681 I wpa_supplicant: nl80211: Driver does not support authentication/association or connect commands
01-25 10:31:28.324  3681  3681 I wpa_supplicant: nl80211: deinit ifname=p2p0 disabled_11b_rates=0
01-25 10:31:28.325  3681  3681 D wpa_supplicant: nl80211: Remove monitor interface: refcount=0
01-25 10:31:28.325  3681  3681 D wpa_supplicant: netlink: Operstate: ifindex=0 linkmode=0 (kernel-control), operstate=6 (IF_OPER_UP)
**01-25 10:31:28.325  3681  3681 E wpa_supplicant: Could not read interface p2p0 flags: No such device**
01-25 10:31:28.325  3681  3681 D wpa_supplicant: nl80211: Set mode ifindex 0 iftype 2 (STATION)
01-25 10:31:28.326  3681  3681 D wpa_supplicant: nl80211: Failed to set interface 0 to mode 2: -19 (No such device)
**01-25 10:31:28.326  3681  3681 E wpa_supplicant: p2p0: Failed to initialize driver interface**
01-25 10:31:28.326  3681  3681 D wpa_supplicant: Failed to add interface p2p0
01-25 10:31:28.327  3681  3681 D wpa_supplicant: p2p0: Cancelling scan request
01-25 10:31:28.327  3681  3681 D wpa_supplicant: p2p0: Cancelling authentication timeout
01-25 10:31:28.327  3681  3681 D wpa_supplicant: Off-channel: Clear pending Action frame TX (pending_action_tx=0x0
01-25 10:31:28.328  3681  3681 D wpa_supplicant: Get randomness: len=20 entropy=0
01-25 10:31:28.329  3681  3681 D wpa_supplicant: random: Updated entropy file /data/misc/wifi/entropy.bin (own_pool_ready=2)

**Comment by abioteau** [comment]
@jerpelea Could you have a look on it?

**Comment by jerpelea** [comment]
the p2p errow can be ignored

**Comment by abioteau** [comment]
Log `wpa_supplicant: Could not read interface p2p0 flags: No such device` seems to be caused by missing files **/sys/class/net/p2p0** and **/sys/class/net/wlan0**.

When i remove **android.hardware.wifi.direct** feature to use wlan_supplicant instead of p2p_supplicant, i have the same issue but on wlan0 interface.
