### ISSUE TITLE
[Tama][AOSP10][4.14] Wireless charger frequently fails to charge

### ISSUE THREAD

**Issue by rinigus** [sonyxperiadev/bug_tracker#701]
**Platform:** Tama
**Device:** Akari
**Kernel version:** 4.14.232-gd88c66b3138a
**Android version:** android-10.0.0_r41 - Sailfish 4.1.0.24
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_tama

**Previously working on**

Has worked on AOSP9, at least in SFOS port.

**Description**

When putting the phone on wireless charger, charging is not always started by phone. At the same time, LED indicator on the charger itself does lid up showing that the connection with the phone is established. Currently, success rate of charging being detected by the phone is relatively low, maybe once in 2+ times. On AOSP9 based SFOS port, charging was always started by phone as soon as wireless charger LED indicator was lid up.

Charging started by phone was judged by presence of charging symbol and logs. When charging symbol was absent, the phone was found to be discharging in time. When present, phone was charging as expected.

**Logs**

Logs were taken from SFOS journal showing mix of dmesg and other processes. Logcat seemed to be rather empty in this respect, but I can acquire it if needed.

In this context, `mce` is a utility that senses and reacts to the changes in the states of the device. Such as starting/stopping charging, responds to power button and such.

*Log when charging works:*

[log-works.txt](https://github.com/sonyxperiadev/bug_tracker/files/6721295/log-works.txt) . 

Note that there are repetitive messages from IDTP that would appear during charging.

*Log when charging fails to start:*

[log-start-failed.txt](https://github.com/sonyxperiadev/bug_tracker/files/6721297/log-start-failed.txt)

Notice that mce switched from `discharging -> not_charging`; healthd shows `chg=w`. However, it failed to proceed to the charging state.

*Log when charging fails to start, taking device OFF the charger:*

[log-taking-off-failed.txt](https://github.com/sonyxperiadev/bug_tracker/files/6721301/log-taking-off-failed.txt)

Again there are changes in the charger state (mce and healthd), consistent with the failed log above.

**Additional context**

Originally filed under SFOS port issues: https://github.com/sailfishos-sony-tama/main/issues/147

**Comment by jerpelea** [comment]
Discontinued Android version
