### ISSUE TITLE
[AOSP10][4.14] Audio-hal-primary-hal loads 32-bit sound_trigger and qcomvisualizer

### ISSUE THREAD

**Issue by rinigus** [sonyxperiadev/bug_tracker#702]
**Platform:** Tama, probably influences others as well
**Device:** Apollo
**Kernel version:** 4.14
**Android version:** android-10.0.0_r41
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_tama

**Previously working on**

Hard to say whether it was an issue earlier as I was using 32-bit SFOS port.

**Description**

While following loaded libraries during PulseAudio initialization of Android drivers in aarch64 environment, I observed that few 32-bit libs were pulled:

```
"/vendor/lib/soundfx/libqcompostprocbundle.so" is 32-bit instead of 64-bit
...
"/vendor/lib/hw/sound_trigger.primary.sdm845.so" is 32-bit instead of 64-bit
```

Not sure whether it is of interest in context of AOSP10. To fix it I have patched the sources using https://github.com/sailfishos-sony-tama/main/blob/hybris-10/patches/vendor/qcom/opensource/audio-hal/primary-hal/0001-Load-libqcomvisualizer-and-sound_trigger.primary-fro.patch . 

Note that I have not seen any difference it terms of functionality with and without the patch.

Filing it here to document an issue, please feel free to close as low priority or not of interest to AOSP10/11

**Comment by MarijnS95** [comment]
Android audio is still solely 32-bit, unless you do https://github.com/MarijnS95/device-sony-common/commit/a5d83527891bc703fee79b09a75590a017aaeaac and then some. Including changes to AOSP repos like:

```diff
diff --git a/audio/common/all-versions/default/service/Android.bp b/audio/common/all-versions/default/service/Android.bp
index 3e8b71570..88cf7a0cd 100644
--- a/audio/common/all-versions/default/service/Android.bp
+++ b/audio/common/all-versions/default/service/Android.bp
@@ -8,7 +8,7 @@ cc_binary {
     // location for init to start it and the build system does not support
     // having two binaries installable to the same location even if they are
     // not installed in the same build.
-    compile_multilib: "32",
+    compile_multilib: "64",
     srcs: ["service.cpp"],

     cflags: [
```

**Comment by MarijnS95** [comment]
That said you can probably submit that `audio-hal` patch to our repo and we'll pick + port it to the relative branches, it's interesting and more correct nevertheless. I wonder if it can't just be `sound_trigger.primary.%s.so` and automatically pick the right library from available search paths.

**Comment by rinigus** [comment]
I will have to look into it and see why I get it 64 bit then. Maybe I should switch to 32 bit then, might have some other small issues on the way.

As for using plain `sound_trigger.primary.%s.so` not sure it will work as we have full paths given for all the libs there. Unfortunately, my patch is not full and there are some other libs untouched, they seemed to be not loaded in our case. So, it would be hard to test such changes.

**Comment by MarijnS95** [comment]
64-bit appears to work just fine here (in Android) so I don't think it's worth a lot of effort to try if the current patch works for you. That said however, it doesn't seem too useful to submit this then unless Android (say, maybe with 12) makes it easier to run 64-bit audio so that it can actually be migrated to and tested.

**Comment by rinigus** [comment]
I will close the issue for now as it is documented now and probably will be fixed when/if Android will switch to 64 bit sound as well.

@MarijnS95 thanks for insights!
