### ISSUE TITLE
[Tama][XZ2][AOSP10][4.14] UceService does not start

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#704]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.14
**Android version:** 11
**Software binaries version:** OEMv5

**Previously working on**
I think on Android 9

**Description**
In logcat a loop of the same error message floods my logs.

**Symptoms**
Battery drain I think. Maybe performance degradation?

**How to reproduce**
Use AOSP and do a `logcat -b all`

**Additional context**
The never ending loop
```
07-03 10:51:41.760  2414  3020 W HidlServiceManagement: Waited one second for com.qualcomm.qti.uceservice@2.2::IUceService/com.qualcomm.qti.uceservice
07-03 10:51:41.762   547   547 I hwservicemanager: Since com.qualcomm.qti.uceservice@2.2::IUceService/com.qualcomm.qti.uceservice is not registered, trying to start it as a lazy HAL.
07-03 10:51:41.764  2414  3020 I HidlServiceManagement: getService: Trying again for com.qualcomm.qti.uceservice@2.2::IUceService/com.qualcomm.qti.uceservice...
07-03 10:51:41.768   547  6032 W libc    : Unable to set property "ctl.interface_start" to "com.qualcomm.qti.uceservice@2.2::IUceService/com.qualcomm.qti.uceservice": error code: 0x20
07-03 10:51:42.140 25565 25594 E ocessService0:: failed to create Unix domain socket: Operation not permitted
07-03 10:51:42.190 31333 31344 E cessService0:1: failed to create Unix domain socket: Operation not permitted
07-03 10:51:42.226 27215 27227 E ocessService0:: failed to create Unix domain socket: Operation not permitted
07-03 10:51:42.260 27015 27028 E ocessService0:: failed to create Unix domain socket: Operation not permitted
07-03 10:51:42.296 32115 32149 E ocessService0:: failed to create Unix domain socket: Operation not permitted
07-03 10:51:42.300  4309  4321 E cessService0:1: failed to create Unix domain socket: Operation not permitted
07-03 10:51:42.312 32337 32350 E cessService0:1: failed to create Unix domain socket: Operation not permitted
07-03 10:51:42.312 27120 27131 E ocessService0:: failed to create Unix domain socket: Operation not permitted
07-03 10:51:42.345 27261 27272 E cessService0:1: failed to create Unix domain socket: Operation not permitted
```

**Comment by MarijnS95** [comment]
Could you rename this issue to `UceService does not start` (with appropriate tags), check since what OEM version that happens, and why it didn't start initially? The fact that it doesn't have a lazystart `interface` declaration (the reason for `property_set` on `"ctl.interface_start"` to fail) isn't more interesting than that.

(Sidenote: I vaguely recall tracking a similar issue with v5 initially, but it might have been a prerelease test version and/or local sepolicy mess...)

**Comment by MartinX3** [comment]
I don't find a .rc file but the manifests
If I googled correctly I should start it with
`adb shell am startservice com.qualcomm.qti.uceservice@2.2::IUceService/com.qualcomm.qti.uceservice` ?
That results in `Error: Not found; no service started.`

And my build date is 2021-06-10

**Comment by MarijnS95** [comment]
> I don't find a .rc file

IIRC it is hosted by `imsrcsd` (can be checked on a working device with `lshal | grep -i uceserv`). See if that fails to start in the log.

> If I googled correctly I should start it with
> `adb shell am startservice com.qualcomm.qti.uceservice@2.2::IUceService/com.qualcomm.qti.uceservice` ?

Nope, that's the fully-qualified name of the HAL interface instance, not the service that hosts it. Given that it's `imsrcsd`:

```
common/rootdir/vendor/etc/init/imsrcsd.rc
1:service vendor.imsrcsservice /odm/bin/imsrcsd
```

So `adb shell start vendor.imsrcsservice`. Can also run `/odm/bin/imsrcsd` directly, eventually with `strace`. (Fyi `am` is for Java managed services under "Activity Manager").

**Comment by MartinX3** [comment]
`lshal | grep -i uceserv`
returns nothing

executing `start vendor.imsrcsservice`
shows me
```
07-05 17:15:39.344     0     0 I init    : Control message: Processed ctl.start for 'vendor.imsrcsservice' from pid: 5999 (start vendor.imsrcsservice)
```
in the logs

executing `/odm/bin/imsrcsd`
shows me
```
07-05 17:13:37.321  5825  5825 I imsrcsd : Uce Service HAL  is starting up...
07-05 17:13:37.323  5825  5825 I imsrcsd : getAndroidPropValue : vendor.ims.DATA_DAEMON_STATUS[1]
```
in the logs

**Comment by MarijnS95** [comment]
> `lshal | grep -i uceserv`
> returns nothing

You need a device with working service for that. It's a good way to check if it started after running one of the below, though.

> executing `start vendor.imsrcsservice`
> shows me
> 
> ```
> 07-05 17:15:39.344     0     0 I init    : Control message: Processed ctl.start for 'vendor.imsrcsservice' from pid: 5999 (start vendor.imsrcsservice)
> ```
> 
> in the logs

And nothing else? Afaik this should show that the service registered, if it works. Before doing this (ie. reboot your device for a clean start) was this service running? (`ps -A | grep ims`)

Either way, check the logs after a reboot - a similar "start" message should show up, hopefully with more info.

> executing `/odm/bin/imsrcsd`
> shows me
> 
> ```
> 07-05 17:13:37.321  5825  5825 I imsrcsd : Uce Service HAL  is starting up...
> 07-05 17:13:37.323  5825  5825 I imsrcsd : getAndroidPropValue : vendor.ims.DATA_DAEMON_STATUS[1]
> ```
> 
> in the logs

Nothing else? Does the program keep running or terminate? Can you run it with `strace -f`?

**Comment by MartinX3** [comment]
> > `lshal | grep -i uceserv`
> > returns nothing
> 
> You need a device with working service for that. It's a good way to check if it started after running one of the below, though.
Sadly I don't own any other device.

So I did a reboot
```
# ps -A | grep ims
system          877      1 10793392  4292 do_select           0 S imsqmidaemon
system          963      1 11028580  9212 do_select           0 S imsdatadaemon
system         1302      1 10889472  9892 binder_ioctl_write_read 0 S imsrcsd
system         1437      1 10906388  9404 binder_ioctl_write_read 0 S ims_rtp_daemon
u0_a129        2338    710 13659248 96872 SyS_epoll_wait      0 S org.codeaurora.ims
```

and about `imsrcsservice` and `imsrcsd`
```
07-07 09:48:03.842     0     0 I init    : starting service 'vendor.imsrcsservice'...
7-07 09:48:03.855     0     0 I init    : Control message: Processed ctl.start for 'vendor.imsrcsservice' from pid: 963 (/odm/bin/imsdatadaemon)
07-07 09:48:03.881  1302  1302 I imsrcsd : Uce Service HAL  is starting up...
07-07 09:48:03.881  1302  1302 I imsrcsd : getAndroidPropValue : vendor.ims.DATA_DAEMON_STATUS[1]
07-07 09:48:08.895  1302  1302 I imsrcsd : getAndroidPropValue : vendor.ims.modem.multisub.cap[2]
07-07 09:48:08.895  1302  1302 I imsrcsd : Uce Service HAL  detected modemVersion[2]
07-07 09:48:08.896  1302  1302 I imsrcsd : Uce Service HAL  loading lib-imsrcs-v2
07-07 09:48:08.935  1302  1302 I Diag_Lib: StartImsService
07-07 09:48:08.936  1302  1302 I imsrcsd : ImsServiceMain startService[1]
07-07 09:48:08.959  1302  1663 I imsrcsd : ImsServiceMain Running..
07-07 09:48:10.650   750   750 W SSLM    : HIGH: SIM: [21/07/07 07:48:11]: 8367: mmgsdi.c: MMGSDI_CARD_INSERTED_EVT, slot: 0x1
07-07 09:48:10.813   750   750 W SSLM    : HIGH: SIM: [21/07/07 07:48:11]: 8230: mmgsdi.c: MMGSDI_PIN1_EVT, status: 0x1, slot: 0x1
07-07 09:48:10.813   750   750 W SSLM    : HIGH: SIM: [21/07/07 07:48:11]: 8250: mmgsdi.c: MMGSDI_PIN2_EVT, status: 0x1, slot: 0x1
```

And now starting from the first place the `uceservice` starting:
```
07-07 09:48:21.596     0     0 E init    : Control message: Could not find 'com.qualcomm.qti.uceservice@2.2::IUceService/com.qualcomm.qti.uceservice' for ctl.interface_start from pid: 545 (/system/bin/hwservicemanager)
```

Running `strace -f /odm/bin/imsrcsd`
[strace -f _odm_bin_imsrcsd.log](https://github.com/sonyxperiadev/bug_tracker/files/6775418/strace.-f._odm_bin_imsrcsd.log)

**Comment by MarijnS95** [comment]
Apparently Seine suffers the same issue, but I cannot repro it on Kumano. The log is different, too:

```
adb logcat -v color --pid=954
--------- beginning of system
08-08 19:33:12.457   954   954 I imsrcsd : Uce Service HAL  is starting up...
08-08 19:33:12.475   954   954 I imsrcsd : Uce Service HAL  loading imsrcsbaseimpl
07-07 10:11:49.003   954   954 I imsrcsd : Starting Service for First Time imsbaseimpl
07-07 10:11:49.016   954   954 I HidlServiceManagement: Registered com.qualcomm.qti.uceservice@2.2::IUceService/com.qualcomm.qti.uceservice
07-07 10:11:49.016   954   954 I imsrcsd : ImsRcsBaseImpl CM_IMSCONNECTIONMANAGER_CREATE_CONNECTION Before Registering Service
07-07 10:11:49.017   954   954 I HidlServiceManagement: Registered com.qualcomm.qti.imscmservice@2.2::IImsCmService/qti.ims.connectionmanagerservice
07-07 10:11:49.017   954   954 I imsrcsd : ImsRcsBaseImpl CM_IMSCONNECTIONMANAGER_CREATE_CONNECTION After Registering Service
```

This is on v5b. I don't know if the binary is different (compiled from a different branch, and/or with different set of flags) or if there's a runtime configuration file somewhere in our repositories that configures it to not start any of this.

**Comment by MarijnS95** [comment]
@MartinX3 Do you have any of the `vendor.ims` properties set as indicated by the log?

**Comment by MartinX3** [comment]
But I didn't set them by myself
```
[vendor.ims.DATA_DAEMON_STATUS]: [1]
[vendor.ims.ENABLE_HELPER]: [1]
[vendor.ims.QMI_DAEMON_STATUS]: [1]
[vendor.ims.activesub]: [0]
[vendor.ims.datadaemon.ims.netid]: [441492361229]
[vendor.ims.modem.multisub.cap]: [2]
[vendor.ims.rcs_loaded_version]: [2]
[vendor.ims.rcs_version]: [0]
```

**Comment by MarijnS95** [comment]
The logs might tell what service _did_ set these, I suspect `imsqmidaemon`.

**Comment by MarijnS95** [comment]
I have a blind guess that `imsrcsd : getAndroidPropValue : vendor.ims.modem.multisub.cap[2]` causes `imsrcsd : Uce Service HAL  detected modemVersion[2]` resulting in `imsrcsd : Uce Service HAL  loading lib-imsrcs-v2` which does not expose the service while `imsrcsd : Uce Service HAL  loading imsrcsbaseimpl` (on Kumano) does. Both libraries have lots of references to the interface.

**Comment by jerpelea** [comment]
@MartinX3 check if all ims services are started
ls /odm/bin/*ims*
ps -A | grep ims

on v4 we have a service name change and this caused the uceservice to fail. I fixed it on master branch for V4

**Comment by Thaodan** [comment]
Also happens on Edo on this time of writing on Android 11.

**Comment by jerpelea** [comment]
Discontinued Android version
