### ISSUE TITLE
[Tama][XZ2][AOSP10][4.14] No IPv6 possible

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#706]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.14
**Android version:** 11
**Software binaries version:** OEMv5

**Previously working on**

I tested it on a device from another person with the same APN with enabled IPv6.
IPv6 did work there.

**Description**
I don't get an IPv6 address.

**Symptoms**
If I switch to IPv6 only, I get no LTE.
`ERROR_DATA_SERVICE_SPECIFIC_ERROR` in the logs.

**How to reproduce**
Switch to IPv4/IPv6 in the APN.
Or switch to IPv6 only in the APN.

**Additional context**
Add any other context, e.g. upload logs or screenshots about the bug here.

`logcat -b radio` while switching to IPv6 only
[logcat -b radio.log](https://github.com/sonyxperiadev/bug_tracker/files/6775473/logcat.-b.radio.log)

**Comment by MartinX3** [comment]
It seems that my provider needs IMS to give me an IPV6.

I tested it with stock LOS 18.
IMS registered
VoLTE available
And I get my IPv6

So, probably after IMS starts working on SODP every provider should give us an IPv6.

**Comment by jerpelea** [comment]
Discontinued Android version
