### ISSUE TITLE
[AOSP11] android-11.0.0_r39 branch fetching errors

### ISSUE THREAD

**Issue by jevgenp** [sonyxperiadev/bug_tracker#707]
**Platform:** TAMA
**Device:** XZ2 Compact (H8324)
**Kernel version:** 4.14
**Android version:** 11
**Software binaries version:** OEM v5

**Previously working on**
Perfectly worked on all branches before, including r38.

**Description**
Fetching errors during repo sync.
Firstly encountered on VM where all was fine until this branch.
Then I tried reinstall/reconfigure VM from the scratch, but errors still there.

**Symptoms**
Screen from old VM
![Screenshot_1](https://user-images.githubusercontent.com/66970854/126061975-a492e703-3606-438d-a259-5dff1083f958.jpg)
And from reconfigured from scratch VM
![Screenshot_1](https://user-images.githubusercontent.com/66970854/126062003-40e76da3-549f-40db-ade1-300e03dd1866.jpg)

**How to reproduce**
run repo sync

**Comment by MarijnS95** [comment]
Might be a (temporary) _local_ network failure? Running `repo init -b android-11.0.0_r39` locally, followed by `repo sync` shows no issues here. It is unlikely both github and googlesource are (and remain) broken at the same time.

**Comment by jevgenp** [comment]
> Might be a (temporary) _local_ network failure?
Probably no. I was trying to reach few of those link in FF and they worked.
And time gap between tries was more than a day.
I tried to run sync today from home network - and no errors, perfectly synced.
Strange but fact :)
