### ISSUE TITLE
[loire] sensor_ind wakelock keeps device awake

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#71]
**Platform:** loire
**Device:** kugo
**Kernel version:** 5.7
**Android version:** 8.1 and 8.0

**Description**
In some situations, sensor hal seems to keep the wakelock sensor_ind held indefinitely. The sensor hal is a blob, hence it's difficult to find what happens exactly such that the hal decides to hold on to the wakelock. 

**Symptoms**
Device stays awake, no deepsleep

**How to reproduce**
It is pretty random when/whether it happens.

**Comment by jerpelea** [comment]
which vendor version are you using ?
please you try on the Android 8.0 !

**Comment by oshmoun** [comment]
I'm using v8 loire  image. 
I did have this issue on 8.0 back when 8.1 wasn't released yet.

**Comment by oshmoun** [comment]
Updated issue concerning which android versions were tested to avoid confusion

**Comment by oshmoun** [comment]
This seems to not be a blobs issue.
After checking "dumpsys sensorservice", found out that an app (Amazon prime video) was using the accelerometer, even though the app itself was closed. Will keep an eye on sensor usage and see if it correlates with the wakelock

**Comment by oshmoun** [comment]
After a couple days testing, it seems the accelerometer (bmi160) is the cause of wakelock

**Comment by oshmoun** [comment]
ok there seems to be a pattern here. The following is merely based on testing for a couple weeks, so not exactly valid as proof due to lack of code and/or logs that explicitly pinpoint a cause. Nonetheless, here it is:
1. Turn off automatic rotation -> wakelock appears in a matter of hours (consistently reproducible while testing)
2. Turn on automatic rotation -> wakelock never appears (at least not in the testing timeframe)
A possible conclusion from these observations is that the wakelock appears if the sensor remains unused for a while?

**Comment by jerpelea** [comment]
@oshmoun updates?

**Comment by oshmoun** [comment]
After having automatic rotation turned on since the observation described above, the issue never happened. Considering sensors logic is proprietary, I don't know what else I could do to diagnose further.

**Comment by jerpelea** [comment]
I think that this issue should be closed since there is no way to investigate the issue on the DSP side

**Comment by oshmoun** [comment]
well, there are bad hacks that can be done to workaround the issue
https://github.com/InvictrixRom-devices/kernel_huawei_angler/commit/c3d3f06f58ebab2ee281ea9b038f80ebc0156817
I don't know which is better, keeping the issue unsolved, or having a bad hack in kernel
your call :)

**Comment by jerpelea** [comment]
can you replicate the issue on other platforms?

**Comment by oshmoun** [comment]
i don't know about yoshino,but tone is definitely unaffected.

**Comment by oshmoun** [comment]
just for your information, the commit has now been ported over to our kernel, and is available here for experimenting:
https://gerrit.omnirom.org/#/c/29346/

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/kernel/pull/1588
mitigation merged
