### ISSUE TITLE
Java smart card in nanoSIM format not work

### ISSUE THREAD

**Issue by bjbole** [sonyxperiadev/bug_tracker#713]
**Platform:** bahamut
**Device:** Sony Xperia 5
**Kernel version:** 
**Android version:** Android 11 AOSP R40
**Software binaries version:** Build from AOSP, build version RQ3A.210805.001.A1

**Is your feature request related to a problem? Please describe.**
After inserting the java smart card in nano SIM format, the phone does not detect it and the card cannot be accessed. The ARA-M applet is installed and configured on the card.

**Describe the solution you'd like**
I want you to explain to me how I can use a java smart card in nano SIM format as a secure element.

**Describe alternatives you've considered**

**Additional context**

**Comment by Haxk20** [comment]
Do you have any website link where it explains what it actually is ?
Cause it doesnt sound like an normal SIM card that could be used for phone calls which the phone expects.

The only info i found about it is an SIM to USB device that could be used for accessing it.
I do not think the SIM card is actually supposed to go into the phone SIM slot.

But if you have some website where i could read about what it actually is. If its some sort of safe storage i do not think it should go into the SIM slot on a phone. But i may be wrong.

**Comment by bjbole** [comment]
I want to put a classic java smart card in the SIM slot on my phone and use it as a security element.

When I put a classic java smart card (nano SIM format) in a mobile phone, it is not recognized and the isSecureElementPresent() method from SEService returns false.

The Link below contains information about the service proposed to be 
used to access and send apdu commands to smart cards.

https://developer.android.com/reference/android/se/omapi/SEService

**Comment by Haxk20** [comment]
> I want to put a classic java smart card in the SIM slot on my phone and use it as a security element.
> 
> When I put a classic java smart card (nano SIM format) in a mobile phone, it is not recognized and the isSecureElementPresent() method from SEService returns false.
> 
> The Link below contains information about the service proposed to be
> used to access and send apdu commands to smart cards.
> 
> https://developer.android.com/reference/android/se/omapi/SEService

I see. May i ask did this work on stock system on the device ?

**Comment by bjbole** [comment]
It reacts in the same way to a device with a factory operating system.

I think the problem is in the implementation of the RIL library whose source code is not available. The callback method from SEService is called from this library when detecting the operator's SIM card. There should also be a procedure here for detecting a classic java smart card as a Secure element.

**Comment by MarijnS95** [comment]
> and the isSecureElementPresent() method from SEService

You mean the method from the [`Reader`](https://developer.android.com/reference/android/se/omapi/Reader)? `SEService` does not have a method.

This however implies that `SEService.isConnected()` returns `true`, and that `getReaders()` gave back a non-empty list. Can you list the names of the readers with [`getName()`](https://developer.android.com/reference/android/se/omapi/Reader#getName()) so that we can make sure this is indeed the SIM card reader (should print SIM1 or SIM2).

Radio, RIL and service logs are interesting to see right as the card is inserted, maybe they contain a hint as to whether a secure element is detected. Things to grab:

- `adb logcat -b default,kernel,radio`. You can clear the logs with `adb logcat -c` before starting that command (pipe it to a file) and inserting the card;
- `adb root && adb shell lshal | grep -i secure` to see if the interface is registered (it should as we have the vintf/policy for it);
- Check if `adb shell dumpsys` contains anything interesting, you can list individual services with `-l`.

**Comment by MarijnS95** [comment]
> It reacts in the same way to a device with a factory operating system.

Then it is _extremely_ unlikely that the Open Devices project can support this, unfortunately. Unless there's a simple (legacy) compiler flag to toggle.

After all, `qcrild` registers the secure element HAL interface for both sims; it wouldn't do that if it doesn't provide access to a SE over it (might be buggy though, won't be the first time).

**Comment by bjbole** [comment]
How to provide access to a SE over it. I have implemented and initialilzed ARA-M applet in my calsic JAVA smart card?

**Comment by MartinX3** [comment]
https://github.com/seek-for-android/pool/wiki
Maybe this helps you @bjbole

**Comment by bjbole** [comment]
Started with Android 9 this is integrated in android OS but with this service java card is not recognized by operating sistem when his is put in nano SIM slot.

**Comment by MartinX3** [comment]
But without the requested logs, there is nothing we can do.

**Comment by bjbole** [comment]
There is log files from my phone with inserted onli java card in SIM1 slot.

adb logcat -b default,kernel,radio/media/borisa/E4C8-396B/Logovi/log.txt

[log.txt](https://github.com/sonyxperiadev/bug_tracker/files/7044409/log.txt)

adb root && adb shell lshal | grep -i secure

[lshal.txt](https://github.com/sonyxperiadev/bug_tracker/files/7044411/lshal.txt)

adb shell dumpsys

carrier_conf
[dump_carrier_conf.txt](https://github.com/sonyxperiadev/bug_tracker/files/7044414/dump_carrier_conf.txt)

secure_element
[dump_sec_elem.txt](https://github.com/sonyxperiadev/bug_tracker/files/7044416/dump_sec_elem.txt)

**Comment by MarijnS95** [comment]
Unknown means just that, unknown. This is likely a default-initialization, as there's no pin state to read/know if the card has an error in the first place.
