### ISSUE TITLE
Auto-reboot for factory data reset loop on Sony Xperia XA2 (pioneer)

### ISSUE THREAD

**Issue by tl3gr4nd** [sonyxperiadev/bug_tracker#715]
**Platform:**
**Device: Sony Xperia XA2 (pioneer)**
**Kernel version:**
**Android version: android-11.0.0_r40**
**Software binaries version: SW_binaries_for_Xperia_Android_11_4.14_v6_nile**

After I successfully compiled the `aosp_h3113-user` distribution (what I gave to `lunch`), I flashed the images using fastboot like specified in the guide. I power on the phone (without a SIM card) , Android loads and the main screen appears. I can browse the applications, activate the developer secret menu... But, after a time (less than 5 minutes), it reboots automatically with a message: 'Factory data reset. Restarting...'. Then, the "Android recovery" screen appears with the following message :

```
Cannot load Android system; Your data may be corrupt. If you continue to get this message, you may need to perform a factory data reset and erase all data stored on this device.
```

I tried the factory data reset, to ignore the message but this reboot always happens.

I took a video with another device that  I converted it to a gif (sorry for the quality). The displayed screen before the reboot was the "About phone" where we can see the uptime in the settings: ![reboot_auto_to_factory_reset](https://user-images.githubusercontent.com/89870139/132136541-e3a3ad5f-d0df-4d33-b28b-d9900bea3602.gif)

And I attached logcat logs. Note that they are not  not the ones generated from the video but from a previous attempt to understand what happened.
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/7112073/logcat.log)

In those logs, we can see many `Process com.android.phone has crashed too many times: killing!` because of `Caused by: java.lang.IllegalStateException: Sensor is null.`. And I suspect the cause of the reboot is a "received command" by 'uncrypt' on the line 7326 of the log file but I do not know why.

**Comment by bartcubbins** [comment]
I can confirm this issue and we are working on it. Caused by https://source.android.com/devices/tech/debug/rescue-party

**Comment by MarijnS95** [comment]
Ah, the good-old partycrasher rebooting defenseless phones because we're missing sensors, in turn causing transpower to fail and taking the whole telephony stack down :(
