### ISSUE TITLE
autoreboot Sony Xperia 10 III (lena)

### ISSUE THREAD

**Issue by Aarqw12** [sonyxperiadev/bug_tracker#716]
Platform:
Device: Sony Xperia 10 III (lena)
Kernel version: 4.19
Android version: android-11.0.0_r45
Software binaries version: SW_binaries_for_Xperia_Android_11_4.19_v7_lena

After I successfully compiled the aosp_xqbt52-userdebug distribution ( used script kernel clang for generate prebuild previously ) , devices bootlop only . I see recovery flashed bootlop too. 

I tried before from stock xperia to compile copyleft kernel and its have bootlop too.

**Comment by MartinX3** [comment]
Did you boot the newest official stock firmware first on both slots?

What are the exact steps you did to compile this rom?
And to flash it?

Does your bootloop has adb for a logcat?

**Comment by Aarqw12** [comment]
> Did you boot the newest official stock firmware first on both slots?
> 
> What are the exact steps you did to compile this rom?
> And to flash it?
> 
> Does your bootloop has adb for a logcat?

yes I have flashed firmware 62.0.A.3.109 before.

no sadly I have looked for log and its bootlop in splash.

tried ramoops too for copyleft kernel over stock 62.0.A.3.109 before flash sodp and log is empty

**Comment by MartinX3** [comment]
Did you try to deactivate vbmeta with fastboot?

If you carefully copy your TA partition on your sdcard, you could read the logs inside.
(Open as text file)
But don't write to the partition at all costs.
It would damage your device forever.

**Comment by Aarqw12** [comment]
> Did you try to deactivate vbmeta with fastboot?
> 
> If you carefully copy your TA partition on your sdcard, you could read the logs inside.
> (Open as text file)
> But don't write to the partition at all costs.
> It would damage your device forever.

fastboot erase metadata
fastboot flash boot_a boot.img​
fastboot flash boot_b boot.img​
fastboot --disable-verification --disable-verity flash vbmeta vbmeta.img
fastboot flash dtbo_a dtbo.img​
fastboot flash dtbo_b dtbo.img​
fastboot flash system_a system.img​
fastboot flash system_b system.img​
fastboot flash system_ext_a system_ext.img
fastboot flash system_ext_b system_ext.img
fastboot flash oem_a SW_binaries_for_Xperia_Android_11_4.19_v7_lena.img
fastboot flash oem_b SW_binaries_for_Xperia_Android_11_4.19_v7_lena.img
fastboot flash vendor_a vendor.img​
fastboot flash vendor_b vendor.img​
fastboot flash product_a product.img​​
fastboot flash product_b product.img​​
fastboot flash vbmeta_system vbmeta_system.img 

as say Haxk20 need dont flash recovery.img I have used recovery he give him via telegram chat. 

for TA I will look

**Comment by MartinX3** [comment]
What about the other vbmeta partition?
You deactivated only one.

**Comment by Aarqw12** [comment]
> What about the other vbmeta partition?
> You deactivated only one.

Its change nothing in result sadly

**Comment by MartinX3** [comment]
We could locate the problem and it is being worked on :)

**Comment by jerpelea** [comment]
before flashing the device please run 
"fastboot reboot fastboot"
This will use the android fastboot and allow you to flash all partitions

**Comment by jerpelea** [comment]
fastboot reboot fastboot
fastboot flash boot_a boot.img
fastboot flash dtbo_a dtbo.img
fastboot flash product_a product.img
fastboot flash recovery_a recovery.img
fastboot flash oem SW_binaries_for_Xperia_Android_11_4.19_v7_lena.img
fastboot flash --disable-verity --disable-verification vbmeta_a vbmeta.img
fastboot flash --disable-verity --disable-verification vbmeta_system_a vbmeta_system.img
fastboot flash vendor_a vendor.img
fastboot flash system_a system.img
fastboot flash system_ext_a system_ext.img
fastboot flash userdata userdata.img
fastboot erase metadata
fastboot --set-active=a

**Comment by Aarqw12** [comment]
> before flashing the device please run
> "fastboot reboot fastboot"
> This will use the android fastboot and allow you to flash all partitions

fastbootd yes I always use that its needed as its dynamic partition phone . I have tried your script too and its no boot ...

@MartinX3 tell me  " luckily they got tombstones
dunno what you did but we got a logcat ".

**Comment by Aarqw12** [comment]
from prebuild kernel its boot , I did something wrong in build kernel I will search myself solution
