### ISSUE TITLE
[TAMA][AOSP11] AOSP r43 with OEM v7 issue

### ISSUE THREAD

**Issue by jevgenp** [sonyxperiadev/bug_tracker#717]
**Platform:** H8324
**Device:** XZ2 Compact
**Kernel version:** 4.14
**Android version:** 11
**Software binaries version:** OEM v7

**Previously working on**
AOSP r40 with OEM v6

**Description**
Infinite "Factory reset" after system boots when phone not connected to PC.

**Symptoms**
If phone not connected to PC over USB cable, after 15-20sec when system boots it going to restart to recovery with message "Factory Reset" and this actions loops.. If connected to PC before or after booting - works without restarts.

**How to reproduce**
Compile latest r43 build and flash it with latest OEM v7 

[r43v7.txt](https://github.com/sonyxperiadev/bug_tracker/files/7155008/r43v7.txt)

**Comment by jerpelea** [comment]
I will build and try to replicate

**Comment by MarijnS95** [comment]
```
09-13 14:18:48.188     0     0 I init    : starting service 'vendor.tad_static'...
09-13 14:18:48.189     0     0 I init    : Created socket '/dev/socket/tad', mode 660, user 1000, group 1000
09-13 14:18:48.193   857   857 I chatty  : uid=1000(system) /vendor/bin/macaddrsetup identical 3065 lines
09-13 14:18:48.193   857   857 E tadif   : Failed to connect to tad.
09-13 14:18:48.194  4463  4463 I tad     : Trim Area daemon starting.
09-13 14:18:48.194   857   857 E tadif   : Failed to connect to tad.
09-13 14:18:48.194   857   857 E tadif   : Failed to connect to tad.
09-13 14:18:48.194  4463  4463 I tad     : Using trim area info (0,16) from arguments.
09-13 14:18:48.194   857   857 E tadif   : Failed to connect to tad.
09-13 14:18:48.195  4463  4463 I tad     : Trim Area using TA version 3.
09-13 14:18:48.195   857   857 E tadif   : Failed to connect to tad.
09-13 14:18:48.196  4463  4463 E tad     : TA location is (partly) outside the device or file 4096 < 16384
09-13 14:18:48.196   857   857 E tadif   : Failed to connect to tad.
09-13 14:18:48.196  4463  4463 E tad     : Failed to configure TA library.
09-13 14:18:48.198     0     0 I init    : Service 'vendor.tad_static' (pid 4463) exited with status 1
09-13 14:18:48.198     0     0 I init    : Sending signal 9 to service 'vendor.tad_static' (pid 4463) process group...
09-13 14:18:48.198     0     0 I libprocessgroup: Successfully killed process cgroup uid 0 pid 4463 in 0ms
09-13 14:18:48.198     0     0 E init    : updatable process 'vendor.tad_static' exited 4 times in 4 minutes
09-13 14:18:48.200     0     0 I init    : processing action (sys.init.updatable_crashing=1) from (/system/etc/init/flags_health_check.rc:10)
09-13 14:18:48.197   857   857 E tadif   : Failed to connect to tad.
09-13 14:18:48.200     0     0 I init    : starting service 'exec 26 (/system/bin/flags_health_check UPDATABLE_CRASHING)'...
09-13 14:18:48.203     0     0 I init    : SVC_EXEC service 'exec 26 (/system/bin/flags_health_check UPDATABLE_CRASHING)' pid 4464 (uid 1000 gid 1000+0 context default) started; waiting...
```

Tad breaks, and throws telephony overboard. Partycrasher reboots the phone to request a wipe if it wasn't for USB:

```
09-13 14:18:43.089  1066  1138 V RescueParty: Disabled because of active USB connection
```

Blame AOSP for that joke of a "solution".

**Comment by jerpelea** [comment]
@MarijnS95 this still does not explain why tad is crashing 
I have to try to replicate the error (tad one)

**Comment by MarijnS95** [comment]
@jerpelea It's this:

```
09-13 14:18:48.194  4463  4463 I tad     : Trim Area daemon starting.
09-13 14:18:48.194  4463  4463 I tad     : Using trim area info (0,16) from arguments.
09-13 14:18:48.195  4463  4463 I tad     : Trim Area using TA version 3.
09-13 14:18:48.196  4463  4463 E tad     : TA location is (partly) outside the device or file 4096 < 16384
09-13 14:18:48.196  4463  4463 E tad     : Failed to configure TA library.
```

**Comment by jerpelea** [comment]
@MarijnS95 should not happen

**Comment by jerpelea** [comment]
-service vendor.tad_static /odm/bin/tad_static /dev/block/bootdevice/by-name/TA 0,16
+service vendor.tad_static /odm/bin/tad_static /dev/block/bootdevice/by-name/TA 0,16 2
result 
01-09 01:19:56.545     0     0 I init    : Created socket '/dev/socket/tad', mode 660, user 1000, group 1000

**Comment by MarijnS95** [comment]
https://github.com/sonyxperiadev/device-sony-tama/commit/37a5718d079951b7bdc6f3a202eea49516d8d82b

Yes, this should have been `tad_legacy.rc` for V2, now it gets V3 as per the above logs.

**Comment by jerpelea** [comment]
@MarijnS95 
already fixed

**Comment by jerpelea** [comment]
please sync and rebuild

**Comment by jevgenp** [comment]
Maybe I'm doing something wrong but after repo sync/repo_update and recompiling rom still the same.
[restart.txt](https://github.com/sonyxperiadev/bug_tracker/files/7156637/restart.txt)

**Comment by MartinX3** [comment]
@jevgenp 
The device-sony-tama repo got force pushed, means its git history got manipulated
Please look into your sync logs for any error and maybe you need to hard reset the repo manually.
