### ISSUE TITLE
[Nile][Pioneer][AOSP11] Rapid scrolling lagging

### ISSUE THREAD

**Issue by llabadie** [sonyxperiadev/bug_tracker#719]
**Platform:** Nile
**Device:** Pioneer
**Kernel version:** 4.14
**Android version:** 11
**Software binaries version:** 7

**Previously working on**
No working reference with AOSP 11.

**Description**
We're currently trying to flash AOSP 11 on Sony XA2 device. We followed the tutorial [here](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-11-0-0/). We tried with AOSP 11 versions r36 and r40.

We flashed the firmware found on [sony website](https://developer.sony.com/file/download/software-binaries-for-aosp-android-11-0-kernel-4-14-nile/) (version 7).

**Symptoms**

Medium speed and rapid scrolling lagging (this is not easy to see) --> similar to #669

From previous post:
- back camera (green screen, slow, lost connection with hardware) -> resolved by #469 and #646
- frequent recovery mode reboot (only happens when not plugged to the computer) --> resolved by #717
- #664 although this is not always happening --> seems to be resolved since previous fixes

**How to reproduce**
Images flashed:

| Partition     | Images                                                                             |
|:--------------:|:-------------------------------------------------------------------------- |
| oem           | SW_binaries_for_Xperia_Android_11_4.14_v7_nile.img |
| boot           | boot.img                                                                           |
| system       | system.img                                                                      |
| vendor       | vendor.img                                                                       |
| userdata    | userdata.img                                                                    |

Scrolling lagging:

1. In Setting, scroll rapidly and see frames lagging. Like several frames are displayed at the same time.

**Additional context**
[build_env.txt](https://github.com/sonyxperiadev/bug_tracker/files/7202348/build_env.txt)
[fastboot_getvar_all.txt](https://github.com/sonyxperiadev/bug_tracker/files/7202342/fastboot_getvar_all.txt)
[kernel_boot_logs.txt](https://github.com/sonyxperiadev/bug_tracker/files/7202346/kernel_boot_logs.txt)
[logcat_boot_logs.txt](https://github.com/sonyxperiadev/bug_tracker/files/7202351/logs_camera_FW7_AOSP11r40.txt)

**Comment by llabadie** [comment]
Reboot in recovery mode resolved with #717

**Comment by MartinX3** [comment]
@llabadie If you put many issues into the same issue ticket about a camera problem, we can't help you.

**Comment by bartcubbins** [comment]
I will leave my comment

> * back camera (green screen, slow, lost connection with hardware)

with the upcoming 4.19 kernel, the AOSP camera app works fine, camera crashes or something else was not detected (I have not tested Open camera or other apps yet).

> * Boot loop on charging

I had something similar, I fixed it and pushed the fix from several parts into the sony/common repo, and the second part of the fix is in Nile/Ganges 4.19 kernel bring up pull request. When I have time, I will backport a fix for the 4.14 kernel and push it.

P.S. and yes, we'd all love it if you stick to the one bug, one ticket rule. Thanks!;)

**Comment by llabadie** [comment]
Camera bugs resolved with #469 waiting for a more permanent solution (#646)

Sorry for the multiple issues, as there is only one left I will rename the issue and update my description

**Comment by jerpelea** [comment]
Discontinued Android version
