### ISSUE TITLE
[Tone] Bluetooth issue while pairing

### ISSUE THREAD

**Issue by Paulbouchara** [sonyxperiadev/bug_tracker#72]
Platform: Tone
Device: Kagura 
Kernel version: 4.4 (LA.UM.5.7.r1)
Android version: 8.1/8.0

Bluetooth have issues, some devices couldn't pair properly such as ds4 controller.
Will take dmesg and logcat, even if logcat via matlog doesn't show anything relevant.

How to reproduce :
Standard pairing procedure, audio devices are fine.
Special devices like ldac, hid devices need a reboot to pair or doesn't even pair at all.
Tested so far:
Ds4 controller
Audio headset (MDR-ZX330BT)
Ldac device at a local shop
Will test later:
Apple keyboard and mouse

**Comment by jerpelea** [comment]
have you enabled the DS4 controller in kernel config?

**Comment by jerpelea** [comment]
check the kernel config

**Comment by jerpelea** [comment]
@Paulbouchara the DS4 controler is not suported by the project. I tested another  Controller model and it works fine over BT.

Please close the ticket if you do not have issues with other connected devices
