### ISSUE TITLE
Update building guide

### ISSUE THREAD

**Issue by H-A-L-I-S** [sonyxperiadev/bug_tracker#720]
**Platform:** All
**Device:** All
**Kernel version:** All
**Android version:** All
**Software binaries version:** All

**Is your feature request related to a problem? Please describe.**
There are a few problems with the building guide

**Describe the solution you'd like**
I made a list with suggestions

**Describe alternatives you've considered**
Please update these points in the building guide (https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-11-0-0/) (it might help the one or other newcomer):
1. Include curl in the dependencies
2. Include python-in-python3 in the dependencies (for Ubuntu, which is the recommended OS in the guide). Otherwise a newcomer will get this error and might not know what to do: `/usr/bin/env 'python' no such file or directory`
3. A advice to run "git config --global user.email "YOUR_EMAIL"" and "git config --global user.name "YOUR_NAME"" if it has not been done previously.
4. Below step 4.1. is a note: "Note: The downloaded data is around 20 GB, and for a successful build you need 100 GB free hard disk space". This is not correct. It actually downloads more than 80GB and needs 300GB of free disk space  (if I remember correctly).

**Comment by jerpelea** [comment]
resolved
