### ISSUE TITLE
Screen does often not turn on correctly

### ISSUE THREAD

**Issue by halis300** [sonyxperiadev/bug_tracker#721]
**Platform:** yoshino 
**Device:** maple
**Kernel version:**  4.14, İ think (İ did not touch that)
**Android version:** 11
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.14_v7_yoshino.zip

**Previously working on**
Has this always been a problem, or is it a new issue?
New issue after İ flashed SODP, which İ build. İ followed exactly the guide. Previously İ had non such issue

**Description**
When İ want to open the screen, it shows often (about 4 out of 5 times) this:
![IMG_20210923_162124_757](https://user-images.githubusercontent.com/79767757/134530745-ee4d7740-156c-4bab-9de6-6def557a4644.jpg)

**Symptoms**
As seen on the picture above

**How to reproduce**
Write how to reproduce here.
just press the power button

**Additional context**
İ will post logcat later here

**Comment by halis300** [comment]
Without fingerprint
[screenerror_without_fingerprint.txt](https://github.com/sonyxperiadev/bug_tracker/files/7219158/screenerror_without_fingerprint.txt)

Wirh fingerprint
[with_fingerprint.txt](https://github.com/sonyxperiadev/bug_tracker/files/7219159/with_fingerprint.txt)

There are a lot of RQBalance-PowerHAL-Hints errors

**Comment by jerpelea** [comment]
Discontinued Android version
