### ISSUE TITLE
Does Xperia 10 III (lena platform) have magnetic lid sensor (hall sensor)?

### ISSUE THREAD

**Issue by mlehtima** [sonyxperiadev/bug_tracker#722]
**Platform:** 
**Device:** Sony Xperia 10 III (lena)
**Kernel version:** 4.19
**Android version:** android-11.0.0_r43
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.19_v7b_lena

The device tree of Xperia 10 III contains the same bu520x1nvx entry as several other devices (in lagoon-qrd.dtsi) which made me think if the really device supports lid sensor, also there is the bu520x1nvx driver but it's not enabled in defconfig and fails to build because of incorrect include for bu520x1nvx.h and missing hall sensor entries (HALL_SENSOR_NOT_USE_SWITCH and HALL_SENSOR_NOT_USE_SETUP_TIMER) from drivers/input/misc/Kconfig. After fixing the build issues and flashing the kernel I can see the input device but no events when trying to trigger an event using magnet. Is the entry in device tree incorrect and there is no lid sensor in the device or is there some other issue with the sensor?

**Comment by mlehtima** [comment]
Looks like there is no functional Hall sensor on lena platform so closing this bug.

**Comment by nekrondev** [comment]
Meanwhile some firmware update changed the situation (Hall sensor is working).
https://forum.sailfishos.org/t/xperia-10-iii-hall-magnet-sensor/12225/18?u=nekron

**Comment by klokik** [comment]
I wonder if nagara (xperia 1 IV) has this sensor. The driver is surely there, loaded and getting interrupts. But what about the sensor being actually there? I wasn't able to trigger it with a magnet, but occasionally it gets triggered on itself blanking the screen.

So either it's broken on my device, or not present at all on the board and the pin is floating in high impedance state.
