### ISSUE TITLE
[4.14][11][bahamut] Pick up/lift gesture does not work

### ISSUE THREAD

**Issue by voidanix** [sonyxperiadev/bug_tracker#725]
**Platform:** kumano
**Device:** bahamut
**Kernel version:** 4.14.240
**Android version:** 11
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.14_v7_kumano.img

**Previously working on**
none AFAIK

**Description**
Currently the device has the "Lift to check phone" option in settings that does absolutely nothing.
Looking around other issues, it seems like other devices also have issues with the lift/pickup gesture.

**Symptoms**
"Lift to check phone" option in settings does nothing and logcat also reports nothing.

**How to reproduce**
Enable the option mentioned above and see the phone not do anything.

**Additional context**
What I cannot comprehend is why does logcat not show anything that indicates the pickup gesture is availible or not on the device, except for this at startup:
```
I sensors-hal: activate:209, com.sonymobile.sensor.pickup_gesture_pure/2002 en=0
I sensors-hal: activate:220, com.sonymobile.sensor.pickup_gesture_pure/2002 en=0 completed
```
Looking around the device, it seems that `com.sonymobile.sensor.pickup_gesture_pure` does not actually exist and `sensors.ssc.so` (presumably called by hals.conf for the sensors multi-HAL) does look to support the gesture.

`pickup_gesture` is also mentioned in the persist partition in `sensors_list.txt`, but that might just be some remains from the stock image as it also mentions `camera_lift_trigger`.

**Comment by voidanix** [comment]
@jerpelea any update on this? All the binaries for all kumano versions do not expose `android.sensor.pick_up_gesture` it seems

**Comment by jerpelea** [comment]
this is a limitation that can not be avoided
