### ISSUE TITLE
[Tama][Akari][AOSP12][4.14] AOSP12 bootlop with latest oem (v7)

### ISSUE THREAD

**Issue by farukr1** [sonyxperiadev/bug_tracker#726]
**Platform:** Tama
**Device:** Akari
**Kernel version:** 4.14
**Android version:** 12
**Software binaries version:** v7

**Previously working on**
AOSP11

**Description**
Built AOSP12 using the official instruction on 15th Nov, flashed latest oem v7 but device bootloops after showing the boot animation for a split second.

**Symptoms**
Device reboots quickly after displaying the boot logo. After a couple of restarts, it displays:

"Your device is corrupt, it can't be trusted and will not boot."

**How to reproduce**
Build AOSP12 and try booting with latest oem.

**Additional context**
Couldn't get any logs without ADB access.

**Comment by MartinX3** [comment]
Please wait for the OEM release for Android 12

**Comment by farukr1** [comment]
> Please wait for the OEM release for Android 12

Saw this for XZP:    https://forum.xda-developers.com/t/rom-aosp-12-sodp-12-0-0_r2.4352415/

Thought I also could use the latest oem to boot AOSP12...

**Comment by MartinX3** [comment]
> > Please wait for the OEM release for Android 12
> 
> Saw this for XZP: [forum.xda-developers.com/t/rom-aosp-12-sodp-12-0-0_r2.4352415](https://forum.xda-developers.com/t/rom-aosp-12-sodp-12-0-0_r2.4352415/)
> 
> Thought I also could use the latest oem to boot AOSP12...

Yes, he's a dev
If you find a way to boot it without OEM A12, let us know (until then you might remove encryption support) :)

**Comment by MarijnS95** [comment]
You can run this just fine on OEMv7 for A11, anyone can, except @MartinX3.

On a device with a 4.14 kernel (anything but Edo and Lena), just be sure to set `OVERRIDE_PRODUCT_COMPRESSED_APEX := false`.

**Comment by MartinX3** [comment]
Hostile bla bla like usually <3

**Comment by MarijnS95** [comment]
@MartinX3 It's a joke, you know just as well as I do how to get your device booting on Android 12. Just stop telling other people they're "not dev enough" to do the same basic thing.

**Comment by MartinX3** [comment]
I don't know why you like to exaggerate in a social way, but it's not my intention to tell people "they're not dev enough".
Instead it was a reference to look at the git commit history of the xda developer if the thread author knows his work.
Please stay polite, especially in a public place. We're adults or at least we should try to act as adults.

**Comment by farukr1** [comment]
> You can run this just fine on OEMv7 for A11, anyone can, except @MartinX3.
> 
> On a device with a 4.14 kernel (anything but Edo and Lena), just be sure to set `OVERRIDE_PRODUCT_COMPRESSED_APEX := false`.

Thanks! It boots.
