### ISSUE TITLE
[4.19][AOSP11][pdx203/Edo] Kernel panics in ipa_pm_is_used

### ISSUE THREAD

**Issue by Thaodan** [sonyxperiadev/bug_tracker#728]
**Platform:**  Edo
**Device:**  Xperia 1 II/PDX203
**Kernel version:**  4.19
**Android version:**  11.0.0_r48
**Software binaries version:**  v7
**Stock Firmware before flashing AOSP:** Latest Android 11, 58.1.A.5.474-R25B

**Previously working on**
New

**Description**
When booting the device the kernel panics and spams the messages attached to the the bug
report.
After a time usually in about a minute the device looks up and doesn't respond anymore.

**Symptoms**
Device crashes

**How to reproduce**
Have a usb cable connected to a PC like a had.

**Additional context**
The kernel panic starts like this:
```
Nov 19 09:28:00 xqat51 kernel: ipa_pm_is_used not implemented for IPA ver 17
Nov 19 09:28:00 xqat51 kernel: WARNING: CPU: 7 PID: 5847 at drivers/platform/msm/ipa/ipa_api.c:3832 ipa_pm_is_used+0x4c/0x80
```
Reverting the commit 4f12cf39dfd37dc33de53c0f4b22fcb95c0fb805 helped, the device no longer panic but still looks up after a time.

[edo_dmesg_boot.log](https://github.com/sonyxperiadev/bug_tracker/files/7575000/edo_dmesg_boot.log)
[edo_kernel_panic_ipa_pm.log](https://github.com/sonyxperiadev/bug_tracker/files/7574998/edo_kernel_panic_ipa_pm.log)

**Comment by bartcubbins** [comment]
I probably have a fix for this, I'll open the PR as soon as possible

**Comment by Thaodan** [comment]
> I probably have a fix for this, I'll open the PR as 
soon as possible

Revert the kernel commit mentioned or is there 
suspend support in the firmware for this?
I compared the stock ipa module and it doesn't use 
ipa_pm_is_used.

**Comment by Thaodan** [comment]
Not sure if that's related but while testing I also noticed ramops messages in pstore regarding external modem requesting the kernel to panic.

**Comment by Thaodan** [comment]
> I probably have a fix for this, I'll open the PR as soon as possible
@bartcubbins how far are you on this?

**Comment by bartcubbins** [comment]
On it right now, sorry for delay

**Comment by bartcubbins** [comment]
https://github.com/sonyxperiadev/kernel/pull/2467

**Comment by Thaodan** [comment]
Looks better now thanks.
