### ISSUE TITLE
[LENA][11][4.19] SIM card is not detected in SIM2 slot

### ISSUE THREAD

**Issue by sledges** [sonyxperiadev/bug_tracker#729]
**Platform:** lena
**Device:** pdx213 xqbt52 (Xperia 10 III)
**Kernel version:** 4.19.188-gd1788aae5e4a-dirty (due to wlan-qc submodules)
**Android version:** AOSP11 android-11.0.0_r46
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.19_v7b_lena.img

**Previously working on** stock Sony Android 62.0.A.3.70 (also when reflashed via Emma to 62.0.A.3.109)

**Description**
Device does not detect SIM card in the 2nd SIM slot.

**Symptoms**
With two SIMs or just one in the 2nd slot, phone acts as if it was a single SIM device.
The SIM2 signal indicator is not shown in the UI status bar, and cannot make/receive calls/SMSs via SIM2, nor set it as preferred. SIM2 slot is "Not available" in Settings > About phone. IMEI is correct.

**How to reproduce**
Build and flash AOSP11 for lena, insert SIM card into slot 2.

**Additional context**
AOSP11 built on Thu Nov 25 23:20:03 UTC 2021:
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/7617608/dmesg.log)
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/7617609/logcat.log)
[getprop.log](https://github.com/sonyxperiadev/bug_tracker/files/7617687/getprop.log)
```
pdx213:/ $ getprop | grep -E "dsds|gsm"
[gsm.current.phone-type]: [1,1]
[gsm.network.type]: [LTE,Unknown]
[gsm.operator.alpha]: [Lebara,]
[gsm.operator.iso-country]: [gb,]
[gsm.operator.isroaming]: [false,false]
[gsm.operator.numeric]: [23415,]
[gsm.sim.operator.alpha]: [Lebara]
[gsm.sim.operator.iso-country]: [gb]
[gsm.sim.operator.numeric]: [23415]
[gsm.sim.state]: [LOADED,ABSENT]
[gsm.version.baseband]: [bitra.gen-00411-07,bitra.gen-00411-07]
[gsm.version.ril-impl]: [Qualcomm RIL 1.0]
[persist.radio.multisim.config]: [dsds]
[persist.vendor.radio.multisim.config]: [dsds]
```

<details>
 <summary>getprop of when SIM2 is detected fine on stock Android 62.0.A.3.109 (flashed via Emma)</summary>

```
[gsm.current.phone-type]: [1,1]
[gsm.network.type]: [LTE,LTE]
[gsm.operator.alpha]: [Lebara,O2 - UK]
[gsm.operator.iso-country]: [gb,gb]
[gsm.operator.isroaming]: [false,false]
[gsm.operator.numeric]: [23415,23410]
[gsm.sim.operator.alpha]: [Lebara,O2]
[gsm.sim.operator.iso-country]: [gb,gb]
[gsm.sim.operator.numeric]: [23415,23410]
[gsm.sim.state]: [LOADED,LOADED]
[gsm.version.baseband]: [bitra.gen-00411-07,bitra.gen-00411-07]
[gsm.version.ril-impl]: [Qualcomm RIL 1.0]
[persist.radio.multisim.config]: [dsds]
```
</details>

Same bug spotted on another device in Finland.

**Comment by jerpelea** [comment]
the bugs seems to be caused by incorrect sim detection

**Comment by Thaodan** [comment]
Works fine for me now.

**Comment by sledges** [comment]
Fixed in https://github.com/sonyxperiadev/kernel/pull/2465
