### ISSUE TITLE
[LENA][11][4.19] SIM1 does not work during 1st boot after flashing

### ISSUE THREAD

**Issue by sledges** [sonyxperiadev/bug_tracker#730]
**Platform:** lena
**Device:** pdx213 xqbt52 (Xperia 10 III)
**Kernel version:** 4.19.188-gd1788aae5e4a-dirty (due to wlan-qc submodules)
**Android version:** AOSP11 android-11.0.0_r46
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.19_v7b_lena.img

**Previously working on** unknown

**Description**
When device boots for the first time after freshly flashed AOSP (or wiped userdata), telephony functions are not available. Only rebooting device or restarting `vendor.qcrild` helps. It works fine on every subsequent bootup.

**Symptoms**
SIM signal strength is not shown in the status bar, phone calls/SMS/mobile data are not working.

**How to reproduce**
Build and flash AOSP11 for lena (or reflash just with empty userdata.img and clear metadata), insert SIM card into slot 1, boot device.

**Additional context**
AOSP11 built on Thu Nov 25 23:20:03 UTC 2021:
Both qcrild are running.
stop vendor.qcrild # at 11-26 00:13:18.010 in logcat
start vendor.qcrild # at 11-26 00:13:30.651 in logcat
SIM1 indicator appears and it starts to work.
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/7627677/dmesg.log)
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/7627678/logcat.log)

**Comment by jerpelea** [comment]
I am investigating the kernel since the sim status does not seem to be propagated

**Comment by sledges** [comment]
This works now during first boot with the latest AOSP build, although it might have some affinity with https://github.com/sonyxperiadev/bug_tracker/issues/736
