### ISSUE TITLE
[LENA+EDO][11][4.19] sometimes both SIM cards are not detected (race condition?)

### ISSUE THREAD

**Issue by sledges** [sonyxperiadev/bug_tracker#736]
**Platform:** lena
**Device:** pdx213 xqbt52 (Xperia 10 III)
**Kernel version:** 4.19.188-g12b66f7f9222-dirty (due to qca submodules)
**Android version:** AOSP11 android-11.0.0_r46
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.19_v8a_lena.img

**Previously working on** stock Sony Android 62.0.A.3.70 (also when reflashed via Emma to 62.0.A.3.109).
It would always fail on AOSP in my tests, even when only the 1st SIM card slot was working earlier this month.

**Description**
Sometimes no SIM cards are detected when device is booted. After reboot or two, both SIM cards are visible again.
Alternatively, one can bring them back to life by executing
```
stop vendor.qcrild2
stop vendor.qcrild
start vendor.qcrild
start vendor.qcrild2
```

**Symptoms**
 SIM1 and SIM2 signal strength icons are not shown in the status bar.

**How to reproduce**

1. Reboot the device
1. Check if SIMs icons are visible
1. If they are working fine, go to step 1 (takes about 3 reboots on average)

**Additional context**

AOSP11 rebuilt on 21st December 2021:
logcat when SIMs are detected successfully:
[logcat-sims.log](https://github.com/sonyxperiadev/bug_tracker/files/7767400/logcat-sims.log)

logcat when no SIMs detected:
[logcat-nosims.log](https://github.com/sonyxperiadev/bug_tracker/files/7767412/logcat-nosims.log)

**Comment by Thaodan** [comment]
I noriced similar issues on Edo/Xperia 1 II. In 4 boots only in one my SIM card was recognized.

**Comment by Aarqw12** [comment]
> 
I get same issue as you because this commit ac5c1c9221de44d990d80821a809a989e77f6019 as I have only 1SIM I have reverted locally for now

**Comment by Thaodan** [comment]
> > 
> 
> I get same issue as you because this commit in kernel misc: sony_ext_uim_ctrl: Add quirks for SoMC Lena ac5c1c9221de44d990d80821a809a989e77f6019, as I have only 1SIM I have reverted locally for now

On Lena I assume?

**Comment by sledges** [comment]
> > 
> 
> I get same issue as you because this commit in kernel misc: sony_ext_uim_ctrl: Add quirks for SoMC Lena ac5c1c9221de44d990d80821a809a989e77f6019, as I have only 1SIM I have reverted locally for now

The issue existed before that commit, sometimes it takes more reboots to reach the same state of no SIM card detected. (I tried with ac5c1c92 reverted for better measure on the latest BSP -- managed to recreate the problem after couple of reboots.)

Preventing qcrild* services from starting and starting them manually later in the boot seems to work reliably, however that's not the way to fix things.

**Comment by sledges** [comment]
After looking at how original stock Android works, we couldn't find any differing wait states that would make qcrild start after underlying modem has been fully initialised. No significant differences were found between the two kernels either when glancing over the code.
So is still a mystery, why this doesn't always work on AOSP, but works fine on stock.

In Sailfish OS we are going with a sad [workaround](https://github.com/mer-hybris/droid-src-sony/pull/12) for now, just adding `sleep 3` before starting `qcrild`, which has been chosen empirically.
We can also patch this upstream to Sony AOSP if desired and proper solution is not yet in sight.

**Comment by MarijnS95** [comment]
We carry less "stuff" so perhaps `class main` just starts/finishes quicker?

Perhaps it is one of the `boot` scripts that need to kick things earlier? I don't even remember if modem(-related) procs are kicked from there, but worth a look.

**Comment by Thaodan** [comment]
> Perhaps it is one of the `boot` scripts that need to kick things earlier? I
> don't even remember if modem(-related) procs are kicked from there, but
> worth a look
Which scripts?

**Comment by MarijnS95** [comment]
`init.qcom.XXXstart.sh`.

Maybe only IPA comes close enough to messing up modem start?

Disclaimer: I have no idea how this fragile system is knotted together on the modem/SIM/networking side.

**Comment by Thaodan** [comment]
> `init.qcom.XXXstart.sh`.
> 
> Maybe only IPA comes close enough to messing up modem start?
Being up to fast or to late?

> Disclaimer: I have no idea how this fragile system is knotted together on
> the modem/SIM/networking side.
How has more experience here?

**Comment by voidanix** [comment]
FYI this also happens on kumano (bahamut, AOSP 11); last time it worked was with v5b binaries IIRC.

So far multiple reboots are required until the SIM lock pin entry appears :P

**Comment by Thaodan** [comment]
Can be closed now,
