### ISSUE TITLE
H8296 Android 10 firmware unavailable in Emma

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/bug_tracker#737]
**Platform:** tama
**Device:** akari (H8296 variant)
**Kernel version:**  n/a
**Android version:**  10
**Software binaries version:** n/a

**Previously working on**
n/a

**Description**
In Emma, the latest firmware for the H8296 (XZ2) I am able to access is 52.0.A.3.126, which is an Android 9 image.  Could you please make a more current image available?  Image 52.1.A.3.49 appears to be available in some regions -- it is an Android 10 build.  I am in Canada.

**Symptoms**
See screen-shot below.

**How to reproduce**
Open Emma and connect an XZ2 device (H8296) and search for firmware (note that the search results may depend upon your geographic region).

**Additional context**
Making an Android 10 image available is important as it apparently addresses the problem of a bootloader unlock breaking the stock camera, which was present in the Android 8 and 9 firmware.

![DSC_1285](https://user-images.githubusercontent.com/5332385/147512735-ead5cac0-f7f1-410f-a0c5-20d18a8c96fa.JPG)

**Comment by jerpelea** [comment]
@jamuir the SW is released 
Thanks for reporting it

**Comment by jamuir** [comment]
Thanks, Alin.

I can confirm that the Android 10 image (52.1.A.3.49) is indeed accessible in Emma now (see screen-shot below).

![DSC_1288](https://user-images.githubusercontent.com/5332385/147599024-1fa502e1-8171-481a-bdf9-ef35ab12b485.JPG)
