### ISSUE TITLE
[Seine][10][4.14] sec_ts_read_event: event buffer  is empty in kernel ring buffer when touching screen 

### ISSUE THREAD

**Issue by Thaodan** [sonyxperiadev/bug_tracker#738]
**Platform:**  Seine 
**Device:** PDX201
**Kernel version:**  4.14.254 
**Android version:**  10
**Software binaries version:**  SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12b_seine

**Previously working on**
I'm not sure.

**Description**
Whenever the touchscreen is used there are very big spam of ` [sec_input] sec_ts_read_event: event buffer is empty` in dmesg, 
like 5 messages per touch. 

**Symptoms**
None except those messages as described above.

**How to reproduce**
Touch the screen.

**Additional context**
Full dmesg log:
[dmesg.seine.sec_ts_event_buffer_spam.log](https://github.com/sonyxperiadev/bug_tracker/files/7814174/dmesg.seine.sec_ts_event_buffer_spam.log)

**Comment by MarijnS95** [comment]
:eyes: PDX203 (and PDX206) is Edo, PDX201 is Seine.

**Comment by Thaodan** [comment]
Fixed.

**Comment by Thaodan** [comment]
Can we do something about this or we just close this?

**Comment by jerpelea** [comment]
please leave it open for now

**Comment by Thaodan** [comment]
What should be done about this?

**Comment by jerpelea** [comment]
we can investigate and patch the root cause

**Comment by Thaodan** [comment]
@jerpelea or@bartcubbins  Any ideas what should be done about this?

**Comment by jerpelea** [comment]
did you manage to find the root cause?

**Comment by MarijnS95** [comment]
> What should be done about this?

Use a driver that isn't a big hack filled with debug code? Such as `samsung,s6sy761` from upstream Linux.

**Comment by Thaodan** [comment]
> did you manage to find the root cause?

Not so far.

**Comment by Thaodan** [comment]
Does it make sense to fix? We could just remove the message if it is not impacting any functionality.

**Comment by jerpelea** [comment]
please remove the message
