### ISSUE TITLE
[4.4] Bug in QPNP WLED driver of 4.4 kernel download

### ISSUE THREAD

**Issue by Flamefire** [sonyxperiadev/bug_tracker#739]
**Platform:** yoshino
**Device:**  lilac
**Kernel version:** 4.4
**Android version:** 10
**Software binaries version:** 47.2.A.10.107

**Description**
The download archive at https://developer.sony.com/file/download/open-source-archive-for-47-2-a-10-107/ contains the 4.4 kernel stuff including drivers/leds/leds-qpnp-wled.c which has a bug likely caused by a merge conflict.

Relevant code starting at line 2326 with original (buggy) indentation:
```
		rc = qpnp_wled_masked_write_reg(wled,
			QPNP_WLED_FS_CURR_REG(wled->sink_base, i),
			mask, reg);
			if (rc < 0)
				return rc;
			if (wled->calc_curr)
				temp = (wled->fs_curr_ua + (QPNP_WLED_FS_CURR_STEP_UA - 1)) /
					QPNP_WLED_FS_CURR_STEP_UA;
			else

			/* CABC */
		reg = wled->en_cabc ? (1  << QPNP_WLED_CABC_SHIFT) : 0;
		mask = QPNP_WLED_CABC_MASK;
		rc = qpnp_wled_masked_write_reg(wled,
			QPNP_WLED_CABC_REG(wled->sink_base, i),
			mask, reg);
			if (rc < 0)
				return rc;
```

**Additional context**
As you can see the code starting at `if(rc < 0)` is wrongly indented hinting already at an issue.

The actual bug then: The variable `temp` is set but never used and only the `else` branch sets the `reg` variable used for the `CABC` register write to a valid value.

I don't know enough about the specifics of the CABC stuff and what exactly is missing there (I guess a write to another register) to know the implications here in how the bug manifests, but writing an invalid value to a register is certainly not good.

**Comment by Thaodan** [comment]
Please fix the bug title and the description.

**Comment by Flamefire** [comment]
@Thaodan I don't understand what you mean. What is there to fix exactly? I enhanced the title a bit.

I can also provide a patch which I'm sure fixes the bug reported here: 
[kernel.patch.txt](https://github.com/sonyxperiadev/bug_tracker/files/7837860/kernel.patch.txt)

**Comment by Thaodan** [comment]
> @Thaodan I don't understand what you mean. What is there to fix exactly? I enhanced the title a bit.

The bug title should be similar to other bugs by reporting the actual platforms affecting etc.

> I can also provide a patch which I'm sure fixes the bug reported here: [kernel.patch.txt](https://github.com/sonyxperiadev/bug_tracker/files/7837860/kernel.patch.txt)

Create a PR for that please.

**Comment by Flamefire** [comment]
This is basically a bug report against the download provided at https://developer.sony.com/file/download/open-source-archive-for-47-2-a-10-107/
I'm not fully sure which platforms are affected and where to create a PR for that. If you have that information, can you suggest a better title/description and provide a link to the repo where the PR should be filed?
I basically just wanted to document my findings so others may chime in with additional information or use this to actually fix things (at the time of writing I didn't had the patch yet)

**Comment by MarijnS95** [comment]
Note that this is a copyleft archive from August 9, **_2019_**.

**Comment by jerpelea** [comment]
Discontinued Android version
