### ISSUE TITLE
[loire] no incall audio nor mic from bt headset

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#74]
**Platform:** loire
**Device:** kugo, suzu
**Kernel version:** 5.7, 6.4
**Android version:** 7.1,8.0, 8.1

**Description**
When taking or making call, and a bt headset is connected, the bt headset has no incall audio, or is completely muted.the other side also doesn't hear anything. 

**Symptoms**
No audio from bt headset while incall, or sound is muted
Mic is muted,as the other side doesn't hear anything 

**How to reproduce**
1. Connect bt headset to device
2. Start a phone call

**Comment by richardtullberg** [comment]
Hi, I havent been able to reproduce the issue for some reason but can you tell me if in the log you get any errors when you make the call such as "cant load effects ns or aec"?

Maybe you can grep on ns or aec. I am uploading a fix for this and hopefully it will help you.

**Comment by oshmoun** [comment]
Thanks for looking into this!
I have to say though, it's weird that you couldn't reproduce the issue. It has been confirmed by at least two other people (@jerpelea and @humberos). 
Will test the fixes asap!

**Comment by richardtullberg** [comment]
@oshmoun  sorry, I had been testing on the wrong device, confusion with another issue I was working on. I am building your specific product now to test it out.

**Comment by oshmoun** [comment]
Ah that explains it. Tested the pr anyway, and the issue persisted.

**Comment by richardtullberg** [comment]
@oshmoun was wondering if you have any audio at all while playing a mp3 through the internal speakers? Do you have any audio while playing the mp3 through your BT device?

**Comment by oshmoun** [comment]
You're right! Seems mp3 playback from internal speakers is busted in a way.
Playing the same mp3 files over bt seems to work though

**Comment by oshmoun** [comment]
@richardtullberg fixed mp3 playback, there was a dt node missing
had to hack the driver responsible a bit too just to get a booting device
here's a patch you could apply:
https://hastebin.com/anuhaleruv.cpp
Will need to find out why msm_compr_add_app_type_cfg_control is crashing the device, as this function is unchanged from 5.7

Note that this doesn't solve the BT issue.

**Comment by oshmoun** [comment]
Updated issue description with the observation that bt mic is also broken, and not necessarily incall. Audio recording apps also don't work when a bt headset is connected.
@richardtullberg is it reasonable to expect a relation between the two issues?

**Comment by jerpelea** [comment]
tested 
Android 7.1 kernel 4.4_5.7_r1
Android 8.1 kernel 4.4_6.4_r1

tha bug is confirmed and the issue appears to be in the kernel

**Comment by oshmoun** [comment]
Fixed with https://github.com/sonyxperiadev/kernel/pull/1580
