### ISSUE TITLE
[LENA][11][4.19] bootctl cannot mark boot as successful (need to reflash boot every 7 reboots)

### ISSUE THREAD

**Issue by sledges** [sonyxperiadev/bug_tracker#740]
**Platform:** lena
**Device:** pdx213 xqbt52 (Xperia 10 III)
**Kernel version:** 4.19.188-g12b66f7f9222-dirty (due to qca submodules)
**Android version:** AOSP11 android-11.0.0_r46
**Software binaries version:** SW_binaries_for_Xperia_Android_11_4.19_v8a_lena.img

**Previously working on** stock Sony Android 62.0.A.3.70 (also when reflashed via Emma to 62.0.A.3.109).

**Description**
Cannot mark boot as successful. After 7 reboot the slot counter goes to 7 and device is in bootloop until boot partition is reflashed.

**Symptoms**
Device goes into bootloop after 7 boots, with bootloader showing "Your device is corrupt. It can't be trusted and will not boot. Your device will be powered off in 5 seconds."

**How to reproduce**

1. Reboot device 7 times

**Additional context**

Flashed as per working [instructions](https://github.com/sonyxperiadev/bug_tracker/issues/716#issuecomment-917872297), also tried [explicitly disabling vbmeta](https://wiki.postmarketos.org/wiki/Android_Verified_Boot_(AVB)#Disabling_verified_boot) and vbmeta_system.

Older devices (XA2 Android 8, Xperia 10 Android 9, Xperia 10 II Android 10) are able to mark boot as successful via `bootctl` command. But in lena (Xperia 10 III Android 11) executing it does not change the fastboot variables (no output in logcat during bootctl launch):
```
# `make bootctl` and deploy it to your device
pdx213:/ # bootctl get-current-slot
0
pdx213:/ # bootctl mark-boot-successful
pdx213:/ # reboot

fastboot getvar all 2>&1 | grep slot-successful:a
(bootloader) slot-successful:a:no
```

It strangely keeps a copy of variables somewhere else and doesn't sync them to bootloader's vars, see:
```
fastboot getvar all 2>&1 | grep slot-unbootable:b
(bootloader) slot-unbootable:b:no
fastboot reboot

pdx213:/ # bootctl is-slot-bootable 1 && echo yes
yes
pdx213:/ # bootctl set-slot-as-unbootable 1
pdx213:/ # bootctl is-slot-bootable 1 && echo yes
70|pdx213:/ reboot

fastboot getvar all 2>&1 | grep slot-unbootable:b
(bootloader) slot-unbootable:b:no
fastboot reboot

pdx213:/ # bootctl is-slot-bootable 1 && echo yes
70|pdx213:/ #
```
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/7870005/logcat.log)

**Comment by sledges** [comment]
This is because lena's bootloader is expecting userspace to follow android.hardware.boot@1.0 (storing bootable flags in GPT boot partition entries), yet Android 11 is on the next version android.hardware.boot@1.1 (using misc partition to store them).

**Comment by MarijnS95** [comment]
That's a nice breaking change for a non-breaking HIDL **_API_** bump. Are you sure this isn't the HAL itself that changed?

**Comment by sledges** [comment]
According to [this](https://static.linaro.org/connect/san19/presentations/san19-217.pdf), already Android 10 moved to misc partition.

1.1 API extends 1.0 with just the two new functions: `set-snapshot-merge-status` and `get-snapshot-merge-status`

Old GPT implementation is [here](https://android.googlesource.com/platform/hardware/interfaces/+/refs/tags/android-11.0.0_r46/boot/1.0/default/BootControl.cpp). New misc partition impl is [here](https://android.googlesource.com/platform/hardware/interfaces/+/refs/tags/android-11.0.0_r46/boot/1.1/default/boot_control/libboot_control.cpp).

I hope AOSP has some graceful way to use legacy 1.0 and discard 1.1, as they seem to have some [files](https://android.googlesource.com/platform/hardware/interfaces/+/refs/tags/android-11.0.0_r46/boot/1.1/default/boot_control/legacy_boot_control.cpp) for that.

fastboot bootloader itself is at mercy of its availability through Emma or stock updates, so that probably is a no for Lena (i.e. it will stay on 1.0 from that PoV).

**Comment by MarijnS95** [comment]
> Old GPT implementation is [here](https://android.googlesource.com/platform/hardware/interfaces/+/refs/tags/android-11.0.0_r46/boot/1.0/default/BootControl.cpp). New misc partition impl is [here](https://android.googlesource.com/platform/hardware/interfaces/+/refs/tags/android-11.0.0_r46/boot/1.1/default/boot_control/libboot_control.cpp).

Correct. The implementation is up to the vendors and us randomly selecting whatever latest default AOSP has available is pretty much wrong.

> I hope AOSP has some graceful way to use legacy 1.0 and discard 1.1, as they seem to have some [files](https://android.googlesource.com/platform/hardware/interfaces/+/refs/tags/android-11.0.0_r46/boot/1.1/default/boot_control/legacy_boot_control.cpp) for that.

That's really pretty ugly, and it seems it is only to use the newer `libboot_control` library/HIDL thingy from a libhardware module, which is subsequently loaded by the `1.0` `BootControl.cpp` HAL-`impl`. Follow `HAL_MODULE_INFO_SYM` inside `#ifdef BOOT_CONTROL_RECOVERY` there.

**Comment by sledges** [comment]
> I hope AOSP has some graceful way to use legacy 1.0 and discard 1.1

Found it :) by reverting https://github.com/sonyxperiadev/device-sony-common/commit/1a91f1b6adb3762aea19e2838a1c01141cf5d5ed

**Comment by jerpelea** [comment]
-    android.hardware.boot@1.0-impl \
-    android.hardware.boot@1.0-impl.recovery \
-    android.hardware.boot@1.0-service
+    android.hardware.boot@1.1-impl \
+    android.hardware.boot@1.1-impl.recovery \
+    android.hardware.boot@1.1-service

**Comment by MarijnS95** [comment]
> Old GPT implementation is [here](https://android.googlesource.com/platform/hardware/interfaces/+/refs/tags/android-11.0.0_r46/boot/1.0/default/BootControl.cpp). New misc partition impl is [here](https://android.googlesource.com/platform/hardware/interfaces/+/refs/tags/android-11.0.0_r46/boot/1.1/default/boot_control/libboot_control.cpp).

Fwiw that's not the "old" implementation but the passthrough loader for a libhardware module. Its implementation is in https://github.com/sonyxperiadev/hardware-qcom-bootctrl/blob/master/boot_control.cpp and referenced from SODP platforms' `bootctrl/Android.bp` file.

> > I hope AOSP has some graceful way to use legacy 1.0 and discard 1.1
> 
> Found it :) by reverting [sonyxperiadev/device-sony-common@1a91f1b](https://github.com/sonyxperiadev/device-sony-common/commit/1a91f1b6adb3762aea19e2838a1c01141cf5d5ed)

That was obvious wasn't it? It's nothing graceful though, and will stop our FCM5 migration right in its tracks. We need to find a solution that loads the libardware module for a 1.1 interface, optionally storing snapshot state on the `misc` partition or returning some error that represents it not being implemented (if AOSP can deal with that gracefully).

In any case, this explains why `bootctl` suddenly started working on some devices, if I remember correctly. We should really validate which of the platforms use which, then make a more informed decision whether to:

- Support the libhardware module on 1.1;
- Find more recent source on CAF that does this already (though it seems the most recent state of things is now provided by AOSP as a default already);
- Back out of 1.1 for a select few platforms.

**Comment by jerpelea** [comment]
bootctrl is use by all devices that have AB partitions and the new implementation should be used on edo, lena, sagami ...

**Comment by MarijnS95** [comment]
> should be used on edo, lena, sagami ...

I'd think so too given the launch requirements, yet this issue is about Lena specifically needing the older GPT version :thinking:

**Comment by jerpelea** [comment]
if lena works fine with the old one (GPT) we should just select it for lena

**Comment by sledges** [comment]
Here's hoping there won't be lena's out there that have stock or Emma-flashed versions that moved to 1.1:)
https://github.com/sonyxperiadev/device-sony-common/pull/879

**Comment by MarijnS95** [comment]
> Here's hoping there won't be lena's out there that have stock or Emma-flashed versions that moved to 1.1:)
> https://github.com/sonyxperiadev/device-sony-common/pull/879

Called it, now it's definitely going to happen!

Thanks for the PR! We'll have to validate the other platforms, and don't forget to document your findings there in the commit and a comment (the specific fact that the _**default**_ 1.1 HAL suddenly uses a different implementation instead of calling into our bootctrl HAL).

We should also remove this now-unused bootctrl libhardware module from the respective platforms **after validating our findings**.

**Comment by Thaodan** [comment]
> Older devices (XA2 Android 8, Xperia 10 Android 9, Xperia 10 II Android 10) are able to mark boot as successful via `bootctl` command. But in lena (Xperia 10 III Android 11) executing it does not change the fastboot variables (no output in logcat during bootctl launch):
> 
> ```
> # `make bootctl` and deploy it to your device
> pdx213:/ # bootctl get-current-slot
> 0
> pdx213:/ # bootctl mark-boot-successful
> pdx213:/ # reboot
> 
> fastboot getvar all 2>&1 | grep slot-successful:a
> (bootloader) slot-successful:a:no
> ```

I tried the same instructions on Edo, Xqat51/pdx203 same results.

**Comment by MarijnS95** [comment]
Findings on Sagami:

- Stock uses a contraption that touches both GPT and `/misc` (stop calling this boot v1.0 vs v1.1, please. That's just an implementation detail of AOSPs default HAL);
- `slot-retry-count` counts down instead of up (I thought that was the case on all devices?);
- Value of `slot-unbootable` differs between `fastboot` and `fastbootd`;
  - `fastboot` `slot-unbootable` will only be marked `yes` as soon as the retry counter reaches 0;
  - `fastbootd` `slot-unbootable`/`slot-successful` seems to match `bootctl is-slot-bootable`/`bootctl set-slot-as-unbootable`;
  - `fastbootd` has no `slot-retry-count`.

Note that the stock library is called `libboot_control_qti.so` (and the impl is obviously post-fixed `-qti`), so we'll probably have to pull in whatever custom they have from CAF.

Can anyone do the same check for Lena, Edo, etc stock, and/or check CAF? I think we _just_ need to use a newer CAF branch/tag that provides the right `android.hardware.boot@1.0-impl-1.1-qti.so`/`libboot_control_qti.so`, while still staying on track for the 1.1/FCM5 HAL migration. I'm willing to take this up and test on Sagaimi+Edo+Lena+Seine+Kumano etc.

**Comment by MarijnS95** [comment]
1.1 implementation for Sagami: https://source.codeaurora.org/quic/la/platform/hardware/qcom/bootctrl/tree/1.1?h=LA.UM.9.14.r1-18900-LAHAINA.0
And the 9.12 branch for all the other 4.19-based devices: https://source.codeaurora.org/quic/la/platform/hardware/qcom/bootctrl/tree/1.1?h=LA.UM.9.12.r1-13700-SMxx50.QSSI12.0

**Comment by jerpelea** [comment]
@sledges https://github.com/sonyxperiadev/vendor-qcom-opensource-bootctrl

**Comment by MarijnS95** [comment]
Thanks for forking already @jerpelea! I just prepared all the necessary commits, and my Sagami now appropriately, instantly shows "device is corrupt and cannot/will not boot" when running `bootctl set-slot-as-unbootable`. Likewise, rebooting to bootloader-fastboot gives me a happy:

```
(bootloader) slot-retry-count:a:6
(bootloader) slot-unbootable:a:no
(bootloader) slot-successful:a:yes
```
now.

Expect PRs soon :tada:. @Thaodan @sledges Can I count on you to test this on Edo and Lena? I'm running short on time :sweat_smile:

**Comment by Thaodan** [comment]
> Thanks for forking already @jerpelea! I just prepared all the necessary commits, and my Sagami now appropriately, instantly shows "device is corrupt and cannot/will not boot" when running `bootctl set-slot-as-unbootable`. Likewise, rebooting to bootloader-fastboot gives me a happy:
> 
> ```
> (bootloader) slot-retry-count:a:6
> (bootloader) slot-unbootable:a:no
> (bootloader) slot-successful:a:yes
> ```
> 
> now.
> 
> Expect PRs soon tada. @Thaodan @sledges Can I count on you to test this on Edo and Lena? I'm running short on time sweat_smile

Tests fine on Edo.

**Comment by jerpelea** [comment]
fixed
