### ISSUE TITLE
Bluetooth not working in AOSP12

### ISSUE THREAD

**Issue by yehonatan2020** [sonyxperiadev/bug_tracker#741]
AOSP/SODP
Seine, Kirin, Mermaid, Griffin
Kernel 4.14
Android 12
OEM binaries 11

NO BLUETOOTH FUNCTIONALITY
bluetooth self-closes when trying to switch it on. 

**How to reproduce**
try switching on bluetooth, closing the menu, and then re opening

**Comment by ShujathMohd** [comment]
It was fixed with https://github.com/sonyxperiadev/kernel-defconfig/commit/3a6faa27720a108283ea590f7860835b3da62a07
