### ISSUE TITLE
build error - OTA package

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#744]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.19
**Android version:** 12
**Software binaries version:** SW_binaries_for_Xperia_Android_12_4.19_v1c_tama

**Previously working on**
Android 11
Kernel 4.14

**Description**
While creating the OTA package, an error occurs.
`make -j` works.

**Symptoms**
The creation of the OTA package fails.

**How to reproduce**
`make -j dist`

**Additional context**
```
[ 46% 6/13] build out/target/product/akari/host_init_verifier_output.txt
FAILED: out/target/product/akari/host_init_verifier_output.txt
/bin/bash -c "out/host/linux-x86/bin/host_init_verifier 		-p out/target/product/akari/obj/ETC/passwd_system_intermediates/passwd_system 		-p out/target/product/akari/obj/ETC/passwd_system_e
xt_intermediates/passwd_system_ext 		-p out/target/product/akari/obj/ETC/passwd_vendor_intermediates/passwd_vendor 		-p out/target/product/akari/obj/ETC/passwd_odm_intermediates/passwd_odm 	-
p out/target/product/akari/obj/ETC/passwd_product_intermediates/passwd_product 		--property-contexts=out/target/product/akari/obj/ETC/plat_property_contexts_intermediates/plat_property_contexts 		-
-property-contexts=out/target/product/akari/obj/ETC/system_ext_property_contexts_intermediates/system_ext_property_contexts 		--property-contexts=out/target/product/akari/obj/ETC/product_property_conte
xts_intermediates/product_property_contexts 		--property-contexts=out/target/product/akari/obj/ETC/vendor_property_contexts_intermediates/vendor_property_contexts 		--property-contexts=out/tar
get/product/akari/obj/ETC/odm_property_contexts_intermediates/odm_property_contexts 		--out_system out/target/product/akari/system 		--out_system_ext out/target/product/akari/system/system_ext
 		--out_vendor out/target/product/akari/vendor 		--out_odm out/target/product/akari/vendor/odm 		--out_product out/target/product/akari/system/product 		> out/target/produc
t/akari/host_init_verifier_output.txt"
host_init_verifier: out/target/product/akari/vendor/etc/init/vendor.somc.hardware.modemswitcher@1.0-service.rc: 2: 
Interface is not in the known set of hidl_interfaces: 'vendor.somc.hardware.modemswitcher@1.0::IModemSwitcher'. Please ensure the interface is spelled correctly and built by a hidl_interface target.
host_init_verifier: Failed to parse init scripts with 1 error(s).
[ 53% 7/13] Package: out/target/product/akari/aosp_h8216-img-eng.martin.zip
2022-02-09 02:21:14 - common.py - WARNING : Failed to read SYSTEM/etc/build.prop
2022-02-09 02:21:15 - common.py - WARNING : Failed to read VENDOR/etc/build.prop
2022-02-09 02:21:15 - common.py - WARNING : Failed to read PRODUCT/etc/build.prop
2022-02-09 02:21:15 - common.py - WARNING : Failed to read PRODUCT/build.prop
2022-02-09 02:21:15 - common.py - WARNING : Failed to read SYSTEM_EXT/etc/build.prop
2022-02-09 02:21:15 - common.py - WARNING : Failed to read SYSTEM_EXT/build.prop
2022-02-09 02:21:15 - common.py - WARNING : Failed to read ODM/etc/build.prop
2022-02-09 02:21:15 - common.py - WARNING : Failed to read ODM/build.prop
2022-02-09 02:21:15 - common.py - WARNING : Failed to read VENDOR_DLKM/etc/build.prop
2022-02-09 02:21:15 - common.py - WARNING : Failed to read VENDOR_DLKM/build.prop
2022-02-09 02:21:15 - common.py - WARNING : Failed to read ODM_DLKM/etc/build.prop
2022-02-09 02:21:15 - common.py - WARNING : Failed to read ODM_DLKM/build.prop
```

**Comment by Pavanpadamata** [comment]
> **Platform:** tama **Device:** akari **Kernel version:** 4.19 **Android version:** 12 **Software binaries version:** SW_binaries_for_Xperia_Android_12_4.19_v1c_tama
> 
> **Previously working on** Android 11 Kernel 4.14
> 
> **Description** While creating the OTA package, an error occurs. `make -j` works.
> 
> **Symptoms** The creation of the OTA package fails.
> 
> **How to reproduce** `make -j dist`
> 
> **Additional context**
> 
> ```
> [ 46% 6/13] build out/target/product/akari/host_init_verifier_output.txt
> FAILED: out/target/product/akari/host_init_verifier_output.txt
> /bin/bash -c "out/host/linux-x86/bin/host_init_verifier 		-p out/target/product/akari/obj/ETC/passwd_system_intermediates/passwd_system 		-p out/target/product/akari/obj/ETC/passwd_system_e
> xt_intermediates/passwd_system_ext 		-p out/target/product/akari/obj/ETC/passwd_vendor_intermediates/passwd_vendor 		-p out/target/product/akari/obj/ETC/passwd_odm_intermediates/passwd_odm 	-
> p out/target/product/akari/obj/ETC/passwd_product_intermediates/passwd_product 		--property-contexts=out/target/product/akari/obj/ETC/plat_property_contexts_intermediates/plat_property_contexts 		-
> -property-contexts=out/target/product/akari/obj/ETC/system_ext_property_contexts_intermediates/system_ext_property_contexts 		--property-contexts=out/target/product/akari/obj/ETC/product_property_conte
> xts_intermediates/product_property_contexts 		--property-contexts=out/target/product/akari/obj/ETC/vendor_property_contexts_intermediates/vendor_property_contexts 		--property-contexts=out/tar
> get/product/akari/obj/ETC/odm_property_contexts_intermediates/odm_property_contexts 		--out_system out/target/product/akari/system 		--out_system_ext out/target/product/akari/system/system_ext
>  		--out_vendor out/target/product/akari/vendor 		--out_odm out/target/product/akari/vendor/odm 		--out_product out/target/product/akari/system/product 		> out/target/produc
> t/akari/host_init_verifier_output.txt"
> host_init_verifier: out/target/product/akari/vendor/etc/init/vendor.somc.hardware.modemswitcher@1.0-service.rc: 2: 
> Interface is not in the known set of hidl_interfaces: 'vendor.somc.hardware.modemswitcher@1.0::IModemSwitcher'. Please ensure the interface is spelled correctly and built by a hidl_interface target.
> host_init_verifier: Failed to parse init scripts with 1 error(s).
> [ 53% 7/13] Package: out/target/product/akari/aosp_h8216-img-eng.martin.zip
> 2022-02-09 02:21:14 - common.py - WARNING : Failed to read SYSTEM/etc/build.prop
> 2022-02-09 02:21:15 - common.py - WARNING : Failed to read VENDOR/etc/build.prop
> 2022-02-09 02:21:15 - common.py - WARNING : Failed to read PRODUCT/etc/build.prop
> 2022-02-09 02:21:15 - common.py - WARNING : Failed to read PRODUCT/build.prop
> 2022-02-09 02:21:15 - common.py - WARNING : Failed to read SYSTEM_EXT/etc/build.prop
> 2022-02-09 02:21:15 - common.py - WARNING : Failed to read SYSTEM_EXT/build.prop
> 2022-02-09 02:21:15 - common.py - WARNING : Failed to read ODM/etc/build.prop
> 2022-02-09 02:21:15 - common.py - WARNING : Failed to read ODM/build.prop
> 2022-02-09 02:21:15 - common.py - WARNING : Failed to read VENDOR_DLKM/etc/build.prop
> 2022-02-09 02:21:15 - common.py - WARNING : Failed to read VENDOR_DLKM/build.prop
> 2022-02-09 02:21:15 - common.py - WARNING : Failed to read ODM_DLKM/etc/build.prop
> 2022-02-09 02:21:15 - common.py - WARNING : Failed to read ODM_DLKM/build.prop
>

**Comment by Pavanpadamata** [comment]
found fix?

**Comment by MartinX3** [comment]
> found fix?

No

**Comment by Pavanpadamata** [comment]
> > found fix?
> 
> No

Me too facing same error

**Comment by MartinX3** [comment]
> > > found fix?
> > 
> > 
> > No
> 
> Me too facing same error pls lmk if found fix or

We all face it :D

**Comment by gaganmalvi** [comment]
Easy. 

Add this to your Android.bp:

```
prebuilt_hidl_interfaces {
    name: "hidl_modemswitcher_interface",
    interfaces: [
        "vendor.somc.hardware.modemswitcher@1.0::IModemSwitcher",
    ],
}
```

**Comment by jerpelea** [comment]
@gaganmalvi please PR the fix so that we can review it

**Comment by gaganmalvi** [comment]
> @gaganmalvi please PR the fix so that we can review it 

Sure - by the next hour.

**Comment by MarijnS95** [comment]
@gaganmalvi This would apply to _all_ devices; it should end up in the `common` repo next to where ModemSwitcher and relevant files are configured.

**Comment by gaganmalvi** [comment]
I'm confused; how do you manage proprietary blobs? Do you do something like LineageOS or is there another vendor repository

**Comment by jerpelea** [comment]
the proprietary blobs are published by Sony and they are flashes on a separate partition

**Comment by MarijnS95** [comment]
> I do not have a Sony smartphone.

@gaganmalvi I can look into this as well if that's easier for you. That way I can test this and make the change in the right location, instead of lots of back-and-forth :wink:

**Comment by gaganmalvi** [comment]
Since it is prebuilt, I think you can just add this to an Android.bp, just like this: 
https://github.com/teracube-mt6765-devs/android_device_teracube_mt6765-common/commit/d7a15827486fe98eb0dc084c13f8c0b547d6b578

**Comment by MartinX3** [comment]
@gaganmalvi 
vendor contains only open source as far as I know
The proprietary stuff is in the OEM.img

**Comment by gaganmalvi** [comment]
> @gaganmalvi vendor contains only open source as far as I know The proprietary stuff is in the OEM.img (oem partition)

...what?
_Sony devices are confusing_ (don't kill me for this :O)
If you are compiling a vendor partition, please disregard the above message xD

**Comment by jerpelea** [comment]
> @gaganmalvi vendor contains only open source as far as I know The proprietary stuff is in the OEM.img (oem partition)

the vendor is built from source and all prebuilts are on oem.img

**Comment by gaganmalvi** [comment]
I'll make a PR in a bit; can you please run tests?

**Comment by MartinX3** [comment]
@gaganmalvi thank you. I was able to build an akai ota.zip

**Comment by gaganmalvi** [comment]
That's amazing; glad to know it worked!

**Comment by jerpelea** [comment]
fixed @gaganmalvi thanks for looking into the issue

**Comment by gaganmalvi** [comment]
Anytime, seems fun to work on Sony devices; hopefully would be able to own one someday!
