### ISSUE TITLE
[EDO PDX206][11][4.19] Mobile Network Connection Dropping

### ISSUE THREAD

**Issue by iancornelius** [sonyxperiadev/bug_tracker#746]
**Platform:** Edo
**Device:** pdx206
**Kernel version:** 4.19.188
**Android version:** 11.0.0_r46
**Software binaries version:** v8a

**Previously working on** 
Unknown

**Description**
Connection to mobile network drops out and reconnects constantly.

**Symptoms**
Unable to receive/make text/phone calls and use mobile data

**How to reproduce**
Build AOSP 11.0.0_r46 with Open GApps Pico

**Additional context**
`adb logcat -b radio`:  [log_radio.txt](https://github.com/sonyxperiadev/bug_tracker/files/8033062/log_radio.txt)

I have tried flashing the modem file from the stock Android 11 firmware from Sony using *newflasher*; however, this does not seem to have resolved the issue.

**Comment by Thaodan** [comment]
I noticed on my device I can call but no connect to mobile data nether in AOSP or Sailfish OS.

**Comment by Thaodan** [comment]
I also have issues getting mobile data working. After flashing stock it was working initially but then it broke again.

**Comment by Miustone** [comment]
Used this Branch? 
https://github.com/sonyxperiadev/vendor-qcom-opensource-telephony/tree/aosp/LA.QSSI.12.0.r1
I am trying this one right now and see if it fixes My 1 III
https://github.com/sonyxperiadev/vendor-qcom-opensource-telephony/tree/aosp/LA.UM.9.14.r1

**Comment by Thaodan** [comment]
Marius Kopp ***@***.***> writes:

> I am trying this one right now and see if it fixes My 1 III
> https://github.com/sonyxperiadev/vendor-qcom-opensource-telephony/tree/aosp/LA.UM.9.14.r1

This bug is about Xperia 1 II

**Comment by jerpelea** [comment]
Discontinued Android version
