### ISSUE TITLE
[lilac] Is it possible to set verified boot state to YELLOW?

### ISSUE THREAD

**Issue by cryptomilk** [sonyxperiadev/bug_tracker#75]
Hello,

when you unlock the device, the boot state is set to ORANGE.

`androidboot.verifiedbootstate=orange`

Is it possible to change it to YELLOW?

See:
https://source.android.com/security/verifiedboot/verified-boot#boot_state

**Comment by oshmoun** [comment]
That would require signing the boot image with Sony keys right?

**Comment by jerpelea** [comment]
Hi,

there is no public option to change the verifiedbootstate on an unlocked phone 

Regards
Alin

**Comment by cryptomilk** [comment]
@oshmoun It would mean that verity would be checked, but the bootloader will not check if the boot.img is signed with the Sony keys.
