### ISSUE TITLE
TAMA BACK CAMERA PROBLEM ON GSI TREBLE ROM

### ISSUE THREAD

**Issue by cuynu** [sonyxperiadev/bug_tracker#750]
**Platform: Tama** 
**Device: Akari** 
**Kernel version: 4.14** 
**Android version: 11** 
**Software binaries version: Stock OEM** 

**Previously working on**
Back camera is working on stock firmware

**Description**
Back camera not working on GSI Treble (Generic System Image) ROM

**Symptoms**
While open back camera got an camera error cannot connect to camera problem

**How to reproduce**
Flash any GSI Treble rom and open back camera

**Additional context**
Add any other context, e.g. upload logs or screenshots about the bug here.

**Comment by MartinX3** [comment]
No logs no help.

Does it work without a GSI?

**Comment by cuynu** [comment]
> * No logs, no help.
> * Stock OEM is not supported
> 
> Does it work without a GSI and with SODP OEM?

SODP OEM with SonyAOSP 11 camera works fine but while record video, its very delay

Here is my log 
[log.txt](https://github.com/sonyxperiadev/bug_tracker/files/8104372/log.txt)

**Comment by sraase** [comment]
According to your log, you run the stock camera HAL, which we don't support.
