### ISSUE TITLE
[Tama][Apollo][4.14][AOSP11] Dropped frames: dsi-ctrl:[dsi_ctrl_handle_error_status] tx timeout error: 0x40

### ISSUE THREAD

**Issue by faenil** [sonyxperiadev/bug_tracker#758]
**Platform:** Tama
**Device:** Apollo
**Kernel version:** 4.14 
**Android version:** AOSP11 r46
**Software binaries version:** v9a

**Previously working on**
N/A

**Description**
After fixing most of the UI lags caused by https://github.com/sonyxperiadev/bug_tracker/issues/757 I am now experiencing UI lags in the Settings application, with dmesg printing a lot of 
`dsi-ctrl:[dsi_ctrl_handle_error_status] tx timeout error: 0x40`
Not sure yet if that is a problem or just a consequence of the GPU not being able to render frames on time.

**Symptoms**
Laggy scrolling in AOSP Settings application

**How to reproduce**
- Mod kernel to fix https://github.com/sonyxperiadev/bug_tracker/issues/757 and add support for rqbalance governor by expanding the apollo defconfig with
```
CONFIG_QCOM_RUN_QUEUE_STATS=y
CONFIG_CPU_QUIET=y
CONFIG_CPU_QUIET_DEFAULT_GOV_RQBALANCE=y
CONFIG_CPU_QUIET_MSM=y
```

- Flash AOSP11 and fixed kernel (will post more instructions as I get the time)
- Open Settings application
- Scroll up and down

**Additional context**
dmesg excerpt:
```
[  332.839122] init: Control message: Could not find 'android.hardware.radio@1.5::IRadio/slot1' for ctl.interface_start from pid: 543 (/system/bin/hwservicemanager)
[  332.973011] IRQ 6: no longer affine to CPU4
[  332.973307] CPU4: shutdown
[  333.352983] dsi-ctrl:[dsi_ctrl_handle_error_status] tx timeout error: 0x40
[  333.386204] dsi-ctrl:[dsi_ctrl_handle_error_status] tx timeout error: 0x40
[  333.769841] CPU1: shutdown
[  333.848561] init: Control message: Could not find 'android.hardware.radio@1.5::IRadio/slot1' for ctl.interface_start from pid: 543 (/system/bin/hwservicemanager)
[  334.577601] dsi-ctrl:[dsi_ctrl_handle_error_status] tx timeout error: 0x40
[  334.610625] dsi-ctrl:[dsi_ctrl_handle_error_status] tx timeout error: 0x40
[  334.643744] dsi-ctrl:[dsi_ctrl_handle_error_status] tx timeout error: 0x40
[  334.846752] init: Control message: Could not find 'android.hardware.radio@1.5::IRadio/slot1' for ctl.interface_start from pid: 543 (/system/bin/hwservicemanager)
[  335.124003] dsi-ctrl:[dsi_ctrl_handle_error_status] tx timeout error: 0x40
```

**Comment by MartinX3** [comment]
The tx error is also in #705 :)

**Comment by MarijnS95** [comment]
I was under the assumption that this only happened on Akatsuki: whenever there's corruption on the screen - observed when the phone renders a single hardware plane on fullscreen - the """Quality""" of Service closed-source binary seems to have been making the wrong choice somewhere and underclocks the hardware, resulting in the same `tx timeout error: 0x40`.

Is there any corruption (colored scanlines going over the screen) visible on Apollo too?

**Comment by faenil** [comment]
I see, thanks for the insight @MarijnS95

I could not see major glitches, perhaps some occasional frame overlap...need to play with it a bit more

**Comment by faenil** [comment]
I see, thanks for the insight @MarijnS95

I could not see major glitches, perhaps some occasional frame overlap...need to play with it a bit more
