### ISSUE TITLE
[all] Network packets filtering and routing by UID does not works

### ISSUE THREAD

**Issue by abioteau** [sonyxperiadev/bug_tracker#76]
**Platform:** ALL
**Device:** ALL
**Kernel version:** 4.4 (5.7_r1)
**Android version:** 7.1.1

**Description**
The per-UID routing is broken since kernel 4.4 (5.7_r1) integrates https://github.com/sonyxperiadev/kernel/pull/1397 which include new-style UID routing from Android o-mr0 :
- https://github.com/sonyxperiadev/kernel/commit/4cbacec96b3cdddc949d4677b06664cb4f7b3d9c
- https://github.com/sonyxperiadev/kernel/commit/afa2b930b940d05593e52b1ecc03754f7eadcc81

**Symptoms**
UID range does not take into account when "VPN" is enable. The command `adb shell ip rule show` does not returns **uidrange** information as it should be: 

> 12000:  from all fwmark 0x0/0x20000 iif lo lookup tun0
> 13000:  from all fwmark 0x10065/0x1ffff lookup tun0
> 14000:  from all oif tun0 lookup tun0

instead of : 

> 12000:  from all fwmark 0x0/0x20000 iif lo **uidrange 0-99999** lookup tun0
> 13000:  from all fwmark 0x10065/0x1ffff **uidrange 0-99999** lookup tun0
> 14000:  from all oif tun0 uidrange **0-99999** lookup tun0

**How to reproduce**
1) Enable VPN
2) Execute `adb shell ip rule show` command. It should return the following lines for **tun0** interface. 

> 12000:  from all fwmark 0x0/0x20000 iif lo uidrange 0-99999 lookup tun0
> 13000:  from all fwmark 0x10065/0x1ffff uidrange 0-99999 lookup tun0
> 14000:  from all oif tun0 uidrange 0-99999 lookup tun0

**Comment by abioteau** [comment]
To solve this issue, we need to integrate the following patches:

- platform/system/netd
Set both legacy and new UID routing attributes. https://android.googlesource.com/platform/system/netd/+/2b078678aafceeefea6a70e96ab8ddefe515d027 
 Use new-style UID routing. https://android.googlesource.com/platform/system/netd/+/882e467ff7b83de868fa0b9a9beb9036bf14aede

- platform/external/iproute2
Update UID routing to upstream implementation. https://android.googlesource.com/platform/external/iproute2/+/04cd308001d732a1c8e5d244daba37c56a4641b0

**Comment by jerpelea** [comment]
looks good

**Comment by jerpelea** [comment]
please pr to repo_update

**Comment by abioteau** [comment]
It is already done. https://github.com/sonyxperiadev/repo_update/pull/18. @jerpelea could you create a branch n-mr1_4.4 in order to point on it from local manifests n-mr1_4.4 (see PR https://github.com/sonyxperiadev/local_manifests/pull/29).

**Comment by jerpelea** [comment]
thanks for taking care of it
