### ISSUE TITLE
[Kumano][J9210][12L] SP2A.220305.012 Wifi Not working

### ISSUE THREAD

**Issue by Miustone** [sonyxperiadev/bug_tracker#767]
**Platform:** Kumano
**Device:** Xperia 5 J9210
**Kernel version:** 4.19
**Android version:** android-12.1.0_r1
**Software binaries version:** Android 12.0 – Kernel 4.19 – Kumano (v1)

**Previously working on**
Don't know...

**Description**
Tapping the Toggles does nothing

**Symptoms**
Wifi does not turn on ir shows Networks

**How to reproduce**
Install AOSP, OEM, Wipe Userdata and tada

**Additional context**
Tell me which Logs You will need and i pull them...

**Comment by bartcubbins** [comment]
https://github.com/sonyxperiadev/kernel-defconfig/pull/116

**Comment by Miustone** [comment]
Thanks! Looks Like its fixes!? I'll make a Clean sync with Aprils 12L and build today to try...

**Comment by bartcubbins** [comment]
Yes, but please note that Alin did not recompile the prebuilt kernel and you need to do it yourself

**Comment by Miustone** [comment]
Its working since some Days. I'll close this Issue (:
