### ISSUE TITLE
[loire] mtp is broken for large files

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#77]
**Platform:** loire
**Device:** kugo, suzu
**Kernel version:** 6.4
**Android version:** 8.1

**Description**
MTP is broken on loire devices.

**Symptoms**
Copying a file to the device using MTP causes MTP to hang right at the end of the copying process.

**How to reproduce**
Try to copy a file larger than 400mb to the device using mtp.

**Comment by jerpelea** [comment]
fixed
98763c9cf06df04fed1e083097eb141719536682
567d85b2655b6acb796d861d3dbbaee660cbcb13
17d0971c67860d45d419757434d37fe834fb699b
edbdfdda6134bc22d22cb1965b82df16859a77bb
d9d26086abd54fde43ab299099c60670aba57a1b

**Comment by jerpelea** [comment]
please retest

**Comment by oshmoun** [comment]
thanks! The issue seems resolvednow.
md5sum of the copied file matches as well
