### ISSUE TITLE
[Kumano][J9210][12L] SP2A.220405.004 No Mobile Data / No second SIM

### ISSUE THREAD

**Issue by Miustone** [sonyxperiadev/bug_tracker#774]
**Platform:** Kumano
**Device:** Xperia 5 J9210
**Kernel version:** 4.19
**Android version:** android-12.1.0_r4
**Software binaries version:** Android 12.0 – Kernel 4.19 – Kumano (v1)

**Previously working on**
Don't know...

**Description**
No initial Mobile Data while it's already turned on after first boot. APN is available but not set. Network shows 4G+ but there is no connection. Can also not send SMS but can do Phone Calls...

**Symptoms**
No Network Connection to Mobile Data

**How to reproduce**
Install AOSP, OEM, Wipe Userdata and tada

**Additional context**
Tell me which Logs You will need and i pull them...
Tried everything around the Settings including switching Network Type (2G,3G,4G), turning Mobile Data on and off. Tried own made APN, tried to switch SIM Slots and the second Slot does not recognize My SIM Card.

**Comment by Thaodan** [comment]
Looks like it related to #735, please check logcat and kernel messages (dmesg).

**Comment by Miustone** [comment]
Still a Problem with the latest Binaries from the 13th... Also on Sagami / Xperia 1 III

**Comment by BrandonMCMFG** [comment]
I have confirmed that this is an issue with the Xperia 5 (J8210-Kunamo) on GSIs and ROMs that use the latest Sony Software Binaries (OEM-Images). 
**Please fix this Sony as it makes my phone useless as a phone on Custom ROMs... :-(**

**Comment by bartcubbins** [comment]
Better late than never https://github.com/sonyxperiadev/kernel/pull/2538

**Comment by voidanix** [comment]
> Better late than never sonyxperiadev/kernel#2538

This is supposed to only fix second SIM detection, mobile data still does not connect.

Something that might be relevant from logs:

```
D DC-C-1  : DcActivatingState: ERROR_DATA_SERVICE_SPECIFIC_ERROR  delay=-1 result=ERROR_DATA_SERVICE_SPECIFIC_ERROR  SetupResult.mFailCause=OEM_DCFAILCAUSE_4 result.isRadioRestartFailure=false isPermanentFailure=false
```

Seems to bring nowhere though: https://cs.android.com/android/platform/superproject/+/android-12.1.0_r27:frameworks/base/telephony/java/android/telephony/DataFailCause.java;l=1008

**Comment by bartcubbins** [comment]
patch was intended only for second SIM detection

**Comment by voidanix** [comment]
Any updates on this? The only thing I could notice thus far is `CONFIG_IPA3` missing from kumano's defconfigs.

**Comment by Miustone** [comment]
They didn't fix anything modem related on any device i guess. No SIM / Mobile Data for the most... I gave up on Xperias

**Comment by jerpelea** [comment]
the issue is kernel related.

**Comment by voidanix** [comment]
Kumano will remain unusable for normal users until both mobile data and
camera will start working.

Enabling IPA (which is, AFAIU, required) on kumano seems to trigger a panic
(device reboots a few seconds into the bootanimation). How is one supposed
to pull pstore from the device to look into this, though? Everything seems
already in place in the defconfig, but there is seemingly no way to pull
the files because the system will just not boot (and the recovery does not
provide adb to do a pull).

I also tried flashing a stock-based recovery to pull the logs, but the
pstore folder only contained crashes from stock-based ROMs, making me
suspect pstore is just broken on 4.19 (looking into this as well rn).

**Comment by voidanix** [comment]
Here's a version with IPADBG enabled: [console-ramoops-0-ipadbg.txt](https://github.com/sonyxperiadev/bug_tracker/files/12850402/console-ramoops-0.txt)
