### ISSUE TITLE
[SAGAMI][PDX215][12L] SQ3A.220605.009.A1 Battery not working 

### ISSUE THREAD

**Issue by Miustone** [sonyxperiadev/bug_tracker#776]
**Platform:** Sagami
**Device:** PDX215
**Kernel version:** 5.4
**Android version:** 12L
**Software binaries version:** SW_binaries_for_Xperia_Android_12_5.4_v2a_sagami

**Previously working on**
Never worked on 12L

**Description**
Battery doesnt shows Percentage or any Info while Off or On...

**Symptoms**
Can't charge or see how much Battery is left...

**How to reproduce**
Install AOSP, OEM, Wipe Userdata and tada

**Additional context**
...

**Comment by jerpelea** [comment]
the bug has been fixed and tested on v3
please sync and build

**Comment by MarijnS95** [comment]
Fixed by https://github.com/sonyxperiadev/device-sony-common/pull/892.
