### ISSUE TITLE
[SAGAMI][PDX215][12L] SQ3A.220605.009.A1 No Wifi

### ISSUE THREAD

**Issue by Miustone** [sonyxperiadev/bug_tracker#778]
**Platform:** Sagami
**Device:** PDX215
**Kernel version:** 5.4
**Android version:** 12L
**Software binaries version:** SW_binaries_for_Xperia_Android_12_5.4_v2a_sagami

**Previously working on**
Never worked on 12L

**Description**
Can't turn on Wifi. Toggle goes back to Off...

**Symptoms**
No way to turn it on. No Networks are shown...

**How to reproduce**
Install AOSP, OEM, Wipe Userdata and tada

**Additional context**
Since Mobile Data is also not working = Non Usable Device

**Comment by jerpelea** [comment]
I can confirm the issue.
The issue will be fixed ASAP

**Comment by jerpelea** [comment]
the issue has been identified and will be fixed ASAP

**Comment by Miustone** [comment]
Thanks a Ton, really appreciate Your Work! I totally depend on this with D!OS. Glad that we have soon a New and fully working OS for our Xperias 🤍 I'll let the issue open for now. Feel free to Close it If wanted...

**Comment by Miustone** [comment]
Thanks a Ton, really appreciate Your Work! I totally depend on this with D!OS. Glad that we have soon a New and fully working OS for our Xperias 🤍 I'll let the issue open for now. Feel free to Close it If wanted...

**Comment by Miustone** [comment]
Got back to building and played around with available branches but still no Wifi here. Any news?

**Comment by Miustone** [comment]
[wifi.txt](https://github.com/sonyxperiadev/bug_tracker/files/10036613/wifi.txt)
adb logcat "wpa_supplicant"

**Comment by bartcubbins** [comment]
As they say, better late than never, I have patches for this, they will land soon

**Comment by bartcubbins** [comment]
Was fixed in https://github.com/sonyxperiadev/device-sony-sagami/pull/23
