### ISSUE TITLE
[kagura] netmgrd constantly crashing when forceencrypt enabled

### ISSUE THREAD

**Issue by nexus511** [sonyxperiadev/bug_tracker#78]
**Platform: tone** 
**Device: kagura (F8331)** 
**Kernel version: Linux localhost 4.4.78-gca9d20e-dirty #13 SMP PREEMPT Tue Jan 30 16:16:02 CET 2018 aarch64** 
**Android version: android-8.1.0_r3** 
**Binaries: SW_binaries_for_Xperia_Android_8.1.6.4_r1_v10_tone.zip**

**Description**

After compiling and installing a recent android-8.1.0_r3 based build on the Sony XZ, I see constant crashes of the netmgrd process.

There is also no data connection via 2G/3G/4G available (which I would guess is related).

**Symptoms**

Every few seconds, a crash entry is written to the log:

```
01-01 12:29:22.329  1134  2815 W NativeCrashListener: Couldn't find ProcessRecord for pid 8911
01-01 12:29:22.334   956   956 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_17
01-01 12:29:22.336  1134  1153 I BootReceiver: Copying /data/tombstones/tombstone_17 to DropBox (SYSTEM_TOMBSTONE)
01-01 12:29:27.212  8921  8921 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x58 in tid 8921 (netmgrd), pid 8921 (netmgrd)
01-01 12:29:27.234  8924  8924 E cutils-trace: Error opening trace file: No such file or directory (2)
01-01 12:29:27.239  8925  8925 W crash_dump64: failed to attach to thread 8922: Operation not permitted
01-01 12:29:27.246  8925  8925 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
01-01 12:29:27.248   956   956 I /system/bin/tombstoned: received crash request for pid 8921
01-01 12:29:27.251  8925  8925 I crash_dump64: performing dump of process 8921 (target tid = 8921)
01-01 12:29:27.253  8925  8925 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-01 12:29:27.254  8925  8925 F DEBUG   : Build fingerprint: 'Sony/aosp_f8331/kagura:8.1.0/OPM1.171019.012/nexus02011743:userdebug/test-keys'
01-01 12:29:27.254  8925  8925 F DEBUG   : Revision: '0'
01-01 12:29:27.255  8925  8925 F DEBUG   : ABI: 'arm64'
01-01 12:29:27.256  8925  8925 F DEBUG   : pid: 8921, tid: 8921, name: netmgrd  >>> /odm/bin/netmgrd <<<
01-01 12:29:27.256  8925  8925 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x58
01-01 12:29:27.257  8925  8925 F DEBUG   : Cause: null pointer dereference
01-01 12:29:27.257  8925  8925 F DEBUG   :     x0   0000000000000000  x1   0000007fcb2e4118  x2   0000000000000004  x3   0000000000000000
01-01 12:29:27.258  8925  8925 F DEBUG   :     x4   0000000000000008  x5   0000000000000020  x6   fefefefefefefeff  x7   7f7f7f7f7f7f7f7f
01-01 12:29:27.258  8925  8925 F DEBUG   :     x8   b81e2f228b35c8a0  x9   b81e2f228b35c8a0  x10  0000000000000000  x11  0000000000000001
01-01 12:29:27.259  8925  8925 F DEBUG   :     x12  0000000000000010  x13  0000000000000000  x14  0000000a2911e64b  x15  0000000000000240
01-01 12:29:27.260  8925  8925 F DEBUG   :     x16  0000000a29139de0  x17  0000006ffdb11a34  x18  0000000000000010  x19  0000000000000000
01-01 12:29:27.260  8925  8925 F DEBUG   :     x20  0000000000000001  x21  0000000a29119434  x22  0000007fcb2e47f8  x23  0000006ffdc67190
01-01 12:29:27.261  8925  8925 F DEBUG   :     x24  0000000000000000  x25  0000006ffe432a40  x26  0000000000000000  x27  0000000000000000
01-01 12:29:27.261  8925  8925 F DEBUG   :     x28  0000000000000000  x29  0000007fcb2e4190  x30  0000000a290bf590
01-01 12:29:27.262  8925  8925 F DEBUG   :     sp   0000007fcb2e4180  pc   0000006ffdb11a44  pstate 0000000060000000
01-01 12:29:27.269  8925  8925 F DEBUG   : 
01-01 12:29:27.269  8925  8925 F DEBUG   : backtrace:
01-01 12:29:27.270  8925  8925 F DEBUG   :     #00 pc 0000000000078a44  /system/lib64/libc.so (fileno+16)
01-01 12:29:27.270  8925  8925 F DEBUG   :     #01 pc 000000000005558c  /odm/bin/netmgrd (netmgr_main+892)
01-01 12:29:27.271  8925  8925 F DEBUG   :     #02 pc 000000000001c148  /odm/bin/netmgrd (main+28)
01-01 12:29:27.271  8925  8925 F DEBUG   :     #03 pc 00000000000a44c4  /system/lib64/libc.so (__libc_init+88)
01-01 12:29:27.272  8925  8925 F DEBUG   :     #04 pc 000000000001b190  /odm/bin/netmgrd (_start_main+80)
01-01 12:29:27.330  1134  2815 W NativeCrashListener: Couldn't find ProcessRecord for pid 8921
01-01 12:29:27.334   956   956 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_18
01-01 12:29:27.336  1134  1153 I BootReceiver: Copying /data/tombstones/tombstone_18 to DropBox (SYSTEM_TOMBSTONE)
01-01 12:29:32.217  8931  8931 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x58 in tid 8931 (netmgrd), pid 8931 (netmgrd)
01-01 12:29:32.239  8934  8934 E cutils-trace: Error opening trace file: No such file or directory (2)
01-01 12:29:32.244  8935  8935 W crash_dump64: failed to attach to thread 8932: Operation not permitted
01-01 12:29:32.250  8935  8935 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
01-01 12:29:32.252   956   956 I /system/bin/tombstoned: received crash request for pid 8931
01-01 12:29:32.255  8935  8935 I crash_dump64: performing dump of process 8931 (target tid = 8931)
```

**How to reproduce**

- build AOSP based on android-8.1.0_r3 following https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-nougat-8-1-oreo-4-4/
- flash OEM package and firmware to device
- boot device with SIM card inserted

**Comment by nexus511** [comment]
Tombstone regarding the crash is available at https://paste.ubuntu.com/26505557/ .

**Comment by Bitti09** [comment]
can't reproduce on my kagura.

How do you flashed the  oem image ?

**Comment by nexus511** [comment]
On a first attempt, I flashed it by directly writing it to 

```
/dev/block/platform/soc/7464900.sdhci/by-name/oem
```

which maps to 

```
/dev/block/mmcblk0p53
```

from recovery (after unpacking with simg2img of course).

As this did not work, I reflashed the device with the current stock image via EMMA and then used

```
fastboot flash oem <image>
```

which leads the the same problem.

**Comment by jerpelea** [comment]
please use the latest build guid instructions
https://developer.sony.com/develop/open-devices/

**Comment by jerpelea** [comment]
please update your device to the latest Sony SW with Emma then flash your build

**Comment by nexus511** [comment]
I actually already did that.

I flashed the device with the latest Sony SW via EMMA and then created a completely new build:

```
mkdir android
repo init -u https://android.googlesource.com/platform/manifest -b android-8.1.0_r3
cd .repo
git clone https://github.com/sonyxperiadev/local_manifests
cd local_manifests
git checkout android-8.1.0_r3
cd ../..
repo sync -j4
./repo_update.sh 
. build/envsetup.sh 
lunch
make -j8
pushd out/target/product/kagura/
fastboot flash oem ~/binaries/SW_binaries_for_Xperia_Android_8.1.6.4_r1_v10_tone.img
for i in boot recovery system; do fastboot flash $i $i.img; done
```

I am still running into the same error. All I notice that the firmware flashed via EMMA reports a different (slightly newer) baseband firmware than SW_binaries_for_Xperia_Android_8.1.6.4_r1_v10_tone.img seems to provide.

Any idea what I might be missing/doing wrong here?

**Comment by nexus511** [comment]
I don't know why, but now the issue has disappeared and I cannot reproduce it on the phone anymore.

**Comment by nexus511** [comment]
Okay. The issue reappears whenever I set forceencrypt=foot for the userdata partition.

Thus, there is an issue with netmgrd on encrypted devices.

**Comment by jerpelea** [comment]
the device encryption works fine and i can not replicate the issue 
@Bitti09 can you reproduce this issue ?

**Comment by nexus511** [comment]
To be sure that we are actually seeing the same issue. I am running the 8.1.0_r10 base build right now, but the same happens on 8.1.0_r3.

To trigger the issue, I use "forceencrypt". This is enabled by the following patch in the devices/sony/tone tree:

```
diff --git a/rootdir/fstab.tone b/rootdir/fstab.tone
index e3bf8af..ac3d132 100644
--- a/rootdir/fstab.tone
+++ b/rootdir/fstab.tone
@@ -5,7 +5,7 @@
 /dev/block/bootdevice/by-name/system       /system      ext4    ro,barrier=1                                                  wait
 /dev/block/bootdevice/by-name/oem          /odm         ext4    ro,barrier=1                                                  wait
 /dev/block/bootdevice/by-name/cache        /cache       ext4    noatime,nosuid,nodev,barrier=1,data=ordered,noauto_da_alloc,errors=panic wait,check,formattable
-/dev/block/bootdevice/by-name/userdata     /data        ext4    noatime,nosuid,nodev,barrier=1,data=ordered,noauto_da_alloc,discard,errors=panic wait,check,formattable,forceencrypt=footer
+/dev/block/bootdevice/by-name/userdata     /data        ext4    noatime,nosuid,nodev,barrier=1,data=ordered,noauto_da_alloc,discard,errors=panic wait,check,formattable,encryptable=footer
 /dev/block/bootdevice/by-name/boot         /boot        emmc    defaults                                                      defaults
 /dev/block/bootdevice/by-name/FOTAKernel   /recovery    emmc    defaults                                                      defaults
 /dev/block/bootdevice/by-name/frp          /persistent  emmc    defaults                                                      defaults
```

If I switch back to just allow encryption of the userdata partition and perform a new build with a clean fstab, the issue deappears.

**Comment by jerpelea** [comment]
fisrt we should see what does each option 
encryptable - allowes you to boot for the first time unencripted and you can encrypt later from settings
forceencrypt - userdata is forced as encrypted on the first boot.

I suspect that the crash that you see is caused either by a permission error (netmgrd can not write on userdata)

please check permisisons and contents on those folders in both cases of encryption 
https://github.com/sonyxperiadev/device-sony-common/blob/master/rootdir/vendor/etc/init/netmgrd.rc

**Comment by nexus511** [comment]
Yeah. You are completely right.

The point is that "on boot" fires before /data is mounted. This means that "/data/vendor/netmgr" never gets created at all.

From what I would guess after a small look at the disassembly, netmgr wants to create "/data/vendor/netmgr/log.txt" which causes a NULL pointer to be returned and netmgr to crash on "fileno".

So I would guess that those crashes also happen on devices that get encrypted after the initial setup but it actually disappears in the log, as the netmgrd gets restarted and properly runs up in a later phase of the boot.

Moving the creation of the directory into the "on-post-fs" trigger will most likely fix the issue.

I will take a deeper look at it and report back as soon as I know that I can confirm above thoughts.

**Comment by nexus511** [comment]
I moved the creation of the directories on the /data partition to the **post-fs-data** trigger and it now properly boots.

It looks like **netmgrd** never gets started before **post-fs-data** fires. I will verify this. If this is the case, I would create a pull-request on this issue. If you don't want to have this change in the tree feel free to reject it, but I would like to keep it as a reference for others tapping into the same issue.

The patch can be basically condensed to

```
diff --git a/rootdir/vendor/etc/init/netmgrd.rc b/rootdir/vendor/etc/init/netmgrd.rc
index c41e46b..3cc4e4c 100644
--- a/rootdir/vendor/etc/init/netmgrd.rc
+++ b/rootdir/vendor/etc/init/netmgrd.rc
@@ -2,6 +2,7 @@ on boot
     #Create NETMGR daemon socket area
     mkdir /dev/socket/netmgr 0750 radio radio
 
+on post-fs-data
     #create netmgr log dir
     mkdir /data/vendor/netmgr 0770 radio radio
     chmod 0770 /data/vendor/netmgr
```

**Comment by jerpelea** [comment]
your finding is valid. Please PR the change

**Comment by jerpelea** [comment]
fixed
