### ISSUE TITLE
suzu broken build

### ISSUE THREAD

**Issue by asmithgh** [sonyxperiadev/bug_tracker#780]
**Platform:** loire
**Device:** suzu
**Kernel version:** 3.10
**Android version:** 6.0.1
**Software binaries version:** v13

**Description**
I followed the instructions at [developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-nougat-marshmallow-6-0-1](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-nougat-marshmallow-6-0-1). The build finishes with no errors. I flashed the build and the latest version of software binaries (v13) from [developer.sony.com/file/download/software-binaries-for-aosp-marshmallow-android-6-0-1-kernel-3-10-loire](https://developer.sony.com/file/download/software-binaries-for-aosp-marshmallow-android-6-0-1-kernel-3-10-loire). Shortly after booting the device, the notification LED lights up purple for a few seconds and the phone does not boot after that, it gets stuck on the Sony logo.

I completed the build on two different machines but the result from both of the machines is the same, the phone does not boot. I tried building newer versions of Android (9.0 and 8.0) for suzu and they boot up just fine.

I assume it has something to do with the change from supplying the software binaries during the build in v12 to flashing the binaries after the build is completed in v13. It seems like some binaries are either in a wrong place or missing completely in v13.

**How to reproduce**
Follow the instructions at [developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-nougat-marshmallow-6-0-1](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-nougat-marshmallow-6-0-1)

**Additional context**
[dmesg.txt](https://github.com/sonyxperiadev/bug_tracker/files/9010704/dmesg.txt)
[logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/9010706/logcat.txt)
[tombstone_03.txt](https://github.com/sonyxperiadev/bug_tracker/files/9010707/tombstone_03.txt)

**Comment by Haxk20** [comment]
Loire as platform has been deprecated and so has Android 6 been. For some time now actually. Aprox 7 years.

I can recommend only 1 thing here. Use newer Android version.

**Comment by jerpelea** [comment]
I am sorry but the platform is discontinued and I am unsure if you can build it on Ubuntu 20
