### ISSUE TITLE
[TAMA][AKARI][12.1] "There's an internal problem with your device."

### ISSUE THREAD

**Issue by AbelChT** [sonyxperiadev/bug_tracker#783]
**Platform:** Tama
**Device:** XZ2
**Kernel version:** 4.19
**Android version:** 12.1
**Software binaries version:** SW_binaries_for_Xperia_Android_12_4.19_v3a_tama.img

**Previously working on**
Before flashing Android 12, I flashed the latest stock ROM

**Description**
After building Android 12 (android-12.1.0_r11) and flashing it, I consistently see the the pop up "There's an internal problem with your device." when Android boot.

I detected as well that sometimes the device is not detecting the SIM card when it boots. Also, sometimes the display goes into a blue tone forcing me to restart it to recover the original colours.

I attach logs.
[logcat_b_all.log](https://github.com/sonyxperiadev/bug_tracker/files/9333997/logcat_b_all.log)

**Comment by jerpelea** [comment]
this is normal since

**Comment by faenil** [comment]
since? :)

**Comment by faenil** [comment]
@jerpelea

**Comment by q-b** [comment]
Same here but on android 13
Tama XZ2C (Apollo)
Same software binaries version

**Comment by sraase** [comment]
This message appears when the odm partition version does not match the version expected by Android (TARGET_VENDOR_VERSION). Flashing a matching odm partition makes the message go away.
