### ISSUE TITLE
[PDX-225] Sony Xperia 10 IV Not Building AOSP android-13.0.0_r1, android-12.0.0_r28

### ISSUE THREAD

**Issue by kenkko** [sonyxperiadev/bug_tracker#784]
**Platform:** Linux Mint
**Device:** Xperia 10 IV XQ-CC72 / CC54

**Description**

Cannot compile code from source. I have followed the guide from [https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-12-0](url).
On branch android-12.0.0_r28, doing command: repo sync, and ./repo_update show that files are missing. 
The following command: source build/envsetup.sh && lunch creates no toast menu to select common combinations.

On branch android-13.0.0_r1, it gets as far as showing a toast menu, but says that gsi_keys.mk is missing. I was able to fix this by downloading the file directly from google git, and putting it into the correct location (/home/user/android/build/target/product). However, on running the command: make -j$(nproc), I am unable to compile the code. I also ran using: make -j 16, and got the same result. It says that many functions are already defined. Please check the logs for more information. Any help would be appreciated.
[crash log.txt](https://github.com/sonyxperiadev/bug_tracker/files/9372697/crash.log.txt)
[crash log 16.txt](https://github.com/sonyxperiadev/bug_tracker/files/9372698/crash.log.16.txt)

**Comment by jerpelea** [comment]
@kenkko thanks for your interest 
The new IV devices are added to the project but they are not officially announced yet

We are working together with community to get the up to sped ASAP. If you are interested in landing a hand you can always submit bugs / PR to help

Best regards
Alin

**Comment by TeamSoulMortal** [comment]
@kenkko 
Go to external folder and remove whole exfatprogs cause its already defined in vendor/external/exfatprogs

Rebuild now and see how it goes...

**Comment by jerpelea** [comment]
I will push the local manifest fix 
please sync the repo

**Comment by kenkko** [comment]
@jerpelea 
Thanks for the advice. I synced the repos, and tried it again.

When running repo sync, I cannot sync the whole tree due to StorageManagerService.java, which needs merging. It tells me to resolve the current index. How do I fix this? Log attached ([StorageManagerService crash.txt](https://github.com/sonyxperiadev/bug_tracker/files/9378306/StorageManagerService.crash.txt)). The repo_update.sh also has the same error ([update script crash.txt](https://github.com/sonyxperiadev/bug_tracker/files/9378307/update.script.crash.txt)).

When running make (make -j$(nproc)), it tells me that: "vendor.qti.hardware.vibrator.impl" depends on undefined module "android.hardware.vibrator-V2-ndk_platform", and the build fails. ([new crash log.txt](https://github.com/sonyxperiadev/bug_tracker/files/9378308/new.crash.log.txt)).

Were can I find the official announcements for new devices to the program? The open devices maintained devices list shows the 10 IV, so I was wondering if they were announced somewhere else?

Thanks for your help

**Comment by jerpelea** [comment]
There are other ways to fix the issue but it is  easy to remove your local repo and start over 

The alpha blobs are released for community early but the official announcement will be made when the devices are reasonably stable. There will be a blog post when they are ready

**Comment by LecrisUT** [comment]
I have tried to build using the provided guide on a Fedora 36, however it fails in similar way as the original. I suppose this is because it is still `WIP`? The error I get:
```
FAILED: ninja: 'kernel/sony/msm-5.4/common-kernel/kernel-pdx225', needed by 'out/target/product/pdx225/kernel', missing and no known rule to make it
```

**Comment by LecrisUT** [comment]
Update, after building the kernel and flashing the images, the device is now in a bootloop.

One thing to note is that `recovery.img` was not generated, which I suspect is the reason I cannot return to `fastbootd`
