### ISSUE TITLE
Kirin device not booting

### ISSUE THREAD

**Issue by yehonatan2020** [sonyxperiadev/bug_tracker#785]
SODP
i3113 - Kirin
kernel 4.14
A11
Binaries version 11_4.14_v9a_ganges

**Previously working on**
Was working before, but some major changes were made to multiple directories and now it doesn't boot

**Description**
After building AOSP based on SODP, A11, Sony device i3113 (kirin), no longer boots

**Symptoms**
Device stuck on boot logo; not entering system

**How to reproduce**
Flash SODP to device, wipe data etc, and then try booting

**Additional context**
Add any other context, e.g. upload logs or screenshots about the bug here.

[kirin-not-booting.txt](https://github.com/sonyxperiadev/bug_tracker/files/9542375/kirin-not-booting.txt)

**Comment by ShujathMohd** [comment]
Android 13 supported kernels are 4.19 and 5.4,
4.14 is not supported on a13,(You can still boot a14 on 4.14 but its not supported), please close this bug.

Regarding the bootloop, you need to add the transpower sensor permissions to run as privileged app.
like this https://github.com/sonyxperiadev/device-sony-akatsuki/commit/8e7f4be65f338a0bb1c6ed7ea21748071c6496d7

`09-11 11:01:52.732  1470  1470 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
09-11 11:01:52.732  1470  1470 E AndroidRuntime: java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.sony.transmitpower (/system/system_ext/priv-app/TransPowerSensors): android.permission.CONTROL_INCALL_EXPERIENCE}
`

**Comment by yehonatan2020** [comment]
It's android 11 that I built not A13

**Comment by yehonatan2020** [comment]
Shujath, does the transpower XML file already exist, or does it have to be created?

**Comment by MarijnS95** [comment]
This file should be auto-included from `TransPowerSensors` instead of by every device/platform individually.

**Comment by yehonatan2020** [comment]
Yep, I rebuilt following the advice from Shujath, and it then booted! Seems may be a better choice to have it in the common device folder as opposed to each individual device, or like Marijn says, included in the TransPowerSensors package itself
