### ISSUE TITLE
DSU Loader not working

### ISSUE THREAD

**Issue by IOZZYS** [sonyxperiadev/bug_tracker#787]
**Platform: sagami** 
**Device: Xperia 1 III (pdx215)** 
**Kernel version: 5.4.147** 
**Android version: 12 (61.1.A.11.36)** 
**Software binaries version: ?** 

**Previously working on**
Has never worked

**Description**
In "Settings -> System -> Developer Options -> DSU Loader" when a GSI is selected and the terms of services are accepted, the DSU Loader pop-up closes unexpectedly.
No GSI is being downloaded in the background and no dynamic system update is initiated later. 
I am not a programmer, but I see some things going wrong in the logcat, I just don't know how to fix them.
Many thanks in advance.

[Logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/9638784/Logcat.txt)

I believe this is the problem:
09-24 15:06:32.553  1436  3268 I ActivityTaskManager: START u0 {dat=https://dl.google.com/... flg=0x10000000 cmp=com.android.dynsystem/.VerificationActivity (has extras)} from uid 1000
09-24 15:06:32.553  7591  7591 D AndroidRuntime: Shutting down VM
09-24 15:06:32.554  7591  7591 E AndroidRuntime: FATAL EXCEPTION: main
09-24 15:06:32.554  7591  7591 E AndroidRuntime: Process: com.android.settings, PID: 7591
09-24 15:06:32.554  7591  7591 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.android.dynsystem/com.android.dynsystem.VerificationActivity}; have you declared this activity in your AndroidManifest.xml?
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2091)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1749)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5403)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5361)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:5747)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:5700)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at com.android.settings.development.DSUTermsOfServiceActivity.installDSU(DSUTermsOfServiceActivity.java:35)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at com.android.settings.development.DSUTermsOfServiceActivity.access$000(DSUTermsOfServiceActivity.java:30)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at com.android.settings.development.DSUTermsOfServiceActivity$1.onClick(DSUTermsOfServiceActivity.java:58)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at android.view.View.performClick(View.java:7451)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7425)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at android.view.View.access$3700(View.java:842)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:28690)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:346)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:475)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7889)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-24 15:06:32.554  7591  7591 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)09-24 15:06:32.557  1436  6104 D ActivityManager: New dropbox entry: com.android.settings, system_app_crash, 1bdb3de6-8e04-4e10-bb2e-6e38343f850e
09-24 15:06:32.558  1436  6104 W ActivityTaskManager:   Force finishing activity com.android.settings/.development.DSUTermsOfServiceActivity
09-24 15:06:32.558  1436  8699 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
09-24 15:06:32.563  1701  1701 D clmlib  : Got activities:0x00000008
09-24 15:06:32.563  1701  1701 I JavaDumper:JavaDumperThread: addEvent: system_app_crash@1664024792559.txt processName: com.android.settings
09-24 15:06:32.563  1701  1804 I JavaDumper:JavaDumperThread: Event: system_app_crash@1664024792559.txt TimeStamp: 1664024792
09-24 15:06:32.569  1436  6104 D ActivityTrigger: ActivityTrigger activityPauseTrigger
09-24 15:06:32.574  7591  7591 I Process : Sending signal. PID: 7591 SIG: 9

**Comment by MarijnS95** [comment]
It seems `DynamicSystemInstallationService` provides the missing `VerificationActivity`, any idea if/why that isn't included in your build? Maybe it's a new thing that has to be included explicitly from `common` (or some of the flags were changed that cause it to be skipped), but I used this functionality in the past.

**Comment by Paulbouchara** [comment]
> It seems `DynamicSystemInstallationService` provides the missing `VerificationActivity`, any idea if/why that isn't included in your build? Maybe it's a new thing that has to be included explicitly from `common` (or some of the flags were changed that cause it to be skipped), but I used DSUs on SODP successfully in the past.

He is talking about stock, which doesn't belongs here

**Comment by MarijnS95** [comment]
> He is talking about stock, which doesn't belongs here

Ah I hadn't spotted that detail in the report yet (skimming concluded the version might have been listed for baseband, relevant in case we're hunting firmware bugs) but then this should just be closed as off-topic instead.

**Comment by Yaroslav285** [comment]
Hello @IOZZYS, Try to update your DSU app with a newer version from here. https://www.apkmirror.com/apk/sony-mobile-communications-inc/dynamic-system-updates-29/dynamic-system-updates-29-12-release/dynamic-system-updates-12-8-android-apk-download/

It started asking for installation on my Xperia 1 II. But still, I have no luck running any of the images proposed by Google in "Developer settings".
