### ISSUE TITLE
[Nagara][pdx224] Bootloop on Android 13 when using 64.1.A.0.869 base

### ISSUE THREAD

**Issue by faenil** [sonyxperiadev/bug_tracker#794]
**Platform:** Nagara
**Device:** pdx224 (Xperia 5 IV)
**Kernel version:** 5.10
**Android version:** `android-13.0.0_r30`
**Software binaries version:** `64.1.A.0.869` + `SW_binaries_for_Xperia_Android_13_5.10_v1b_nagara.zip`

**Previously working on**
Using `64.0.H.4.18` as a base leads to a successful boot.

**Description**
AOSP does not boot on pdx224 using the latest (`64.1.A.0.869`) official FW, released end of Feb 2023, as base.
I was able to boot it starting from the latest FW available on Emma, i.e. Android 12 based `64.0.H.4.18`
When I do the whole procedure starting off `64.1.A.0.869`, it goes into a bootloop.
Details below.

Source code used:

- Kernel source is untouched, just rebuilt via `build-clang-shared.sh` (prebuilt kernel for this device is not yet released)
- Nagara device repo is basically `t-mr1` branch plus https://github.com/sonyxperiadev/device-sony-nagara/compare/t-mr1...MarijnS95:device-sony-nagara:t-mr1
- AOSP branch `android-13.0.0_r30`, repo_update'd and a2dp patches applied (see bullet list below)
  - undid https://github.com/sonyxperiadev/repo_update/commit/3f90fdcb2f8c723e3e8f981c976d7e8424719969 
  - applied the [device-sony-common](https://github.com/sonyxperiadev/device-sony-common/pull/899) build fix
  - applied the [a2dp device PR](https://github.com/sonyxperiadev/device-sony-nagara/commit/55f46299561c389e64f0ff55ce25dc01e84ce2af)

The target is `-eng` variant

**Symptoms**
Device shows kernel log and after a few seconds reboots. Rinse and repeat :)

**How to reproduce**
- Lock bootloader
- Flash latest Emma FW for pdx224 (`64.0.H.4.18`)
- Upgrade 3-4 times, until you reach `64.1.A.0.869`
- Reboot into fastboot mode
- `fastboot oem unlock <code>`
- Following the [official flashing guide](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-13#tutorial-step-7), issue `fastboot erase metadata`
```
Erasing 'metadata'                                 FAILED (remote: 'Erasing is not allowed for partition
')
fastboot: error: Command failed
```
- Following the flashing guide steps, `fastboot reboot fastboot`
The device reboots, then shows a quick "Erasing..." screen, then reboots again, and it performs factory reset
- From the wizard, turn off, go to fastboot mode, issue `fastboot reboot fastboot` again (this time the device enters userspace fastboot)
-flash OEM binary `fastboot flash oem SW_binaries_for_Xperia_Android_13_5.10_v1b_nagara.img`, again, post factory reset
- Flash all partitions
- Press pwr button to select "Reboot now" on fastboot menu

At this point the device tries to boot, shows kernel log (see screenshot) and after a few seconds it reboots.
It does so in a never ending loop (I let it reboot 5 times, in this particular instance, before forcing the device off by holding vol up + pwr buttons).

`fastboot reboot recovery` doesn't help. Same reboot loop.

**Additional context**
![IMG_20230226_173547](https://user-images.githubusercontent.com/795435/222916429-44779059-9b6a-4ade-abb6-88c645e60569.jpg)

**Comment by jerpelea** [comment]
please use the tested FW 64.0.H.4.18 until the issue it fixed

**Comment by jerpelea** [comment]
@Thaodan new Murray SW has been released in Flashtool

**Comment by Thaodan** [comment]
> @Thaodan new Murray SW has been released in Flashtool

Which one are you referring too? I flashed XQ-CC54 65.0.A.0.1185 GLOBAL-A4 User-Live COM CustomerId(S20000517) no change. 
There's also `XQ-CC54 65.1.A.5.50 GLOBAL-A4 User-Live COM CustomerId(S20000517)`.

**Comment by jerpelea** [comment]
XQ-CC54 65.1.A.5.50 - Android 13
XQ-CC54 65.0.A.0.1185 - Android 12

**Comment by Thaodan** [comment]
Which one of those should I flash? I got a boot loop on XQ-CC54 65.1.A.5.50. Build date Jun 17 18:07, android-13.0.0_r30.

**Comment by jerpelea** [comment]
during the bringup the device was flashed with  65.0.A.0.1185

**Comment by Thaodan** [comment]
> during the bringup the device was flashed with 65.0.A.0.1185

That's what I've flashed now. I still get a bootloop.

**Comment by bartcubbins** [comment]
Fixed in
https://github.com/sonyxperiadev/kernel/pull/2592
https://github.com/sonyxperiadev/kernel-defconfig/pull/138
