### ISSUE TITLE
[Tama][H8416] XZ3 4.19 AOSP 13 OEM v2 && v3 ; Completely unresponsive after loader post, logcat provided

### ISSUE THREAD

**Issue by project-two-five-zero-one** [sonyxperiadev/bug_tracker#798]
Platform: Tama 
Device: XZ3 
Kernel version: 4.19 
Android version: AOSP 13 
Software binaries version: oem v2 && v3

Description:
Title of the bug sums up the issue. After the loader boots the kernel the device appears as if it is off (LED is off and cannot be switched on, notification lights do not blink, not a blip from the speakers, etc.); apparently it is attempting to mount the partitions as the kernel is responsive via adb and I pulled a logcat - > [error.LOG](https://github.com/sonyxperiadev/bug_tracker/files/11724713/error.LOG)

**Comment by MarijnS95** [comment]
Note that the display on XZ3 specifically will run very rough and not survive a panel off -> on. It is being worked on.

**Comment by project-two-five-zero-one** [comment]
Will there be new oem binaries when the issue is solved/resolved? My only interest with kernel 4.19 is building LOS20, which I know is quite a bit of work; is that possible with the current state of the kernel (assuming not)?

**Comment by MarijnS95** [comment]
I only know that 4.14 used to work fine™ on Tama. Afaik individual HALs and device trees in this project have already migrated to 4.19 so it's probably hard to go back, unless building Android 12?

@bartcubbins has been working on the migration, he should be better able to answer your questions.

**Comment by bartcubbins** [comment]
I will send several PRs with a solution within a few days

**Comment by project-two-five-zero-one** [comment]
Has there been any progress with kernel 4.19 and the binaries; or is it going to be ditched, instead progressing towards something like what phodina is currently developing?

**Comment by MartinX3** [comment]
https://github.com/sonyxperiadev/kernel/pull/2563

If this PR fixed it, please close the issue. :)

**Comment by MarijnS95** [comment]
@project-two-five-zero-one what's @phodina developing?

**Comment by project-two-five-zero-one** [comment]
@MarijnS95 👎🏼 , https://github.com/sonyxperiadev/bug_tracker/issues/799#issuecomment-1621042133

**Comment by MarijnS95** [comment]
@project-two-five-zero-one what's the thumbs-down for?

I'm aware that @phodina is creating a pmOS configuration that puts all our/my mainline work on the Tama platform and various subsystems to use, which is great to let the wider Sony Tama community get a taste of our mainline dream.

**Comment by phodina** [comment]
> [sonyxperiadev/kernel#2563](https://github.com/sonyxperiadev/kernel/pull/2563)
> 
> If this PR fixed it please close the issue. :)

I'll check if any of the commits might help with the display panel

**Comment by MarijnS95** [comment]
Looks like the display is working now and survives a power cycle, thanks @bartcubbins! The device is still slow and sluggish which might be dexing, bad/lacking scaling, or typical downstream struggles elsewhere.

To everyone else, note that performance is locked to MAX in https://github.com/sonyxperiadev/kernel/pull/2563/commits/81f3601f2108e820ed56714d6e62f360bc1beea2 so don't expect the greatest battery/thermals :joy:

**Comment by phodina** [comment]
> 

Should this option be also enabled on the mainline kernel?

**Comment by MarijnS95** [comment]
@phodina mainline is a totally different beast, there are no hacks like the "userspace libdisplayqos" referenced by that commit :tada: 

(The timing/clock calculations are still wrong though... but less so)
