### ISSUE TITLE
[LOIRE] [ALL] AOSP 6.0.1 build broken

### ISSUE THREAD

**Issue by vladimir-zahradnik** [sonyxperiadev/bug_tracker#8]
**Platform:** SoMC Loire
**Device:** ALL
**Kernel version:** 3.10.84
**Android version:** android-6.0.1_r81

**Description**
When I try to build latest revision of AOSP 6.0.1, build eventually fails. I followed official build [instruction guide][marshmallow-build-instructions]. Apparently build script is trying to create a directory ```out/target/product/suzu/system/vendor/firmware/``` for which was already created a symlink. Because of that make ends with an error.

Most probably this issue is related to latest commits in [device-sony-common][device-sony-common], starting with commit, which [adds symlink for /vendor/firmware][symlink-vendor-firmware]. When I check my build directory I can see that ```system/vendor/firmware``` symlink is created.

```sh
[hyperion@Latitude vendor]$ pwd
/srv/git/android-sources/xperia-kestra-6.0.1/out/target/product/suzu/system/vendor
[hyperion@Latitude vendor]$ ls -la
celkom 4
drwxr-xr-x 1 hyperion hyperion  44 okt 19 11:15 .
drwxr-xr-x 1 hyperion hyperion  96 okt 18 13:33 ..
drwxr-xr-x 1 hyperion hyperion 320 okt 18 12:11 bin
drwxr-xr-x 1 hyperion hyperion  52 okt 18 12:11 etc
lrwxrwxrwx 1 hyperion hyperion  13 okt 19 11:15 firmware -> /odm/firmware
drwxr-xr-x 1 hyperion hyperion 486 okt 18 10:20 lib
drwxr-xr-x 1 hyperion hyperion 486 okt 18 10:20 lib64
[hyperion@Latitude vendor]$
```

This should not happen as there is a check for loire platform:
```make
ifneq ($(filter loire tone yoshino,$(PRODUCT_PLATFORM)),)
...
endif
```

Hence I suspect that PRODUCT_PLATFORM variable is not set for some reason and therefore code to create symlink is executed. If there's a way how I can print this variable during build, please let me know.

Also I can see that all conditional expressions are inside following conditional, like this:
```make
ifneq ($(filter yukon rhine shinano kanuti kitakami loire,$(PRODUCT_PLATFORM)),)
...
ifneq ($(filter loire tone yoshino,$(PRODUCT_PLATFORM)),)
endif
endif
```

Is this intended behavior or an error? You already check in first conditional that target platform is not loire and subsequently you do this in other conditions as well... For instance if I was building for ```rhine``` platform, no code would be executed at all. I created a [pull request][pull-request] for this.

**Log**
```sh
Install: out/target/product/suzu/system/vendor/bin/tad_static
Install: out/target/product/suzu/system/vendor/etc/firmware//libpn547_fw.so
Install: out/target/product/suzu/system/vendor/firmware/a530_gpmu.fw2
Install: out/target/product/suzu/system/vendor/firmware/a530_pfp.fw
mkdir: nie je možné vytvoriť adresár `out/target/product/suzu/system/vendor/firmware/': Súbor existuje
make: *** [build/core/base_rules.mk:560: out/target/product/suzu/system/vendor/firmware/a530_gpmu.fw2] Chyba 1
make: *** Čeká se na nedokončené úlohy…
Install: out/target/product/suzu/system/vendor/firmware/a530_pm4.fw
Install: out/target/product/suzu/system/vendor/firmware/a530_zap.b00
mkdir: nie je možné vytvoriť adresár `out/target/product/suzu/system/vendor/firmware/': Súbor existuje
make: *** [build/core/base_rules.mk:560: out/target/product/suzu/system/vendor/firmware/a530_pfp.fw] Chyba 1
mkdir: nie je možné vytvoriť adresár `out/target/product/suzu/system/vendor/firmware/': Súbor existuje
make: *** [build/core/base_rules.mk:560: out/target/product/suzu/system/vendor/firmware/a530_pm4.fw] Chyba 1
mkdir: nie je možné vytvoriť adresár `out/target/product/suzu/system/vendor/firmware/': Súbor existuje
make: *** [build/core/base_rules.mk:560: out/target/product/suzu/system/vendor/firmware/a530_zap.b00] Chyba 1

#### make failed to build some targets (54:02 (mm:ss)) ####
```

**How to reproduce**
Follow [official build instructions][marshmallow-build-instructions] for Android 6.0.1.
- Set up AOSP build for target aosp_f5121-userdebug (suzu)
- Start building

Build should fail with mentioned error.

[marshmallow-build-instructions]: https://developer.sonymobile.com/open-devices/aosp-build-instructions/how-to-build-aosp-marshmallow-for-unlocked-xperia-devices/

[device-sony-common]: https://github.com/sonyxperiadev/device-sony-common/tree/m-mr1

[symlink-vendor-firmware]: https://github.com/sonyxperiadev/device-sony-common/commit/0ce3103d3063ccfe54eec50a19659d144d1e3d61

[pull-request]: https://github.com/sonyxperiadev/device-sony-common/pull/337

**Comment by Bitti09** [comment]
short info: only nougat and Oreo are actively supported by the Sony open devices project at the moment. all other /older Android versions are at  their end of life

**Comment by jerpelea** [comment]
I am sorry for the delay 
We will update the build buide ASAP to provide the latest changes in sync with Xperia X development

**Comment by vladimir-zahradnik** [comment]
Thanks for the info. Anyway if I manage to fix it, do you still accept pull requests?

**Comment by jerpelea** [comment]
the fix is:

rm -r vendor/out/sony/loire-common

than build

**Comment by vladimir-zahradnik** [comment]
Thanks, I will try it out.

**Comment by jerpelea** [comment]
Build guide has been updated
Enjoy

**Comment by vladimir-zahradnik** [comment]
@jerpelea I looked at the updated guide. It's definitely more understandable now.

One more thing. In section "Flash vendor image to your device" you point to [List of devices and resources][resources] page, but for Xperia X it still points to old vendor binaries, e.g. [SW_binaries_for_Xperia_AOSP_M_MR1_3.10_v12_loire.zip][old-vendor-binaries-link].

I was able to find newer binaries only through your [Latest updates][latest-updates] section. If you could update the link also in [List of devices and resources][resources], that would be great.

Thanks!

[resources]: https://developer.sonymobile.com/open-devices/list-of-devices-and-resources/
[old-vendor-binaries-link]: https://developer.sonymobile.com/downloads/software-binaries/software-binaries-for-aosp-marshmallow-6-0-1-loire/
[latest-updates]: https://developer.sonymobile.com/open-devices/latest-updates/
