### ISSUE TITLE
[tama][akari] build error since android-13.0.0_r52

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#800]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.19 
**Android version:** 13
**Software binaries version:** ANDROID_12_4.19_V3A_TAMA

**Previously working on**
`android-13.0.0_r43`

**Description**
Compiling doesn't work after new security patch update `android-13.0.0_r52`

**Symptoms**
Error while compiling.

**How to reproduce**
Compile the code

**Additional context**
```bash
FAILED: out/soong/build.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     -o out/soong/build.ninja --globListDir build --globFile out/soong/globs-build.ninja -t -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.build Android.bp
error: device/google/lynx/powerstats/Android.bp:15:1: module "soong_namespace": namespace device/google/gs201/powerstats does not exist
ninja: build stopped: subcommand failed.
```

**Comment by MarijnS95** [comment]
We untracked `gs201` in https://github.com/sonyxperiadev/local_manifests/pull/141 and will also have to untrack `lynx` now

**Comment by kamsad** [comment]
Hello everyone,  am having the same issue with r52 for 5 IV and wondering how to fix it?

**Comment by MartinX3** [comment]
Fixed with https://github.com/sonyxperiadev/local_manifests/commit/1ce5c9fd9bcee4f740bc3a37eed684bb86bf80b6
