### ISSUE TITLE
AOSP build error : kernel/sony/msm-5.10/common-kernel/nagara/kernel',  missing and no known rule to make it

### ISSUE THREAD

**Issue by revilomm** [sonyxperiadev/bug_tracker#805]
**Platform: AOSP ** 
**Device: 1IV 
**Android version: 13

Hi, I got a problem to build Android 13 for 1 IV

Using build instruction from here:

https://developer.sony.com/open-source/aosp-on-xperia-open-devices/guides/aosp-build-instructions/build-aosp-android-13/

trying to build : lunch aosp_xqct54-userdebug

i got following error:

FAILED: ninja: 'kernel/sony/msm-5.10/common-kernel/nagara/kernel', needed by 'out/target/product/pdx223/kernel', missing and no known rule to make it
11:01:16 ninja failed with: exit status 1

Can you point me to the missing build instruction ?

**Comment by jerpelea** [comment]
Hello 
we are in the process of migrating to a new kernel version. For this reason the prebuilt kernels are not provided.
If you are a developer and you want to help us fix the bugs you can manually build the kernel 
Best regards
Alin

**Comment by revilomm** [comment]
Hi , 
thank you for the fast answer.
Can you please provide a complete build instruction for the kernel , because i tried this as well and got stuck  ?
best regards
Oliver

**Comment by jerpelea** [comment]
Hi Olver, 
if you are not a kernel developer is better to wait for the kernel to be published.
Even if you build the kernel yourself there may be instability issues 
(there is a script in the folder that will build all kernels)
Best regards
Alin

**Comment by revilomm** [comment]
Hi Alin,
Can you please specify which folder and which script .. and yes i  have some experience building kernels  for linux and Android since Android 1.0 ?

https://developer.sony.com/open-source/aosp-on-xperia-open-devices/guides/kernel-compilation-guides/how-to-build-and-flash-a-linux-kernel-for-aosp-supported-devices/how-to-manually-build-the-linux-kernel-for-64-bit-devices/

problem 1:

git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/
does not have any binaries after cloning

problem 2: where to find defconfig file  for Xperia 1 IV

problem 3: which is the right kernel branch 

Can you please provide just the step to produce a working kernel ?

Thanks

**Comment by jerpelea** [comment]
kernel/sony/msm-x.xx/common-kernel/build-kernels-clang.sh in your AOSP tree
you should not try to compile the kernel outside the Android tree

**Comment by revilomm** [comment]
Hi ,
thanks i found it already .. build was successfull
