### ISSUE TITLE
Xperia 1 IV Serial connection

### ISSUE THREAD

**Issue by ivan-j-l4b** [sonyxperiadev/bug_tracker#807]
Hello Sony team, 

Hope that you can help us with setting up UART on phone. 

**Platform:XQ-CT54/pdx223* 
**Device:Xperia 1 IV* 
**Kernel version:5.10.117* 
**Android version:13* 
**Software binaries version:64.1.A.0.857* 

**Not sure has this Previously working**

**Description**
We are trying to get custom ROM on XQ-CT54/pdx223 phone. 
Trying to setup UART for debugging. 
This is done on original Sony ROM. 
We are flowing instructions: 
https://developerworld.wpp.developer.sony.com/open-source/aosp-on-xperia-open-devices/guides/access-uart-ports/
This phone unfortunately is not mentioned in manual. 

**Symptoms**
There is noting on UART. 

**How to reproduce**
Connect UART over SD card port. 

**Additional context**
Is UART over SD card port supported on Xperia 1 IV (XQ-CT54/pdx223) ?

Kind regards, 
Ivan Janković
Software Engineer
L4B Software GmbH
Email:    ivan.j@l4b-software.com
Web:      http://www.l4b-software.com/

**Comment by jerpelea** [comment]
Hi,
the guides should be used only with OSS SW.
I will check ASAP is the device uses USB or SDCard Uart
If you reboot the phone you should see the initial serial output on your minicon app
Best regards
Alin

**Comment by jerpelea** [comment]
Hi @ivan-j-l4b,

the UART information is not disclosed yet for Xperia 1/5IV and 1/5V
This information will be disclosed ASAP
Thanks for your patience

Best regards
Alin
