### ISSUE TITLE
Xperia 1 IV AOSP flashing

### ISSUE THREAD

**Issue by ivan-j-l4b** [sonyxperiadev/bug_tracker#808]
Hello Sony team,

*Platform: XQ-CT54/pdx223
*Device: Xperia 1 IV
*Kernel version: 5.10.117
*Android version: 13

*Not sure if this has previously been  working*

**Description**
We are trying to build and flash AOSP. 
We were following this tutorial:
https://developer.sony.com/open-source/aosp-on-xperia-open-devices/guides/aosp-build-instructions/build-aosp-android-13/
Building was successful, according to the AOSP build system. 

**Symptoms**
```
root@NBK0044U:/home/ivan.j/Work/SoftingVCPI/Sony# fastboot flashall -w
--------------------------------------------
Bootloader Version...: unknown
Baseband Version.....: 
Serial Number........: QV770BS1CQ
--------------------------------------------
Checking 'product'                                 FAILED

Device product is 'pdx223'.
Update requires 'XQ-CT54'.

fastboot: error: requirements not met!
```

**How to reproduce**
```
# update to last Sony FW with Newflasher (XQ-CT54_Customized EU-UK_64.1.A.0.977)

adb reboot bootloader
# blue led - ROM fastboot

fastboot reboot fastboot
# FastbootD

fastboot flashall -w
```

**Additional context**
This topic has already been discussed at: 
https://github.com/sonyxperiadev/bug_tracker/issues/806
Main answer there was: 
https://github.com/sonyxperiadev/bug_tracker/issues/806#issuecomment-1752921088
jerpelea: 
> please follow the steps:
>     1. flash the device using flashtool with the latest Sony FW
>     2. put the device in fastboot (blue led)
>     3. type on the console (on the pc) fastboot reboot fastboot

The issue is that this is exactly the procedure that we are following. 

In #806 there was a confusion. 
It looks like Sony flashing procedure newer worked. 

From https://github.com/sonyxperiadev/bug_tracker/issues/806#issuecomment-1752926412
> That mis-name is intentional, so that fastboot can distinguish between bootloader-fastboot and recovery-fastboot

But, we have situation like Product names are being swapped ?!?

Could you please take a look, what is going on here? 

Kind regards,
Ivan Janković
Software Engineer
L4B Software GmbH
Email: [ivan.j@l4b-software.com](mailto:ivan.j@l4b-software.com)
Web: http://www.l4b-software.com/

**Comment by jerpelea** [comment]
Hi,
I will build and flash the device ASAP
Best regards
Alin

**Comment by ivan-j-l4b** [comment]
Thank you @jerpelea

**Comment by jerpelea** [comment]
@ivan-j-l4b

Can you please flash the partitions using this script which is similar to the build guide:

fastboot reboot fastboot
fastboot wipe-super
fastboot flash boot_a out/target/product/$DEVICE\/boot.img
fastboot flash dtbo_a out/target/product/$DEVICE\/dtbo.img
fastboot flash recovery_a out/target/product/$DEVICE\/recovery.img
fastboot flash --disable-verity --disable-verification vbmeta out/target/product/$DEVICE\/vbmeta.img
fastboot flash --disable-verity --disable-verification vbmeta_system out/target/product/$DEVICE\/vbmeta_system.img
fastboot flash oem_a out/target/product/$DEVICE\/odm.img
fastboot flash vendor_boot_a out/target/product/$DEVICE\/vendor_boot.img

#fastboot flash super out/target/product/$DEVICE\/super.img
fastboot flash product_a out/target/product/$DEVICE\/product.img
fastboot flash system_a out/target/product/$DEVICE\/system.img
fastboot flash vendor_a out/target/product/$DEVICE\/vendor.img
fastboot flash vendor_dlkm_a out/target/product/$DEVICE\/vendor_dlkm.img
fastboot flash system_ext_a out/target/product/$DEVICE\/system_ext.img

fastboot flash userdata out/target/product/$DEVICE\/userdata.img

fastboot erase metadata
fastboot --set-active=a

Best regards
Alin

**Comment by ivan-j-l4b** [comment]
Will try

**Comment by ivan-j-l4b** [comment]
Hello @jerpelea, 

Before trying to flash, 
I wanted to check are all images present. 

2 are missing! 
```
$ ll odm.img
ls: cannot access 'odm.img': No such file or directory

$ vendor_dlkm.img
ls: cannot access 'vendor_dlkm.img': No such file or directory
```

What is your recommendation about this? 

Kind Regards, 
Ivan

**Comment by ivan-j-l4b** [comment]
Hello @jerpelea,

I have done all commands, 
except flashing 2 missing images. 

When I trey to boot I get: 
- Unlocked bootloader warning, 
- Sony logo. 
Then screen god black. 
Phone reboots in about 30s. 

There is no USB devices detected. (dmesg -w)

Kind regards, 
Ivan

**Comment by jerpelea** [comment]
Hi 
it looks like you are missing the odm image 

Please follow step 7 from the guide 
https://developer.sony.com/open-source/aosp-on-xperia-open-devices/guides/aosp-build-instructions/build-aosp-android-13/

NOTE: You can rename the image from step 7 odm.img

Best regards
Alin

**Comment by ivan-j-l4b** [comment]
Let me try

**Comment by ivan-j-l4b** [comment]
Flashed all including odm.img

Same result :(

When I try to boot I get:

    Unlocked bootloader warning,
    Sony logo.
    Then screen goes black.
    Phone reboots in about 30s.

**Comment by jerpelea** [comment]
Hi,
I can flash and test my device tomorrow 
Best regards
ALin

**Comment by ivan-j-l4b** [comment]
Thanks

**Comment by jerpelea** [comment]
why are you using Newflasher instead of Sony Flashtool?

**Comment by ivan-j-l4b** [comment]
Sony Flashtool is not working on Linux
 (Is Sony Flashtool the same as Emma?)

**Comment by jerpelea** [comment]
flashtool is Emma

**Comment by jerpelea** [comment]
@ivan-j-l4b I just tested the PDX223 and it boots to Android

my device was flashed with 64.0.A.4.6 SW
I used the Android 13 build guide and flashed the provided vendor binary
https://developer.sony.com/file/download/software-binaries-for-aosp-android-13-0-kernel-5-10-nagara-v1

**Comment by ivan-j-l4b** [comment]
Thanks

**Comment by ivan-j-l4b** [comment]
Hello @jerpelea , 

As we are building same thing, 
but it does not work on our side, 
could you please provide all commands you have done. 
So we could try to replicate. 
We would appropriate. 

Thanks, 
Ivan

**Comment by ioanasolopa** [comment]
Hi @jerpelea , Can we schedule a meeting with @ivan-j-l4b for this topic? Thanks.

**Comment by jerpelea** [comment]
@ivan-j-l4b 

1. flash your device with flashtool to 64.0.A.4.6
2. follow the build guide step by step upto step 4
3. compile the kernel binary using kernel/sony/msm-5.10/common-kernel/build-kernels-clang.sh 
4. continue with the build guide and flash the device (sing my script or following the step 8 from the guide)

Thanks 
Alin

**Comment by ivan-j-l4b** [comment]
Hello @jerpelea , 

This is what Emma tool let me flash: 
![Emma](https://github.com/sonyxperiadev/bug_tracker/assets/123489662/cd5d4c70-33a4-45fe-ac16-d94ccf33851c)

I now have flashed 64.1.A.0.857
```
XQ-CT54:/ $ getprop ro.system.build.id                                                                                                                                                                                                                                   
64.1.A.0.857
```
How I make Emma tool to download 64.0.A.4.6?

**Comment by jerpelea** [comment]
I am fairly sure that any  64.0.A.4.xx  64.0.A.5.xx should be close to the one flashed on my device

**Comment by ivan-j-l4b** [comment]
OK, will try

**Comment by ivan-j-l4b** [comment]
Was able to install 64.0.A.4.6

I have no Idea how  Emma now gave me 64.0.A.4.6 to download this time

Flashed my build. 

Phone is now booting :) . 

```
pdx223:/ # getprop ro.system.build.id
TQ3A.230901.001
pdx223:/ # 
pdx223:/ # getprop ro.system.build.version.incremental
eng.ivan.j.20231025.094422
```
@jerpelea 
Thanks for help

So, 64.0.A.4.6 needs to be flashed first. 

Closing ticket
