### ISSUE TITLE
[loire] fingerprints database is unreadable by HAL

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#81]
**Platform:** loire
**Device:** suzu, kugo
**Kernel version:** 6.4, 5.7
**Android version:** 8.1, 8.0

**Description**
FPC HAL fails to read the user database for fingerprints.

**Symptoms**
Can't authenticate using already enrolled fingerprints
Can't enroll new fingerprints
Can't remove fingerprints

**How to reproduce**
If this is the first boot after a fully wipe, then fpc will work then, so you can enroll some fingerprints.
After that, reboot, and the issue shall appear.
In logcat, an error will show up about being unable to read user database:
```
02-12 19:25:33.414  7077  7077 E AOSP FPC HAL: Error loading user database: -6
```

**Comment by oshmoun** [comment]
note that this is a different issue than #21

**Comment by jerpelea** [comment]
the fix will be released in vendor v11
