### ISSUE TITLE
AOSP does not build for Xperia 1 V: 'kernel/sony/msm-5.15/common-kernel/yodo/kernel' missing

### ISSUE THREAD

**Issue by ivan-j-l4b** [sonyxperiadev/bug_tracker#813]
Hello Sony team,

**Platform: XQ-DQ54 / pdx234**
**Device: Xperia 1 V**
Kernel version: ?
Android version: 13

Not sure if this has previously been working

**Description**
Building AOSP by Sony instructions fails. 
https://developerworld.wpp.developer.sony.com/open-source/aosp-on-xperia-open-devices/guides/aosp-build-instructions/build-aosp-android-13/

https://github.com/sonyxperiadev/bug_tracker/issues/808#issuecomment-1778632509 point 3

**Symptoms**
`FAILED: ninja: 'kernel/sony/msm-5.15/common-kernel/yodo/kernel', needed by 'out/target/product/pdx234/kernel', missing and no known rule to make it`

**How to reproduce**
```
repo init -u https://android.googlesource.com/platform/manifest -b android-13.0.0_r75
cd .repo
git clone https://github.com/sonyxperiadev/local_manifests
cd local_manifests
git checkout android-13.0.0_r75
cd ../..

repo sync
./repo_update.sh

./kernel/sony/msm-5.10/common-kernel/build-kernels-clang.sh

source build/envsetup.sh
lunch aosp_xqdq54-eng
make -j16
```

**Additional context**
./kernel/sony/msm-5.10/common-kernel/build-kernels-clang.sh
is missing a way to build yodo kernel. 

```
ivan.j@BS~/sony/aosp.1.V/kernel/sony/msm-5.10/common-kernel$ grep -C1 'PLATFORMS' build_shared_vars.sh


PLATFORMS="nagara"

```

Only nagara is supported

```
ivan.j@BS~/sony/aosp.1.V/kernel/sony/msm-5.10/common-kernel$ git show
commit a65b5a86215dcf0d42c58d3d32acd291c289c49c (HEAD -> aosp/K.P.1.0.r1, sony/aosp/K.P.1.0.r1, m/android-13.0.0_r75)
Author: Alin Jerpelea <alin.jerpelea@sony.com>
Date:   Wed Oct 11 14:16:14 2023 +0200

    add Android 14 Clang (build r487747c)
    
    Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>
```

Kind regards, 
Ivan

**Comment by jerpelea** [comment]
Xperia 1V and 5V are not announced as being part of Open Devices (for now it is work in progress). 
When the devices will be ready they will be announced in a blogpost
If you want to help with development the contributions are welcomed

Best regards
Alin
