### ISSUE TITLE
Android 14 build instructions are missing some required tools

### ISSUE THREAD

**Issue by onitake** [sonyxperiadev/bug_tracker#818]
**Platform:** Debian bullseye
**Device:** N/A
**Kernel version:** N/A
**Android version:** 14.0.0_r14
**Software binaries version:** ?

**Previously working on**
~~Has this always been a problem~~, or is it a new issue?

**Description**
The build instructions at https://developer.sony.com/open-source/aosp-on-xperia-open-devices/guides/aosp-build-instructions/build-aosp-android-14/ are missing a bunch of utilities that will make the build fail.

This is the full set that I had to install into a fresh Debian bookworm container:
```
apt-get install -y openjdk-11-jdk bison g++-multilib git gperf libxml2-utils make zlib1g-dev:i386 zip liblz4-tool libncurses5 libssl-dev bc flex curl python-is-python3 zlib1g-dev libelf-dev gnupg procps rsync
```

I'd also have preferred to use a more recent build OS, but OpenJDK 11 is no longer available in Debian bookworm. Any chance that it will build with a more recent JDK?

**Symptoms**
See above.

**How to reproduce**
See above.

**Additional context**
N/A

**Comment by jerpelea** [comment]
@onitake 
please use Ubuntu 20.04 according to our guide or follow the Google instructions
https://source.android.com/docs/setup/start/requirements

**Comment by MartinX3** [comment]
@onitake 
Or try my container to build it
https://github.com/MartinX3-AndroidDevelopment/SCRIPTS_BUILD

**Comment by onitake** [comment]
Thanks for the link - but I disagree that this should be ignored.
The utilities _are_ required, and while you might get lucky and have them installed on the system, this is not guaranteed.
This is particularly true when you use a build container, which comes with a minimal set of software installed.

FWIW, I also tested the container with Ubuntu 20.04 as base image, and the required utilities `rsync` and `gpg` weren't installed either. `procps` was installed, but it can't hurt to add it to the list regardless.

So, I'd like to request the the package list in the documentation is updated, regardless of the OS used.

**Comment by onitake** [comment]
@MartinX3 Thanks for the hint, I'll take a look!
