### ISSUE TITLE
[yoshino] No audio record in low latency usecase

### ISSUE THREAD

**Issue by abioteau** [sonyxperiadev/bug_tracker#82]
**Platform:** Yoshino
**Device:** ALL
**Kernel version:** 4.4
**Android version:** 7.1.1|8.0.0

**Description**
Audio is not recorded in low latency usecase.

**Symptoms**
In low latency usecase, there is a pcm_prepare failure.
> [  112.140638] msm-pcm-dsp-noirq soc:qcom,msm-pcm-dsp-noirq: ASoC: platform prepare error: -5
> [  112.140732]  MSM8998 ULL_NOIRQ: ASoC: prepare FE MSM8998 ULL_NOIRQ failed

**How to reproduce**
Make a call with an VoIP app that uses low latency usecase (ex: Citadel Phone).

**Comment by abioteau** [comment]
@jerpelea Issue is solved with by https://github.com/abioteau/device-sony-yoshino/commit/d986277a24c2486f076b304c6968c42cca1ae123 for yoshino platform and https://github.com/abioteau/device-sony-maple/commit/64b6bc8d02f33701a1909e42bb6e59acefe80559 for maple device only.

**Comment by jerpelea** [comment]
all other devices should have the same fix
thanks for looking into it

**Comment by abioteau** [comment]
@jerpelea poplar and lilac does not need a specific commit as maple because following commits already fix low latency record mixer paths
- https://github.com/sonyxperiadev/device-sony-poplar/commit/d0f6041861d59bfb787dbe60af853efa42762b90
- https://github.com/sonyxperiadev/device-sony-lilac/commit/123dfe8d61a6db212199b323bdcac7815538d0fb

**Comment by jerpelea** [comment]
when the others were updated maple was not forgotten
thanks for looking into this one
