### ISSUE TITLE
I can not replicate the error on Ubuntu 22.04, bare metal

### ISSUE THREAD

**Issue by redfoot0** [sonyxperiadev/bug_tracker#821]
I can not replicate the error on Ubuntu 22.04, bare metal

_Originally posted by @jerpelea in https://github.com/sonyxperiadev/bug_tracker/issues/820#issuecomment-1873953504_
            
Did you also have to create a softlink from libncurses5 to 6 (as 5 is not available anymore)?
Any other hacks you had to do?

**Comment by jerpelea** [comment]
no hacks needed
