### ISSUE TITLE
Xperia 1 V AOSP flashing

### ISSUE THREAD

**Issue by ivan-j-l4b** [sonyxperiadev/bug_tracker#822]
Hello Sony team,

*Platform: XQ-DQ54/pdx237
*Device: Xperia 1 V
*Android version: 13

Not sure if this has previously been working

**Description**
After flashing AOSP phone does not boot

**Symptoms**
After flashing AOSP phone does not boot

**How to reproduce**
XQ-DQ54_Customized EU-UK_67.0.A.4.104
Flash AOSP like: 
https://github.com/sonyxperiadev/bug_tracker/issues/808#issuecomment-1775032522

**Additional context**
On "Xperia 1 IV" Sony's Android 12 is flashed before AOSP is flashed, 
as per https://github.com/sonyxperiadev/bug_tracker/issues/808#issuecomment-1776966824
issue is now that there is no Android 12 for 1 V phone

**Comment by jerpelea** [comment]
adb logcat please

**Comment by ivan-j-l4b** [comment]
[flashing.log.txt](https://github.com/sonyxperiadev/bug_tracker/files/13820306/flashing.log.txt)
![20240103_154646](https://github.com/sonyxperiadev/bug_tracker/assets/123489662/96ee032a-d3b8-47ae-8245-c952d33e463f)

**Comment by ivan-j-l4b** [comment]
# ll
-rw-r--r-- 1 ivan.j domain users        13 Jan  3 13:15 android-info.txt
-rw-r--r-- 1 ivan.j domain users 100663296 Jan  2 13:15 boot.img
-rw-r--r-- 1 ivan.j domain users        72 Jan  2 11:45 build_fingerprint.txt
-rw-r--r-- 1 ivan.j domain users        60 Jan  2 11:45 build_thumbprint.txt
-rw-r--r-- 1 ivan.j domain users    181556 Jan  2 11:44 clean_steps.mk
-rw-r--r-- 1 ivan.j domain users    519475 Jan  2 11:46 dtb.img
-rw-r--r-- 1 ivan.j domain users  25165824 Jan  2 13:01 dtbo.img
-rw-r--r-- 1 ivan.j domain users    416667 Jan  2 13:49 installed-files.json
-rw-r--r-- 1 ivan.j domain users     47151 Jan  2 13:47 installed-files-product.json
-rw-r--r-- 1 ivan.j domain users     16696 Jan  2 13:47 installed-files-product.txt
-rw-r--r-- 1 ivan.j domain users      1715 Jan  2 13:15 installed-files-ramdisk-debug.json
-rw-r--r-- 1 ivan.j domain users       504 Jan  2 13:15 installed-files-ramdisk-debug.txt
-rw-r--r-- 1 ivan.j domain users      1242 Jan  2 13:15 installed-files-ramdisk.json
-rw-r--r-- 1 ivan.j domain users       357 Jan  2 13:15 installed-files-ramdisk.txt
-rw-r--r-- 1 ivan.j domain users     65920 Jan  2 13:31 installed-files-recovery.json
-rw-r--r-- 1 ivan.j domain users     18444 Jan  2 13:31 installed-files-recovery.txt
-rw-r--r-- 1 ivan.j domain users      3017 Jan  2 13:10 installed-files-root.json
-rw-r--r-- 1 ivan.j domain users       658 Jan  2 13:10 installed-files-root.txt
-rw-r--r-- 1 ivan.j domain users    215383 Jan  2 13:53 installed-files-system_ext.json
-rw-r--r-- 1 ivan.j domain users     93193 Jan  2 13:53 installed-files-system_ext.txt
-rw-r--r-- 1 ivan.j domain users    133589 Jan  2 13:49 installed-files.txt
-rw-r--r-- 1 ivan.j domain users    185034 Jan  2 13:40 installed-files-vendor.json
-rw-r--r-- 1 ivan.j domain users     33416 Jan  2 13:26 installed-files-vendor-ramdisk-debug.json
-rw-r--r-- 1 ivan.j domain users     10468 Jan  2 13:26 installed-files-vendor-ramdisk-debug.txt
-rw-r--r-- 1 ivan.j domain users     32943 Jan  2 13:26 installed-files-vendor-ramdisk.json
-rw-r--r-- 1 ivan.j domain users     10321 Jan  2 13:26 installed-files-vendor-ramdisk.txt
-rw-r--r-- 1 ivan.j domain users     61591 Jan  2 13:40 installed-files-vendor.txt
-rw-r--r-- 1 ivan.j domain users      6564 Jan  2 11:46 misc_info.txt
-rw-r--r-- 1 ivan.j domain users  53293624 Jan  2 11:46 module-info.json
-rw-r--r-- 1 ivan.j domain users  57059395 Jan  2 11:46 module-info.json.rsp
lrwxrwxrwx 1 ivan.j domain users        53 Jan  2 14:31 odm.img -> ../SW_binaries_for_Xperia_Android_13_5.15_v2_yodo.img
-rw-r--r-- 1 ivan.j domain users        41 Jan  2 11:45 previous_build_config.mk
-rw-r--r-- 1 ivan.j domain users 289063096 Jan  2 13:47 product.img
-rw-r--r-- 1 ivan.j domain users   3177742 Jan  2 13:15 ramdisk.img
-rw-r--r-- 1 ivan.j domain users  18219053 Jan  2 13:32 ramdisk-recovery.img
-rw-r--r-- 1 ivan.j domain users 104857600 Jan  2 13:32 recovery.img
-rw-r--r-- 1 ivan.j domain users      4976 Jan  2 13:15 super_empty.img
-rw-r--r-- 1 ivan.j domain users 479400156 Jan  2 13:53 system_ext.img
-rw-r--r-- 1 ivan.j domain users 926150972 Jan  2 13:50 system.img
-rw-r--r-- 1 ivan.j domain users  10445124 Jan  2 13:16 userdata.img
-rw-r--r-- 1 ivan.j domain users      8192 Jan  2 13:53 vbmeta.img
-rw-r--r-- 1 ivan.j domain users      4096 Jan  2 13:50 vbmeta_system.img
-rw-r--r-- 1 ivan.j domain users       118 Jan  2 11:46 vendor-bootconfig.img
-rw-r--r-- 1 ivan.j domain users   5341184 Jan  2 13:26 vendor_boot-debug.img
-rw-r--r-- 1 ivan.j domain users 100663296 Jan  2 13:26 vendor_boot.img
-rw-r--r-- 1 ivan.j domain users   5341184 Jan  2 13:26 vendor_boot-test-harness.img
-rw-r--r-- 1 ivan.j domain users 200356000 Jan  2 13:40 vendor.img
-rw-r--r-- 1 ivan.j domain users   4805743 Jan  2 13:26 vendor_ramdisk-debug.img
-rw-r--r-- 1 ivan.j domain users   4577740 Jan  2 13:26 vendor_ramdisk.img
-rw-r--r-- 1 ivan.j domain users   4806131 Jan  2 13:26 vendor_ramdisk-test-harness.img

**Comment by bartcubbins** [comment]
I will recheck DTS, that's all what I can do at this moment

**Comment by jerpelea** [comment]
I see that you have an oem.img file 
what file is that ?

**Comment by ivan-j-l4b** [comment]
SW_binaries_for_Xperia_Android_13_5.15_v2_yodo.img
from
https://developer.sony.com/file/download/software-binaries-for-aosp-android-13-0-kernel-5-15-yodo-v2

**Comment by jerpelea** [comment]
thanks 
what happens when you try fastboot reboot recovery from fastboot

**Comment by ivan-j-l4b** [comment]
Similar. 

> from fastboot
ROM fastboot is only fastboot I can get to (green led)

> what happens when you try fastboot reboot recovery
1- Screen I have sent
2- SONY screen
3- Black screen

No fastboot
No ADB

**Comment by jerpelea** [comment]
thanks for confirming 
we will check if there is any patch missing

**Comment by jerpelea** [comment]
for now please use Android 12 image for 1IV

**Comment by jerpelea** [comment]
please reflash the stock image with flashtool

**Comment by ivan-j-l4b** [comment]
This is what I have on Emma tool: 

![Emma-1V](https://github.com/sonyxperiadev/bug_tracker/assets/123489662/40068caa-fcc4-4b14-aa2e-bbc984ac38f3)

**Comment by ivan-j-l4b** [comment]
Also Emma tool will not let me flash image for "1 IV" on "1 V"

**Comment by jerpelea** [comment]
please try again to flash 1V

**Comment by jerpelea** [comment]
67.0.A.xx.xx is the FW you would like to flash on the device

**Comment by ivan-j-l4b** [comment]
Started: 

![Screenshot_20240103_163221](https://github.com/sonyxperiadev/bug_tracker/assets/123489662/e258cba8-1147-4fe4-80f2-dae02a3bc53a)

**Comment by bartcubbins** [comment]
> The same issue is also on Xperia 1 IV.

Can you share `fastboot getvar all` result from 1IV?

**Comment by ivan-j-l4b** [comment]
# fastboot getvar all
(bootloader) cpu-abi:arm64-v8a
(bootloader) snapshot-update-status:none
(bootloader) super-partition-name:super
(bootloader) is-logical:vbmeta_system_b:no
(bootloader) is-logical:keymaster_b:no
(bootloader) is-logical:recovery_b:no
(bootloader) is-logical:featenabler_b:no
(bootloader) is-logical:tzxflattest_a:no
(bootloader) is-logical:tzxflattest_b:no
(bootloader) is-logical:vendor_boot_a:no
(bootloader) is-logical:qupfw_b:no
(bootloader) is-logical:uefi_a:no
(bootloader) is-logical:abl_b:no
(bootloader) is-logical:vbmeta_b:no
(bootloader) is-logical:tz_b:no
(bootloader) is-logical:vendor_boot_b:no
(bootloader) is-logical:vm-bootsys_a:no
(bootloader) is-logical:boot_b:no
(bootloader) is-logical:shrm_a:no
(bootloader) is-logical:tz_a:no
(bootloader) is-logical:featenabler_a:no
(bootloader) is-logical:dtbo_b:no
(bootloader) is-logical:aop_config_b:no
(bootloader) is-logical:oem_b:no
(bootloader) is-logical:dsp_b:no
(bootloader) is-logical:sda:no
(bootloader) is-logical:xbl_config_a:no
(bootloader) is-logical:aop_config_a:no
(bootloader) is-logical:multiimgoem_a:no
(bootloader) is-logical:imagefv_b:no
(bootloader) is-logical:vm-bootsys_b:no
(bootloader) is-logical:xbl_b:no
(bootloader) is-logical:hyp_b:no
(bootloader) is-logical:multiimgoem_b:no
(bootloader) is-logical:init_boot_b:no
(bootloader) is-logical:sdb:no
(bootloader) is-logical:userdata:no
(bootloader) is-logical:hyp_a:no
(bootloader) is-logical:bluetooth_a:no
(bootloader) is-logical:aop_a:no
(bootloader) is-logical:keymaster_a:no
(bootloader) is-logical:ssd:no
(bootloader) is-logical:bluetooth_b:no
(bootloader) is-logical:aop_b:no
(bootloader) is-logical:devcfg_a:no
(bootloader) is-logical:xbl_ramdump_b:no
(bootloader) is-logical:uefisecapp_b:no
(bootloader) is-logical:imagefv_a:no
(bootloader) is-logical:dsp_a:no
(bootloader) is-logical:oem_a:no
(bootloader) is-logical:modem_a:no
(bootloader) is-logical:cpucp_b:no
(bootloader) is-logical:qweslicstore_b:no
(bootloader) is-logical:devcfg_b:no
(bootloader) is-logical:uefisecapp_a:no
(bootloader) is-logical:misc:no
(bootloader) is-logical:init_boot_a:no
(bootloader) is-logical:xbl_ramdump_a:no
(bootloader) is-logical:abl_a:no
(bootloader) is-logical:modem_b:no
(bootloader) is-logical:cpucp_a:no
(bootloader) is-logical:qweslicstore_a:no
(bootloader) is-logical:qupfw_a:no
(bootloader) is-logical:shrm_b:no
(bootloader) is-logical:uefi_b:no
(bootloader) is-logical:xbl_config_b:no
(bootloader) is-logical:sdc:no
(bootloader) is-logical:xbl_a:no
(bootloader) is-logical:multiimgqti_a:no
(bootloader) is-logical:multiimgqti_b:no
(bootloader) is-logical:boot_a:no
(bootloader) is-logical:vbmeta_system_a:no
(bootloader) is-logical:recovery_a:no
(bootloader) is-logical:super:no
(bootloader) is-logical:vbmeta_a:no
(bootloader) is-logical:metadata:no
(bootloader) is-logical:dtbo_a:no
(bootloader) is-logical:odm_a:yes
(bootloader) is-logical:odm_b:yes
(bootloader) is-logical:product_a:yes
(bootloader) is-logical:product_b:yes
(bootloader) is-logical:system_a:yes
(bootloader) is-logical:system_b:yes
(bootloader) is-logical:system_dlkm_a:yes
(bootloader) is-logical:system_dlkm_b:yes
(bootloader) is-logical:system_ext_a:yes
(bootloader) is-logical:system_ext_b:yes
(bootloader) is-logical:vendor_a:yes
(bootloader) is-logical:vendor_b:yes
(bootloader) is-logical:vendor_dlkm_a:yes
(bootloader) is-logical:vendor_dlkm_b:yes
(bootloader) battery-soc-ok:yes
(bootloader) battery-voltage:0
(bootloader) off-mode-charge:0
(bootloader) treble-enabled:true
(bootloader) is-userspace:yes
(bootloader) partition-size:vbmeta_system_b:0x10000
(bootloader) partition-size:keymaster_b:0x80000
(bootloader) partition-size:recovery_b:0x6400000
(bootloader) partition-size:featenabler_b:0x20000
(bootloader) partition-size:tzxflattest_a:0x40000
(bootloader) partition-size:tzxflattest_b:0x40000
(bootloader) partition-size:vendor_boot_a:0x6000000
(bootloader) partition-size:qupfw_b:0x14000
(bootloader) partition-size:uefi_a:0x780000
(bootloader) partition-size:abl_b:0x180000
(bootloader) partition-size:vbmeta_b:0x10000
(bootloader) partition-size:tz_b:0x400000
(bootloader) partition-size:vendor_boot_b:0x6000000
(bootloader) partition-size:vm-bootsys_a:0x10625000
(bootloader) partition-size:boot_b:0x6000000
(bootloader) partition-size:shrm_a:0x20000
(bootloader) partition-size:tz_a:0x400000
(bootloader) partition-size:featenabler_a:0x20000
(bootloader) partition-size:dtbo_b:0x1800000
(bootloader) partition-size:aop_config_b:0x80000
(bootloader) partition-size:oem_b:0xC0000000
(bootloader) partition-size:dsp_b:0x8000000
(bootloader) partition-size:sda:0x3B91800000
(bootloader) partition-size:xbl_config_a:0x4B000
(bootloader) partition-size:aop_config_a:0x80000
(bootloader) partition-size:multiimgoem_a:0x8000
(bootloader) partition-size:imagefv_b:0x200000
(bootloader) partition-size:vm-bootsys_b:0x10625000
(bootloader) partition-size:xbl_b:0xF5A000
(bootloader) partition-size:hyp_b:0x800000
(bootloader) partition-size:multiimgoem_b:0x8000
(bootloader) partition-size:init_boot_b:0x800000
(bootloader) partition-size:sdb:0x1000000
(bootloader) partition-size:userdata:0x35E7AA5000
(bootloader) partition-size:hyp_a:0x800000
(bootloader) partition-size:bluetooth_a:0x600000
(bootloader) partition-size:aop_a:0x80000
(bootloader) partition-size:keymaster_a:0x80000
(bootloader) partition-size:ssd:0x2000
(bootloader) partition-size:bluetooth_b:0x600000
(bootloader) partition-size:aop_b:0x80000
(bootloader) partition-size:devcfg_a:0x20000
(bootloader) partition-size:xbl_ramdump_b:0x200000
(bootloader) partition-size:uefisecapp_b:0x200000
(bootloader) partition-size:imagefv_a:0x200000
(bootloader) partition-size:dsp_a:0x8000000
(bootloader) partition-size:oem_a:0xC0000000
(bootloader) partition-size:modem_a:0x28A00000
(bootloader) partition-size:cpucp_b:0x100000
(bootloader) partition-size:qweslicstore_b:0x40000
(bootloader) partition-size:devcfg_b:0x20000
(bootloader) partition-size:uefisecapp_a:0x200000
(bootloader) partition-size:misc:0x100000
(bootloader) partition-size:init_boot_a:0x800000
(bootloader) partition-size:xbl_ramdump_a:0x200000
(bootloader) partition-size:abl_a:0x180000
(bootloader) partition-size:modem_b:0x28A00000
(bootloader) partition-size:cpucp_a:0x100000
(bootloader) partition-size:qweslicstore_a:0x40000
(bootloader) partition-size:qupfw_a:0x14000
(bootloader) partition-size:shrm_b:0x20000
(bootloader) partition-size:uefi_b:0x780000
(bootloader) partition-size:xbl_config_b:0x4B000
(bootloader) partition-size:sdc:0x1000000
(bootloader) partition-size:xbl_a:0xF5A000
(bootloader) partition-size:multiimgqti_a:0x8000
(bootloader) partition-size:multiimgqti_b:0x8000
(bootloader) partition-size:boot_a:0x6000000
(bootloader) partition-size:vbmeta_system_a:0x10000
(bootloader) partition-size:recovery_a:0x6400000
(bootloader) partition-size:super:0x360000000
(bootloader) partition-size:vbmeta_a:0x10000
(bootloader) partition-size:metadata:0x4000000
(bootloader) partition-size:dtbo_a:0x1800000
(bootloader) partition-size:odm_a:0x1743000
(bootloader) partition-size:odm_b:0x0
(bootloader) partition-size:product_a:0x8882F000
(bootloader) partition-size:product_b:0x0
(bootloader) partition-size:system_a:0x36BEE000
(bootloader) partition-size:system_b:0x22A0000
(bootloader) partition-size:system_dlkm_a:0x6B000
(bootloader) partition-size:system_dlkm_b:0x0
(bootloader) partition-size:system_ext_a:0x3254C000
(bootloader) partition-size:system_ext_b:0x0
(bootloader) partition-size:vendor_a:0x70183000
(bootloader) partition-size:vendor_b:0x0
(bootloader) partition-size:vendor_dlkm_a:0x4887000
(bootloader) partition-size:vendor_dlkm_b:0x0
(bootloader) version-vndk:33
(bootloader) partition-type:vbmeta_system_b:raw
(bootloader) partition-type:keymaster_b:raw
(bootloader) partition-type:recovery_b:raw
(bootloader) partition-type:featenabler_b:raw
(bootloader) partition-type:tzxflattest_a:raw
(bootloader) partition-type:tzxflattest_b:raw
(bootloader) partition-type:vendor_boot_a:raw
(bootloader) partition-type:qupfw_b:raw
(bootloader) partition-type:uefi_a:raw
(bootloader) partition-type:abl_b:raw
(bootloader) partition-type:vbmeta_b:raw
(bootloader) partition-type:tz_b:raw
(bootloader) partition-type:vendor_boot_b:raw
(bootloader) partition-type:vm-bootsys_a:raw
(bootloader) partition-type:boot_b:raw
(bootloader) partition-type:shrm_a:raw
(bootloader) partition-type:tz_a:raw
(bootloader) partition-type:featenabler_a:raw
(bootloader) partition-type:dtbo_b:raw
(bootloader) partition-type:aop_config_b:raw
(bootloader) partition-type:oem_b:raw
(bootloader) partition-type:dsp_b:raw
(bootloader) partition-type:sda:raw
(bootloader) partition-type:xbl_config_a:raw
(bootloader) partition-type:aop_config_a:raw
(bootloader) partition-type:multiimgoem_a:raw
(bootloader) partition-type:imagefv_b:raw
(bootloader) partition-type:vm-bootsys_b:raw
(bootloader) partition-type:xbl_b:raw
(bootloader) partition-type:hyp_b:raw
(bootloader) partition-type:multiimgoem_b:raw
(bootloader) partition-type:init_boot_b:raw
(bootloader) partition-type:sdb:raw
(bootloader) partition-type:userdata:raw
(bootloader) partition-type:hyp_a:raw
(bootloader) partition-type:bluetooth_a:raw
(bootloader) partition-type:aop_a:raw
(bootloader) partition-type:keymaster_a:raw
(bootloader) partition-type:ssd:raw
(bootloader) partition-type:bluetooth_b:raw
(bootloader) partition-type:aop_b:raw
(bootloader) partition-type:devcfg_a:raw
(bootloader) partition-type:xbl_ramdump_b:raw
(bootloader) partition-type:uefisecapp_b:raw
(bootloader) partition-type:imagefv_a:raw
(bootloader) partition-type:dsp_a:raw
(bootloader) partition-type:oem_a:raw
(bootloader) partition-type:modem_a:raw
(bootloader) partition-type:cpucp_b:raw
(bootloader) partition-type:qweslicstore_b:raw
(bootloader) partition-type:devcfg_b:raw
(bootloader) partition-type:uefisecapp_a:raw
(bootloader) partition-type:misc:raw
(bootloader) partition-type:init_boot_a:raw
(bootloader) partition-type:xbl_ramdump_a:raw
(bootloader) partition-type:abl_a:raw
(bootloader) partition-type:modem_b:raw
(bootloader) partition-type:cpucp_a:raw
(bootloader) partition-type:qweslicstore_a:raw
(bootloader) partition-type:qupfw_a:raw
(bootloader) partition-type:shrm_b:raw
(bootloader) partition-type:uefi_b:raw
(bootloader) partition-type:xbl_config_b:raw
(bootloader) partition-type:sdc:raw
(bootloader) partition-type:xbl_a:raw
(bootloader) partition-type:multiimgqti_a:raw
(bootloader) partition-type:multiimgqti_b:raw
(bootloader) partition-type:boot_a:raw
(bootloader) partition-type:vbmeta_system_a:raw
(bootloader) partition-type:recovery_a:raw
(bootloader) partition-type:super:raw
(bootloader) partition-type:vbmeta_a:raw
(bootloader) partition-type:metadata:raw
(bootloader) partition-type:dtbo_a:raw
(bootloader) partition-type:odm_a:raw
(bootloader) partition-type:odm_b:raw
(bootloader) partition-type:product_a:raw
(bootloader) partition-type:product_b:raw
(bootloader) partition-type:system_a:raw
(bootloader) partition-type:system_b:raw
(bootloader) partition-type:system_dlkm_a:raw
(bootloader) partition-type:system_dlkm_b:raw
(bootloader) partition-type:system_ext_a:raw
(bootloader) partition-type:system_ext_b:raw
(bootloader) partition-type:vendor_a:raw
(bootloader) partition-type:vendor_b:raw
(bootloader) partition-type:vendor_dlkm_a:raw
(bootloader) partition-type:vendor_dlkm_b:raw
(bootloader) has-slot:vbmeta_system:yes
(bootloader) has-slot:keymaster:yes
(bootloader) has-slot:recovery:yes
(bootloader) has-slot:featenabler:yes
(bootloader) has-slot:tzxflattest:yes
(bootloader) has-slot:vendor_boot:yes
(bootloader) has-slot:qupfw:yes
(bootloader) has-slot:uefi:yes
(bootloader) has-slot:abl:yes
(bootloader) has-slot:vbmeta:yes
(bootloader) has-slot:tz:yes
(bootloader) has-slot:vm-bootsys:yes
(bootloader) has-slot:boot:yes
(bootloader) has-slot:shrm:yes
(bootloader) has-slot:dtbo:yes
(bootloader) has-slot:aop_config:yes
(bootloader) has-slot:oem:yes
(bootloader) has-slot:dsp:yes
(bootloader) has-slot:sda:no
(bootloader) has-slot:xbl_config:yes
(bootloader) has-slot:multiimgoem:yes
(bootloader) has-slot:imagefv:yes
(bootloader) has-slot:xbl:yes
(bootloader) has-slot:hyp:yes
(bootloader) has-slot:init_boot:yes
(bootloader) has-slot:sdb:no
(bootloader) has-slot:userdata:no
(bootloader) has-slot:bluetooth:yes
(bootloader) has-slot:aop:yes
(bootloader) has-slot:ssd:no
(bootloader) has-slot:devcfg:yes
(bootloader) has-slot:xbl_ramdump:yes
(bootloader) has-slot:uefisecapp:yes
(bootloader) has-slot:modem:yes
(bootloader) has-slot:cpucp:yes
(bootloader) has-slot:qweslicstore:yes
(bootloader) has-slot:misc:no
(bootloader) has-slot:sdc:no
(bootloader) has-slot:multiimgqti:yes
(bootloader) has-slot:super:no
(bootloader) has-slot:metadata:no
(bootloader) has-slot:odm:yes
(bootloader) has-slot:product:yes
(bootloader) has-slot:system:yes
(bootloader) has-slot:system_dlkm:yes
(bootloader) has-slot:system_ext:yes
(bootloader) has-slot:vendor:yes
(bootloader) has-slot:vendor_dlkm:yes
(bootloader) security-patch-level:2023-09-01
(bootloader) vendor-fingerprint:Sony/pdx234/pdx234:13/TKQ1.221114.001/1:user/release-keys
(bootloader) hw-revision:0
(bootloader) current-slot:a
(bootloader) serialno:QV7706MAJD
(bootloader) product:pdx234
(bootloader) version-os:13
(bootloader) first-api-level:33
(bootloader) slot-count:2
(bootloader) max-download-size:0x10000000
(bootloader) version:0.4
(bootloader) version-baseband:
(bootloader) secure:yes
(bootloader) variant:NA
(bootloader) dynamic-partition:true
(bootloader) system-fingerprint:Sony/pdx234/pdx234:13/TKQ1.221114.001/1:user/release-keys
(bootloader) version-bootloader:unknown
(bootloader) unlocked:yes
all: 
Finished. Total time: 0.464s

**Comment by ivan-j-l4b** [comment]
Original Sony FW 67.0.A.4.104 flashed: 

![Screenshot_20240104_092119](https://github.com/sonyxperiadev/bug_tracker/assets/123489662/cd5d1bad-d4e1-4709-8684-d0dee5f9bfbe)

getprop
[ro.product.build.id]: [67.0.A.4.104]

Then AOSP is flashed

The same. 
It does not boot :(

**Comment by jerpelea** [comment]
did you sync the code and rebuild the kernel ?

**Comment by ivan-j-l4b** [comment]
yes

repo init -u https://android.googlesource.com/platform/manifest -b android-13.0.0_r75
cd .repo
git clone https://github.com/sonyxperiadev/local_manifests
cd local_manifests
git checkout  android-13.0.0_r75
cd ../..

only_build_for=yodo  ./kernel/sony/msm-5.15/common-kernel/build-kernels-clang.sh

make -j15

**Comment by jerpelea** [comment]
please run repo_update.sh as the build guide specifies and use the script to  keep your tree updated with the latest changes

**Comment by ivan-j-l4b** [comment]
I did. 
Just forget to mention it. 
Updated.

**Comment by jerpelea** [comment]
tested by me and some colleagues 
it works. please retest
