### ISSUE TITLE
Vulkan support is broken on Xperia 10 V (Android 13)

### ISSUE THREAD

**Issue by mlehtima** [sonyxperiadev/bug_tracker#826]
**Platform:** 
**Device:** Xperia 10 V (pdx235/zambezi)
**Kernel version:** 5.4
**Android version:** Android 13
**Software binaries version:** SW_binaries_for_Xperia_Android_13_5.4_v2b_zambezi

**Previously working on**
Probably never worked

**Description**
While testing vulkan support on Sailfish OS I noticed that symlink /vendor/lib64/hw/vulkan.qcom.so points to /odm/lib64/hw/vulkan.qcom.so but the file in odm is named vulkan.adreno.so

**Symptoms**
Vulkan is not working

**How to reproduce**
Try to use vulkan support

**Additional context**
Ways to fix are replacing the symlink with vulkan.adreno.so and setting ro.hardware.vulkan=adreno property or renaming the library in odm release

**Comment by jerpelea** [comment]
on it 
Thanks for reporting it

**Comment by jerpelea** [comment]
please update prop and symlink

**Comment by MarijnS95** [comment]
For the record we set the suffix to `qcom` generically for all devices here:

https://github.com/sonyxperiadev/device-sony-common/blob/56c57b4252ac33d7f29e59991b69090afd2d277c/common-prop.mk#L273-L275

Right above that the EGL is found by the `adreno` suffix though, newer blobs probably tried to consistenize the two.

**Comment by jerpelea** [comment]
please test the latest vendor release

**Comment by lkraav** [comment]
> please test the latest vendor release

Did it work @mlehtima?

**Comment by mlehtima** [comment]
In Android 14 vulkan works now but I think Android 13 is missing this commit https://github.com/sonyxperiadev/device-sony-common/commit/07bab83797d8fc7212bdd3f22e1027b72ca983ec

**Comment by jerpelea** [comment]
vendor v4 will be released ASAP with several fixes
