### ISSUE TITLE
vendor image for android 14

### ISSUE THREAD

**Issue by lingdux** [sonyxperiadev/bug_tracker#827]
**Platform:**
ubuntu 22.04
**Device:** 
xperia 1 v xq-dq54
**Kernel version:**
5.15
**Android version:**
android-14.0.0_r20
**Software binaries version:** 

**Previously working on**
Never worked/first time trying

I successfully built aosp,and then I found only vendor image for android 13.
it's [Software binaries for AOSP Android 13.0– Kernel 5.15- Yodo (v2)]
can I use it on android 14?
if I can't, what should I do?

**Comment by jerpelea** [comment]
Hi 
we are working on a new odm version which should fix the error 
Best regards
Alin

**Comment by bartcubbins** [comment]
> can I use it on android 14?

the only thing I can say is that A13 blobs will not be compatible with A14 due to changes in [Remote Key Provisioning](https://source.android.com/docs/core/ota/modular-system/remote-key-provisioning)
