### ISSUE TITLE
successfully built android13 but no vendor_dlkm.img

### ISSUE THREAD

**Issue by lingdux** [sonyxperiadev/bug_tracker#828]
Platform:
ubuntu 22.04
Device:
xperia 1 v xq-dq54
Kernel version:
5.15
Android version:
android-13.0.0_r75
Software binaries version:

Previously working on
Never worked/first time trying

I successfully built android13, at the last step, I found no vendor_dlkm.img.
what should I do?

**Comment by jerpelea** [comment]
that image can be skipped
