### ISSUE TITLE
Xperia X - Battery drain issue while offline charing via PC charger

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#84]
**Platform:** loire
**Device:** Suzu f5121
**Kernel version:** 4.4.114-g7d4cc83-dirty (built on Feb 19)
**Android version:** 8.1.0
**Firmware version:** v10
**FTF firmware version:** 34.3.A.0.252

**Description**
When connected to offline charge via PC, it seems that the battery is discharging instead of charging. The percentages are correct, after the device is booted up, the same number is shown by the device. 

Apart from the Suzu, I can't test it on other devices with the `loire` platform.

**Symptoms**
Battery status is decreasing, instead of increasing. 

**How to reproduce**
Turn off the device, and then connect it to a PC to charge.

**Comment by jerpelea** [comment]
please connect the cable to the PC 
after 1 min of charging please get the log and attach it 
dmesg | grep battery >charging.txt

**Comment by dimitar10** [comment]
Same on Kagura with latest (27 Feb) prebuilt kernel (and firmware 41.3.A.2.24).

**Comment by kholk** [comment]
I have detected some bad issues with the SDP charging.
This PR should have solved this bug:
https://github.com/sonyxperiadev/kernel/pull/1586

**Comment by jerpelea** [comment]
please retest with a manually compiled kernel

**Comment by jerpelea** [comment]
confirmd on suzu with latest kernel

**Comment by oshmoun** [comment]
tested with a freshly built kernel, the issue still persists

**Comment by jerpelea** [comment]
tested on Android 8.1 _r30 and the bug is solved

@dimitar10  please retest

**Comment by dimitar10** [comment]
The issue is fixed on Suzu devices running Android 8.1 _r30. The device was flashed with the latest Sony firmware available via the Emma Flashtool, and then flashed the latest 8.1 _r30 , following the instructions mentioned previously in the discussion.

Tested with:
- regular front mount USB port on a PC case
- regular USB port on a laptop

Additional testing with wall chargers:
- 1.5 A regular 
- 2.0 A quick-charge-cabable

show that offline charging works.
