### ISSUE TITLE
Building AOSP 13 for nagara fails today with Conflicting major version: 2.5 (from device/sony/common/vintf/manifest.xml) vs. 2.5 (from device/sony/common/vintf/android.hardware.camera.provider.xml)

### ISSUE THREAD

**Issue by b100dian** [sonyxperiadev/bug_tracker#846]
**Platform:** nagara
**Device:** pdx224 (5 IV)
**Kernel version:** 5.15 (prebuilt)
**Android version:** 13
**Software binaries version:**  

**Previously working on**
Has this always been a problem, or is it a new issue?

This probably worked before https://github.com/sonyxperiadev/device-sony-common/commit/c49b13e1df1050fddde769d8deb96769e0e7b41b 

**Description**

`lunch aosp_xqcq54-userdebug` followed by `make -j$(nproc)` produces a build error in about an hour

**Symptoms**
```
[ 30% 52385/172107] build out/target/product/pdx224/gen/ETC/vendor_manifest.xml_intermediates/manifest.xml
FAILED: out/target/product/pdx224/gen/ETC/vendor_manifest.xml_intermediates/manifest.xml
/bin/bash -c "BOARD_SEPOLICY_VERS=33.0  PRODUCT_ENFORCE_VINTF_MANIFEST=true     PRODUCT_SHIPPING_API_LEVEL=27   out/host/linux-x86/bin/assemble_vintf -o out/target/product/pdx224/gen/ETC/vendor_manifest.xml_intermediates/manifest.xml           -i device/sony/nagara/vintf/android.hardware.security.keymint-service-qti.xml:device/sony/nagara/vintf/vendor.qti.hardware.qseecom_v1.0.xml:device/sony/common/vintf/manifest.xml:device/sony/common/vintf/vendor.nxp.nxpnfc.xml:device/sony/common/vintf/android.hardware.secure_element_ds.xml:device/sony/common/vintf/vendor.qti.hardware.dsp.xml:device/sony/common/vintf/android.hw.qcradio_ds.xml:device/sony/common/vintf/vendor.hw.radio_ds.xml:device/sony/common/vintf/vendor.hw.qtiradio_ds.xml:device/sony/common/vintf/android.hardware.radio.config.xml:device/sony/common/vintf/vendor.hw.radio.ims.xml:device/sony/common/vintf/vendor.hw.radio.internal.xml:device/sony/common/vintf/vendor.hw.radio.uceservice.xml:device/sony/common/vintf/vendor.hw.imsservices.xml:device/sony/common/vintf/vendor.hw.dataservices.xml:device/sony/common/vintf/vendor.qti.qesdhal.xml:device/sony/common/vintf/vendor.somc.modem.xml:device/sony/common/vintf/vendor.hw.cneservices.xml:device/sony/common/vintf/android.hardware.vibrator_v1.0.xml:device/sony/common/vintf/vendor.qti.hardware.audio.xml:device/sony/common/vintf/android.hardware.camera.provider.xml"
File "device/sony/common/vintf/android.hardware.camera.provider.xml" cannot be added: HAL "android.hardware.camera.provider" has a conflict: Conflicting major version: 2.5 (from device/sony/common/vintf/manifest.xml) vs. 2.5 (from device/sony/common/vintf/android.hardware.camera.provider.xml). Check whether or not multiple modules providing the same HAL are installed.
23:00:34 ninja failed with: exit status 1

```

**How to reproduce**

Follow Android 13 build steps for Xperia 5 IV

**Additional context**

Reverting https://github.com/sonyxperiadev/device-sony-common/commit/c49b13e1df1050fddde769d8deb96769e0e7b41b seems to make the build continue

**Comment by bartcubbins** [comment]
I'm currently working on A14/15 patches and will fix this once I finish it

**Comment by rinigus** [comment]
There is interest in getting AOSP13 working only if there are blobs that work with it. Currently there is no gsm nor camera in nagara aosp13 blobs making functionality rather limited. So, if newer blobs will be AOSP14 only, the interest in getting AOSP13 up and running is rather limited as well :) .

**Comment by jerpelea** [comment]
@rinigus  
the telephony should work on Android 13 if the vintf is adjusted for the new radio

**Comment by rinigus** [comment]
vintf misconfiguration runs in the several issues over here. Its a new topic for me and I would have to read up on it. Hopefully, then I can help with it too.

**Comment by bartcubbins** [comment]
@jerpelea please update the AOSP 14 guide to at least r62 or higher. Then I can send patches that will be valid for A14 and A15 at the same time, otherwise we will have to do double work (if we stay at <r62 it will bring us more headaches). Also we will need to update the part of the guide responsible for selecting the target in accordance with the latest changes
https://source.android.com/docs/setup/build/building#choose-a-target

**Comment by jerpelea** [comment]
@bartcubbins 
our new targets are 

Xperia 1 II
lunch aosp_xqat52-ap1a-userdebug
Xperia 1 III
lunch aosp_xqbc52-ap1a-userdebug
Xperia 1 IV
lunch aosp_xqct54-ap1a-userdebug
Xperia 1 V
lunch aosp_xqdq54-ap1a-userdebug


Xperia 10 II
lunch aosp_xqau52-ap1a-userdebug
Xperia 10 III
lunch aosp_xqbt52-ap1a-userdebug
Xperia 10 IV
lunch aosp_xqcc54-ap1a-userdebug
Xperia 10 V
lunch aosp_xqdc54-ap1a-userdebug


Xperia 5 II
lunch aosp_xqas52-ap1a-userdebug
Xperia 5 III
lunch aosp_xqbq52-ap1a-userdebug
Xperia 5 VI
lunch aosp_xqcq54-ap1a-userdebug
Xperia 5 V
lunch aosp_xqde54-ap1a-userdebug

**Comment by rinigus** [comment]
@jerpelea, I think starting from r5x targets had ap2a. At least I couldn't build with ap1a when testing recently on r55

**Comment by bartcubbins** [comment]
@rinigus Yes[1], that's exactly why r62+ would allow us to avoid such confusion and use trunk_staging as Google itself uses everywhere
[1] https://android.googlesource.com/platform/build/release/+/refs/tags/android-14.0.0_r55/aconfig/

**Comment by b100dian** [comment]
I'm closing this issue for the merge that landed fixes the build - thanks all for the info and the updates :+1:

**Comment by jerpelea** [comment]
@bartcubbins 

all build targets will use ap2a which is tested and available

Best regards
Alin

**Comment by jerpelea** [comment]
@bartcubbins 
do you have the patches for vintf or should I fix it?
1. Update deprecated HALs to the latest version.
2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 5.
3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 5 where applicable.
4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.: Success

**Comment by bartcubbins** [comment]
@jerpelea sure:) I sent PRs. if I missed something please let me know.
