### ISSUE TITLE
No Software Binaries for Android 14 on 5V

### ISSUE THREAD

**Issue by EisregenHaha** [sonyxperiadev/bug_tracker#849]
**Platform:** yodo
**Device:** Xperia5 V, XQDE-54 (pdx237)
**Kernel version:** 5.15
**Android version:** 14
**Software binaries version:** none because where are they

**Description**
there simply are none for A14 on this site [Link](https://developer.sony.com/open-source/aosp-on-xperia-open-devices/get-started/supported-devices-maintained
)
i found this [issue](https://github.com/sonyxperiadev/bug_tracker/issues/827) in which its said that they are being worked on for 1V but that was back in april soooooooooooooooooooooooooooooooooooooooooooooooooooooooo did i build aosp for nothing or can i just not find them 
**Symptoms**
annoyance idk 

**How to reproduce**
visiting the site ig

**Additional context**
no

**Comment by ziggutas** [comment]
Damn, you're right; I hadn't got as far as looking until now. That's a pity.
Did you manage to get a completed build then?

**Comment by EisregenHaha** [comment]
> Damn, you're right; I hadn't got as far as looking until now. That's a pity. Did you manage to get a completed build then?

yes the build finished but i didnt flash it as yk, without the oem stuff theres no point, it wouldnt boot without the ones for A14

**Comment by bartcubbins** [comment]
At this moment you can boot with A13 blobs. Device will boot.

**Comment by EisregenHaha** [comment]
> At this moment you can boot with A13 blobs. Device will boot.

oh alright thanks. will try once i figure out what images to flash
