### ISSUE TITLE
Build AOSP14 for Xperia5 V error: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix

### ISSUE THREAD

**Issue by ziggutas** [sonyxperiadev/bug_tracker#854]
**Platform:**  yodo
**Device:**  Xperia5 V, XQDE-54 (pdx237)
**Kernel version:** 
**Android version:** android-14_r67
**Software binaries version:** 

**Description**
`ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix: 
    vendor.qti.hardware.camera.aon@1.3::IAONService/aoncameraservice`

Occurs when build is almost complete, 98% or so.

Adding that instance to framework_compatibility_matrix.xml in device/sony/common/vintf/ allows the build to complete but I don't know if that's the correct place for it really.

**How to reproduce**
Follow the guide to build 

**Additional context**
error log: https://pastebin.com/d5pQYy2a

**Comment by MarijnS95** [comment]
The expected solution for this was merged yesterday: https://github.com/sonyxperiadev/device-sony-common/pull/928

Did you sync since that moment?

**Comment by ziggutas** [comment]
Ooof! No I didn't. I'll do that now. Thanks.
