### ISSUE TITLE
Xperia5 V: phone sevice not working on android-14_r67

### ISSUE THREAD

**Issue by ziggutas** [sonyxperiadev/bug_tracker#855]
**Platform:**  yodo
**Device:** Xperia5 V, XQDE-54 (pdx237)
**Kernel version:** 5.15
**Android version:** android-14_r67
**Software binaries version:**  Patched SW_binaries_for_Xperia_Android_13_5.15_v4a_yodo.zip

**Description**
Insert SIM and boot the device and there is not indication that there is SIM in the phone. SIM status in Settings is greyed out and there is no network icon in status bar or pull down settings.

I see that this pretty much duplicates  #847 but that's for aosp13 and I don't know what the etiquette is here. Do I add a "me too for aosp14 Xperia 5 V" comment in that issue and close this one; or do I leave this one open? Or does a fix in 13 automatically result in a fix for 14? Apologies for my ignorance in this matter!

**Additional context**
radio.txt https://pastebin.com/PyycF1Pp

**Comment by EmanuelCN** [comment]
The log is quite self explainatory, you are missing vendor/lib64/vendor.qti.hardware.radio.internal.deviceinfo-V1-ndk.so, try adding it from stock and see how it goes, eventually send new logcat.

**Comment by ziggutas** [comment]
Thanks for the suggestion! I was unable to install aosp14 again even though I seemingly started from the same stock version and followed the same steps from my notes. 

I'm stepping back from this for now  and closing this issue.

**Comment by EisregenHaha** [comment]
btw ziggutas, we got pos working. soon will be usable completely fine. emanuel in this thread built the file. join the xperia telegram if ya wanna be notified when its ready. so far shit like cam isnt working

**Comment by EisregenHaha** [comment]
> btw ziggutas, we got pixel os working. soon will be usable completely fine. emanuel in this thread built the file. join the xperia telegram if ya wanna be notified when its ready. so far shit like cam isnt working

@ziggutas lineageos and rising both booted, i havent published rising yet but you can download lineage in the tg group

**Comment by ziggutas** [comment]
That's great Eren! Thanks for the heads-up.
What's the tg group called exactly? I looked for it last time you mentioned it and could not find it. Still can't.
