### ISSUE TITLE
[suzu] No display at boot

### ISSUE THREAD

**Issue by abioteau** [sonyxperiadev/bug_tracker#86]
**Platform:** loire
**Device:** suzu
**Kernel version:** 5.7_r1
**Android version:** 7.1.1

**Description**
The suzu device needs a specific bootloader version to support partner root key (XCS service), 1299-4841 S1_Boot_MSM8956_LA1.0.1_XCS-12. This bootloader does not display Sony boot screen when partner root key and ROM is installed, so display seems to be not initialized when kernel is launched (display_status=off in kernel command line).

**Symptoms**
Kernel crash at boot [dmesg.txt](https://github.com/sonyxperiadev/bug_tracker/files/1747605/dmesg.txt)

**How to reproduce**
Insert partner root key and flash partner ROM with XCS service.

**Comment by jerpelea** [comment]
I am sorry but the bugtracker is used for AOSP only !

**Comment by abioteau** [comment]
@jerpelea could you just have a look on kernel crash? Perhaps if we solve it, we will also fix the display behaviour.
