### ISSUE TITLE
[loire] intermittent random reboots

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#87]
**Platform:** loire
**Device:** kugo
**Kernel version:** 6.4
**Android version:** 8.1

**Description**
The device randomly reboots. It seems to be related to having an sdcard inserted, at least according to logs, but uncertain.

**Symptoms**
Random reboots ahoy!

**How to reproduce**
Keep the device on long enough, with an sdcard inserted. Not tested with no sdcard inserted.

**Logs**
console-ramoops: https://pastebin.com/sMX9u5bT

**Comment by kholk** [comment]
Cannot reproduce locally.

**Comment by oshmoun** [comment]
it is indeed very rare, especially because it seems to only happen if the device was on for a while ( at least longer than 1 day)

**Comment by jerpelea** [comment]
i am using kugo as my dd and up time 4 days
no reboot here

**Comment by kholk** [comment]
Suzu was manually rebooted yesterday, stayed up for a week, got used for like 1.5/2hrs per day, no issues!
P.S.: 64GB Samsung EVO+ MicroSD

**Comment by jerpelea** [comment]
is there anyone else having reboots?

**Comment by chris42** [comment]
Yes, had a reboot as well, after a few days uptime. Didn't notice it at first, but found my phone back in SIM Lock screen.
Kugo, 8.1, binaries v10

**Comment by mase76** [comment]
I have the same issue with 2 Suzu devices running Omnirom 8.1. I tried formatting the sdcard as storage extension and now as removable storage. The reboots appear in both cases.

**Comment by wandi34** [comment]
Also have the same issue. I have a 128GB Samsung SD card formated as external media drive. suzu, 8.1, binaries v11

**Comment by oshmoun** [comment]
A good lead to the cause of the issue has been found, and is currently under testing.

**Comment by oshmoun** [comment]
this issue should be fixed now with https://github.com/sonyxperiadev/kernel/pull/1595

**Comment by mase76** [comment]
Seems so. No more random reboots here for now.
