### ISSUE TITLE
Xperia XZs - Build sanitized with ASAN address coverage, stuck at boot logo

### ISSUE THREAD

**Issue by jvarg** [sonyxperiadev/bug_tracker#88]
**Platform:** 
ARM64
**Device:** 
keyaki
**Kernel version:** 
default from build guide
**Android version:** 
8.1 newest from build guide

**Description**
Building a ASAN instrumented build (based on the userdebug configuration and also the eng config) as well as flashing it succeeds, but is stuck on boot logo "Android".
Accesing the device with `adb root; adb shell`
is working and i can access logcat.
Interesting bits:
```
09-27 01:15:06.171  3025  3025 F DEBUG   : Build fingerprint: 'Sony/aosp_g8231/keyaki:8.1.0/OPM1.171019.016/jvarg02270428:userdebug/test-keys'
09-27 01:15:06.171  3025  3025 F DEBUG   : Revision: '0'
09-27 01:15:06.172  3025  3025 F DEBUG   : ABI: 'arm64'
09-27 01:15:06.172  3025  3025 F DEBUG   : pid: 3021, tid: 3021, name: xtra-daemon  >>> /odm/bin/xtra-daemon <<<
09-27 01:15:06.172  3025  3025 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
09-27 01:15:06.173  3025  3025 F DEBUG   : Cause: null pointer dereference
09-27 01:15:06.173  3025  3025 F DEBUG   :     x0   0000000000000002  x1   0000007fe17ad548  x2   0000000000000000  x3   0000000000000000
09-27 01:15:06.173  3025  3025 F DEBUG   :     x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0000000000000000
09-27 01:15:06.174  3025  3025 F DEBUG   :     x8   0000000000000000  x9   ffffffffffffffdf  x10  0000000000000000  x11  ffffffffffffffff
09-27 01:15:06.174  3025  3025 F DEBUG   :     x12  0000007fe17ad470  x13  0000007fe17ad4b0  x14  e2e70c1974181772  x15  0000007fe17ad520
09-27 01:15:06.175  3025  3025 F DEBUG   :     x16  0000007aa4f532e8  x17  0000007aa57ef180  x18  0000007aa5a5ca18  x19  0000000000000000
09-27 01:15:06.175  3025  3025 F DEBUG   :     x20  0000007fe17ad548  x21  0000000000000002  x22  000000000000181a  x23  0000007aa583aa4b
09-27 01:15:06.175  3025  3025 F DEBUG   :     x24  0000007aa5a62000  x25  0000007aa6823a40  x26  0000007aa67b63d8  x27  0000001000000001
09-27 01:15:06.176  3025  3025 F DEBUG   :     x28  0000007aa5a62000  x29  0000007fe17ad510  x30  0000007aa57ef1e0
09-27 01:15:06.176  3025  3025 F DEBUG   :     sp   0000007fe17acca0  pc   0000000000000000  pstate 0000000020000000
09-27 01:15:06.187  3026  3026 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 3026 (crash_dump32), pid 3026 (crash_dump32)
09-27 01:15:06.188  3025  3025 F DEBUG   :
09-27 01:15:06.188  3025  3025 F DEBUG   : backtrace:
09-27 01:15:06.189  3025  3025 F DEBUG   :     #00 pc 0000000000000000  <unknown>
09-27 01:15:06.189  3025  3025 F DEBUG   :     #01 pc 00000000000501dc  /system/lib64/libclang_rt.asan-aarch64-android.so (__interceptor_sigprocmask+92)
09-27 01:15:06.189  3025  3025 F DEBUG   :     #02 pc 000000000001d9b4  /system/lib64/libc.so (abort+76)
09-27 01:15:06.190  3025  3025 F DEBUG   :     #03 pc 000000000008ce88  /system/lib64/libclang_rt.asan-aarch64-android.so (__sanitizer::Abort()+60)
09-27 01:15:06.190  3025  3025 F DEBUG   :     #04 pc 0000000000092d40  /system/lib64/libclang_rt.asan-aarch64-android.so (__sanitizer:yahooie()+152)
09-27 01:15:06.190  3025  3025 F DEBUG   :     #05 pc 000000000007e26c  /system/lib64/libclang_rt.asan-aarch64-android.so (__asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long)+284)
09-27 01:15:06.191  3025  3025 F DEBUG   :     #06 pc 0000000000092dc4  /system/lib64/libclang_rt.asan-aarch64-android.so (__sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long)+116)
09-27 01:15:06.191  3025  3025 F DEBUG   :     #07 pc 000000000006e06c  /system/lib64/libclang_rt.asan-aarch64-android.so (InitializeCommonInterceptors()+15476)
09-27 01:15:06.192  3025  3025 F DEBUG   :     #08 pc 0000000000069c70  /system/lib64/libclang_rt.asan-aarch64-android.so (__asan::InitializeAsanInterceptors()+36)
09-27 01:15:06.192  3025  3025 F DEBUG   :     #09 pc 000000000007d8cc  /system/lib64/libclang_rt.asan-aarch64-android.so (__asan::AsanInitInternal()+348)
09-27 01:15:06.192  3025  3025 F DEBUG   :     #10 pc 000000000005054c  /system/lib64/libclang_rt.asan-aarch64-android.so (pthread_mutex_lock+72)
09-27 01:15:06.193  3025  3025 F DEBUG   :     #11 pc 00000000000982a0  /system/lib64/libc.so (jemalloc_constructor+116)
09-27 01:15:06.193  3025  3025 F DEBUG   :     #12 pc 0000000000020b5c  /system/bin/linker64 (__dl__ZL10call_arrayIPFviPPcS1_EEvPKcPT_mbS5_+276)
09-27 01:15:06.193  3025  3025 F DEBUG   :     #13 pc 0000000000020d8c  /system/bin/linker64 (__dl__ZN6soinfo17call_constructorsEv+396)
09-27 01:15:06.194  3025  3025 F DEBUG   :     #14 pc 0000000000020c84  /system/bin/linker64 (__dl__ZN6soinfo17call_constructorsEv+132)
09-27 01:15:06.194  3025  3025 F DEBUG   :     #15 pc 0000000000020c84  /system/bin/linker64 (__dl__ZN6soinfo17call_constructorsEv+132)
09-27 01:15:06.194  3025  3025 F DEBUG   :     #16 pc 0000000000020c84  /system/bin/linker64 (__dl__ZN6soinfo17call_constructorsEv+132)
09-27 01:15:06.195  3025  3025 F DEBUG   :     #17 pc 0000000000020c84  /system/bin/linker64 (__dl__ZN6soinfo17call_constructorsEv+132)
09-27 01:15:06.195  3025  3025 F DEBUG   :     #18 pc 000000000001cc64  /system/bin/linker64 (__dl___linker_init+3196)
09-27 01:15:06.195  3025  3025 F DEBUG   :     #19 pc 0000000000023360  /system/bin/linker64 (_start+4)
09-27 01:15:06.228  3028  3028 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 3028 (crash_dump32), pid 3028 (crash_dump32)
09-27 01:15:06.323  3025  3025 E crash_dump64: unable to connect to activity manager: No such file or directory
09-27 01:15:06.324   655   655 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_27

09-27 01:15:10.870  3042  3042 E zygote64: Could not create image space with image file '/system/framework/boot.art'. Attempting to fall back to imageless running. Error was: Cannot relocate image /system/framework/boot.art to /data/dalvik-cache/arm64/system@framework@boot.art: Failed execv(/system/bin/patchoat --input-image-location=/system/framework/boot.art --output-image-file=/data/dalvik-cache/arm64/system@framework@boot.art --instruction-set=arm64 --base-offset-delta=5959680) because non-0 exit status
09-27 01:15:10.871  3042  3042 E zygote64: Attempted image: /system/framework/boot.art

09-27 01:15:15.173  3318  3318 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 3318 (crash_dump32), pid 3318 (crash_dump32)
09-27 01:15:15.194  3316  3316 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 3316 (android.hardwar), pid 3316 (android.hardwar)
09-27 01:15:15.208  3320  3320 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 3320 (crash_dump32), pid 3320 (crash_dump32)
09-27 01:15:15.241  3322  3322 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 3322 (crash_dump32), pid 3322 (crash_dump32)
09-27 01:15:15.263  3264  3264 F libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xed4e94a0 in tid 3264 (cameraserver), pid 3264 (cameraserver)
```
 

**Symptoms**
Build won't boot to GUI

**How to reproduce**
after the default make process succeeded, enter:
`make -j$(nproc) SANITIZE_TARGET='address coverage'`

**Comment by jerpelea** [comment]
please remove /odm/bin/xtra-daemon from your device and try to boot

**Comment by jvarg** [comment]
@jerpelea thanks for your response, it did not solve the problem. Still stuck on Android booting sequence.
output from `logcat *:W` 
is attached.
[logcat_out.txt](https://github.com/sonyxperiadev/bug_tracker/files/1774615/logcat_out.txt)

**Comment by jerpelea** [comment]
please post a logcat from boot

**Comment by jvarg** [comment]
@jerpelea i attached a logcat output straight from booting up the device. I don't have UART access and hope what i attached is sufficient
[logcat_boot.txt](https://github.com/sonyxperiadev/bug_tracker/files/1775163/logcat_boot.txt)

**Comment by kholk** [comment]
@jvarg To use KASAN/KCOV you should follow the procedure on Google's website: they are explaining how to do that on "generically" Google Pixel. 99.9% of this procedure surely also applies to us.

https://source.android.com/devices/tech/debug/kasan-kcov

**Comment by jvarg** [comment]
@kholk thanks for your response, i followed the guide for fuzzing with libfuzzer, i'm not sure if i have to build a KASAN kernel to do so? For my understanding, the libfuzzer guide describes a instrumented userland (which is what i need). The procedure is working fine on a Nexus 5x so i doubt, that i have to rebuild the kernel. I also tried several builds without the default kernel directory, for a clean rebuild.

**Comment by kholk** [comment]
From what I understand, yes libFuzzer needs KASAN/KCOV support.
I linked the Google page to make you aware of the possibility that we need some different parameters (addresses) for building a good boot image (beware: not kernel image, I'm talking about the Android boot.img!).

If you already tried to play with these, then.... I should be able to play and make a KASAN/KCOV build to check (and hopefully eventually solve) the issue locally on Thursday!

**Comment by jvarg** [comment]
@kholk on the kernel side, i only removed the folder, so that it gets generated at the normal build stage, i haven't compiled an KSAN/KCOV kernel described in the android dev manual.
I did compile Android 8.1 with ASAN santiaizer for a Nexus 5x, also without compiling a KASAN kernel which does not have the issue beeing stuck on bootlogo.
Thanks for your effort!

**Comment by jerpelea** [comment]
The kernel configuration for our devices needs to be configured for KASAN/KCOV

Please add the following lines and recompile the kernel (also please note that most debugging is off by default and you will have to diff pixel kernel config to see what else should be enabled)

CONFIG_KASAN=y
CONFIG_KASAN_INLINE=y
CONFIG_KCOV=y
CONFIG_SLUB=y
CONFIG_SLUB_DEBUG=y

**Comment by kholk** [comment]
Oh. Now I see what you mean. Okay, okay.... Well, as I said, from what I understand you need kernel support for that userspace sanitizers to work as expected...

But. 

Note that, compared to the Nexus/Pixel kernels, our defconfigs have gone under a nice cleanup (all devices, of course) so many debugging things are disabled to prefer a smaller kernel binary giving also more performance to a more debugging friendly one.
Thing is, once we got the devices stable, there was no reason to keep certain debugging enabled as that would be a waste of resources. 

Maybe (and I say maybe, because I didn't actually try) some debugging options are required to get ASAN working without kernel support.
In any case, since you want to actually debug your userspace with ASAN, I'd recommend to enable KASAN support in kernel as shown by Google's developer guide. 

If after enabling this your system still doesn't work as expected, we can dive into that and try to find the source of this issue!

**Comment by jvarg** [comment]
@kholk  @jerpelea Thanks guys! i'll try my luck with a new KASAN kernel this week!

**Comment by jerpelea** [comment]
@jvarg Did you boot it ?

**Comment by jvarg** [comment]
@jerpela had a bit of trouble with my build server setup last week. I'll try a KASAN kernel/build on thursday. I'll report back ASAP then you can close this issue.

**Comment by jerpelea** [comment]
thanks

**Comment by jerpelea** [comment]
updates?

**Comment by jvarg** [comment]
I failed building the KASAN kernel and integrate it in the Xperia build -.-
I guess you can close it, since the procedure should be clear from the android manual.
Will try again on the next release.
Thanks for your help!

**Comment by jvarg** [comment]
That would be awesome!

**Comment by jerpelea** [comment]
tested and works nice 
[    0.000000] kasan: KernelAddressSanitizer initialized

**Comment by jerpelea** [comment]
--- a/arch/arm64/configs/aosp_tone_keyaki_defconfig
+++ b/arch/arm64/configs/aosp_tone_keyaki_defconfig
@@ -35,7 +35,11 @@ CONFIG_BLK_DEV_INITRD=y
 # CONFIG_AIO is not set
 # CONFIG_MEMBARRIER is not set
 CONFIG_EMBEDDED=y
-# CONFIG_SLUB_DEBUG is not set
+CONFIG_KASAN=y
+CONFIG_KASAN_INLINE=y
+CONFIG_KCOV=y
+CONFIG_SLUB=y
+CONFIG_SLUB_DEBUG=y
 # CONFIG_COMPAT_BRK is not set
 CONFIG_PROFILING=y
 CONFIG_JUMP_LABEL=y

**Comment by jerpelea** [comment]
in the platform folder apply the following patch 
```
--- a/PlatformConfig.mk
+++ b/PlatformConfig.mk
@@ -38,13 +38,15 @@ BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4

 BOARD_KERNEL_BASE        := 0x80000000
 BOARD_KERNEL_PAGESIZE    := 4096
-BOARD_KERNEL_TAGS_OFFSET := 0x01E00000
-BOARD_RAMDISK_OFFSET     := 0x02000000
+BOARD_KERNEL_OFFSET      := 0x80000
+BOARD_KERNEL_TAGS_OFFSET := 0x02500000
+BOARD_RAMDISK_OFFSET     := 0x02700000
+BOARD_MKBOOTIMG_ARGS     := --kernel_offset $(BOARD_KERNEL_OFFSET) --ramdisk_offset $(BOARD_RAMDISK_OFFSET) --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)

```

**Comment by ThomasKels** [comment]
@jerpelea @kholk how is it possible to get the correct offsets from the image/device?
is it possible to calculate or how can i transfer this to other devices? in that specific case of course you know but is it possible to get this info from somewhere?
can i grep for the ramdisk header or the kernel tags
