### ISSUE TITLE
Android auto / android wear not pairing correctly

### ISSUE THREAD

**Issue by Paulbouchara** [sonyxperiadev/bug_tracker#89]
Platform: Tone (potentially all)
Device: Kagura
Kernel version: 4.4.118
Android version: 8.1

Description
Android auto/wear doesn't work (Auto tested by me, wear reported on XDA thread)

Symptoms
Android auto triggers the connection phase, and then disable the car mode automatically because of a fail in connection phase
I'll post a pastebin asap

How to reproduce
Try to pair a car on auto or a new watch in wear

**Comment by Paulbouchara** [comment]
https://pastebin.com/yUjBvShm
Pastebin for auto

**Comment by jerpelea** [comment]
We do not support GAPPS or Android Auto on the bugtracker

**Comment by jerpelea** [comment]
I use a Fitbit Smartband and I can't spot any connectivity issues on it
