### ISSUE TITLE
FM Radio

### ISSUE THREAD

**Issue by Gouster4** [sonyxperiadev/bug_tracker#91]
**Platform:tone** 
**Device:kagura** 
**Kernel version:4.4** 
**Android version:8.1** 

**Description**
I know its not bug. But our device does not have FM Radio. Snapdragin 820 does have FM Reciever. I know that stock fw foes not have FM too, but it will be nice to have FM Radio in AOSP. Thanx.

**Comment by jerpelea** [comment]
fmradio will not be enabled on any device

**Comment by Gouster4** [comment]
Ok. Just thinking if you dont want include it.

**Comment by jerpelea** [comment]
there were too many issues in the past caused by FM

**Comment by Gouster4** [comment]
You mean that FM implementation messed up some other functionality?

**Comment by jerpelea** [comment]
just BT

**Comment by Gouster4** [comment]
Oh. Of course Bluetooth is more important than FM. So i agree with this step. But in future when AOSP will be in final state (no fixes needed), You can try to get FM with BT working (as last step).

**Comment by jerpelea** [comment]
The FM for BCM HW needs a different BT driver than the one used now

Please note that for devices that do not have FM Radio in stock Sw there is no possibility to enable the FM in Open Devices

**Comment by jerpelea** [comment]
for Devices that use the QCOM BT HW there may be a possibility to enable FM Radio if this function was present in the stock SW since the needed driver is already used

**Comment by Gouster4** [comment]
Ok. So FM will not come, until good BCM BT driver with FM support will be released. Of course if it will be even released.

**Comment by jerpelea** [comment]
the driver is OSS feel free to port it

**Comment by Gouster4** [comment]
Ok. I will try something. If i will be sucessfull, i will make flashable zip to enable FM for people who wants it even when BT will have issues. 
Thanx for help, and sorry for wasting your time.

**Comment by jerpelea** [comment]
if you port the driver properly you can push the fix and we will consider it
