### ISSUE TITLE
[poplar] Tethering issue

### ISSUE THREAD

**Issue by Rabbit53** [sonyxperiadev/bug_tracker#92]
**Platform:** yoshino
**Device:** poplar
**Kernel version:** 4.4 (prebuilt)
**Android version:** 8.1
**Software binary version:** v10

**Description**
Tethering clients can't accsess the Internet. 

**Symptoms**
Tethering clients can't accsess the Internet. But Users can check ping between cellphone and clients.(Maybe LAN is establish)

**How to reproduce**
Enable Tethering by USB,Wi-Fi or Bluetooth and connect any client.

**Log**
```
02-21 23:57:56.581 I/wificond( 745): New station 00:28:f8:88:49:92 associated with hotspot
02-21 23:57:56.581 I/hostapd ( 4177): wlan0: STA 00:28:f8:88:49:92 IEEE 802.11: associated
02-21 23:57:56.582 I/hostapd ( 4177): wlan0: STA 00:28:f8:88:49:92 IEEE 802.11: associated
02-21 23:57:56.617 I/hostapd ( 4177): wlan0: AP-STA-CONNECTED 00:28:f8:88:49:92
02-21 23:57:56.618 I/hostapd ( 4177): wlan0: STA 00:28:f8:88:49:92 WPA: pairwise key handshake completed (RSN)
02-21 23:57:56.618 I/hostapd ( 4177): wlan0: STA 00:28:f8:88:49:92 WPA: pairwise key handshake completed (RSN)
02-21 23:57:56.669 I/dnsmasq ( 4180): DHCPREQUEST(wlan0) 192.168.43.12 00:28:f8:88:49:92
02-21 23:57:56.670 I/dnsmasq ( 4180): DHCPACK(wlan0) 192.168.43.12 00:28:f8:88:49:92 mypc
02-21 23:57:57.849 D/TelephonyProvider( 1528): subIdString = 1 subId = 1
02-21 23:57:57.850 E/Tethering( 885): [UpstreamNetworkMonitor] ERROR registerMobileNetworkRequest() already registered
```

**Comment by oshmoun** [comment]
just for the sake of thoroughness, tested wifi and bt tethering on loire and tone devices (both ways), and couldn't replicate the issue.
could someone confirm on a yoshino device?

**Comment by jerpelea** [comment]
I tested Lilac and I could not replicate the issue

**Comment by jerpelea** [comment]
This bug can not be replicated
