### ISSUE TITLE
[All] - Android 8.1 - Extended Settings: DRS does not work

### ISSUE THREAD

**Issue by iArvee** [sonyxperiadev/bug_tracker#94]
**Platform:** Yoshino
**Device:** maple
**Kernel version:** default from guide
**Android version:** 8.1

**Description**
The dynamic resolution switch in the extended settings does not work. According to @jerpelea , issue is currently being worked on. However, would just like to add this issue for updates.

**Symptoms**
Upon selecting a resolution, phone will display a black screen. Also the setting is reverted to default upon reboot.

**How to reproduce**
1. Access extended settings.
2. Select a resolution.
3. Notice that the phone will display a black screen. Also notice that upon rebooting of phone, the setting is reverted to default.

Logs:
n/a

**Comment by Paulbouchara** [comment]
@kholk said that the commits are almost ready and one more bug needs to be fixed, just be patient :)

**Comment by kholk** [comment]
I am aware of the current state of DRS and there is new work on it that actually makes it work, however it needs some more (little) cleanup and testing love, even though I'm writing this comment from my Maple in 4k! :)))) 

Expect a solution very soon!

**Comment by Gaijin1** [comment]
Is there an ETA on this? Really looking forward to it on 8.1.

**Comment by Habibster** [comment]
Will the 120Hz also work on the tone devices like the XZ? Also what the guy above me said, any ETA?

**Comment by Paulbouchara** [comment]
It will work on :Loire (suzu), tone (all), Yoshino (all)
No ETA for now
Cheers

**Comment by lonewolfbtown** [comment]
I am also waiting for this fix. Patiently. Pestering the developers Is not going to make them work faster. When it's ready it's ready.

**Comment by jerpelea** [comment]
@kholk

**Comment by Gaijin1** [comment]
For anyone that's been waiting for this fix, I just want to pass on another option. This guy made a blashable boot image for any AOSP 8.1 that forces 4K. There's on 1080p option and the Extended settings are still broken, but it works great for me. https://forum.xda-developers.com/showthread.php?p=76276702

**Comment by Habibster** [comment]
is development on this on a break or something?

**Comment by amakuramio** [comment]
please fix 120 hz, I don't care about 4k, just want 120 hz

**Comment by Gaijin1** [comment]
I'd been slapped down for asking about this once "pestering the developers" according to lonewolfbtown. I haven't asked again after that, but after months with nothing, I just assumed they gave up on it or are just skipping Android 8 altogether and waiting for 9, by which time the XZP will be old and no longer relevant for development and not done then either.  You can use the kernel I linked to in an earlier post, or it looks like the latest Carbon ROM may have a kernel for it, too. Search 4K in the Carbon ROM thread on XDA.

**Comment by lonewolfbtown** [comment]
Lol "slapped down". If you got your feelings hurt from that then you need help snowflake. Xz2 premium came out out yes I'd say there is another big dog now then the xz premium. Thank your for making my day outsider=gaijin. I'm off to bigger sony devices I bid you adoo. Rolf lololololol

**Comment by amakuramio** [comment]
offtopic, nougat has 120hz working but doesn't support exfat, can anyone make a patch for it or guide me how to fix it?

**Comment by kholk** [comment]
The 4K DRS functionality will be restored after the migration to k4.9 will be finished.
We are changing the HALs and it would be useless to redo the work twice.

Have a lil more patience :)

**Comment by amakuramio** [comment]
@kholk thanks, I really got autistic eyes and the AMOLED pwn makes my head hurt so much :)
can't wait :)

**Comment by kholk** [comment]
No problem.

Btw, the panel is IPS, not AMOLED... and... since you have that kind of health issue, you shall understand that:
- In OLED technology, each pixel emits its own light
- In LCD (TFT, IPS, anything else) technology the pixel matrix is lit by an array of LEDs (the.. backlight!).

The refresh rate of the pixel matrix of the LCD technology has nothing to do with the PWM of the backlight so, if you have issues **with the backlight PWM** then raising the display refresh rate will not change anything at all for you!

I'm sorry if that disappoints you but, for your health, I think that it's essential for you to know this.
To learn more about this, please search on Google and learn about the differences between the (*)OLED and LCD technology.

Cheers!

**Comment by amakuramio** [comment]
@kholk Thanks for your reply. I know that Sony uses IPS (LCD) and it causes more eye strain than OLED, AMOLED PWM hurts my eyes the most (Samsung), I tried Nougat 120 hz and my eyes felt less painful, maybe it was just placebo? : /
When I was 12 years old I used to have CRT with refresh rate of 120hz, could play video games for hours without any effect, but after I switched to LCD 60 hz just 1 hour and I got tired of it.
It doesn't seem to be related to glare or blue light (I used glasses, blue light filters, screen protectors without effect...) What do you suggest I should do?

**Comment by kholk** [comment]
The CRT technology (in brief) has a cannon that emits light. In that case, raising the refresh rate will cause more light flashes per second, that's why it felt more comfortable for you.

From a hardware perspective, raising the brightness of an LCD display will raise the PWM frequency of the backlight (in most cases!) for it to "shine more light", but that will also be bad for your eyes in certain conditions.

In any case, I'm not a medic and all I can tell you comes from hardware knowledge. For medical questions, you should definitely refer to your medic.

**Comment by lonewolfbtown** [comment]
Is there any reason or cause from the 4.9 alpha kernel causing the camera apps to not start or be a black screen?

**Comment by jerpelea** [comment]
the camera is not implemented yet on 4.9

**Comment by lonewolfbtown** [comment]
Thanks jerplelea. At least I know im not crazy lol

**Comment by Habibster** [comment]
i think this is my 3rd or 4th time asking across 6 or so months, but any developments? 😅

**Comment by kholk** [comment]
We are working on it.

Please be patient.

**Comment by Habibster** [comment]
Back on my bi-monthly checkup 😅 hows development on 120Hz going?

btw sorry if its feels like i keep asking this alot, might come across as rude. i understand that development is probably tight and there aren't many ppl willing to do this stuff for free (i presume)
but im just curious 👍

**Comment by MartinX3** [comment]
Please wait or the kernel 4.9 migration is finished.:)

**Comment by doh007** [comment]
Sorry if we're asking this "relatively often", but any updates? x)

**Comment by MartinX3** [comment]
I would wait for the new camera framework.
Maaaaaaaaaaaaaaaaaaaaaaaaaaaaybe it is near.
https://github.com/sonyxperiadev/device-sony-common/commit/43b6c5ff7b811291f9003ffdcdcd416e8001d48f

**Comment by jerpelea** [comment]
@doh007 the Android 8 development stopped and the Android 9 is usable
