### ISSUE TITLE
Xperia XA2, XA2 Ultra - No incall sound

### ISSUE THREAD

**Issue by jerpelea** [sonyxperiadev/bug_tracker#96]
**Platform:** Nile
**Device:** XA2, XA2 Ultra
**Kernel version:** 4.4
**Android version:**  8.x

**Description**
during a voicecall there is no sound and no mic 

**Symptoms**
during a voicecall there is no sound and no mic 

**How to reproduce**
dial a number and try to have a coversation

**Comment by luk1337** [comment]
https://github.com/sonyxperiadev/device-sony-nile/pull/15 enables incall sound but volume control doesn't work (yet?)

**Comment by jerpelea** [comment]
incall speaker is still not working

**Comment by jerpelea** [comment]
03-23 14:29:34.653   628   893 D hardware_info: hw_info_append_hw_type : device_name = voice-speaker
03-23 14:29:34.653   628   893 D audio_hw_primary: enable_snd_device: snd_device(10: voice-speaker)
03-23 14:29:34.654   628   893 D audio_route: Apply path: voice-speaker

**Comment by luk1337** [comment]
I think we'd need to have a proper audio calibration for voice-speaker to work properly. The tricks we are using for handset and headset aren't working there.

**Comment by jerpelea** [comment]
we have to use the right device

**Comment by luk1337** [comment]
btw here are logs from stock ~ https://gist.github.com/luk1337/d489f1e4725887b16560f6f914ede57a

**Comment by jerpelea** [comment]
@BuzzBumbleBee

**Comment by pablomh** [comment]
I'm able to have a successful voicecall with XA2 (h4113) albeit without volume control.

**Comment by richardtullberg** [comment]
05-08 12:32:41.653     0     0 E qdsp_cvp_callback: cmd = 0x13198 returned error = 0x1
05-08 12:32:41.653     0     0 E voice_send_cvp_topology_commit_cmd: DSP returned error[ADSP_EFAILED]
05-08 12:32:41.654     0     0 E voice_setup_vocproc: Set topology commit failed err:-131
05-08 12:32:41.654     0     0 E         : setup voice failed

**Comment by jerpelea** [comment]
the fix is merged and the DSP is initialized
https://github.com/sonyxperiadev/device-sony-common/commit/11833ba1d081dfb2a8175150ea7144f6b69d9a5d

next step is routing
