### ISSUE TITLE
Xperia XA2, XA2 Ultra - Unable to connect to any WiFi network

### ISSUE THREAD

**Issue by luk1337** [sonyxperiadev/bug_tracker#97]
**Platform:** Nile 
**Device:** XA2, XA2 Ultra
**Kernel version:** 4.4 
**Android version:**  8.x

**Description**
The phone is unable to connect to any WiFi network.

**Symptoms**
It tries to connect for few seconds and then it times out.

**How to reproduce**
Try to connect to WiFi network, it should disconnect you within few seconds.

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/vendor-qcom-opensource-wlan-qcacld-3.0/pull/8
https://github.com/sonyxperiadev/vendor-qcom-opensource-wlan-fw-api/pull/1
https://github.com/sonyxperiadev/vendor-qcom-opensource-wlan-qca-wifi-host-cmn/pull/2

**Comment by kholk** [comment]
Despite these PRs being a good upgrade for all the devices featuring QCA CLD, these are not solving the Nile connection issues.

They are however necessary to use the latest SDM630 compatible code, as the previous revision was for MSM8998 only.

**Comment by luk1337** [comment]
Fixed.
