### ISSUE TITLE
Xperia XA2, XA2 Ultra - update thermanager

### ISSUE THREAD

**Issue by jerpelea** [sonyxperiadev/bug_tracker#98]
**Platform:** nile
**Device:** XA2,XA2 Ultra
**Kernel version:** 4.4
**Android version:** 8.x

**Description**
TODO: update the thermanager mitigation

**Symptoms**
TODO: update the thermanager mitigation

**How to reproduce**
TODO: update the thermanager mitigation

**Comment by jerpelea** [comment]
@kholk

**Comment by kholk** [comment]
Sure :)))

**Comment by kholk** [comment]
Updated in PRs:
https://github.com/sonyxperiadev/device-sony-discovery/pull/12
https://github.com/sonyxperiadev/device-sony-pioneer/pull/11

Can be closed.
